### ISSUE TITLE
在一些软件中输入异常

### ISSUE THREAD

**Issue by pihao** [rime/weasel#10]
**魔兽世界/Windows8 Metro：**不显示候选框。可以出字，只是没有候选框。
**Chrome下的Google Drive表格：**单击选中单元格时无法输入，必需双击进入编辑状态才能输入。
**Sublime Text 2：**候选框不跟随光标。所有输入法（微软五笔、小鸭五笔等）都存在这个现象，估计这个软件本身在输入法这方面不兼容。

**系统：** Windows 8.1, 64bit
**输入法：** 小狼毫 0.9.29.1

**Comment by LevskiWeng** [comment]
候選框不跟隨光標的情況，當使用Foxmail撰寫郵件正文時也存在。

系統：Windows 7，32bit
輸入法：小狼毫 0.9.30

**Comment by tgmerge** [comment]
Sublime Text 2/3 IME跟随光标的问题可以用一个叫IME Support的插件解决……
https://packagecontrol.io/packages/IMESupport

小狼毫TSF在Metro界面下也不显示候选框。

系统：Windows 8.1，64bit
输入法：小狼毫0.9.30

**Comment by kakaaaluote** [comment]
@tgmerge 还真解决了，多谢！再谢！

**Comment by TomatoFryEggs** [comment]
目前win10貌似又不行了，还有解决方案么？
 @tgmerge @kakaaaluote
