### ISSUE TITLE
在Intelij IDEA下，文字提示框定位不正确

### ISSUE THREAD

**Issue by jccode** [rime/weasel#100]
[描述]  如题，在Intelij IDEA下使用小狼毫输入法进行中文输入。

[期望结果]  文字提示框应该显示在当前光标处。

[实际结果]  文字提示框出现在整个屏幕的左上角。 如下图所示。

![rime_bug](https://user-images.githubusercontent.com/2819095/33534148-a716c0a2-d8e0-11e7-9415-b793ce205e65.png)

**Comment by ijLee** [comment]
这是 IDEA 的问题，可以尝试更改 IDEA 的 jre64/jre32 试试。

**Comment by nameoverflow** [comment]
@ijLee jre 版本是会影响输入法作用吗？

**Comment by ijLee** [comment]
@nameoverflow 有影响。可以尝试使用旧版本的 jre 试试。比如，IDEA-2018.1 使用 jdk1.8.0_162 的 jre，输入法候选框就可以正常显示。我是Windows10系统。

**Comment by nameoverflow** [comment]
@ijLee 感谢提醒，验证了确实在 jdk1.8.0_162 可以正常。

**Comment by jccode** [comment]
jdk1.8.0_162 64位 win7 下，问题依旧。

**Comment by nameoverflow** [comment]
@jccode IME 还是 TSF ？

**Comment by ijLee** [comment]
@jccode 用旧版本的 IDEA 的 jre64 试试。
