### ISSUE TITLE
切换输入法后，能把中英文状态重置成默认设置吗

### ISSUE THREAD

**Issue by iahu** [rime/weasel#1000]
首先，这是一个提问，不是提交 Bug。

几乎每天都会遇到同一个问题，那就是从默认英文输入法切换到 Rime 输入法后，输入的结果是一串英文，然后很无奈地换成中文状态再输入。

其实这个场景很直接，我从默认英文输入法切换到 Rime 的目的就是使用有我想要的 Rime 输入法，一般别于英文的输入法，所以我希望可以实现切换后默认进入中文模式（或者我设置的默认模式）。

我不知道现在的功能是否能支持（配置实在太复杂）。谢谢。

**Comment by fxliang** [comment]
看看你的方案是不是ascii_mode下有reset: 1的情况吧

switches:
  - name: ascii_mode
    states: [ 中, 英 ]

**Comment by iahu** [comment]
这个配置管用，谢谢🙏在 2023年9月28日，19:10，fxliang ***@***.***> 写道：﻿
看看你的方案是不是ascii_mode下有reset: 1的情况吧
switches:

name: ascii_mode
states: [ 中, 英 ]
