### ISSUE TITLE
求助一个AHK、WPS、Rime输入法的问题。

### ISSUE THREAD

**Issue by pessni** [rime/weasel#1002]
**上报前请检查**
- [ 1] 我遇到的问题没有其他人在  里提到过
- [ 1] 我的小狼毫版本于 rime/weasel 下载
- [ 1] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Microsoft Windows  版本22H2(0S内部版本22621.2283)
 - 小狼毫版本: 0.15.0， Github下载。

**描述遇到的问题**
 WPS文档内用Rime输入法（Windows平台的小狼毫）编辑文字（不论输入法状态是中文还是英文），AutoHotKey脚本的部分热键功能无效，请大佬指点问题出在哪里，怎样解决？
WPS和Rime输入法都是官网最新版本。
不起作用的部分热键具体如下：
 
===热键===
;Ctrl + Left
!x:: Send ^{Left}
;Ctrl + Right
!.:: Send ^{Right}
;Ctrl + Baskspace
!z:: Send ^{Backspace}
;Ctrl + Delete
!/:: Send ^{Delete}
;选择当前位置到行首的文字
!y:: Send +{Home}
;选择当前位置到行末的文字
!p:: Send +{End}
;选中该行文字
!k:: Send {Home}+{End}
===热键===

简单总结，情况是：
Rime+AHK+ Office Word，正常。
Windows自带输入法+AHK+WPS，正常。
Rime+AHK+WPS，不正常

 
**其他补充说明**
这两天遇到一个新情况，我觉得是同一个原因。我长期使用Edge/Chrome浏览器的Vimium扩展，但是小狼毫输入法状态下Vimium的快捷键无效，按Shift切换小狼毫为A【英文状态】后，Vimium的快捷键正常工作。

我初步猜测，Windows自带的输入法在没有输入框时自动处于未激活状态，而小狼毫输入法在没有输入框时仍然处于激活状态。
不知道是否是这样，以及是否有什么方法可以解决这个问题。
恳请各位指教，谢谢！

如需要提供其他信息，请回复指明。

**Comment by xntzmk** [comment]
碰到+1，好像是中文输入的时候输入的按键都Vimium C都没有接收到 ，都必须换成英文的

**Comment by a0193143** [comment]
測試了一下，有時有效有時無效
就想到很像之前用腳本在小狼毫上打字太快會有的問題
試著把Send改成SendEvent或是SendPlay，最前面加上`SetKeyDelay 100`模擬正常的按鍵速度就能用了
預設是10ms，小狼毫受不了
Send(Input)不支援SetKeyDelay

**Comment by a0193143** [comment]
具體是哪一個快捷鍵和你的輸入法方案？
我在Firefox、Edge，倉頡五代我會用到的那些都沒有問題

**Comment by pessni** [comment]
> 具體是哪一個快捷鍵和你的輸入法方案？ 我在Firefox、Edge，倉頡五代我會用到的那些都沒有問題

可能你用的是win10。具体可以看下这个issue，https://github.com/rime/weasel/issues/997，我也在里面详细说了。
