### ISSUE TITLE
自定义短语的不是次序数字越小权重越大的吗？

### ISSUE THREAD

**Issue by kidzgy** [rime/weasel#1011]
**上报前请检查**
- [ 没有] 我遇到的问题没有其他人在 issue 里提到过
- [是的 ] 我的小狼毫版本于 rime/weasel 下载
- [是的] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [版本 10.0.17763.1217]
 - 小狼毫版本: [0.15.0] (2023-06-06)

**描述遇到的问题**
简短地描述你所遇到的问题
在编辑custom_phrase.txt时，第三列的数字代表权重，我看网上教程是写着数字越小权重越大排得越靠前，而我在实操的时候却是数字越小权重越小，排得越靠后。

**预期行为**
我觉得数字越大权重越大，一点意义都没有，在其他输入法转化为小狼毫词库的时候，还要将次序特地颠倒，数字就不用代表什么权重不权重，就代表着候选位的顺序就是最直观恰当的体现。

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
![微信截图_20231014005445](https://github.com/rime/weasel/assets/6967810/5cef560b-1459-44a3-bf00-8110cc38c48e)

教程出处：https://zhuanlan.zhihu.com/p/411957994
![微信截图_20231014114806](https://github.com/rime/weasel/assets/6967810/44bdb83d-ef5d-421c-b373-8564400303e5)

**Comment by jhy1234** [comment]
这个教程说错了。数字越大权重才越大，也就越靠前。

**Comment by SogaSuga** [comment]
这个教程写错了。数字越大权重越大，也就越靠前。
