### ISSUE TITLE
输入法设定，”界面风格设定“，无法显示预览

### ISSUE THREAD

**Issue by changzaicl** [rime/weasel#1012]
Actions下面最新版本，“输入法设定” →”界面风格设定“，无法显示预览。
![image](https://github.com/rime/weasel/assets/144407904/178f2b82-f83b-4a82-b07a-ef4767ae1a0a)

**Comment by Techince** [comment]
选中的这个配色是自定义的，制作皮肤的作者需要提供相应的图片才能显示出来。

**Comment by ChihSee-Hsie** [comment]
> 选中的这个配色是自定义的，制作皮肤的作者需要提供相应的图片才能显示出来。

注意到这个问题，所以试了一下。即使是早有图片的预设配色，在最新版本中也一样显示不出来。

**Comment by fxliang** [comment]
是我的锅，少做一张图上去

**Comment by ChihSee-Hsie** [comment]
经试验，似乎现在无论通过修改 weasel.custom 还是通过输入法设定程序都无法更改配色方案。

**Comment by ChihSee-Hsie** [comment]
追加：修改输入方案列表同样不成功。

**Comment by Techince** [comment]
![image](https://github.com/rime/weasel/assets/12376669/1e60a595-60d1-455a-a3da-a602cef08f23)

**Comment by Techince** [comment]
![image](https://github.com/rime/weasel/assets/12376669/0778f6eb-96b5-4e45-9165-7459bbe7a455)

**Comment by changzaicl** [comment]
Actions下面最新版本（2023年10月16日）已经解决此问题。谢谢
