### ISSUE TITLE
最新构建版本中 uniquifier 似乎失效

### ISSUE THREAD

**Issue by ChihSee-Hsie** [rime/weasel#1013]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 22H2 22621.2428
 - 小狼毫版本: 0.15.0.0 ， commit CI # 149

**遇到的问题**
在最新构建版本的 weasel 中，简体模式下会出现重复的候选项，这应当是因为一简对多繁的汉字在 OpenCC 转换之后，没有经过 uniquifier 过滤而造成的。然而在我的设定中包括了加载 uniquifier 的内容，故推测是该组件失效。

![例子：输入「li」的结果](https://github.com/rime/weasel/assets/91021998/c94b08bb-9461-406e-9545-40dc47521f11)

**Comment by fxliang** [comment]
librime关联
