### ISSUE TITLE
【功能请求】通过将 WeaselServer.exe 注册为服务实现高优先级自启动

### ISSUE THREAD

**Issue by d0j1a1701** [rime/weasel#1015]
如题，WallpaperEngine 就采取这种自启方式，几乎可以做到进入桌面后立即启动。建议 Weasel 也添加该功能。

同时注册为服务可以实现崩溃后自动重开，适合输入法后端。

**Comment by linct96** [comment]
支持

**Comment by rebron1900** [comment]
附议

**Comment by fxliang** [comment]
跨session都有问题，跨user问题更多，等风吧

**Comment by d0j1a1701** [comment]
> 跨session都有问题，跨user问题更多，等风吧
（悲）
但是可以作为一个可选功能提供，考虑到大多数 Windows 用户实际上只有一个 user
