### ISSUE TITLE
office 365 的 word 中, 拖动标尺后打字时候选框显示不正常 (闪烁)

### ISSUE THREAD

**Issue by BH2WFR** [rime/weasel#1017]
**操作系统信息**
 - OS 详细版本: Windows 11 22H2
 - office 版本: Microsoft 365 最新版
 - 小狼毫版本: 0.15.0.0,  CI 构建版本 680de26

**描述遇到的问题**
拖动标尺后, 在插入模式下打字会导致候选框闪烁, 无法正常显示; 按 Insert 切换到 覆写模式下正常
小狼毫版本为 **0.15 最新 680de26 主仓库 CI 构建版本**
在之前某个 CI 构建版本中, 此问题得到解决, 但是继续更新后问题再次出现
下图为录屏 (gif)
![Animation1](https://github.com/rime/weasel/assets/60873943/fd1bdac2-f397-42d7-b6bc-988d718475ce)

**Comment by changzaicl** [comment]
我之前反映的问题，估计类似。
“最新action下的版本在word中可以鼠标选字，但是选字后再次输入不显示输入框。盲打后，可以发现刚才的选字是“虚”的，并没有真正输入，只是在word中显示了。”

**Comment by Techince** [comment]
拖动这个滑块后，编辑请求就有很大机率由同步模式转变为异步模式，这会导致候选框在每次按键弹起时消失。
解决的办法就是设一个异步检测标志，在OnKeyUp事件中判断它是为异步时，不执行_UpdateComposition(pContext);
可以试试这个版本：
https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.0-installer_x64.exe
过两天还要再合并梁梁的代码。

**Comment by llpub** [comment]
[Techince](https://github.com/Techince)的说法应该是所有关于闪烁Issues里最接近这个bug本质的。
用了Techince的[weasel-0.15.1.004-installer_x64.exe](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.004-installer_x64.exe)，Word2019拖动标尺终于不闪烁了

**Comment by Techince** [comment]
> [Techince](https://github.com/Techince)的说法应该是所有关于闪烁Issues里最接近这个bug本质的。 用了Techince的[weasel-0.15.1.004-installer_x64.exe](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.004-installer_x64.exe)，Word2019拖动标尺终于不闪烁了。 唯一不足的是C:\Windows\sysWOW64\weasel.dll 被Windows defender报毒，virustotal里也有几家杀软认为是Trojan。这个weasel.dll 被干掉后在企业微信等部分消息软件不能输入，浏览器/Office等大部分软件不受影响。

SysWOW64中的weasel.dll不能被干掉，这个是32位应用程序的输入法模块，64位的输入法模块在System32文件夹下。32位程序只能加载32位的dll，64位加载64位的dll。

**Comment by BH2WFR** [comment]
> > [Techince](https://github.com/Techince)的说法应该是所有关于闪烁Issues里最接近这个bug本质的。 用了Techince的[weasel-0.15.1.004-installer_x64.exe](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.004-installer_x64.exe)，Word2019拖动标尺终于不闪烁了。 唯一不足的是C:\Windows\sysWOW64\weasel.dll 被Windows defender报毒，virustotal里也有几家杀软认为是Trojan。这个weasel.dll 被干掉后在企业微信等部分消息软件不能输入，浏览器/Office等大部分软件不受影响。
> 
> SysWOW64中的weasel.dll不能被干掉，这个是32位应用程序的输入法模块，64位的输入法模块在System32文件夹下。32位程序只能加载32位的dll，64位加载64位的dll。

您好, 我尝试使用了您的修改版本, 但是好像在onenote上工作不太正常, 要么打字不出现候选框, 要么就输入的汉字会重复(打一个字出两个重复的字); 而且在 chrome/edge 的网页中打字的时候候选框会出现在屏幕左上角, 而不是网页中的文本框附近.

**Comment by Techince** [comment]
> > > [Techince](https://github.com/Techince)的说法应该是所有关于闪烁Issues里最接近这个bug本质的。 用了Techince的[weasel-0.15.1.004-installer_x64.exe](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.004-installer_x64.exe)，Word2019拖动标尺终于不闪烁了。 唯一不足的是C:\Windows\sysWOW64\weasel.dll 被Windows defender报毒，virustotal里也有几家杀软认为是Trojan。这个weasel.dll 被干掉后在企业微信等部分消息软件不能输入，浏览器/Office等大部分软件不受影响。
> > 
> > 
> > SysWOW64中的weasel.dll不能被干掉，这个是32位应用程序的输入法模块，64位的输入法模块在System32文件夹下。32位程序只能加载32位的dll，64位加载64位的dll。
> 
> 您好, 我尝试使用了您的修改版本, 但是好像在onenote上工作不太正常, 要么打字不出现候选框, 要么就输入的汉字会重复(打一个字出两个重复的字); 而且在 chrome/edge 的网页中打字的时候候选框会出现在屏幕左上角, 而不是网页中的文本框附近.

你安装的是005版本吗？新版本重新将小狼毫的IME模块加入到备用输入配置了，Win11上测试的OneNote 2021没有副作用。不知道你安装完成是否注销过系统？

**Comment by BH2WFR** [comment]
> > > > [Techince](https://github.com/Techince)的说法应该是所有关于闪烁Issues里最接近这个bug本质的。 用了Techince的[weasel-0.15.1.004-installer_x64.exe](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.004-installer_x64.exe)，Word2019拖动标尺终于不闪烁了。 唯一不足的是C:\Windows\sysWOW64\weasel.dll 被Windows defender报毒，virustotal里也有几家杀软认为是Trojan。这个weasel.dll 被干掉后在企业微信等部分消息软件不能输入，浏览器/Office等大部分软件不受影响。
> > > 
> > > 
> > > SysWOW64中的weasel.dll不能被干掉，这个是32位应用程序的输入法模块，64位的输入法模块在System32文件夹下。32位程序只能加载32位的dll，64位加载64位的dll。
> > 
> > 
> > 您好, 我尝试使用了您的修改版本, 但是好像在onenote上工作不太正常, 要么打字不出现候选框, 要么就输入的汉字会重复(打一个字出两个重复的字); 而且在 chrome/edge 的网页中打字的时候候选框会出现在屏幕左上角, 而不是网页中的文本框附近.
> 
> 你安装的是005版本吗？新版本重新将小狼毫的IME模块加入到备用输入配置了，Win11上测试的OneNote 2021没有副作用。不知道你安装完成是否注销过系统？

您好, 浏览器上已经表现正常了, 我的小狼毫分支版本是 .005版本, 安装后已经重启了多次系统,  onenote 版本是最新的 microsoft 365(16.0.17126.20126), 主屏幕缩放率是150%, onenote 插件全部卸载后仍有此问题.

目前的问题是以下两种状态:

- 状态1: 在 onenote 的笔记窗口中, 打字不显示候选框, 按下空格无法让汉字上屏, 但是在 ontnote 的其他文本框(查找/搜索等)可以正常显示候选框并输入汉字, 问题只在笔记框中打字时出现.
- 状态2: 在 onenote 的笔记窗口中, 打字时候选框显示正常, 但是上屏时会输出两遍 (打一个字出两个字), 但是在 onenote 的 查找/搜索等其他文本框中工作正常.
  不断尝试重启 onenote 和 小狼毫算法服务, 问题仍出现在 状态1 或 状态2 所描述的状态,  也曾更改过主屏幕缩放率为100%, 依次重启 onenote(托盘图标退出) 和小狼毫算法服务, 仍然出现 问题 2.

**Comment by Techince** [comment]
> > > > > [Techince](https://github.com/Techince)的说法应该是所有关于闪烁Issues里最接近这个bug本质的。 用了Techince的[weasel-0.15.1.004-installer_x64.exe](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.004-installer_x64.exe)，Word2019拖动标尺终于不闪烁了。 唯一不足的是C:\Windows\sysWOW64\weasel.dll 被Windows defender报毒，virustotal里也有几家杀软认为是Trojan。这个weasel.dll 被干掉后在企业微信等部分消息软件不能输入，浏览器/Office等大部分软件不受影响。
> > > > 
> > > > 
> > > > SysWOW64中的weasel.dll不能被干掉，这个是32位应用程序的输入法模块，64位的输入法模块在System32文件夹下。32位程序只能加载32位的dll，64位加载64位的dll。
> > > 
> > > 
> > > 您好, 我尝试使用了您的修改版本, 但是好像在onenote上工作不太正常, 要么打字不出现候选框, 要么就输入的汉字会重复(打一个字出两个重复的字); 而且在 chrome/edge 的网页中打字的时候候选框会出现在屏幕左上角, 而不是网页中的文本框附近.
> > 
> > 
> > 你安装的是005版本吗？新版本重新将小狼毫的IME模块加入到备用输入配置了，Win11上测试的OneNote 2021没有副作用。不知道你安装完成是否注销过系统？
> 
> 您好, 浏览器上已经表现正常了, 我的小狼毫分支版本是 .005版本, 安装后已经重启了多次系统, onenote 版本是最新的 microsoft 365(16.0.17126.20126), 主屏幕缩放率是150%, onenote 插件全部卸载后仍有此问题.
> 
> 目前的问题是以下两种状态:
> 
> * 状态 1: 在 onenote 的笔记窗口中, 打字时光标会闪烁, 但无法显示候选框, 按下空格也无法让汉字上屏, (且无法正常显示小狼毫方案选单). 但是在 ontnote 的其他文本框(查找/搜索等)可以正常显示候选框并输入汉字, 问题只在笔记框中打字时出现.
> * 状态 2: 在 onenote 的笔记窗口中, 打字时候选框显示正常, 但是上屏时会输出两遍 (打一个字出两个字), 但是在 onenote 的 查找/搜索等其他文本框中工作正常.
>   不断尝试重启 onenote 和 小狼毫算法服务, 问题仍出现在 状态1 或 状态2 所描述的状态,  也曾更改过主屏幕缩放率为100%, 依次重启 onenote(托盘图标退出) 和小狼毫算法服务, 仍然出现 问题 2.
> 
> 更新: **我尝试了换回您的 .004 版本, 这个问题解决了**, 降级安装, 注销重新登录后, onenote 上可以正常打字.

这个是小狼毫的IME模块引起的问题。之前因为OneNote启动时会同时加载IME和TSF两个模块，然后TSF在处理按键消息时就变成了经输入法处理过的按键消息，而不是原始消息。最近在研究这个备用IME，在我本机上没有出再现过此问题，我以为已经不会再出现那种问题了。看来还得把这个模块给去掉。

**Comment by Techince** [comment]
@BH2WFR 试试新版本吧。006版本移除了IME模块。
[小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.006-installer_x64.exe)

**Comment by Techince** [comment]
检查System32和SysWoW64目录下是否存在weasel.ime文件，有的话，请删除。
我本机测试的OneNote 2021没有此问题，我另一个Win10装的Office 2016，OneNote也没有问题

**Comment by Techince** [comment]
。

> > @BH2WFR 试试新版本吧。006版本移除了IME模块。 [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.006-installer_x64.exe)
> 
> 您好，我试着更新了006版本，但是onenote上面仍然工作异常，不显示候选框，但按下空格可以输入，但是会输入两次（打一个字出两个字），且除编辑区外搜索框等处也无法正常显示候选框，但搜索框中不存在打一个字出两个字的问题。
> 
> 更新：在onenote中，不断重启onenote，**有时候工作正常，有时候工作不正常**， 　　有候点击托盘菜单中“关闭守护”就正常了，但是有时候点了这个也不行
> 
> 　　降级回 004 版本后问题恢复正常。

检查System32和SysWoW64目录下是否存在weasel.ime文件，有的话，请删除。
我本机测试的OneNote 2021没有此问题，我另一个Win10装的Office 2016，OneNote也没有问题

**Comment by Techince** [comment]
> > @BH2WFR 试试新版本吧。006版本移除了IME模块。 [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.006-installer_x64.exe)
> 
> 您好，我试着更新了006版本，但是onenote上面仍然工作异常，不显示候选框，但按下空格可以输入，但是会输入两次（打一个字出两个字），且除编辑区外搜索框等处也无法正常显示候选框，但搜索框中不存在打一个字出两个字的问题。
> 
> 更新：在onenote中，不断重启onenote，**有时候工作正常，有时候工作不正常**， 　　有候点击托盘菜单中“关闭守护”就正常了，但是有时候点了这个也不行
> 
> 　　降级回 004 版本后问题恢复正常。

检查System32和SysWoW64目录下是否存在weasel.ime文件，有的话，请删除。
我本机测试的OneNote 2021没有此问题，我另一个Win10装的Office 2016，OneNote也没有问题

**Comment by BH2WFR** [comment]
@Techince 
确实我在您说的这两个目录找到了 weasel.ime 文件, 手动尝试删除, 发现被占用, 遂用火绒强行粉碎, 重启后在 Onenote 中输入法工作恢复正常, **006 版本在Onenote上的工作问题解决了.**  谢谢!
