### ISSUE TITLE
weasel 0.15 + win10 突然無法輸入，也無法重新部署

### ISSUE THREAD

**Issue by changchichung** [rime/weasel#1018]
上禮拜在一台全新安裝的win10 筆電上，裝了weasel 0.15 ，在安裝過程中有更改路徑到 c:\weasel 
本來都是正常在使用
今天重新開機之後，切換到小狼毫卻無法輸入中文字，在工具列點重新部署沒有任何反應，手動砍掉 weaselserver 再執行也沒有作用，用命令列模式重新部署，會出現可以用小狼毫手寫輸入的訊息，但是中文依舊無法輸入

移除小狼毫，重新開機，然後再次重新安裝又突然變得可以正常輸入了
請問有辦法開啟 debug 看看發生了什麼事嗎？

**Comment by changzaicl** [comment]
试试Actions下面最新的版本

**Comment by sccccchallz** [comment]
> 
> 不了解你的意思...
> 
> 上禮拜用到今天本來都好好的，剛剛又突然發生無法輸入也無法重新部署的狀況.

尝试在 actions 页面里下载最新版

**Comment by tyf2018** [comment]
我也是，今天一直显示部署中（持续了七八个小时），无法输入。重装后没有部署自定义词典前是能正常输入的，但是放入自定义词典重新部署后就一直无法输入。重新安装了actions的最新版，也是如此。这两天，Windows也没有更新啥的。0.15版自发布后一直在用，应该有半年了，一直正常。

**Comment by Mowd** [comment]
遇到同樣問題，手動執行算法服務後恢復正常
![image](https://github.com/rime/weasel/assets/1097892/90808194-7367-4982-92dd-bddc4287a59d)

**Comment by tyf2018** [comment]
> 手動執行算法服務

肯定有手动打开算法服务的，未果。

直接复制另一台电脑上的build文件夹覆盖后，问题终于得到解决。只是有点担心下次会不会又毫无征兆地突发故障

**Comment by Techince** [comment]
> > 直接复制另一台电脑上的build文件夹覆盖后，问题终于得到解决。只是有点担心下次会不会又毫无征兆地突发故障
> 
> 肯定會，因為我就是這樣不斷的發生錯誤

查下「%temp%\rime*」开头的日志 ，看看日志中有没有错误发生

**Comment by tyf2018** [comment]
@Techince 没找到昨天的日志。但今天的日志中有这样的报错内容（目前输入法使用正常）：

E20231106 12:34:22.625779 16176 key_event.cc:68] parse error: unrecognized modifier 'Ctrl'
E20231106 12:36:08.639540  8000 key_event.cc:68] parse error: unrecognized modifier 'Ctrl'
E20231106 12:37:47.896203 12872 key_event.cc:68] parse error: unrecognized modifier 'Ctrl'
E20231106 12:39:35.591912  5212 key_event.cc:68] parse error: unrecognized modifier 'Ctrl'
E20231106 12:40:09.508219  9404 key_event.cc:68] parse error: unrecognized modifier 'Ctrl'
E20231106 12:41:34.665225 15368 key_event.cc:68] parse error: unrecognized modifier 'Ctrl'
E20231106 12:41:52.724074 14472 key_event.cc:68] parse error: unrecognized modifier 'Ctrl'
E20231106 12:42:55.304666 15292 key_event.cc:68] parse error: unrecognized modifier 'Ctrl'
E20231106 12:47:07.548097  9404 simplifier.cc:56] opencc config not found: C:\Users\Matt\AppData\Roaming\Rime\opencc\emoji.json

跟Ctrl键有关么？另外emoji.json这个文件其实是存在的，不知道为什么会报错。

**Comment by Techince** [comment]
> @Techince 没找到昨天的日志。但今天的日志中有这样的报错内容（目前输入法使用正常）：
> 
> E20231106 12:34:22.625779 16176 key_event.cc:68] parse error: unrecognized modifier 'Ctrl' E20231106 12:36:08.639540 8000 key_event.cc:68] parse error: unrecognized modifier 'Ctrl' E20231106 12:37:47.896203 12872 key_event.cc:68] parse error: unrecognized modifier 'Ctrl' E20231106 12:39:35.591912 5212 key_event.cc:68] parse error: unrecognized modifier 'Ctrl' E20231106 12:40:09.508219 9404 key_event.cc:68] parse error: unrecognized modifier 'Ctrl' E20231106 12:41:34.665225 15368 key_event.cc:68] parse error: unrecognized modifier 'Ctrl' E20231106 12:41:52.724074 14472 key_event.cc:68] parse error: unrecognized modifier 'Ctrl' E20231106 12:42:55.304666 15292 key_event.cc:68] parse error: unrecognized modifier 'Ctrl' E20231106 12:47:07.548097 9404 simplifier.cc:56] opencc config not found: C:\Users\Matt\AppData\Roaming\Rime\opencc\emoji.json
> 
> 跟Ctrl键有关么？另外emoji.json这个文件其实是存在的，不知道为什么会报错。

按键设置错误，你查下方案配置中绑定按键那块

**Comment by tyf2018** [comment]
> 按键设置错误

我是这样设置的，请问怎样修改呢？
  "switcher/hotkeys":
    - "Ctrl+Shift+F4"

**Comment by tyf2018** [comment]
> Ctrl+Shift+F4

我在定制指南中找到原因了，原来Ctrl要写成Control
