### ISSUE TITLE
不能正确触发浏览器的 `compositionupdate` 事件

### ISSUE THREAD

**Issue by se1phine** [rime/weasel#1019]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: win11 23H2 22631.2428
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
不能正确触发浏览器的`compositionupdate` 事件，如图
![Recording 2023-11-03 115251](https://github.com/rime/weasel/assets/11831722/4631e8a5-c220-4370-ba27-89f050984981)

测试地址：https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionupdate_event

**复现步骤**
重现问题的步骤，如：
1. 打开 '...' 软件
2. 输入 '...'
3. 进行 '...' 操作
4. 遇到了 '...' 问题

**预期行为**
![Recording 2023-11-03 115420](https://github.com/rime/weasel/assets/11831722/b254a6cf-5b83-4e88-b643-cc3e896ae225)

**用户文件**
[Rime.zip](https://github.com/rime/weasel/files/13246581/Rime.zip)

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**

如果有其他补充说明，可以写在这里

**Comment by Techince** [comment]
将Systel设置inline_preedit: true后就可以触发了。微软的输入法就是这个风格

**Comment by fxliang** [comment]
因为网页上这个事件依赖输入框的内容变化，inline_preedit: false 的时候只有第一码键入时预插入空格，后面就不改了。
