### ISSUE TITLE
win10 1709  导致开始点不开 按win键无反应。

### ISSUE THREAD

**Issue by guobing1993** [rime/weasel#102]
这个输入法是真的好用，当我第一次进入开始菜单找到输入法的设置点开后，win 10的   开始   就点不开了。点不开的还有微软小娜。稍后我将继续重新安装再次尝试。

**Comment by gigglin** [comment]
看到很多人都碰到类似问题.我现在想用开始菜单,都先切个别的输入法.

**Comment by kawori** [comment]
我也遇到这个问题，解决方法可以是在任务管理器中重启资源管理器。
但是这不是长久之计，因为它很影响使用体验。
甚至可能导致其它问题，比如在出现无法呼出开始菜单的问题之后，我用Snipaste截图的时候会卡在截图界面，无法截图，其它窗口都无法控制。
这应当是一个亟待解决的问题。

**Comment by lotem** [comment]
暫不支持 Windows 10。詳見： http://rime.im/download/#Windows

Duplicate of https://github.com/rime/weasel/issues/102
