### ISSUE TITLE
unreal 引擎中使用中文输入法 候选框位置不正确

### ISSUE THREAD

**Issue by KangLong** [rime/weasel#1023]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows10 22H2 19045.3570
 - 小狼毫版本:   0.15.0.0 

**描述遇到的问题**
在 unreal 引擎中输入中文，候选框会出现在屏幕左上角。在 4.27 或者最新的 5.3.1 中都有这个问题

**复现步骤**
![微信截图_20231111155225](https://github.com/rime/weasel/assets/6110799/fc937b3f-31df-44c2-bf71-3e5ee18390e5)

**预期行为**
中文 候选框正确的出现在光标

**Comment by Techince** [comment]
@KangLong 我这个版本修复过虚幻引擎的坐标错误了。
https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.0-installer_x64.exe

**Comment by KangLong** [comment]
> @KangLong 我这个版本修复过虚幻引擎的坐标错误了。 https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.0-installer_x64.exe

感谢，使用新版后没问题了

**Comment by Ahtaler** [comment]
> @KangLong我这个版本修复了虚拟引擎的坐标错误。 https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.003-installer_x64.exe

 ✅我的小狼毫版本于 rime/weasel 下载
 ✅我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

· OS 详细版本: Windows10 22H2 19045 4529
· 小狼毫版本: 0.16.1.0

**描述遇到的问题**
在 unreal 引擎5.3.2版本中，输入中文，候选框会出现在屏幕左上角，且0.5s后输入框闪退消失

**复现步骤**
![Snipaste_2024-06-26_11-11-05](https://github.com/rime/weasel/assets/55629173/8678d4f4-d3d3-4b51-ba06-8f372ba22f02)

**预期行为**
中文候选框正确的出现在光标处且正确输入

**Comment by eusru** [comment]
> [@KangLong](https://github.com/KangLong) 我这个版本修复过虚幻引擎的坐标错误了。 https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.003-installer_x64.exe

请问关于这个问题，您还记得当时是怎么修复的
