### ISSUE TITLE
主分支 与 Techince 分支一些 bug

### ISSUE THREAD

**Issue by Huandeep** [rime/weasel#1024]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于  [rime/weasel](https://github.com/rime/weasel/actions/runs/6812500882) [Techince/weasel 20231109 ](https://github.com/Techince/weasel/releases) 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [  Windows 11 23H2 22631.2506]
 - 小狼毫版本: [ [56d02a4](https://github.com/rime/weasel/actions/runs/6812500882) [Techince/weasel 20231109](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.0-installer_x64.exe) ]

**描述遇到的问题**
1. 主分支 和 Techince 分支均出现 Chromium 内核浏览器地址栏抖动
2. Techince 分支 导入文本码表后无法按照词频显示

**复现步骤**
重现问题的步骤，如：
**1**
  1. 打开 Chromium 内核浏览器
  2. 在地址栏键入`ha`或者 键入`ha`再删除，再键入`ha` ，可复现

**2** 
  1. 打开 用户词典管理
  2. 导入 文本码表
  4. 键入 测试文本
  5. 无法按照词频显示

**测试文本**
```
截止	jie zhi	18
戒指	jie zhi	17
截至	jie zhi	16
介质	jie zhi	15
借支	jie zhi	14
节制	jie zhi	13
截肢	jie zhi	12
皆知	jie zhi	11
节支	jie zhi	10
洁治	jie zhi	9
接枝	jie zhi	8
接旨	jie zhi	7
界址	jie zhi	6
节肢	jie zhi	5
解职	jie zhi	4
借指	jie zhi	3
介值	jie zhi	2
阶值	jie zhi	1
```

**截图**
**问题1**
https://github.com/rime/weasel/assets/30691481/10819542-a27b-4f71-bdcc-a805657768be

**问题2**
正常情况
![Snipaste_2023-11-11_20-39-33](https://github.com/rime/weasel/assets/30691481/8cf7533e-d25c-4faf-9b6f-dd674a8a42f1)
Techince 分支出现的情况
![Snipaste_2023-11-11_20-55-42](https://github.com/rime/weasel/assets/30691481/e301e7bd-4725-4788-9cd2-210887ef2f0e)

**其他补充说明**
希望主分支合并修复word键入第一个编码无法快速显示的 bug
![Snipaste_2023-11-11_20-59-32](https://github.com/rime/weasel/assets/30691481/4701516c-6bbc-4724-b451-3a562b978456)

**Comment by Techince** [comment]
@Huandeep 你观察的太仔细了，你观察的太仔细了。我一直用的是横版候选框，测试时没有问题。看到你的测试，调成竖版候选，游戏器那里偶尔闪一下。但是发现了其它的问题，由于固定了首码坐标，造成竖版候选框，若第一码之后的某一码候选项少于一页的设定值时，此窗口不会下降。

**Comment by Techince** [comment]
> @Techince 导入文本码表后无法按照词频显示，这个是 bug 吗？ 主分支是词频从大到小。 你的分支是从**个位数最大到个位数最小**显示， 再到**两位数最大到两位数最小**显示，分成多部分。

文本码表这个是librime处理的，Weasel端没动这个呀！梁梁的32位版本你试过了吗？那个版本的导入文本正常吗？

**Comment by Techince** [comment]
> > > @Techince 导入文本码表后无法按照词频显示，这个是 bug 吗？ 主分支是词频从大到小。 你的分支是从**个位数最大到个位数最小**显示， 再到**两位数最大到两位数最小**显示，分成多部分。
> > 
> > 
> > 文本码表这个是librime处理的，Weasel端没动这个呀！梁梁的32位版本你试过了吗？那个版本的导入文本正常吗？
> 
> 这个`issue`的**问题2**的**第1张图**就是**32位**版本的，用测试文本导入**一切正常**，相反用**64位**版本的就会出现**第2张图**那种情况，我测试过多次，确认就是**64位**存在这个问题。

那我找找原因吧。这个不太好查

**Comment by Techince** [comment]
> @Techince 用最新的[rime-d3944b8-Windows-clang](https://github.com/rime/librime/actions/runs/6855498232) 并且清空用户数据再重新导入文本码表就没事了

似乎是我本地编译的librime出现问题了
