### ISSUE TITLE
[BUG] 在游玩tModLoader时无法切换到中文输入

### ISSUE THREAD

**Issue by nullpo21** [rime/weasel#1025]
**上报前请检查**
- [ o ] 我遇到的问题没有其他人在 issue 里提到过
- [ o ] 我的小狼毫版本于 rime/weasel 下载
- [ o ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 版本1903 （操作系统内部版本 18362.1016）
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
在游戏tModLoader里，无法切换到中文输入，无论是使用shift，ctrl+shift，ctrl+space，alt+space等用于切换输入法的快捷键，皆无法切换到中文输入。

**复现步骤**
重现问题的步骤，如：
1. 打开 'tModLoader（需同时安装Terraria）' 软件
2. 输入 '任意字符'
3. 进行 '中英切换' 操作
4. 遇到了 '无法切换中英文' 问题

**预期行为**
暂无

**用户文件**
见下方评论

**截图**
暂无

**其他补充说明**
- 注1：tModLoader是游戏Terraria的社区自制模组开源软件，Terraria本体不支持加载模组，需通过tModLoader加载。Terraria本体可在steam购买获得，同时会附赠tModLoader。除了steam附赠以外，tModLoader也可以单独下载，其开源地址是https://github.com/tModLoader/tModLoader
注意tModLoader在客户机上无法单独运行（在服务器上可作为服务器运行），在客户机上需先安装Terraria本体；
- 注2：Terraria本体是可以正常输入的，但是输入框的样式是windows自带的输入法的样式；
- 注3：0.14版本的小狼毫对于Terraria和tModLoader都是正常使用的，输入框的样式也是正确的自定义样式，只是0.14版本的输入框有BUG，不会随着光标移动，而是固定在窗口的左上角；

**Comment by nullpo21** [comment]
[userdata.zip](https://github.com/rime/weasel/files/13330151/userdata.zip)

**Comment by nullpo21** [comment]
> > [userdata.zip](https://github.com/rime/weasel/files/13330151/userdata.zip)
> 
> 试一下此版本。 [weasel-0.15.1.0-installer_x64.exe](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.002-installer_x64.exe)

你好，经过测试，该版本在tModLoader（以下简称tml）里可以切换到中文输入，感谢作者。
同时，还存在以下两个问题：

1. 在Terraria本体里，输入框样式仍然为windows自带输入法样式，且无法进行输入框横纵向切换；
2. 在tml里，输入框固定在右下角，不会跟踪光标位置，在聊天软件TIM和编辑器notepadd++里光标跟踪表现正常。

测试图片如下：
本体新建角色测试
![本体新建角色测试](https://github.com/rime/weasel/assets/38742959/1e725d90-246a-4b38-8393-fa2bd10b0368)

本体聊天框测试
![本体聊天框测试](https://github.com/rime/weasel/assets/38742959/efe94a02-aa64-40ab-a61d-dbd307817913)

tml新建角色测试-横向
![tml新建角色测试-横向](https://github.com/rime/weasel/assets/38742959/7ed2560e-e293-42d8-9d44-9f1cde2f91dc)

tml新建角色测试-纵向
![tml新建角色测试-纵向](https://github.com/rime/weasel/assets/38742959/2c9d6bbe-bbee-4d1b-b7e7-4e9e7cfbe6f6)

tml聊天框测试-横向
![tml聊天框测试-横向](https://github.com/rime/weasel/assets/38742959/50de0861-4419-4926-aa8a-efec5c1da1f0)

tml聊天框测试-纵向
![tml聊天框测试-纵向](https://github.com/rime/weasel/assets/38742959/eed3e81f-5ef6-4f37-8106-3240f4616e26)

**Comment by Techince** [comment]
@nullpo21 像这种游戏，如果不支持无UI模式的话，输入法一般是获取不到它的焦点坐标的。只能使用「Ctrl+Shift+F」快捷键，手动将候选框拖到合适的位置。

**Comment by nullpo21** [comment]
> @nullpo21 像这种游戏，如果不支持无UI模式的话，输入法一般是获取不到它的焦点坐标的。只能使用「Ctrl+Shift+F」快捷键，手动将候选框拖到合适的位置。 如果是Win10系统的话，可以先用快捷键「Ctrl+Shift+G」，关闭候选框，看看游戏是否支持无UI模式。若游戏没有接管候选框绘制，再执行那个快捷键重新打开候选框，然后执行快捷键移动候选框。 看你的候选框样式是inline_preedit: false，可以试试inline_preedit: true

在使用inline_preedit: true之后，游戏确实接管了绘制框，其样式与上图“本体新建角色测试”一致，非常感谢！

issue已解决，关闭。
