### ISSUE TITLE
在foxmail中新建邮件框中输入内容，菜单栏下的一个区域总是一闪一闪的

### ISSUE THREAD

**Issue by changzaicl** [rime/weasel#1027]
**操作系统信息**
 - OS 详细版本: Windows 11 23H2
 - 小狼毫版本: 最新发布版本后的 CI 构建，2023年11月14日

**描述遇到的问题**
简短地描述你所遇到的问题

**复现步骤**
重现问题的步骤，如：
1. 打开 'foxmail' 软件
2. 新建邮件，在任何位置输入，均可以复现
3. 遇到了 '菜单栏抖动' 问题

https://github.com/rime/weasel/assets/144407904/cb48c465-c799-48ef-97b2-a680c7b1fa58

**Comment by liangzhi52** [comment]
确实有changzaicl说的这种情况
另外，在foxmail 中打字，输入法相应速度偏慢。
