### ISSUE TITLE
Navigator光標組件移動的單位問題

### ISSUE THREAD

**Issue by 29988122** [rime/weasel#103]
請問一下，我看了很久navigator的設定，還看了sourcecode
( https://github.com/rime/librime/blob/9c4fa8ab63438f8d184203e4a5079e5d3c744795/src/rime/gear/navigator.cc )
就是試圖自己定製，要解決一個問題：
注音輸入如果打錯，會用方向鍵左右來選取要改的碼；但是方向鍵往左並不是一次移動一個按鍵，有時候是一次移動一個"字"，很困擾。

e.g. ㄏㄠㄅㄨㄏㄠ共六個字，但是使用方向往左移動的時候只要按三次，一次移動ㄏㄠ / ㄅㄨ / ㄏㄠ
這樣子超級麻煩的，會沒有辦法按音去改正鍵入錯誤

我猜重點在這一行，注意佛振的註解，這就是說他要移動遊標的時候會以字為單位，但是這樣在修改打錯的音上反而造成很多麻煩..

else {
// take a jump leftwards when there are multiple spans,
// but not from the middle of a span.
(spans_.Count() > 1 &&
spans_.HasVertex(ctx->caret_pos())
? JumpLeft(ctx) : Left(ctx)) || End(ctx);
}
return kAccepted;

不過我看不懂。請問我應當要怎麽改動，能夠讓navigator不論是在何種輸入法（我主要使用注音），方向鍵左右移動都只會移動一個"音"，而不是一次移動兩三個音？

**Comment by Prcuvu** [comment]
在设计上，是希望每按一次方向左键移动到光标左侧最后一个编码切分的起始处，然后再用方向右键移动到需要修改的码元。这样一来，在连打长句的时候，修改时按方向键的次数减少。希望可以解决你的疑问。

**Comment by 29988122** [comment]
我其實可以理解這麼做的原因，我甚至翻了當年google mailgroup的patchnote出來確認：https://groups.google.com/forum/#!topic/rime-devel/ZK1sGi9xC70

我清楚這是intended behavior，只是不太直觀而已（預設一次移動一個編碼切分，而不是碼元。要移動碼元必須要如你說的一般使用方向右鍵）。

只是好奇，畢竟RIME/小狼毫本就有高定製性，又是opensource的，曾經自己試著要改過這個行為，但卻因為能力不足的關係，無果，所以上來看能不能從您們這兒獲得一些建議而已。囧。

**Comment by Prcuvu** [comment]
@lotem 是否应该增加方向左键移动一个码元/切分的选项？

**Comment by lotem** [comment]
一點感想：拼音的字母作爲「音節組成部分」的概念不如注音符號強，所以用戶通常會刪除錯誤的拼音，再重新拼寫，很少會移動光標修改錯誤的拼式。倒是按「字」向前移動編輯比較常用。
傳統 Windows 注音輸入法裏面，移動光標修改拼式和編輯字句是由兩個模式分別支持的，因此造就了不同的用戶習慣。
