### ISSUE TITLE
配置 inline_preedit 内嵌输入码后，输入过程中按 Shift 无输入状态提示

### ISSUE THREAD

**Issue by hiikii** [rime/weasel#1030]
**操作系统信息**
 - OS 详细版本: Windows 11 22H2 22621.2715
 - 小狼毫版本: 0.15.0.0，Commit 76bd36b

**描述遇到的问题**
尝试打 patch 配置 "style/inline_preedit": true 后，样式表现正常，但在输入中途按左 Shift 未观察到有中英切换的图标弹出，同时发现当候选词选中为纯字母英文时，按左 Shift 不会自动关闭候选词列表。

**复现步骤**
重现问题的步骤，如：
1. [使用的方案](https://github.com/iDvel/rime-ice)，有自己修改 rime_ice 配置所以切换到了该方案内提供的 melt_eng 来进行验证
2. 在中文输入状态下，输入任意内容，候选词选中为中文，继续按下左 Shift，无中英切换图标弹出
3. 在中文输入状态下，输入任意内容如 test，候选词选中为英文 test，继续按下左 Shift，无中英切换图标弹出，同时候选词列表依然显示

**预期行为**
输入状态的中英切换图标可以正常显示，候选词为英文时，按左 Shift 也会关闭候选词列表

**其他补充说明**
由于使用的方案可在中文输入模式下输入英文词汇，为避免混淆，将复现步骤分为了 2 和 3，其中 3 既可以在上述 rime_ice 方案（有修改）里复现，也可以在 melt_eng（未修改）里复现，default.yaml 使用 weasel 自带

**Comment by fxliang** [comment]
![shift](https://github.com/rime/weasel/assets/4023160/2f3b9ae6-fe8a-4adc-a600-1a4d7ea6cd94)
使用rime-ice测试，未复现问题

**Comment by fxliang** [comment]
所以问题是解决了？
