### ISSUE TITLE
0.15.0 bug

### ISSUE THREAD

**Issue by ytlxz** [rime/weasel#1034]
在方案选单设定界面，如果选择了超集，主题风格的设置就不起作用了，显示默认的主题风格了，并且提示的拆字部分都显示为小方框了
![image](https://github.com/rime/weasel/assets/38758274/f2f4a9ad-4861-439d-8ae2-1ba5147b10bd)
![image](https://github.com/rime/weasel/assets/38758274/94c00a69-4fb0-4a52-87df-ca93f820046e)
![image](https://github.com/rime/weasel/assets/38758274/275b6636-37ba-42df-bf32-69d6dd13adb4)
![image](https://github.com/rime/weasel/assets/38758274/54a33702-83d9-4f4f-a4ce-b5cd9a46415c)
小狼毫助手的设置如下
![image](https://github.com/rime/weasel/assets/38758274/4003aaa3-e1d8-40e1-8750-399969d50a7f)
在方案选单设定界面，如果不选择超集，一切显示正常
![image](https://github.com/rime/weasel/assets/38758274/9b1fc260-c37a-41a5-ba79-18f2ba4ee695)
![image](https://github.com/rime/weasel/assets/38758274/649d659a-e7f8-4776-a4cc-cf786861fa76)
![image](https://github.com/rime/weasel/assets/38758274/cbb438fb-a4ef-4ad7-9a01-caa59d7c0569)

**Comment by fxliang** [comment]
把“超集”文件中的style内容全部注释了试了再来报

**Comment by yanhuacuo** [comment]
98超集比较特殊，需要指定字体，不可更改。
因为98超集码表收录了 unicode15.1 标准规范的十万多汉字及其全部拆分，完整覆盖到 扩i 。
同时，98超集扩编时，对部分拆分字根做了适当形变（增至369枚基础字根），这也限制了超集在自定义字体上的灵活性。
总之，98超集可以换【主题配色】，但是不要改预设的字体。
