### ISSUE TITLE
Fluent Search 重复上屏候选

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#1038]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 19044.3570; Windows 11 22H2
 - Weasel: 15.0；CI 测试版；14.3 
 - fluent search：<https://www.fluentsearch.net/>

从 14.3 一直到 15.0，包括最近可用的 CI 版本，和 x64 Fork 版本都出现的问题。

在 Fluent search 中，输入拼音后重复输入两遍候选。例如，打字： `nihao`，会上屏「你好你好」。

无论是 inline 还是非 inline_preedit 都会输入一次候选，上屏两次：微软拼音输入法没有这种情况，视频如下

[20230816191554.webm](https://github.com/rime/weasel/assets/76689045/b02e000a-8e8f-4b33-8c93-b3c48ddd7c60)

另外是一些其他的信息，不知道是否相关，也放在这里
- 14.3 会在 Chrome、Obsidian 上偶然重复上屏；
- 后来的 15 版本只在输入验证码（类似 Apple、Steam 登录那种给几个格子让输入）的时候碰到过重复上屏；

**Comment by mirtlecn** [comment]
我找找明确的复现方法

**Comment by mirtlecn** [comment]
找到了一个能稳定触发此 bug 的软件，fxliang 有余力可以帮忙看看，感激不尽。 @fxliang

**Comment by fxliang** [comment]
之前neovide也会，但是后来不知道他们改了什么后面就没有了……所以其实我的感觉是，不要乱动，不然为一个软件改了可能会引入其他的某个软件的不兼容，到时又改回去……

**Comment by mirtlecn** [comment]
那我隔这放着吧。

**Comment by Sakuranokwa** [comment]
我使用 Rime 也遇到了同様的情況 !

**Comment by wordpure** [comment]
Fluent Search beta 版已经修复这个 [问题](https://github.com/adirh3/Fluent-Search/issues/844) 了，更新一下，或者等它推送到稳定版就好。

[Beta 安装版](https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe)

[Beta 便携版](https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/portable)

![image](https://github.com/rime/weasel/assets/68013962/bf550ec7-afa9-44be-903c-936a43f2af62)
