### ISSUE TITLE
在Firefox浏览器里，会自动插入空格

### ISSUE THREAD

**Issue by joeaki1983** [rime/weasel#1043]
在Firefox浏览器里，reddit网站上，输入中文的时候，会自动在中文里插入空格，Chrome浏览器就没有这个状况，排除是Firefox插件问题（把所有插件都关了），请问如何解决，谢谢。

**Comment by Techince** [comment]
> 在Firefox浏览器里，reddit网站上，输入中文的时候，会自动在中文里插入空格，Chrome浏览器就没有这个状况，排除是Firefox插件问题（把所有插件都关了），请问如何解决，谢谢。

用inline_preedit: true模式。非嵌入式需要插入一个哑字符才能获取到焦点坐标，但个别应用中会出现副作用。
