### ISSUE TITLE
feature request: app_options 匹配进程名不区分大小写

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#1048]
- Windows 显示的进程名是大小写兼具的，
- 系统大小写不敏感

但在 app_options 中，得全小写才能匹配。

从任务管理器等出复制的进程名，到 weasel.yaml 还得全小写，有一些反直觉？碰到了不少新手在这里栽跟头了

有没有可能改成不区分大小写匹配？或者说目前的设计是有意为之？

**Comment by fxliang** [comment]
全小写是之前的有意为之，具体原因不详
https://github.com/rime/weasel/blob/master/WeaselIPC/WeaselClientImpl.cpp#L44
