### ISSUE TITLE
vs2015编译源码，多处出现库文件编译错误

### ISSUE THREAD

**Issue by Alexkun** [rime/weasel#105]
报错为：C2893 未能使函数模板 unknow-type std::invoke(_Callable &&,_Types &&...) 专用化
![000f11cf-9127-4d24-bac7-041edbd37c1b](https://user-images.githubusercontent.com/11203920/34668572-fdb15c7c-f4a8-11e7-93fb-bce4fe8cdde1.png)

多个子项目编译出现这个问题，搜了一下说是可能因为编译器升级导致函数库冲突的问题，有没有什么解决办法？

**Comment by Prcuvu** [comment]
无法再现这个问题。请参考 [INSTALL.md](https://github.com/rime/weasel/blob/master/INSTALL.md) 进行编译。
