### ISSUE TITLE
小狼毫经常不能使用，提示已禁用输入法

### ISSUE THREAD

**Issue by eric1ee** [rime/weasel#1051]
多次复现的bug 系统是win10和win11，小狼毫版本：0.15
在Excel中经常无法输入中文，右下指示器显示“x”号，鼠标悬停在“x”号上提示已禁用输入法，但在其他窗口又能正常使用
![image](https://github.com/rime/weasel/assets/23067121/8aa91231-ba0d-4783-a936-b738dc57ebbf)

**Comment by csjtl** [comment]
ctrl+空格

**Comment by Techince** [comment]
试一下这个版本。
[小狼毫x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.005-installer_x64.exe)

**Comment by Techince** [comment]
> > 试一下这个版本。 [小狼毫x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.005-installer_x64.exe)
> 
> 发现你这版杀毒软件报毒比目前的少多了，特别是 Bitdefender 等平台是不报毒的。不晓得什么原因

实际上是没有毒的，源代码都在这里开放着，官方版本是工具链生成的，不知道怎么会被杀软报毒。

**Comment by diablosin** [comment]
> 试一下这个版本。 [小狼毫x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.005-installer_x64.exe)

你好，安装这个版本后，无法切换到中文输入，ctrl+·也切不出来输入方案选择，服务是开启的

**Comment by Techince** [comment]
> > 试一下这个版本。 [小狼毫x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.005-installer_x64.exe)
> 
> 你好，安装这个版本后，无法切换到中文输入，ctrl+·也切不出来输入方案选择，服务是开启的

我又上传了一个最近编译的，个人感觉还算比较稳定。之前的005版本修错代码了，个别程序会崩溃。

**Comment by diablosin** [comment]
> > > 试一下这个版本。 [小狼毫x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.005-installer_x64.exe)
> > 
> > 
> > 你好，安装这个版本后，无法切换到中文输入，ctrl+·也切不出来输入方案选择，服务是开启的
> 
> 我又上传了一个最近编译的，个人感觉还算比较稳定。之前的005版本修错代码了，个别程序会崩溃。 安装完后需要注销一下才会生效。

重新安装了最新的版本还是不能输入中文，shift键不能切换中英文状态，而且手动点击状态栏中的输入法图标，切换到英文输入的状态[A]，敲击键盘时又自动切回中文输入提示的状态图标

**Comment by Techince** [comment]
> > > > 试一下这个版本。 [小狼毫x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.005-installer_x64.exe)
> > > 
> > > 
> > > 你好，安装这个版本后，无法切换到中文输入，ctrl+·也切不出来输入方案选择，服务是开启的
> > 
> > 
> > 我又上传了一个最近编译的，个人感觉还算比较稳定。之前的005版本修错代码了，个别程序会崩溃。 安装完后需要注销一下才会生效。
> 
> 重新安装了最新的版本还是不能输入中文，shift键不能切换中英文状态，而且手动点击状态栏中的输入法图标，切换到英文输入的状态[A]，敲击键盘时又自动切回中文输入提示的状态图标

算法服务没启动。

**Comment by diablosin** [comment]
> > > > > 试一下这个版本。 [小狼毫x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.005-installer_x64.exe)
> > > > 
> > > > 
> > > > 你好，安装这个版本后，无法切换到中文输入，ctrl+·也切不出来输入方案选择，服务是开启的
> > > 
> > > 
> > > 我又上传了一个最近编译的，个人感觉还算比较稳定。之前的005版本修错代码了，个别程序会崩溃。 安装完后需要注销一下才会生效。
> > 
> > 
> > 重新安装了最新的版本还是不能输入中文，shift键不能切换中英文状态，而且手动点击状态栏中的输入法图标，切换到英文输入的状态[A]，敲击键盘时又自动切回中文输入提示的状态图标
> 
> 算法服务没启动。

确实是算法服务没启动，手动WeaselServer运行也不行。操作系统版本是Win 10 22H2，内部版本19045.3803，CPU 5600X

**Comment by eric1ee** [comment]
> 试一下这个版本。 [小狼毫x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.005-installer_x64.exe)

感谢，用了这个后两天了，没有遇到禁用的情况了
