### ISSUE TITLE
方案安装工具貌似固定写入 AppData 而不是安装时指定的用户文件夹

### ISSUE THREAD

**Issue by toshiya14** [rime/weasel#1053]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 22H2 22621.1702
 - 小狼毫版本: 0.15.0

**描述遇到的问题**
如果在安装的时候指定了用户文件目录，后续再通过 `rime-install.bat` 进行安装时，还是会写到 `%APPDATA%/Rime` 文件夹内。

**复现步骤**
重现问题的步骤，如：
1. 安装时，选择用户文件夹：`D:\Profile\RIME`
2. 使用输入法设置，选择**获取更多输入方案**，输入 `iDvel/rime-ice:others/recipes/full`。
3. 安装完成
4. 重新进入输入法设置。

**预期行为**
重新进入输入法设置，应该可以见到刚刚新安装的方案。但是没有。
在第2步中，也可见：
```
Working directory: C:\Program Files (x86)\Rime\weasel-0.15.0
Package installer directory: C:\Program Files (x86)\Rime\weasel-0.15.0\
Download cache directory: C:\Users\xxx\AppData\Local\Temp
Rime user directory: C:\Users\xxx\AppData\Roaming\Rime
```
`Rime user directory` 并没有使用安装时指定的用户文件夹。

**尝试修复**
在 `rime-install-config.bat` 中加入 `set rime_dir=D:\Profile\RIME`，再次安装。
方案成功安装。

**Comment by mirtlecn** [comment]
应该是 https://github.com/rime/plum 负责的，所以应该去那边提 issue。

rime-install.bat 应该不支持 recipe 式的写法，而且安装这类含有 lua 脚本的方案有问题，因为它只复制 yaml txt json 等文件，安装后应该打不了字才对。

**Comment by fxliang** [comment]
试毒点新玩具吧
https://github.com/fxliang/rppi_get
ci下有64位的构建
