### ISSUE TITLE
小狼毫 0.15 与 0.14.3 相比无法使用 symbols.yaml 里的符号配置

### ISSUE THREAD

**Issue by Gloryandel** [rime/weasel#1054]
针对方案的补丁或者直接修改：
patch:
  punctuator/import_preset: symbols # 使用此符号表
  recognizer/patterns/punct: '^/([0-9]0?|[A-Za-z]+)$'

预期行为：
1. 输入 /字符 出现 symbols 里对应的符号

实际行为：只要修改为 symbols （symbols.yaml）均无法通过编译，单改为默认的 default （punctuation.yaml）即可。

0.14.3 正常，同文输入法，中文输入法（Trime 无障碍版）均正常

需求：如果事 bug 希望能解决，或者是期望行为求新的配置方法

用的配置文件均为默认配置：
terra_pinyin.schema.yaml
terra_pinyin.dict.yaml
symbols.yaml
punctuation.yaml

**Comment by Gloryandel** [comment]
并非  yaml 语法问题。有空格的
![1702875405484](https://github.com/rime/weasel/assets/51497852/63720144-4cf8-4ce3-add6-af947f8a3016)

**Comment by fxliang** [comment]
你应该上传下你的symbols.yaml来看看。

**Comment by Gloryandel** [comment]
> 你应该上传下你的symbols.yaml来看看。 symbols.yaml是后端相关的项目，前端并不会修改这些项目的响应处理流程的东西，所以你描述的问题，大概率是你的文件存在了问题。
> 
> ![image](https://private-user-images.githubusercontent.com/4023160/291294588-df0c8fc7-21b6-448e-8d0e-8206050b7c8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTUxMDEsIm5iZiI6MTcwMjkxNDgwMSwicGF0aCI6Ii80MDIzMTYwLzI5MTI5NDU4OC1kZjBjOGZjNy0yMWI2LTQ0OGUtOGQwZS04MjA2MDUwYjdjOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMTU1MzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRlNjU0NDk2MjNmM2QyODI2NTRkY2ZhMDQ4YjNhOTgwOWE5YjEwODIwODFkNzE0MWE4ZjBlMDE1ZjU2NGI1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tQChHQn33sKxNPpW8YpxPB3LP_P6dtM_MMU-CpTQdF8)

![image](https://github.com/rime/weasel/assets/51497852/5ccd9b7e-cdd3-4917-a510-a7a99e4d8938)

**Comment by Gloryandel** [comment]
> 你应该上传下你的symbols.yaml来看看。 symbols.yaml是后端相关的项目，前端并不会修改这些项目的响应处理流程的东西，所以你描述的问题，大概率是你的文件存在了问题。
> 
> ![image](https://private-user-images.githubusercontent.com/4023160/291294588-df0c8fc7-21b6-448e-8d0e-8206050b7c8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTUxMDEsIm5iZiI6MTcwMjkxNDgwMSwicGF0aCI6Ii80MDIzMTYwLzI5MTI5NDU4OC1kZjBjOGZjNy0yMWI2LTQ0OGUtOGQwZS04MjA2MDUwYjdjOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMTU1MzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRlNjU0NDk2MjNmM2QyODI2NTRkY2ZhMDQ4YjNhOTgwOWE5YjEwODIwODFkNzE0MWE4ZjBlMDE1ZjU2NGI1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tQChHQn33sKxNPpW8YpxPB3LP_P6dtM_MMU-CpTQdF8)

我怀疑 punctuator 对象要单独成文件（官方文件是punctuation.yaml 里只包含全/半角相关配置）。但是如此不知道 symbols 怎么导入

**Comment by fxliang** [comment]
不要怀疑，方案里punctuator/import_preset: symbols 正常使用没有问题。你继续自查下了。

**Comment by Gloryandel** [comment]
> 不要怀疑，方案里punctuator/import_preset: symbols 正常使用没有问题。你继续自查下了。

感谢，对比官方文件才发现的，不知道哪个时候误输入的。
![image_11](https://github.com/rime/weasel/assets/51497852/5b6db0bb-3fab-473a-b733-81018aee4e32)
SublimeText 和 VSCode 都不会高亮提示错误😂😂
![image_13](https://github.com/rime/weasel/assets/51497852/cd620945-6226-4113-9213-b58cd4b410e5)

在哪可以查看编译日志？

**Comment by Gloryandel** [comment]
小狼毫有 Lua 脚本的扩展功能吗？似乎整个教程中都未提到？

**Comment by fxliang** [comment]
https://github.com/hchunhui/librime-lua/wiki

> 小狼毫有 Lua 脚本的扩展功能吗？似乎整个教程中都未提到？
