### ISSUE TITLE
候选词和高亮窗口左缘的空隙

### ISSUE THREAD

**Issue by ChihSee-Hsie** [rime/weasel#1061]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 23H2 22631.2861]
 - 小狼毫版本: [ 0.15.0.0 ，Commit 1e78320 ]

**描述遇到的问题**
如题，在 @fxliang 公构建的最新版本小狼毫中，候选词和高亮窗口之间出现了较大的空隙。如果用方向键选词，还会发现随着高亮窗口的移动，候选词的绝对位置会发生跳跃。具体见下图：
![候选词和候选窗之间的空隙](https://github.com/rime/weasel/assets/91021998/ecf13620-9347-4565-8b6f-0f0cdbc07d7d)

![候选词位置的左右跳跃](https://github.com/rime/weasel/assets/91021998/39baa9bd-c581-4392-8ec9-e474272e8b35)

从版本历史来看，在 [Commit CI #458](https://github.com/fxliang/weasel/actions/runs/7218490994) 及之前的几个构建版本中似乎都没有这个问题。再往前则偶见偶不见。自 [Commit CI #460](https://github.com/fxliang/weasel/actions/runs/7232618803) 开始直到最新的构建，这一问题一直出现。

**预期行为**
以下是使用 [Commit CI #458](https://github.com/fxliang/weasel/actions/runs/7218490994) 构建版本的效果（配置文件没有更动）：
![Untitled3](https://github.com/rime/weasel/assets/91021998/2b6f95b4-0eab-4443-9801-75e00cbb705f)

再次感谢 fxliang 公的贡献！

**Comment by fxliang** [comment]
https://github.com/fxliang/weasel/actions/runs/7284028666
待这个构建完可以试试，没有问题就准备合到主仓

**Comment by ChihSee-Hsie** [comment]
感谢贡献，不过我试了一下，发现虽然间隔变小了，高亮区移动时候选词的绝对位置却还是会相应地左右跳动。我感觉这个问题可能不是 mark_gap 的问题，而与 hilite_padding 或者 margin 有关，我尝试分别修改了 `spacing` 和 `hilite_spacing` 两个参数，没有发现明显的变化。

**Comment by fxliang** [comment]
> 感谢贡献，不过我试了一下，发现虽然间隔变小了，高亮区移动时候选词的绝对位置却还是会相应地左右跳动。我感觉这个问题可能不是 mark_gap 的问题，而与 hilite_padding 或者 margin 有关，我尝试分别修改了 `spacing` 和 `hilite_spacing` 两个参数，没有发现明显的变化。

不是的，这个是因为这个hilited_mark增加的空间，在horizontal布局的时候只在高亮候选上有加上，其他候选并没有加这个空间。目标是不要因为这个标识让整体的布局位置都横向增加而产生空落感。移动高亮位置的时候是触发重新计算布局，从而原来的高亮候选的框会变小，变小的尺寸会在新的高亮候选中加上。
