### ISSUE TITLE
0.15.0 版本小狼毫中候选词后部的空白消失且无法调整

### ISSUE THREAD

**Issue by suc1997** [rime/weasel#1064]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - Windows 11 22H2 22621.2861
 - 0.15.0

**描述遇到的问题**
开发者您好：
　　由 0.14.3 版本更新至 0.15.0 版本后，部分UI及相关设置项与先前版本表现不一致。

**复现步骤**
在 0.14.3 版本的小狼毫中，候选词的后部有微小的间隙，并且可以随着 style/layout/hilite_spacing 产生相应变化，如图1、2中「法」字后部所示。

![图1](https://github.com/rime/weasel/assets/25244664/faf4265b-55de-494e-8f9b-137dac29b653)
图1

![图2](https://github.com/rime/weasel/assets/25244664/71a1587f-1e06-431d-b360-bdb622730ae5)
图2

而在 0.15.0 版本中，相应的设置对应的视觉效果如图3、4所示（新增的圆角效果已经进行微调）。

![图3](https://github.com/rime/weasel/assets/25244664/d2a0dfc5-202a-4fe0-b36c-bd3c2d8f6b2f)
图3

![图4](https://github.com/rime/weasel/assets/25244664/21d695c0-7082-46dd-ad59-3b69733add15)
图4

请问在新版本中还有相关设置项可以调节相应的视觉效果吗？

十分感谢各位开发者与贡献者

**Comment by fxliang** [comment]
没有，这个是代码固化的。总体的逻辑是，padding总是最边的字符的外延距离。在没有comment的状态下，padding是从candidate的右侧开始。

事实上你所描述的0.14.3的状态是一个不合理的状态，就美观对称的逻辑，应该序号前面也加上这个hilite_spacing才是更合理的状态，然而那样更加引入不合理的状态。

**Comment by suc1997** [comment]
> 没有，这个是代码固化的。总体的逻辑是，padding总是最边的字符的外延距离。在没有comment的状态下，padding是从candidate的右侧开始。
> 
> 事实上你所描述的0.14.3的状态是一个不合理的状态，就美观对称的逻辑，应该序号前面也加上这个hilite_spacing才是更合理的状态，然而那样更加引入不合理的状态。

明白了，感谢您的解答
