### ISSUE TITLE
【快捷键】如何屏蔽 `Ctrl+space` 禁用输入法快捷键

### ISSUE THREAD

**Issue by Cierra-Runis** [rime/weasel#1065]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 23H2 23631.2861
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
`Ctrl+space` 禁用输入法，但我需要在 `vscode` 中使用该快捷键

**复现步骤**
重现问题的步骤，如：
略

**预期行为**
提供屏蔽该快捷键的方法

**Comment by spew8712** [comment]
可嘗試此處幾個方法：
https://www.zhihu.com/question/22288432
另外，此現象無關weasel或rime，是windows本身問題。

**Comment by Cierra-Runis** [comment]
> 可嘗試此處幾個方法： https://www.zhihu.com/question/22288432 另外，此現象無關weasel或rime，是windows本身問題。

非常感谢，修改注册表后解决了

**Comment by JadeYao-z** [comment]
good
