### ISSUE TITLE
`color_scheme_dark` 配置不能立即生效

### ISSUE THREAD

**Issue by RiwiHow** [rime/weasel#1066]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 23H2 22631.2861]
 - 小狼毫版本: [ 最新的 CI 版本（[1e78320](https://github.com/rime/weasel/releases/tag/latest)） ]

**描述遇到的问题**
`color_scheme_dark` 配置不能立即生效

**复现步骤**
重现问题的步骤，如：
1. 现在在 Windows 设置里面是「浅色」，输入法是 `color_scheme` 的配色
2. 改变设置为「深色」，输入法依旧是 `color_scheme` 的配色，必须手动「重启算法服务」后，输入法才能变成 `color_scheme_dark` 的配色
3. 从「深色」切换成「浅色」，也需要手动「重启算法服务」

**预期行为**
Windows 颜色改变后，应该立即切换成配置文件对应的配色

**用户文件**
`weasel.custom.yaml` 的配置如下：
```
patch:
  "style/color_scheme": google
  "style/color_scheme_dark": lost_temple
```

**Comment by fxliang** [comment]
#1055 的产出试下吧
https://github.com/rime/weasel/actions/runs/7300873202

**Comment by RiwiHow** [comment]
> https://github.com/rime/weasel/actions/runs/7300873202

我是点这个链接进去后，下载的 `artifact`。不过依旧没有解决....

**Comment by fxliang** [comment]
这么奇怪的嘛，你看pr里我放的动图里即便是方案里定义的配色（明暗）都可以即时切换了。。

**Comment by RiwiHow** [comment]
但是它就是自动变不了 😭...需要我提供什么日志吗？

![1](https://github.com/rime/weasel/assets/53964574/011c365b-7dc6-4406-bfbe-f05410482269)

**Comment by fxliang** [comment]
不知道是不是Windows11上没有了那个消息，留意这个产出看看情况
https://github.com/fxliang/weasel/actions/runs/7358175773


> 但是它就是自动变不了 😭...需要我提供什么日志吗？
> 
> ![1](https://private-user-images.githubusercontent.com/53964574/293037205-011c365b-7dc6-4406-bfbe-f05410482269.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjcyMTQsIm5iZiI6MTcwMzg2NjkxNCwicGF0aCI6Ii81Mzk2NDU3NC8yOTMwMzcyMDUtMDExYzM2NWItN2RjNi00NDA2LWJmYmUtZjA1NDEwNDgyMjY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE2MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNTJkYmE0MTZjNjY1N2M1Y2JjODgxOWYzMmQ4Y2M3MjkzYzQzNTBkY2UyYjExNDFkNDY3OTJmMzhmMmZkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGjvs6AbgeCUMOoNrhcNK2D-mAgQ6-FzR-RI2SacZOE) [ ![1](https://private-user-images.githubusercontent.com/53964574/293037205-011c365b-7dc6-4406-bfbe-f05410482269.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjcyMTQsIm5iZiI6MTcwMzg2NjkxNCwicGF0aCI6Ii81Mzk2NDU3NC8yOTMwMzcyMDUtMDExYzM2NWItN2RjNi00NDA2LWJmYmUtZjA1NDEwNDgyMjY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE2MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNTJkYmE0MTZjNjY1N2M1Y2JjODgxOWYzMmQ4Y2M3MjkzYzQzNTBkY2UyYjExNDFkNDY3OTJmMzhmMmZkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGjvs6AbgeCUMOoNrhcNK2D-mAgQ6-FzR-RI2SacZOE) ](https://private-user-images.githubusercontent.com/53964574/293037205-011c365b-7dc6-4406-bfbe-f05410482269.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjcyMTQsIm5iZiI6MTcwMzg2NjkxNCwicGF0aCI6Ii81Mzk2NDU3NC8yOTMwMzcyMDUtMDExYzM2NWItN2RjNi00NDA2LWJmYmUtZjA1NDEwNDgyMjY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE2MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNTJkYmE0MTZjNjY1N2M1Y2JjODgxOWYzMmQ4Y2M3MjkzYzQzNTBkY2UyYjExNDFkNDY3OTJmMzhmMmZkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGjvs6AbgeCUMOoNrhcNK2D-mAgQ6-FzR-RI2SacZOE) [ ](https://private-user-images.githubusercontent.com/53964574/293037205-011c365b-7dc6-4406-bfbe-f05410482269.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjcyMTQsIm5iZiI6MTcwMzg2NjkxNCwicGF0aCI6Ii81Mzk2NDU3NC8yOTMwMzcyMDUtMDExYzM2NWItN2RjNi00NDA2LWJmYmUtZjA1NDEwNDgyMjY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE2MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNTJkYmE0MTZjNjY1N2M1Y2JjODgxOWYzMmQ4Y2M3MjkzYzQzNTBkY2UyYjExNDFkNDY3OTJmMzhmMmZkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGjvs6AbgeCUMOoNrhcNK2D-mAgQ6-FzR-RI2SacZOE)

**Comment by RiwiHow** [comment]
> 不知道是不是 Windows11 上没有了那个消息，留意这个产出看看情况

问题解决了，感谢 👍
![2](https://github.com/rime/weasel/assets/53964574/08a21fea-5ab0-4dce-89d7-2d87591a8ff4)
