### ISSUE TITLE
最新构建在QQNT下无法正常工作

### ISSUE THREAD

**Issue by Parsifa1** [rime/weasel#1067]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: 23h2 22631.2861
 - 小狼毫版本: 1e78320

**描述遇到的问题**
在QQNT中无法正常输入中文

**截图**
![image](https://github.com/rime/weasel/assets/31800073/78868345-f6d6-41a8-91fb-1767823d92df)

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by RiwiHow** [comment]
似乎是正常工作的，不过我用的是 12.22 的 CI [构建](https://github.com/rime/weasel/actions/runs/7300873202)
![2](https://github.com/rime/weasel/assets/53964574/5f6d5569-6e98-4676-8885-3673ecefc6e6)
