### ISSUE TITLE
[TSF] Results of auto-selection cleared by subsequent manual selection

### ISSUE THREAD

**Issue by sbxlmdsl** [rime/weasel#107]
Downloaded the newest version Weasel by Nameoverflow. It can work nice on Windows 10 Edge and Notepad. Excited for your great job. But for TSF and Edge, when inputting  Chinese characters with auto selection followed by space selection, only the last character retains and all others get lost.

**Comment by sbxlmdsl** [comment]
Submitted this issue on the other thread about the newest version.

**Comment by nameoverflow** [comment]
这确实是个问题，应该作为一个 issue。

**Comment by nameoverflow** [comment]
来自贴吧的动图：

![](http://imgsrc.baidu.com/forum/w%3D580/sign=52a2082f86b1cb133e693c1bed5556da/c1e31bf33a87e950532090ac1b385343faf2b41a.jpg)
