### ISSUE TITLE
在部分应用中，小狼毫输出的字变成乱码

### ISSUE THREAD

**Issue by cangzhouyuhe** [rime/weasel#1072]
在IDM下载框中，使用小狼毫输入文字，有的文字会变成乱码无法显示。图1、2
请问应该如何解决？
![截图_20240105134436](https://github.com/rime/weasel/assets/50189901/00d1f481-5258-4673-aa93-bebbe31cdd09)
![image](https://github.com/rime/weasel/assets/50189901/b35c3439-9e57-44af-9615-8af935311819)

**Comment by yanhuacuo** [comment]
将 IDM 升级到 V6.42 即可，这是 IDM 的一个 bug
