### ISSUE TITLE
外接屏幕的切换会导致算法服务失效

### ISSUE THREAD

**Issue by SnakeHit** [rime/weasel#1073]
windows版本：Microsoft Windows 版本21H2(0S内部版本22000.2538)
小狼毫版本：1.5.0.0

**描述遇到的问题**

外接屏幕的切换会导致算法服务失效（即按shift无法切换中文输入，重启后恢复）

![image](https://github.com/rime/weasel/assets/45898625/b8150865-327d-458f-adf7-e46acf1ad005)

**Comment by fxliang** [comment]
日常双屏，未发现问题。或者试试nightly构建？

**Comment by SnakeHit** [comment]
> 日常双屏，未发现问题。或者试试nightly构建？

感谢回复，那可能是别的原因导致的，请问有办法捕捉错误原因吗

**Comment by QianmuZ** [comment]
类似的问题，我是远程桌面连接的时候有问题，需要重启算法服务，可能跟远程的时候分辨率不一样有关，具体原因未知

**Comment by fxliang** [comment]
怎么个远程？我之前有用向日葵问题不大。
另外是最新构建的版本吗？

**Comment by QianmuZ** [comment]
> 怎么个远程？我之前有用向日葵问题不大。 另外是最新构建的版本吗？

使用便携机mstsv远程台式机，台式机1920*1080，便携机2K，版本是上一个nightly版本

**Comment by fxliang** [comment]
好，有空修修

**Comment by fxliang** [comment]
留意这个ci的产出，看看是不是解决了。
https://github.com/fxliang/weasel/actions/runs/7456434250
@QianmuZ @SnakeHit

**Comment by QianmuZ** [comment]
> 留意这个ci的产出，看看是不是解决了。 https://github.com/fxliang/weasel/actions/runs/7456434250 @QianmuZ @SnakeHit

我这边还是不行

**Comment by fxliang** [comment]
> > 留意这个ci的产出，看看是不是解决了。 https://github.com/fxliang/weasel/actions/runs/7456434250 @QianmuZ @SnakeHit
> 
> 我这边还是不行

https://github.com/fxliang/weasel/actions/runs/7468810882
这个应该是可以解决的，但是我不确定这样会不会有点卡

**Comment by QianmuZ** [comment]
> > > 留意这个ci的产出，看看是不是解决了。 https://github.com/fxliang/weasel/actions/runs/7456434250 @QianmuZ @SnakeHit
> > 
> > 
> > 我这边还是不行
> 
> https://github.com/fxliang/weasel/actions/runs/7468810882 这个应该是可以解决的，但是我不确定这样会不会有点卡

很遗憾，还是不行

**Comment by fxliang** [comment]
如果是这样，那就不是UI的问题了。原来我猜想是显示设置变化之后导致Direct2D的资源失效，我最后让你试的那个就已经是每次候选窗口消失就会重新创建Direct2D资源的了……

**Comment by rebron1900** [comment]
> 如果是这样，那就不是UI的问题了。原来我猜想是显示设置变化之后导致Direct2D的资源失效，我最后让你试的那个就已经是每次候选窗口消失就会重新创建Direct2D资源的了……

我目前是多显示器使用，每次系统启动都无法正常启动小狼毫算法服务，而且把算法服务创建快捷方式丢到shell:startup里还不行，只能使用计划任务延迟10秒左右启动。

但是这种方式只能在开机的时候启动，如果中途算法服务挂掉了的话又会出现无法输入中文的问题。

所以我写了个用于保活的脚本，希望官方能在下个版本修复一下这个问题：

```
# 配置进程名、路径和循环检测间隔
$processName = "WeaselServer"
$processPath = "C:\Program Files (x86)\Rime\weasel-0.15.0\WeaselServer.exe"
$intervalInSeconds = 10

function Start-WeaselServer {
    Start-Process -FilePath $processPath -NoNewWindow
}

while ($true) {
    $process = Get-Process -Name $processName -ErrorAction SilentlyContinue
    if (!$process) {
        Write-Output "WeaselServer process not found, starting..."
        Start-WeaselServer
    }
    Start-Sleep -Seconds $intervalInSeconds
}
```

**Comment by fxliang** [comment]
其实我已用双屏工作很多很多年，但是从未发生过无法启动服务的问题。从技术层面来说，加保活相关的代码没有难度，但是会将背后的根本原因永远的埋了，从而永远没有机会再修好，这个可能不是最优解。

关于自动启动相关，我用的是bat脚本处理，只有一句,可供参考
```bat
	REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Run /v WeaselServer /d "%~dp0%INSTVER%\WeaselServer.exe" /f
```

**Comment by SnakeHit** [comment]
> 其实我已用双屏工作很多很多年，但是从未发生过无法启动服务的问题。从技术层面来说，加保活相关的代码没有难度，但是会将背后的根本原因永远的埋了，从而永远没有机会再修好，这个可能不是最优解。
> 
> 关于自动启动相关，我用的是bat脚本处理，只有一句,可供参考
> 
> ```batchfile
> 	REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Run /v WeaselServer /d "%~dp0%INSTVER%\WeaselServer.exe" /f
> ```

在我的电脑上，即使不开双屏，单单笔记本一个屏幕，如果toggle这个任务栏自动隐藏开关也会造成算法服务失效，必须重启算法服务恢复
![image](https://github.com/rime/weasel/assets/45898625/7bd23594-a1af-43e2-ad53-d17e39b9cf69)

**Comment by rebron1900** [comment]
这个问题不少人都碰到过，应该要好好排查一下。

**Comment by fxliang** [comment]
排查的基础是可复现故障，那个状态栏自动隐藏的设置我试了但是没有复现提及的问题。等能稳定复现的高手出手修了。

**Comment by rebron1900** [comment]
> 排查的基础是可复现故障，那个状态栏自动隐藏的设置我试了但是没有复现提及的问题。等能稳定复现的高手出手修了。

我可以稳定复现，但是不知道怎么排查

**Comment by rebron1900** [comment]
我的情况是：
- 主电脑是个ROG幻X平板，通过dockhub链接了一个vga显示器
- 投影模式是扩展
- 外接的显示器作为主显示器。

根据上面的设置后稳定复现过程：
- 断开拓展坞电源，此时外接屏幕熄屏，主画面闪烁完后显示在平板上，通过任务管理器检查，小狼毫算法服务存活
- 接上拓展坞电源，平板画面闪烁，外接屏亮起，主画面显示在外接屏幕上，此时再查看任务管理器，算法服务已经挂了。

**Comment by rebron1900** [comment]
想看看日志是否有变化，所以进行了第二次尝试。
- 关掉算法服务，删除temp目录中的rime日志文件
- 重新启动算法服务，新日志产生，内容看下方截图。
- 重复上面提到的复现过程
- 检查日志，此时日志没有任何变化。

![PixPin_2024-01-23_12-31-11](https://github.com/rime/weasel/assets/7929884/b52a78d2-f66f-483f-844c-0380d242ce33)

![PixPin_2024-01-23_12-31-21](https://github.com/rime/weasel/assets/7929884/7a5ff24e-bb71-411d-bd96-cf92fc156b3b)

**Comment by fxliang** [comment]
有一个略麻烦的排查是，跟着主线ci的产物，折中测试定位出第一个出现这个bug的commit,发出来。

**Comment by samb233** [comment]
关于这一点我可以提供一点信息。
在前几天算法服务频繁闪退后，我回退到了 https://github.com/rime/weasel/actions/runs/7269518512 这个action下的版本，在我的机器上没有再闪退。

最新的pre-release在我笔记本用雷电口外接显示器时，算法服务100%会闪退

**Comment by fxliang** [comment]
再反复取中值试到具体那个时候开始必现。。。

**Comment by fxliang** [comment]
https://github.com/fxliang/weasel/actions/runs/7633990194

可以试试这个的产出。在我电脑上可以通过修改输出屏幕状态（单1单2扩展切换）复现的，这个之后故障基本消失。

**Comment by SnakeHit** [comment]
> https://github.com/fxliang/weasel/actions/runs/7633990194
> 
> 可以试试这个的产出。在我电脑上可以通过修改输出屏幕状态（单1单2扩展切换）复现的，这个之后故障基本消失。
> 
> 另外有Windows11的话看看 #1066 的问题状态

使用这个产出，目前在我的电脑上故障也基本消失了，感谢👍

**Comment by rebron1900** [comment]
> https://github.com/fxliang/weasel/actions/runs/7633990194
> 
> 可以试试这个的产出。在我电脑上可以通过修改输出屏幕状态（单1单2扩展切换）复现的，这个之后故障基本消失。
> 
> 另外有Windows11的话看看 #1066 的问题状态

没问题了，我是windows11，颜色问题我测试了一下可以实时变化。
