### ISSUE TITLE
我找不到相关的任何问题可以参考，来求助一下，关于切换繁简时的外观。

### ISSUE THREAD

**Issue by LO-H-W** [rime/weasel#1076]
请问哪里可以更改这个切换简繁时显示的文字？

![螢幕擷取畫面 2024-01-07 182015](https://github.com/rime/weasel/assets/154674265/a3ae673f-30e6-46f2-8918-9b29f0668218)

例如把现在的
                      「汉字」、「漢字」，改为
                      「简」、「繁」。
                      
不知道有什么方法可以实现上述更动呢？具体是要到哪个地方去修改？谢谢。

**Comment by fxliang** [comment]
这个部分目前还是硬编码，代码写死的。

如果是nightly 构建的基础上，注释掉下面链接的代码，重新构建，替换WeaselServer.exe，就可以了。全半角那个硬编码还有另外一个地方关联别注释(

https://github.com/rime/weasel/blob/master/RimeWithWeasel/RimeWithWeasel.cpp#L682-L689

**Comment by LO-H-W** [comment]
谢谢回复，不过你说的意思是指我把你连接的资料下载下来，注释掉标注的8行，然后替代程序文件夹中的“WeaselServer.exe”是吗？

**Comment by fxliang** [comment]
> 谢谢回复，不过你说的意思是指我把你连接的资料下载下来，注释掉标注的8行，然后替代程序文件夹中的“WeaselServer.exe”是吗？

额，好吧。请等更新，别乱来。上面是指自行编译构建的

**Comment by LO-H-W** [comment]
好的，谢谢
