### ISSUE TITLE
新手发问，请问我可以直接更改xxx.scgema.Yaml这里的文字改变方案的显示字体吗？

### ISSUE THREAD

**Issue by LO-H-W** [rime/weasel#1078]
我的方案只要切换到繁体打些字都会显示得很不常用，「床、牀」，「群、羣」，「麵、麪」诸如此类的状况，
我是否可以直接更改xxx.scgema.Yaml中switches的选项，并在engine中更改相应的名称来实现呢？
我没办法成功，是方法不对还是哪里输入错误了呢？

![1](https://github.com/rime/weasel/assets/154674265/493ffd6f-7772-4d1b-9523-4d5a2607d409)
![2](https://github.com/rime/weasel/assets/154674265/05065176-41bc-4b18-9854-d32ee3893c5a)

我把这边的文字改成

![3](https://github.com/rime/weasel/assets/154674265/24cded6f-1c27-4582-a2c4-bd6d5709c306)
![4](https://github.com/rime/weasel/assets/154674265/42bc5d40-41ce-42f6-8fa9-2312254ec5f4)

恳请麻烦解惑，谢谢了。

**Comment by NSIOISN** [comment]
我建议你安装雾凇拼音，那边对简繁转换有更好的方案。

https://github.com/iDvel/rime-ice/issues/575

**Comment by LO-H-W** [comment]
謝謝您，完美解決我的需求。

**Comment by LO-H-W** [comment]
> 我的方案只要切换到繁体打些字都会显示得很不常用，「床、牀」，「群、羣」，「麵、麪」诸如此类的状况， 我是否可以直接更改xxx.scgema.Yaml中switches的选项，并在engine中更改相应的名称来实现呢？ 我没办法成功，是方法不对还是哪里输入错误了呢？
> 
> ![1](https://private-user-images.githubusercontent.com/154674265/294919638-493ffd6f-7772-4d1b-9523-4d5a2607d409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Mjc3ODQsIm5iZiI6MTcwNDgyNzQ4NCwicGF0aCI6Ii8xNTQ2NzQyNjUvMjk0OTE5NjM4LTQ5M2ZmZDZmLTc3NzItNGQxYi05NTIzLTRkNWEyNjA3ZDQwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxOTExMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTIxODczOWRhYjM3N2I4ZjJkOGFhMWQ2NTFmOGRmMzAyMjIwMWE3Yjc2ZWI3Yzc3YTM5NDg0ZTIyODk2YTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6AlLb2pixQJm79y-brOf9DPkGi6xdTRsNNXj8UwJemw) ![2](https://private-user-images.githubusercontent.com/154674265/294919665-05065176-41bc-4b18-9854-d32ee3893c5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Mjc3ODQsIm5iZiI6MTcwNDgyNzQ4NCwicGF0aCI6Ii8xNTQ2NzQyNjUvMjk0OTE5NjY1LTA1MDY1MTc2LTQxYmMtNGIxOC05ODU0LWQzMmVlMzg5M2M1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxOTExMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjAzNjIwOTE3YWZlM2I3MjMzYTc1ZjM5ZDY2ZjI5YTVlOWZhOTA1NmU3Y2M2YmRkZGNhOTM1NTRlNTIxZjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-dL5rsP4vpGhVrluyr7v9H9SOJGwnNT8JHZaFWJgTvo)
> 
> 我把这边的文字改成
> 
> ![3](https://private-user-images.githubusercontent.com/154674265/294919870-24cded6f-1c27-4582-a2c4-bd6d5709c306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Mjc3ODQsIm5iZiI6MTcwNDgyNzQ4NCwicGF0aCI6Ii8xNTQ2NzQyNjUvMjk0OTE5ODcwLTI0Y2RlZDZmLTFjMjctNDU4Mi1hMmM0LWJkNmQ1NzA5YzMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxOTExMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2VjYjc4NzNlZDExYjJiY2RmZWZmMTk3NWMyNzdjNWU5NWM0NWZmYmQxZTQ4NmJhZjljZDFlZDg4Y2YxYWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZHiNQVL5tiGOZb5-G5LLGy6Jwvb5d3aJ2q8VFKmhV5U) ![4](https://private-user-images.githubusercontent.com/154674265/294919942-42bc5d40-41ce-42f6-8fa9-2312254ec5f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Mjc3ODQsIm5iZiI6MTcwNDgyNzQ4NCwicGF0aCI6Ii8xNTQ2NzQyNjUvMjk0OTE5OTQyLTQyYmM1ZDQwLTQxY2UtNDJmNi04ZmE5LTIzMTIyNTRlYzVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxOTExMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzcxYWY0OGYzZjYwMmQ1ZmE4NDczN2QyMjE2ZTE0M2JjZTdjOTk2ZmIyZTEyNWFjYWY4OTg1ODBmYjAxZTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4vzXeCbU-NU-0vFSwpU14uupFGUMuU5mmXxXgwlc6vw)
> 
> 恳请麻烦解惑，谢谢了。
