### ISSUE TITLE
「功能询问/请求」如何关闭输入法自带的英文输入，实现只有中文输入。

### ISSUE THREAD

**Issue by OcrSu** [rime/weasel#1084]
我目前的使用习惯是，Win+Space切换中英文输入，而不是切换到输入法自带的英文输入。
虽然rime没有在特定场景中自动切换到英文输入的特性，从而影响到我的使用习惯。
但我觉得如果能彻底关闭输入法自带的英文输入方式是最好的（来自我的一点小强迫症）

**Comment by lotem** [comment]
在系統裏設置一個英文鍵盤, 一個小狼毫, 而後用 Win+Space 就可以在系統層面切換中英文了.

**Comment by OcrSu** [comment]
> 在系統裏設置一個英文鍵盤, 一個小狼毫, 而後用 Win+Space 就可以在系統層面切換中英文了.

我知道这个方法，且一直是这么使用的。

但，如果输入法能提供关闭自带英文输入功能就好了，

这样会避免因为 某些时候 按错shift等按键导致为英文输入状态，连续按win + space好几次也找不到哪个是中文输入法，需要用眼睛去看状态栏确认后，再切换回中文输入法状态才可以。

**Comment by lotem** [comment]
Shift做狀態切換是可以配置的. 默認的配置在這裏:

https://github.com/rime/rime-prelude/blob/dd84abecc33f0b05469f1d744e32d2b60b3529e3/default.yaml#L60

如果只是不想用 Shift 切換, 可以在輸入方案裏把單擊 `Shift_L`, `Shift_R` 的動作重設爲 `noop`.
在問題裏搜 `ascii_composer/switch_key` 別的回答.

另外通過方案選單也可以改變中西文轉換狀態. 這取決於方案裏是否設有`ascii_mode` 這項開關.

**Comment by mirtlecn** [comment]
- 在 default.yaml 中将 ascii_composer/switch_key 所有按键都设置为 noop
- 删除 schema.yaml 中对于 ASCII mode 的 switch 选项
- 将 key_binder/bindings 关于 ascii_mode 按键设置为一个不常用的按键组合
- 在 weasel.yaml 里面将 app_options 中关于 ascii_mode 的行全部删除

绝大部分情况下不会切换为英文模式了，但是碰到过有一些应用会将输入法强制调整为英文模式

**Comment by OcrSu** [comment]
> * 在 default.yaml 中将 ascii_composer/switch_key 所有按键都设置为 noop
> * 删除 schema.yaml 中对于 ASCII mode 的 switch 选项
> * 将 key_binder/bindings 关于 ascii_mode 按键设置为一个不常用的按键组合
> * 在 weasel.yaml 里面将 app_options 中关于 ascii_mode 的行全部删除
> 
> 绝大部分情况下不会切换为英文模式了，但是碰到过有一些应用会将输入法强制调整为英文模式

我会尝试的，谢谢。

纯中文输入应该能规避很多问题,不过我现在没有时间研究定制输入方案。

**Comment by TsuZing** [comment]
> Shift做狀態切換是可以配置的. 默認的配置在這裏:
> 
> https://github.com/rime/rime-prelude/blob/dd84abecc33f0b05469f1d744e32d2b60b3529e3/default.yaml#L60
> 
> 如果只是不想用 Shift 切換, 可以在輸入方案裏把單擊 `Shift_L`, `Shift_R` 的動作重設爲 `noop`. 在問題裏搜 `ascii_composer/switch_key` 別的回答.
> 
> 另外通過方案選單也可以改變中西文轉換狀態. 這取決於方案裏是否設有`ascii_mode` 這項開關.

关闭快捷键并不能关闭英文模式本身。除了输入法自己的快捷键，Windows也提供了切换中英文的API，大部分国产游戏会在离开输入框后自动切换为英文模式，某些情况会和英文键盘冗余甚至冲突，导致需要手动按中英文切换键或者切换两次输入法才能切换回中文模式。小狼毫和部分程序也有不明BUG，如果在选字框显示的时候单击输入框外中断输入，那么小狼毫也会变成英文模式。目前来看唯一彻底的解法就是关闭英文模式

**Comment by lotem** [comment]
可以的。

輸入方案裏，`switches` 部分不設置 `ascii_mode` 開關；`engine/processors` 不添加 `ascii_composer` 組件。

**Comment by liuliping0315** [comment]
我在windows上没有遇到楼主的问题，从其他输入法切换到小狼毫之后，它一定是中文状态。但是微软拼音不行，我完全无法接受微软拼音。在linux中rime的表现和微软拼音类似，没弄明白。
