### ISSUE TITLE
在自动插入空格的网页上输入时重复上屏

### ISSUE THREAD

**Issue by carica** [rime/weasel#1085]
**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [ ] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ 运行 winver.exe 获取，如 Windows 1022H2 19045]
 - 小狼毫版本: https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.006-installer_x64.exe

**描述遇到的问题**
google contacts网页版中输入电话号码时，由于自动插入空格，导致数字重复上屏。如打139222，会在输入第一个2的时候上屏2个“2”

**Comment by Techince** [comment]
抱歉，我这里无法访问google的网页，没办法测试。
又上传了个新版本，还是那个下载链接，可以试用一下。

**Comment by Techince** [comment]
> > 抱歉，我这里无法访问google的网页，没办法测试。 又上传了个新版本，还是那个下载链接，可以试用一下。
> 
> 还是一样的问题，找了个示例地址：https://react-international-phone-storybook.vercel.app/?path=/story/phoneinput--default

我这里打不开你发的这个链接。
[日志版输入模块](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weaselx64.dll)
你可以下载这个日志版模块，将「System32\weasel.dll」备份一下，用这个替换它。（操作这一步时，小狼毫不能为当前活动输入法）
1、重启浏览器，打开那个网页。
2、切换至小狼毫输入法，输入内容，直式「重复上屏」事件触发。
3、切换至别的输入法，关闭浏览器。
4、打开「%temp%」目录，找到「TextSetviceFramework.log.*」开头的日志，将日志文件发到这里就行。

**Comment by carica** [comment]
> > > 抱歉，我这里无法访问google的网页，没办法测试。 又上传了个新版本，还是那个下载链接，可以试用一下。
> > 
> > 
> > 还是一样的问题，找了个示例地址：https://react-international-phone-storybook.vercel.app/?path=/story/phoneinput--default
> 
> 我这里打不开你发的这个链接。 [日志版输入模块](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weaselx64.dll) 你可以下载这个日志版模块，将「System32\weasel.dll」备份一下，用这个替换它。（操作这一步时，小狼毫不能为当前活动输入法） 1、重启浏览器，打开那个网页。 2、切换至小狼毫输入法，输入内容，直式「重复上屏」事件触发。 3、切换至别的输入法，关闭浏览器。 4、打开「%temp%」目录，找到「TextSetviceFramework.log.*」开头的日志，将日志文件发到这里就行。

[TextServiceFramework.log](https://github.com/rime/weasel/files/14039662/TextServiceFramework.log)

**Comment by Techince** [comment]
> > > > 抱歉，我这里无法访问google的网页，没办法测试。 又上传了个新版本，还是那个下载链接，可以试用一下。
> > > 
> > > 
> > > 还是一样的问题，找了个示例地址：https://react-international-phone-storybook.vercel.app/?path=/story/phoneinput--default
> > 
> > 
> > 我这里打不开你发的这个链接。 [日志版输入模块](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weaselx64.dll) 你可以下载这个日志版模块，将「System32\weasel.dll」备份一下，用这个替换它。（操作这一步时，小狼毫不能为当前活动输入法） 1、重启浏览器，打开那个网页。 2、切换至小狼毫输入法，输入内容，直式「重复上屏」事件触发。 3、切换至别的输入法，关闭浏览器。 4、打开「%temp%」目录，找到「TextSetviceFramework.log.*」开头的日志，将日志文件发到这里就行。
> 
> [TextServiceFramework.log](https://github.com/rime/weasel/files/14039662/TextServiceFramework.log)

这个日志只记录到了输入了一个“[”，然后输入法又重新加载了一次，接着又输入了一个数字“1”就退出了，没有记录到重复输入的数字呀。

**Comment by carica** [comment]
> > > > > 抱歉，我这里无法访问google的网页，没办法测试。 又上传了个新版本，还是那个下载链接，可以试用一下。
> > > > 
> > > > 
> > > > 还是一样的问题，找了个示例地址：https://react-international-phone-storybook.vercel.app/?path=/story/phoneinput--default
> > > 
> > > 
> > > 我这里打不开你发的这个链接。 [日志版输入模块](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weaselx64.dll) 你可以下载这个日志版模块，将「System32\weasel.dll」备份一下，用这个替换它。（操作这一步时，小狼毫不能为当前活动输入法） 1、重启浏览器，打开那个网页。 2、切换至小狼毫输入法，输入内容，直式「重复上屏」事件触发。 3、切换至别的输入法，关闭浏览器。 4、打开「%temp%」目录，找到「TextSetviceFramework.log.*」开头的日志，将日志文件发到这里就行。
> > 
> > 
> > [TextServiceFramework.log](https://github.com/rime/weasel/files/14039662/TextServiceFramework.log)
> 
> 这个日志只记录到了输入了一个“[”，然后输入法又重新加载了一次，接着又输入了一个数字“1”就退出了，没有记录到重复输入的数字呀。

输入只有1个1，但是上屏是2个1……

**Comment by Techince** [comment]
> > > > > > 抱歉，我这里无法访问google的网页，没办法测试。 又上传了个新版本，还是那个下载链接，可以试用一下。
> > > > > 
> > > > > 
> > > > > 还是一样的问题，找了个示例地址：https://react-international-phone-storybook.vercel.app/?path=/story/phoneinput--default
> > > > 
> > > > 
> > > > 我这里打不开你发的这个链接。 [日志版输入模块](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weaselx64.dll) 你可以下载这个日志版模块，将「System32\weasel.dll」备份一下，用这个替换它。（操作这一步时，小狼毫不能为当前活动输入法） 1、重启浏览器，打开那个网页。 2、切换至小狼毫输入法，输入内容，直式「重复上屏」事件触发。 3、切换至别的输入法，关闭浏览器。 4、打开「%temp%」目录，找到「TextSetviceFramework.log.*」开头的日志，将日志文件发到这里就行。
> > > 
> > > 
> > > [TextServiceFramework.log](https://github.com/rime/weasel/files/14039662/TextServiceFramework.log)
> > 
> > 
> > 这个日志只记录到了输入了一个“[”，然后输入法又重新加载了一次，接着又输入了一个数字“1”就退出了，没有记录到重复输入的数字呀。
> 
> 输入只有1个1，但是上屏是2个1……

还是原链接，又上传了一个，你测试一下。

**Comment by carica** [comment]
> > > > > > > 抱歉，我这里无法访问google的网页，没办法测试。 又上传了个新版本，还是那个下载链接，可以试用一下。
> > > > > > 
> > > > > > 
> > > > > > 还是一样的问题，找了个示例地址：https://react-international-phone-storybook.vercel.app/?path=/story/phoneinput--default
> > > > > 
> > > > > 
> > > > > 我这里打不开你发的这个链接。 [日志版输入模块](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weaselx64.dll) 你可以下载这个日志版模块，将「System32\weasel.dll」备份一下，用这个替换它。（操作这一步时，小狼毫不能为当前活动输入法） 1、重启浏览器，打开那个网页。 2、切换至小狼毫输入法，输入内容，直式「重复上屏」事件触发。 3、切换至别的输入法，关闭浏览器。 4、打开「%temp%」目录，找到「TextSetviceFramework.log.*」开头的日志，将日志文件发到这里就行。
> > > > 
> > > > 
> > > > [TextServiceFramework.log](https://github.com/rime/weasel/files/14039662/TextServiceFramework.log)
> > > 
> > > 
> > > 这个日志只记录到了输入了一个“[”，然后输入法又重新加载了一次，接着又输入了一个数字“1”就退出了，没有记录到重复输入的数字呀。
> > 
> > 
> > 输入只有1个1，但是上屏是2个1……
> 
> 还是原链接，又上传了一个，你测试一下。（安装包）

修复了，感恩的心。
