### ISSUE TITLE
方案补丁里的配色指令失效

### ISSUE THREAD

**Issue by yanhuacuo** [rime/weasel#1086]
https://github.com/rime/weasel/actions/runs/7581892307

上面节点的版本有如下问题：方案补丁里的配色指令失效

方案A.custom.yaml 中特别指定了主题 A，
方案B.custom.yaml 中特别指定了主题 B。

当前使用【方案A】时，主题A 正在生效中，ctrl + ` 切换到【方案B】后，方案B.custom.yaml 中特别指定的主题B，未能生效。

weasel.custom.yaml 重新掌管了最高权限，这是很久以前旧版的特点。

**Comment by fxliang** [comment]
使用公共配色和方案内配色测试，均未复现问题，请再自查配置

![abcf](https://github.com/rime/weasel/assets/4023160/b3b91795-fa1f-4b48-8f97-4c361fdbe433)
![abcf2](https://github.com/rime/weasel/assets/4023160/5fba408f-aa5a-4ea1-a88e-1e04d096cf3f)

**Comment by yanhuacuo** [comment]
win11 的 C 库好像出了问题，重做系统后解决掉了，可以正常使用了。
