### ISSUE TITLE
Firefox 下部分网页中候选框無法正确定位

### ISSUE THREAD

**Issue by dec32** [rime/weasel#1087]
**上报前请检查**

- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**

 - OS 版本：Windows 10 22H2 19045.3930
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**

Firefox 下部分网页中候选框無法正确定位

**复现步骤**

1. 启動 Firefox 访问 google.com
2. 在搜索栏任意输入一些内容，但不按空格提交
3. 此时可以観察到候选框浮動在屏幕左上角
4. 按空格提交，然後再任意输入一些内容
5. 此後候选框位置正常

**截图**

![](https://github.com/rime/weasel/assets/56337978/c63dd7ce-d165-46a1-9456-25d76b8dfa29)
![](https://github.com/rime/weasel/assets/56337978/16e2191e-094b-4ee2-a09f-87c94f43b842)

**其他补充说明**

在其他网站的输入框这一问题也偶有発生，不過概率很低，在 google 则是必现

**Comment by Techince** [comment]
试试这个版本。
[Weasel_x64.exe](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.006-installer_x64.exe)
建议使用inline_preedit: true风格的候选框。有些网页的编辑控件不允许插入「空白」哑字符，插入的话会被浏览器直接结束本次合成，现象就是那个编辑框里输入法不上内容。但大多数编辑控件在inline_preedit: flase风格中必须插入一个哑字符才能获取到正确的焦点坐标。使用inline_predit: true风格就不存在此问题，输入的合成码直接被插入到上下文中，焦点坐标会不断更新。

**Comment by dec32** [comment]
这个版本确实可以，感谢
