### ISSUE TITLE
根据install md 步骤，build fail 但是无法翻译 error 意义

### ISSUE THREAD

**Issue by joejztang** [rime/weasel#1088]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 19045.2965
 - 小狼毫版本: 9061a1aa1e5f1787f6045de86f9c249f9fbd400e

**描述遇到的问题**
根据 https://github.com/rime/weasel/blob/master/INSTALL.md 按步骤进行安装，build fail，但是不知道怎样翻译以下error。
[error.txt](https://github.com/rime/weasel/files/14042396/error.txt)

**复现步骤**
根据[install md](https://github.com/rime/weasel/blob/master/INSTALL.md)的步骤执行，直到build。
我的build方法，在vs 2019里面 Tools -> Command Line -> Developer Command Prompt。然后输入 .\build.bat all

**预期行为**
output\archives 里面有installer生成。

**用户文件**

**截图**
![error](https://github.com/rime/weasel/assets/14283647/335ed8e3-7cd1-44f7-8c3d-dcad91a3478a)

**其他补充说明**
1. vs 2019
2. boost 1.84.0
3. python 3.12

非常感谢！

**Comment by Techince** [comment]
你没设置NSI路径。

**Comment by joejztang** [comment]
感谢！
