### ISSUE TITLE
show_notifications_when 选项在最新 CI 构建版本中失效

### ISSUE THREAD

**Issue by Robotxm** [rime/weasel#1090]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 23H2 22635.3066
 - 小狼毫版本: 0.15.0.0，a5af53e

**描述遇到的问题**
设置了 `show_notifications_when` 为 `never` 但切换中英文时还是会在输入框有提示。

**复现步骤**
1. 在配置文件中设置 `show_notifications_when` 为 `never`
2. 在任意应用程序中使用 Shift 进行中英文你切换

**预期行为**
在 `show_notifications_when` 为 `never` 的时候不展示中英文状态提示。

**用户文件**

**截图**

**其他补充说明**
在 `fb80f61` 这个提交里发现了与 `state_label` 相关的改动，不知道和这个有没有关系

**Comment by Robotxm** [comment]
> #1055 因为功能上和这个key原来在squirrel里的作用不一样，为避免误解调整了。

感谢解答，设置 `show_notifications` 为 `false` 之后成功了。

**Comment by ZhangTianrong** [comment]
设置 `show_notifications: false` 似乎无效。
