### ISSUE TITLE
在OneNote中使用有bug

### ISSUE THREAD

**Issue by bladeyon** [rime/weasel#1092]
**描述遇到的问题**
在OneNote中输入，不显示候选面板（一直闪），确定输入后（敲空格键），内容重复

**操作系统信息**
 - OS 详细版本: Windows 11 22H2 22621.3007
 - 小狼毫版本: 0.15.0.0 
 - OneNote版本：Microsoft® OneNote® 适用于 Microsoft 365MSO (版本 2312 Build 16.0.17126.20132) 64 位

![20240126](https://github.com/rime/weasel/assets/22049187/041d8966-94f4-46a8-926c-dee1978215b6)

**Comment by Techince** [comment]
删除「System32\weasel.ime」文件即可。
你的版本有点老了，新版本已经不安装此文件了。
