### ISSUE TITLE
無法打出「祕」

### ISSUE THREAD

**Issue by franksushiboycom** [rime/weasel#1094]
**操作系统信息**
 - OS 详细版本: Windows 11 23H2 22631.3085
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
候選字不會出現「祕」
臺灣使用「祕」書，小狼毫只能打出「秘」書
自定義「祕書」，小狼毫打出來也會自動轉成「秘書」

![mishu](https://github.com/rime/weasel/assets/55827794/2df794fb-8972-40a6-bb72-631bd8c1c418)

**Comment by Techince** [comment]
「祕書」
![image](https://github.com/rime/weasel/assets/12376669/e2a695f0-5dc6-4943-b3fb-dac228da1101)

**Comment by franksushiboycom** [comment]
研究了一下，發現問題出在 opencc TWVariants.ocd2。
後來解決方法是，在 TWVariants.ocd2 裡面追加「秘」「祕」之對應。
如果不想動 ocd2，也可以去 opencc 的 github 下載 TWVariants.txt，在 TWVariants.txt 最後一行追加秘祕之對應。然後修改t2tw.json，ocd2 改 text，TWVariants.ocd2 改 TWVariants.txt 即可。
