### ISSUE TITLE
將候選詞界面遷移至前端

### ISSUE THREAD

**Issue by nameoverflow** [rime/weasel#110]
現在小狼毫的架構中候選詞界面由 WeaselServer 創建並顯示，帶來了一些問題：

- 在一些特殊窗體中候選詞界面作爲一個普通窗體無法顯示在最頂層而被遮擋：如部分全屏遊戲、Windows 10 的 Cortana
![image](https://user-images.githubusercontent.com/10287709/36084580-9fa6bc64-0ff9-11e8-80ac-855f62572e49.png)

- 由於各應用的顯示設置不同，使用 TSF 或者 IME 獲取到的輸入位置在傳遞給 WeaselServer 後發生偏移：如 JetBrain 系列應用在高分屏下的表現 (#100)
![image](https://user-images.githubusercontent.com/10287709/36084650-35ae710c-0ffa-11e8-91af-2299169efc35.png)

- Windows 推薦的方式是使用 TSF 的接口顯示候選詞界面，部分應用會對此實現針對性的行爲，可能造成當前的模式不適用。典型的如英雄聯盟遊戲中的文字輸入。

將候選詞界面從 WeaselServer 中剝離還可以去除 WeaselServer 程序對窗體子系統的依賴，從而方便將其作爲 Win32 服務的形式運行。

<del>當然，如果純粹使用 TSF 顯示候選詞，可能需要拋棄 IME 輸入法的支持。</del>

我覺得可以嘗試一下？ @lotem @Prcuvu

**Comment by lotem** [comment]
猴啊。支持啊。

**Comment by nameoverflow** [comment]
這樣說是不是有點欽定的感覺？

**Comment by Prcuvu** [comment]
同意。

**Comment by mrhso** [comment]
抛弃 IME 的话，Windows XP 的 TSF 支持完善吗？

**Comment by TivJsou** [comment]
建议抛弃IME。xp系统使用老版本没有任何问题。
新版本没有理由还要再考虑对xp的兼容，而导致对新系统各种不兼容。

**Comment by mrhso** [comment]
其实也可以考虑代码自适应，这样新老系统都能很好顾及到。

**Comment by Prcuvu** [comment]
目前就是代码自适应的。重要的是，IME 之后需要跟进修改。这件事可以交给我来做。

**Comment by lotem** [comment]
IME 也可以在前端顯示選詞介面。
依照 IME 的傳統作法，整個輸入法都在前端加載。
把介面移到後端算是另類作法了。兼容性風險++。
主要好處是：
介面代碼只須編譯一次（--x64）；
介面只加載到內存一份（前端被每個應用程序加載）；
前端穩定，倘介面出錯可保應用程序不垮。
