### ISSUE TITLE
将 WeaselServer.exe 编译为64位版本后，服务可以启动，但是无法打字

### ISSUE THREAD

**Issue by ccyybn** [rime/weasel#1102]
- 将 **WinSparkle.lib WinSparkle.dll**  都替换为 x64 版本后

- 在 [weasel.sln](https://github.com/rime/weasel/blob/master/weasel.sln)  里修改编译目标为 x64

- **git checkout** librime 的 最新 release 版本 [1.10.0](https://github.com/rime/librime/releases/tag/1.10.0) 

- **librime** 和 **weasel** 项目的env.bat 修改
```
set ARCH=x64
```

- 执行 **build.bat all**

成功编译出x64的 WeaselServer.exe，启动后托盘里图标 右键菜单 可以打开窗口

但是打字的时候目没有反应，输出的是字母，程序图标一直卡在 **正在部署状态**

### **https://github.com/ccyybn/weasel/commit/b2981c5aca6fd469ddee9c28cd2b53722e362306**

![Snipaste_2024-02-13_00-57-31](https://github.com/rime/weasel/assets/7237501/23d6ea0e-aeda-406b-b4b1-dd7b56101fca)

![Snipaste_2024-02-13_00-59-32](https://github.com/rime/weasel/assets/7237501/f98560a6-2db0-409d-abcf-cd25e58f67ed)

**Comment by ccyybn** [comment]
[weasel-0.15.0.0-installer.zip](https://github.com/rime/weasel/files/14241663/weasel-0.15.0.0-installer.zip)

这是编译出来的安装包，安装环境是全新的win11虚拟机，测试 **32位版本** 在相同环境下正常

**Comment by Techince** [comment]
[小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)
编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。

**Comment by ccyybn** [comment]
> [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。

能提供一下源代码吗，我对win32编程不是很了解，谢谢

**Comment by Techince** [comment]
> > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。
> 
> 能提供一下源代码吗，我对win32编程不是很了解，谢谢

https://github.com/Techince/weasel

**Comment by ccyybn** [comment]
> > > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。
> > 
> > 
> > 能提供一下源代码吗，我对win32编程不是很了解，谢谢
> 
> https://github.com/Techince/weasel

刚刚使用你提供的安装包试了一下，有一种非常卡顿的感觉，按下键后有时要等几秒，explorer 程序期间失去响应

**Comment by Techince** [comment]
> > > > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。
> > > 
> > > 
> > > 能提供一下源代码吗，我对win32编程不是很了解，谢谢
> > 
> > 
> > https://github.com/Techince/weasel
> 
> 刚刚使用你提供的安装包试了一下，有一种非常卡顿的感觉，按下键后有时要等几秒，explorer 程序期间失去响应，不知道是不是系统不同的问题

安装完成后，注销一下系统才会正常。

**Comment by ccyybn** [comment]
> > > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。
> > 
> > 
> > 能提供一下源代码吗，我对win32编程不是很了解，谢谢
> 
> https://github.com/Techince/weasel

通过修改 

**typedef uintptr_t RimeSessionId;** 为 **using RimeSessionId = uint64_t;** 

现在没有卡在正在部署了，但是打字仍然不出汉字

#### **COMMIT** https://github.com/ccyybn/weasel/commit/1c7d947bc3e329149bd090414b85c82335a2299a

**Comment by Alexguy1199** [comment]
太好了，终于有人编译64位Windows RIME了！

**Comment by Techince** [comment]
> > > > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。
> > > 
> > > 
> > > 能提供一下源代码吗，我对win32编程不是很了解，谢谢
> > 
> > 
> > https://github.com/Techince/weasel
> 
> 在主仓库代码基础上，通过修改
> 
> **typedef uintptr_t RimeSessionId;** 为 **using RimeSessionId = uint64_t;**
> 
> 现在没有卡在正在部署了，但是打字仍然不出汉字
> 
> #### **COMMIT** [ccyybn/weasel@1c7d947](https://github.com/ccyybn/weasel/commit/1c7d947bc3e329149bd090414b85c82335a2299a)

建议多看看64位的源码。从32位源码到64位源码，需要修改不少地方，得静下心来分析逻辑来适配64位程序才行。
目前有现成的64位源码，可以直接阅读

**Comment by ccyybn** [comment]
> > > > > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。
> > > > 
> > > > 
> > > > 能提供一下源代码吗，我对win32编程不是很了解，谢谢
> > > 
> > > 
> > > https://github.com/Techince/weasel
> > 
> > 
> > 在主仓库代码基础上，通过修改
> > **typedef uintptr_t RimeSessionId;** 为 **using RimeSessionId = uint64_t;**
> > 现在没有卡在正在部署了，但是打字仍然不出汉字
> > #### **COMMIT** [ccyybn/weasel@1c7d947](https://github.com/ccyybn/weasel/commit/1c7d947bc3e329149bd090414b85c82335a2299a)
> 
> 建议多看看64位的源码。从32位源码到64位源码，需要修改不少地方，得静下心来分析逻辑来适配64位程序才行。 目前有现成的64位源码，可以直接阅读

非常感谢你的源代码，由于你的代码做了巨量的其他改动，这中间过程非常艰难，不过我终于分辨出了 **x64** 的有效部分，目前基于官方代码的 64位版本 已经完全正常

#### 下面是修改的部分
### https://github.com/ccyybn/weasel/commit/061c65d610746c810720922bd743adcd184467dc

#### 64位版本 安装包

### [weasel-0.15.0.0-installer.zip](https://github.com/rime/weasel/files/14261118/weasel-0.15.0.0-installer.zip)

**Comment by Techince** [comment]
> > > > > > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。
> > > > > 
> > > > > 
> > > > > 能提供一下源代码吗，我对win32编程不是很了解，谢谢
> > > > 
> > > > 
> > > > https://github.com/Techince/weasel
> > > 
> > > 
> > > 在主仓库代码基础上，通过修改
> > > **typedef uintptr_t RimeSessionId;** 为 **using RimeSessionId = uint64_t;**
> > > 现在没有卡在正在部署了，但是打字仍然不出汉字
> > > #### **COMMIT** [ccyybn/weasel@1c7d947](https://github.com/ccyybn/weasel/commit/1c7d947bc3e329149bd090414b85c82335a2299a)
> > 
> > 
> > 建议多看看64位的源码。从32位源码到64位源码，需要修改不少地方，得静下心来分析逻辑来适配64位程序才行。 目前有现成的64位源码，可以直接阅读
> 
> 非常感谢你的源代码，由于你的代码做了巨量的其他改动，这中间过程非常艰难，不过我终于分辨出了 **x64** 的有效部分，目前基于官方代码的 64位版本 已经完全正常
> 
> #### 下面是修改的部分
> ### [ccyybn/weasel@061c65d](https://github.com/ccyybn/weasel/commit/061c65d610746c810720922bd743adcd184467dc)
> #### 64位版本 安装包
> ### [weasel-0.15.0.0-installer.zip](https://github.com/rime/weasel/files/14261118/weasel-0.15.0.0-installer.zip)

先恭喜一下。
不过作为开发者，要尽量避免重复造轮子。
我去年夏天开始改造64位，使用的C++20标准，输入法逻辑与官方保持一致，但会修复一些已知bug。

**Comment by Alexguy1199** [comment]
> [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。 ![image](https://private-user-images.githubusercontent.com/12376669/304176702-0ac5752b-3203-41bf-bd11-cc1dcd7e5daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjUzNjQsIm5iZiI6MTcwNzkyNTA2NCwicGF0aCI6Ii8xMjM3NjY2OS8zMDQxNzY3MDItMGFjNTc1MmItMzIwMy00MWJmLWJkMTEtY2MxZGNkN2U1ZGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE1Mzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNjM4ZDc3NGY1NGYzNDdmNzFmZDUyNDRmNzViYzE4ODBkZGExZjdmZjU5YmRjYjMxYzY5NzY2ZTI3OGIwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JJ_3256ML452HfMHwdj-t9z5SRjR_IJb1JgO9_enOgk)

这个版本会报病毒，在Windows 11 64bit 系统。

**Comment by Techince** [comment]
> > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。 ![image](https://private-user-images.githubusercontent.com/12376669/304176702-0ac5752b-3203-41bf-bd11-cc1dcd7e5daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjUzNjQsIm5iZiI6MTcwNzkyNTA2NCwicGF0aCI6Ii8xMjM3NjY2OS8zMDQxNzY3MDItMGFjNTc1MmItMzIwMy00MWJmLWJkMTEtY2MxZGNkN2U1ZGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE1Mzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNjM4ZDc3NGY1NGYzNDdmNzFmZDUyNDRmNzViYzE4ODBkZGExZjdmZjU5YmRjYjMxYzY5NzY2ZTI3OGIwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JJ_3256ML452HfMHwdj-t9z5SRjR_IJb1JgO9_enOgk)
> 
> 这个版本会报病毒，在Windows 11 64bit 系统。

报毒的话可以添加到杀软的信任区域里。

**Comment by Alexguy1199** [comment]
> > > > > > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。
> > > > > 
> > > > > 
> > > > > 能提供一下源代码吗，我对win32编程不是很了解，谢谢
> > > > 
> > > > 
> > > > https://github.com/Techince/weasel
> > > 
> > > 
> > > 在主仓库代码基础上，通过修改
> > > **typedef uintptr_t RimeSessionId;** 为 **using RimeSessionId = uint64_t;**
> > > 现在没有卡在正在部署了，但是打字仍然不出汉字
> > > #### **COMMIT** [ccyybn/weasel@1c7d947](https://github.com/ccyybn/weasel/commit/1c7d947bc3e329149bd090414b85c82335a2299a)
> > 
> > 
> > 建议多看看64位的源码。从32位源码到64位源码，需要修改不少地方，得静下心来分析逻辑来适配64位程序才行。 目前有现成的64位源码，可以直接阅读
> 
> 非常感谢你的源代码，由于你的代码做了巨量的其他改动，这中间过程非常艰难，不过我终于分辨出了 **x64** 的有效部分，目前基于官方代码的 64位版本 已经完全正常
> 
> #### 下面是修改的部分
> ### [ccyybn/weasel@061c65d](https://github.com/ccyybn/weasel/commit/061c65d610746c810720922bd743adcd184467dc)
> #### 64位版本 安装包
> ### [weasel-0.15.0.0-installer.zip](https://github.com/rime/weasel/files/14261118/weasel-0.15.0.0-installer.zip)

安装测试了一下，安装过程没有报错，但是运行好像不正常。右键目录的选项无反应。重新部署也没有反应。

**Comment by ccyybn** [comment]
> > > > > > > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。
> > > > > > 
> > > > > > 
> > > > > > 能提供一下源代码吗，我对win32编程不是很了解，谢谢
> > > > > 
> > > > > 
> > > > > https://github.com/Techince/weasel
> > > > 
> > > > 
> > > > 在主仓库代码基础上，通过修改
> > > > **typedef uintptr_t RimeSessionId;** 为 **using RimeSessionId = uint64_t;**
> > > > 现在没有卡在正在部署了，但是打字仍然不出汉字
> > > > #### **COMMIT** [ccyybn/weasel@1c7d947](https://github.com/ccyybn/weasel/commit/1c7d947bc3e329149bd090414b85c82335a2299a)
> > > 
> > > 
> > > 建议多看看64位的源码。从32位源码到64位源码，需要修改不少地方，得静下心来分析逻辑来适配64位程序才行。 目前有现成的64位源码，可以直接阅读
> > 
> > 
> > 非常感谢你的源代码，由于你的代码做了巨量的其他改动，这中间过程非常艰难，不过我终于分辨出了 **x64** 的有效部分，目前基于官方代码的 64位版本 已经完全正常
> > #### 下面是修改的部分
> > ### [ccyybn/weasel@061c65d](https://github.com/ccyybn/weasel/commit/061c65d610746c810720922bd743adcd184467dc)
> > #### 64位版本 安装包
> > ### [weasel-0.15.0.0-installer.zip](https://github.com/rime/weasel/files/14261118/weasel-0.15.0.0-installer.zip)
> 
> 安装测试了一下，安装过程没有报错，但是运行好像不正常。右键目录的选项无反应。重新部署也没有反应。

刚又测试了一遍，在我的环境下，没发现异常，建议完全卸载32位版本后，删除本机用户文件夹数据，重启再安装，如果你的方案使用了lua脚本，需要重新编译rime.dll，我编译时忘记克隆这个扩展支持了，不过不影响正常输入，只是一些转农历大写数字的功能用不了

**Comment by dangpengsong** [comment]
> > > > > > > > [小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe) 编译64位需要修改一些代码，尤其是管道消息头部的RimeSessionId类型。
> > > > > > > 
> > > > > > > 
> > > > > > > 能提供一下源代码吗，我对win32编程不是很了解，谢谢
> > > > > > 
> > > > > > 
> > > > > > https://github.com/Techince/weasel
> > > > > 
> > > > > 
> > > > > 在主仓库代码基础上，通过修改
> > > > > **typedef uintptr_t RimeSessionId;** 为 **using RimeSessionId = uint64_t;**
> > > > > 现在没有卡在正在部署了，但是打字仍然不出汉字
> > > > > #### **COMMIT** [ccyybn/weasel@1c7d947](https://github.com/ccyybn/weasel/commit/1c7d947bc3e329149bd090414b85c82335a2299a)
> > > > 
> > > > 
> > > > 建议多看看64位的源码。从32位源码到64位源码，需要修改不少地方，得静下心来分析逻辑来适配64位程序才行。 目前有现成的64位源码，可以直接阅读
> > > 
> > > 
> > > 非常感谢你的源代码，由于你的代码做了巨量的其他改动，这中间过程非常艰难，不过我终于分辨出了 **x64** 的有效部分，目前基于官方代码的 64位版本 已经完全正常
> > > #### 下面是修改的部分
> > > ### [ccyybn/weasel@061c65d](https://github.com/ccyybn/weasel/commit/061c65d610746c810720922bd743adcd184467dc)
> > > #### 64位版本 安装包
> > > ### [weasel-0.15.0.0-installer.zip](https://github.com/rime/weasel/files/14261118/weasel-0.15.0.0-installer.zip)
> > 
> > 
> > 安装测试了一下，安装过程没有报错，但是运行好像不正常。右键目录的选项无反应。重新部署也没有反应。
> 
> 刚又测试了一遍，在我的环境下，没发现异常，建议完全卸载32位版本后，删除本机用户文件夹数据，重启再安装，如果你的方案使用了lua脚本，需要重新编译rime.dll，我编译时忘记克隆这个扩展支持了，不过不影响正常输入，只是一些转农历大写数字的功能用不了

装上测试了一下,可以打字,但是候选框不显示,只能盲猜,安装的时候疯狂闪烁升级检测那个窗口

**Comment by ccyybn** [comment]
@dangpengsong 现在建议编译大佬新弄的64版本 https://github.com/rime/weasel/pull/1121
