### ISSUE TITLE
偶尔会出现候选空白的情况

### ISSUE THREAD

**Issue by KwdeTfpv** [rime/weasel#1107]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 19045.3930
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
偶尔会出现候选空白的情况

**复现步骤**

**预期行为**
简短地描述你预期小狼毫怎么反馈

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
![image](https://github.com/rime/weasel/assets/91249019/a1db86de-d72a-4bae-92b6-e8d48c11358a)

**其他补充说明**
1、需要切换一下输入法，才能正常
2、使用的是五笔，
![image](https://github.com/rime/weasel/assets/91249019/9844f5ff-f54d-455a-a0a1-e5590caebfc7)

**Comment by fxliang** [comment]
#1037 有修，可以试试nightly build.
