### ISSUE TITLE
最新nightly build版本，在我的电脑上出现算法服务无法运行的情况。

### ISSUE THREAD

**Issue by nulllee** [rime/weasel#1109]
win11 64位 最新补丁，12650h，神舟笔记本。
无论是自启动还是手动都无法启动该服务，无任何报错提示，程序文件没有被杀软杀掉。

**Comment by yanhuacuo** [comment]
马克，我也遇到了。
不过我这边更奇怪，不仅 CI 编译物运行不了，
拉下代码本地编译成功后，其他人都可用，唯独我用不了。
但是，
我用小狼毫助手，每 200 毫秒间隔检测一次算法服务，令之强行在线，一切又是正常的。
似乎是 weasl 想睡觉，而小狼毫助手及时唤醒它，就没有问题。
log 里也没有报错信息或警告信息。
也是自除夕前，更了一次 win11 之后，出现了这个问题。

**Comment by nulllee** [comment]
> 马克，我也遇到了。 不过我这边更奇怪，不仅 CI 编译物运行不了， 拉下代码本地编译成功后，其他人都可用，唯独我用不了。 但是， 我用小狼毫助手，每 200 毫秒间隔检测一次算法服务，令之强行在线，一切又是正常的。 似乎是 weasl 想睡觉，而小狼毫助手及时唤醒它，就没有问题。 log 里也没有报错信息或警告信息。 也是自除夕前，更了一次 win11 之后，出现了这个问题。

唉，要不是12650h安Win10小核有问题，我也不用这狗屁win11了，不好用毛病还多。👎

**Comment by fxliang** [comment]
https://github.com/rime/weasel/issues/978#issuecomment-1759354457

用这个开dump,看看dump在哪（虽然其实dump文件我不会用

**Comment by fxliang** [comment]
https://github.com/rime/weasel/issues/978#issuecomment-1759354457

用这个开wer,看看dump在哪（虽然其实dump文件我不会用

**Comment by nulllee** [comment]
> [#978 (comment)](https://github.com/rime/weasel/issues/978#issuecomment-1759354457)
> 
> 用这个开wer,看看dump在哪（虽然其实dump文件我不会用

我已经回退了，这几天打字多，不想弄这个dump文件，要是有之前的log文件可以告诉我路径去翻翻发出来。

**Comment by fxliang** [comment]
这种问题通常是seg fault exception ,直接崩不会有log的

**Comment by ding** [comment]
遇到了同样的问题，应该是服务没有运行，手工启动也无任何反应。

**Comment by Techince** [comment]
似乎是WTL库有关。我编译的[小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本，当Visual Studio更新版本时，偶尔也会遇到「算法服务」或「输入法设定」不能正常启动，跟踪代码时，指向的错误是WTL框架代码。最近的「输入法设定」通过改变编译选项才让它能正常启动，但生成的文件体积从原来的800多KB变成了现在的1.46M. 可能是WTL不是微软正式发行的，没有得到微软的支持。

**Comment by ding** [comment]
> 似乎是WTL库有关。我编译的[小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本，当Visual Studio更新版本时，偶尔也会遇到「算法服务」或「输入法设定」不能正常启动，跟踪代码时，指向的错误是WTL框架代码。最近的「输入法设定」通过改变编译选项才让它能正常启动，但生成的文件体积从原来的800多KB变成了现在的1.46M. 可能是WTL不是微软正式发行的，没有得到微软的支持。

这个库是最近引入的么？

**Comment by Techince** [comment]
> > 似乎是WTL库有关。我编译的[小狼毫64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本，当Visual Studio更新版本时，偶尔也会遇到「算法服务」或「输入法设定」不能正常启动，跟踪代码时，指向的错误是WTL框架代码。最近的「输入法设定」通过改变编译选项才让它能正常启动，但生成的文件体积从原来的800多KB变成了现在的1.46M. 可能是WTL不是微软正式发行的，没有得到微软的支持。
> 
> 这个库是最近引入的么？

不是，很早就引入的。早期的时候，MFC还没被边缘化，WTL相对MFC相对来说生成的可执行文件更小，也没有VC++运行库依赖。而今天微软界面库发展到了WinUI，WTL也被边缘化，库的更新频率也不活跃了，可能会遇到一些bug没有及时解决。
