### ISSUE TITLE
round_corner参数不生效

### ISSUE THREAD

**Issue by 971230** [rime/weasel#1110]
**上报前请检查**
- [✅] 我遇到的问题没有其他人在 issue 里提到过
- [✅] 我的小狼毫版本于 rime/weasel 下载
- [✅] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 22H2 22621.3155]
 - 小狼毫版本: [ 0.15.0.0 ]

**描述遇到的问题**
就是单纯的round_corner这个参数不生效的问题，好多自带的皮肤都有这个参数，但是我这下载下来怎么都不生效

下面是配置
`customization:
  distribution_code_name: Weasel
  distribution_version: 0.15.0.0
  generator: "Weasel::UIStyleSettings"
  modified_time: "Mon Feb 19 08:21:43 2024"
  rime_version: 1.8.5
patch:
  "menu/page_size": 9
  "preset_color_schemes/aqua": # aqua是自定义皮肤名字，用于style/color_scheme选项
    name: 碧水／Aqua # 方案设置中显示的配色名称
    author: 佛振 <chen.sst@gmail.com> # 配色作者名称
    # color_format: abgr                          # 颜色格式：argb；rgba；abgr（默认）
    text_color: 0x000000 # 默认文字颜色
    # comment_text_color: 0x000000                # 注释文字颜色
    # label_color: 0x000000                       # 标签文字颜色
    back_color: 0xeceeee # 候选窗背景色
    shadow_color: 0x00000000 # 候选窗阴影色
    border_color: 0xe0e0e0 # 候选窗边框颜色
    hilited_text_color: 0x000000 # 编码文字颜色
    hilited_back_color: 0xd4d4d4 # 编码背景颜色
    hilited_shadow_color: 0x00000000 # 编码背景块阴影颜色
    hilited_candidate_text_color: 0xffffff # 高亮候选文字颜色
    hilited_candidate_back_color: 0xfa3a0a # 高亮候选背景颜色
    hilited_candidate_shadow_color: 0x00000000 # 高亮候选背景块阴影颜色
    # hilited_candidate_border_color: 0xe0e0e0    # 高亮候选边框颜色
    # hilited_label_color: 0x000000               # 高亮候选的标签颜色
    # hilited_mark_color: 0x000000                # 高亮候选前的标记颜色
    # hilited_comment_text_color: 0x000000        # 高亮候选的注释颜色
    candidate_text_color: 0x000000 # 非高亮候选文字颜色
    candidate_back_color: 0xeceeee # 非高亮候选背景颜色
    candidate_shadow_color: 0x00000000 # 非高亮候选背景块阴影颜色
    # candidate_border_color: 0xe0e0e0            # 非高亮候选的边框颜色
    # nextpage_color: 0x00000000                  # inline_preedit: false 翻页箭头颜色：下一页；不设置则不显示箭头
    # prevpage_color: 0x00000000                  # inline_preedit: false 翻页箭头颜色：上一页；不设置则不显示箭头
  style:
    color_scheme: aqua
    display_tray_icon: false
    font_face: "LXGW ZhenKai"
    font_point: 12
    fullscreen: false
    horizontal: true
    inline_preedit: true
    label_format: "%s."
    layout: {
        border_width: 3,
        candidate_spacing: 20,
        hilite_padding: 10,
        hilite_spacing: 5,
        margin_x: 10,
        margin_y: 10,
        min_height: 0,
        min_width: 100,
        shadow_radius: 6, #全局阴影模糊半径，为0则全局禁用阴影
        spacing: 10,
        corner_radius: 16, #候选框外圆角半径
        round_corner: 18, #候选字背景色块圆角幅度
      }
    preedit_type: composition
  "style/color_scheme": aqua #这里指定皮肤名称
`

**截图**
![image](https://github.com/rime/weasel/assets/37500200/b3141002-48a5-4db2-8aef-5a01a6fd7b27)

**其他补充说明**
重新卸载安装也无法生效

**Comment by 3biubiu** [comment]
我也遇到了这个问题

**Comment by fxliang** [comment]
因为padding >= margin，触发天圆地方模式了

**Comment by lotem** [comment]
`round_corner` 是整個窗口的圓角吧。註釋是這麼說的：「#候选框外圆角半径」
——不是。代碼格式糊了。
