### ISSUE TITLE
Nightly Build版本 无法启动 WeaselServer

### ISSUE THREAD

**Issue by MOldtime** [rime/weasel#1116]
**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 24H2 26058.1400 ]
 - 小狼毫版本: [ e040ab4 ]

**描述遇到的问题**
在使用 [Nightly Build](https://github.com/rime/weasel/releases/tag/latest) 的时候无法启动WeaselServer 手动也无法运行
我看到有合并关于这个应用的pr 是否是我的操作没正确？

**用户文件**
[Rime.zip](https://github.com/rime/weasel/files/14395106/Rime.zip)
默认生成

**其他补充说明**
我看到了同样的问题 #1109 ，但是问题已经关闭，看起来并没有解决
这是通过 https://github.com/rime/weasel/issues/978#issuecomment-1759354457 获取的文件，由于github上传格式限制的原因 我改成了txt后缀
[rime.weasel.TIME.Money.log.INFO.20240225-113136.txt](https://github.com/rime/weasel/files/14395126/rime.weasel.TIME.Money.log.INFO.20240225-113136.txt)

**Comment by Techince** [comment]
好新的系统版本呀！测试下[64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本

**Comment by dyphire** [comment]
遇到了同样的问题，上面发的 64 位版本可以工作

**Comment by MOldtime** [comment]
> 好新的系统版本呀！测试下[64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版

感谢修复，看起来是另一个分支，如果可以Pr合并就太好了

**Comment by Techince** [comment]
> > 好新的系统版本呀！测试下 [64 位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本
> 
> 遇到了同样的问题，这个 64 位版本可以工作，但是这个版本又无法退出算法服务了

可以退出「算法服务」的，前提是取消托盘菜单里的「开启守护」。

**Comment by Techince** [comment]
> > 好新的系统版本呀！测试下[64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版
> 
> 感谢修复，看起来是另一个分支，如果可以Pr合并就太好了

应该是librime那里的问题。64位版本用正常的项目设置，「输入法设定」不能正常打开，得开启「启用调试」信息才能正常打开。

**Comment by fxliang** [comment]
试下，从librime那边下载1.10.0的dll看看，如果顺手试下对比1.9.0的情况（无中文字符的用户路径情况下）

**Comment by MOldtime** [comment]
当我重新下回 e040ab4 安装发现又可以使用了，很奇怪，可能是驱动的问题，我昨天晚上更新了显卡驱动
目前只能不了了之 无法继续往下测试，这个isseus也许可以继续打开，问题看起来还没有真正定位

**Comment by mirtlecn** [comment]
应该是 librime 最近的更改引起的，我用没有合并一大堆 pr 前的 weasel 和合并后的 weasel 在两台虚拟机上测试，都不能启动最新的 librime ci 版本。反之 1.9，1.10 工作正常。

revert 了 librime 最新的几次更改（随便 revert 到了 c3edda7e34d6e4dc95d27e038f9dca8f28bd2a63），就正常工作了。

**Comment by EmccK2** [comment]
Window Defender直接报毒了，把weasel的文件都删了

**Comment by jdjxk** [comment]
> 好新的系统版本呀！测试下[64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本

可以可以，这个版本没有问题

**Comment by MOldtime** [comment]
看起来 https://github.com/rime/weasel/pull/1161 解决了这个我想还有个原因就是自启动太慢，导致

**Comment by mirtlecn** [comment]
另开一个 issue 呗，不过我记得有人提过这个
