### ISSUE TITLE
中文模式输入的字符导致Chrome地址栏候选项丢失

### ISSUE THREAD

**Issue by llamess** [rime/weasel#1118]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [ ] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 10 20H2 19042.685]
 - 小狼毫版本: [  0.15.1.007 ， @Techince 构建的64位版本 ]

**描述遇到的问题**
在Chrome浏览器中输入英文字符无法触发浏览器弹出地址栏的下拉列表。  
（Chrome 版本为122.0.6261.70）  

**复现步骤**
1、打开新的Chrome.exe进程，按shift将输入法改为英文输入模式，输入字母g，可以看到有下拉的候选项  
![pic0](https://github.com/rime/weasel/assets/134357843/1230c5c7-caa6-4a2c-99d0-5e5501efbaf2)  

2、另外新开Chrome.exe进程，在中文模式下输入字母g，此时地址栏候选项消失。  
![pic2](https://github.com/rime/weasel/assets/134357843/7bd4fda0-c62e-4de5-bad1-7b9ff0e97461)  
此时即使将输入法改回英文模式，仍然无法触发弹出地址栏的候选项。
![pic4](https://github.com/rime/weasel/assets/134357843/dcb3e975-09a4-4177-8e42-7b8040c11ed3)

**预期行为**
希望在任何情况下都能正常弹出Chrome浏览器地址栏的候选项

**Comment by Techince** [comment]
仔细测试了一下。是小狼毫的候选框UI那里的问题。可以用「Ctrl+Shift+G」关闭候选框，输入内容不出候选框，搜索列表候选不会消息。这个得找梁梁来修，目录的WeaselUI是梁梁在维护的。

**Comment by fxliang** [comment]
几点信息：
1. UI是TSF的实例的成员，并未直接参与与应用的交互，所以如果是应用本身的响应出现问题而不是ui显示不正常，那这个问题会与TSF的代码相关，而不是WeaselUI；
2. 经测试主仓的产物，并未复现issue所提的问题，一切正常，且出现问题的发行包为Techince另外发布的版本。因此在此先关闭此issue，如有需要再另行打开。

**Comment by fxliang** [comment]
几点信息：
1. UI是TSF的实例的成员，并未直接参与与应用的交互，所以如果是应用本身的响应出现问题而不是ui显示不正常，那这个问题会与TSF的代码相关，而不是WeaselUI；
2. 经测试主仓的产物，并未复现issue所提的问题，一切正常，且出现问题的发行包为Techince另外发布的版本。因此在此先关闭此issue，如有需要再另行打开。
