### ISSUE TITLE
“茧”字无法正确输入

### ISSUE THREAD

**Issue by Qeynos** [rime/weasel#1119]
issues中看了没有类似的报告
24-2-24日的nightly
win10 22h2
自然码双拼

“茧”字无法输入，通过扩展词库关联输入时会变成“简”，不清楚是否存在opencc的问题
其他还有“乾”字，输入时直接生成的词在再次调用时会转化成“干”
“钜”字，同样自造词使用时会被转化成“巨”

**Comment by Techince** [comment]
![image](https://github.com/rime/weasel/assets/12376669/842ae964-54aa-49aa-a7c5-afe0fa7b8a73)
![image](https://github.com/rime/weasel/assets/12376669/a3c84f84-3a2d-48fa-9dc8-51487bc92fc5)
![image](https://github.com/rime/weasel/assets/12376669/4af01903-bd98-4f29-90ff-53f5af8ac731)

**Comment by Qeynos** [comment]
> ![image](https://private-user-images.githubusercontent.com/12376669/308081790-842ae964-54aa-49aa-a7c5-afe0fa7b8a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjk2NjMsIm5iZiI6MTcwOTAyOTM2MywicGF0aCI6Ii8xMjM3NjY2OS8zMDgwODE3OTAtODQyYWU5NjQtNTRhYS00OWFhLWE3YzUtYWZlMGZhN2I4YTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEwMjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNzA5ZGIwZjRhNzIwYjc0NGQ4MDU3NTgzMGM4MWU4MzI5MTE4MjhkZDIzMTI1ZThmMTkyZmQxNzZmNDJjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JURbdrvfOkUuvqZu9Du0KiCGagGhEFn-SEzF-_ATLIM) ![image](https://private-user-images.githubusercontent.com/12376669/308081873-a3c84f84-3a2d-48fa-9dc8-51487bc92fc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjk2NjMsIm5iZiI6MTcwOTAyOTM2MywicGF0aCI6Ii8xMjM3NjY2OS8zMDgwODE4NzMtYTNjODRmODQtM2EyZC00OGZhLTlkYzgtNTE0ODdiYzkyZmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEwMjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZGNmYjA0NWNkMTFiNGQ5ODcwODNmZDc4YzdmNjU1YWI1YWY5OWU1ZGZkN2E3OTA4MjMxNjNiNWMxZjI5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4ozBbQUwyyR6wo83f8n0GdMe4V6ttDwzSi2BZhCydEQ) ![image](https://private-user-images.githubusercontent.com/12376669/308081960-4af01903-bd98-4f29-90ff-53f5af8ac731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjk2NjMsIm5iZiI6MTcwOTAyOTM2MywicGF0aCI6Ii8xMjM3NjY2OS8zMDgwODE5NjAtNGFmMDE5MDMtYmQ5OC00ZjI5LTkwZmYtNTNmNWFmOGFjNzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEwMjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZTI4ZGNjNTExMzZjNjdkMjhiYjA1YzY1ZmEzNmU4MmU2YjYzMTA4ODFmZWRkZTQ3N2Q1ZDk0OTg3OGY0NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yq8cvS17OMVBz_cEIJkCjaMkR-UIogWzQWz_jjyZxew)

“茧”字是自然码双拼打不出来，后面的乾和钜都是组词后调用会变成简化字

**Comment by mirtlecn** [comment]
没有仔细研究，但猜测是 OpenCC 的问题。

如果你主要用简体字，建议直接用简体词库。如果你不明白这是什么意思，可以尝试使用「雾凇拼音」之类的现成配置，里面同样有自然码双拼。

不要使用方案内置的朙月拼音等字库，其原本都是繁体（康熙）通过 OpenCC 转换来的，会有很多不合常理的转换。

同样的问题，出现在简体字库转换为繁体字时，也有较多的不符合习惯的转换。

**Comment by Qeynos** [comment]
> 没有仔细研究，但猜测是 OpenCC 的问题。
> 
> 如果你主要用简体字，建议直接用简体词库。如果你不明白这是什么意思，可以尝试使用「雾凇拼音」之类的现成配置，里面同样有自然码双拼。
> 
> 不要使用方案内置的朙月拼音等字库，其原本都是繁体（康熙）通过 OpenCC 转换来的，会有很多不合常理的转换。
> 
> 同样的问题，出现在简体字库转换为繁体字时，也有较多的不符合习惯的转换。

确实是opencc的问题，似乎佛振之前也提过，这个雾凇拼音确实能解决这个问题，非常感谢您的答复
