### ISSUE TITLE
小狼毫在Word 2019下候选框闪烁或不显示-Win 11 64位（word中设置编号，通过标尺推动后，可以复现）

### ISSUE THREAD

**Issue by changzaicl** [rime/weasel#1120]
这个问题在新的actions下版本， 及nightly release版本依然会重现。office是2021版本，输入法控制已经关闭。
只需要在word中，通过调整拖动标尺就会出现。而且可以复现。
word是使用大户，请帮助修复。谢谢！

**Comment by Techince** [comment]
[64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)

**Comment by changzaicl** [comment]
谢谢，这个版本的确可以解决这个word中的bug。
不过，作为官方版本这个问题不修复，不太好理解。

**Comment by fxliang** [comment]
因为没有人pr咯

**Comment by changzaicl** [comment]
哦，谢谢了！
这个问题是可以重现的，只要用鼠标拖动几次标尺后，就肯定出现输入框闪烁的情况。然后只能重启word才能不闪烁，重启weasel无效。

**Comment by Techince** [comment]
> 因为没有人pr咯

我上次提交的pr可以修复这个问题。

**Comment by fxliang** [comment]
> > 因为没有人pr咯
> 
> 我上次提交的pr可以修复这个问题。

1,向主仓PR，操作见下图。

![image](https://github.com/rime/weasel/assets/4023160/3182e94e-e55c-468c-8c34-3a51a117b230)

2，你那个pr夹了太多其他无关的东西，无法review.

**Comment by Techince** [comment]
> > > 因为没有人pr咯
> > 
> > 
> > 我上次提交的pr可以修复这个问题。
> 
> 1,向主仓PR，操作见下图。
> 
> ![image](https://private-user-images.githubusercontent.com/4023160/308879180-3182e94e-e55c-468c-8c34-3a51a117b230.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDQwNzgsIm5iZiI6MTcwOTIwMzc3OCwicGF0aCI6Ii80MDIzMTYwLzMwODg3OTE4MC0zMTgyZTk0ZS1lNTVjLTQ2OGMtOGMzNC0zYTUxYTExN2IyMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMTA0OTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjgzYmEwMjliZDIzZGI5MGQ4MDg5OWQ5MzAyMzMxYzhhZmIyMWQ1M2RiZTRmNTMzY2VhMjYwZWJmN2E4YzY2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mGnh8y6Kv5IvVSgo97xy5Gfge0A265osxEUOFofWmYM)
> 
> 2，你那个pr夹了太多其他无关的东西，无法review.

好的，我去看看怎么操作，非常感谢。

**Comment by changzaicl** [comment]
期待大佬们合作解决。

**Comment by changzaicl** [comment]
目前还没看到任何进展，搞得实在无法使用word了。还请大佬们重视此问题的修复，期待早日解决。

**Comment by Techince** [comment]
> 目前还没看到任何进展，搞得实在无法使用word了。还请大佬们重视此问题的修复，期待早日解决。

目前librime端正在改动，得等librime端稳定后我才能编译官方版本进行修改测试。

**Comment by fxliang** [comment]
> > 目前还没看到任何进展，搞得实在无法使用word了。还请大佬们重视此问题的修复，期待早日解决。
> 
> 目前librime端正在改动，得等librime端稳定后我才能编译官方版本进行修改测试。

librime的改动和这个有什么关系，难道你还想将submodule更新也pr了？

**Comment by changzaicl** [comment]
谢谢大佬们。看样子指日可待。谢谢！

**Comment by Techince** [comment]
新版本的构建遇到编译错误了。
![image](https://github.com/rime/weasel/assets/12376669/ae4df68c-f148-4fcc-8619-fd1004dd37d6)

**Comment by changzaicl** [comment]
这……如何是好……
加油💪

**Comment by changzaicl** [comment]
用Techince新提交的文件修改，我自己尝试CI了一个，使用了半天时间，在word中的确修复了，暂未发现其他问题。
