### ISSUE TITLE
无法修改同步文件夹

### ISSUE THREAD

**Issue by KangLong** [rime/weasel#1125]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本:  Windows 11 22H2 19045.3803
 - 小狼毫版本:  如 0.15.0.0 

**描述遇到的问题**
按照教程，修改 installation.ymal 文件，点击 用户资料同步 按钮后，installation.ymal 文件会被重新生成并被覆盖掉

**复现步骤**
重现问题的步骤，如：
1. 右键托盘，点击用户文件夹
2. 在弹出的文件夹内，修改 installation.yaml，添加 sync_dir: "D:\MyRime"
3. 右键托盘，点击 用户资料同步（或者 点击重新部署）
4. installation.ymal 中添加的 sync_dir 被删除，并且重新生成了一个新的 installation_id

**预期行为**
我想要修改同步文件夹的路径

**其他补充说明**
在网上搜了很长时间，所有的教程都是修改用户文件夹下的 installation.ymal，尝试过自建 installation.custom.ymal，但是无用。

**Comment by mirtlecn** [comment]
![image](https://github.com/rime/weasel/assets/76689045/57222529-53a6-470b-b237-34016223c4d1)

**Comment by KangLong** [comment]
> ![image](https://private-user-images.githubusercontent.com/76689045/308923119-57222529-53a6-470b-b237-34016223c4d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTI0NzYsIm5iZiI6MTcwOTIxMjE3NiwicGF0aCI6Ii83NjY4OTA0NS8zMDg5MjMxMTktNTcyMjI1MjktNTNhNi00NzBiLWIyMzctMzQwMTYyMjNjNGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDEzMDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMDFiOTkwZTNjY2U0ZDFmZWI3ZTc0MDc1NGNmMjBjZWYxNzI5YzgzMjJlMzhkYzMyYTk3MGJlNmMzNjgxODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fuM8W2JgRz-lEIsvp7fR35hOYAATR2imdRSWq7RoTyI)
> 
> ```yaml
> sync_dir: 'D:\Sync\Rime'
> sync_dir: "D:\\Sync\\Rime"
> ```

.....

thk
