### ISSUE TITLE
WeaselServer.exe 会随机自己崩溃，Exit code [3221225477]，大概每天一次

### ISSUE THREAD

**Issue by ccyybn** [rime/weasel#1126]
**上报前请检查**
- [ * ] 我遇到的问题没有其他人在 issue 里提到过
- [  ] 我的小狼毫版本于 rime/weasel 下载
- [ * ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - Windows 11 23H2 22631.3007

**描述遇到的问题**
因为会崩溃，就写了个Windows服务监控 WeaselServer.exe，崩溃后调用 GetExitCodeProcess检查，得到 Exit code [3221225477]

**复现步骤**
重现问题的步骤，如：
1. 几乎都发生在，英文模式下打字，就可能突然崩了，不怎么频繁，大概一天一次，重启服务后大概就正常了

**用户文件**
[data.zip](https://github.com/rime/weasel/files/14468279/data.zip)

**Comment by ccyybn** [comment]
刚在虚拟机试了一下，有另外一个问题

安装官方installer 后，直接把我上传的 data 替换到程序目录，删除用户文件夹，重新部署会卡在正在部署中，不知道算不算另外一个bug

而直接把我的 data 打包进 installer，一次安装，就能成功部署

[weasel-0.15.0.0-installer.zip](https://github.com/rime/weasel/files/14468591/weasel-0.15.0.0-installer.zip)

**Comment by ccyybn** [comment]
好像在开机后比较容易出现

**Comment by ccyybn** [comment]
能否考虑给 WeaselServer.exe 加个守护进程，崩溃后自动重新启动，我尝试在Windows服务里调用 CreateProcessAsUser，来启动WeaselServer.exe，不过它好像马上就死了，CreateProcessAsUser 启动 WeaselDeloyer.exe /dict 倒是可以成功看到窗口出现

**Comment by Techince** [comment]
我这个版本加了类似守护的功能([64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe))，可手动关闭。TSF端检测服务端无响应时就启动「算法服务」。

**Comment by ccyybn** [comment]
> 我这个版本加了类似守护的功能([64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe))，可手动关闭。TSF端检测服务端无响应时就启动「算法服务」。

好主意，上次参考你的代码改了个64位，现在再看看怎么检测无响应的，你是写在LanguageBar.cpp里面的吗

**Comment by Techince** [comment]
> > 我这个版本加了类似守护的功能([64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe))，可手动关闭。TSF端检测服务端无响应时就启动「算法服务」。
> 
> 好主意，上次参考你的代码改了个64位，现在再看看怎么检测无响应的，你是写在LanguageBar.cpp里面的吗

![image](https://github.com/rime/weasel/assets/12376669/3d872598-8dc9-41f2-bcbb-4b2df9d301b2)
在WeaselTSF::_EnsureServerConnected里

**Comment by ccyybn** [comment]
> > > 我这个版本加了类似守护的功能([64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe))，可手动关闭。TSF端检测服务端无响应时就启动「算法服务」。
> > 
> > 
> > 好主意，上次参考你的代码改了个64位，现在再看看怎么检测无响应的，你是写在LanguageBar.cpp里面的吗
> 
> ![image](https://private-user-images.githubusercontent.com/12376669/309562234-3d872598-8dc9-41f2-bcbb-4b2df9d301b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTU0MjcsIm5iZiI6MTcwOTU1NTEyNywicGF0aCI6Ii8xMjM3NjY2OS8zMDk1NjIyMzQtM2Q4NzI1OTgtOGRjOS00MWYyLWJjYmItNGIyZGY5ZDMwMWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEyMjUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZmNmNDY4ZDkwNzVkYmUzNTMwYzQwYmFjMTY1NjlkNzY1N2FlZDc3YzgxZGViMDRjNWVjZWIxYzAxZjIyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lh3m3zGxm6WCJ58zvElTbs0KTEVRbbHOyoEvervpZxg) 在WeaselTSF::_EnsureServerConnected里

这里好像有按键才会触发检测，我弄了个线程循环检查，不过TSF会在每个窗口都生成，导致我的线程也有好多个，不过还好多个线程重复启动 WeaselServer.exe 问题不大

**Comment by Techince** [comment]
@ccyybn 是的。当你没有输入时，算法服务是否运行无关紧要。这个逻辑可确保输入不会中断。

**Comment by ccyybn** [comment]
> @ccyybn 是的。当你没有输入时，算法服务是否运行无关紧要。这个逻辑可确保输入不会中断。

有一点可以优化一下，重启服务后把 TSF当前的中英文状态，恢复到服务里，这样用户就完全没有感知了

不过一些自定义Option，有点不方便，由于TSF里面并没有记录状态值，导致每项都要硬编码一下，以同步到TSF里面

![image](https://github.com/rime/weasel/assets/7237501/8e5e8898-a86f-46bc-a589-cbdc6a239033)

**Comment by fxliang** [comment]
可以看看nightly build，或者更新rime.dll到最新版测试看看情况

**Comment by ccyybn** [comment]
> 可以看看nightly build，或者更新rime.dll到最新版测试看看情况

还是会崩，我觉得是 playwright 爬虫启动了网页，在网页里的输入框触发了输入法，然后不知怎么的输入法就崩了

不过现在我加了崩溃后重启 和 重启后各个程序的TSF恢复自己的中英文，简繁体些状态，使用上已经没影响了

**Comment by fxliang** [comment]
3221225477对应为0xc0000005, nullptr referenced

最近有两个commit做了一点处理，可能可以消除一部分问题，nightly可以试试 @ccyybn 

2b9d96868b28670e3394679bdc1e4e211e7bdf0f
952ad12035cfd47e9cad5e60ad577a6a04e0cab3

**Comment by ccyybn** [comment]
> 3221225477对应为0xc0000005, 我之前试处理ITfThreadFocsSink 的时候试出来的状态是 nullptr referenced
> 
> 最近有两个commit做了一点处理，可能可以消除一部分问题，nightly可以试试 @ccyybn
> 
> [2b9d968](https://github.com/rime/weasel/commit/2b9d96868b28670e3394679bdc1e4e211e7bdf0f) [952ad12](https://github.com/rime/weasel/commit/952ad12035cfd47e9cad5e60ad577a6a04e0cab3)

我感觉似乎是由于两个进程同时使用输入法，就会崩溃，日常使用一般不会有这种同时使用的情况，但是当有自动程序也在调用输入法时，就容易出问题

新版的崩溃概率是要低一些了，当我在执行脚本时，不打字，就很难崩溃了，之前是 playwright 和 执行playwright的命令行两个进程都会触发崩溃，现在执行脚本时，要再加上我故意在记事本里打字，才容易出现打字卡死崩掉的情况

**Comment by fxliang** [comment]
https://github.com/fxliang/weasel/actions/runs/9109244341
改了一点东西，减少一点不必要的服务端ui更新，有可能再避免一点问题 @ccyybn
