### ISSUE TITLE
只有一个候选时, 候选框宽度无法调小

### ISSUE THREAD

**Issue by hxse** [rime/weasel#1127]
**操作系统信息**
 - OS 详细版本:  Windows 11 23H2 22631.3155
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
只有一个候选时, 候选框太宽了, 即使写了min_width也无法调小

![image](https://github.com/rime/weasel/assets/22582226/dae4571c-c93c-402b-80c2-3dbd6c31c575)

**Comment by changzaicl** [comment]
我觉得还是您的配置问题。我的min_width：120，也是非常小的。
    layout:
      align_type: center 
      border_width: 2 
      candidate_spacing: 4
      corner_radius: 8
      hilite_padding: 6
      hilite_padding_x: 4
      hilite_padding_y: 4
      hilite_spacing: 8
      margin_x: 8
      margin_y: 8
      max_height: 600
      max_width: 0
      min_height: 0
      min_width: 120
      round_corner: 6
      shadow_offset_x: 4
      shadow_offset_y: 4
      shadow_radius: 0
      spacing: 16

**Comment by Qeynos** [comment]
![截图_20240307152151](https://github.com/rime/weasel/assets/28810097/e3ba58bd-86c4-45e8-86a9-770817c3cfae)

并没有问题，请参考一下

**Comment by fxliang** [comment]
先看看build的部署产出是不是预期的状态吧

**Comment by hxse** [comment]
不知道怎么回事, 算了, 先这样吧
