### ISSUE TITLE
global_ascii 选项失效

### ISSUE THREAD

**Issue by hxse** [rime/weasel#1128]
**操作系统信息**
 - OS 详细版本:  Windows 11 23H2 22631.3155
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
参考了 https://github.com/rime/weasel/pull/1055 , 在`weasel.custom.yaml`添加了
```
patch:
  "global_ascii": true
```
但是并没有出现预期中的统一的ascii状态, 仍然是不同窗口保持着不同的状态

**Comment by fxliang** [comment]
0.15.0.0 未加这个特性，最新nightly里才有
