### ISSUE TITLE
vim_code {Control+C} 快捷键是否需要设置为非 composing 时才生效，或生效时，上屏/清除 compose 内容

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#1129]
**上报前请检查**
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我遇到的问题没有其他人在 issue 里提到过

**描述遇到的问题**

将 terminal 设置为 vim_mode: true （期望 vim 在 terminal 中使用）

情况一：

在 key_binder 处设置了 Ctrl + C 快捷键，composing 时生效

nvim-qt 中

预期：composing 时 {Control+C} -> 切换 OpenCC ；not composing -> ascii_mode

实际：composing 时 {Control+C} -> OpenCC && set ascii_mode true，出现意外情况

情况二：

shell 中

composing 时，按 {Control+C}，切换下一行的时候，候选不会上屏，也不会消失，按空格会直接进入 input 序列。

预期：清屏或者上屏。

![1709555396](https://github.com/rime/weasel/assets/76689045/4ba792e0-32b3-4cd6-a82d-04c37cc8344e)

cc @fxliang 

(此外，在 x64 位的 action 版本中，发现 vim mode 会在 flow launcher 中意外生效，伴随有 style 样式修改不生效、不同会话出现不同样式<修改系统浅色暗算模式，修改 style 重新部署时>，不能稳定复现，总是用一段时间出现，发现稳定复现办法再报告）

**Comment by fxliang** [comment]
加一个下面这样的就可以了
```cpp
			RimeClearComposition(_s(ipc_id));
```

**Comment by mirtlecn** [comment]
OK

第二个应当是 shell 更优先接管快捷键的问题。

**Comment by fxliang** [comment]
> OK
> 
> 第二个应当是 shell 更优先接管快捷键的问题。
> 
> 不打算在主分支上改我就关了

关于`Control+c`见我testbuild分支的ga产出https://github.com/fxliang/weasel/actions/runs/8151794077

**Comment by mirtlecn** [comment]
没问题了

**Comment by hgaogao** [comment]
你的配置是怎么样的？我给vs code 配置了vim_code并不能生效，使用的是rime-ice这个配置方案
```yaml
 Code.exe:
    ascii_mode: true 
    vim_mode: true 
```
