### ISSUE TITLE
设置粗体显示无变化

### ISSUE THREAD

**Issue by 971230** [rime/weasel#1130]
**上报前请检查**
- [✅] 我遇到的问题没有其他人在 issue 里提到过
- [✅] 我的小狼毫版本于 rime/weasel 下载
- [❎] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [Windows 11 23H2 22631.3155]
 - 小狼毫版本: [0.15.0.0]

**描述遇到的问题**
1.在weasel.custom.yaml文件中设置字体为粗体时，没有任何变化，字重无论多少显示效果都一样；
2.字体设置为黑体/宋体时，字体显示效果感觉都有一些毛刺，锯齿感，楷体不会，这方面可能是字体本身问题，不知道和rime有没有关系

**预期行为**
正常反馈疑问，可以解决最好

**用户文件**
<img width="292" alt="PixPin_2024-03-06_14-42-33" src="https://github.com/rime/weasel/assets/37500200/b1b18e35-b5dd-4458-b24b-13908c0b11eb">

**截图**
<img width="936" alt="PixPin_2024-03-06_14-42-09" src="https://github.com/rime/weasel/assets/37500200/105c060e-3c5e-4071-b7bc-fdd7fd8cac22">
<img width="356" alt="PixPin_2024-03-06_14-42-55" src="https://github.com/rime/weasel/assets/37500200/22df3c4f-225b-4ccb-83bc-97459cbf77fa">

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by mirtlecn** [comment]
https://github.com/rime/weasel/wiki/Weasel-定制化#字体
