### ISSUE TITLE
小狼毫不能重新部署

### ISSUE THREAD

**Issue by queyuewutong** [rime/weasel#1131]
**上报前请检查**
- [ ×] 我遇到的问题没有其他人在 issue 里提到过
- [ √] 我的小狼毫版本于 rime/weasel 下载
- [ √] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ 运行 winver.exe 获取，Windows 10LTSC版本]
 - 小狼毫版本: [ 如 0.15.0.0，近两个月更新的都不能用 ]

**描述遇到的问题**
不能重新部署，不能打字。

**复现步骤**
近两个月安装的都不能重新部署，两个月之前的版本可以

**预期行为**
请帮忙给解答一下怎么解决？

**Comment by fxliang** [comment]
信息量太少，无法评估

**Comment by 335869741** [comment]
小狼毫算法服务有没有重启？

**Comment by Hades-001** [comment]
我也是这个情况，安装之后算法服务启动不了，回退到 2 月前的版本才能正常启动。

**Comment by sci-42ver** [comment]
Here is one simple script workaround by re-executing `WeaselServer`.
```powershell
$path = Get-Process WeaselServer | Select-Object -ExpandProperty Path

$p = Get-Process -Name WeaselServer
Stop-Process -InputObject $p
Get-Process | Where-Object {$_.HasExited} # check whether exited

Start-Sleep -Milliseconds 1000
# since we need to quote the path "D:\Program Files (x86)\Rime\weasel-0.15.0\WeaselServer.exe" due to that it has sapces inside it, we need "&" https://stackoverflow.com/a/6338047/21294350
iex '& "$path"'
```

**Comment by Licolnlee** [comment]
想请问下style下设置的color_scheme_dark每次生效都必须重新部署，各位有遇到吗？

**Comment by sci-42ver** [comment]
> 想请问下style下设置的color_scheme_dark每次生效都必须重新部署，各位有遇到吗？

这些配置应该都必须 重新部署(deploy)吧 https://github.com/rime/home/wiki/CustomizationGuide#%E5%9C%A8%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE%E4%B8%AD%E6%B7%BB%E5%8A%A0%E4%BA%94%E7%AD%86%E9%9B%99%E6%8B%BC

**Comment by fxliang** [comment]
关于无法部署，留意一下错误日志里面有没有相关所在卷外部修改的报错，如果出现这个报错，是要将整个build目录删除了再部署才可以的。原因可能是上游的相关的一些逻辑漏洞要另外处理。错误日志位置默认是`%temp%`，文件名是`rime.weasel`开头的文件，错误日志带`ERROR`字样

**Comment by sci-42ver** [comment]
请问 使用小图标的重新部署 是不是 无法同步lua脚本, 如果build文件夹已经build相关schema和对应的custom?

通过查看 `$ grep -r "lua" /tmp/rime.weasel.DESKTOP-O0JBM8G.czg.log.*20240313-0* | grep "registering" | sort -t: -u -k1,1` 发现好像只有在启动server时 会同步.

**Comment by jdjxk** [comment]
同样问题，日志中未找到错误信息，删除build也没有解决，退回正式版使用正常

**Comment by queyuewutong** [comment]
> 关于无法部署，留意一下错误日志里面有没有相关所在卷外部修改的报错，如果出现这个报错，是要将整个build目录删除了再部署才可以的。原因可能是上游的相关的一些逻辑漏洞要另外处理。错误日志位置默认是`%temp%`，文件名是`rime.weasel`开头的文件，错误日志带`ERROR`字样

**Comment by queyuewutong** [comment]
> 同样问题，日志中未找到错误信息，删除build也没有解决，退回正式版使用正常

我也是。。。删除了仍然没有解决。我现在用的X64版本

**Comment by queyuewutong** [comment]
> 关于无法部署，留意一下错误日志里面有没有相关所在卷外部修改的报错，如果出现这个报错，是要将整个build目录删除了再部署才可以的。原因可能是上游的相关的一些逻辑漏洞要另外处理。错误日志位置默认是`%temp%`，文件名是`rime.weasel`开头的文件，错误日志带`ERROR`字样

删除了重新部署了仍然没有解决。删除build之后，出现了一次部署，但是只有一次，后面就仍然不行了

**Comment by sci-42ver** [comment]
> > 关于无法部署，留意一下错误日志里面有没有相关所在卷外部修改的报错，如果出现这个报错，是要将整个build目录删除了再部署才可以的。原因可能是上游的相关的一些逻辑漏洞要另外处理。错误日志位置默认是`%temp%`，文件名是`rime.weasel`开头的文件，错误日志带`ERROR`字样
> 
> 删除了重新部署了仍然没有解决。删除build之后，出现了一次部署，但是只有一次，后面就仍然不行了

> 删除build之后，出现了一次部署，但是只有一次，后面就仍然不行了

请问你的问题是 _更改后的schema之类文件_ 无法生效么? 可以看下INFO文件，查看它 `loading config file ...` 了哪些文件。一般应该只有更改的文件会重新build。

由于你是用Windows 10LTSC，我在windows 11 pro上使用时没有问题的，windows 10 不太清楚。

**Comment by jdjxk** [comment]
> > 同样问题，日志中未找到错误信息，删除build也没有解决，退回正式版使用正常
> 
> 我也是。。。删除了仍然没有解决。我现在用的X64版本

是的，换用64位版本一切正常

**Comment by sci-42ver** [comment]
抱歉，你们好像用的是 nightly build (Pre-release)，我的上述comments都是基于Latest。讲的不在一个频道上。

这个问题如果一定要解决，应该只能看修改的源代码，我之前只研究过部分librime代码，关于weasel的代码没看过。定位一下出问题的commit, 然后查看修改的代码分析并作相应修改。

看了一下 [0.15.0 和 latest 的 diff](https://github.com/rime/weasel/compare/0.15.0...latest), 其使用了新的clang-format配置，不太好在网页上查看问题出在哪。

**Comment by fxliang** [comment]
如果不能部署，只要看WeaselDeploy的commit log就可以了，实际上从0.14.3以来改动不大

经我手的一些修改主要是
- 中文路径的修复
- 无default.custom.yaml或weasel.custom.yaml情况下无法部署
- 语言本地化
- 用户目录预览图
- 一些关联的文本编码转换函数的变化

如果只到0.15.0,那修改更少

关于无法新部署，我自己有遇到的是和上游关联的“所在卷外部修改”引发的异常

所以要定位问题，可能要你的脱敏数据，版本号（commit），系统信息才有的继续查

**Comment by Yik0o** [comment]
> 如果不能部署，只要看WeaselDeploy的commit log就可以了，实际上从0.14.3以来改动不大
> 
> 经我手的一些修改主要是
> 
> * 中文路径的修复
> * 无default.custom.yaml或weasel.custom.yaml情况下无法打开对话框
> * 语言本地化
> * 用户目录预览图
> * 一些关联的文本编码转换函数的变化
> 
> 如果只到0.15.0,那修改更少
> 
> 关于无法新部署，我自己有遇到的是和上游关联的“所在卷外部修改”引发的异常
> 
> 所以要定位问题，可能要你的脱敏数据，版本号（commit），系统信息才有的继续查

我就是突然无法部署了，升级到0.163也没用，重新拉一遍方案也没用。也试了试上面你提到的办法，依旧发不出字，只有下划线。这是log
`Log file created at: 2024/10/18 06:44:44
Running on machine: DESKTOP-SLCGJ72
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
E20241018 06:44:44.110503 16304 modules.cc:77] rime.lua error: C:\Users\Yi.k0\AppData\Roaming\Rime\rime.lua:39: module 'search' not found:
	no field package.preload['search']
	no file 'C:\Users\Yi.k0\AppData\Roaming\Rime\lua\search.lua'
	no file 'C:\Users\Yi.k0\AppData\Roaming\Rime\lua\search\init.lua'
	no file 'D:\Rime\weasel-0.16.3\data\lua\search.lua'
	no file 'D:\Rime\weasel-0.16.3\data\lua\search\init.lua'
	no file 'D:\Rime\weasel-0.16.3\lua\search.lua'
	no file 'D:\Rime\weasel-0.16.3\lua\search\init.lua'
	no file 'D:\Rime\weasel-0.16.3\search.lua'
	no file 'D:\Rime\weasel-0.16.3\search\init.lua'
	no file 'D:\Rime\weasel-0.16.3\..\share\lua\5.4\search.lua'
	no file 'D:\Rime\weasel-0.16.3\..\share\lua\5.4\search\init.lua'
	no file '.\search.lua'
	no file '.\search\init.lua'
	no file 'D:\Rime\weasel-0.16.3\search.dll'
	no file 'D:\Rime\weasel-0.16.3\..\lib\lua\5.4\search.dll'
	no file 'D:\Rime\weasel-0.16.3\loadall.dll'
	no file '.\search.dll'
`

**Comment by fxliang** [comment]
你这个是方案没有抄完整，里面用的lua脚本不存在所以过不了
` rime.lua error: C:\Users\Yi.k0\AppData\Roaming\Rime\rime.lua:39: module 'search' not found:`

**Comment by Yik0o** [comment]
雾凇拼音方案，去他那儿反应了，最新方案没人出现我这个问题。我只直接整个解压包丢进去的，没有做任何修改

**Comment by Yik0o** [comment]
[rime.weasel.DESKTOP-SLCGJ72.Yi.k0.log.INFO.20241018-115808.21816.log](https://github.com/user-attachments/files/17427757/rime.weasel.DESKTOP-SLCGJ72.Yi.k0.log.INFO.20241018-115808.21816.log)
又重新拉了一遍，这次log更完整了，不过看不懂😭😭

**Comment by fxliang** [comment]
检查你的配置，雾凇拼音加最新小狼毫测试部署结束后正常打字，现在就是用雾凇回复的
