### ISSUE TITLE
单个字体的字形设置，会影响其他字体序列

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#1132]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - 小狼毫版本: https://github.com/rime/weasel/actions/runs/8167510638

**描述遇到的问题**

写 wiki 时候无意间试出来的，简单的例子：

```yaml
style/font_face: "仿宋::80:Italic , Microsoft Yahei UI"
```

仿宋的斜体设置，影响到了后面的微软雅黑：

![image](https://github.com/rime/weasel/assets/76689045/f42668a9-a0fd-4443-8f5a-1d3b49463db1)

```yaml
style/font_face: "仿宋::80:Italic , Microsoft Yahei UI:normal"
```

微软雅黑的普通字形设置，影响到了前面的仿宋。

![image](https://github.com/rime/weasel/assets/76689045/ca287778-b1cf-4e2e-8939-d76e67459202)

**Comment by fxliang** [comment]
https://github.com/rime/weasel/wiki/%E5%AD%97%E9%AB%94%E8%A8%AD%E5%AE%9A

暂不支持每个字体分别设置字形字重
