### ISSUE TITLE
无法正确捕获小键盘的功能键

### ISSUE THREAD

**Issue by demon-Dark** [rime/weasel#1133]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [Windows 10 22H2 19045.4046]
 - 小狼毫版本: [ 0.15.0.0  [4d70cdd] ]

**描述遇到的问题**
- 无法正确捕获小键盘的功能键,如KP_Home
- 小键盘5的对应功能键未找到
**复现步骤**
在配置文件内加入且重新部署后,没有改变按键功能
```
    - {accept: KP_Insert, send: KP_Space, when: always}
    - {accept: KP_Home, send: 1, when: always}
    - {accept: KP_Up, send: 2, when: always}
    - {accept: KP_Page_Up, send: 3, when: always}
    - {accept: KP_Left, send: 4, when: always}
    - {accept: KP_Clear, send: 5, when: always}
    - {accept: KP_Tab, send: 6, when: always}
    - {accept: KP_End, send: 7, when: always}
    - {accept: KP_Down, send: 8, when: always}
    - {accept: KP_Page_Down, send: 9, when: always}
```
**预期行为**
改变成设置的对应按钮

**用户文件**

**截图**

**其他补充说明**

**Comment by nulllee** [comment]
忘了在哪里看到的来着，作者用的键盘没有小键盘，所以可能作者不会去做这个功能。

**Comment by lotem** [comment]
键值不对。

NumLock打开时，发送 KP_0…KP_9 等数字键。NumLock关闭时，发送 Home…Delete 等编辑键。
