### ISSUE TITLE
`app_options` 无法生效 (尽管配置了环境变量)

### ISSUE THREAD

**Issue by sci-42ver** [rime/weasel#1138]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ 运行 winver.exe 获取，如 Windows 11 22H2 22621.1555]
   - Windows 11 22H2 22621.3155 基于 `winver.exe`
     但是
     ```powershell
     $ (Get-Item "HKLM:SOFTWARE\Microsoft\Windows NT\CurrentVersion") # https://superuser.com/a/1640261/1658455
                                    ProductName               : Windows 10 Pro
     ```
     可能由于使用 Windows 10 key 来激活电脑, 然后 [使用这个Windows 10 key来更新windows 11](https://answers.microsoft.com/en-us/windows/forum/all/activate-windows-11-with-windows-10-key/2db8ddb6-dc89-41a0-8cd9-9d4c321342e0).
 - 小狼毫版本: [ 如 0.15.0.0 ， CI 构建版请附短 commit hash ，如 372c9c ]
   - 0.15.0

**描述遇到的问题**
在 build 文件夹 "D:\Rime\Data\build", "D:\Rime\Data\build\weasel.yaml" 已经成功编译, 并有
```yaml
app_options:
  Code.exe:
    ascii_mode: true
```
通过运行 `"C:\Windows\system32\rundll32.exe" sysdm.cpl,EditEnvironmentVariables` 检查环境变量, "D:\Users\czg\AppData\Local\Programs\Microsoft VS Code" 已经在 "User variables->Path". 前者包含要运行的程序 "Code.exe".

**复现步骤**
重现问题的步骤，如：
1. 打开 'Code.exe' 软件
2. 输入 'abc'
3. 依然使用输入法 而不是直接上屏字母 (即 `ascii_mode:false`).

**预期行为**
直接上屏字母 基于以上配置 `app_options ... ascii_mode: true`.

**用户文件**
由于过长, 此处我仅在上方贴出 build 文件夹里的相关内容.

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
之前我大部分时间使用linux, 一直用的是ibus-rime->fcitx5-rime, 它貌似[不支持 app_options](https://github.com/rime/librime/issues/374#issuecomment-638694888)

**Comment by mirtlecn** [comment]
https://github.com/rime/weasel/wiki/Weasel-%E5%AE%9A%E5%88%B6%E5%8C%96#%E5%BA%94%E7%94%A8%E8%AE%BE%E7%BD%AE

**Comment by sci-42ver** [comment]
这个问题问得有些多余 抱歉. wiki里已经提供了答案(有人comment提供hint后,删除了comment.)
