### ISSUE TITLE
小狼毫如何实现候选高亮全包无边框？

### ISSUE THREAD

**Issue by isPoto** [rime/weasel#1139]
我想要实现这种高亮全包的效果，即候选高亮与边角完全融合，没有边框：
https://imagehost.mintimate.cn/post_rimeQucikInit/hotkeys_macOS.jpg

而目前默认是这样的：
https://www.yumefx.com/wp-content/uploads/2021/02/RIME_02.jpg

但目前我查阅资料和模板并没有发现相关实现信息
似乎是 Mac Only
我想知道小狼毫如何做到这样的效果

由于我无法上传图片，不知道为什么，我只能发图片链接，需点进去看图

**Comment by fxliang** [comment]
https://github.com/rime/weasel/wiki/%E7%A4%BA%E4%BE%8B#%E7%AB%96%E6%8E%92-%E5%A4%A9%E5%9C%86%E5%9C%B0%E6%96%B9

核心是margin_x/margin_y <= hilite_padding_x/hilite_padding_y(如果margin < hilite_padding的时候会解析为和hilite_padding一样的数值）, 如果没有单独设置hilite_padding_x/hilite_padding_y, 那hilite_padding_x/hilite_padding_y = hilite_padding
