### ISSUE TITLE
Word 2016 在英文模式中，無法連續輸入半形英文符號

### ISSUE THREAD

**Issue by MarkenChen** [rime/weasel#1142]
**操作系统信息**
 - OS 详细版本:  Windows 11 23H2 
 - 小狼毫版本: 0.15.1.007 x64  [https://github.com/Techince/weasel/releases](https://github.com/Techince/weasel/releases)

**描述遇到的问题**
使用Word 2016 標準版時，當切換到英文模式(顯示A)時，連續輸入半形(半角)英文符號時(例如 !@#$%^)，只會出現第1個字，然後就下一個符號就無法上字，例如我要輸續輸入  !@ ，只會上字! ，但是可以按方向鍵，就可以輸入第2個字。
但是在，在 Excel 2016 和 PowerPoint 2016、和其他程式 都是正常的，目前只發現Word 2016會這樣子。
另外全形(全角)連續輸入符號 ！＠＃，也是正常的。
另外，試過內建的 注音、拚字 輸入法，也是同樣的問題。

**复现步骤**
重现问题的步骤，如：
1. 打開Word軟體
2. 切換到注音、拚字或是無蝦米 輸入法
3. 切換到 半形(半角)
4. 連續輸入英文符號  !@#$%^
5. 只會上字 第1 個符號  ! 
6. 輸入 ! 方向鍵  @ 方向鍵 # .... 就可以顯示  !@#

**预期行为**
可連續輸入英文半形符號，例如 !@#$%

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题
[Rime.zip](https://github.com/rime/weasel/files/14621751/Rime.zip)

**Comment by fxliang** [comment]
经查主仓产物未复现描述的问题，建议联系 @Techince 另外解决

**Comment by Techince** [comment]
经测试，输入「@#$%」时，它们都出现在候选框里，有的是候选列表的第一条，有的则是第二条。改成英文模式可以连续上屏，中文模式下因为有候选列表，输入内容不会直接上屏。

**Comment by fxliang** [comment]
他描述的问题是在ascii mode下的吧
> 使用Word 2016 標準版時，當切換到英文模式(顯示A)時，連續輸入半形(半角)英文符號時(例如 !@#$%^)，只會出現第1個字，然後就下一個符號就無法上字，例如我要輸續輸入 !@ ，只會上字! ，但是可以按方向鍵，就可以輸入第2個字。

**Comment by Techince** [comment]
[007](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本可以在ascii_mode下直接上屏。

**Comment by MarkenChen** [comment]
> [007](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本可以在ascii_mode下直接上屏。

我就是使用 007 版本的，也只有在Word 2016會這樣子，Excel 2016 PowerPoint 2016 都不會，其他程式也沒發現，全型也沒問題，半型英文符號才會，所以不知道是不是我的電腦設定的關係。如果大家都測不出來，只能再等新的版本試試看。

**Comment by Techince** [comment]
> > [007](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本可以在ascii_mode下直接上屏。
> 
> 我就是使用 007 版本的，在(A)的模式下 Word 2016 才會這樣子，Excel 2016 PowerPoint 2016 都不會，其他程式也沒發現，在A模式全型也沒問題，半型英文符號才會，所以不知道是不是我的電腦設定的關係。如果大家都測不出來，只能再等新的版本試試看。

Word 2021测试没有问题，明天找个Word 2016的环境再测试一下。
