### ISSUE TITLE
在Waterfox上无法使用小狼毫在部分网页的输入栏内进行输入

### ISSUE THREAD

**Issue by sojuo** [rime/weasel#1144]
**操作系统信息**
 - OS 详细版本: 版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎7/‎8
操作系统内部版本	19045.4046
体验	Windows Feature Experience Pack 1000.19053.1000.0

 - 小狼毫版本:  0.15.0.0 ， [fe91172](https://github.com/rime/weasel/commit/fe911727c687ea827aa17eea6b100c33cc4b9500) ]

**描述遇到的问题**
无法在Waterfox上使用小狼毫输入法在[Telegram](web.telegram.org)等部分网站的输入栏输入。

**复现步骤**
在Waterfox上使用小狼毫输入法在[Telegram](web.telegram.org)网页内的聊天栏内进行输入。

**预期行为**
可以正常输入字符

**用户文件**
[Rime.zip](https://github.com/rime/weasel/files/14626826/Rime.zip)

**截图**
![waterfox_CPfF3rIMN1](https://github.com/rime/weasel/assets/109811457/f6bd690f-5f33-4631-941a-ff0220d47c67)

**其他补充说明**
目前已发现此Bug会出现在Waterfox上，Firefox上暂未发现类似Bug，Chromium系列浏览器暂未测试。

**Comment by lianzhoulu** [comment]
> 能输上文字的输入法都是inline_preedit: true模式。 小狼毫使用此模式也可以输入内容的。

在`weasel.custom.yaml`文件夹内添加`"style/inline_preedit": true`后似乎无效？
![图片](https://github.com/rime/weasel/assets/109811457/63673bb2-f14e-4b56-a471-612348425d7e)

**Comment by lianzhoulu** [comment]
> 能输上文字的输入法都是inline_preedit: true模式。 小狼毫使用此模式也可以输入内容的。

感谢指导，在`\Rime\weasel.custom.yaml`内添加了`"inline_preedit": true`后便可以正常使用了。

**Comment by sojuo** [comment]
iron

> 能输上文字的输入法都是inline_preedit: true模式。 小狼毫使用此模式也可以输入内容的。

在重裝了系統重新下載小狼毫並按照原來在`\Rime\weasel.custom.yaml`内添加`"inline_preedit": true`的方法配置後似乎又出現了上述無法輸入的情況？

**Comment by sojuo** [comment]
> iron
> 
> > 能输上文字的输入法都是inline_preedit: true模式。 小狼毫使用此模式也可以输入内容的。
> 
> 在重裝了系統並重新下載小狼毫並按照原來在`\Rime\weasel.custom.yaml`内添加`"inline_preedit": true`的方法配置後似乎又出現了上述無法輸入的情況？

勉強解決了，在`\Rime\build\weasel.yaml`中添加`inline_preedit: true`即可解決。但這樣的話就會導致自己輸入的內容不在小狼毫自带的候选框内显示显示预编辑内容，而是在相应程序内显示预编辑内容……
