### ISSUE TITLE
不能拖动候选框

### ISSUE THREAD

**Issue by byzod** [rime/weasel#1146]
**上报前请检查**
- [✔] 我遇到的问题没有其他人在 issue 里提到过
- [✔] 我的小狼毫版本于 rime/weasel 下载
- [✔] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 21H2 19044.3086
 - 小狼毫版本:  .0.15.0 (2023-06-06)

**描述遇到的问题**
不能拖动候选框

比方说对线的时回头改上面的句子、写issue时确认下面填的信息、更新信用卡地址1时想看看地址2填了没有、做meme时根据下面图片的表情捏台词等等等等等，由于候选框总是跟随输入点，必然会出现遮挡下面/右面文字或图片的时候

不如说很奇怪为社么issue里完全没有搜到有人提到这个问题啊？

**复现步骤**
> ![1](https://github.com/rime/weasel/assets/848607/e4cf0abd-a25a-4697-a26a-df1f4f302080)

**预期行为** （QQ拼音）
> ![An1](https://github.com/rime/weasel/assets/848607/c94fb73d-9f43-44d9-979f-058beb182f94)

**用户文件**
略，可用默认配置（朙月拼音）复现

**Comment by Techince** [comment]
这个[x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本支持此功能，但想拖动候选框时，需要执行一次快捷键，或从菜单里选择。

**Comment by byzod** [comment]
> 这个[x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)版本支持此功能，但想拖动候选框时，需要执行一次快捷键，或从菜单里选择。

感谢。~就是好像有点麻烦😢~
