### ISSUE TITLE
提供64位的小狼毫构建

### ISSUE THREAD

**Issue by fxliang** [rime/weasel#1147]
#1121 欢迎测试反馈😀

- 在同一个安装包内提供64位和32位构建产物，安装包自动识别系统版本安装对应的程序（包括ARM/ARM64)，64位应用和32位应用协议兼容，新的Server/Deployer与旧安装的tsf协议兼容。
- 支持部署大词库，64位构建默认支持较大词库部署；32位版本的程序，在64位系统下，结合librime的nightly 构建（msvc），支持最大4GB的内存访问能力，可以构建较大的词库，空明码测试通过；如是32位程序在32位系统上，可访问内存依赖系统的4GT设置
- 为程序的dll/exe添加版本信息，正式版数字型版本号，nightly版带commit short id的版本号
- 修复WeaselDeployer中的部分繁体中文环境本土化字符串显示，更新comctl版本到6.0，界面更现代风格
- 更新WinSparkle到0.8.1

已知问题：
- 未处理部分应用中的TSF识别问题
- ~~仍然会有部分杀毒软件会误报，主要集中在32位构建的tsf dll `weasel.dll`和`weaselt.dll`~~

**Comment by Qeynos** [comment]
安装目录默认仍为x86，使用上暂时没有异常

**Comment by fxliang** [comment]
> 安装目录默认仍为x86，使用上暂时没有异常

因为安装包是x86的，所以默认安装目录是x86，实际安装的是根据系统状态判定的

**Comment by Qeynos** [comment]
不知什么时候开始，更新不需要重启也不会报错崩溃了，真好，感谢您的付出

**Comment by Qeynos** [comment]
"style/layout/min_height"设置的参数与最新的nightly不同，我使用竖排的候选框，6行候选词，原本设置300可以保持候选词不足6行时保持高度，现在需要调整到320才行

**Comment by fxliang** [comment]
但是没有动ui和ui参数读取的内容呢

**Comment by fxliang** [comment]
> 每次打开总有惊喜。不过，word中拖动标尺后，候选框闪烁问题为啥迟迟不完善解决呢😁

https://github.com/fxliang/weasel/actions/runs/8339858495，试了两个commit，可能可以解决（我没试出问题）

**Comment by changzaicl** [comment]
谢谢🙏 
我测试这2个commit，的确解决了。真的是手到病除呀👍

**Comment by fxliang** [comment]
> 谢谢🙏 我测试这2个commit，的确解决了。真的是手到病除呀👍

我只是将Techince的pr调整了下修改了点东西而已，纯抄

**Comment by changzaicl** [comment]
@fxliang 那个word闪烁的修复，可否更新到https://github.com/rime/
[weasel]。
现在是一尝鲜新版本，这个word闪烁的问题，还是会出现。总是催促，添麻烦了

**Comment by fxliang** [comment]
> @fxliang 那个word闪烁的修复，可否更新到现在新版本中。 现在是一尝鲜新版本，这个word闪烁的问题，还是会出现。总是催促，添麻烦了

早前那个link，还是会出现吗？https://github.com/fxliang/weasel/actions/runs/8339858495

**Comment by changzaicl** [comment]
这个链接中的，我测试了很多次，都不会出现。
但是https://github.com/rime/weasel/actions下新的commit还是会出现。

**Comment by fxliang** [comment]
> 这个链接中的，我测试了很多次，都不会出现。 但是https://github.com/rime/weasel/actions 下新的commit还是会出现。

原来Techince在提pr的，今早忽然见他似乎不知为何关了那个pr。
另外加了个#1155

**Comment by changzaicl** [comment]
Actions下新的commit会在edge浏览器中输入不了中文，只能直接输入英文字母。输入切换几次才可以输入中文，确定不是配置的问题

**Comment by fxliang** [comment]
> Actions下新的commit会在edge浏览器中输入不了中文，只能直接输入英文字母。输入切换几次才可以输入中文，确定不是配置的问题

和之前那两个commit是一样的修改，只是合并到一个commit了。

**Comment by changzaicl** [comment]
(https://github.com/fxliang/weasel/commit/cd9953efd386a5837c773258f371ba9026ee4dd0)，下最新的([cd9953e] 我在word中多次尝试均未出现之前的“拖动标尺闪烁”的情况。
但是在浏览器地址栏，浏览器内容需要输入的时候都是只能输入英文字母。切换一次输入法后，才可以输入中文。请核实。谢谢！

**Comment by Qeynos** [comment]
> [cd9953e](https://github.com/fxliang/weasel/commit/cd9953efd386a5837c773258f371ba9026ee4dd0)，下最新的([[cd9953e](https://github.com/rime/weasel/commit/cd9953efd386a5837c773258f371ba9026ee4dd0)] 我在word中多次尝试均未出现之前的“拖动标尺闪烁”的情况。 但是在浏览器地址栏，浏览器内容需要输入的时候都是只能输入英文字母。切换一次输入法后，才可以输入中文。请核实。谢谢！

我刚刚试过，没有发现浏览器输入前需要切换的问题

**Comment by changzaicl** [comment]
我也试了一下，又可以了。偶发现象，我暂时还没找到如何复现，但是肯定会有。
等我搞明白如何复现，再来汇报。

**Comment by changzaicl** [comment]
![无法输入中文情况_2024-03-27_20-52-33](https://github.com/rime/weasel/assets/144407904/86c704da-61aa-4742-a45e-fd0022457629)
这个实在Foxmail中出现的，在主题等位置可以输入，但是正文中是英文状态，看标点都是英文的。类似无法在浏览器中输入的情况，浏览器中我还是会出现，但是目前还是无法找不到复现的方法。

**Comment by changzaicl** [comment]
这个时间段的log如下，希望有帮助。

'"D:\\RIME\\build\\radical_pinyin.schema.yaml"'.
I20240327 20:51:09.863272 10612 dictionary.cc:324] loading dictionary 'radical_pinyin'.
I20240327 20:51:09.864275 10612 engine.cc:130] updated option: emoji
I20240327 20:51:09.864275 10612 engine.cc:144] updated property: client_app
I20240327 20:51:09.864275 10612 engine.cc:144] updated property: client_type
I20240327 20:51:09.864275 10612 engine.cc:130] updated option: inline_preedit
I20240327 20:51:09.864275 10612 engine.cc:130] updated option: soft_cursor
I20240327 20:51:09.865275 10612 engine.cc:130] updated option: inline_preedit
I20240327 20:51:09.865275 10612 engine.cc:130] updated option: soft_cursor
I20240327 20:51:10.995379 10612 simplifier.cc:35] initializing opencc: "D:\\RIME\\opencc\\My.json"
I20240327 20:51:51.938127  2324 engine.cc:74] starting engine.
I20240327 20:51:51.938127  2324 engine.cc:130] updated option: _auto_commit
I20240327 20:51:51.938127  2324 dictionary.cc:324] loading dictionary 'rime_ice_My'.
I20240327 20:51:51.939361  2324 dictionary.cc:324] loading dictionary 'melt_eng'.
I20240327 20:51:51.939361  2324 dictionary.cc:324] loading dictionary 'radical_pinyin'.
I20240327 20:51:51.940392  2324 config_data.cc:68] loading config file '"D:\\RIME\\build\\radical_pinyin.schema.yaml"'.
I20240327 20:51:51.943714  2324 dictionary.cc:324] loading dictionary 'radical_pinyin'.
I20240327 20:51:51.944720  2324 engine.cc:130] updated option: emoji
I20240327 20:51:51.944720  2324 engine.cc:144] updated property: client_app
I20240327 20:51:51.944720  2324 engine.cc:144] updated property: client_type
I20240327 20:51:51.944720  2324 engine.cc:130] updated option: inline_preedit
I20240327 20:51:51.944720  2324 engine.cc:130] updated option: soft_cursor
I20240327 20:51:51.944720  2324 engine.cc:130] updated option: inline_preedit
I20240327 20:51:51.944720  2324 engine.cc:130] updated option: soft_cursor
I20240327 20:52:34.816519  3468 engine.cc:74] starting engine.
I20240327 20:52:34.817523  3468 engine.cc:130] updated option: _auto_commit
I20240327 20:52:34.817523  3468 dictionary.cc:324] loading dictionary 'rime_ice_My'.
I20240327 20:52:34.817523  3468 dictionary.cc:324] loading dictionary 'melt_eng'.
I20240327 20:52:34.818526  3468 dictionary.cc:324] loading dictionary 'radical_pinyin'.
I20240327 20:52:34.820523  3468 config_data.cc:68] loading config file '"D:\\RIME\\build\\radical_pinyin.schema.yaml"'.
I20240327 20:52:34.825636  3468 dictionary.cc:324] loading dictionary 'radical_pinyin'.
I20240327 20:52:34.826517  3468 engine.cc:130] updated option: emoji
I20240327 20:52:34.826517  3468 engine.cc:144] updated property: client_app
I20240327 20:52:34.826517  3468 engine.cc:144] updated property: client_type
I20240327 20:52:34.826517  3468 engine.cc:130] updated option: inline_preedit
I20240327 20:52:34.826517  3468 engine.cc:130] updated option: soft_cursor
I20240327 20:52:34.827518  3468 engine.cc:130] updated option: inline_preedit
I20240327 20:52:34.827518  3468 engine.cc:130] updated option: soft_cursor
I20240327 20:52:47.436273  9476 simplifier.cc:35] initializing opencc: "D:\\RIME\\opencc\\My.json"
I20240327 20:53:17.716128  4888 engine.cc:74] starting engine.
I20240327 20:53:17.717128  4888 engine.cc:130] updated option: _auto_commit
I20240327 20:53:17.717128  4888 dictionary.cc:324] loading dictionary 'rime_ice_My'.
I20240327 20:53:17.717128  4888 dictionary.cc:324] loading dictionary 'melt_eng'.
I20240327 20:53:17.717128  4888 dictionary.cc:324] loading dictionary 'radical_pinyin'.
I20240327 20:53:17.719128  4888 config_data.cc:68] loading config file '"D:\\RIME\\build\\radical_pinyin.schema.yaml"'.

**Comment by changzaicl** [comment]
![edge中无法输入中文_2024-03-27_21-17-24](https://github.com/rime/weasel/assets/144407904/2c639d41-ee02-43d8-9510-26a6621a3d94)

edge zong, including here, I can not input Chinese（来回切换后，可以输入了）

**Comment by fxliang** [comment]
是有点问题，我pb分支改了点东西可能试试，不过似乎会第一次输入要keyup才弹出的感觉。要再看了

**Comment by changzaicl** [comment]
目前试了一个快小时了，在edge、Foxmail中均可以输入。

**Comment by fxliang** [comment]
> 目前试了一个快小时了，在edge、Foxmail中均可以输入。

留意一下新打开应用的时候第一个按键下去的时候是不是要弹起按键的时候才有候选框出来，我试过在虚拟机里和实体机上表现有一点不太一样

**Comment by dangpengsong** [comment]
发现一个很奇怪的bug，在 https://greasyfork.org/zh-CN/scripts/by-site/github.com 里面搜索框输入的时候候选框闪一下就没了，调试发现跟div的flex布局相关，这是什么神奇的bug

![shanshuo](https://github.com/rime/weasel/assets/10460635/ae6a99bb-45bd-4d67-adba-51d2e4d9f548)
![微信图片_20240329091405](https://github.com/rime/weasel/assets/10460635/874ef4b5-a2b7-4b78-9a92-8ddb54e20552)
