### ISSUE TITLE
【功能请求】Windows的“开关键盘逻辑”默认为“切换中英文”

### ISSUE THREAD

**Issue by hzinchengdu** [rime/weasel#1149]
【功能请求】
Windows的“Ctrl+Space开关键盘逻辑”默认为“切换中英文”

或者

1. Windows可配置的“开关键盘逻辑为切换中英文”；
2. Windows可配置的“开关输入法全局一致，类似于global ascii: true”；
3. Windows可配置的“关闭输入法时：‘上屏正在输入的字母序列’或‘清除未上屏内容’”。

原因：
1. 几乎所有的输入法在大众看来没有“开启/关闭输入法”的概念；
2. 所有的大众输入法都可配置“上屏正在输入的字母序列”或“清除未上屏内容”；
3. 现代Windows系统默认所有窗口使用相同的输入法状态（看见测试版已实现global ascii: true）。

希望实现和大众输入法相同的功能，目前有位开发者在[fork版](https://github.com/zhylmzr/weasel)上实现了（[在我的请求下](https://github.com/zhylmzr/weasel/issues/1)），这位开发者也贡献了global ascii的相关代码。

**Comment by fxliang** [comment]
> Windows可配置的“开关输入法全局一致，类似于global ascii: true”；
> Windows可配置的“关闭输入法时：‘上屏正在输入的字母序列’或‘清除未上屏内容’”。

#1096 之后，global_ascii已完整实现，以上两点已完整实现。

> 几乎所有的输入法在大众看来没有“开启/关闭输入法”的概念；
Windows可配置的“开关键盘逻辑为切换中英文”；

但是微软API是有的，`Control+Space`是一个系统业务操作，输入法只是响应这个业务的结果作出一点标识上的变化和适当的关闭输入法内部的一些工作流。如果强制限制不能关闭键盘，这个操作有点不合理。所以应该是短期内不会有这个动作处理。

**Comment by hzinchengdu** [comment]
作为一个大众输入法用户，第一句没看懂。从大众的使用习惯上来讲，反而是Rime在这个地方做得不合理，因为没留可选项供用户选择。
1. 现代Windows系统上几乎所有的输入法按`Ctrl+Space`都是切换中英文状态；
2. 用户的习惯会随着系统功能的改变而改变。
    - 例子1：Windows XP默认所有窗口的输入法状态都不统一，而现在是默认所有窗口的状态都统一（习惯XP的老用户也可以勾选“允许我为每个应用窗口使用不同的输入法”选项来遵循以往的习惯）。
    - 例子2：在现代Windows系统中，`Ctrl+Space`在用户看来是切换中英文状态，那自然有一定的用户基数是用这个模式切换的。

从大众的角度来说，Rime不合理的地方：
1. 在现代Windows系统中，不勾选“允许我为每个应用窗口使用不同的输入法”选项时，几乎所有的输入法都按这个模式执行，而Rime却按照XP系统的逻辑执行，这与系统的选项不一致，显然不合理。
2. Rime最近才实现了global_ascii，这对一些习惯所有窗口的状态都一致的用户来说是天大的好事，相信实现这个功能经过了很多大众看不懂的论证。但是对于习惯用`Ctrl+Space`切换中英文的用户，发现开关输入法状态仍然不一致，每个窗口的开关状态都是独立的。
3. 其他输入法用`Ctrl+Space`基本上看起来是切换中英文状态，那为什么不做个类似于global_ascii的可选项留给大众选择呢。

**Comment by fxliang** [comment]
> 其他输入法用Ctrl+Space基本上看起来是切换中英文状态，那为什么不做个类似于global_ascii的可选项留给大众选择呢。

因为你的理解有误

`Ctrl+Space`关闭键盘，再打字输出的内容，取决于当前输入法的注册语言。如果是简体中文或者繁体中文的注册语言，则在键盘关闭的时候输出的是英文字母；如果是中文维语的注册，则输出的是维语字母。并非是你所说的中英文这样。

扩展来说，Rime的ascii_mode，因为键盘未关闭，逻辑仍然是要将按键传递当前的按键键码到librime后端处理返回。有些方案会添加ascii_mode下的processor的时候，就会有对应的响应处理，比如有某English方案就是这样。

但是如果键盘关闭，那这些按键将不再传递到后端，而是直接上屏按键，这时上屏的内容取决于当前输入法注册的语言对应 的键盘字符（如上所述）。从而关闭键盘和ascii_mode其实是两种不一样的逻辑，不能视同。

> Rime最近才实现了global_ascii，这对一些习惯所有窗口的状态都一致的用户来说是天大的好事，相信实现这个功能经过了很多大众看不懂的论证。但是对于习惯用Ctrl+Space切换中英文的用户，发现开关输入法状态仍然不一致，每个窗口的开关状态都是独立的。

这个是Rime的特色，如果这个都要去除，那不如多装一个输入法其实并不太点磁盘。会做global_ascii是因为这个做下来其实并不太费事（只修改服务端），而且并未引入问题，也没有受TSF影响。

**Comment by fxliang** [comment]
[test_tsf.zip](https://github.com/rime/weasel/files/14648636/test_tsf.zip)

附件是两个dll，我将hant状态的注册语言改为了中文维语，你可以试在管理员模式下运行以下命令注册输入法或解除注册
注册之后，不管你怎么`Ctrl+Space`，上屏的一定是维语字母不是英文字母。

```cmd
regsvr32 weaselt.dll
regsvr32 weaseltx64.dll
```
解注册
```cmd
regsvr32 /u weaselt.dll
regsvr32 /u weaseltx64.dll
```

![image](https://github.com/rime/weasel/assets/4023160/746e3c17-7da7-4072-bbd4-beb310c1037b)

**Comment by hzinchengdu** [comment]
好的，但华人使用输入法的所有使用场景几乎都是中英之间的切换。

你说的“多装一个输入法其实并不太占磁盘”我认同，但我认为市面上除了系统自带的输入法和Rime，还有一个mac上的落格输入法，其他都不怎么样，搜狗输入法是流氓软件，影子输入法我觉得还不成熟。

有网友说推荐用Alt+Shift切换中英文，我觉得这些人是没有考虑有多种语言输入的需求才说这种话（比如中文、英文、日文、法文之间怎么切换比较合理）。

我现在太忙了，等我不忙时学编程自己改代码实现。

**Comment by fxliang** [comment]
不用学，直接告诉你怎么改
![image](https://github.com/rime/weasel/assets/4023160/b1ec6539-e73d-4906-b40b-c48e1933353b)


> 好的，但华人使用输入法的所有使用场景几乎都是中英之间的切换。
> 
> 你说的“多装一个输入法其实并不太占磁盘”我认同，但我认为市面上除了系统自带的输入法和Rime，还有一个mac上的落格输入法，其他都不怎么样，搜狗输入法是流氓软件，影子输入法我觉得还不成熟。
> 
> 有网友说推荐用Alt+Shift切换中英文，我觉得这些人是没有考虑有多种语言输入的需求才说这种话（比如中文、英文、日文、法文之间怎么切换比较合理）。
> 
> 我现在太忙了，等我不忙时学编程自己改代码实现。

**Comment by fxliang** [comment]
> 好像没这么简单，前面的判断和切换回来的逻辑也要改

似乎有道理，这个只是不让关语言栏了，呵呵
