### ISSUE TITLE
【功能请求】font_face可以像CSS的font-family一样选择多种字体

### ISSUE THREAD

**Issue by hzinchengdu** [rime/weasel#1150]
输入法样式的font_face可以像CSS的font-family一样选择多种字体，按照从前往后的优先级读取，这样可以解决字库不完善导致部分字符无法显示的问题。

比如：
```
"style/font_face": "Microsoft YaHei", "MiSans L3", "苹方-简体"
```

**Comment by yanhuacuo** [comment]
已经实现了,而且更进一步，可以用 Unicode Point 来绑定特定字体的渲染。

https://github.com/rime/weasel/wiki/%E5%AD%97%E9%AB%94%E8%A8%AD%E5%AE%9A#%E5%AD%97%E9%AB%94%E5%AE%B6%E6%97%8F%E5%90%8D%E5%AD%97-family-name
