### ISSUE TITLE
无法使用网页的快捷键, 例如油管, B站的视频

### ISSUE THREAD

**Issue by LuomingXu** [rime/weasel#1151]
### 操作系统信息
 - OS 详细版本: win11 23H2(22631.3296)
 - 小狼毫版本: fe91172

### 描述遇到的问题
无法在中文模式下使用网页快捷键(油管, B站), 例如全屏播放"f", 剧场模式"t"

### 复现步骤
重现问题的步骤，如：
- 处于中文模式下
- 随便打开个视频试试

### 其他补充说明
个人感觉是#997 提到过的问题@fxliang做了一部分解答
https://github.com/rime/weasel/issues/997#issuecomment-1751562982
> 这个问题，不仅仅是输入法的问题，潜在的问题是vimnium应该在退出insert mode 的时候应该禁用输入法，切换进入insert mode 的时候再使能输入法。
> 
> 目前小狼毫是不管有没有输入焦点都可用的状态，没有外部信号禁用就一直尝试使用输入接口，于是就出问题了。
> 
> 看你们上面的讨论应该要在没有焦点的时候禁用小狼毫才能解的感觉了，但是这个方法和目前小狼毫的逻辑是相悖的，要再观望

没有**输入焦点**依旧在接收, 就会导致
- 中文模式下
- 没有输入焦点, 随便乱按键盘dkgjksdjlkgjal
- 然后点击输入框(有了输入焦点), 随便按个键, a, 
- 上一步的乱码就会出现在输入框dkgjksdjlkgjal**a**

从而导致了, 网页没有接收到快捷键指令, 指令被rime接收了

如视频所示

https://github.com/rime/weasel/assets/24503603/2f898b36-9462-455f-9afa-5aad82f820bb

**Comment by fxliang** [comment]
试过vimnium-c和vimnium,都正常工作，所以问题不一定就只是输入法的问题，等风，说不定哪天两边都改了结果忽然就解决了

**Comment by fxliang** [comment]
试过vimnium-c和vimnium,都正常工作，所以问题不一定就只是输入法的问题，等风，说不定哪天两边都改了结果忽然就解决了

**Comment by LuomingXu** [comment]
vimnium-c和vimnium我都不用

**Comment by mirtlecn** [comment]
> 试过vimnium-c和vimnium,都正常工作，所以问题不一定就只是输入法的问题

Windows 11 + Chromium 系浏览器就能 100% 复现了。

**Comment by fxliang** [comment]
难不成要加个app_option diabled?

**Comment by LuomingXu** [comment]
> 难不成要加个app_option disabled?

不是很懂, 试了一下Potplayer, 中文模式下, 可以快捷键控制, 例如静音(m)

> Windows 11 + Chromium 系浏览器就能 100% 复现了。

看到这个, 试了一下firefox打开YT, 中文模式, 快捷键可以控制
也许要像#946 一样, 对chrome系的浏览器做特别处理? @fxliang

**Comment by mirtlecn** [comment]
麻烦点的 workaround：给 chrome 浏览器加上个 vim_mode，按快捷键之前先 Esc 一下：

```yaml
patch:
  app_options/chrome.exe/vim_mode: true
```

**Comment by LuomingXu** [comment]
> 麻烦点的 workaround：给 chrome 浏览器加上个 vim_mode，按快捷键之前先 Esc 一下：
> 
> ```yaml
> patch:
>   app_options/chrome.exe/vim_mode: true
> ``
试了一下 @mirtlecn 
- 中文模式下, 快捷键显然不行, rime直接接收了"ttttt"按键
- 按了esc, 确实可以使用快捷键
- 但是点击一个输入框(搜索栏, 或地址栏), "ttttt"的接收清除了, 也自动变成了英文模式

确实很烦🤔.....

**Comment by fxliang** [comment]
试过Win10 + Edge (122.0.2365.92), +Firefox 124 打开b站，在中文状态下操作f切换全屏没有问题。所以，这个事情不仅仅是小狼毫相关的事项，可能跟系统版本，浏览器版本，网页的实现都有关系，所以我是不同意做硬编码针对性修改tsf的流程的（我对TSF深层也没有细了解过），更何况这个不是崩溃项，建议还是等风。

**Comment by LuomingXu** [comment]
> 试过Win10 + Edge (122.0.2365.92), +Firefox 124 打开b站，在中文状态下操作f切换全屏没有问题。

我是win11, edge, chrome, firefox, 全都是最新版, firefox没这个问题

>所以我是不同意做硬编码针对性修改tsf的流程的（我对TSF深层也没有细了解过），更何况这个不是崩溃项，建议还是等风。

那我就关闭这个issue吧
