### ISSUE TITLE
更新winget 上小狼豪到0.15

### ISSUE THREAD

**Issue by xarthurx** [rime/weasel#1152]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [ ] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H219045.4170
 - 小狼毫版本:  如 0.14.3

**描述遇到的问题**
winget上应该不能安装 **0.15**

**复现步骤**
重现问题的步骤，如：
- `winget search Rime`
- 查看Rime版本

**预期行为**
winget上应该能安装 0.15

**截图**
![image](https://github.com/rime/weasel/assets/1921878/1c2e59e9-dbf0-45d2-ab99-eb4aa2165a18)

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by mirtlecn** [comment]
更不了，15.0 的版本有静默安装的 bug，那边拒绝更新了。现在修了，等过几天（或许是几周或者几个月）发 16.0 就能推了

**Comment by mirtlecn** [comment]
等下次大版本更新吧，15.0 版本就这样了。另外这个 issue 去 winget 那边提更好（已经有了其实）。

**Comment by mirtlecn** [comment]
https://github.com/microsoft/winget-pkgs/pull/153641

**Comment by fxliang** [comment]
winget 0.16.0.0的pr已merge ,本issue 关闭
