### ISSUE TITLE
可执行文件下载后，被浏览器检测为病毒

### ISSUE THREAD

**Issue by ijliym** [rime/weasel#1154]
最新版可执行文件 weasel-0.15.0.0-installer.exe 下载后被浏览器检测为病毒

![image](https://github.com/rime/weasel/assets/43025881/b08a623a-bfa9-419b-b1ed-f48a36908d13)

![image](https://github.com/rime/weasel/assets/43025881/1208a87d-45ca-489f-8c0b-98951454e493)

**Comment by fxliang** [comment]
老问题了，同样的代码，在本机编译之后，同一个产出的dll，本机的编译的dll在virustotal上检测只有一个误报，ci的产物就有12到13个

暂时：选择信任加白名单；或者不用；或者自行编译。

> 〔小狼毫〕的開發與發佈均在受保護的環境中完成。如果使用過程中，您系統中某種“安全”軟件稱「發現木馬」，那麼此種情形將考驗您的判斷力。

**Comment by fxliang** [comment]
closed by https://github.com/rime/weasel/commit/f4ecee1c1dfc94270159af4017d86ca4bc113ea6
