### ISSUE TITLE
win10 22H2 weasel 15.0/14.0 报错，一直无法载入/使用用户词典，之后完全无法输入中文

### ISSUE THREAD

**Issue by daszzzpg** [rime/weasel#1158]
**描述遇到的问题**
安装后重启前可以输入中文，也能记住用户词典
但是重启后，再输入用户词典里的词就记不住了，报错
如果重新卸载，在选择安装具体输入法的界面就开始报错，打一个勾报错一次

**复现步骤**
第一次安装，重启前可以输入中文字符，可以记忆
重启后也可以输入中文字符，但是无法再记忆
之后卸载后重装，在选择要勾选哪些输入法时就开始报错，切换到输入法时报错，重新部署服务也报错

**预期行为**
应该正常输入中文字符

`Log file created at: 2024/03/25 23:03:55
Running on machine: admin
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
W20240325 23:03:55.727625 20708 registry.cc:16] replacing previously registered component: charset_filter
E20240325 23:08:46.623603 18808 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:08:46.624614  6188 level_db.cc:242] db recovery failed: NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb: ???????????

E20240325 23:08:46.624614  6188 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:08:46.624614  6188 user_db_recovery_task.cc:53] Error creating db 'luna_pinyin'.
E20240325 23:08:50.751634  2852 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:08:50.752633  6188 level_db.cc:242] db recovery failed: NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb: ???????????

E20240325 23:08:50.752633  6188 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:08:50.752633  6188 user_db_recovery_task.cc:53] Error creating db 'luna_pinyin'.
E20240325 23:08:59.245496 13968 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:08:59.245496  5392 level_db.cc:242] db recovery failed: NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb: ???????????

E20240325 23:08:59.246500  5392 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:08:59.246500  5392 user_db_recovery_task.cc:53] Error creating db 'luna_pinyin'.
E20240325 23:09:02.061018  8060 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:09:02.062018  5392 level_db.cc:242] db recovery failed: NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb: ???????????

E20240325 23:09:02.062018  5392 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:09:02.062018  5392 user_db_recovery_task.cc:53] Error creating db 'luna_pinyin'.
E20240325 23:09:12.208078  3300 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:09:12.208078  5392 level_db.cc:242] db recovery failed: NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb: ???????????

E20240325 23:09:12.209079  5392 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:09:12.209079  5392 user_db_recovery_task.cc:53] Error creating db 'luna_pinyin'.
E20240325 23:09:14.549714 21592 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:09:14.549714  5392 level_db.cc:242] db recovery failed: NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb: ???????????

E20240325 23:09:14.550714  5392 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:09:14.550714  5392 user_db_recovery_task.cc:53] Error creating db 'luna_pinyin'.
E20240325 23:09:20.830821 11284 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:09:20.831820  5392 level_db.cc:242] db recovery failed: NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb: ???????????

E20240325 23:09:20.831820  5392 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:09:20.831820  5392 user_db_recovery_task.cc:53] Error creating db 'luna_pinyin'.
E20240325 23:09:30.101508  6004 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:09:30.102507  5392 level_db.cc:242] db recovery failed: NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb: ???????????

E20240325 23:09:30.102507  5392 level_db.cc:277] Error opening db 'luna_pinyin': NotFound: C:\Program Files (x86)\Rime\wuser\luna_pinyin.userdb/LOCK: ???????????

E20240325 23:09:30.102507  5392 user_db_recovery_task.cc:53] Error creating db 'luna_pinyin'.
W20240325 23:09:54.307065  5804 registry.cc:16] replacing previously registered component: charset_filter
E20240325 23:09:54.476066  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:38.211987  3080 deployer.cc:103] a work thread is already running.
E20240325 23:10:38.356426  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:38.537487  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:39.045109 29040 deployer.cc:103] a work thread is already running.
W20240325 23:10:39.088902 29064 deployer.cc:103] a work thread is already running.
W20240325 23:10:39.118032 29068 deployer.cc:103] a work thread is already running.
E20240325 23:10:39.130240  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:39.182106 28968 deployer.cc:103] a work thread is already running.
W20240325 23:10:39.205448 26964 deployer.cc:103] a work thread is already running.
W20240325 23:10:39.230996 10568 deployer.cc:103] a work thread is already running.
E20240325 23:10:39.292079  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:39.293080 29116 deployer.cc:103] a work thread is already running.
W20240325 23:10:39.324501 29120 deployer.cc:103] a work thread is already running.
W20240325 23:10:39.391321  8204 deployer.cc:103] a work thread is already running.
E20240325 23:10:39.456549  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:39.479422  4220 deployer.cc:103] a work thread is already running.
W20240325 23:10:39.612304  6760 deployer.cc:103] a work thread is already running.
E20240325 23:10:39.624562  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:39.764676  5180 deployer.cc:103] a work thread is already running.
E20240325 23:10:39.784965  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:39.825594 17860 deployer.cc:103] a work thread is already running.
W20240325 23:10:39.878207 29232 deployer.cc:103] a work thread is already running.
W20240325 23:10:39.939093 23492 deployer.cc:103] a work thread is already running.
E20240325 23:10:39.948478  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:40.003880 23488 deployer.cc:103] a work thread is already running.
W20240325 23:10:40.084195 29220 deployer.cc:103] a work thread is already running.
W20240325 23:10:40.106420 29128 deployer.cc:103] a work thread is already running.
E20240325 23:10:40.107419  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:40.203752 29268 deployer.cc:103] a work thread is already running.
E20240325 23:10:40.267712  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:40.276721 29280 deployer.cc:103] a work thread is already running.
W20240325 23:10:40.358033 29296 deployer.cc:103] a work thread is already running.
W20240325 23:10:40.421046 29224 deployer.cc:103] a work thread is already running.
E20240325 23:10:40.443086  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:40.502110 29132 deployer.cc:103] a work thread is already running.
W20240325 23:10:40.527110  4152 deployer.cc:103] a work thread is already running.
E20240325 23:10:40.622989  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:40.640086 28752 deployer.cc:103] a work thread is already running.
W20240325 23:10:40.766269 29108 deployer.cc:103] a work thread is already running.
E20240325 23:10:40.798270  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:40.825927 16488 deployer.cc:103] a work thread is already running.
E20240325 23:10:40.970996  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:41.124400  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:41.261323 23524 deployer.cc:103] a work thread is already running.
E20240325 23:10:41.308631  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:41.342383  3112 deployer.cc:103] a work thread is already running.
W20240325 23:10:41.460335 29116 deployer.cc:103] a work thread is already running.
E20240325 23:10:41.489460  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:41.552471 17940 deployer.cc:103] a work thread is already running.
E20240325 23:10:41.659107  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:41.837673  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:42.021462  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:42.190691  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:42.358381  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:42.426725 29728 deployer.cc:103] a work thread is already running.
E20240325 23:10:42.525554  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:42.526530 29736 deployer.cc:103] a work thread is already running.
E20240325 23:10:42.692517  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:42.858819  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:43.027868  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:43.202553  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:43.259997 29744 deployer.cc:103] a work thread is already running.
W20240325 23:10:43.331233 29756 deployer.cc:103] a work thread is already running.
E20240325 23:10:43.363191  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:43.406646 29772 deployer.cc:103] a work thread is already running.
W20240325 23:10:43.444021 29780 deployer.cc:103] a work thread is already running.
E20240325 23:10:43.526182  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:43.693660  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:43.858759  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:44.028134  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:44.030133 29892 deployer.cc:103] a work thread is already running.
W20240325 23:10:44.094581 29908 deployer.cc:103] a work thread is already running.
W20240325 23:10:44.172930 29916 deployer.cc:103] a work thread is already running.
E20240325 23:10:44.196183  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:44.237566 29924 deployer.cc:103] a work thread is already running.
W20240325 23:10:44.317000 29936 deployer.cc:103] a work thread is already running.
E20240325 23:10:44.352313  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:44.389113 29944 deployer.cc:103] a work thread is already running.
E20240325 23:10:44.505920  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:44.565053 29952 deployer.cc:103] a work thread is already running.
E20240325 23:10:44.657630  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:44.809535  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:44.955051  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:45.099272  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:45.245857  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:45.390029  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:45.536357  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:45.685492  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:45.851687  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:46.009738  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:46.153724  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:46.301218  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:46.625243  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:47.578497  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:50.711611 30308 registry.cc:16] replacing previously registered component: charset_filter
E20240325 23:10:50.889269  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:10:51.850677 30392 deployer.cc:103] a work thread is already running.
E20240325 23:10:51.883677  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:10:52.038005  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:11:58.452316 26840 registry.cc:16] replacing previously registered component: charset_filter
E20240325 23:11:58.609876  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:12.042095  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:12.804600  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:13:17.511353 23068 registry.cc:16] replacing previously registered component: charset_filter
E20240325 23:13:17.669399  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:13:24.558939 22532 registry.cc:16] replacing previously registered component: charset_filter
E20240325 23:13:24.723480  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:26.680124  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:33.003890  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:13:36.854208  7308 registry.cc:16] replacing previously registered component: charset_filter
E20240325 23:13:37.011792  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:41.829409  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:43.308602  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:13:44.072891 25464 deployer.cc:103] a work thread is already running.
E20240325 23:13:44.191479  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:13:44.218026 23576 deployer.cc:103] a work thread is already running.
W20240325 23:13:44.322033 25076 deployer.cc:103] a work thread is already running.
E20240325 23:13:44.331034  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:44.472815  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:44.610353  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:45.021147  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:13:45.929059 25152 deployer.cc:103] a work thread is already running.
E20240325 23:13:46.047250  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:46.187248  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:13:55.346499 25040 deployer.cc:103] a work thread is already running.
E20240325 23:13:55.396499  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:13:55.536638  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:14:04.578896  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:14:06.522619  6204 deployer.cc:103] a work thread is already running.
E20240325 23:14:06.544152  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:14:06.685155  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:14:07.894675  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:14:08.253734  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:14:09.835494  8164 deployer.cc:103] a work thread is already running.
E20240325 23:14:09.903223  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:14:10.049224  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:14:30.337927  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:14:35.301631  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:14:37.077730  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:14:37.279788  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:15:39.034348  3148 deployer.cc:103] a work thread is already running.
E20240325 23:15:39.086391  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:15:39.226892  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:15:41.778352 30820 deployer.cc:103] a work thread is already running.
E20240325 23:15:41.826951  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:15:41.971992  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:15:42.202984 24164 deployer.cc:103] a work thread is already running.
E20240325 23:15:42.209985  5392 config_data.cc:47] failed to save config to stream.
W20240325 23:15:42.289736 12752 deployer.cc:103] a work thread is already running.
W20240325 23:15:42.310739 14956 deployer.cc:103] a work thread is already running.
E20240325 23:15:42.351126  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:15:42.491622  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:15:42.630178  5392 config_data.cc:47] failed to save config to stream.
E20240325 23:23:49.834331 26628 config_data.cc:47] failed to save config to stream.
E20240325 23:23:52.603987 26628 config_data.cc:47] failed to save config to stream.
W20240325 23:23:56.729415  3204 deployer.cc:103] a work thread is already running.
E20240325 23:23:56.774308 26628 config_data.cc:47] failed to save config to stream.
E20240325 23:23:56.915616 26628 config_data.cc:47] failed to save config to stream.
W20240325 23:23:57.570120 20340 deployer.cc:103] a work thread is already running.
W20240325 23:23:57.591717 17752 deployer.cc:103] a work thread is already running.
E20240325 23:23:57.630717 26628 config_data.cc:47] failed to save config to stream.
E20240325 23:23:57.772576 26628 config_data.cc:47] failed to save config to stream.
E20240325 23:23:57.911477 26628 config_data.cc:47] failed to save config to stream.
`

日志文件2
`Log file created at: 2024/03/25 23:09:53
Running on machine: admin
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
E20240325 23:09:53.277959 10100 config_data.cc:47] failed to save config to stream.
E20240325 23:09:54.304066 10100 config_data.cc:47] failed to save config to stream.
`

**Comment by Qeynos** [comment]
看起来像文件缺失并且文件夹权限有问题

**Comment by wxyzh** [comment]
你把用户目录放哪了？Program Files (x86) 是需要特权的。

**Comment by fxliang** [comment]
权限限制了，不要设置用户目录在特权目录中
