### ISSUE TITLE
最新的 Nightly Build 和 Action，算法服务无法自动或手动启动

### ISSUE THREAD

**Issue by olapEin** [rime/weasel#1160]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 专业版 23H2 22631.3374
 - 小狼毫版本: d344d50 和 https://github.com/rime/weasel/actions/runs/8431752321

**描述遇到的问题**
自从某 action 后，算法服务无法自动或手动启动。最早的 0.15.0.0 没有问题。

去查了日志大部分都是 INFO，少部分 WARNING 是切换输入配置时提示无文件，没有 ERROR。

我现在不太清楚如何排查问题，需要指导一下

**Comment by fxliang** [comment]
尝试：
1. 只用内置方案看有没有变化
2. 使用WeaselSetup修改用户目录看有没有变化
3. 清空build目录里的内容，用weaseldeployer /deploy看有没有正常部署完成
4. 检查rime.dll是否为自行修改的文件，尝试使用rime/librime的最新nightly构建看有没有变化
5. 试用#1121的构建产物看有没有变化

**Comment by olapEin** [comment]
使用默认配置默认路径全新安装，依然无法启动服务，用的是 f4ecee1。

手动启动服务时，会有是否检查更新的那个弹窗闪烁一下消失。

**Comment by fxliang** [comment]
试试新版Rime备发布的
https://github.com/rime/librime/releases/tag/untagged-01c6247752592d143968

**Comment by yanhuacuo** [comment]
关注，我也是这个 win11 版本遇到的算法服务彻底罢工： Windows 11 专业版 23H2

**Comment by olapEin** [comment]
> 试试新版Rime发布的 https://github.com/rime/librime/releases/tag/1.11.0

我应该怎么判断当前的 weasel 是 64 位还是 32 位。

**Comment by fxliang** [comment]
> > 试试新版Rime发布的 https://github.com/rime/librime/releases/tag/1.11.0
> 
> 我应该怎么判断当前的 weasel 是 64 位还是 32 位。

32位系统安装的是32位，windows 10 ARM64也是装的32位；intel/AMD CPU64位系统都是安装的64位

**Comment by olapEin** [comment]
> > > 试试新版Rime发布的 https://github.com/rime/librime/releases/tag/1.11.0
> > 
> > 
> > 我应该怎么判断当前的 weasel 是 64 位还是 32 位。
> 
> 32位系统安装的是32位，windows 10 ARM64也是装的32位；intel/AMD CPU64位系统都是安装的64位

好的，目前这样是解决了，期待新版本正式解决这个问题。

@yanhuacuo 如果这个方法没什么问题的话我就关闭该 issus 了。

**Comment by olapEin** [comment]
最新的 e664248 没有问题了

**Comment by yanhuacuo** [comment]
确实没问题了
