### ISSUE TITLE
chrome 失焦后还在接受按键.

### ISSUE THREAD

**Issue by konaisland** [rime/weasel#1162]
chrome浏览器在网页中的输入框输入文字之后，再单击网页的其他部分，此时其他的输入法都会失焦不再接受按键。

但这时候小狼毫还在接受按键，导致chrome插件的按键接受出现问题。

其他部分软件似乎也有这种情况。

**Comment by mirtlecn** [comment]
和 #997 重复。似乎是 Windows 11 + Chrome 浏览器独有问题

> 其他部分软件

好奇有哪些呢？

**Comment by Morgal106** [comment]
> 和 #997 重复。似乎是 Windows 11 + Chrome 浏览器独有问题
> 
> > 其他部分软件
> 
> 好奇有哪些呢？

edge，新版qq，vscode等基于Chromium和Electron的软件似乎都存在相同的行为

**Comment by fxliang** [comment]
https://github.com/fxliang/weasel/actions/runs/8851579238
有兴趣可以试试这个 ，大致猜测是不是Windows 11 下的浏览器里失焦的时候是像gvim那样关闭了输入法，当然只是猜测

**Comment by mirtlecn** [comment]
> https://github.com/fxliang/weasel/actions/runs/8851579238
有兴趣可以试试这个 ，大致猜测是不是Windows 11 下的浏览器里失焦的时候是像gvim那样关闭了输入法，当然只是猜测

不行，没效果
