### ISSUE TITLE
[A中] 图标导致游戏跳屏

### ISSUE THREAD

**Issue by DeepTulip** [rime/weasel#1163]
一些游戏是屏幕独占的，比如LOL，而这个图标会破坏独占，让屏幕跳屏到桌面，这可能导致灾难后果，跳屏后再切换回去，至少7-8秒，这时我的人物已经死了。这种情况发生了几次，现在在游戏里我都不敢发言了。

有个类似的
https://github.com/rime/weasel/issues/698

不知道几年过去了，这个图标是否有了关闭的选项了，或者是否能智能识别这种独占屏幕的窗口了

**Comment by fxliang** [comment]
https://github.com/rime/weasel/blob/master/output/data/weasel.yaml#L14

#1031 已经实现这个了

**Comment by lotem** [comment]
感動。就算有種種不便還堅持使用。
