### ISSUE TITLE
关于方案选单，有大大能回复教一下吗

### ISSUE THREAD

**Issue by ifsayyes** [rime/weasel#1165]
我按下CTRL+`之后，设置繁→简

为什么每个窗口，都要设置一次…
重新开机后，又变成繁体字

有什么方法可以固定输出简体字呢？

**Comment by yanhuacuo** [comment]
内置的方案就是基本可打字，要用舒服需要调一些参数，在托盘图标里，有「帮助文档」，修改一下开关的默认值即可。

**Comment by ifsayyes** [comment]
> 内置的方案就是基本可打字，要用舒服需要调一些参数，在托盘图标里，有「帮助文档」，修改一下开关的默认值即可。

谢谢大佬，目前已经解决默认的问题。
