### ISSUE TITLE
speller/delimiter 似乎失效

### ISSUE THREAD

**Issue by ChihSee-Hsie** [rime/weasel#1166]
**上报前请检查**
- [*] 我遇到的问题没有其他人在 issue 里提到过
- [*] 我的小狼毫版本于 rime/weasel 下载
- [*] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - 小狼毫版本: [ fxliang构建的版本29dd14f ]

**描述遇到的问题**
speller/delimiter 似乎失效

**截图**
![Untitled](https://github.com/rime/weasel/assets/91021998/c3867fe3-7ebf-493c-8bb5-88e376505be1)

**Comment by fxliang** [comment]
和#1164 一样的问题了，ci里构建的文件和上游构建的文件不一样了，要再查差异
