### ISSUE TITLE
User directory incorrectly set within Weasel-integrated Rime package installer

### ISSUE THREAD

**Issue by hegotit** [rime/weasel#1170]
**上报前请检查**
- [ ] 关联issue #493 、PR [rime/plum#86](https://github.com/rime/plum/pull/68)
- [ ] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 19045.2728
 - 小狼毫版本: 0.15.0.0 e55ee96

**描述遇到的问题**

Rime package installer 获取用户文件夹路径错误

```
Rime package installer

Working directory: D:\Rime\weasel-0.15.0
Package installer directory: D:\Rime\weasel-0.15.0\
Download cache directory: C:\Users\admin\AppData\Local\Temp
Rime user directory: C:\Users\admin\AppData\Roaming\Rime


Enter package name, URL, user/repo or downloaded ZIP to install:
```
注册表 `\HKEY_CURRENT_USER\SOFTWARE\Rime\Weasel` 下 `RimeUserDir` 对应值为 `D:\RimeData`

**复现步骤**
重现问题的步骤：
1. 点击 '输入法设定'
2. 点击 '获取更多输入方案'

**预期行为**
优先根据Windows注册表获取用户文件夹路径

**共享文件**
此为共享文件夹下 `rime-install-config.bat` ：
```
rem for downloading Git for Windows installer
set git_mirror=taobao

rem Rime configuration manager and downloaded packages
set plum_dir=%APPDATA%\plum
```

**其他补充说明**
`git_mirror=taobao` 已过时，烦请注释或另设镜像

**Comment by mirtlecn** [comment]
因为这里也有一个 rime-config.bat，没跟着更新

git_mirror=taobao 这个没什么用，plum 项目那个自动下载安装 git 的逻辑写的太老了，印象中是不是没写完？不如自己下载。
