### ISSUE TITLE
【讨论】有没有人研发新的整句输入模型

### ISSUE THREAD

**Issue by hallyoung** [rime/weasel#1171]
现在 NLP 取得了长足的进步，比如下面这个榜单

中文句子向量模型
https://huggingface.co/spaces/mteb/leaderboard

有没有人基于此训练新的拼音整句输入模型

或者研发新的整句输入算法

我这真不是手里拿着 LLM 这把锤子，看什么都是钉子

我是真觉得能有所改变

**Comment by LEOYoon-Tsaw** [comment]
LLM根本不需要你輸入了吧，它自己就能替你寫
