### ISSUE TITLE
win11无法开机启动，已经在启动目录增加了快捷方式

### ISSUE THREAD

**Issue by plainee** [rime/weasel#1173]
win11无法开机启动，已经在启动目录增加了快捷方式
开机后还是需要手动启动一下才能用。

**Comment by xieshenluoji** [comment]
我也遇到了同样的问题，而且在任务栏右下角的图标点重新部署没反应，必须到开始菜单里找到重新部署的程序点击才行。

**Comment by dgzd** [comment]
删除原有的 WeaselServer.exe 启动项，然后在注册表中添加新的启动项。
按 `win + r` 输入 `regedit` 打开注册表，在注册表中如下位置
`HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Winlogon` 
创建字符串值，名称 `Shell`，值为 `explorer.exe,"D:\Program Files\Rime\weasel-0.15.0\WeaselServer.exe"`
注：值中的地址需要根据自己的安装位置自行修改。

创建完后，小狼毫立刻就恢复正常了，且开机后也不会再出现无法输入中文的问题。

**Comment by dgzd** [comment]
别下官网版本的，下载此地址提供的小狼毫不会有问题：https://github.com/Techince/weasel/releases

**Comment by plainee** [comment]
> 别下官网版本的，下载此地址提供的小狼毫不会有问题：https://github.com/Techince/weasel/releases

果然可以，为啥官网的不行呢。
而且更新成github的版本，外观都变了，这太突然了

**Comment by fxliang** [comment]
https://github.com/rime/weasel/blob/master/output/install.nsi#L286
https://github.com/rime/weasel/blob/master/output/install.bat#L50
这两个位置可能要改吧大概

Techince的fork为什么没有这个问题？因为他在tsf里处理了自动拉起服务的逻辑
为什么主仓没有加这个逻辑？加了这个问题就不会被发现永远沉在海底，类似的其他服务的问题也会被埋永不见天日

**Comment by mirtlecn** [comment]
请验证一下：

开机后，不做任何操作，等 1 分钟，Weasel 是否可以正常打字。

另外，

> 已经在启动目录增加了快捷方式

这是什么意思呢？你是手动又添加了一遍自启动吗？

**Comment by plainee** [comment]
用这个版本，解决：别下官网版本的，下载此地址提供的小狼毫不会有问题：https://github.com/Techince/weasel/releases
