### ISSUE TITLE
Excel和Windows 11 Explorer的地址栏中输入第一个字母无效

### ISSUE THREAD

**Issue by changzaicl** [rime/weasel#1178]
最新[Nightly Build](https://github.com/rime/weasel/releases/tag/latest)有以下类似问题：
系统：Windows 11 23H2 22631.3374
1. 在Explorer中地址栏中输入第一个字母输入无效，再次输入可以。但是search框中可以第一次直接输入。
2. 在excel中，定位到一个单元格后，第一个字母输入无效。第二个字母才有效。或者必须双击单元格，有光标输入符号后才可以输入。

**Comment by fxliang** [comment]
关联 #1182

**Comment by changzaicl** [comment]
网上搜索后，发现这是word、excel中输入法的普遍问题呀。换作WPS系列，一切都清静了。先换WPS用😄

**Comment by fxliang** [comment]
这个确认是上面描述那个pr关联的，revert了先了
