### ISSUE TITLE
使用 為 而非 爲

### ISSUE THREAD

**Issue by GhostShadow0316** [rime/weasel#1179]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 19045.3086
 - 小狼毫版本: 0.14.6

**描述遇到的问题**
自動選字選的字怪怪的

自動選字是 「爲」但是我通常是用「為」
自動選字是 「着」但是我通常是用「著」
自動選字是 「裏」但是我通常是用「裡」

**复现步骤**
重现问题的步骤，如：
1. 打开任何软件
2. 输入 `wei she me`
3. 顯示 `爲什麼`

**预期行为**
顯示 「為什麼」 而不是 「爲什麼」
有什麼方法可以自訂這種東西？

**Comment by LEOYoon-Tsaw** [comment]
可以用OpenCC轉港台用字

**Comment by GhostShadow0316** [comment]
沒辦法更改詞庫之類的嗎？

**Comment by lotem** [comment]
可以的。
可以自己編寫詞典，注意不要導入預設的「八股文」詞彙表。
https://github.com/rime/home/wiki/RimeWithSchemata#%E7%A2%BC%E8%A1%A8%E8%88%87%E8%A9%9E%E5%85%B8
