### ISSUE TITLE
preedit_type = preview 时用 TSF 触发方案菜单可能导致 WeaselServer 及宿主应用崩溃

### ISSUE THREAD

**Issue by Prcuvu** [rime/weasel#118]
已经过三人验证。

**Comment by mrhso** [comment]
已验证，可以重现。
环境：Windows 7 记事本
![image](https://user-images.githubusercontent.com/13294467/36650976-469cded0-1ae1-11e8-8471-41568edc6778.png)
![image](https://user-images.githubusercontent.com/13294467/36650983-4f0753e8-1ae1-11e8-80ff-08ac1841c287.png)

**Comment by nameoverflow** [comment]
b1d1ec4 之后的问题？
