### ISSUE TITLE
obsidian里excalidraw插件里不能调用数字键

### ISSUE THREAD

**Issue by zhl111** [rime/weasel#1180]
**上报前请检查**
- [x ] 我遇到的问题没有其他人在 issue 里提到过
- [x ] 我的小狼毫版本于 rime/weasel 下载
- [x ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 22H2 22621.1555]
 - 小狼毫版本: [ 0.15.1.005]

**描述遇到的问题**
obsidian里excalidraw插件里不能调用数字键

**复现步骤**
别的输入法都可以，0.15版的也ok

**Comment by mirtlecn** [comment]
你用非官方，应该去下载的地方，那里提 issue。
