### ISSUE TITLE
NeoVIM-QT下无法输入『<』

### ISSUE THREAD

**Issue by lifei** [rime/weasel#1188]
**上报前请检查**
- [✔] 我遇到的问题没有其他人在 issue 里提到过
- [✔] 我的小狼毫版本于 rime/weasel 下载
- [✔] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 23H2 22631.3447
 - 小狼毫版本: 0.15.1.0

**描述遇到的问题**
NeoVIM-QT下无法输入『<』

**复现步骤**
重现问题的步骤，如：
1. 打开 'NeoVIM-QT' 软件
2. 输入 '<'
4. 遇到了 无任何反应 问题

**预期行为**
输入<

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
![demo](https://github.com/rime/weasel/assets/350000/a2e81162-7c3e-4735-ac56-45b48ec3cb64)

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by fxliang** [comment]
并没有发布0.15.1.0，是@Techince的fork？ 你可能在他的仓库下issue或者邮件他可能会更合适，毕竟他改了很多和目前仓库不兼容的代码，在这里讨论会引起误解的。https://github.com/techince/weasel

我试过rime/weasel master分支的构建，没有这个问题的
![rpl](https://github.com/rime/weasel/assets/4023160/e7584696-9f77-45bd-b77c-e7474d100340)

**Comment by Techince** [comment]
下载这个最版本试试。
[x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.008-installer_x64.exe)
最版本我测试的没有问题

**Comment by lifei** [comment]
> 下载这个最版本试试。 [x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.008-installer_x64.exe) 最版本我测试的没有问题

此版本有严重问题，会导致应用程序窗口崩溃。  @Techince

**Comment by lifei** [comment]
我切换到Nightly版本了，Wezterm和NeoVIM的问题均解决了。

**Comment by Techince** [comment]
> > 下载这个最版本试试。 [x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.008-installer_x64.exe) 最版本我测试的没有问题
> 
> @Techince
> 
> 此版本有严重问题，会导致应用程序窗口崩溃。 任何处于焦点的窗口就会崩溃。包括但不限于Explorer.exe、Wezterm、Process Lasso等。

这种情况通常是由于代码中的数据结构和配置文件不一致造成的，卸载重装就好了。
