### ISSUE TITLE
提示框不光标跟随：按 shift 切换中英文时图标位置不正常

### ISSUE THREAD

**Issue by lifenjoiner** [rime/weasel#119]
主要是离光标远，位置又没法预测。类似的还有#95、#100、#110。

关于候选框不光标跟随，补充几个焦点在非可输入组件时特殊情形：
焦点在任务栏输入时候选框在屏幕左上角；
焦点在 Edge 的非可输入组件时候选框在屏幕右下角；
焦点在桌面时候选框先在屏幕右下角闪一下再出现在左上角。

**Comment by nameoverflow** [comment]
要怎么才能做到把焦点放在不是文本框的地方输入……

**Comment by lifenjoiner** [comment]
点一下就好了，比如在桌面上空白的地方点击一下，用键盘操作 mplayer 。

又发现在 win7 上，对于可输入区域，多数能正常跟随光标，候选框比中英文图标情况好。
不正常的情况，先输入一下让候选框出来，再切换就中英文图标可以正常。而不正常的位置是上一次正常的位置。例： firefox 下，此时在输入这条回复，你把焦点放到工具栏搜索框，测试切换中英。

**Comment by nameoverflow** [comment]
提示框跟随已在 https://github.com/nameoverflow/weasel/commit/9e2f9f17c059bf129c2c8b2561471670ea200dd7 修复。
