### ISSUE TITLE
开机后无法输入中文，需要手动重启算法服务方可。

### ISSUE THREAD

**Issue by lifei** [rime/weasel#1190]
**上报前请检查**
- [✔] 我遇到的问题没有其他人在 issue 里提到过
- [✔] 我的小狼毫版本于 rime/weasel 下载
- [✔] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 23H2 22631.3447]
 - 小狼毫版本: [0.15.0-0379963]

**描述遇到的问题**
开机后无法输入中文，需要手动重启算法服务方可。

**复现步骤**
重现问题的步骤，如：
1. 重启电脑
2. 输入中文，不可
3. 重启算法服务
4. 输入中文，可

**预期行为**
重启电脑，可输入中文。

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by fxliang** [comment]
潜在关联 #1173

**Comment by mirtlecn** [comment]
请验证一下：

开机后，不做任何操作，等 1 分钟，Weasel 是否可以正常打字。

**Comment by plainee** [comment]
这个版本解决了了：
别下官网版本的，下载此地址提供的小狼毫不会有问题：https://github.com/Techince/weasel/releases

**Comment by lifei** [comment]
> 这个版本解决了了： 别下官网版本的，下载此地址提供的小狼毫不会有问题：https://github.com/Techince/weasel/releases

这个版本bug也多，诸如NeoVIM下无法输入『<』，导致输入法的宿主进程CPU100%而崩溃等。

**Comment by fxliang** [comment]
> > 这个版本解决了了： 别下官网版本的，下载此地址提供的小狼毫不会有问题：https://github.com/Techince/weasel/releases
> 
> 这个版本bug也多，诸如NeoVIM下无法输入『<』，导致输入法的宿主进程CPU100%而崩溃等。

如方便可以试试 #1203 ，或者直接在hkcu下加多一个启动项，看有没有解决？

**Comment by Qeynos** [comment]
我这出现了安装后没重启可以正常使用，但重启后无法打字，重启算法服务提示找不到weaselserver.exe，重装一遍正常
还有一次出现了安装最后一步出现rime.dll不存在的错误，重装一遍正常

**Comment by Qeynos** [comment]
> 我这出现了安装后没重启可以正常使用，但重启后无法打字，重启算法服务提示找不到weaselserver.exe，重装一遍正常 还有一次出现了安装最后一步出现rime.dll不存在的错误，重装一遍正常

出现第一个问题的是weasel-0.15.0-2941162-installer，第二个问题出现得更早一些，不记得是哪个了，出现nightly都会装一下并且不重启使用

**Comment by fxliang** [comment]
在现有安装的情况下直接安装包里卸载旧安装再安装，似乎有复现过类似你描述的文件丢失的问题，不过这个似乎是Windows的一些重启删除文件处理机制可能相关，目前未了解到相关的解决方案。

或者还是先卸载了注销后再安装来的更稳。

**Comment by mirtlecn** [comment]
安装下

https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns

这是检查自启动有没有注册成功的微软提供的小工具。

看看 weasel 算法服务在不在里面

不确定的话，打开后，截个图看看，

**Comment by QianmuZ** [comment]
> 我这出现了安装后没重启可以正常使用，但重启后无法打字，重启算法服务提示找不到weaselserver.exe，重装一遍正常 还有一次出现了安装最后一步出现rime.dll不存在的错误，重装一遍正常

先前遇到过类似问题，是杀毒软件删除文件了，可以添加下杀软白名单试试

**Comment by fxliang** [comment]
了解下如果有开机服务“没起来”的，是不是普遍将小狼毫设置成了默认输入法，谢谢

**Comment by wordpure** [comment]
> 了解下如果有开机服务“没起来”的，是不是普遍将小狼毫设置成了默认输入法，谢谢

我这边是设置成默认输入法的，并且在系统语言设置里把其他输入法键盘都删掉了。

**Comment by fxliang** [comment]
> > 了解下如果有开机服务“没起来”的，是不是普遍将小狼毫设置成了默认输入法，谢谢
> 
> 我这边是设置成默认输入法的，并且在系统语言设置里把其他输入法键盘都删掉了。

可以试加一个微软拼音，然后让微软拼音作为开机默认之后，看看是不是崩？

**Comment by fxliang** [comment]
https://github.com/fxliang/weasel/actions/runs/9109244341
改了一点东西，减少一点不必要的ui更新，有可能再避免一点问题，可以试试，是不是会好一点？OK的话，考虑合入

**Comment by wordpure** [comment]
> 可以试加一个微软拼音，然后让微软拼音作为开机默认之后，看看是不是崩？

尴尬的是，我用 Total Uninstall 卸载重装后，开机启动已经恢复正常了😂

**Comment by dalamudx** [comment]
我也有这个问题，但不是开机后无法输入中文，就是打游戏用着用着，算法服务可能就掉了，打不出来中文，得手动启动一下算法服务🤣

**Comment by Qeynos** [comment]
我也有类似崩溃的情况，虽然概率不高，最多一天一次，但却是最近几个版本才出现能感知的频率

**Comment by zzm-note** [comment]
下载了最新的[0.16.0]版本，比0.150版本更加频繁了，大部分时间开机都需要重启服务才能输入中文。
![image](https://github.com/rime/weasel/assets/25860330/8066eff1-ede2-4c09-859a-612f2d26c9a8)

**Comment by nantianliao** [comment]
遇到同样问题，开机后算法服务没有启动，需手动启动。

**Comment by fxliang** [comment]
可以试试这个https://github.com/fxliang/weasel/actions/runs/9140885344

加了windows error report, 加了守护
