### ISSUE TITLE
feature request ，关于输入法中英文状态 自动切换 相关内容

### ISSUE THREAD

**Issue by jixiuf** [rime/weasel#12]
我知道 vim  好像可以自动根据当前是否是noral or insert 状态 来切换输入法状态，
但是我用了 Emacs 中的evil-mode 模拟了vim 的行为， 也需要频繁在normal or insert 状态间进行切换， 所以能否让rime支持此种行为。
比如 
1 类似于fcitx 输入法中的fcitx-remote 命令， 
     http://fcitx.github.io/handbook/chapter-remote.html
   可以提供当前 中英文状态 信息， 并且通过外部命令 改变中英文状态
2 我看到当我用shift 切换中英文时， 会在光标附近显示一个字母A或汉字“中” 来显示当前处于哪种状态，  能否 让这两个字符始终跟在光标附近，不要一闪而过。

另一个问题是关于按键绑定的，  
 按键能够提供哪些功能的绑定， 有没有文档 ，能不能做到 既完成某个按键绑定到调用rime某个或多个函数的同时， 又不阻碍此按键原来的功能，
比如 我把escape 绑定到 将输入法切换到英文状态， 同时vim 也能收到 按下Escape键的事件

**Comment by walker-zheng** [comment]
为什么不能默认输入英文，shift切换到中文，还得改配置文件？配置程序应该加上这个选择，而且选择多个输入方式，也只有第一个有效，这是不是太复杂了，限选一个不好么？

**Comment by gttiankai** [comment]
同求这个功能啊!

**Comment by lotem** [comment]
針對 gvim 的處理只在IME接口的前端實現了（吧？）。現在大多數場合用的是TSF接口的前端。
不知道這個辦法是否可行。
這裏討論的問題似乎是與本題不同的輸入法狀態管理機制： https://github.com/rime/weasel/issues/232

**Comment by fxliang** [comment]
with #1113 , it's possible to switch ascii mode by command line.

**Comment by pharaoh2012** [comment]
功能2 可以考虑输入焦点发生变化时候（例如程序切换）在光标周围显示当前状态几秒钟。

**Comment by fxliang** [comment]
> 功能2 可以考虑输入焦点发生变化时候（例如程序切换）在光标周围显示当前状态几秒钟。

```yaml
# weasel.custom.yaml
patch:
    show_notifications_time: 5000   # unit: ms, how long a time the tip will show
```

**Comment by pharaoh2012** [comment]
> > 功能2 可以考虑输入焦点发生变化时候（例如程序切换）在光标周围显示当前状态几秒钟。
> 
> ```yaml
> # weasel.custom.yaml
> patch:
>     show_notifications_time: 5000   # unit: ms, how long a time the tip will show
> ```

你这个是时间长短的设置，我说的核心是窗口变化时候显示一下当前状态的提示。
