### ISSUE TITLE
TSF 模式对 win7 cmd.exe 无效

### ISSUE THREAD

**Issue by lifenjoiner** [rime/weasel#120]
如果全部迁移到 TSF 的话，这个是要考虑的。听 @Prcuvu 的意思像是想尽快发布新版本，各种异常赶快报啊 （：

**Comment by nameoverflow** [comment]
现在手上没有 Windows 7 环境不清楚它是不支持 TSF 还是需要实现特定接口……
不知道 PIME 能否支持 Windows 7 的 cmd ？

**Comment by mrhso** [comment]
![image](https://user-images.githubusercontent.com/13294467/36822544-9309696a-1d33-11e8-9264-c163b86cbccc.png)
不过候选框飘到外面去了。

**Comment by nameoverflow** [comment]
Fixed.
