### ISSUE TITLE
weasel/Wiki里面的示例 ”Windows11风格" 没有显示Windows 11 输入法风格标记

### ISSUE THREAD

**Issue by momotu** [rime/weasel#1205]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 23H2 22631.3447 ]
 - 小狼毫版本: [ 0.15.0.0 ]

**描述遇到的问题**
使用wiki示例里面的windows11风格时，没有正确的显示出mark_text标记。

**复现步骤**
重现问题的步骤，如：
1. weasel.custom.yaml使用wiki中的windows11风格示例，此时hilited_mark_color: 0xc06700，重新部署后没有显示Windows 11 输入法风格标记

**用户文件**
# weasel.custom.yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.15.0.0
  generator: "Weasel::UIStyleSettings"
  modified_time: "Wed Apr 10 00:58:18 2024"
  rime_version: 1.8.5

patch:
  style/+:
    label_format: "%s"
    inline_preedit: true
    font_point: 15
    label_font_point: 15
    comment_font_point: 15
    horizontal: true
    color_scheme: win11light
    color_scheme_dark: win11dark
    mark_text: ""
    layout/+:
      min_width: 10
      margin_x: 16
      margin_y: 8
      border: 2
      spacing: 20
      candidate_spacing: 22
      hilite_spacing: 6
      hilite_padding: 2
      hilite_padding_x: 8
      corner_radius: 10
      round_corner: 8
      shadow_radius: 8
  preset_color_schemes/+:
    win11light:
      name: " Win11浅色 / Win11light"
      text_color: 0x191919
      label_color: 0x191919
      hilited_label_color: 0x191919
      back_color: 0xf9f9f9
      border_color: 0x009e5a00
      hilited_mark_color: 0xc06700
      hilited_candidate_back_color: 0xf0f0f0
      shadow_color: 0x20000000
    win11dark:
      name: "Win11暗色 / Win11Dark"
      text_color: 0xf9f9f9
      label_color: 0xf9f9f9
      back_color: 0x2C2C2C
      hilited_label_color: 0xf9f9f9
      border_color: 0x002C2C2C
      hilited_mark_color: 0xFFC24C
      hilited_candidate_back_color: 0x383838
      shadow_color: 0x20000000

**截图**
![屏幕截图 2024-04-24 105252](https://github.com/rime/weasel/assets/29321516/9234cede-6fd5-48aa-a288-d3515e960d10)

**Comment by plainee** [comment]
应该是：hilited_mark_color，你试试。

**Comment by mirtlecn** [comment]
装上 16 再试 @momotu

**Comment by wzxmer** [comment]
> 直接复制了wiki的代码放`weasel.custom.yaml`，效果大概这样未发现问题呢
> 
> ![image](https://private-user-images.githubusercontent.com/4023160/325615347-ab88e4cf-4782-4114-8480-78373cc10fb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDQ3NzcsIm5iZiI6MTcxNjc0NDQ3NywicGF0aCI6Ii80MDIzMTYwLzMyNTYxNTM0Ny1hYjg4ZTRjZi00NzgyLTQxMTQtODQ4MC03ODM3M2NjMTBmYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMTcyNzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzI2MDY4ZTA4ZTEwYjg4ZGQwNGJlMjllYTEzZWQ1NGMwNTBhZDA2N2UwZTQ5OTlhZTJiNTRlODk3OWY3MmJhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sVW8DLEQ4WOEs6-52fvazVj1cKOQI99U3hGe5gWWpus)
> 
> ```yaml
> # weasel.custom.yaml
> patch:
>   style/+:
>     label_format: "%s"
>     inline_preedit: true
>     font_point: 15
>     label_font_point: 15
>     comment_font_point: 15
>     horizontal: true
>     color_scheme: win11light
>     color_scheme_dark: win11dark
>     layout:
>       min_width: 10
>       margin_x: 16
>       margin_y: 8
>       border: 2
>       spacing: 20
>       candidate_spacing: 22
>       hilite_spacing: 6
>       hilite_padding: 2
>       hilite_padding_x: 8
>       corner_radius: 10
>       round_corner: 8
>       shadow_radius: 8
>   preset_color_schemes/+:
>     win11light:
>       name: " Win11浅色 / Win11light"
>       text_color: 0x191919
>       label_color: 0x191919
>       hilited_label_color: 0x191919
>       back_color: 0xf9f9f9
>       border_color: 0x009e5a00
>       hilited_mark_color: 0xc06700
>       hilited_candidate_back_color: 0xf0f0f0
>       shadow_color: 0x20000000
>     win11dark:
>       name: "Win11暗色 / Win11Dark"
>       text_color: 0xf9f9f9
>       label_color: 0xf9f9f9
>       back_color: 0x2C2C2C
>       hilited_label_color: 0xf9f9f9
>       border_color: 0x002C2C2C
>       hilited_mark_color: 0xFFC24C
>       hilited_candidate_back_color: 0x383838
>       shadow_color: 0x20000000
> ```

可不可以把标签前的标记优化一下，太粗了，不知道跟显示器有没有关系，我扩展屏1080P，还有笔记本的2K显示下，这个标记都粗很多，或者增加一下这个标记的长度粗细控制？

**Comment by wzxmer** [comment]
示例代码，我也尝试了，第一次尝试失败，然后把weasel.custom.yaml文件的代码只留示例代码，就行了，再检查一下吧
