### ISSUE TITLE
系统快捷键的响应/拦截问题

### ISSUE THREAD

**Issue by nantianliao** [rime/weasel#1209]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ 运行 winver.exe 获取，如 Windows 10 22H2 19045.4291]
 - 小狼毫版本: [ 0.15.0.0，48eabf1]

**描述遇到的问题**
候选词出现后，按下Ctrl+Z会响应系统的撤销并出现显示异常。

**复现步骤**
重现问题的步骤，如：
1. 中文输入法下输入编码，此时显示一组候选词；
2. 按下键盘 Ctrl+Z ；
3. 已输入的文本被撤销，输入的拼音消失并且候选列表跟随光标移动。

**预期行为**
输入未完成时，不应响应系统快捷键。（参考输入法为微软拼音）

**用户文件**
无

**截图**
![rime_24](https://github.com/rime/weasel/assets/11886245/5e9dfff0-7b56-4124-8953-673af3fd03f1)

**其他补充说明**
无

**Comment by fxliang** [comment]
应用：我收到Ctrl按下，你处理不处理？
weaseltsf: 我问问看....我不处理，您来吧
应用：你不处理啊，我再看看

应用：我收到z按下，你处理不处理？
weaseltsf: 我问问看...我不处理，您来吧
应用：你不处理啊，我看看，似乎要撤销，盘它，撤销，移动光标了喂
weaseltsf:这样啊，那我也移动一下位置咯，移它，O了
应用：好的

应用：我收到z放开，你处理不处理？
weaseltsf: 我问问看...我不处理，您来吧
应用：这样子，我看看，我好像整过了，过！

应用：我收到Ctrl放开了，你要不要处理？
weaseltsf: 我问问看...我不处理，您来吧
应用：这样子，我看看，我好像整过了，过！

目前看这个逻辑是预期内的

**Comment by nantianliao** [comment]
> 应用：我收到Ctrl按下，你处理不处理？ weaseltsf: 我问问看....我不处理，您来吧 应用：你不处理啊，我再看看
> 
> 应用：我收到z按下，你处理不处理？ weaseltsf: 我问问看...我不处理，您来吧 应用：你不处理啊，我看看，似乎要撤销，盘它，撤销，移动光标了喂 weaseltsf:这样啊，那我也移动一下位置咯，移它，O了 应用：好的
> 
> 应用：我收到z放开，你处理不处理？ weaseltsf: 我问问看...我不处理，您来吧 应用：这样子，我看看，我好像整过了，过！
> 
> 应用：我收到Ctrl放开了，你要不要处理？ weaseltsf: 我问问看...我不处理，您来吧 应用：这样子，我看看，我好像整过了，过！
> 
> 目前看这个逻辑是预期内的

感谢大佬回复！这应该也不算什么问题，就是这个拼音在按下Ctrl+Z后不显示就比较奇怪。

**Comment by fxliang** [comment]
这个是哪个应用？可以再看看

**Comment by nantianliao** [comment]
> 这个是哪个应用？可以再看看


https://github.com/rime/weasel/assets/11886245/549cdfcb-5a52-4b94-9e93-18e60f1ce451

@fxliang VSCode，我还录了一个视频。这跟主题有关吗？

**Comment by fxliang** [comment]
![mspy](https://github.com/rime/weasel/assets/4023160/b5dd9206-691b-47af-8fcc-47ad14c07f9a)

![mspy](https://github.com/rime/weasel/assets/4023160/17d648da-6176-430f-b7fe-5d653b66d64b)

小加两行就可以实现你期待的状态（合成过程中占用全部按键输入），只是这个不确定是不是会有其他副作用，比如一直有用户提的在Windows 11 下Chrome浏览器的输入占用问题的问题很可能会加重

**Comment by nantianliao** [comment]
> ![mspy](https://private-user-images.githubusercontent.com/4023160/326046468-b5dd9206-691b-47af-8fcc-47ad14c07f9a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk3NTMsIm5iZiI6MTcxNDI2OTQ1MywicGF0aCI6Ii80MDIzMTYwLzMyNjA0NjQ2OC1iNWRkOTIwNi02OTFiLTQ3YWYtOGZjYy00N2FkMTRjMDdmOWEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDE1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI3MDE4NjU0MzdmZDA5YTM4ZWNlZWEyYzJiMmE1NGRhMmIzNjY1ZTZhMGY3NzM4NzQ4ZGUyMDA4Y2JmMjJmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P2R9s3PlNfbGDXxIUNHF1f-4LrJ9ULNvB3__7Uh7EU4) [ ![mspy](https://private-user-images.githubusercontent.com/4023160/326046468-b5dd9206-691b-47af-8fcc-47ad14c07f9a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk3NTMsIm5iZiI6MTcxNDI2OTQ1MywicGF0aCI6Ii80MDIzMTYwLzMyNjA0NjQ2OC1iNWRkOTIwNi02OTFiLTQ3YWYtOGZjYy00N2FkMTRjMDdmOWEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDE1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI3MDE4NjU0MzdmZDA5YTM4ZWNlZWEyYzJiMmE1NGRhMmIzNjY1ZTZhMGY3NzM4NzQ4ZGUyMDA4Y2JmMjJmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P2R9s3PlNfbGDXxIUNHF1f-4LrJ9ULNvB3__7Uh7EU4) ](https://private-user-images.githubusercontent.com/4023160/326046468-b5dd9206-691b-47af-8fcc-47ad14c07f9a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk3NTMsIm5iZiI6MTcxNDI2OTQ1MywicGF0aCI6Ii80MDIzMTYwLzMyNjA0NjQ2OC1iNWRkOTIwNi02OTFiLTQ3YWYtOGZjYy00N2FkMTRjMDdmOWEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDE1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI3MDE4NjU0MzdmZDA5YTM4ZWNlZWEyYzJiMmE1NGRhMmIzNjY1ZTZhMGY3NzM4NzQ4ZGUyMDA4Y2JmMjJmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P2R9s3PlNfbGDXxIUNHF1f-4LrJ9ULNvB3__7Uh7EU4) [ ](https://private-user-images.githubusercontent.com/4023160/326046468-b5dd9206-691b-47af-8fcc-47ad14c07f9a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk3NTMsIm5iZiI6MTcxNDI2OTQ1MywicGF0aCI6Ii80MDIzMTYwLzMyNjA0NjQ2OC1iNWRkOTIwNi02OTFiLTQ3YWYtOGZjYy00N2FkMTRjMDdmOWEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDE1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI3MDE4NjU0MzdmZDA5YTM4ZWNlZWEyYzJiMmE1NGRhMmIzNjY1ZTZhMGY3NzM4NzQ4ZGUyMDA4Y2JmMjJmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P2R9s3PlNfbGDXxIUNHF1f-4LrJ9ULNvB3__7Uh7EU4)
> 
> ![weasel_mod](https://private-user-images.githubusercontent.com/4023160/326048308-4a405c0f-edfc-4a54-a297-0f58b3ae7db5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk3NTMsIm5iZiI6MTcxNDI2OTQ1MywicGF0aCI6Ii80MDIzMTYwLzMyNjA0ODMwOC00YTQwNWMwZi1lZGZjLTRhNTQtYTI5Ny0wZjU4YjNhZTdkYjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDE1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQxMjJjYWE2NmZhZmVjMjBiN2E0ZDlmOTg1NWU4NTBmZWE3ZjhhOTBmOGU0Mzk5NmI1YTY5MmU0MTRlNmI2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MFx3_Nmx5i67oryWRl7Fls5zKxh6F3f0Txl6y56EmEc) [ ![weasel_mod](https://private-user-images.githubusercontent.com/4023160/326048308-4a405c0f-edfc-4a54-a297-0f58b3ae7db5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk3NTMsIm5iZiI6MTcxNDI2OTQ1MywicGF0aCI6Ii80MDIzMTYwLzMyNjA0ODMwOC00YTQwNWMwZi1lZGZjLTRhNTQtYTI5Ny0wZjU4YjNhZTdkYjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDE1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQxMjJjYWE2NmZhZmVjMjBiN2E0ZDlmOTg1NWU4NTBmZWE3ZjhhOTBmOGU0Mzk5NmI1YTY5MmU0MTRlNmI2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MFx3_Nmx5i67oryWRl7Fls5zKxh6F3f0Txl6y56EmEc) ](https://private-user-images.githubusercontent.com/4023160/326048308-4a405c0f-edfc-4a54-a297-0f58b3ae7db5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk3NTMsIm5iZiI6MTcxNDI2OTQ1MywicGF0aCI6Ii80MDIzMTYwLzMyNjA0ODMwOC00YTQwNWMwZi1lZGZjLTRhNTQtYTI5Ny0wZjU4YjNhZTdkYjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDE1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQxMjJjYWE2NmZhZmVjMjBiN2E0ZDlmOTg1NWU4NTBmZWE3ZjhhOTBmOGU0Mzk5NmI1YTY5MmU0MTRlNmI2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MFx3_Nmx5i67oryWRl7Fls5zKxh6F3f0Txl6y56EmEc) [ ](https://private-user-images.githubusercontent.com/4023160/326048308-4a405c0f-edfc-4a54-a297-0f58b3ae7db5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk3NTMsIm5iZiI6MTcxNDI2OTQ1MywicGF0aCI6Ii80MDIzMTYwLzMyNjA0ODMwOC00YTQwNWMwZi1lZGZjLTRhNTQtYTI5Ny0wZjU4YjNhZTdkYjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDE1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQxMjJjYWE2NmZhZmVjMjBiN2E0ZDlmOTg1NWU4NTBmZWE3ZjhhOTBmOGU0Mzk5NmI1YTY5MmU0MTRlNmI2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MFx3_Nmx5i67oryWRl7Fls5zKxh6F3f0Txl6y56EmEc)
> 
> 小加两行就可以实现你期待的状态（合成过程中占用全部按键输入如issue提到的ctrl+z不传递给应用），只是这个不确定是不是会有其他副作用，比如一直有用户提的在Windows 11 下Chrome浏览器的输入占用问题的问题很可能会加重
> 
> 如果要试可以试试这个 https://github.com/fxliang/weasel/actions/runs/8851579238

完全ok，要的就是这种效果。由于本人是win10，所以没法确认win11 chrome的情况，望谅解。感谢大佬~
