### ISSUE TITLE
chrome/Edge的地址栏智能搜索功能，在小狼毫输入中文后就失效了

### ISSUE THREAD

**Issue by plainee** [rime/weasel#1211]
**上报前请检查**
下载来源：https://github.com/Techince/weasel
版本008

**操作系统信息**
 - OS 详细版本: Windows 11 22H2
 - 小狼毫版本: [weasel-0.15.1.008-installer_x64.exe](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.008-installer_x64.exe)

**描述遇到的问题**
chrome/Edge的地址栏智能搜索功能，在小狼毫输入中文后就失效了

**复现步骤**
重现问题的步骤，如：
1. 打开chrome
2. 英文状态在地址栏输入abc（可以弹出书签、历史、google搜索）
3. 切换中文输入“中国”（步骤2的功能就失效了，没有弹窗，不能搜索历史、书签、不能联想）

备注：其他输入法不会影响浏览器功能

bug图：
![image](https://github.com/rime/weasel/assets/54027179/e7278baa-a32f-477a-9d26-01bfbdbca3bd)

**Comment by plainee** [comment]
之所以要用https://github.com/Techince/weasel下载来源，是因为官网的地址在win11下不能开机启动。

**Comment by fxliang** [comment]
@techince

**Comment by Techince** [comment]
这个原因不好查。若说是TSF的问题，我的版本可以用快捷键关闭候选框，没有候选框，Chrome的地址栏候选项就不会消失。

https://github.com/rime/weasel/assets/12376669/46569e0e-ebc3-44a1-8919-01aac4c9e4a1

**Comment by fxliang** [comment]
![test](https://github.com/rime/weasel/assets/4023160/3728d35f-b6ff-424d-9cca-2345b8ee7f5d)

**Comment by plainee** [comment]
> 这个原因不好查。若说是TSF的问题，我的版本可以用快捷键关闭候选框，没有候选框，Chrome的地址栏候选项就不会消失。
> 
>  default.mp4

只能看到这个现象，只要按一下Shift切换中文，就会出现这个问题，必须重启浏览器才能恢复。
而且换回官网的weasel版本，就没这个问题。

另外，能否把win11支持开机启动的能力，合入到rime/weasel主干啊，之所以要用这个分支的包是因为主干每次开机要重新启动一下才能起来，添加的启动-快捷方式不起作用。

**Comment by plainee** [comment]
> ![test](https://private-user-images.githubusercontent.com/4023160/326311992-3728d35f-b6ff-424d-9cca-2345b8ee7f5d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODMzNDgsIm5iZiI6MTcxNDk4MzA0OCwicGF0aCI6Ii80MDIzMTYwLzMyNjMxMTk5Mi0zNzI4ZDM1Zi1iNmZmLTQyNGQtOWNjYS0yMzQ1YjhlZTdmNWQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMDgxMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg3NDNiMjI5OGExM2E5ZmViYzk3MWJhZTNkYWY1MzZjZTQ1NWM4ZDJiMDZmYzE5MGQ3N2VmOTE0OTU1NzBhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FQW-3VUdvtGgO_qVKQw3mGgoA1sS5O1cnJosYBmhgDA) [ ![test](https://private-user-images.githubusercontent.com/4023160/326311992-3728d35f-b6ff-424d-9cca-2345b8ee7f5d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODMzNDgsIm5iZiI6MTcxNDk4MzA0OCwicGF0aCI6Ii80MDIzMTYwLzMyNjMxMTk5Mi0zNzI4ZDM1Zi1iNmZmLTQyNGQtOWNjYS0yMzQ1YjhlZTdmNWQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMDgxMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg3NDNiMjI5OGExM2E5ZmViYzk3MWJhZTNkYWY1MzZjZTQ1NWM4ZDJiMDZmYzE5MGQ3N2VmOTE0OTU1NzBhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FQW-3VUdvtGgO_qVKQw3mGgoA1sS5O1cnJosYBmhgDA) ](https://private-user-images.githubusercontent.com/4023160/326311992-3728d35f-b6ff-424d-9cca-2345b8ee7f5d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODMzNDgsIm5iZiI6MTcxNDk4MzA0OCwicGF0aCI6Ii80MDIzMTYwLzMyNjMxMTk5Mi0zNzI4ZDM1Zi1iNmZmLTQyNGQtOWNjYS0yMzQ1YjhlZTdmNWQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMDgxMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg3NDNiMjI5OGExM2E5ZmViYzk3MWJhZTNkYWY1MzZjZTQ1NWM4ZDJiMDZmYzE5MGQ3N2VmOTE0OTU1NzBhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FQW-3VUdvtGgO_qVKQw3mGgoA1sS5O1cnJosYBmhgDA) [ ](https://private-user-images.githubusercontent.com/4023160/326311992-3728d35f-b6ff-424d-9cca-2345b8ee7f5d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODMzNDgsIm5iZiI6MTcxNDk4MzA0OCwicGF0aCI6Ii80MDIzMTYwLzMyNjMxMTk5Mi0zNzI4ZDM1Zi1iNmZmLTQyNGQtOWNjYS0yMzQ1YjhlZTdmNWQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMDgxMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg3NDNiMjI5OGExM2E5ZmViYzk3MWJhZTNkYWY1MzZjZTQ1NWM4ZDJiMDZmYzE5MGQ3N2VmOTE0OTU1NzBhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FQW-3VUdvtGgO_qVKQw3mGgoA1sS5O1cnJosYBmhgDA)

只能看到这个现象，只要按一下Shift切换中文，就会出现这个问题，必须重启浏览器才能恢复。
而且换回官网的weasel版本，就没这个问题。

另外，能否把win11支持开机启动的能力，合入到rime/weasel主干啊，之所以要用这个分支的包是因为主干每次开机要重新启动一下才能起来，添加的启动-快捷方式不起作用。

**Comment by fxliang** [comment]
rime/weasel下的产出，安装包中有在HKLM下添加启动项的动作，会对全部用户有效，见
https://github.com/rime/weasel/blob/master/output/install.nsi#L294

检查启动项的情况，参考这个comment的操作看看情况


>
> 打开任务管理器，点启动页面。看看算法服务是不是启用状态。
> 或者
> 安装下
> https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns
> 这是检查自启动有没有注册成功的微软提供的小工具。
> 看看 weasel 算法服务在不在里面
> 不确定的话，打开后，截个图看看，

_Originally posted by @mirtlecn in https://github.com/rime/weasel/issues/1190#issuecomment-2078829797_


或者可以试试以下的批处理添加 启动项到HKCU下
将以下内容保存到一个bat文件中，放weaselserver.exe所在目录，或者将%CD%改成实际的安装目录，运行，在HKCU下添加一个启动项看问题是否有解决

```bat
@echo off
rem this script will write autorun info in HKCU\Software\Microsoft\Windows\CurrentVersion\Run
rem named WeaselServer
rem keyvalue __path_to_WeaselServer.exe__
rem put it in to path of WeaselServer.exe
rem and run it
set INSTALLDIR=%CD%
REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Run /v WeaselServer /d "%INSTALLDIR%\WeaselServer.exe" /f
pause
````

关于为什么rime/weasel没有添加类似守护之类的功能进来，原因见
https://github.com/rime/weasel/pull/1203#issuecomment-2078727919

**Comment by mirtlecn** [comment]
> 另外，能否把win11支持开机启动的能力，合入到rime/weasel主干啊

我来给你省流，那个分支没做什么 win11 启动支持。每次提交很乱，不可能合并进来。

它是在你每次按键的时候，就尝试启动算法服务。换句话说，做了进程守护。

虽然小狼毫经常崩，但我两三台计算机都没法复现你说的开机不自启，我猜测

- 两个版本混用卸载不干净，
- 未正常安装
- 软件禁止自启

看看 autorun 结果

@Techince
