### ISSUE TITLE
切换不同应用/同一应用其他输入框时，有概率导致默认输入方案不生效

### ISSUE THREAD

**Issue by amakerlife** [rime/weasel#1214]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows11 23H2 22635.3566
 - 小狼毫版本: https://github.com/rime/weasel/commit/c7bd0935150140f0d4e67deba9e5a579e0de2c74

**描述遇到的问题**
升级后，在切换不同应用/同一应用其他输入框时，有概率导致默认（？）（`schema_list` 中第一个）输入方案不生效，触发输入方案选择。

**复现步骤**

**预期行为**
不触发输入方案选择。

**用户文件**

**截图**

**其他补充说明**

**Comment by Ivan-MuTang** [comment]
解决了吗？

**Comment by fxliang** [comment]
这个表现，找了些Windows 11的用户，均未复现故障。

可以试试将rime.dll,用回旧一点的版本看看情况？有可能和上游修另外一个事情有可能有关联，https://github.com/rime/librime/releases/tag/1.11.0

如果是64位系统通常用x64的librime发布就可以的。

**Comment by amakerlife** [comment]
> 解决了吗？

如果调整过`切换输入方案`的快捷键试试改一下或者暂时注释掉？试了一下 0.16 没问题。
