### ISSUE TITLE
在 inline_preedit 开启的情况下，如果input内容在某处无法组词，光标移动到该处就会卡住

### ISSUE THREAD

**Issue by ccyybn** [rime/weasel#1217]
使用默认配置即可复现，请看下方动图，安卓上没问题，不开 inline_preedit 同样没问题

卡住时，继续向右按，光标无响应，然后向左按，也没响应，多次按直到抵消向右按的次数，光标才会响应

![2024-05-06 11-07-24](https://github.com/rime/weasel/assets/7237501/a3f30c5a-6209-46d4-af1b-d633a3588a7f)
![2024-05-06 11-10-34](https://github.com/rime/weasel/assets/7237501/20948d10-2b61-40a4-898d-37c086da869d)

![XRecorder_Edited_07052024_022431 (2)](https://github.com/rime/weasel/assets/7237501/bba16d6e-ecdd-4f3b-b4db-582400bf0995)

**Comment by fxliang** [comment]
可能是#890 未处理完吧

我试了一下这样就可以了，其他潜在的问题未确认

```diff
diff --git a/WeaselIPC/ContextUpdater.cpp b/WeaselIPC/ContextUpdater.cpp
index 72d36f8..8563b88 100644
--- a/WeaselIPC/ContextUpdater.cpp
+++ b/WeaselIPC/ContextUpdater.cpp
@@ -60,10 +60,6 @@ void ContextUpdater::_StoreText(Text& target,
       attr.range.start = _wtoi(vec[0].c_str());
       attr.range.end = _wtoi(vec[1].c_str());
       attr.range.cursor = _wtoi(vec[2].c_str());
-      if (attr.range.cursor < attr.range.start ||
-          attr.range.cursor > attr.range.end) {
-        attr.range.cursor = attr.range.end;
-      }

       target.attributes.push_back(attr);
       return;
```
