### ISSUE TITLE
每晚建構版 weasel-0.15.0-52f8ce8-installer.exe 安裝時異常中文

### ISSUE THREAD

**Issue by dasu88** [rime/weasel#1223]
![2024-05-10_103009](https://github.com/rime/weasel/assets/23251263/2f924722-3a4e-4cf6-9105-00d47bcb5897)

**Comment by fxliang** [comment]
之前的pull request裏的typo

請先卸載舊版本的小狼毫

這樣是對的嗎？

**Comment by dasu88** [comment]
> 之前的pull request裏的typo
> 
> 請先卸載舊版本的小狼毫
> 
> 這樣是對的嗎？

是的，這樣是正確的

**Comment by fxliang** [comment]
改了，等新CI构建产物出来就好
