### ISSUE TITLE
高分屏上候选窗口比例变形

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#1224]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 23H2]
 - 小狼毫版本: [ 492c84fe8d4523e6cd8100c83ba688c885361a12 ]

**描述遇到的问题**
4K 300% 缩放（为了效果更明显）：

Weasel （似乎圆角、空隙都没有被缩放）

![image](https://github.com/rime/weasel/assets/76689045/28a5c413-ddcf-4a3f-9bce-bd57fc77d5f1)
![4](https://github.com/rime/weasel/assets/76689045/79a41d87-a913-4227-93dd-aeae757dc298)

Weasel 1920x1080 125%（期待效果）

![image](https://github.com/rime/weasel/assets/76689045/138ac736-231a-47fb-a948-28d739d2d25d)
![image](https://github.com/rime/weasel/assets/76689045/052cdbb3-a6f7-44e4-8319-18e3e4b896ac)

微软拼音：（高分屏和低分屏保持一致）

![image](https://github.com/rime/weasel/assets/76689045/9d95fc68-6b78-4a5f-bf58-e9dda4e0b09e)

**Comment by mirtlecn** [comment]
另外两个没太能稳定复现（高频复现，但偶尔正常）的问题，不知道有没有外接屏幕和键盘的人遇到：

- 在屏幕间切换，Weasel 更高概率崩溃
- 外接键盘时，weasel 窗口不断闪烁，任务栏失去响应（看不到状态变化）（观察到的并发事件，screentogif 这个软件无法正常工作，提示「设置快捷键以打开鼠标跟随」，尽管并没有打开鼠标跟随），切换到微软拼音正常。

**Comment by fxliang** [comment]
是的，layout里的尺寸参数目前未做dpi响应处理，单位仍然是像素不是DIP,可能下次发版处理。

屏幕之间切换未复现（日常双屏工作），外接键盘问题未复现问题（日常台式机外接键盘）
