### ISSUE TITLE
0.16版本與Windows10安裝繁體界面，會連動安裝簡體語言包

### ISSUE THREAD

**Issue by dasu88** [rime/weasel#1226]
- OS 详细版本:Windows 10
 - 小狼毫版本: 0.16

**描述遇到的问题**
安裝0.16版本，環境選繁體，安裝完成後windows 會連動安裝簡體語言包，0.15以前版本並無此問題

![2024-05-15_112438](https://github.com/rime/weasel/assets/23251263/a3233254-7bcd-44dc-b4d7-49e83300d259)

**Comment by fxliang** [comment]
新版实现在同一个dll里注册多个区域的中文langid profile（仅使能其中一个）,应该是这个引起的。要解决的话要将setup也细化改了才行。之前这个一直没有用户反馈到...下次改再看看怎么改合适。

**Comment by dasu88** [comment]
> 新版实现在同一个dll里注册多个区域的中文langid profile（仅使能其中一个）,应该是这个引起的。要解决的话要将setup也细化改了才行。之前这个一直没有用户反馈到...下次改再看看怎么改合适。

因OS本身为繁体，但也能支持简体显示，所以不会特别安装简体语言包，当前只能安装後先把简体语言包移除，期待早日修正此问题，谢谢。

**Comment by Youxikong** [comment]
简体中文系统也是类似，系统自动装上了繁体中文语言包。

**Comment by dasu88** [comment]
> > 奇怪，我卸载了原来版本的，然后装上 16，没有出现繁体中文语言包欸
> 
> 我是使用繁體中文介面。一樣是 uninstall version 0.15 之後再裝 version 0.16，但沒有出現簡中語言包 😆

我在vmware里的新环境测试了多次都出现同样的状况才来回报，但我另一名同事未缷载旧版本，直接安装，并未出现安装语言包的现象，所以我也不明白其触发的点为何?

**Comment by CharlesMengCA** [comment]
安装时检查是 /s 还是 /t
其它时候用注册表HKEY_CURRENT_USER\SOFTWARE\Rime\Weasel\Hant 0, 简中， 1， 繁中。

**Comment by CharlesMengCA** [comment]
和 #1230 一样的问题， 删除不存在的簡體語言包变成了安装簡體語言包

**Comment by Youxikong** [comment]
太奇怪了。前几天安装了`9848f71`这个版本的nightly，没有安装繁体中文语言包。今天从[Actions](https://github.com/rime/weasel/actions/runs/9153875955)下载的这个版本，安装后反而出现了繁体中文语言包。

**Comment by fxliang** [comment]
额，这个调的是本机的input.dll 我换另外一台电脑也发现不行。。。

**Comment by dasu88** [comment]
> @dasu88 @Youxikong 可以看看 #1252看是不是解了

不好意思，我的专业能力不足，只能从释出的安装档案来试…上述讯息里，我找不到任何可安装的档案来确认此问题是否已解。

**Comment by fxliang** [comment]
https://github.com/rime/weasel/actions/runs/9153875955/artifacts/1518162761

**Comment by dasu88** [comment]
> @dasu88 @Youxikong 可以看看 #1252看是不是解了

目前测试已不会出现安装其他语言包的问题，但这个版本会出现病毒提示
![2024-05-21_083257](https://github.com/rime/weasel/assets/23251263/47be12fb-cce3-494f-816c-803f095f7d5e)

**Comment by fxliang** [comment]
😂就是检查了下注册表里面的`Hant`设定来判断执行两行代码……这都可以产生误报嘛……

**Comment by dasu88** [comment]
> 😂就是检查了下注册表里面的`Hant`设定来判断执行两行代码……这都可以产生误报嘛……

可有解?

**Comment by CharlesMengCA** [comment]
快速测了一下 #1230 的问题已经没有了。

感觉其它用GetUserDefaultLCID()的地方，也应该用这个注册表值来确定简繁体。

**Comment by fxliang** [comment]
> 快速测了一下 #1230 的问题已经没有了。
> 
> 感觉其它用GetUserDefaultLCID()的地方，也应该用这个注册表值来确定简繁体。

用户有可能会切换界面语言，有可能会同时安装不同langid的profile，纯注册表似乎无解吧
