### ISSUE TITLE
关于新位置首次输入时自动弹输入法选择的问题

### ISSUE THREAD

**Issue by Ivan-MuTang** [rime/weasel#1227]
您好，谢谢您提供这么好用的输入工具
以下是更新到  16后遇到的关题，

每次打开新窗口，或窗口间来间切换后首次输入时，总会自动弹出输入法选择

弹出后按ESC或重新选择输入法后，输入都是正常，再次从其它窗口切回时，首次输入又会弹出

请问是否在配置项里可以将其关闭？

**Comment by fxliang** [comment]
相同问题#1214，请移步跟踪更新，谢谢
