### ISSUE TITLE
与自定义shell的不兼容，在装载服务的时候

### ISSUE THREAD

**Issue by RaidOpe** [rime/weasel#1242]
**上报前请检查**

- [  ] 我遇到的问题没有其他人在 issue 里提到过
- [  ] 我的小狼毫版本于 rime/weasel 下载
- [  ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: 版本23H2(OS内部版本22631.3447) 
 - 小狼毫版本:  0.16 

**描述遇到的问题**
资源管理器崩溃重启

**复现步骤**
重现问题的步骤，如：
![crash](https://github.com/rime/weasel/assets/95146386/2353e01b-c30e-45fb-979b-9664a6bf7c23)

**预期行为**
与微软输入法一样，不冲突

**用户文件**
应该不需要

**截图**

**其他补充说明**
[开源项目的Shell](https://github.com/moudey/Shell)

**Comment by fxliang** [comment]
看看#1246的产出是不是解决了

**Comment by RaidOpe** [comment]
貌似在第一次重新装载时，能够兼容，然后崩溃

![crash2](https://github.com/rime/weasel/assets/95146386/dfd0c28d-8cd1-49da-845b-de16e371f4b3)

**Comment by fxliang** [comment]
这个是系统的任务栏吗？

**Comment by RaidOpe** [comment]
[开源项目的Shell](https://github.com/moudey/Shell) 如果你说的是shell，右键呼出。或许可以像其他软件一样，避开而调用shell 
![image](https://github.com/rime/weasel/assets/95146386/94e2de1f-382d-4cdb-8b33-188080191722)

**Comment by fxliang** [comment]
这个shell，我试了，菜单都不一定可以正常响应，潜在关联shell里的问题太多。暂不考虑针对性处理。暂关闭此issue
