### ISSUE TITLE
Win10SDK下无法编译通过，VersionHelpers导致

### ISSUE THREAD

**Issue by TivJsou** [rime/weasel#125]
项目中的
```
weasel\include\VersionHelpers.hpp
```
与win10SDK下的
```
Windows Kits\10\Include\10.0.16299.0\um\VersionHelpers.h
```
这两个文件中包含有相同的方法定义
![image](https://user-images.githubusercontent.com/10483290/36879563-5d99721c-1dff-11e8-9e74-24a057a09b83.png)

---
weasel能在win10sdk-x64-vc2017这种情况下编译运行吗？
librime我是改改配置文件，编出x64版了。不过用rime_api_console.exe时会crash.

weasel在解决上面说的VersionHelpsers问题后，还有一些“无法解析的外部符号”的错。

---
对cmake不熟悉，调的我头晕。
我用的boost1.66.0与cmake3.10.2. cmake在查找boost库时会报找不到的问题，这个不是librime的问题，
很多用了cmake和boost的项目都报这类issue。

**Comment by nameoverflow** [comment]
现在是用 XP toolset 构建的

**Comment by Prcuvu** [comment]
为了保持与 Windows XP 的兼容，我刻意设置成使用 Windows XP 平台工具集，另外设置了 Windows 8.1 SDK 中 VersionHelpers.h 里的同名函数，因此不可以使用 Windows 10 SDK 编译。
