### ISSUE TITLE
汉字拼音模式对浏览器视频操作无效

### ISSUE THREAD

**Issue by Z4R1TSU** [rime/weasel#1251]
**上报前请检查**
- [*] 我遇到的问题没有其他人在 issue 里提到过
- [*] 我的小狼毫版本于 rime/weasel 下载
- [*] 我在使用小狼毫的最新发布版本
- 
**操作系统信息**
 - OS 详细版本: Windows 11 23H2
 - 小狼毫版本:  0.16.0.0 雾凇

**描述遇到的问题**
浏览器播放视频必须得英文模式才能对视频进行操作，即在小狼毫中文情况下，对视频的比如全屏f键和b站的弹幕d键或是任何键都无效

**复现步骤**
重现问题的步骤，如：
1. 打开浏览器chrome或是ms edge
2. 保证在中文模式下
3. 打开任意视频
4. 尝试对视频进行字母键位的操作
5. 问题出现：无法对视频进行操作

**预期行为**
在中文模式下，我按f视频应该切换全屏等等。

**Comment by LEOYoon-Tsaw** [comment]
中文模式下按f竟然輸入了中文，可惡！

**Comment by lotem** [comment]
讓瀏覽器實現。在視頻裏面不要調用輸入法。
輸入法不知道是視頻還是別的。
