### ISSUE TITLE
使用问题：请问如何修改光标的形状

### ISSUE THREAD

**Issue by freedomspiritJohn** [rime/weasel#1258]
目前光标是^形状，我想修改为|形状，但是不知道应该如何修改。 
![image](https://github.com/rime/weasel/assets/129288685/aa6be61d-cad2-4c78-98d2-77cb7795a959)
![image](https://github.com/rime/weasel/assets/129288685/bf793814-a507-44f3-9229-347563b447ee)
还有如何关闭表情包候选项只开启文字的候选项。

**Comment by fxliang** [comment]
不支持这样修改的，这个是librime内部固定的字符。

**Comment by freedomspiritJohn** [comment]
> 不支持这样修改的，这个是librime内部固定的字符。

那鼠标的形状能修改吗，请问怎么修改啊，没找到案例。

**Comment by fxliang** [comment]
> > 不支持这样修改的，这个是librime内部固定的字符。
> 
> 那鼠标的形状能修改吗，请问怎么修改啊，没找到案例。

鼠标形状是你系统的设定吧，小狼毫没有处理鼠标形状相关的处理。

**Comment by freedomspiritJohn** [comment]
> > > 不支持这样修改的，这个是librime内部固定的字符。
> > 
> > 
> > 那鼠标的形状能修改吗，请问怎么修改啊，没找到案例。
> 
> 鼠标形状是你系统的设定吧，小狼毫没有处理鼠标形状相关的处理。

系统是win11，但是我也没有改过鼠标形状，都是默认的，不应该是竖线吗
![image](https://github.com/rime/weasel/assets/129288685/fca8e2d5-fe75-4140-a4f1-dfdce5645f85)

**Comment by fxliang** [comment]
你图中也没有鼠标形状吧？？？

应用中的光标形状是应用自行决定的

**Comment by freedomspiritJohn** [comment]
> 你图中也没有鼠标形状吧？？？
> 
> 应用中的光标形状是应用自行决定的

说错了，不是鼠标形状，是光标形状。就是我想把小狼毫的^改成|。能修改吗
![image](https://github.com/rime/weasel/assets/129288685/b25449f8-17f6-40ee-bab6-7dfca74cc01d) 
![image](https://github.com/rime/weasel/assets/129288685/fa6c814f-78ba-469f-ba27-0a486780989c)

**Comment by fxliang** [comment]
![image](https://github.com/rime/weasel/assets/4023160/6ea7eb66-c2f9-4440-986b-8ee13a141400)

>  不支持这样修改的，这个是librime内部固定的字符。

**Comment by freedomspiritJohn** [comment]
> ![image](https://private-user-images.githubusercontent.com/4023160/333098743-6ea7eb66-c2f9-4440-986b-8ee13a141400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTIzMjksIm5iZiI6MTcxNjQ1MjAyOSwicGF0aCI6Ii80MDIzMTYwLzMzMzA5ODc0My02ZWE3ZWI2Ni1jMmY5LTQ0NDAtOTg2Yi04ZWUxM2ExNDE0MDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMDgxMzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk5OTk1MWM4MzBlN2EzOWYwMjI0MGI3OTI5MTExZTJlOTdhZDRlMjk2MDkzZjg4Yjk0NTRlYjFiYmM3Y2NlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VTP3YReaqYxmEMxbylZD_iApOcyelQmj6V9SJ6jPFv4)
> 
> > 不支持这样修改的，这个是librime内部固定的字符。

那只能希望后续可以修改吧
