### ISSUE TITLE
输入进程崩溃

### ISSUE THREAD

**Issue by thep0y** [rime/weasel#1261]
**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [ ] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 23H2 22631.3593
 - 小狼毫版本: 0.16.0

**描述遇到的问题**
输入文字时会输入进程突然崩溃，无法再输入中文，任务管理器中无法找相小狼毫进程，只有重启进程才能恢复正常。

**复现步骤**
重现问题的步骤，如：
1. 打开 'Xmind' 软件
2. 创建若干个节点，输入若干个文字
3. 输入中途切换到 chrome 若干次
4. 输入法进程退出，无法输入中文

**预期行为**
不退出或不崩溃。

**用户文件**
[rime.zip](https://github.com/rime/weasel/files/15430674/rime.zip)

**补充**
日志文件的最后几行：
```
I20240524 16:16:42.780799  3404 engine.cc:133] updated option: ascii_mode
I20240524 16:16:57.475858  3404 engine.cc:133] updated option: ascii_mode
I20240524 16:17:09.624717  3404 engine.cc:133] updated option: ascii_mode
I20240524 16:22:48.061807  3404 engine.cc:133] updated option: ascii_mode
I20240524 16:27:37.444553 35456 engine.cc:96] engine disposed.
```
未发现 #1259  所说的WeaselServer.exe的dmp文件。

**Comment by fxliang** [comment]
0.16.0还没有#1259 描述的特性

**Comment by thep0y** [comment]
安装 nightly 版后似乎未再发生进程崩溃
