### ISSUE TITLE
新手提问，关于候选框内的提示码

### ISSUE THREAD

**Issue by hubgogo** [rime/weasel#1263]
版本 0.160 
 方案 86五笔拼音

所有都是官方的设置

有一个问题 ：
怎么取消显示候选框内的提示码
如下图：（红框内）
![2024-05-25_173626](https://github.com/rime/weasel/assets/91697479/fda45f3f-6153-466b-b939-a9372f7beece)

谢谢！

**Comment by LEOYoon-Tsaw** [comment]
大概是spelling_hints: 0

**Comment by hubgogo** [comment]
> 大概是spelling_hints: 0

哥们，请问这个参数是直接加在 wubi_pinyin.custom.yaml 里面吗？（试过了，无效）

                                                    wubi_pinyin.schema.yaml 里面找不到这个参数

不知道怎么运用呢。

**Comment by yanhuacuo** [comment]
加上这么一句：

wubi_pinyin.custom.yaml 的 path 字段下：

空格与别的对齐

```
  "translator/comment_format": ["xform/[~a-z]*//",]
```

**Comment by hubgogo** [comment]
> 加上这么一句：
> 
> wubi_pinyin.custom.yaml 的 path 字段下：
> 
> 空格与别的对齐
> 
> ```
>   "translator/comment_format": ["xform/[~a-z]*//",]
> ```

多谢解答，不过这个命令我加上了，重新部署后没有效果。不知我格式错没有。如下图：

![image](https://github.com/rime/weasel/assets/91697479/1d7ed78e-fb56-4b4a-8b49-e0c7c0ee22ce)



![image](https://github.com/rime/weasel/assets/91697479/47338d9f-3621-4c5a-883d-d96f2e28b70d)

**Comment by yanhuacuo** [comment]
【中州韵助手：消除逐键提示編码】 https://www.bilibili.com/video/BV1Lx4y1p7NZ/?share_source=copy_web&vd_source=37920c8c7678220e3b54da59922b8164

**Comment by fxliang** [comment]
```yaml
"translator/comment_format/+":
  - "xform/^.*$//"
```

**Comment by hubgogo** [comment]
> ```yaml
> "translator/comment_format/+":
>   - "xform/^.*$//"
> ```
> 
> 如果要全局都关comment ，在小狼毫下还可以patch 成style/comment_font_point: 0

多谢完美解决问题，style/comment_font_point: 0 有效。赞
如图：
![2024-05-26_143335](https://github.com/rime/weasel/assets/91697479/1323aca8-0875-41bf-b4cc-ea01be4babac)

![2024-05-26_143611](https://github.com/rime/weasel/assets/91697479/a22c47dc-6774-4b85-9ac8-9c52572d487c)

**Comment by yanhuacuo** [comment]
> > ```yaml
> > "translator/comment_format/+":
> >   - "xform/^.*$//"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果要全局都关comment ，在小狼毫下还可以patch 成style/comment_font_point: 0
> 
> 多谢完美解决问题，style/comment_font_point: 0 有效。赞 如图： ![2024-05-26_143335](https://private-user-images.githubusercontent.com/91697479/333852204-1323aca8-0875-41bf-b4cc-ea01be4babac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDYxMTQsIm5iZiI6MTcxNjcwNTgxNCwicGF0aCI6Ii85MTY5NzQ3OS8zMzM4NTIyMDQtMTMyM2FjYTgtMDg3NS00MWJmLWI0Y2MtZWEwMWJlNGJhYmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA2NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOTg2MWFiZTY1Yzc5M2NiM2VkN2E2Y2FiMWZhNWFmMDE3NTIzZjk5ZmJjZDY3MjIyY2Y5OTY1NGJjZWY3ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hpOABmksz8NB2AhfoB0QKnipxMYRQUfF-2R7YHiluI0)
> 
> ![2024-05-26_143611](https://private-user-images.githubusercontent.com/91697479/333852209-a22c47dc-6774-4b85-9ac8-9c52572d487c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDYxMTQsIm5iZiI6MTcxNjcwNTgxNCwicGF0aCI6Ii85MTY5NzQ3OS8zMzM4NTIyMDktYTIyYzQ3ZGMtNjc3NC00Yjg1LTlhYzgtOWM1MjU3MmQ0ODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA2NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYzRhOTA4MTBiZmYxM2ZmZGJjY2M5ODUyZjVhNDE3MTc3ZmJjZTg4MTFkMGU5N2E4MjcxYzdiODZlZTkwOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0qa2--F_69Xk1dpQUk7Q2JxQY8FyecL72BMh1-6_Ils)

其实都可以，只是你的配置中存在着冲突或其它未知错误。

**Comment by hubgogo** [comment]
> > > ```yaml
> > > "translator/comment_format/+":
> > >   - "xform/^.*$//"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 如果要全局都关comment ，在小狼毫下还可以patch 成style/comment_font_point: 0
> > 
> > 
> > 多谢完美解决问题，style/comment_font_point: 0 有效。赞 如图： ![2024-05-26_143335](https://private-user-images.githubusercontent.com/91697479/333852204-1323aca8-0875-41bf-b4cc-ea01be4babac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDYxMTQsIm5iZiI6MTcxNjcwNTgxNCwicGF0aCI6Ii85MTY5NzQ3OS8zMzM4NTIyMDQtMTMyM2FjYTgtMDg3NS00MWJmLWI0Y2MtZWEwMWJlNGJhYmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA2NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOTg2MWFiZTY1Yzc5M2NiM2VkN2E2Y2FiMWZhNWFmMDE3NTIzZjk5ZmJjZDY3MjIyY2Y5OTY1NGJjZWY3ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hpOABmksz8NB2AhfoB0QKnipxMYRQUfF-2R7YHiluI0)
> > ![2024-05-26_143611](https://private-user-images.githubusercontent.com/91697479/333852209-a22c47dc-6774-4b85-9ac8-9c52572d487c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDYxMTQsIm5iZiI6MTcxNjcwNTgxNCwicGF0aCI6Ii85MTY5NzQ3OS8zMzM4NTIyMDktYTIyYzQ3ZGMtNjc3NC00Yjg1LTlhYzgtOWM1MjU3MmQ0ODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA2NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYzRhOTA4MTBiZmYxM2ZmZGJjY2M5ODUyZjVhNDE3MTc3ZmJjZTg4MTFkMGU5N2E4MjcxYzdiODZlZTkwOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0qa2--F_69Xk1dpQUk7Q2JxQY8FyecL72BMh1-6_Ils)
> 
> 其实都可以，只是你的配置中存在着冲突或其它未知错误。



> > > ```yaml
> > > "translator/comment_format/+":
> > >   - "xform/^.*$//"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 如果要全局都关comment ，在小狼毫下还可以patch 成style/comment_font_point: 0
> > 
> > 
> > 多谢完美解决问题，style/comment_font_point: 0 有效。赞 如图： ![2024-05-26_143335](https://private-user-images.githubusercontent.com/91697479/333852204-1323aca8-0875-41bf-b4cc-ea01be4babac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDYxMTQsIm5iZiI6MTcxNjcwNTgxNCwicGF0aCI6Ii85MTY5NzQ3OS8zMzM4NTIyMDQtMTMyM2FjYTgtMDg3NS00MWJmLWI0Y2MtZWEwMWJlNGJhYmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA2NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOTg2MWFiZTY1Yzc5M2NiM2VkN2E2Y2FiMWZhNWFmMDE3NTIzZjk5ZmJjZDY3MjIyY2Y5OTY1NGJjZWY3ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hpOABmksz8NB2AhfoB0QKnipxMYRQUfF-2R7YHiluI0)
> > ![2024-05-26_143611](https://private-user-images.githubusercontent.com/91697479/333852209-a22c47dc-6774-4b85-9ac8-9c52572d487c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDYxMTQsIm5iZiI6MTcxNjcwNTgxNCwicGF0aCI6Ii85MTY5NzQ3OS8zMzM4NTIyMDktYTIyYzQ3ZGMtNjc3NC00Yjg1LTlhYzgtOWM1MjU3MmQ0ODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA2NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYzRhOTA4MTBiZmYxM2ZmZGJjY2M5ODUyZjVhNDE3MTc3ZmJjZTg4MTFkMGU5N2E4MjcxYzdiODZlZTkwOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0qa2--F_69Xk1dpQUk7Q2JxQY8FyecL72BMh1-6_Ils)
> 
> 其实都可以，只是你的配置中存在着冲突或其它未知错误。

噢，我只是用的 [润笔](https://pdog18.github.io/rime-soak/) 小助手 改了一下横排和内嵌，加上了emoji，其它均官方默认。

还是多谢你提供的建议。你的工具我切换到“上屏行为”就抱错。 界面上还有一点点错位，指针需要向上方偏移一些才能选中。

谢谢 😆️
