### ISSUE TITLE
安装最新nightly后preedit_format转换失效

### ISSUE THREAD

**Issue by hegotit** [rime/weasel#1268]
**上报前请检查**
- [✅] 我遇到的问题没有其他人在 issue 里提到过
- [✅] 我的小狼毫版本于 rime/weasel 下载
- [✅] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 23H2 22631.3593
 - 小狼毫版本: 6a68382

**描述遇到的问题**
preedit_format失效

**复现步骤**
重现问题的步骤，如：
1. 安装6a68382
2. 输入键位 `VIMA`
3. 输入框双拼输入未转为全拼

**预期行为**
双拼输入经过preedit_format转换为全拼

**用户文件**
文件太大了传不上来，使用的是雾凇拼音 [rime-ice](https://github.com/iDvel/rime-ice)

**截图**

异常：
![image](https://github.com/rime/weasel/assets/153287866/d8c1d0db-13d2-4771-b5d3-cc88b816705c)

回退至 b1aebe8 恢复正常：
![image](https://github.com/rime/weasel/assets/153287866/cf24aec1-3fa7-45a2-b2ab-82b46d6bde1d)

**Comment by hegotit** [comment]
> 7z里可以见两个的，一个32位的一个64位的

![image](https://github.com/rime/weasel/assets/153287866/b973f624-4ba1-4ffd-99c7-bed43b423c0b)

替换后没有修复：

![image](https://github.com/rime/weasel/assets/153287866/4409f5bc-dba8-440d-aa16-9e1699d58cfc)

**Comment by changzaicl** [comment]
[5ff8dda](https://github.com/rime/weasel/commit/5ff8ddaabdb51825107bf1fd16a5a39ae831e1dd)这个版本正常。
[6a68382](https://github.com/rime/weasel/commit/6a6838267fabed867df028877a9b046ef9528353)这个不行，已多次删除重装验证。

**Comment by fxliang** [comment]
想起大概是librime用vs2019构建是有这个问题，用vs2022构建就正常。

小狼毫了为了解决误报问题用了vs2019来做ci，于是在vs2019里构建的librime就不能用的状态
