### ISSUE TITLE
输入焦点切出时不会丢弃当前 composition

### ISSUE THREAD

**Issue by Prcuvu** [rime/weasel#127]
来自 QQ 群的用户反馈：

![image](https://user-images.githubusercontent.com/7923857/37154212-31186aac-231a-11e8-9b04-08e78243b818.png)

![image](https://user-images.githubusercontent.com/7923857/37154149-0e96afd4-231a-11e8-82f6-4485b8d9e9ac.png)

**Comment by nameoverflow** [comment]
这是个 BUG 啊
