### ISSUE TITLE
最新版的 CHANGELOG 某个配置选项书写错误

### ISSUE THREAD

**Issue by Parsifa1** [rime/weasel#1272]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**描述遇到的问题**
[最新版的 CHANGELOG](https://github.com/rime/weasel/blob/master/CHANGELOG.md) 关于 `ascii_tip_follow_cursor` 写成了 `ascii_tips_follow_cursor`, 会导致配置无法生效

**Comment by fxliang** [comment]
fixed, thx
