### ISSUE TITLE
提个小白求助，字体的"|"如何设置为粗体

### ISSUE THREAD

**Issue by QianmuZ** [rime/weasel#1274]
**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [X] 我的小狼毫版本于 rime/weasel 下载
- [X] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 23H2
 - 小狼毫版本: nightly

**描述遇到的问题**
设置fontface，如何将marktext的"|"设置为粗体？
当前设置：style/font_face: "Sarasa UI SC:7c:7c, Segoe UI Emoji:30:39, Segoe UI Emoji:23:23, Segoe UI Emoji:2a:2a, Segoe UI Emoji:fe0f:fe0f, Segoe UI Emoji:20e3:20e3, Sarasa UI SC Regular, Segoe UI Emoji, Noto Color Emoji SVG"

想要设置为粗体：style/font_face: "Sarasa UI SC:7c:7c **:Bold** , Segoe UI Emoji:30:39, Segoe UI Emoji:23:23, Segoe UI Emoji:2a:2a, Segoe UI Emoji:fe0f:fe0f, Segoe UI Emoji:20e3:20e3, Sarasa UI SC Regular, Segoe UI Emoji, Noto Color Emoji SVG"

添加了Bold后，整个字体都变成粗体了

**截图**
![image](https://github.com/rime/weasel/assets/28744797/219048bb-28c1-4cd9-b96e-2f4e3208c217)

**Comment by fxliang** [comment]
当前基础上，将mark_text设置为"",然后就是高仿Win11风格的状态了

![image](https://github.com/rime/weasel/assets/4023160/fc8168c6-1d1e-48d0-a00f-87a8a8ffb78d)

**Comment by QianmuZ** [comment]
> 当前基础上，将mark_text设置为"",然后就是高仿Win11风格的状态了
> 
> ![image](https://private-user-images.githubusercontent.com/4023160/334733528-fc8168c6-1d1e-48d0-a00f-87a8a8ffb78d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzM4NDAsIm5iZiI6MTcxNjk3MzU0MCwicGF0aCI6Ii80MDIzMTYwLzMzNDczMzUyOC1mYzgxNjhjNi0xZDFlLTQ4ZDAtYTAwZi04N2E4YThmZmI3OGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDkwNTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTgyNjE0ODEwNGE3NmE4NDMwYTQzNjg5NmNmMTJlZTEwMDljOTVlNzdiZGZjMDJjNzQ4OTNhYzI0NzJjZjQ0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.54q9SeNNEKMSZcVrWzdU_QLUDQER0kFKGlPaR0SyhO4)

![image](https://github.com/rime/weasel/assets/28744797/4df663a2-cacc-423b-b450-5179e8012c47)

感觉默认的这个显示有点奇怪

**Comment by wzxmer** [comment]
请问你的 |  是怎么做到跟候选居中相对对齐的，我的总会偏下一点
![1717003129283](https://github.com/rime/weasel/assets/46368648/4ab3a5e4-ba84-4816-83be-e876806bd9af)

**Comment by QianmuZ** [comment]
> 请问你的 | 是怎么做到跟候选居中相对对齐的，我的总会偏下一点 ![1717003129283](https://private-user-images.githubusercontent.com/46368648/334900691-4ab3a5e4-ba84-4816-83be-e876806bd9af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzIzMjAsIm5iZiI6MTcxNzAzMjAyMCwicGF0aCI6Ii80NjM2ODY0OC8zMzQ5MDA2OTEtNGFiM2E1ZTQtYmE4NC00ODE2LTgzYmUtZTg3NjgwNmJkOWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAxMjAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZDRhMTEyYzdiMmFhOWQwZGRmOWQ0MDhkMTE5MTI1OWY5Zjg3ZjZhZTY5YjRjOTY0NjI1MmVhZjkyODZmZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YIXd3eKhen6ys5VOtyY1Mq3qo8uXIPnw0hU6SAZDBKs)

我偏下的情况先前遇到过，是因为字体的原因，你更换字体试一下。
