### ISSUE TITLE
想请问这个WARNING.log的造成原因与实际影响

### ISSUE THREAD

**Issue by dasu88** [rime/weasel#1275]
**上报前请检查**
- [V] 我遇到的问题没有其他人在 issue 里提到过
- [V] 我的小狼毫版本于 rime/weasel 下载
- [V ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2
 - 小狼毫版本: weasel-0.16.0-1d44e29

**描述遇到的问题**
我发现日志文件夹内，经常会出现WARRNING.log，其內容如下：
Log file created at: 2024/05/29 16:46:38
Running on machine: TY-I041
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
W20240529 16:46:38.435207 15704 config_compiler.cc:527] circular dependencies detected in liur.schema:
W20240529 16:46:38.436562 15704 config_compiler.cc:367] accessing blocking node with unresolved dependencies: liur.schema:
W20240529 16:46:38.436674 15704 config_compiler.cc:527] circular dependencies detected in liur.schema:
W20240529 16:46:38.438736 15704 config_compiler.cc:367] accessing blocking node with unresolved dependencies: liur.schema:
W20240529 16:46:38.438843 15704 config_compiler.cc:527] circular dependencies detected in liur.schema:
W20240529 16:46:38.438879 15704 config_compiler.cc:367] accessing blocking node with unresolved dependencies: liur.schema:

实际使用weasel 看似没有问题，但想了解一下它的成因与解决方案

**Comment by fxliang** [comment]
circular dependencies detected in liur.schema

方案依赖循环了，部署过程发现循环跳过了后面的无用的循环，不然会永远部署下去的

**Comment by dasu88** [comment]
> 我看了下，其实是方案里面，有一个 __include，引用了本文件的节点
> 
> https://github.com/ianzhuo/rime-liur/blob/9080e000d4bf859d91100188309e6e6c2f159ebf/Rime/liur.schema.yaml#L115
> 
> RIME 编译此文件时，展开 include 发现这是一个未被编译完成的文件（正在编译的文件），因而认为这可能造成一些误会。
> 
> 因而给出警告。没有实际影响。

谢谢说明
