### ISSUE TITLE
Neovide 看不到已鍵入字符 | typed Pinyin invisible in Neovide

### ISSUE THREAD

**Issue by One-In-Dark** [rime/weasel#1280]
**操作系统信息**
 - OS 详细版本: Windows 11 23H2 22631.3593
 - 小狼毫版本: Nightly release (8246b8c) (or 0.15.0.0)

**描述遇到的问题**
在 `Neovide` 中输入时, 看不到未上屏的已输入的拼音, 只有候选框. (Neovide [GitHub Repo](https://github.com/neovide/neovide))

Unable to see typed characters of Pinyin in Neovide.

在 luna_pinyin (朙月拼音) 和 double_pinyin_flypy (小鹤双拼) 下都会出现. 在皮肤 `DOTA 2` 和 `現代戰爭 / Modern Warfare` 下均可復現.

在 Neovim 终端中不会出现. Neovide 不需要额外配置.

In terminal Neovim it works well. Neovide can be of no configuration.

**复现步骤**
1. 打开 Neovide 软件
2. 在中文输入法下输入任何字符

**预期行为**
让我能够看到已输入的拼音.

**用户文件**
应该不需要特殊的配置文件. 采用雾凇拼音.

Rime Ice is used (indeed). [GitHub Repo](https://github.com/iDvel/rime-ice).

**截图**
![image](https://github.com/rime/weasel/assets/61355140/f0e4e316-b9f4-47c1-b884-140e5aed25c3)

![image](https://github.com/rime/weasel/assets/61355140/b517f358-f921-4ccd-a36b-7a2c508b0686)

**其他补充说明**
如此看来可能是 Neovide 处理已经输入的字符的问题. 不清楚应当是 bug 还是 feature request.

It seems to be JUST incompatibility with Neovide. Maybe it's rather feature request than bug.

**Comment by fxliang** [comment]
这个是neovide的bug
![image](https://github.com/rime/weasel/assets/4023160/94092c74-2037-4f08-b698-e6de04932aaa)

**Comment by One-In-Dark** [comment]
Yes, you're right. Sorry for my carelessness.

FYI, see Neovide Issue [#1931](https://github.com/neovide/neovide/issues/1931).

**Comment by xiehuc** [comment]
<img width="475" alt="Image" src="https://github.com/user-attachments/assets/0aa5d5f3-0da3-44c6-bac8-33f1317ebe0b" />

patch:
  app_options:
    com.neovide.neovide:
      no_inline: true

可以绕过去
