### ISSUE TITLE
0.16.1 在英文操作系統會強制使用英文界面

### ISSUE THREAD

**Issue by jack2game** [rime/weasel#1288]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 23H2 English Version
 - 小狼毫版本: 0.16.1

**描述遇到的问题**
無法修改小狼毫控制界面的語言

**预期行为**
增加設置界面的語言選項

**Comment by fxliang** [comment]
简体环境显示简体，繁体环境显示繁体，英文环境显示英文，有什么问题？

**Comment by jack2game** [comment]
有非常大的問題，應該將語言的選擇交還給用戶。日常使用英文系統，並不代表我系統中的所有程序都只能用英文運行。

**Comment by fxliang** [comment]
似有道理。pr welcome

**Comment by skylee03** [comment]
我的系統語言是繁體中文，不知爲何也顯示英文界面。😵‍💫

**Comment by fxliang** [comment]
@ccyybn 有空来修了

> 我的系統語言是繁體中文，不知爲何也顯示英文界面。😵‍💫 ![image](https://private-user-images.githubusercontent.com/24489025/337920210-a971ac10-c346-4d2b-b6e0-3b6ff2f487ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4OTE2MTMsIm5iZiI6MTcxNzg5MTMxMywicGF0aCI6Ii8yNDQ4OTAyNS8zMzc5MjAyMTAtYTk3MWFjMTAtYzM0Ni00ZDJiLWI2ZTAtM2I2ZmYyZjQ4N2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDAwMDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NzMzZjhkOTdhODE2NGQzZWY3MTdjMmNmOTc3NTBkMjYyMGQ1ZTNiMzJkMmFiODVjNjlhYjVmNzkxZjAxNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AsFq-amcD-iluoOUh8XeqCQBZ606ZekQSTTV-aiHfdI)

**Comment by ccyybn** [comment]
@skylee03 
我本来怀疑是这个`英文（香港特别行政区）`导致的，不过配置成这样后，我仍然没有复现这个问题

![image](https://github.com/rime/weasel/assets/7237501/72cb8de7-7e2b-409e-bd65-bc0173d479fb)

**Comment by ccyybn** [comment]
@skylee03 或许你可以试试把那个 `英文（香港特别行政区）` 换成 `繁体（香港特别行政区）`看看行不行

**Comment by jack2game** [comment]
> @skylee03 或许你可以试试把那个 `英文（香港特别行政区）` 换成 `繁体（香港特别行政区）`看看行不行

爲何一定要求用戶改變他們的系統設定，而不是提供正確的解決方案（即增加語言選項）呢？

**Comment by ccyybn** [comment]
@fxliang 之前是用的GetUserDefaultLCID()来判断语言，不知道是否 GetUserDefaultUILanguage() 更准确，不过我现在无法复现上面的问题，没法判断

**Comment by fxliang** [comment]
> > @skylee03 或许你可以试试把那个 `英文（香港特别行政区）` 换成 `繁体（香港特别行政区）`看看行不行
> 
> 爲何一定要求用戶改變他們的系統設定，而不是提供正確的解決方案（即增加語言選項）呢？

因为那样复杂，更易出不可用问题。

而我不明白，用户设定系统界面是英文的反而接受不了英文界面的小狼毫是什么心态？

同理简繁体。

**Comment by ccyybn** [comment]
@jack2game 
这里分为两个问题，一个是BUG，系统UI语言判断可能不准确，可能会受到地区选项干扰？

另一个是你提到的自定义显示语言，属于新增功能

之前没有发现问题，是因为你习惯于英文系统里小狼毫显示为繁体，并且安装时键盘选项也是繁体，否则当时英文系统还会出现简繁体都有的情况

**Comment by jack2game** [comment]
> > > @skylee03 或许你可以试试把那个 `英文（香港特别行政区）` 换成 `繁体（香港特别行政区）`看看行不行
> > 
> > 
> > 爲何一定要求用戶改變他們的系統設定，而不是提供正確的解決方案（即增加語言選項）呢？
> 
> 因为那样复杂，更易出不可用问题。
> 
> 而我不明白，用户设定系统界面是英文的反而接受不了英文界面的小狼毫是什么心态？
> 
> 同理简繁体。

很簡單的道理，而且上面的comments已經很清楚地說過。我的作業系統是英文，不代表我所有應用程序都只能用英文運行。

我在學習中文的過程中，想要讓自己的軟件用中文顯示也有錯嗎？如果你平常用中文系統，是不是你電腦上的所有英文文檔和軟件都應該只用英文顯示？

我甚至想問完全不給用戶一個應有的正常選項是什麼心態？

**Comment by ccyybn** [comment]
@jack2game 你的想法很好，但新功能工作量较大，主要看有没有`contributor`有这个需要和动力做这个功能，目前优先让软件默认按照系统语言显示是更为正确和通用的做法

**Comment by jack2game** [comment]
這其實不是什麼新穎的想法，我甚至不覺得是什麼值得稱讚的想法，因爲這是最基礎最基礎的用戶尋求之一。

如果在更新前連正常選項都不能提供的話，推送這個功能更新所帶來的用戶反饋就可以預見的肯定是負面的。0.16.1才推送兩天，試問類似的抱怨還少嗎？光issue就已經開了兩個，https://github.com/rime/weasel/issues/1296 也是類似的問題。

而認爲按照系統語言是“正确和通用”的做法，這又是誰評判的呢？是用戶還是試圖強行改變用戶習慣的開發者？而“把選擇權交給用戶自己”是不是更正確，更通用呢？

請再次站在用戶的角度來考慮，這不是一個什麼“nice to have”的選項，而是切切實實影響到了不少人的使用，我們才會打開這些issue。如果開發者不能正視這個問題，那不得不說是非常遺憾的。

**Comment by fxliang** [comment]
你的想法不是问题，但是你只看到用户的问题，没有想到过一点点实现这个”选项“中可能潜在的各种矛盾和各种问题，所以就判断现在这个状态烂，评价不可接受，是不是对用爱发电的开发者太苛刻呢？如果这样可以继续用0.16.0，但是那个也是自动简繁的。

为什么应用跟随系统语言是基本正确？因为系统语言都不影响正常使用，那软件跟随系统的状态不会造成**不可用问题**，更何况那些界面是极低频的界面。

或者下一个版本，出现一个有能力有精力的开发者可以做出更符合你需求的状态吧。

**Comment by jack2game** [comment]
正因爲我是用戶，所以我是看不到開發中的細節和問題的。正常來說，開發者和用戶幾乎都是單向的信息壁壘，但正因爲如此，不是開發者更應該站在用戶的角度出發嗎？

開發任何功能都需要一定的努力，這點我完全不否認，但我覺得讓我難以接受的是開發出不完善功能的同時，還試圖質問用戶是“什麼心態”的這種做法。

**Comment by fxliang** [comment]
> 爲何一定要求用戶改變他們的系統設定，而不是提供正確的解決方案（即增加語言選項）呢？

如果不是看到这句话，这个话题我本来是不会加词的。我已说了pr welcome ，和看到skylee03的情况有让英文界面相关的cc来留意这个issue。

cc在尝试和相关用户沟通细节确认怎么改进的时候，您上来就很不礼貌的反问，不合适吧

当你反问的时候，是不允许不同观点的别人反问的，是这个情况吗？

你是用户，我也是用户。你有不接受的表达方式，我也有啊。

**Comment by gaboolic** [comment]
我认为 
1 “简体环境显示简体，繁体环境显示繁体，英文环境显示英文” ，即跟随系统
2 一律显示简体 
3 一律显示繁体
三种情况均可接受，并且都有道理。
当然如果能提供可以更改语言的选项就更好了
ps：我用的鼠须管，整个菜单只有6个选项，一共也没几个单词/中文

**Comment by jack2game** [comment]
> > 爲何一定要求用戶改變他們的系統設定，而不是提供正確的解決方案（即增加語言選項）呢？
> 
> 如果不是看到这句话，这个话题我本来是不会加词的。我已说了pr welcome ，和看到skylee03的情况有让英文界面相关的cc来留意这个issue。
> 
> cc在尝试和相关用户沟通细节确认怎么改进的时候，您上来就很不礼貌的反问，不合适吧
> 
> 当你反问的时候，是不允许不同观点的别人反问的，是这个情况吗？
> 
> 你是用户，我也是用户。你有不接受的表达方式，我也有啊。

您說到這已經完全脫離這個issue討論的主題，連您自己都說“本來已經不會加詞”，但您既然要問，我就儘我可能說明：

1）我所問的問題是與本issue直接相關的問題，既然這個issue是討論相關issue的，問題的次序有關係嗎？所以這個issue的comments部分如果我在其他人之前問了問題就是“不禮貌”了嗎？還是說您是想要儘可能的找出我回覆裏的“瑕疵”，從而從其他一些(無關痛癢的)方面“攻擊”我？如果cc因爲(我在他人之前回覆)這件事被我冒犯，那我可以表達歉意，但是這跟您的回覆又有什麼關聯呢？

2）我從來沒有表達過不允許反問，您是如何得出這個結論的呢？但請在這個頁面上看一下，從您一開始的對我的問題而回覆的“是什麼心態”這種表達，請問是正常反問還是本身就已經帶有敵意了呢？

3）說到“不想加詞”是不是已經意識到了稍稍有一些理虧了呢？如果繼續說下去真的就偏離此issue太多了，一直偏題的問題上糾纏也完全不是我想做的，如果您還想繼續討論，我們可以換個場合。

我還是那個觀點：開發任何功能都需要一定的努力，這點我完全不否認，但我覺得讓我非常遺憾的是不能正視問題，在開發出不完善功能的同時，還試圖質問用戶是“什麼心態”的這種做法。

**Comment by fxliang** [comment]
我不认为不能设置界面语言是功能不完善或者什么问题，我坚持跟随系统界面的语言是正确且简单可靠的方案。输入法是系统级软件，其界面的语言跟随系统太正常和正确了。

不加词是基于，已表达，已了解，无想法，无计划。

关于这个issue，说到这，目前严肃的回复是暂无计划加选项。除非有人pr出合适的代码。

**Comment by skylee03** [comment]
> @skylee03 或许你可以试试把那个 `英文（香港特别行政区）` 换成 `繁体（香港特别行政区）`看看行不行

Windows 不允许语言列表中同时设置两种繁体中文，我将“英文（香港特别行政区）”移除后重启系统未能解决问题。我遇到的情况与现在这个 issue 应该不是同一个问题，或许我新开一个 issue 比较好。

**Comment by hegotit** [comment]
> 這其實不是什麼新穎的想法，我甚至不覺得是什麼值得稱讚的想法，因爲這是最基礎最基礎的用戶尋求之一。
> 
> 如果在更新前連正常選項都不能提供的話，推送這個功能更新所帶來的用戶反饋就可以預見的肯定是負面的。0.16.1才推送兩天，試問類似的抱怨還少嗎？光issue就已經開了兩個，#1296 也是類似的問題。
> 
> 而認爲按照系統語言是“正确和通用”的做法，這又是誰評判的呢？是用戶還是試圖強行改變用戶習慣的開發者？而“把選擇權交給用戶自己”是不是更正確，更通用呢？
> 
> 請再次站在用戶的角度來考慮，這不是一個什麼“nice to have”的選項，而是切切實實影響到了不少人的使用，我們才會打開這些issue。如果開發者不能正視這個問題，那不得不說是非常遺憾的。

开源产品和商业产品是非常不一样的，这一点我觉得一定要铭记于心。所谓“最基础最基础的需求”，仅仅针对商业产品，反过来对于开源产品而言，用户有需求有两个选择：1.提出issue，然后等维护者更新；2.自己提交PR。如果出于各种主客观原因维护者不做更新，而自身也没有足够技术储备提交PR，那么更明智实际的做法是寻求其他的开源或商业产品。

**Comment by fxliang** [comment]
虽然这个功能原本不想做，后面cc的pr之后看了只要小改就可以解，于是加了几行，最新nightly已经具备设置的功能，weaselsetup.exe 带参数/lt /ls /le分别可设置繁体简体和英文

就这样吧
