### ISSUE TITLE
weasel.dll 造成 Internet Explorer 11 崩溃

### ISSUE THREAD

**Issue by lifenjoiner** [rime/weasel#129]
1. 环境
build 31、33
![crash_other_app](https://user-images.githubusercontent.com/19585474/37282756-8e26043e-2630-11e8-8a91-78cc556768af.png)

2. 重现方法：IE，bing搜索框，输入中文按空格
![crash_other_app_bing](https://user-images.githubusercontent.com/19585474/37282831-cd7a5af4-2630-11e8-9014-1dfc7f3ac229.png)

3. 调试定位：“.text”段偏移+0x992
3.1 动态
![crash_other_app_dbg](https://user-images.githubusercontent.com/19585474/37282914-00a66bca-2631-11e8-8585-3f8ffd47bf5a.png)
3.2 静态
![crash_other_app_dis](https://user-images.githubusercontent.com/19585474/37283172-f892191a-2631-11e8-89f6-30f72094ec54.png)
3.3 源码
`WeaselTSF/Composition.cpp`?

**Comment by lifenjoiner** [comment]
应该是这里吧？`GetRange`
```
STDAPI CEndCompositionEditSession::DoEditSession(TfEditCookie ec)
{
	/* Clear the dummy text we set before, if any. */
	ITfRange *pCompositionRange;
	if (_pComposition->GetRange(&pCompositionRange) == S_OK)
		pCompositionRange->SetText(ec, 0, L"", 0);
	
	_pComposition->EndComposition(ec);
	_pTextService->OnCompositionTerminated(ec, _pComposition);
	return S_OK;
}
```

**Comment by nameoverflow** [comment]
大概是 https://github.com/rime/weasel/pull/117 遗留问题

**Comment by Prcuvu** [comment]
> 应该是这里吧？GetRange

定位正确。这里出现错误：
Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.

**Comment by nameoverflow** [comment]
这个很神奇的，在 weasel.dll 中一切都还正常，进入 Windows 的 ntdll 之后就丢了。我觉得已经超出了作为应用开发者的掌控范围……

**Comment by Prcuvu** [comment]
这次出现了新情况：

![image](https://user-images.githubusercontent.com/7923857/37296648-909b0f36-2656-11e8-873e-8946c302ffee.png)

**Comment by lotem** [comment]
如果不用 https://github.com/rime/weasel/pull/117，而用同步方式下原先的 hack，有沒有可能避免崩潰？
我不太懂，不妨考慮一下。

**Comment by Prcuvu** [comment]
暂时无法在其他 32 位应用上重现问题。

**Comment by nameoverflow** [comment]
可能要改变下现有的 composition 机制来解决。

**Comment by nameoverflow** [comment]
今天试了下又不能复现了……

**Comment by lifenjoiner** [comment]
最近更新升级到 Win 10 16299.309 后，套 IE 壳的程序也会崩溃次数也多了，比如我第一个截图的 GB，搞得我现在都不怎么敢用啦……

**Comment by nameoverflow** [comment]
[这个](https://ci.appveyor.com/project/rime/weasel/build/master%20build%2039-xydwpqfk/artifacts)应该能修复崩溃的问题。
