### ISSUE TITLE
有没有 "隐私模式" 之类的功能, 实现开启后不再记录用户词库, 也不记录词频

### ISSUE THREAD

**Issue by BH2WFR** [rime/weasel#1290]
有没有 "隐私模式" 之类的功能, 实现开启后不再记录用户词库, 也不记录词频

**Comment by LEOYoon-Tsaw** [comment]
關閉用戶詞典即可

**Comment by LEOYoon-Tsaw** [comment]
為啥要複製？直接關掉就行了

**Comment by fxliang** [comment]
既然不想 有留记录，在要用的方案里关闭用户词典就可以了

**Comment by BH2WFR** [comment]
> 關閉用戶詞典即可
> 既然不想 有留记录，在要用的方案里关闭用户词典就可以了

好的, 非常感谢!

**Comment by BH2WFR** [comment]
> 既然不想 有留记录，在要用的方案里关闭用户词典就可以了

作者您好，我遇到一个问题，关闭 enable_user_dict 后原有的个人用户词库读不到了，有没有其他可以实现对用户词库「只读取， 不写入」的方案？

**Comment by fxliang** [comment]
这个其实不自前端问题，参考添加扩展词库的方法，增加一个个人词库，增加或者删减的里面的内容的不重新部署一次

原来的用户词典就一定要开用户词典才可以读取，但是同时必要是会写入。
