### ISSUE TITLE
升級後完全無法輸入中文簡體

### ISSUE THREAD

**Issue by geniusleung** [rime/weasel#1291]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 10 22H2 OS Build 19045.4412 ]
 - 小狼毫版本: [ 0.16.1.0 ]

**描述遇到的问题** 及 **复现步骤**
升級前一切正常。升級後只要切換任何有關簡體輸入的輸入法都崩潰。

1. 使用三種輸入法：明月拼音，明月拼音-簡化字，粵語拼音
2. 切換 明月拼音和粵語拼音 輸出繁體字一切正常。
3. 切換 明月拼音-簡化字 崩潰，等2-3秒後只能輸入英文。且無法切換輸入法。需重啓服務。
4. 切換 粵語拼音後，輸出繁體字一切正常，但把輸出由 香港傳統漢字 改成 大陆简化汉字 後 崩潰同上。等2-3秒後只能輸入英文。且無法切換輸入法。需重啓服務。
5. 即使重新安裝，或者完全卸載後再重新安裝舊版本，問題依然存在。
6. （新發現）打開 詞典管理，可以打開設定界面，但是一開就崩潰同上。關閉設定界面後無法輸入中文，要重啓服務才能繼續使用。

**预期行为**
可能是字詞庫有衝突或者問題？

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by LEOYoon-Tsaw** [comment]
你用了自己的opencc字典吧，大概率是字典是壞的，最重要的是不要有重複的key

**Comment by geniusleung** [comment]
> 你用了自己的opencc字典吧，大概率是字典是壞的，最重要的是不要有重複的key

沒有啊，我也沒有改動過其他設定啊。剛剛嘗試打開 詞典管理，可以打開，但是一開就崩潰了。關閉設定後要重啓服務才能繼續使用。

**Comment by LEOYoon-Tsaw** [comment]
你用戶文件夾裡有opencc文件夾嗎，如果有的話裡面有什麼？

**Comment by geniusleung** [comment]
有opencc文件夾。
![image](https://github.com/rime/weasel/assets/87888909/aeff76db-cdf9-4b31-9003-5ec56baa8858)

**Comment by LEOYoon-Tsaw** [comment]
就是這裡的ocd有壞的

**Comment by geniusleung** [comment]
> 就是這裡的ocd有壞的

請問如何解決？我試過重新安裝也不能修復。

**Comment by geniusleung** [comment]
剛剛把這個文件夾的所有文件全部刪除後，修復正常了。謝謝幫忙。
