### ISSUE TITLE
请问一下大家， 打字选字宽出现黑边怎么解决 更新0.16.1出现 

### ISSUE THREAD

**Issue by zyz688** [rime/weasel#1294]
![image](https://github.com/rime/librime/assets/88613601/cc4344de-48ed-4309-ad80-ac053bdd0c3f)

**Comment by fxliang** [comment]
对应配色的`hilited_mark_color` 设置为`0x00000000` 即可

**Comment by zyz688** [comment]
> 对应配色的`hilited_mark_color` 设置为`0x00000000` 即可

谢谢 解决了

**Comment by offferu** [comment]
我这里是白边，还蛮好看的，让我知道这是选中词

![屏幕截图 2023-07-04 230406](https://github.com/rime/weasel/assets/34037165/902aeb77-9c2f-4862-b0d0-8ee983069d01)
