### ISSUE TITLE
小狼毫的组件自动联网真的好吗？

### ISSUE THREAD

**Issue by ChihSee-Hsie** [rime/weasel#1295]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载

**描述遇到的问题**
小狼毫开始主动提醒更新

**预期行为**
作为以保护用户隐私且不联网为主打的输入法，小狼毫主动联网提醒更新的行为似乎容易引起某种隐忧。故建议这一功能改为手动检查更新。

**Comment by fxliang** [comment]
这样就可以不自动检查更新了
```cmd
 REG ADD HKCU\Software\Rime\Weasel\Updates /v CheckForUpdates /d 0
```

**Comment by fxliang** [comment]
这样就可以不自动检查更新了
```cmd
 REG ADD HKCU\Software\Rime\Weasel\Updates /v CheckForUpdates /d 0
```

安装包里也只是加一行

要默认也不难，只是这个一直都是这样的，改了好？别人有意见要默认打开怎么办？代码都是公开的，从QQ群下载的时候都不隐居，这公开代码ci构建的有啥隐忧的……

**Comment by fxliang** [comment]
@ChihSee-Hsie 可以看看 #1297

可能还会改改，静默安装默认使能可能更合理
