### ISSUE TITLE
中文系統若使用非默認排序方式，則小狼毫界面語言變爲英文

### ISSUE THREAD

**Issue by skylee03** [rime/weasel#1299]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 22H2 22623.1325
 - 小狼毫版本: 0.16.1

**描述遇到的问题**

Windows 顯示語言爲「中文（繁體，台灣）」且排序方式爲「部首/筆劃」，小狼毫輸入法界面語言爲英文。

**复现步骤**

將 Windows 顯示語言設爲「中文（繁體，台灣）」，並在「地區格式」中將「排序方法」設爲「部首/筆劃」。

**预期行为**

小狼毫顯示繁體中文界面。

**截图**

![image](https://github.com/rime/weasel/assets/24489025/400ef71a-d4b3-42c6-9ef6-46f78d4d94cb)

![image](https://github.com/rime/weasel/assets/24489025/67302a7c-bce5-44cc-944b-05f5fea99df8)

**其他补充说明**

根據 [MS-LCID](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f)，一個 LCID 的結構如下：

![image](https://github.com/rime/weasel/assets/24489025/c48ac4c0-bb6e-45da-8138-2660fc3b6016)

由於 LCID 包含 Sort ID，而我所設置的排序方式並非中文（台灣）的默認排序方式， `GetUserDefaultLCID()` 所獲取到的 LCID 爲 263172 (0x00040404) 而非 1028 (0x00000404)。

該問題曾於 #1288 評論區提及。由於該問題與原 issue 並非同一問題，故單獨提出 issue。

**建議修改**

獲取系統語言的代碼可考慮改爲 `GetUserDefaultLCID() & 0xFFFF` 或使用其他 API。

相關 API 在我電腦上得到的結果如下：

```
GetUserDefaultUILanguage:   1028
GetSystemDefaultUILanguage: 1028

GetUserDefaultLangID:       1028
GetSystemDefaultLangID:     1028

GetUserDefaultLCID:         263172
GetSystemDefaultLCID:       1028
```

**Comment by fxliang** [comment]
很细致，刚也看到MS-LCID那份资料

@ccyybn 可以看看这个

**Comment by skylee03** [comment]
裝上了最新的 nightly build，問題已被修復。感謝 @fxliang 和 @ccyybn！
![image](https://github.com/rime/weasel/assets/24489025/8c1ca285-336e-4999-87fb-a4125ee1ddf9)

**Comment by skylee03** [comment]
- Fixed by #1298
