### ISSUE TITLE
Windows 8.1 下使用小狼毫 TSF 导致 Store Application 宿主崩溃

### ISSUE THREAD

**Issue by be5invis** [rime/weasel#13]
1. 将系统惟一输入法设置成小狼毫 TSF
2. 打开「邮件」「应用商店」等应用
3. 查看事件查看器，选择 Windows 事件，可以发现来自 Apps 源的崩溃记录

**Comment by luckyamber** [comment]
我也是这个问题，今天才找到原因

**Comment by adouzzy** [comment]
Same problem under windows 10, 10159.
I can not open Edge browser, Store, and the star menu is laggy.
See I cannot type Chinese now ...
