### ISSUE TITLE
简繁切换UI异常

### ISSUE THREAD

**Issue by bennyyip** [rime/weasel#1300]
**操作系统信息**
 - OS 详细版本: Windows 11 Version 23H2 (0S Build 22631.3593)
 - 小狼毫版本: 0.16.1

**描述遇到的问题**
`ctrl+shift+3` 简繁切换左边一片空白，印象中旧版本是有字的。全角半角等切换也是一样的现象。
 ![image](https://github.com/rime/weasel/assets/7467687/00b5f9a7-5c65-4bef-9746-96b18fa3108b)

**用户文件**
[build/weasel.yaml](https://pastebin.com/w41CXzRC)
文件太长了，我放到pastebin

**Comment by fxliang** [comment]
我用明月拼音配合我目前的配色没有复现问题，可能您试试换个默认的配色看看？会不会是配色上有漏了什么？
![tip](https://github.com/rime/weasel/assets/4023160/92e9a23d-0d28-4d3a-b74a-600b03c2f2e4)

**Comment by bennyyip** [comment]
奇怪，我重啓服務就正常了。
我先關了issue吧，等我找到怎麼復現再開
