### ISSUE TITLE
浏览器地址栏中文输入时，按回车不能触发字母上屏

### ISSUE THREAD

**Issue by lhs-12** [rime/weasel#1301]
**操作系统信息**
 - OS 详细版本: Windows 11 23H2 22631.3672
 - 小狼毫版本: 0.16.1

**描述遇到的问题**
浏览器地址栏，使用中文输入，按回车不能触发字母上屏

**复现步骤**
1. 打开Edge浏览器
2. 切换到中文输入状态，在地址栏输入
3. 按回车

**预期行为**
按回车后，应该触发字母上屏，但在浏览器地址栏，按回车后字母没了。
该功能在记事本等其他软件上正常。

**Comment by fxliang** [comment]
Windows 10 试过inline_preedit和非inline_preedit，都未复现问题

**Comment by lhs-12** [comment]
我刚尝试把配置清空重新部署，默认配置下，结果还是一样。
补充一点：如果地址栏里本身有内容，然后打字后按回车，会直接触发搜索，打的字像是被吃掉了。打字按空格倒是正常输出中文没问题。

Win10不出现那估计是系统或浏览器版本原因导致的吧，以后看其他Win11的人有没有遇到同样的问题吧。

**Comment by fxliang** [comment]
版本 122.0.2365.80 (正式版本) (64 位)
这个应该还算比较新吧？

**Comment by lhs-12** [comment]
> 和@lhs-12一样的系统配置 edge版本 125.0.2535.92 (正式版本) (64 位) 按回车后，字母上屏输入正常。

我也是这个edge版本。。。而且我还把扩展全关了，就是个纯净的浏览器。依然不正常。

另外，我配置了ascii_composer的switch_key的行为为commit_code，这个上屏倒是正常的。就只有回车不正常。

**Comment by lhs-12** [comment]
我找到原因了，导致这个的原因是我联想电脑的电脑管家里面，有个“搜索引擎保护”的配置，这个配置默认是开的，把这个配置关掉了，就正常了。

![image](https://github.com/rime/weasel/assets/45565870/b71d681f-5427-45ad-8e61-7c74c177df08)

**Comment by fxliang** [comment]
出问题的方式可能是小狼毫上屏了又被管家删除了，这样很可能没办法

**Comment by lhs-12** [comment]
> 出问题的方式可能是小狼毫上屏了又被管家删除了，这样很可能没办法

但我 switch_key 的行为配置为 commit_code 的时候，用 switch_key 上屏是正常的，所以应该还是有办法的。

不过说实话，我也觉得这玩意恶心，一些第三方软件搞的骚操作，把系统自带浏览器都搞出些莫名其妙的东西。就算这次给他兼容了，下次保不准他改个代码，又出问题。所以我更推荐文档里提一下这种类似的情况就可以了，不一定要代码兼容他。

**Comment by fxliang** [comment]
> > 出问题的方式可能是小狼毫上屏了又被管家删除了，这样很可能没办法
> 
> 但我 switch_key 的行为配置为 commit_code 的时候，用 switch_key 上屏是正常的，所以应该还是有办法的。
> 
> 不过说实话，我也觉得这玩意恶心，一些第三方软件搞的骚操作，把系统自带浏览器都搞出些莫名其妙的东西。就算这次给他兼容了，下次保不准他改个代码，又出问题。所以我更推荐文档里提一下这种类似的情况就可以了，不一定要代码兼容他。

核心是switch key不是enter吧

**Comment by lhs-12** [comment]
估计是吧，可能是个无法解决的问题

**Comment by ws2bhhh** [comment]
环境：Windows 11 26100.4652，rime_version: 1.13.1
确认火绒有同款问题。
开启了浏览器保护后Edge中文模式输入`asd`按下回车会直接搜索`a s d`而不是键入`asd`且rime假死，无论怎么按都不出候选直到来回切换一次中英文
并且不止Edge，VSCode测了表现为光标换行候选框不动
多次测试后发现 关闭保护->重启算法服务->切换中英文 问题消失
