### ISSUE TITLE
TSF 模式 Win7 IE 网页只能输入英文

### ISSUE THREAD

**Issue by lifenjoiner** [rime/weasel#131]
32位 Win7，IE 11。
IE 怎么和 cmd 一样特殊？难道是多进程引起的？单进程的套壳浏览器和多进程的firefox、chrome 倒是正常，……

**Comment by Prcuvu** [comment]
请 @mrhso 验证。

**Comment by mrhso** [comment]
我并无 IE 11 环境。
在 Windows 7 x64 运行的 IE 8 中，无法重现。

**Comment by zhtw2013** [comment]
已重現，Win10 x64 IE11無法輸入中文。

**Comment by nameoverflow** [comment]
合并至 #136 讨论。
