### ISSUE TITLE
chat.baidu.com不能打字

### ISSUE THREAD

**Issue by xfdyd** [rime/weasel#1313]
**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [ ] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 19045.4412
 - 小狼毫版本: 0.16.1

**描述遇到的问题**
chat.baidu.com不能打字

**复现步骤**
重现问题的步骤，如：
1. 打开 chat.baidu.com
2. 登录
3. 在下方输入框打字
4. 第一次按键时，输入法经常闪一下就没了，致使无法打字上屏。

**预期行为**
按键时，输入法候选条保持显示。

**用户文件**
[data.zip](https://github.com/user-attachments/files/15847794/data.zip)

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
我刚全新安装。

**Comment by IV16SL** [comment]
没能复现此问题。

**Comment by xfdyd** [comment]
> 没能复现此问题。

我这里搜狗等也有这个问题，很普遍。浏览器是新的Chrome。

**Comment by fxliang** [comment]
参考firefox的workaround，设置app_options/chrome.exe/inline_preedit: true

这个是因为该页面的js不吃空格开头的字符串（你无法直接输入空格开头），而inline_preedit: false时为了定位输入框使用了哑字符空格，于是引发了无法输入的问题。
