### ISSUE TITLE
0.16.1.0 版，style/hover_type: "semi_hilite" 好像有問題

### ISSUE THREAD

**Issue by JoKlever** [rime/weasel#1314]
升級到 0.16.1.0 版 (on Win11 pro 64-bit)
當 style/inline_preedit: true 時，hover_type: "semi_hilite" 在第一個候選詞的 “semi_hilite" 好像有問題。

Correct -
![2024-06-17 Rime PR - correct](https://github.com/rime/home/assets/139798818/a2d20a0f-db5d-44a3-9b0a-26b2d5bcb3d9)

Incorrect -
![2024-06-17 Rime PR - incorrect](https://github.com/rime/home/assets/139798818/8aa2de97-c06e-4c53-b4a9-02f7f0686ba7)

**Comment by fxliang** [comment]
我相信在[cc8fd06](https://github.com/rime/weasel/commit/cc8fd06cb7f2e6bcac6cd46f9265214613482a89)修复了，可以更新用稍后的nightly产出，谢谢反馈~

![image](https://github.com/rime/weasel/assets/4023160/4da8b778-d0e8-4700-9a87-42ef5226f726)

**Comment by JoKlever** [comment]
@spew8712

主要是在 translator/comment_format 做調整：

translator:
  always_show_comments: true
  comment_format:               # 將註釋訊息做些轉換
    # Convert tonal numerals to superscripts
    # No change tone for the last（or single）word
    - xform/1$/¹/
    - xform/2$/²/
    - xform/3$/³/
    - xform/4$/⁴/
    - xform/5$/⁵/
    - xform/6$/⁶/
    - xform/7$/⁷/
    - xform/8$/⁸/

    # 按台語（閩南語）變調規則 
    # Also display the tone change, except the 9th tone （I think, it stays the same.）
    - xform/1/¹⁷/
    - xform/2/²¹/
    - xform/3/³²/
    - xform/([Hh])4/$1⁴²/
    - xform/([^Hh])4/$1⁴⁸/
    - xform/5/⁵⁷/
    - xform/6/⁶¹/
    - xform/7/⁷³/
    - xform/([Hh])8/$1⁸³/
    - xform/([^Hh])8/$1⁸⁴/
    - xform/9/⁹/

當然，這只有對可以連在一起的“詞”是正確的，因為只有最後一個字是保持原調。如果連續打的字不成一個“詞”，結果就不對了。😥

**Comment by JoKlever** [comment]
@fxliang 

您測的是不是 當 **style/inline_preedit: true** 的結果？

多謝！
