### ISSUE TITLE
反馈一个BUG,`这个按键 即使设定了只有一个符号,输入的时候仍旧会弹出列表让选择

### ISSUE THREAD

**Issue by chainofhonor** [rime/weasel#1316]
版本0.16.1
系统WIN10 LTSC 2021

配置文件如下,我把所有的符号按键都改为英文模式下的符号了
![小狼毫配置文件](https://github.com/rime/weasel/assets/38763606/c5277d53-0d91-4847-a476-bd72efbf68ed)

然后问题来了,键盘ESC下面[TAB上面]的这个键,按下去以后尽管只有1个候选,仍旧还弹出列表让用户选择
![小狼毫反馈bug](https://github.com/rime/weasel/assets/38763606/dda99ec4-ed58-4e6e-bbd7-ed0055367fa6)

**Comment by chainofhonor** [comment]
最后提个小建议:
建议把 明月简体 这个输入方式的默认设置改为:

候选10个
全角符号改为中文符号,不要让用户手动去选择
半角符号改为英文符号,不要让用户去选择
按键绑定只保留when: has_menu的那4个 [说实话,其他的那些按键真的没用,绝大多数人都是普通人,不需要那么多按键]
功能键切换改为如下
  switch_key:
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: noop
    Shift_R: noop
ctrl和shift键真的不需要加什么功能

这样做的目的是:
让用户安装好了,就能直接用了,不需要慢慢的调整了

我重新安装小狼毫是因为我2021年提的一个issue有人回复说0.16.1修复了在魔兽争霸里面输入中文的问题
然后刚好win10自带的输入法又有点问题,经常词序出问题然后还没法直接输入带数字的网址
我就安装了小狼毫看看效果
经过这几个小时的折腾,我感觉现在用起来终于像样了

**Comment by ClixTW** [comment]
上屏的問題，是少改了方案內的speller/alphabet：
```
# 拼写设定
speller:
  # 如果不想让什么标点直接上屏，可以加在 alphabet，或者编辑标点符号为两个及以上的映射
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA`
```
（從rime-ice複製的，多麼貼心的註釋）

不建議半形符號預設成英文符號，這樣大多數人會像你一樣打的是中文，用的卻是錯誤的英文標點。

**Comment by chainofhonor** [comment]
https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F

按照这个教程,我上面的修改应该是没问题的,这应该就是程序的bug  
在候选仅仅只有1个的时候还弹出列表

你提供的方式我也测试了,不行

**Comment by wwssxx** [comment]
关了吧，这是你设置了反查，反查的快捷键是这个符号。
