### ISSUE TITLE
請問如何打出半型的（）符號❓

### ISSUE THREAD

**Issue by iorizero** [rime/weasel#1320]
請問如何打出半型的（）符號❓
之前用行易的可以自建，現在要何自建半型的（），謝謝

**Comment by LEOYoon-Tsaw** [comment]
看不懂，你要打出哪個字符？這兒有Unicode全部字符，你找找

http://www.unicode.org/charts/

**Comment by iorizero** [comment]
我要的是半型的括號（）。,g、，gg 是打的出來，但都是全型，我要的是半型。

**Comment by LEOYoon-Tsaw** [comment]
你要打什麼符號自己加到字典/symbols裡就行

**Comment by skylee03** [comment]
中文輸入狀態下圓括號默認是全形，若想要半形括號，可以按 <kbd>Shift</kbd> 進入英文輸入狀態後再輸入，或者按 <kbd>Ctrl</kbd> + <kbd>`</kbd> 在選單內切換全／半形標點。

**Comment by iorizero** [comment]
感謝您 [skylee03](https://github.com/skylee03) 
已解決，我在  liur_customWords.dict.yaml 中加入 ，但是是排在第一排。
就是不想用 Shift + 9 和 Shift + 0 輸入 才提問，非常感謝您的幫忙。
另外，在其對應的倉庫提問。這個不太懂什麼意思？抱歉，再請給予指教。

**Comment by skylee03** [comment]
> 感謝您 [skylee03](https://github.com/skylee03) 已解決，我在 liur_customWords.dict.yaml 中加入 ，但是是排在第一排。 就是不想用 Shift + 9 和 Shift + 0 輸入 才提問，非常感謝您的幫忙。 另外，在其對應的倉庫提問。這個不太懂什麼意思？抱歉，再請給予指教。

感覺這個問題更像是針對具體輸入方案的提問，所以直接在 [hsuanyi-chou/rime-liur](https://github.com/hsuanyi-chou/rime-liur) 問應該能得到更加針對性的答覆，不過在這裏問也可以。

**Comment by iorizero** [comment]
謝謝，了解了。請問為什麼原生小狼豪沒有嘸蝦米❓是因為版權嗎❓

**Comment by LEOYoon-Tsaw** [comment]
> 謝謝，了解了。請問為什麼原生小狼豪沒有嘸蝦米❓是因為版權嗎❓

rime只自帶很少量的方案，因為沒有必要用大量方案去佔用用戶的磁盤空間。更多的方案可以通過plum獲取。
