### ISSUE TITLE
Windows 10 Cortana/开始菜单 下不显示候选词菜单（版本： 0.10.0 预览版）

### ISSUE THREAD

**Issue by zaneyu** [rime/weasel#133]
各开发者好：

刚刚测试了在知乎上发布的 0.10.0 预览版，我留意到在 Windows 10 下在开始菜单或 Cortana 界面中使用 TSF 模式时都无法显示候选词菜单，但可以实际输入汉字。在 Edge 或商店中（估计其他 Metro 应用类同）则可正常显示菜单。

Windows 10 版本： Pro 1709 build 16299.248

顺颂
时祺

**Comment by Prcuvu** [comment]
Duplicate of #110.
