### ISSUE TITLE
Rime causes Windows to freeze for 5-10 seconds when clicking taskbar

### ISSUE THREAD

**Issue by scorpjke** [rime/weasel#1335]
OS: Windows 11 23H2 22631.3880
Rime: 0.16.1.0

--- Describe the problem ---
Rime causes my system to freeze.

--- Reproduce the steps ---
1. Make sure the language is set to Rime.
2. Click anything on the taskbar (switch to another app or the time icon or the volume icon, etc)
3. The whole PC (explorer.exe?) just freezes for 5-10 seconds.

--- Other Supplementary Notes ---
The reason I'm sure that this freezing is caused by Rime is because when I switch the language to anything else, the freezing never happens.

This is the only problem. At other times, Rime works fast and my laptop works fast. This problem appeared immediately on my newly bought laptop. My previous laptop (Windows 10) didn't have this problem.

**Comment by fxliang** [comment]
try the nightly release, I think 60c5455 might have solved it.

**Comment by hlc1209** [comment]
> > try the nightly release, I think [60c5455](https://github.com/rime/weasel/commit/60c5455c57996e5fb8d9602e31579f6ed24627e6) might have solved it.
> 
> Not sure what to do with that specific url you gave me, I don't know how to compile that. I installed this: https://github.com/rime/weasel/releases/tag/latest
> 
> It didn't help, the freezing still happens.

https://github.com/rime/weasel/releases/tag/latest

**Comment by TomoeMami** [comment]
> > try the nightly release, I think [60c5455](https://github.com/rime/weasel/commit/60c5455c57996e5fb8d9602e31579f6ed24627e6) might have solved it.
> 
> Not sure what to do with that specific url you gave me, I don't know how to compile that. I installed this: https://github.com/rime/weasel/releases/tag/latest
> 
> It didn't help, the freezing still happens.

Check out this: https://github.com/rime/weasel/actions

**Comment by s-rog** [comment]
This also happens on windows 10, tried the latest nightly with that commit but the issue remains.

**Comment by s-rog** [comment]
I performed a clean re-install of weasel (removing rime from appdata) and the issue seems to have disappeared, even after applying my previous yaml customization, thanks.

**Comment by scorpjke** [comment]
When you told me to reinstall, I didn't consider also deleting the Rime folder with yaml files. Looks like this issue happened because when I started using a new PC, I just copied the whole Rime folder with yaml files, including the Build folder, I'm guessing that's what caused problems. After deleting the Rime folder, the problem disappeared.
