### ISSUE TITLE
ctrl+space关闭键盘后，第一个或前几个字符消失

### ISSUE THREAD

**Issue by hlc1209** [rime/weasel#1336]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本:  Windows 11 23H2 22631.3737
 - 小狼毫版本: 0.16.1

**描述遇到的问题**
ctrl+space关闭键盘后，鼠标点击任意其他位置，第一个（有时是前几个）字符消失

**复现步骤**
1. 使用中文输入模式
2. 在任意文字输入框中，任意按几个键，出现候选字框
3. 保持候选字框存在，直接按ctrl+space关闭键盘
4. 稳定复现

**预期行为**
不应该有字符消失现象

**用户文件**
https://github.com/iDvel/rime-ice
只改了截图所示内容
![image](https://github.com/user-attachments/assets/d48b94c9-e53e-43a3-8760-4229ff2ae17a)

**截图**
如GIF所示
候选字框消失时，是我按了ctrl+space
![PixPin_2024-07-23_17-16-21](https://github.com/user-attachments/assets/598a6292-f3f3-45b0-b627-705ab8846a7e)

**其他补充说明**
关联https://github.com/iDvel/rime-ice/issues/973

**Comment by fxliang** [comment]
https://github.com/rime/weasel/blob/372bcb4f48f9f86a6b187af4a49f0d4c50d24973/WeaselTSF/Compartment.cpp#L246-L250

ctrl+space不是切换英文模式，是关闭键盘。
这个是预期行为，关闭键盘的时候清空composition。
可能会有人觉得这不合理，希望有高人可以给出让所有人都觉得合理的方案意见吧

**Comment by hlc1209** [comment]
> https://github.com/rime/weasel/blob/372bcb4f48f9f86a6b187af4a49f0d4c50d24973/WeaselTSF/Compartment.cpp#L246-L250
> 
> ctrl+space不是切换英文模式，是关闭键盘。 这个是预期行为，关闭键盘的时候清空composition。 可能会有人觉得这不合理，希望有高人可以给出让所有人都觉得合理的方案意见吧
> 
> 而且你后面的复现方式和标题的描述相去甚远

原来
![image](https://github.com/user-attachments/assets/0b795ccc-aef6-4a7a-b537-cd8f9ac2176e)
是关闭键盘的状态，而不是英文模式。已修改标题

**Comment by hlc1209** [comment]
> https://github.com/rime/weasel/blob/372bcb4f48f9f86a6b187af4a49f0d4c50d24973/WeaselTSF/Compartment.cpp#L246-L250
> 
> ctrl+space不是切换英文模式，是关闭键盘。 这个是预期行为，关闭键盘的时候清空composition。 可能会有人觉得这不合理，希望有高人可以给出让所有人都觉得合理的方案意见吧
> 
> 而且你后面的复现方式和标题的描述相去甚远

不过我从智能ABC到搜狗拼音到微软拼音再到RIME。我经常打了几个字符后才发现是英文状态，多年习惯就是英文输入时使用ctrl+space切换（也照顾到有些时候打游戏用ctrl+space关闭输入法）。
我觉得既然是关闭键盘，输入法就不应该再发挥作用。字符消失与直觉上的期待颇为不符。

**Comment by fxliang** [comment]
> 我觉得既然是关闭键盘，输入法就不应该再发挥作用。字符消失与直觉上的期待颇为不符。

问题在于，也有人认为应该清空之前的composition。所以我说

> 希望有高人可以给出让所有人都觉得合理的方案意见吧

**Comment by hlc1209** [comment]
> > 我觉得既然是关闭键盘，输入法就不应该再发挥作用。字符消失与直觉上的期待颇为不符。
> 
> 问题在于，也有人认为应该清空之前的composition。所以我说
> 
> > 希望有高人可以给出让所有人都觉得合理的方案意见吧

您说的composition是指候选词框吗？
如果是候选词框的话，我觉得无论是否清空，反正都是”关闭键盘“的行为。既然关闭了键盘，输入法就不应该干预后续的所有行为，字符消失也不应该发生

**Comment by ClixTW** [comment]
感覺兩位說的不是同一件事😅

這邊可以復現，
在候選框存在時Ctrl+Space關閉輸入法，
然後隨意輸入幾行英文，用滑鼠點擊不同行時，
會有英文字母被刪除或移動位置。

**Comment by fxliang** [comment]
> 复现步骤
> 
> 使用中文输入模式
> 在任意文字输入框中，任意按几个键，出现候选字框
> 保持候选字框存在，直接按ctrl+space关闭键盘
> 稳定复现

因为标题描述不清，所以只能看复现步骤，结果……

**Comment by mirtlecn** [comment]
> 多年习惯就是英文输入时使用ctrl+space切换（也照顾到有些时候打游戏用ctrl+space关闭输入法）。

我也有用 control + space 切换中英输入的习惯。好像关闭键盘后，清除或者上屏全部 composition 是之前我提的 FR。

我提供一个解决方法：在系统中禁用 control + space 快捷键，用 RIME 本身来控制此快捷键，这也是我一直以来的做法：

## 步骤一：
在 rime 将 control + space 绑定为切换中英，且上屏未输入字符；
```
# default.custom.yaml
key_binder/bindings/+:
  - { accept: Control+space, when: always, toggle: ascii_mode }
  - { accept: Control+space, when: always, send: Eisu_toggle }
ascii_composer/switch_key/Eisu_toggle: commit_code
```

## 步骤二：

禁用简体中文环境下， control + space 作为输入法/非输入法切换快捷键（注意，会影响微软拼音输入法的切换中英方式）

导入以下注册表即可。

[Regedit.zip](https://github.com/user-attachments/files/16356679/Regedit.zip)

之所以要用注册表，是因为 Windows 提供的 GUI 配置方式无法持久生效，似乎是自 xp 时代以来的 bug（文本服务与输入语言->高级键设置）

## 效果

按下 control + space 后：

[1721792060.webm](https://github.com/user-attachments/assets/a9b70507-e23a-4be5-b426-82e27d7d8868)

**Comment by hlc1209** [comment]
> > 多年习惯就是英文输入时使用ctrl+space切换（也照顾到有些时候打游戏用ctrl+space关闭输入法）。
> 
> 我也有用 control + space 切换中英输入的习惯。好像关闭键盘后，清除或者上屏全部 composition 是之前我提的 FR。
> 
> 我提供一个解决方法：在系统中禁用 control + space 快捷键，用 RIME 本身来控制此快捷键，这也是我一直以来的做法：

这是非常好的workaround。感谢！
只可惜我有时也使用其他语言键盘，不得不继续使用Windows自带的ctrl+space快捷键。
还是希望rime能早日修复这个issue
