### ISSUE TITLE
0.16.1 会导致大量软件在关闭后产生 Application Error 事件

### ISSUE THREAD

**Issue by EVANGELION-Air** [rime/weasel#1337]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 Enterprise LTSC 21H2 19044.4651 / Windows 10 Enterprise 22H2 19045.4651
 - 小狼毫版本: 0.16.1 2024-06-06 release

**描述遇到的问题**
该问题非常隐蔽，因为并没有导致软件出现错误无法使用，它仅仅会在软件关闭后产生，但是会在事件管理器以及系统可靠性记录中产生大量错误日志
根据Windows事件管理器记录，事件ID 为 1000，来源为 Application Error，错误模块路径: C:\Windows\SYSTEM32\ntdll.dll
在最初我认为是系统存在损坏或者驱动出现错误导致定位到ntdll，但是经过我大量全新安装系统与排查实验，最终定位到是 rime/weasel 0.16.1导致的问题
此外，我已经尝试nightly版本，并没有解决该问题
有大量软件都会出现这一情况，以下我以 word 和系统自带的 计算机管理 为例

**复现步骤**
1.全新安装0.16.1正式版本，可以全默认状态不做任何修改，包括输入方案
2.确保切换到weasel
3.打开word，或者，直接右键开始菜单打开 计算机管理
4.随便打几个字，或者，在计算机管理中打开事件查看器，查看一下事件日志，只要保证该软件是在使用 weasel 输入法
5.关闭 word，或者，直接关闭事件查看器，你会发现软件是正常关闭的，但是鼠标出现异常的加载转圈动画
6.此时再打开计算机管理，定位到事件查看器，你会发现出现了 Application Error 日志

以 word 为例，事件日志为：

错误应用程序名称: WINWORD.EXE，版本: 16.0.17726.20160，时间戳: 0x668c4981
错误模块名称: ntdll.dll，版本: 10.0.19041.4522，时间戳: 0x8a1bb6f3
异常代码: 0xc000000d
错误偏移量: 0x0000000000112414
错误进程 ID: 0x1dcc
错误应用程序启动时间: 0x01dadea069bf89da
错误应用程序路径: C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE
错误模块路径: C:\Windows\SYSTEM32\ntdll.dll
报告 ID: e98bd674-0cca-4fa5-a141-889d03fc7f9e
错误程序包全名: 
错误程序包相对应用程序 ID: 

我非常确定该问题是由 weasel 输入法导致的，因为我在出现上述日志后立刻卸载了 weasel 输入法重复上述过程，此问题不再发生

我又尝试使用 0.16.0 版本，发现问题发生变化，并且是随机产生的，此时的事件管理器会准确报告 WeaselServer.exe 出现问题，事件ID 为 1000，来源为 Application Error，输入法服务退出，需要手动启用服务

错误应用程序名称: WeaselServer.exe，版本: 0.16.0.0，时间戳: 0x66437bf0
错误模块名称: unknown，版本: 0.0.0.0，时间戳: 0x00000000
异常代码: 0xc0000005
错误偏移量: 0x0000000000000000
错误进程 ID: 0x23a8
错误应用程序启动时间: 0x01dadea464d04692
错误应用程序路径: C:\Program Files (x86)\Rime\weasel-0.16.0\WeaselServer.exe
错误模块路径: unknown
报告 ID: 3d0ed72f-e8b1-43eb-b50c-913bd55f9cd0
错误程序包全名: 
错误程序包相对应用程序 ID: 

**预期行为**
无

**用户文件**
我没有任何定制文件，可以使用全默认设置复现该问题

**截图**
无

**其他补充说明**
无

**Comment by mirtlecn** [comment]
在 win 10 22H2 和 win11 23H2 虚拟机测试用官方的 16.1 测试了下，确实能复现。

倒是本机上不能复现。还有同是 mmc.exe，只看到计算机管理可以触发，什么磁盘管理，设备管理都不行。

不过没发现实际影响。程序正常退出，算法服务也发现崩溃。

**Comment by fxliang** [comment]
@EVANGELION-Air 可以看看 #1338 的产出看是不是解决了，谢谢~
