### ISSUE TITLE
在特定程序下禁止中英文切换

### ISSUE THREAD

**Issue by terrytw** [rime/weasel#1339]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [Windows 10 22H2 19045.4046]
 - 小狼毫版本: [0.16.1.0]

**描述遇到的问题**
希望能在特定程序下禁止中英文切换,主要原因是游戏经常会误操作切换导致出现问题

**Comment by mirtlecn** [comment]
我好像体会过你说的「误操作切换导致出现问题」，

不过这个让游戏本身去做更好，比如 MC（我的世界）就一直有禁用输入法的插件啊，还要程序在部分界面会自己关掉输入法，那么 win 应当有相关的接口吧。

统一给一个应用禁掉 ascii mode，不太好吧。比如 MC 里面聊天要打中文，游戏中就不需要输入法。

**Comment by fxliang** [comment]
Ctrl+空格解决问题

**Comment by terrytw** [comment]
Shift + Space 的确解决了问题, 谢谢!

**Comment by TsuZing** [comment]
Ctrl+Space 不就是切换中英文的系统快捷键吗？如何起到“禁止中英文切换”的效果？我使用 Alt+Shift 更换输入法来实现中英文切换，即RIME只需要中文输入，已经禁用除大写锁定外的所有中英文切换快捷键，但部分程序仍然会把RIME切换至英文模式，导致必须按两下 Alt+Shift 才能输入中文，即使已经设置 `ascii_mode: false`

**Comment by christaikobo** [comment]
Ctrl+Space是微软拼音切换中英文的快捷键. 
用rime的时候, Ctrl+Space会禁用输入法

![Image](https://github.com/user-attachments/assets/c5067621-868d-4be4-911c-52aa92b258e8)

![Image](https://github.com/user-attachments/assets/88f8b6b9-daad-442e-abc9-6d6ff5c0d21e)

**Comment by TsuZing** [comment]
所以确实不能完全实现“禁止中英文切换”，只能禁止中文输入，不能禁止英文输入。不知有什么方法能实现后者，这个问题实际上在微软拼音也诟病已久，微软拼音的自动切换中英文无法关闭，并且经常出现BUG导致输入模式莫名其妙变成英文。OS都自带了输入法切换，输入法内置的语言切换某些场景就显得多此一举了

**Comment by christaikobo** [comment]
ctrl+space可以解决我的问题, 因为我的问题是游戏内出现中文输入导致游戏操作指令不能register

至于彻底禁止中英文切换, 你可以关注https://github.com/rime/weasel/issues/1544

另外"OS自带输入法切换"这一点我是不赞同的, 微软拼音并不是OS, 就好比Edge并不是OS一样. 我用的英文windows系统, 是没有微软拼音的.
