### ISSUE TITLE
根据文档编译不成功，求个官方编译视频教学~

### ISSUE THREAD

**Issue by cunkai** [rime/weasel#1344]
![PixPin_2024-08-07_10-48-25](https://github.com/user-attachments/assets/719b57f1-d347-4a07-bbe5-639af9fc7094)

https://github.com/rime/weasel/blob/master/INSTALL.md  

这个文档默认编译的是arm64  需要改成0

但是还是有很多C++引入报错 , 我vs玩的菜~ 

![微信截图_20240807092349](https://github.com/user-attachments/assets/265b0507-2f3c-48cb-91e3-2e71eb5cf627)

**Comment by fxliang** [comment]
1，不需要修改build.bat，如果不编译arm产物，build.bat就是
2，librime不建议自行构建，直接用github.install.bat来部署准备就可以
3，不支持vs2015，vs2017没有试过，建议至少要vs2019来构建.vs2015如无意外是不支持c++17标准的
4，community版通常不会包含atl，要另外使用visual studio installer安装atl组件
5，boost，建议要1.84.0，install_boost.bat来解决或者自行安装boost 1.84.0
6，编译步骤，参考release-ci.yml的步骤来开展，build.bat arm64那一步不加arm64就基本没有问题了

**Comment by terrytw** [comment]
@cunkai 请问你后来编译成功了吗, 能否请你写个流水账式的编译过程步骤?
编译指南里的一些步骤我都不太看得懂....

**Comment by cunkai** [comment]
win11 64 位编译成功了 但是后来忙别的忘记步骤了 boots 那个需要点时间 报错都得解决了 可能网络问题啥的吧 忘记了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: terrytw ***@***.***&gt;
发送时间: 2024年9月5日 13:22
收件人: rime/weasel ***@***.***&gt;
抄送: cunkai ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [rime/weasel] 根据文档编译不成功，求个官方编译视频教学~ (Issue #1344)





 
@cunkai 请问你后来编译成功了吗, 能否请你写个流水账式的编译过程步骤?
 编译指南里的一些步骤我都不太看得懂....

**Comment by terrytw** [comment]
@fxliang 请问一下

```
Build succeeded.

"C:\Users\Admin\Desktop\weasel\weasel-master\weasel.sln" (Build target) (1) ->
"C:\Users\Admin\Desktop\weasel\weasel-master\WeaselIME\WeaselIME.vcxproj" (default target) (5) ->
(DoLinkOutputFilesMatch target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1
267,5): warning MSB8012: TargetPath(C:\Users\Admin\Desktop\weasel\weasel-master\Release\weasel.ime) does not match the
Linker's OutputFile property value (C:\Users\Admin\Desktop\weasel\weasel-master\output\weasel.ime). This may cause your
 project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) propert
y values match the value specified in %(Link.OutputFile). [C:\Users\Admin\Desktop\weasel\weasel-master\WeaselIME\Weasel
IME.vcxproj]


"C:\Users\Admin\Desktop\weasel\weasel-master\weasel.sln" (Build target) (1) ->
"C:\Users\Admin\Desktop\weasel\weasel-master\WeaselServer\WeaselServer.vcxproj" (default target) (6) ->
"C:\Users\Admin\Desktop\weasel\weasel-master\RimeWithWeasel\RimeWithWeasel.vcxproj" (default target) (7) ->
(ClCompile target) ->
  C:\Users\Admin\Desktop\weasel\weasel-master\RimeWithWeasel\RimeWithWeasel.cpp(47,1): warning C4996: 'localtime': This
 function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WAR
NINGS. See online help for details. [C:\Users\Admin\Desktop\weasel\weasel-master\RimeWithWeasel\RimeWithWeasel.vcxproj]


"C:\Users\Admin\Desktop\weasel\weasel-master\weasel.sln" (Build target) (1) ->
"C:\Users\Admin\Desktop\weasel\weasel-master\WeaselServer\WeaselServer.vcxproj" (default target) (6) ->
"C:\Users\Admin\Desktop\weasel\weasel-master\WeaselIPCServer\WeaselIPCServer.vcxproj" (default target) (8) ->
  C:\Users\Admin\Desktop\weasel\weasel-master\WeaselIPCServer\WeaselServerImpl.cpp(413,20): warning C4101: 'ex': unrefe
renced local variable [C:\Users\Admin\Desktop\weasel\weasel-master\WeaselIPCServer\WeaselIPCServer.vcxproj]


"C:\Users\Admin\Desktop\weasel\weasel-master\weasel.sln" (Build target) (1) ->
"C:\Users\Admin\Desktop\weasel\weasel-master\WeaselServer\WeaselServer.vcxproj" (default target) (6) ->
  C:\Users\Admin\Desktop\weasel\weasel-master\WeaselServer\SystemTraySDK.cpp(116,1): warning C4996: 'GetVersionExW': wa
s declared deprecated [C:\Users\Admin\Desktop\weasel\weasel-master\WeaselServer\WeaselServer.vcxproj]
  C:\Users\Admin\Desktop\weasel\weasel-master\WeaselServer\SystemTraySDK.cpp(159,1): warning C4996: 'GetVersion': was d
eclared deprecated [C:\Users\Admin\Desktop\weasel\weasel-master\WeaselServer\WeaselServer.vcxproj]

    5 Warning(s)
    0 Error(s)

Time Elapsed 00:00:43.81
Command line defined: "WEASEL_VERSION=0.16.1"
Command line defined: "WEASEL_BUILD=0"
Command line defined: "PRODUCT_VERSION=0.16.1.0"
Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
Processing script file: "output\install.nsi" (UTF8)
!insertmacro: macro "_If" requires 4 parameter(s), passed 2!
Error in script "output\install.nsi" on line 128 -- aborting creation process
error building weasel...
```
这里提到的warning是否正常, 另外error是什么原因, 如何解决呢?

**Comment by fxliang** [comment]
SystemTraySDK里的警告是因为代码里用了一些旧的实现方法未去修改，功能正常但是编译器认为你应该与时俱进修改成现代一点的写法；WeaselServerImpl那个警告是正常的不影响；localtime那个编译器建议是要改localtime_s来解决，但是旧写法问题也不大；至于WeaselIME里的那个是vs项目文件里的设置有几个位置未统一，能用后面有时间再改。

至于构建installer里的错误，是因为你的NSIS版本太旧了，装新的nsis就可以了。

**Comment by terrytw** [comment]
换用新版本NSIS后的确编译成功, 非常感谢解答!

**Comment by terrytw** [comment]
我来写个流水账吧, 帮助一下后来人
1. 安装VS2019 enterprise (include C++, 除了默认勾选的, 要加上MFC), Cmake(3.30.3), python(3.12.5), clang-format(LLVM 18.1.6), NSIS (3.10) and Git for windows (2.46.0). 
2. 打开Git Bash命令行窗口, git clone weasel 项目
3. 把msbuild.exe所在位置(默认/C/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin)和weasel/output加入PATH
4. 下载boost(版本和install_boost.bat一致), 解压放在weasel/deps下
5. 运行./install_boost.bat
6. 运行./github.install.bat
7. 运行./build.bat data
8. 运行./build.bat installer

**Comment by z1gc** [comment]
目前官方提供的安装包，server 版本还是 x64 的，虽然无伤大雅，但是还是更倾向于原生，我稍微修改了一下 https://github.com/z1gc/weasel/commit/8a49b846c503e1cdbdccf3bd12c02709ce5de148，这个版本可以直接在最新的 VS 2022（144.x）下编译通过，方法同 https://github.com/rime/weasel/issues/1344#issuecomment-2333710700 所述，不过需要注意的是我自己的仓库带了一个 patch，clone 仓库后把这个 patch 删了就能编译完整的了。

效果如图：
<img width="509" alt="image" src="https://github.com/user-attachments/assets/dee4d7bd-1575-4d30-8a83-71e33b793c6c">

能够正常在微信中输入。

**Comment by lingmingxi** [comment]
如果有人编译失败了，需要打开vs检查一下报错的文件在哪里，windows编译默认继承了所有的变量，如果你的系统里还有其他的工具链，比如说anaconda3，编译的时候可能会错误的被使用

**Comment by lingmingxi** [comment]
我来写个vs2022流水账吧, 帮助一下后来人


1. 安装VS2022 Community 我的是17.14.25版本(选择C++桌面开发, 除了默认勾选的, 要加上MFC，在右边的c++桌面开发的可选里面找c++ mfc，我是的14.3版本), Cmake(3.31.6-msvc6，安装到默认位置或者在env.bat指定), python(3.12.5), and Git for windows (2.46.0).

     你安装VS2022 Community的时候clang-format(LLVM )会自动帮你装上，你可以看看Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin有没有

2. 打开cmd 运行git clone --recursive --depth 1 https://github.com/rime/weasel.git  克隆库

1. 然后输入bash --version看看是否是git的
  如果报错，添加C:\Program Files\Git\usr\bin到PATH，如果是wsl的bash ，把前面这个路径调整到PATH的最上面

1. 安装最新的 NSIS（3.11） 和boost（1.90.0）,下载地址分别在install_nsis.bat和install_boost.bat。

    niri太老的版本会报
    !insertmacro: macro "_If" requires 4 parameter(s), passed 2!
    Error in script "output\install.nsi" on line 128 -- aborting creation process

1. 把msbuild.exe所在位置(默认C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin)和weasel/output加入PATH

1. 下载boost（1.90.0）, 解压放在weasel/deps下
    boost太老会报错
    don't know how to make <p/L:/shurufa/weasel/dep/boost_1_84_0>D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\Hostx64\vcvarsall.bat

1. 在env vs2019.bat基础上改一下, 重命名为env.bat, 确保boost_root路径正确

```
  rem Customize your build environment and save the modified copy to env.bat
  
  set WEASEL_ROOT=%CD%
  
  rem REQUIRED: path to Boost source directory
  if not defined BOOST_ROOT set BOOST_ROOT=%WEASEL_ROOT%\deps\boost_1_90_0
  
  rem OPTIONAL: architecture, Visual Studio version and platform toolset
  rem set ARCH=Win32
  set BJAM_TOOLSET=msvc-14.3
  set CMAKE_GENERATOR="Visual Studio 17 2022"
  set PLATFORM_TOOLSET=v143
  
  rem OPTIONAL: path to additional build tools
  rem set DEVTOOLS_PATH=%ProgramFiles%\Git\cmd;%ProgramFiles%\Git\usr\bin;%ProgramFiles%\CMake\bin;L:\python\venv;
  
  if not defined WEASEL_BUNDLED_RECIPES set WEASEL_BUNDLED_RECIPES=prelude essay luna-pinyin double-pinyin
```
    其中WEASEL_BUNDLED_RECIPES是指定安装包里输入法用的，详见https://github.com/rime/plum，如果没有这个变量会报错/usr/bin/bash: plum/rime-install: No such file or directory

8. 修改一下build.bat，set build_arm64=1改成0，if %build_rime% == 1 (   这个括号里最后一行添加cd %WEASEL_ROOT%，现在是169行，然后直接./build.bat all就好了，最后在L:\shurufa\weasel\output\archives找到编译后的安装包
9.如果有代码级别的报错，vs打开工程检查一下报错的文件在哪里，windows编译默认继承了所有的PATH，如果你的系统里还有其他的工具链，比如说anaconda3，编译的时候可能会错误的被使用.

**Comment by fxliang** [comment]
不要ARM构建的，只要powershell .\get-rime.ps1 -use dev ;  .\build.bat installer就行 不用改build.bat 的
