### ISSUE TITLE
开启 inline_preedit 后，小狼毫「候选窗口」与「预编辑区」之间位置变化

### ISSUE THREAD

**Issue by sdhdgb** [rime/weasel#1345]
第一次在 Rime 发帖提问，如有不妥之处，请不吝赐教，谢谢了先。

1、 系统信息：
1.1 操作系统: Windows 10 专业版 22H2
1.2 小狼毫版本: 0.15.0.0

2、 前情提要：
2.1 开启 inline_preedit 后，小狼毫在输入时，下方的「候选窗口」始终跟随在上方的「预编辑区」后面，如图1～
当输入较长字符后，编码与候选词之间会产生较大的距离，会影响输入判断和错误修正，感觉不习惯。
2.2 未开启 inline_preedit 时，在小狼毫的候选窗口内，编码与候选词之间是一种类似「左对齐」方式，如图2，习惯这种输入方式打字。
2.3 微软拼音的默认输入方式也类似于开启了“inline_preedit”，在输入文字时，预编辑区与下方的候选窗口采用的也是「左对齐」模式，如图3

3、问题：
在小狼毫开启 inline_preedit （行内显示预编辑区）选项后，如何使其「候选窗口」与「预编辑区」之间采用「左对齐」模式？～类似于未开启 inline_preedit 时的小狼毫，或微软拼音的输入界面。

谢谢！
![图1 开启行内预显示编辑区](https://github.com/user-attachments/assets/1be28021-fc61-4902-8de5-1fd3a01e45fc)

![图2 不开启行内显示预编辑区](https://github.com/user-attachments/assets/67a9f5ca-d38f-4904-80a8-9adb19f7518d)

![图3 微软拼音输入模式](https://github.com/user-attachments/assets/87b720cd-58a0-4a57-83ec-5a544474ca1b)

**Comment by ZeroMapleQvQ** [comment]
建议你更新到小狼毫的最新版本试试,我在[28ace8e](https://github.com/rime/weasel/actions/runs/10155767932/artifacts/1753740577)版本未能成功复现.
