### ISSUE TITLE
Error opening db 'luna_pinyin': IO error: D:\rime\user\luna_pinyin.userdb/LOCK: 拒绝访问。

### ISSUE THREAD

**Issue by Ardea-alba** [rime/weasel#1348]
系统：win11
weasel：0.16.1
第一次安装时自定义了user文件夹的路径，后面卸载重装也没法再改它的路径了。我现在的应用本体是默认路径在c盘，user文件夹在d盘。
现在遇到问题包括新的输入法没有候选词，候选词个数等个性化配置更改后不起作用等。从报错看很可能是user文件夹的问题。是否有办法重新指定user文件夹的路径？
![image](https://github.com/user-attachments/assets/f6722d61-ea9f-4634-a520-20b3d828fde7)

**Comment by changzaicl** [comment]
右键退出“算法服务”，之后就可以删除或暂时移到其他地方。
换user地址，可以到程序文件夹中，打开“weaselSetup”试试
