### ISSUE TITLE
Win11系统横向布局的候选栏不显示

### ISSUE THREAD

**Issue by capedghost** [rime/weasel#1349]
**操作系统信息**
 - OS 详细版本: Windows 11-专业工作站版-23H2-22631.4037
 - 小狼毫版本: 0.16.1.0

**描述遇到的问题**
修改候选栏为横向排列，重启电脑后，打字时不显示候选栏，按空格仍可以上屏第一个候选。

**复现步骤**
1. 安装小狼毫，勾选自带的朙月拼音方案
2. 在weasel.custom.yaml中添加如下图所示配置并重新部署
![image](https://github.com/user-attachments/assets/461004a6-56bd-4646-9a34-95696d7ce41b)
3. 试打，可以正常显示候选栏
![test2](https://github.com/user-attachments/assets/e722dae0-d1d5-4a21-98d0-73a7620b9259)
4. 重启电脑，再进行打字，就不显示候选栏，按空格仍可上屏第一个候选词。尝试重新部署或重启算法服务，均无法恢复正常。
![test3](https://github.com/user-attachments/assets/4c28e69b-78eb-4968-a029-dc3674812628)
5. 删除weasel.custom.yaml中的配置并重新部署，即可正常显示纵向的候选栏，重启电脑后也仍可正常显示候选栏。

**Comment by fxliang** [comment]
patch 后:的节点会被覆盖掉，你可以看看你现有配置下，build/weasel.yaml的内容就明白了。

你这个意图应该写作

```yaml
patch:
  style/horizontal: true
```
