### ISSUE TITLE
托盘图标为白色透明背景，切换方案时，图标无法与背景区分开

### ISSUE THREAD

**Issue by yjnu** [rime/weasel#1351]
## 问题
1. 由微软输入法转过来，想仿微软输入法的托盘图标，于是做了下面两个白字，透明背景的图标。下面有两张中英图标，直接可能看不到，新标签页打开，可以看清。
![ascii_icon_ying](https://github.com/user-attachments/assets/c258ab1a-3615-4acf-9796-f03543992f9d)
![icon_zhong](https://github.com/user-attachments/assets/8361d84d-ab79-40b3-a7e5-03d83c47cc06)

2.  中英切换时，无法与软件白色区分开，由于在全白背景下切换无法显示，下图我在浅色背景下切换的
![中英切换](https://github.com/user-attachments/assets/63cf2a4b-ccb7-46f0-ba54-bab478072c89)

3. 半角全角切换，简繁切换，中英标点符号切换，无法与 rime 自带的白色背景区分开
![半角全角切换](https://github.com/user-attachments/assets/690f53c6-6fc1-4f0b-a0b9-841ce8c8feb1)
![简繁切换](https://github.com/user-attachments/assets/159f304c-34db-4b8d-aba5-31adbe215759)

## 改进建议
1. schema 里增加一项 icon_background_color，自定义背景色，如不设置，默认为白色
2. 中英切换，现在是直接显示图标，建议增加背景色，背景色所画区域正好是图标大小（不影响正常有背景色的图标显示），背景色色值由建议一里面的配置项设置。

**Comment by fxliang** [comment]
那为什么不直接做一个不是透明背景的icon，或者透明背景但是对比度足够的icon，或者设置一个暗色的背景呢？要知道微软这个白色的icon也是配合暗色的背景色的场景来用的。而且……您现在这个的状态下文字和背景色都是白色这个是认真的嘛……

完全不敢想象的是白色的背景候选框中套一个黑色（或者蓝色绿色黄色等）的背景块上面再绘制一个白色前景的icon会是多么的难看

透明背景的纯色前景图显示就意味着一个对比度不明确的光学表达，只有明确了背景色和前景色的对比度足够才能保证足够的对比度，这个是光学问题。

**Comment by yjnu** [comment]
1. 回复如此傲慢啊，直接关问题。下图是正常在托盘的显示状态。
![托盘显示状态](https://github.com/user-attachments/assets/2eba09a7-166a-48e7-8a20-460194d640b3)

2.  我提问题肯定是展示有问题的部分，展示好的怎么说问题。

3. 自带的白底黑字矩形比文字直接融入任务栏好看？我说了我的建议，您就往难看的配色上去想，这是解决问题的态度，不是加重矛盾？我在图标中加了背景色，任务栏中就只能显示方正的图标，因为没有背景色，图标又是白色的，rime 切换方案只显示图标或背景色固定是白色，所以希望加个背景色配置项。

**Comment by fxliang** [comment]
您提了建议，作为目前唯一的活跃维护，我评估过您的建议，认为不计划采纳该建议，于是以not planned 为由关闭issue。而且我原回复还用了敬语表达“您”。。。如果您会觉得不采纳您提的建议就是傲慢，好吧

您可以提目前状态下极端有问题的状态，我不能指出您建议采纳后的极端情况，是这样吗？

你知道白色前景在暗色任务栏中显示好看，又有没有切换到浅色背景看看情况？应该看不清吧？

您说我往极端的去想，您试画一个白色背景然后用您这个白字透明背景的png加个任意单色方块颜色任选出个好看的效果图，ppt来画或者画图板出个能看不丑的就行。试试看我是不是真的往极端的想了。

我猜想您是想在暗色背景的系统设定下，又想用浅色的输入法背景，所以就发现任务栏和候选栏的icon无法调和了。试下我提的建议，比如用暗色的背景色，或者在icon图形周边（文字笔划）加一个深色的shadow是不是有机会对比度上去了又在任务栏中又好看呢？
