### ISSUE TITLE
text_color 影响范围

### ISSUE THREAD

**Issue by yjnu** [rime/weasel#1356]
## 问题原因
根据给的教程图（下图），打字时，我用不到 text_color，我还不想显示字母右小角的“^”，经测试发现，text_color 与 back_color 为一个色值时就不会显示“^”。

![Pasted image 20240723102916](https://github.com/user-attachments/assets/9f5ef081-2756-4451-8766-ea2c2d6c41d0)

设置好后的显示效果，见下图

![Screenshot_2024-08-26_22-55-01](https://github.com/user-attachments/assets/a435971c-f062-42ce-ba64-cd532afa6b0e)

使用时发现方案切换的提示框，文字与背景分别用的就是 text_color 与 back_color，同色就看不到提示信息，见下图

![Screenshot_2024-08-26_22-43-29](https://github.com/user-attachments/assets/81759933-37b4-449d-a87a-2fcc2ff90f3a)

## 解决建议

1. 切换方案的文字颜色可以用候选第一个的字体色 hilited_candidate_text_color，或者 “^” 单独用一种颜色。

**Comment by fxliang** [comment]
lua/disable_soft_cursor.lua
```lua
local function disable_soft_cursor(key, env)
	local engine = env.engine
	local context = engine.context
  local soft_cursor = context:get_option("soft_cursor")
  if soft_cursor == nil or soft_cursor == true then
    context:set_option("soft_cursor", false)
  end
  return 2
end

return { func = disable_soft_cursor }
```

方案patch

```yaml
patch:
  engine/processors/+:
    - lua_processor@*disable_soft_cursor
````
![image](https://github.com/user-attachments/assets/efd173c5-4e37-4dae-b8a8-023691150452)

**Comment by yjnu** [comment]
感谢您的细致回复，已解决，学习了，给您赞助了一杯奶茶，心意虽小，但诚意满满。

**Comment by fxliang** [comment]
谢谢老板
