### ISSUE TITLE
0.10.0.0在ie上的问题

### ISSUE THREAD

**Issue by rimefans** [rime/weasel#136]
环境：32位win8.1下IE
在地址栏可以正常输入中文，但是在网页如百度则不能正常输入中文，小狼毫会直接输入编码。环境如下：
![qq 20180315165233](https://user-images.githubusercontent.com/15376679/37453011-5da0f114-2871-11e8-8827-8750e07c995f.png)
![qq 20180315165258](https://user-images.githubusercontent.com/15376679/37453012-5dfb7e0e-2871-11e8-99b5-a6e127d7dfa4.png)

**Comment by Prcuvu** [comment]
使用的是 IME 还是 TSF？

**Comment by rimefans** [comment]
没有打开安全模式。
用的是TSF

**Comment by nameoverflow** [comment]
不知道和 #129 有没有关系

**Comment by hosxy** [comment]
这个问题我也有
我是系统是 win10 1709 同样是 TFS 模式

**Comment by nameoverflow** [comment]
测试了一下，Windows 10 下只有在打开保护模式时才能复现这个问题。
![image](https://user-images.githubusercontent.com/10287709/37715068-ff46acfa-2d55-11e8-92de-d477ad323657.png)

**Comment by rimefans** [comment]
是的，打开了安全模式。退出安全模式之后，就能正常地输入中文了
