### ISSUE TITLE
ESET的保护所有浏览器和小狼毫冲突

### ISSUE THREAD

**Issue by z19961225** [rime/weasel#1362]
**操作系统信息**
 - OS 详细版本: 
       OS 名称:          Microsoft Windows 11 专业工作站版
       OS 版本:          10.0.22621 暂缺 Build 22621
 - 小狼毫版本: 
       0.16.1.41.9275283 

**描述遇到的问题**
    如果开启ESET杀软的  安全银行业务和浏览-保护所有浏览器则会导致小狼毫在所有浏览器中无法使用

**复现步骤**
重现问题的步骤，如：
1. 打开 'ESET' 软件
2. 开启保护所有浏览器
![image](https://github.com/user-attachments/assets/2d094580-dd87-456a-8566-9194958e472a)

4. 运行Chrome，当Chrome出现ESET的绿框时，表示该浏览器在安全模式下，这时候就无法使用小狼毫了
![image](https://github.com/user-attachments/assets/b5f12a34-ace6-4305-98a1-a44513dc33f7)

6. 遇到了 '...' 问题

**预期行为**
简短地描述你预期小狼毫怎么反馈

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by AoThen** [comment]
https://github.com/rime/weasel/issues/929#issuecomment-2163161968
