### ISSUE TITLE
输入法改进建议

### ISSUE THREAD

**Issue by freesoft0000** [rime/weasel#137]
1、配置可以gui话，这个估计很多人都提过了。如果配置能界面话更好。比较很多人都不懂怎么自己去修改配置文件。

2、安装可以在一个界面完成，这样更符合大众一般化。目前的安装过程中会弹出一个子窗口，需要用户确认才可以下一步，安装位置什么的都可以在一个界面完成，符合微软的习惯，傻瓜化，下一步、下一步...就可以了。另外，现在应该支持带参数静默安装吧？

3、安装后第一次重启电脑会提示是否自动更新输入法，我不知道其他人的习惯，我个人是一般更新都是禁用的。这个如果可以在安装的时候有设置就好了，省的重启后再设置。

**Comment by freesoft0000** [comment]
4、目前官方帮助文档比较简陋。如果可以随安装包附带使用和谁知教程就好了。最好是pdf或者chm格式的。方便离线用户使用。比较很多人对这个输入法还不熟悉。

**Comment by nameoverflow** [comment]
目前没有计划，欢迎贡献代码。

**Comment by freesoft0000** [comment]
水平没有到呀。如果有能力很愿意添砖加瓦，心有余力不足呀。

**Comment by lotem** [comment]
感謝提出建議。

配置方式之前多有討論，圖形界面主要是沒資源做，也難以完全實現配置文件所提供的靈活性。目前確定的方向是通過開發配置管理器，讓用戶更方便地分享輸入方案及配置。

安裝程序是基於 NSIS 開發，把設置嵌入安裝嚮導界面，開發的工作量要大一些。目前也沒有資源做這類錦上添花的改進。此外，獨立的設置程序方便在安裝後直接運行修改設置。

靜默安裝加命令行參數 `/S`

詢問自動更新按照業界慣例是在軟件第一次使用時。「被安裝」而從不使用就不會問。
