### ISSUE TITLE
0.16.2 新功能weaselSetup.exe /release似乎无效

### ISSUE THREAD

**Issue by dawnray** [rime/weasel#1375]
**上报前请检查**
- [ ☑︎] 我遇到的问题没有其他人在 issue 里提到过
- [ ☑︎] 我的小狼毫版本于 rime/weasel 下载
- [ ☑︎] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 19045.4894
 - 小狼毫版本:  0.16.2.0 

**描述遇到的问题**
使用weaselSetup /release设置更新只获取release版本无效。

**复现步骤**
重现问题的步骤：
1. 在程序文件夹，命令行输入weaselSetup.exe /release
2. 授权允许系统变更
3. 进行 '检查新版本' 操作
4. 遇到了 '返回Nightly Build版本为最新版本，并建议更新' 问题

**预期行为**
应当判断当前最新release版本与安装版本一直，不提示更新

**用户文件**
无

**截图**
![image](https://github.com/user-attachments/assets/5391ebcf-4bf7-49b7-b7a9-6d65dc39ce55)

![image](https://github.com/user-attachments/assets/0fcd6d6c-698f-4c6c-a860-f371c985de74)

**其他补充说明**
无

**Comment by fxliang** [comment]
这个功能上线有些时候了，只是testing channel中的人都没有提过，所以确实是有问题，有个字符串有问题，已修复
