### ISSUE TITLE
Windows Defender 报毒 “Trojan:Win32/Critet.BS”

### ISSUE THREAD

**Issue by dgeibi** [rime/weasel#138]
<img width="418" alt="default" src="https://user-images.githubusercontent.com/2224764/37468322-ab57f494-289d-11e8-8093-335bc69006ff.PNG">

相关链接
[Threat descriptions search results - Windows Defender Security Intelligence](https://www.microsoft.com/en-us/wdsi/threats/threat-search?query=trojan:win32/critet.bs&2147726294&page=1&showall=false&sortby=relevance&sortdir=desc&size=10)
[Trojan:Win32/Critet.BS - Technical Support (PC, unmodded installs) - Kerbal Space Program Forums](https://forum.kerbalspaceprogram.com/index.php?/topic/172357-trojanwin32critetbs/)

**Comment by Prcuvu** [comment]
![image](https://user-images.githubusercontent.com/7923857/37470103-bb0e90a6-28a1-11e8-868b-24acc4854cb9.png)
无法重现。请试着更新 Windows Defender 病毒定义。

**Comment by codingnemo** [comment]
有趣的是，Avira 也报毒：ADWARE/FileFinder.Gen7
具体说明页面：https://www.avira.com/zh-cn/support-threats-summary-product?tid=147821&threat=ADWARE&track=1
看描述似乎被怀疑为含有广告？！

**Comment by dgeibi** [comment]
更新完就不会报了

**Comment by jtain** [comment]
我的 avast 也報毒
