### ISSUE TITLE
0.16.3版本如何设置开机自动同步用户词库？

### ISSUE THREAD

**Issue by cqwnjsdc2212** [rime/weasel#1382]
此前一直使用windows自带的任务计划程序，每次开机计划启动一次小狼毫同步程序WeaselDeployer.exe
[https://www.expoli.tech/articles/2024/05/01/Rime-Xiaolanghao-timing-user%20dictionary-synchronization-settings](url)
但刚刚更新0.16.3后，打开程序文件夹中的WeaselDeployer.exe会出现输入法方案选单
![ascnbhzbxchasc](https://github.com/user-attachments/assets/e79b26b3-eeb7-487b-8477-17f0a17b9ee6)
启动WeaselDeployer.exe不会同步用户词库，不清楚是不是bug，大家都遇到了吗

**Comment by fxliang** [comment]
这个一直没有变化过，计划任务里面用`WeaselDeployer.exe /sync`即可（保证在path里或者用exe的全路径）
