### ISSUE TITLE
win11 24H2 並升級weasel 0.16.3(3c70aed)出現偶然打字不編碼直接英文字母輸出

### ISSUE THREAD

**Issue by sheaahhoi1** [rime/weasel#1383]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建
- [x]我從weasel 0.16.1進行方案編寫固定使用一段時間,無發生任何問題,前天升級weasel 0.16.3才出現

**操作系统信息**
 - OS 详细版本: [ 运行 winver.exe 获取，如 Windows 11 24H2 26100.1882]
 - 小狼毫版本: [ 如 0.16.3 ， CI 构建版请附短 commit hash ， 3c70aed ]

**描述遇到的问题**
简短地描述你所遇到的问题

**复现步骤**
重现问题的步骤，如：
1. 打开 '任何' 软件
2. 输入 '...'
3. 进行 '中文輸入法' 操作
4. 遇到了 '首碼直出,沒有進行編碼處理' 问题
以下偶發出現沒有辦法確定因素
打字偶發性打不編碼直接進行英文字母輸出
1.ascii_mode切換/
2.CTRL+V貼上英文接著打中文j木字,
3.連續輸入中文也會偶然出現中途不拆碼例如上句"j木"直接輸出英文字

**预期行为**
简短地描述你预期小狼毫怎么反馈
任何應該進行編碼,而不是第一個是英文字母之後再進行編碼,

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

[user_setting.zip](https://github.com/user-attachments/files/17286923/user_setting.zip)
請把m卜下列帶有.zXX.zip的.zip刪除因為是分割檔案原副檔案名是Z01~Z06,不能上傳
[user_setting.z01.zip](https://github.com/user-attachments/files/17286927/user_setting.z01.zip)
[user_setting.z02.zip](https://github.com/user-attachments/files/17286928/user_setting.z02.zip)
[user_setting.z03.zip](https://github.com/user-attachments/files/17286929/user_setting.z03.zip)
[user_setting.z04.zip](https://github.com/user-attachments/files/17286930/user_setting.z04.zip)
[user_setting.z05.zip](https://github.com/user-attachments/files/17286931/user_setting.z05.zip)
[user_setting.z06.zip](https://github.com/user-attachments/files/17286932/user_setting.z06.zip)

**截图**
如果问题需要，可附上 GIF 图片
![QQ20241008-113845_結果](https://github.com/user-attachments/assets/6efcf8d9-4dff-4ff2-986f-f0a2adbd9684)

**其他补充说明**
如果有其他补充说明，可以写在这里
我weasel 0.16.1進行輸入操作正常,但在weasel 0.16.3出現錯誤

**Comment by fxliang** [comment]
别打包build的内容……

**Comment by Mythologyli** [comment]
有可能是系统的问题，我用搜狗输入法也会出现此种现象

系统 26100.2033

**Comment by myonlylonely** [comment]
我用搜狗输入法也是同样的问题

**Comment by m2nlight** [comment]
偶尔还会输入不出字，导致所在程序崩溃

**Comment by fxliang** [comment]
如果是系统性的问题就等Windows修复咯（

**Comment by LIXiangChen** [comment]
系统问题, 搜狗同, 这是其他人发的: https://answers.microsoft.com/zh-hans/windows/forum/all/windows11/85892fa6-cda9-467b-a633-b5ab6f1f098e
但是系统的反馈中心里似乎还没看到此问题的反馈

**Comment by myonlylonely** [comment]
@LIXiangChen 解决方法：打开触摸键盘1次再关闭，恢复正常了。

**Comment by sheaahhoi1** [comment]
該問題已知任何地方(程式/介面)/任何鍵盤輸入法包括微軟親兒子輸入法也出現

**Comment by Mythologyli** [comment]
https://answers.microsoft.com/zh-hans/windows/forum/windows_11-wintop_language/windows11/85892fa6-cda9-467b-a633-b5ab6f1f098e?messageId=c170f9a7-3629-49a1-a087-2fdd5cbbc23c

**Comment by BH2WFR** [comment]
**简体中文输入法下**还会有另一种问题, 触发方式相同, 但是表现形式不是直接上屏, 
而是在光标处出现一个黑色的框, 打出的字符都在框中, 且不论按esc 还是 enter 都无法上屏, 无法关闭.

不论是在中文模式, 还是在英文模式, 都会触发此问题. 尤其是在**英文模式下**, 此问题发作时, 输入字母会在光标处**弹出黑框**, **输入标点时会输出全角标点符号** (且不是小狼毫中symbols.yaml定义的标点符号, 而更像微软拼音输入法中的全角标点符号)

**Comment by Mythologyli** [comment]
> **简体中文输入法下**还会有另一种问题, 触发方式相同, 但是表现形式不是直接上屏, 
> 而是在光标处出现一个黑色的框, 打出的字符都在框中, 且不论按esc 还是 enter 都无法上屏, 无法关闭.
> 
> 不论是在中文模式, 还是在英文模式, 都会触发此问题. 尤其是在**英文模式下**, 此问题发作时, 输入字母会在光标处**弹出黑框**, **输入标点时会输出全角标点符号** (且不是小狼毫中symbols.yaml定义的标点符号, 而更像微软拼音输入法中的全角标点符号)
> 
> 我的另一台 windows 11 23H2 电脑则没有这个问题. 此问题出现的电脑在两个月前刚刚升级了 windows 11 24H2, 且刚升级的时候也没有问题, 自从安装了某个补丁以后就开始出现这个问题了.
> 
> 
> 
> 

这是应该也是微软的问题，我用的搜狗，我经常在写代码的时候遇到。靠开一次触摸键盘也能暂时解决

**Comment by BH2WFR** [comment]
唉, Micro$oft 真是太伟大了

**Comment by MoonLord-LM** [comment]
[默认中文输入法打字第一个字首字母会以英文形式出现](https://answers.microsoft.com/zh-hans/windows/forum/all/%E9%BB%98%E8%AE%A4%E4%B8%AD%E6%96%87%E8%BE%93/b09b31f5-5133-4fa4-8659-ad2694c99c63?page=3)

**Comment by fweiger** [comment]
> https://answers.microsoft.com/zh-hans/windows/forum/windows_11-wintop_language/windows11/85892fa6-cda9-467b-a633-b5ab6f1f098e?messageId=c170f9a7-3629-49a1-a087-2fdd5cbbc23c
> 
> > 感谢提供方法和思路
> > 在此基础上我研究这个问题应该是
> > C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy里的TextInputHost.exe引发
> > 只重命名此文件即可解决 非常感谢！
> > 不过经朋友测试后发现（因为我已经重装了系统） 重命名TextInputHost.exe会使win+v和win+。的两个功能失效
> > 不知道还会不会有更多副作用 还是请官方积极重视此问题 尽快解决

TextInputHost 这个文件被重命名之后 会出现鼠标卡顿的情况  桌面的进程占用cpu的问题在我的电脑中
