### ISSUE TITLE
OneDrive同步问题

### ISSUE THREAD

**Issue by WvvvWv** [rime/weasel#1391]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Win11 24H2 26100.2033
 - 小狼毫版本: 0.16.3

**描述遇到的问题**
无法使用OneDrive下的目录作为同步文件夹

**复现步骤**
重现问题的步骤，如：
1. 打开用户文件夹，修改installation.yaml里的同步目录为OneDrive的Rime同步目录。
2. 右击小狼毫托盘图标，点击重新部署
3. 此时installation.yaml内容变为默认内容

截图：
首次修改的截图
![Clip_2024-10-13_15-29-44](https://github.com/user-attachments/assets/9f0136b0-202e-49f0-a6c2-77d9c6ab5eae)

点击重新部署后的截图
![Clip_2024-10-13_15-30-46](https://github.com/user-attachments/assets/2a6260a0-787c-4898-a82e-7f6399eab6db)
![Clip_2024-10-13_15-30-54](https://github.com/user-attachments/assets/3590fec6-63d6-4034-a01f-83477bcf7947)

日志：
`Log file created at: 2024/10/13 15:30:33
Running on machine: WIN-SU1JEB8F354
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
I20241013 15:30:33.475344 10180 core_module.cc:20] registering core components.
I20241013 15:30:33.476649 10180 registry.cc:14] registering component: config_builder
I20241013 15:30:33.476656 10180 registry.cc:14] registering component: config
I20241013 15:30:33.476660 10180 registry.cc:14] registering component: schema
I20241013 15:30:33.476663 10180 registry.cc:14] registering component: user_config
I20241013 15:30:33.476667 10180 dict_module.cc:25] registering components from module 'dict'.
I20241013 15:30:33.476670 10180 registry.cc:14] registering component: tabledb
I20241013 15:30:33.476673 10180 registry.cc:14] registering component: stabledb
I20241013 15:30:33.476675 10180 registry.cc:14] registering component: plain_userdb
I20241013 15:30:33.476678 10180 registry.cc:14] registering component: userdb
I20241013 15:30:33.476682 10180 registry.cc:14] registering component: corrector
I20241013 15:30:33.476686 10180 registry.cc:14] registering component: dictionary
I20241013 15:30:33.476690 10180 registry.cc:14] registering component: reverse_lookup_dictionary
I20241013 15:30:33.476694 10180 registry.cc:14] registering component: user_dictionary
I20241013 15:30:33.476697 10180 registry.cc:14] registering component: userdb_recovery_task
I20241013 15:30:33.476702 10180 levers_module.cc:22] registering components from module 'levers'.
I20241013 15:30:33.476704 10180 registry.cc:14] registering component: detect_modifications
I20241013 15:30:33.476707 10180 registry.cc:14] registering component: installation_update
I20241013 15:30:33.476710 10180 registry.cc:14] registering component: workspace_update
I20241013 15:30:33.476712 10180 registry.cc:14] registering component: schema_update
I20241013 15:30:33.476715 10180 registry.cc:14] registering component: config_file_update
I20241013 15:30:33.476717 10180 registry.cc:14] registering component: prebuild_all_schemas
I20241013 15:30:33.476720 10180 registry.cc:14] registering component: user_dict_upgrade
I20241013 15:30:33.476723 10180 registry.cc:14] registering component: cleanup_trash
I20241013 15:30:33.476725 10180 registry.cc:14] registering component: user_dict_sync
I20241013 15:30:33.476728 10180 registry.cc:14] registering component: backup_config_files
I20241013 15:30:33.476731 10180 registry.cc:14] registering component: clean_old_log_files
I20241013 15:30:33.498425 10180 deployment_tasks.cc:85] updating rime installation info.
I20241013 15:30:33.498497 10180 config_data.cc:72] loading config file 'F:\Rime\installation.yaml'.
E20241013 15:30:33.498703 10180 config_data.cc:77] Error parsing YAML: yaml-cpp: error at line 7, column 24: bad character found while scanning hex number
I20241013 15:30:33.499565 10180 deployment_tasks.cc:131] creating installation info.
I20241013 15:30:33.499657 10180 deployment_tasks.cc:138] generated installation id: e147d120-3052-4e52-8303-8cd5e99c3bad
I20241013 15:30:33.499663 10180 config_data.cc:201] write: installation_id
I20241013 15:30:33.499673 10180 config_data.cc:201] write: install_time
I20241013 15:30:33.499681 10180 config_data.cc:201] write: distribution_name
I20241013 15:30:33.499685 10180 deployment_tasks.cc:148] distribution: 小狼毫
I20241013 15:30:33.499688 10180 config_data.cc:201] write: distribution_code_name
I20241013 15:30:33.499692 10180 deployment_tasks.cc:153] distribution code name: Weasel
I20241013 15:30:33.499694 10180 config_data.cc:201] write: distribution_version
I20241013 15:30:33.499698 10180 deployment_tasks.cc:157] distribution version: 0.16.3
I20241013 15:30:33.499701 10180 config_data.cc:201] write: rime_version
I20241013 15:30:33.499704 10180 deployment_tasks.cc:160] Rime version: 1.11.2
I20241013 15:30:33.499707 10180 config_data.cc:91] saving config file 'F:\Rime\installation.yaml'.
I20241013 15:30:33.500088 10180 deployment_tasks.cc:165] updating workspace.
I20241013 15:30:33.500177 10180 config_data.cc:72] loading config file 'H:\Program\Rime\weasel-0.16.3\data\default.yaml'.
I20241013 15:30:33.500488 10180 config_data.cc:72] loading config file 'F:\Rime\default.yaml'.
I20241013 15:30:33.501582 10180 config_data.cc:72] loading config file 'F:\Rime\build\default.yaml'.
I20241013 15:30:33.503153 10180 config_data.cc:72] loading config file 'F:\Rime\build\default.yaml'.
I20241013 15:30:33.504542 10180 deployment_tasks.cc:188] updating schemas.
I20241013 15:30:33.504550 10180 deployment_tasks.cc:197] schema: rime_ice
I20241013 15:30:33.504606 10180 config_data.cc:72] loading config file 'F:\Rime\rime_ice.schema.yaml'.
I20241013 15:30:33.506422 10180 config_data.cc:72] loading config file 'F:\Rime\build\rime_ice.schema.yaml'.
I20241013 15:30:33.517588 10180 config_data.cc:72] loading config file 'F:\Rime\build\rime_ice.schema.yaml'.
I20241013 15:30:33.528445 10180 deployment_tasks.cc:360] preparing dictionary 'rime_ice'.
I20241013 15:30:33.528511 10180 dict_compiler.cc:81] compiling dictionary for F:\Rime\build\rime_ice.schema.yaml
I20241013 15:30:33.784832 10180 table.cc:254] loading table file: F:\Rime\build\rime_ice.table.bin
I20241013 15:30:33.791407 10180 prism.cc:76] loading prism file: F:\Rime\build\rime_ice.prism.bin
I20241013 15:30:33.791478 10180 prism.cc:106] found double array image of size 2304.
I20241013 15:30:33.791494 10180 dict_compiler.cc:126] F:\Rime\rime_ice.dict.yaml[6 file(s)] (1896831611)
I20241013 15:30:33.791500 10180 dict_compiler.cc:128] F:\Rime\build\rime_ice.schema.yaml (4052411494)
I20241013 15:30:33.791530 10180 reverse_lookup_dictionary.cc:33] loading reversedb: F:\Rime\build\rime_ice.reverse.bin
I20241013 15:30:33.791678 10180 deployment_tasks.cc:377] dictionary 'rime_ice' is ready.
I20241013 15:30:33.792382 10180 config_data.cc:72] loading config file 'F:\Rime\build\rime_ice.schema.yaml'.
I20241013 15:30:33.803140 10180 deployment_tasks.cc:197] schema: melt_eng
I20241013 15:30:33.803264 10180 config_data.cc:72] loading config file 'F:\Rime\melt_eng.schema.yaml'.
I20241013 15:30:33.804152 10180 config_data.cc:72] loading config file 'F:\Rime\build\melt_eng.schema.yaml'.
I20241013 15:30:33.806270 10180 config_data.cc:72] loading config file 'F:\Rime\build\melt_eng.schema.yaml'.
I20241013 15:30:33.808268 10180 deployment_tasks.cc:360] preparing dictionary 'melt_eng'.
I20241013 15:30:33.808323 10180 dict_compiler.cc:81] compiling dictionary for F:\Rime\build\melt_eng.schema.yaml
I20241013 15:30:33.810772 10180 table.cc:254] loading table file: F:\Rime\build\melt_eng.table.bin
I20241013 15:30:33.810937 10180 prism.cc:76] loading prism file: F:\Rime\build\melt_eng.prism.bin
I20241013 15:30:33.810976 10180 prism.cc:106] found double array image of size 647936.
I20241013 15:30:33.810993 10180 dict_compiler.cc:126] F:\Rime\melt_eng.dict.yaml[3 file(s)] (299416012)
I20241013 15:30:33.810997 10180 dict_compiler.cc:128] F:\Rime\build\melt_eng.schema.yaml (589482259)
I20241013 15:30:33.811022 10180 reverse_lookup_dictionary.cc:33] loading reversedb: F:\Rime\build\melt_eng.reverse.bin
I20241013 15:30:33.811189 10180 deployment_tasks.cc:377] dictionary 'melt_eng' is ready.
I20241013 15:30:33.811238 10180 deployment_tasks.cc:197] schema: radical_pinyin
I20241013 15:30:33.811278 10180 config_data.cc:72] loading config file 'F:\Rime\radical_pinyin.schema.yaml'.
I20241013 15:30:33.812165 10180 config_data.cc:72] loading config file 'F:\Rime\build\radical_pinyin.schema.yaml'.
I20241013 15:30:33.813439 10180 deployment_tasks.cc:421] source file changed: F:\Rime\radical_pinyin.schema.yaml
I20241013 15:30:33.813502 10180 config_data.cc:72] loading config file 'F:\Rime\radical_pinyin.schema.yaml'.
I20241013 15:30:33.814451 10180 auto_patch_config_plugin.cc:29] auto-patch radical_pinyin.schema:/__patch: radical_pinyin.custom:/patch?
W20241013 15:30:33.814458 10180 config_compiler.cc:527] circular dependencies detected in radical_pinyin.schema:
W20241013 15:30:33.814482 10180 config_compiler.cc:367] accessing blocking node with unresolved dependencies: radical_pinyin.schema:
I20241013 15:30:33.814910 10180 config_compiler.cc:537] resolved: Include(radical_pinyin.schema:algebra_pinyin)
I20241013 15:30:33.814917 10180 config_compiler.cc:537] resolved: PendingChild(radical_pinyin.schema:/speller/algebra)
I20241013 15:30:33.814920 10180 config_compiler.cc:537] resolved: PendingChild(radical_pinyin.schema:/speller)
W20241013 15:30:33.815008 10180 config_data.cc:69] nonexistent config file 'F:\Rime\radical_pinyin.custom.yaml'.
I20241013 15:30:33.815023 10180 config_compiler.cc:426] optional resource not loaded: radical_pinyin.custom
I20241013 15:30:33.815027 10180 config_compiler.cc:537] resolved: Patch(radical_pinyin.custom:patch <optional>)
I20241013 15:30:33.815060 10180 config_data.cc:72] loading config file 'F:\Rime\default.yaml'.
I20241013 15:30:33.816262 10180 auto_patch_config_plugin.cc:29] auto-patch default:/__patch: default.custom:/patch?
I20241013 15:30:33.816324 10180 config_data.cc:72] loading config file 'F:\Rime\default.custom.yaml'.
I20241013 15:30:33.816437 10180 config_compiler.cc:214] patching schema_list
I20241013 15:30:33.816446 10180 config_compiler.cc:537] resolved: Patch(default.custom:patch <optional>)
I20241013 15:30:33.816453 10180 legacy_preset_config_plugin.cc:26] interpreting key_binder/import_preset: default
I20241013 15:30:33.816460 10180 legacy_preset_config_plugin.cc:52] interpreting punctuator/import_preset: default
I20241013 15:30:33.816466 10180 legacy_preset_config_plugin.cc:65] interpreting recognizer/import_preset: default
I20241013 15:30:33.816496 10180 build_info_plugin.cc:27] resource 'radical_pinyin.custom' not loaded.
I20241013 15:30:33.816510 10180 config_data.cc:91] saving config file 'F:\Rime\build\radical_pinyin.schema.yaml'.
I20241013 15:30:33.817479 10180 config_data.cc:72] loading config file 'F:\Rime\build\radical_pinyin.schema.yaml'.
I20241013 15:30:33.818683 10180 deployment_tasks.cc:360] preparing dictionary 'radical_pinyin'.
I20241013 15:30:33.818746 10180 dict_compiler.cc:81] compiling dictionary for F:\Rime\build\radical_pinyin.schema.yaml
I20241013 15:30:33.822208 10180 table.cc:254] loading table file: F:\Rime\build\radical_pinyin.table.bin
I20241013 15:30:33.822403 10180 prism.cc:76] loading prism file: F:\Rime\build\radical_pinyin.prism.bin
I20241013 15:30:33.822444 10180 prism.cc:106] found double array image of size 80896.
I20241013 15:30:33.822459 10180 dict_compiler.cc:126] F:\Rime\radical_pinyin.dict.yaml[1 file(s)] (410032804)
I20241013 15:30:33.822463 10180 dict_compiler.cc:128] F:\Rime\build\radical_pinyin.schema.yaml (60947361)
I20241013 15:30:33.822489 10180 reverse_lookup_dictionary.cc:33] loading reversedb: F:\Rime\build\radical_pinyin.reverse.bin
I20241013 15:30:33.822761 10180 deployment_tasks.cc:377] dictionary 'radical_pinyin' is ready.
I20241013 15:30:33.823115 10180 deployment_tasks.cc:245] finished updating schemas: 3 success, 0 failure.
I20241013 15:30:33.823159 10180 config_data.cc:72] loading config file 'F:\Rime\user.yaml'.
I20241013 15:30:33.823249 10180 config_data.cc:201] write: var/last_build_time
I20241013 15:30:33.823257 10180 config_data.cc:91] saving config file 'F:\Rime\user.yaml'.
I20241013 15:30:33.823532 10180 deployment_tasks.cc:583] clean up trash.
I20241013 15:30:33.824071 10180 config_data.cc:72] loading config file 'H:\Program\Rime\weasel-0.16.3\data\weasel.yaml'.
I20241013 15:30:33.826471 10180 config_data.cc:72] loading config file 'F:\Rime\weasel.yaml'.
I20241013 15:30:33.829442 10180 config_data.cc:72] loading config file 'F:\Rime\build\weasel.yaml'.
`

**Comment by WvvvWv** [comment]
补充一点，我将目录换成其他盘符可以正常同步

**Comment by WindyValley** [comment]
E20241013 15:30:33.498703 10180 config_data.cc:77] Error parsing YAML: yaml-cpp: error at line 7, column 24: bad character found while scanning hex number
你把路径分隔符换成'\\'或者'/'试试，应该是奇怪的转义问题

**Comment by WvvvWv** [comment]
> E20241013 15:30:33.498703 10180 config_data.cc:77] Error parsing YAML: yaml-cpp: error at line 7, column 24: bad character found while scanning hex number 你把路径分隔符换成'\'或者'/'试试，应该是奇怪的转义问题

好奇怪，我今天到公司用另一台电脑同步成功了，两天设备onedrive区别就是一个是默认c盘目录（同步失败），另一台我改了d盘（同步成功）。

**Comment by WindyValley** [comment]
> > E20241013 15:30:33.498703 10180 config_data.cc:77] Error parsing YAML: yaml-cpp: error at line 7, column 24: bad character found while scanning hex number 你把路径分隔符换成'\'或者'/'试试，应该是奇怪的转义问题
> 
> 好奇怪，我今天到公司用另一台电脑同步成功了，两天设备onedrive区别就是一个是默认c盘目录（同步失败），另一台我改了d盘（同步成功）。

是\Adm这里的转义异常，跟前面盘符没关系

**Comment by WvvvWv** [comment]
> > > E20241013 15:30:33.498703 10180 config_data.cc:77] Error parsing YAML: yaml-cpp: error at line 7, column 24: bad character found while scanning hex number 你把路径分隔符换成''或者'/'试试，应该是奇怪的转义问题
> > 
> > 
> > 好奇怪，我今天到公司用另一台电脑同步成功了，两天设备onedrive区别就是一个是默认c盘目录（同步失败），另一台我改了d盘（同步成功）。
> 
> 是\Adm这里的转义异常，跟前面盘符没关系

ok，我晚上回去再试试

**Comment by WvvvWv** [comment]
> > > E20241013 15:30:33.498703 10180 config_data.cc:77] Error parsing YAML: yaml-cpp: error at line 7, column 24: bad character found while scanning hex number 你把路径分隔符换成''或者'/'试试，应该是奇怪的转义问题
> > 
> > 
> > 好奇怪，我今天到公司用另一台电脑同步成功了，两天设备onedrive区别就是一个是默认c盘目录（同步失败），另一台我改了d盘（同步成功）。
> 
> 是\Adm这里的转义异常，跟前面盘符没关系

搞定了，win盘符\改成\\就可以了，多谢
