### ISSUE TITLE
使用多个 xxx/@before n格式的patch时,只会插入一项

### ISSUE THREAD

**Issue by iamqiz** [rime/weasel#1392]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**描述遇到的问题**
简短地描述你所遇到的问题

想在某个列表元素(比如最后一个last)前面插入多个元素, 所以使用了`@before last`, 配置如下
```
patch:
  engine/translators/@before last: "lua_translator@time_translator0"
  engine/translators/@before last: "lua_translator@sj_translator"
```
结果如下
![PixPin_2024-10-15_04-57-55](https://github.com/user-attachments/assets/85393e96-11a2-4060-bafe-6a576184ca90)
期望是插入2个配置,但实际只插入了一个

**其他补充说明**
如果有其他补充说明，可以写在这里

其实,我更希望 下面这些@ 型patch可以支持插入列表,而不仅仅是单个元素
![PixPin_2024-10-15_05-09-20](https://github.com/user-attachments/assets/30be8be5-7f55-4410-b897-8d754976b812)

比如说 支持下面的形式
```
patch:
  engine/translators/@before last: 
    - "lua_translator@time_translator0"
    - "lua_translator@sj_translator"
```

**Comment by WindyValley** [comment]
这个Issue应该提给librime

**Comment by fxliang** [comment]
before last 重复key了，读不出来第二个，部署会报错或警告

**Comment by iamqiz** [comment]
@fxliang 根据我的测试,见上图,重复key会使用最后一个的值,忽略之前的, 
/+ 在后面加,不适合某些需要提前处理的组件, 所以就希望增加个在某项元素之前插入多个值的功能

**Comment by fxliang** [comment]
> @fxliang 根据我的测试,见上图,重复key会使用最后一个的值,忽略之前的, /+ 在后面加,不适合某些需要提前处理的组件, 所以就希望增加个在某项元素之前插入多个值的功能

就几行，复制出来删减处理一下就解决了。如需就到librime 提需求看有没有人愿意做吧

**Comment by iamqiz** [comment]
@fxliang @WindyValley 
已解决,
 在索引为n的列表元素前插入多个新元素的配置如下
```
    列表/@before n+0: "新元素1"
    列表/@before n+1: "新元素2"
    列表/@before n+2: "新元素3"
```
思路为,在索引为n的列表元素前插入m个元素,那么就分成m次,每次插入1个;
第一次时,使用 @before n
第二次时,原先索引为n的元素此时的索引变成了n+1(因为前面新插入了一个), 因此需要使用 @before n+1
以此类推,第三次使用 @before n+2

至于下面这种语法不生效的原因,我猜测是因为key重复了而yaml不支持或者忽略之前的同名key ?!
```
patch:
    engine/translators/@before 0: "新元素1"
    engine/translators/@before 0: "新元素2"
```
