### ISSUE TITLE
windows10 候选字修改无效

### ISSUE THREAD

**Issue by xingezhang** [rime/weasel#140]
windows10 1607
小狼毫 0.10.0.0

候选字修改无效，延续0.9.30的设置default.custom.yaml，也copy到build目录，重新部署后依然只有5个

**Comment by nameoverflow** [comment]
……build 目录明显是放程序生成的东西的不是放用户的文件的

**Comment by xingezhang** [comment]
好的，我再来试试看

**Comment by xingezhang** [comment]
是我的问题，现在没问题了，另外我使用gvim时发现，直接使用Shift切换中英文无效，必须重新激活输入法才能使用Shift切换中英文
