### ISSUE TITLE
突然重新部署没用，打不出汉字

### ISSUE THREAD

**Issue by Yik0o** [rime/weasel#1402]
系统：win11
方案调好，用了半年，突然想改个标点映射发现不能部署或是只有却不起作用（0.15版本），后重新拉方案，同样没用，并且连汉字也打不出来，只有下划线。最后升级为0.16.3依旧部署不起作用，试过重启算法，重启软件，重启电脑。log没有erro，我把这几次的log贴在下下面。但是，其他方案都是可以使用的，只有拼音方案用不了，但是将输入法重新设定，取消拼音重新部署他是有反应的。（雾凇拼音方案）
[rime.weasel.DESKTOP-SLCGJ72.Yi.k0.log.INFO.20241018-114041.12936.log](https://github.com/user-attachments/files/17427697/rime.weasel.DESKTOP-SLCGJ72.Yi.k0.log.INFO.20241018-114041.12936.log)

[rime.weasel.DESKTOP-SLCGJ72.Yi.k0.log.INFO.20241018-113256.22284.log](https://github.com/user-attachments/files/17427698/rime.weasel.DESKTOP-SLCGJ72.Yi.k0.log.INFO.20241018-113256.22284.log)

**Comment by fxliang** [comment]
![image](https://github.com/user-attachments/assets/85aa3e8f-f5c0-4be2-8b78-66dd27abbc9e)
我整包雾凇拼音的文件拉下来，然后解压，指定用户目录，部署完成后正常打字，看来你要另外检查你的配置了。

**Comment by Yik0o** [comment]
终于好了，感谢。必须也要将词典也要添加进去，一直只是添加方案，没想到词典也会影响😓
