### ISSUE TITLE
windows上特定程序默认英文输入失效

### ISSUE THREAD

**Issue by skywk** [rime/weasel#1421]
**上报前请检查**
- [☑ ] 我遇到的问题没有其他人在 issue 里提到过
- [☑ ] 我的小狼毫版本于 rime/weasel 下载
- [ ☑] 我在使用小狼毫的最新发布版本

**操作系统信息**
 - OS 详细版本: [ Windows 11 24H2 26100.1591]
 - 小狼毫版本: [  0.16.3.0  ]

**描述遇到的问题**
我在default.custom.yaml中设置了  
app_options/gvim.exe:
    ascii_mode: true
但打开gvim后仍然默认是中文输入。我也尝试设定了其他程序，也是一样失效。

**复现步骤**
重现问题的步骤，如：
如问题中描述

**预期行为**
我希望设定后打开程序能默认为英文输入状态。

**用户文件**
log中相关信息
I20241107 09:10:44.770785  9160 config_compiler.cc:214] patching app_options/Executor.exe
I20241107 09:10:44.770792  9160 config_compiler.cc:214] patching app_options/gvim.exe

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by fxliang** [comment]
default.custom.yaml   ？

weasel.custom.yaml里补丁吧

**Comment by skywk** [comment]
@fxliang 谢谢你。确实如你所说。 ;)
