### ISSUE TITLE
RIME 无法检测大写的状态

### ISSUE THREAD

**Issue by yuelwish** [rime/weasel#1427]
**操作系统信息**
CachyOS Linux x86_64
fcitx5-rime 5.1.9-1.1

**描述遇到的问题**
我的系统中有两个输入法，一个是 fcitx5自带的英文输入法，第二个是rime。
当我在rime中切换大写之后，切换到英文输入法， 切换为小写
这时候回到rime， rime认为我还是在英文输入状态， 必须要按两次 Caps 然后才能输入中文

**预期行为**
预期行为，应该是当我在英文输入法状态，如果已经是小写了，回到 rime 应该给我恢复当前输入方案的默认状态

**截图**
![](https://iili.io/2uFV9hF.gif)

**其他补充说明**
这个问题其实已经过去很久了(几年了)，我也已经更换过N个linux发行版了，这个问题始终存在。

**Comment by fxliang** [comment]
这个应该在对应的前端下提issue，weasel是Windows下的rime前端呢
