### ISSUE TITLE
小狼毫无法在Sandboxie沙盘中使用

### ISSUE THREAD

**Issue by RigHakiko** [rime/weasel#143]
国产大厂的软件一般不安全, 所以只能在Sandboxie中运行, 而国产软件比如QQ之类的就用不了小狼毫了.

只能输入英文, 输入法失效, 请问是否有可行的解决方案??
![untitled](https://user-images.githubusercontent.com/17807588/37584353-1d445e68-2b90-11e8-8a39-314205b9e990.jpg)

**Comment by nameoverflow** [comment]
小狼毫输入法需要被输入的应用能与输入法进程通信。Sandboxie 如果会阻挡应用和外界的通信的话是无法使用的。

**Comment by lifenjoiner** [comment]
不知是否完全遵循了 TSF 规范？微软拼音是可以使用的，应该是下一阶段增强的方向吧？
![zq](https://user-images.githubusercontent.com/19585474/37593731-e5ddae68-2b6a-11e8-88a1-ff27d15a0283.png)

**Comment by mrhso** [comment]
这个道理和 PIME 相同。
Sandboxie 会阻挡与输入法进程的通信（WeaselServer 对应 PIMELauncher）
这样就无法输入，所以一般来说无解，除非重构。

**Comment by kongwy** [comment]
@mrhso Sandboxie 本身可以设置开放一些规则的资源访问，不知道可否利用这个解决呢？

![image](https://user-images.githubusercontent.com/9990631/37657697-af00f6a8-2c86-11e8-879c-6bc846f1596a.png)

**Comment by nameoverflow** [comment]
@lifenjoiner 和 TSF 没关系……输入法处理机制的原因。

**Comment by RigHakiko** [comment]
现在我有了一个很勉强的方法, 是在Sandboxie中运行WeaselServer.exe, 就能输入中文了
![image](https://user-images.githubusercontent.com/17807588/37707873-9ad0cc6c-2d3f-11e8-8073-cae51de6dbce.png)

**Comment by kongwy** [comment]
@RigHakiko 我在 Sandboxie 里似乎无法保持 `WeaselServer.exe` 运行，运行后 Sandboxie 主窗口看不到这项进程。

**Comment by nameoverflow** [comment]
我觉得 #148 说不定也对这个有效。
等 CI build 好了可以下来试试。

**Comment by TylerGeorge** [comment]
请在沙盘里允许 `\device\namedpipe\weaselnamedpipe` 的直接访问。
用沙盘的 `资源访问监控` 可以看到。

**Comment by RigHakiko** [comment]
@TylerGeorge 请问是在哪里增加这个? 是这样吗?
![image](https://user-images.githubusercontent.com/17807588/37883170-6623e4c8-30db-11e8-9b5b-6d906c768256.png)
还有请问, 是不是回复别人只能用这个"@"? 就是这个?
![image](https://user-images.githubusercontent.com/17807588/37883183-81a01924-30db-11e8-8d05-f05a39779949.png)

不好意思, 我发现我原来这么小白

**Comment by RigHakiko** [comment]
@kongwy 我是小白, 使用的事件系统是Window 10, 没有遇到这个情况, 爱莫能助. 不知道@TylerGeorge的方法如何

**Comment by nameoverflow** [comment]
由于 https://github.com/rime/home/issues/221 ，可能下个版本会改成 `\device\namedpipe\用户名\weaselnamedpipe`。

**Comment by Jamesismrtype** [comment]
@TylerGeorge Hi,能否请您详细说一下添加的方法呢？我可以在资源访问监控中发现Pipe     O  \Device\NamedPipe\用户名\WeaselNamedPipe，也在沙盘设置中找到了“资源访问\文件访问\完全访问”，我应该如何将相应的内容添加到完全访问中呢？若方便的话还请指点一下

**Comment by edwinhuish** [comment]
请问每次弹出这个候选框都要卡几秒无响应，请问怎么解决呢？
![image](https://user-images.githubusercontent.com/5207925/92346082-46e51880-f0fe-11ea-956b-0f8e1eb2c111.png)

**Comment by delphinuz** [comment]
> 
> 
> 请问每次弹出这个候选框都要卡几秒无响应，请问怎么解决呢？
> 
> ![image](https://user-images.githubusercontent.com/5207925/92346082-46e51880-f0fe-11ea-956b-0f8e1eb2c111.png)

同樣有這問題，連續打許多字後，都要等大約4~5秒才能完全顯示，困擾很久了，但一直無法解決，即使重新安裝。

不過發現與應用有關，像是wechat電腦版就不行，非常卡。但新版的line就很快(舊版也是慢的)，firefox新版也沒問題很快，估計與應用使用的文字框物件有關。rime可以考慮一下這部分的問題。

**Comment by delphinuz** [comment]
> 
> 
> @TylerGeorge Hi,能否请您详细说一下添加的方法呢？我可以在资源访问监控中发现Pipe O \Device\NamedPipe\用户名\WeaselNamedPipe，也在沙盘设置中找到了“资源访问\文件访问\完全访问”，我应该如何将相应的内容添加到完全访问中呢？若方便的话还请指点一下
> 
> 已解决，原来只要将“\Device\NamedPipe\用户名\WeaselNamedPipe”添加到沙盘设置\资源访问\文件访问\完全访问 中即可

加了還是沒用，另外還有大小寫，試過兩個都不行。
Pipe        \Device\NamedPipe\**\WeaselNamedPipe
Pipe        \device\namedpipe\**\weaselnamedpipe

**Comment by skygunner** [comment]
谷歌拼音输入法V2 V3可以直接输入到Sandboxie，无需单独运行；
win10自带微软拼音，单独运行也无法输入到Sandboxie；

谷歌拼音，小狼毫输入中文到Sandboxie都是比较卡顿，按键要过一会才会显示候选窗格，输入英文就没有问题。

**Comment by skygunner** [comment]
"D:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "C:\Sandbox\username\DefaultBox\drive\D\Program Files (x86)\Tencent\WeChat\WeChat.exe"
"D:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "D:\Program Files (x86)\Rime\weasel-0.14.3\WeaselServer.exe"

**Comment by skygunner** [comment]
> @TylerGeorge Hi,能否请您详细说一下添加的方法呢？我可以在资源访问监控中发现Pipe O \Device\NamedPipe\用户名\WeaselNamedPipe，也在沙盘设置中找到了“资源访问\文件访问\完全访问”，我应该如何将相应的内容添加到完全访问中呢？若方便的话还请指点一下
> 
> 已解决，原来只要将“\Device\NamedPipe\用户名\WeaselNamedPipe”添加到沙盘设置\资源访问\文件访问\完全访问 中即可

how to do this?
\Device\NamedPipe\username\WeaselNamedPipe to resource access, file access , full access

**Comment by delphinuz** [comment]
>  For Rime, need to add this to work:
> \Device\NamedPipe\your-username\WeaselNamedPipe
> to resource file access , full access.

试了还是不行，不知是否 your-username 为中文的原因？不过要改username为英文也来不急了。

**Comment by Lehmaning** [comment]
@RigHakiko 把 `WeaselServer.exe` 加进沙盒设置中的`通用选项 - 自动启动`就可以了。

**Comment by delphinuz** [comment]
> @RigHakiko 现在把 WeaselServer.exe 加进沙盒设置中的通用选项 - 自动启动就可以了。
这方法原面可以的，缺点就是很卡，打字打完要快5~6秒，字才会一个个反应。

但昨天win10进行了一个很久的更新(约1小时)后，重启动，weaselserver再也无法于sandboxie里使用，会一直发生错误而被中止，所以我才又想使用ipc的方式。

不过后来成功，是要写在 File Access里，非IPC Access里。不过原来微信打字很卡的问题，反而更严重了，打完字大约10秒以上才会一个个字反应。

**Comment by edwinhuish** [comment]
@delphinuz 试试允许调用窗体？

我之前用搜狗输入法的时候也一样，很久才弹出候选框，后面发现勾选允许调用窗体就能够解决。

**Comment by delphinuz** [comment]
@edwinhuish 调用窗体 <- 在哪有这设定？小狼毫里还是sandboxie?

**Comment by skygunner** [comment]
> > @RigHakiko 现在把 WeaselServer.exe 加进沙盒设置中的通用选项 - 自动启动就可以了。
> > 这方法原面可以的，缺点就是很卡，打字打完要快5~6秒，字才会一个个反应。
> 
> 但昨天win10进行了一个很久的更新(约1小时)后，重启动，weaselserver再也无法于sandboxie里使用，会一直发生错误而被中止，所以我才又想使用ipc的方式。
> 
> 不过后来成功，是要写在 File Access里，非IPC Access里。不过原来微信打字很卡的问题，反而更严重了，打完字大约10秒以上才会一个个字反应。

微信打字很卡并不是输入法的问题，你用任何输入法，微信在沙盒里都是卡出翔
原因应该是微信用的是chromeframework还是啥的写的，这个在沙盒里有严重性能问题
QQ 旺旺就毫无问题

**Comment by delphinuz** [comment]
> 微信打字很卡并不是输入法的问题，你用任何输入法，微信在沙盒里都是卡出翔。不过微软拼音好像要好一些。
> 原因应该是微信用的是chromeframework还是啥的写的，这个在沙盒里有严重性能问题
> QQ 旺旺就毫无问题

理解，是部分应用很卡，部分就没问题，所以应是这原因。

**Comment by edwinhuish** [comment]
> @edwinhuish 调用窗体 <- 在哪有这设定？小狼毫里还是sandboxie?

@delphinuz 在sandboxie的沙盒设置里。我现在不用sandboxie了，否则也可以截图给你看看。反正搜狗输入法是这个问题，小狼毫应该也是这个问题。

当时搜狗输入法是第一下等很久才有反应。当候选框出来后，继续输入就很快。一旦空格上屏，重新输入又要等很久候选框弹出。。。 你看看小狼毫是否也是这样？

**Comment by delphinuz** [comment]
> @delphinuz 在sandboxie的沙盒设置里。我现在不用sandboxie了，否则也可以截图给你看看。反正搜狗输入法是这个问题，小狼毫应该也是这个问题。
> 
> 当时搜狗输入法是第一下等很久才有反应。当候选框出来后，继续输入就很快。一旦空格上屏，重新输入又要等很久候选框弹出。。。 你看看小狼毫是否也是这样？

那不一样。这里是输入后，大约5秒，才非常慢一个个字出现，每个字出现大约要2~3秒。所以打完一串字后，我就先切换到其他应用，等大约30秒反应完，我再继续输入。

我刚更新到sandboxie最新版，速度有快些，但还是慢，大约每1秒出现一个字，比之前2~3秒快些。

```

**Comment by Apricity7117** [comment]
请问现在最新版的sandboxie-plus怎么设置才能在沙盒中使用搜狗输入法
