### ISSUE TITLE
vim中光标处出现字符残影

### ISSUE THREAD

**Issue by yeheng282** [rime/weasel#1440]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 22H2 22621.4541
 - 小狼毫版本: 0.16.3.0

**描述遇到的问题**
简短地描述你所遇到的问题
输入法ascii_mode模式，在gvim、vscode（vim插件）、idea（vim插件）中normal模式下，执行dd命令后，光标处有不同形式的字符残影。

**复现步骤**
重现问题的步骤，如：
1. 打开gvim软件
2. 输入多行文本
3. 进行 dd操作
4. 移动到下一行
5. 光标处有字符残影
6. 按下esc后残影消失

**预期行为**
不出现残影

**用户文件**
雾凇拼音

**截图**

https://github.com/user-attachments/assets/9c822a2f-a9dc-414a-ac4e-95fea2ed3156

https://github.com/user-attachments/assets/74d7ee74-0b9d-4124-8269-62a0a97cb21b

https://github.com/user-attachments/assets/4bcd5349-8f46-4d96-8fe0-8ff0081a32ad

**Comment by fxliang** [comment]
![gvim](https://github.com/user-attachments/assets/0d086429-e3ca-4304-884b-95ed4cfe5642)
gvim 8.2，未复现问题

**Comment by yeheng282** [comment]
是否可能与屏幕缩放有关？我的电脑显示器使用125%的缩放倍率。
在我的记忆里，该问题是在我调整了屏幕缩放倍率后出现的。在这之前，我使用的100%的缩放倍率，没发现有这个问题。
我也曾尝试将屏幕缩放倍率还原到100%，但没能解决。

**Comment by yeheng282** [comment]
windows系统升级到22621.4602后，问题不复现。

**Comment by S-H-Go** [comment]
我是在 vim 中将文字复制到系统剪切板的时候会出现这个问题。
@fxliang 也许你可以试试 `“+yy` 或  `”+dd`。
