### ISSUE TITLE
人在国外，请问可以将键盘映射为北欧键盘吗？现在只能进行中英文切换

### ISSUE THREAD

**Issue by XiaodongAAA** [rime/weasel#1447]
**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [ ] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ 运行 winver.exe 获取，如 Windows 11 22H2 22621.1555]
 - 小狼毫版本: [ 如 0.15.0.0 ， CI 构建版请附短 commit hash ，如 372c9c ]

**描述遇到的问题**
简短地描述你所遇到的问题

**复现步骤**
重现问题的步骤，如：
1. 打开 '...' 软件
2. 输入 '...'
3. 进行 '...' 操作
4. 遇到了 '...' 问题

**预期行为**
简短地描述你预期小狼毫怎么反馈

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by LEOYoon-Tsaw** [comment]
问题描述不清，可能重复的问题 #1430

**Comment by lotem** [comment]
Windows 上的鍵盤佈局/輸入法和語言綁定，而中文輸入法對應的鍵盤佈局通常是美式鍵盤。

您可能需要切換輸入語言，另一個帖子有人提示「按Win+空格或者Alt+Shift切换」。

畢竟 `ascii_mode` 依然是就輸入語言爲中文的需求而設置的。適用場景是中文輸入間雜拉丁字母等 ASCII 字符。
