### ISSUE TITLE
在繁體中文 Microsoft Windows 10 上被 Windows defender 誤判為病毒

### ISSUE THREAD

**Issue by feyfeytw** [rime/weasel#145]
Trojan:Win32/Critet.BS

**Comment by ztl8702** [comment]
+1. 和语言应该没关系。我用的英文版也是报毒。`Windows 10 Build 17120`

**Comment by zhtw2013** [comment]
跟語言沒關係，誤報要解決只能一個一個找防毒軟體廠商回報
剛發佈新版的時候誤報是19個防毒誤報，經過我逐一回報之後變成13個了
（寫信、上傳給主流防毒廠商）
非主流的防毒軟體我就不管了，很多根本沒有誤報的回報入口..

然後我找不到哪裏能夠回報Windows defender的誤報，所以就不知道怎麼辦了..

我感覺防毒軟體廠商也是很奸詐，誤報的很爽快，
但卻沒有方便的誤報回報入口，很多不是藏的很深就是根本沒有，
這樣軟體開發者有時候被誤跑也很難平反啊....

**Comment by nameoverflow** [comment]
Duplicated.
https://github.com/rime/weasel/issues/139
