### ISSUE TITLE
weasel 0.10.0 用户同步资料，不会合并同目录下其它子文件夹内的词库

### ISSUE THREAD

**Issue by wrlssqi** [rime/weasel#149]
系统：win10 1709 
小狼毫版本： 0.10.0
设置同步目录为onedrive目录，底下有三个rime的同步子文件夹。点击用户资料同步后，不会合并其余两个子文件夹内词库，只会把当前id文件夹内的词库更新一下。
![image](https://user-images.githubusercontent.com/9946624/37779471-6fd53b4a-2e27-11e8-99c1-5714a09d4ec1.png)

**Comment by Prcuvu** [comment]
每次重新安装时，小狼毫会生成新的 `installation_id` 以区别不同安装的设置，不与其他设置合并。用户应在 `installation.yaml` 中自行修改为旧名称以同步旧设置。
另外，`installation_id` 完全可以自由命名，参见[说明书](https://github.com/rime/home/wiki/UserGuide#%E8%A8%AD%E5%AE%9A%E5%90%8C%E6%AD%A5%E4%BD%8D%E7%BD%AE)。

**Comment by wrlssqi** [comment]
我已经将其安装id改为了旧名称。我这里指的是其不会同步其它两个子文件夹里的词库。按照用户同步部分的说明，"同步時，依次將各子文件夾中的詞典快照合併到用戶詞典，最後爲合併後的用戶詞典生成一份新的快照文件。"，这里并没有做到这一点，只是把当前设备的词库上传到了对应的目录下。
比如我一台win10设备id号为3e2f8018-8658-4b4a-87fc-7c02e539992e，即截图里的第一个文件夹。点击用户同步后，其日志如下：
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0323 09:39:18.087090 16924 core_module.cc:20] registering core components.
I0323 09:39:18.089094 16924 registry.cc:14] registering component: config_builder
I0323 09:39:18.089094 16924 registry.cc:14] registering component: config
I0323 09:39:18.089094 16924 registry.cc:14] registering component: schema
I0323 09:39:18.089094 16924 registry.cc:14] registering component: user_config
I0323 09:39:18.089094 16924 dict_module.cc:24] registering components from module 'dict'.
I0323 09:39:18.089094 16924 registry.cc:14] registering component: tabledb
I0323 09:39:18.089094 16924 registry.cc:14] registering component: stabledb
I0323 09:39:18.089094 16924 registry.cc:14] registering component: plain_userdb
I0323 09:39:18.089094 16924 registry.cc:14] registering component: userdb
I0323 09:39:18.089094 16924 registry.cc:14] registering component: dictionary
I0323 09:39:18.089094 16924 registry.cc:14] registering component: reverse_lookup_dictionary
I0323 09:39:18.089094 16924 registry.cc:14] registering component: user_dictionary
I0323 09:39:18.089094 16924 registry.cc:14] registering component: userdb_recovery_task
I0323 09:39:18.089094 16924 levers_module.cc:23] registering components from module 'levers'.
I0323 09:39:18.089094 16924 registry.cc:14] registering component: detect_modifications
I0323 09:39:18.089094 16924 registry.cc:14] registering component: installation_update
I0323 09:39:18.089094 16924 registry.cc:14] registering component: workspace_update
I0323 09:39:18.089094 16924 registry.cc:14] registering component: schema_update
I0323 09:39:18.089094 16924 registry.cc:14] registering component: config_file_update
I0323 09:39:18.089094 16924 registry.cc:14] registering component: prebuild_all_schemas
I0323 09:39:18.089094 16924 registry.cc:14] registering component: user_dict_upgrade
I0323 09:39:18.089094 16924 registry.cc:14] registering component: cleanup_trash
I0323 09:39:18.089094 16924 registry.cc:14] registering component: user_dict_sync
I0323 09:39:18.089094 16924 registry.cc:14] registering component: backup_config_files
I0323 09:39:18.089094 16924 registry.cc:14] registering component: clean_old_log_files
I0323 09:39:18.094107 16924 deployer.cc:114] starting work thread for 3 tasks.
I0323 09:39:18.113685 12652 deployer.cc:83] running deployment tasks:
I0323 09:39:18.113685 12652 deployment_tasks.cc:80] updating rime installation info.
I0323 09:39:18.114181 12652 config_data.cc:65] loading config file 'C:\Users\wrlss\AppData\Roaming\Rime\installation.yaml'.
I0323 09:39:18.114682 12652 deployment_tasks.cc:98] installation info exists. installation id: 3e2f8018-8658-4b4a-87fc-7c02e539992e
I0323 09:39:18.114682 12652 deployment_tasks.cc:106] sync dir: C:\Users\wrlss\OneDrive\RimeSync
I0323 09:39:18.114682 12652 deployment_tasks.cc:108] previous distribution: Weasel
I0323 09:39:18.114682 12652 deployment_tasks.cc:111] previous distribution version: 0.10.0
I0323 09:39:18.114682 12652 deployment_tasks.cc:114] previous Rime version: 1.3.0
I0323 09:39:18.114682 12652 deployment_tasks.cc:521] backing up config files.
I0323 09:39:18.128198 12652 config_data.cc:65] loading config file 'C:\Users\wrlss\AppData\Roaming\Rime\user.yaml'.
I0323 09:39:18.130460 12652 deployment_tasks.cc:565] backed up 3 config files to C:\Users\wrlss\OneDrive\RimeSync\3e2f8018-8658-4b4a-87fc-7c02e539992e, 0 failed, 4 up-to-date, 0 skipped.
I0323 09:39:18.131451 12652 user_dict_manager.cc:223] synchronizing 2 user dicts.
I0323 09:39:18.131451 12652 user_dict_manager.cc:189] synchronize user dict 'emoji'.
I0323 09:39:18.143483 12652 user_db.cc:123] backing up userdb 'emoji.userdb' to C:\Users\wrlss\OneDrive\RimeSync\3e2f8018-8658-4b4a-87fc-7c02e539992e\emoji.userdb.txt
I0323 09:39:18.143483 12652 tsv.cc:62] writing tsv file: C:\Users\wrlss\OneDrive\RimeSync\3e2f8018-8658-4b4a-87fc-7c02e539992e\emoji.userdb.txt
I0323 09:39:18.147496 12652 level_db.cc:302] closed db 'emoji.userdb'.
I0323 09:39:18.147496 12652 user_dict_manager.cc:189] synchronize user dict 'luna_pinyin'.
I0323 09:39:18.159525 12652 user_db.cc:123] backing up userdb 'luna_pinyin.userdb' to C:\Users\wrlss\OneDrive\RimeSync\3e2f8018-8658-4b4a-87fc-7c02e539992e\luna_pinyin.userdb.txt
I0323 09:39:18.159525 12652 tsv.cc:62] writing tsv file: C:\Users\wrlss\OneDrive\RimeSync\3e2f8018-8658-4b4a-87fc-7c02e539992e\luna_pinyin.userdb.txt
I0323 09:39:18.265827 12652 level_db.cc:302] closed db 'luna_pinyin.userdb'.
I0323 09:39:18.265827 12652 deployer.cc:95] 3 tasks ran: 3 success, 0 failure.
看起来并未有将其余两个目录下的词库同步的操作，实际上也并没有。之前用的prime，以及ibus-rime均无此问题，可同步所有用户词库。

**Comment by Prcuvu** [comment]
小狼毫和其余前端使用相同的方法进行同步，应该是后端算法库的更新导致这个问题。请将这个问题移动到 [rime/librime](https://github.com/rime/librime) 那边。

**Comment by lotem** [comment]
只有與 ID （目錄名）對應的機器會更新該目錄的文件內容。
用戶詞典的合併發生在本地。
