### ISSUE TITLE
Full Emoji compatibility

### ISSUE THREAD

**Issue by LEOYoon-Tsaw** [rime/weasel#152]
Weasel now can be used to input emojis, but the problem is that it renders emoji in text mode, which is black and white, instead of the expected colorful representation.
Another drawback here is that the current text representation lacks support for ZWJ sequences. As an example:
![image](https://user-images.githubusercontent.com/4469383/37812663-127f73aa-2e9c-11e8-8c2a-ca4080ae22ae.png)
The doctor emoji is a ZWJ sequence behind scene, but didn't appear properly. What I'm sure is that Windows 10 provide excellent support for emojis, the built-in input can render emojis in the colorful emoji representation very well. So I hope that weasel can do so, at least on windows 10.

**Comment by Prcuvu** [comment]
This feature requires DirectWrite support in WeaselUI.

**Comment by hiking93** [comment]
Any updates?

**Comment by harrysummer** [comment]
I worked on DirectWrite rendering a while ago. However, it seems still some issues:

![image](https://user-images.githubusercontent.com/1215413/121258349-a5911b80-c863-11eb-85c6-81f1911e431b.png)

The "Health Worker" emoji is working but "Keycap 1" is not.

**Comment by harrysummer** [comment]
Added font fallback logic and now it fully works. The latest Windows also included the emoji of doctor. I'll try to organize the code when I got some time.

![image](https://user-images.githubusercontent.com/1215413/131830283-d1b94e71-c9db-4023-ac54-01ad8877c3f2.png)

**Comment by fxliang** [comment]
close by release 0.15.0
