### ISSUE TITLE
combo pinyin 在 emacs 25.3.1 中不工作

### ISSUE THREAD

**Issue by tusooa** [rime/weasel#155]
weasel 0.10.0, windows 10 x64
具体表现为输入任何按键组合之后无候选词出现，再按任何键都没有反应，并且不能切换中英文，但是可以按Ctrl grave 切换到另一种输入方案。
Luna pinyin无问题。别的应用程序尚未发现问题。

**Comment by tusooa** [comment]
此外，非TSF版本可以正常工作。上述bug仅在「小狼毫(TSF)」中发生。

**Comment by Yunoinsky** [comment]
同样的问题, weasel 0.14.3 windows 11 x64 emacs 28.1 mingw版

(目前似乎 TSF 版本被合并了, 所以没有test TSF和非TSF)

combo-pinyin 空格和回车都没有作用, ctrl/alt 可以取消输入, 也可以切换到其他输入方案或输入法.

具体表现为能够显示输入框, 但候选词不出现, 输入光标停留在输入框的开头. 感觉像是 chord 出了问题

其他输入方案都没有问题,

**Comment by tusooa** [comment]
我已经很久没用过windows了，不好意思
