### ISSUE TITLE
最新版的weasel只有TSF模式？

### ISSUE THREAD

**Issue by CrazyCamouflage** [rime/weasel#158]
由于weasel是主力输入法，但是我发现Dota2这些游戏只支持IME模式的输入法。请问一下，weasel现在是TSF和IME自动识别切换还是只有TSF了？

**Comment by Guwalgiyakuan** [comment]
weasel-0.10.0.0 目前两种模式都在

**Comment by Prcuvu** [comment]
两个都有。
