### ISSUE TITLE
Windows Server 2012中WeaselServer启动失败

### ISSUE THREAD

**Issue by toiiggww** [rime/weasel#16]
Windows Server 2012中，TFS模式，未关闭UAC，切换输入法时提示“服务进程启动不起来”，从Sysinternal的procexp中看，只有父进程为任务管理器或其它以管理员方式运行的程序，可以正常输入。即使将WeaselServer加入开始菜单项运行，均失败。
未测试Win8及UAC关闭情况。
可能本问题是导致其它Issue中无法输入的情况的原因。

**Comment by nameoverflow** [comment]
当前版本不再自动唤醒 server。
