### ISSUE TITLE
小狼毫 0.10.0 下载windows defender 报毒

### ISSUE THREAD

**Issue by Ych4321** [rime/weasel#160]
Hi，
你好，感谢制作更新小狼毫的版本。我下载后发现Windows defender 报毒，安装文件直接被删除。
![image](https://user-images.githubusercontent.com/12496668/37950590-b1bfa020-31cb-11e8-9b58-159cfa2548f7.png)

**Comment by nameoverflow** [comment]
Duplicated with #139

**Comment by nameoverflow** [comment]
Duplicate of #139
