### ISSUE TITLE
单词的拼音错误不知道是否可以提在这里

### ISSUE THREAD

**Issue by Guwalgiyakuan** [rime/weasel#162]
![Windows_NT_2018-03-27_22-08-32.png](https://i.loli.net/2018/03/27/5aba523d3d0fe.png)
这两个字的拼音是不是不对？ 我也不知道这种问题发在哪里合适，不合适的话麻烦管理员删掉。

**Comment by mrhso** [comment]
没有所谓的「管理员才能删」的说法。
另外词典问题请在相应的仓库提，这里只是前端仓库。

**Comment by nameoverflow** [comment]
https://github.com/rime/rime-luna-pinyin

大概应该去这里提。
