### ISSUE TITLE
朙月拼音输入，几个字母键“对位”错位

### ISSUE THREAD

**Issue by qijianjun** [rime/weasel#164]
**版本：**

windows的0.10.0

**异常描述：**

比如按S键，出来的却是A键的查词结果，26个字母挨着按了一遍，有这个情况的有“o p r s n q”共6个键。

**配置情况：**

用的配置是0.9.30时用过的，当时没有这个问题，更新到当前版本后也没改过配置，只更新过词库。

![image](https://user-images.githubusercontent.com/612912/38121068-8f95dea2-33ff-11e8-9448-0f7e61b634a0.png)

![image](https://user-images.githubusercontent.com/612912/38121081-a3e9d188-33ff-11e8-8fc1-7096e14cfcac.png)

**Comment by nameoverflow** [comment]
试试把用户文件夹中的 binary 文件清空后重新部署。

**Comment by qijianjun** [comment]
谢谢，问题解决了。
我用户目录下没有binary文件夹，是在build处理的。
然后比较了重新部署后的yaml文件，只有在luna_pinyin.schema.yaml有新增的几行符号词库有更新，其他是一样的。所以推测可能是之前的bin词库有问题。
