### ISSUE TITLE
win10 下显示两个小狼毫

### ISSUE THREAD

**Issue by chaosye0** [rime/weasel#165]
win10 下显示两个小狼毫，用着是一样的，想切换到其它就得切两下，很不方便，能去掉一个吗

<a href="http://s1036.photobucket.com/user/chaos_ye/media/TIM20180331094556_zpszso4wyh2.png.html" target="_blank"><img src="http://i1036.photobucket.com/albums/a446/chaos_ye/TIM20180331094556_zpszso4wyh2.png" border="0" alt=" photo TIM20180331094556_zpszso4wyh2.png"/></a>

**Comment by X1aomu** [comment]
可以在控制面板里找到键盘设置，把其中的小狼毫删掉，这样删掉的是 IME 框架的，就会只剩下 TSF 框架的了。

**Comment by Prcuvu** [comment]
切换到其他语言只需按 <kbd>Alt</kbd> + <kbd>Shift</kbd>，且可以在控制面板中删除“小狼毫”，只保留“小狼毫 (TSF)”。

**Comment by chaosye0** [comment]
谢谢，解决问题了

**Comment by xarthurx** [comment]
最近的windows 10 更新，控制面板調整了，沒有鍵盤的選項……
更新以後又出來了，並且刪不掉。
