### ISSUE TITLE
Windows 10 下打开托盘图标显示并在激活西文模式时用鼠标操作任务栏会卡住数秒

### ISSUE THREAD

**Issue by Prcuvu** [rime/weasel#166]
操作包括点击托盘图标或开始按钮、或者鼠标点击任务栏空位后按 <kbd>Shift</kbd> 切换到西文模式。卡住数秒后，任务栏将恢复响应。
IME 和 TSF 都存在这个问题。

麻烦 @mrhso 测试一下 Windows 7 是否可以用相同方法重现。

**Comment by X1aomu** [comment]
@Prcuvu 我在 Win10 下没有出现这个问题，Weasel 是目前最新的 AppVeyor Build 54，系统是 Win10 1709。

**Comment by Guwalgiyakuan** [comment]
同Win10 1709 使用的 Build 54 版
剛開機也發現卡的厲害，試了一下：
1.如果是覆蓋安裝沒有清除過個人配置 就會出現 @Prcuvu 說的情況。
2.如果先卸載舊版，刪除 Rime 個人配置文件之後全新安裝就沒問題。

**Comment by Prcuvu** [comment]
已确认在关闭托盘图标显示时不会发生这个问题。

**Comment by Prcuvu** [comment]
> 这是我这里的情况，不知道是不是个例。

我也独立发现了这个条件。

**Comment by mrhso** [comment]
Windows 7 (IA-32 x86-64) 已重现。

**Comment by lotem** [comment]
可以刪除托盤圖標。
其菜單內容已移至開始菜單，因此默認不顯示。

**Comment by Guwalgiyakuan** [comment]
托盤圖標感覺還是有一點用處的，普通用戶應該都適應了中英文切換的時候看一眼托盤圖標。目前的方式切換顯示在輸入框附近，因爲位置不固定而且圖標又小經常切換了之後不知道目前的狀態是中文還是英文，如果改爲類似微軟拼音模式的中英切換顯示方法是否要大改？

有時候我會用微軟日文輸入感覺它的設置很好，當在日文輸入狀態下切換輸入窗口的時候屏幕上會出現一個大寫的 `A` 或 `あ` 的字樣一閃而過提示用戶當前的輸入狀態。而且托盤圖標也會有對應的文字顯示。

本人不懂代碼，只是從使用者角度來感受。

**Comment by nameoverflow** [comment]
将由 https://github.com/nameoverflow/weasel/commit/45cf112099fa6db335cda06b1aaa0ae9c7975efe 修复。

@Guwalgiyakuan 计划将用类似 Windows 10 系统自带输入法的图标取代托盘图标。

**Comment by Guwalgiyakuan** [comment]
@nameoverflow 期待并感谢各位的工作 👍
