### ISSUE TITLE
中文输入模式下激活大写状态后无法上屏

### ISSUE THREAD

**Issue by qijianjun** [rime/weasel#167]
**环境：**

使用的版本为0.10.0，操作系统为Win10，输入方案为朙月拼音。

**问题：**

如果在中文输入模式下激活了大写键，不论是开启后开始输入大写字母，还是输入小写字母过程中切换到大写状态并开始输入大写字母，当前的输入结果都无法上屏。

因为设置的上屏快捷键是空格，此时按空格还是会输入空格，按backspace还是会回退删除。

要结束这种“胶着”状态，需要取消大写的激活状态，但有时必须删除输入面板上的全部前输入或者输入一些中文，才能取消输入面板。

不知这是设置的问题还是BUG？

**例外：**

偶尔不会出现这个问题，例如输入前一行的“bug”时正常，但再试又不行了，似乎按上屏键速度特别快时有可能不出问题，但不确定。

**Comment by qijianjun** [comment]
谢谢！就是说后面的版本不会有这个问题了，但还未发布是吧？

**Comment by lotem** [comment]
按照發佈計劃，下個版本不會解決這個問題。但是正如 @nameoverflow 所說，可以通過升級配置解決。

**Comment by RigHakiko** [comment]
@lotem 请问怎么通过升级配置解决? 我没有看懂他的意思

**Comment by lotem** [comment]
@RigHakiko 最新的默認配置是這樣的：大寫鎖定鍵會清除未完成的輸入。
https://github.com/rime/rime-prelude/blob/master/default.yaml#L158
