### ISSUE TITLE
無法修改yaml、選單符號消失了！

### ISSUE THREAD

**Issue by paultw** [rime/weasel#168]
版本: 0.10

我試着要修改dafult.yaml、 weasel.yaml 等資料。
但是出現無法儲存的狀況。

此外，選字的時候，符號消失了。。 這樣子選字起來很麻煩。。
![default](https://user-images.githubusercontent.com/36876929/38179613-032bd268-3658-11e8-9e2a-bc38e080c934.jpg)

![error](https://user-images.githubusercontent.com/36876929/38179623-160ce124-3658-11e8-9fb6-e133154d2565.JPG)

**Comment by Guwalgiyakuan** [comment]
要修改用戶  %AppData\Rime% 中的文檔，不可以改安裝目錄下的

**Comment by paultw** [comment]
如圖所示，這是我在0.9版本， %AppData\Rime% 中修改的檔案。 但0.10版本似乎沒有變動到？
我選單應該是10個選項，但現在變成只有5個

![default](https://user-images.githubusercontent.com/36876929/38181233-5a3fa500-3664-11e8-9e9d-6633a5c17faf.JPG)
![default](https://user-images.githubusercontent.com/36876929/38181245-6834b5a6-3664-11e8-9dc2-e2e1bea2f4ae.png)

**Comment by Guwalgiyakuan** [comment]
本人沒有使用過 `0.9` 版本，不清楚升級後是否需要別的設置才能保證原來的配置不變。
跟人認爲備份好設置全新安裝 `0.10.0` 之後再參照原配置修改比較穩妥。
重點是修改 `weasel.custom.yaml` 後別忘了 `重新部署`

**Comment by nameoverflow** [comment]
正确的配置方法是修改用户文件夹下的 custom.yaml 而不是修改 dafult.yaml、 weasel.yaml。
%AppData\Rime% 中的 default.yaml 档案在新版不再用到，可以删除。

**Comment by lotem** [comment]
將以 https://github.com/rime/librime/pull/193 修復
