### ISSUE TITLE
Weasel0.10.0: 選字無法顯示

### ISSUE THREAD

**Issue by hhtmp88** [rime/weasel#169]
今早剛將 Weasel0.10.0 安裝到 Win10。

起初選字鍵均能正常顯示及選字，
但後來有些訊息問是否選擇『自動更新』，Yes之後，下午再用 小狼豪 時，選字鍵便不能正常顯示！

有辦法可以反回最初安裝時的狀態 及停止再自動更新嗎？

**Comment by hhtmp88** [comment]
自動更新前有以下的問題，但「選字鍵」能正常顯示！
* win10 下显示两个小狼毫
https://github.com/rime/weasel/issues/165

自動更新後 issue#165 的問題 更正了，但「選字鍵」變成不能正常顯示！

**Comment by nameoverflow** [comment]
选字问题见 #168 。
0.10 版目前不会接收自动更新。

**Comment by hhtmp88** [comment]
怎樣才可使選字鍵重現？

**Comment by nameoverflow** [comment]
可以先删除 %APPDATA%/Rime 下的 `default.yaml` （只保留 `default.custom.yaml`），重新部署。

**Comment by nameoverflow** [comment]
Duplicate of #168

**Comment by hhtmp88** [comment]
"nameoverflow: 可以先删除 %APPDATA%/Rime 下的 default.yaml （只保留 default.custom.yaml），重新部署。"
--> 我只能在 Rime 的安裝目錄找到 default.yaml:

C:\win_prg\chi_prg\RimeWeasel\weasel-0.10.0\data\
--  將 default.custom.yaml 放到這裏對嗎？

在所有用户目錄 均找不到 Rime 目錄 及default.yaml 啊：


* user01 -- with administrative right
C:\Users\user01\AppData
-- only these folders found: Local, LocalLow, and Roaming

* user02 -- no admin right
C:\Users\user02\AppData
-- only these folders found: Local, LocalLow, and Roaming

**Comment by nameoverflow** [comment]
是否自定了用户资料目录？

**Comment by hhtmp88** [comment]
Weasel  的安裝目錄是自定的，如下：
C:\win_prg\chi_prg\RimeWeasel\weasel-0.10.0\


但「用户资料目录」則不太肯定

**Comment by nameoverflow** [comment]
开始菜单中有「小狼毫用户目录」的图标。

**Comment by hhtmp88** [comment]
Thanks!

用户资料目录 are found as follows:
* user01 -- with administrative right
C:\Users\user01\AppData\Roaming\Rime
* user02 -- no admin right
C:\Users\user02\AppData\Roaming\Rime

**Comment by Prcuvu** [comment]
这个问题源于我的疏忽。我为 `weasel.yaml` 新增候选项标签格式的配置时，忘记增加配置文件的版本号，导致配置文件没有及时更新从而无法正确呈现标签。更新到最新的 0.11.0 版本可以解决这个问题。
