### ISSUE TITLE
opencc失效

### ISSUE THREAD

**Issue by Prcuvu** [rime/weasel#17]
版本：commit 269b854c471ad344f2a43f3d0db32adea1f0f023
小狼毫opencc失效。
症状：朙月拼音的繁简转换失效，朙月拼音·简化字输出为繁体，朙月拼音·臺灣正體也输出为默认繁体字形。

**Comment by lotem** [comment]
是的。
數據文件還沒有替換成 opencc 1.2 格式的。

**Comment by Prcuvu** [comment]
已解决。
