### ISSUE TITLE
词典报错：IO error: acquiring lock failed

### ISSUE THREAD

**Issue by Hermittttt** [rime/weasel#173]
环境：
小狼毫0.10.0，win10，小鹤双拼，启用了用户资料同步。

描述：
使用过程中弹出错误提示框，日志文件如下。这个错误遇到过两次，上一次重新安装解决了，这次又来了，文件权限没有问题。

Log file created at: 2018/04/05 11:10:25
Running on machine: HERMIT-LAPTOP
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0405 11:10:25.296227  9776 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:10:25.327481  6328 level_db.cc:242] db recovery failed: OK
E0405 11:10:25.327481  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:10:25.327481  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:10:28.882377  1472 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:10:28.898783  6328 level_db.cc:242] db recovery failed: OK
E0405 11:10:28.899785  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:10:28.899785  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:12:32.859912   720 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:12:32.875955  6328 level_db.cc:242] db recovery failed: OK
E0405 11:12:32.877960  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:12:32.877960  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:13:02.296823  5668 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:13:02.296823  6328 level_db.cc:242] db recovery failed: OK
E0405 11:13:02.296823  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:13:02.296823  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:13:27.655957  6468 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:13:27.671584  6328 level_db.cc:242] db recovery failed: OK
E0405 11:13:27.671584  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:13:27.671584  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:14:04.085433  8092 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:14:04.101060  6328 level_db.cc:242] db recovery failed: OK
E0405 11:14:04.101060  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:14:04.101060  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:17:06.848287  6052 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:17:06.863916  6708 level_db.cc:242] db recovery failed: OK
E0405 11:17:06.863916  6708 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:17:06.863916  6708 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:18:32.379779  6500 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:18:32.411031  6708 level_db.cc:242] db recovery failed: OK
E0405 11:18:32.411031  6708 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:18:32.411031  6708 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:19:19.472134 10000 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:19:19.519013  6708 level_db.cc:242] db recovery failed: OK
E0405 11:19:19.519013  6708 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:19:19.519013  6708 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:19:29.061020  8204 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:19:29.076649  6708 level_db.cc:242] db recovery failed: OK
E0405 11:19:29.076649  6708 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:19:29.076649  6708 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:19:40.506512  6324 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:19:40.529196  6708 level_db.cc:242] db recovery failed: OK
E0405 11:19:40.529196  6708 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:19:40.529196  6708 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:21:53.248257  8224 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:21:53.279539  6328 level_db.cc:242] db recovery failed: OK
E0405 11:21:53.279539  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:21:53.279539  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
E0405 11:22:16.871909  7752 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:22:16.887540  6328 level_db.cc:242] db recovery failed: OK
E0405 11:22:16.887540  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:22:16.887540  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.

**Comment by lotem** [comment]
具體怎麼同步的？
另外 `E0405` 重複了很多次但看不出出錯時在做什麼，再貼一段 INFO log 看看 `E0405` 錯誤信息前後的上下文。

**Comment by Hermittttt** [comment]
您好！
使用的就是小狼毫的用户资料同步功能，地址是本地的一个dropbox文件夹。
INFO log如下
I0405 11:10:25.280599  9776 engine.cc:71] starting engine.
I0405 11:10:25.280599  9776 config_data.cc:65] loading config file 'C:\Users\outca\AppData\Roaming\Rime\user.yaml'.
I0405 11:10:25.280599  9776 engine.cc:126] updated option: simplification
I0405 11:10:25.280599  9776 config_data.cc:65] loading config file 'C:\Users\outca\AppData\Roaming\Rime\build/double_pinyin_flypy.schema.yaml'.
I0405 11:10:25.296227  9776 engine.cc:126] updated option: _auto_commit
I0405 11:10:25.296227  9776 dictionary.cc:265] loading dictionary 'luna_pinyin'.
I0405 11:10:25.296227  9776 table.cc:299] loading table file: C:\Users\outca\AppData\Roaming\Rime\build/luna_pinyin.table.bin
I0405 11:10:25.296227  9776 prism.cc:77] loading prism file: C:\Users\outca\AppData\Roaming\Rime\build/double_pinyin_flypy.prism.bin
I0405 11:10:25.296227  9776 prism.cc:107] found double array image of size 1024.
E0405 11:10:25.296227  9776 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
I0405 11:10:25.311853  9776 deployer.cc:114] starting work thread for 1 tasks.
I0405 11:10:25.311853  6328 deployer.cc:83] running deployment tasks:
I0405 11:10:25.311853  6328 level_db.cc:233] trying to recover db 'luna_pinyin.userdb'.
I0405 11:10:25.311853  9776 engine.cc:126] updated option: ascii_mode
I0405 11:10:25.327481  9776 engine.cc:139] updated property: client_app
I0405 11:10:25.327481  9776 engine.cc:139] updated property: client_type
I0405 11:10:25.327481  9776 engine.cc:126] updated option: inline_preedit
I0405 11:10:25.327481  9776 engine.cc:126] updated option: soft_cursor
I0405 11:10:25.327481  6328 level_db.cc:236] repair finished.
E0405 11:10:25.327481  6328 level_db.cc:242] db recovery failed: OK
I0405 11:10:25.327481  6328 user_db_recovery_task.cc:43] recreating db file.
E0405 11:10:25.327481  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:10:25.327481  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
I0405 11:10:25.327481  6328 deployer.cc:95] 1 tasks ran: 0 success, 1 failure.
I0405 11:10:28.881374  1472 engine.cc:71] starting engine.
I0405 11:10:28.881374  1472 engine.cc:126] updated option: simplification
I0405 11:10:28.881875  1472 engine.cc:126] updated option: _auto_commit
I0405 11:10:28.881875  1472 dictionary.cc:265] loading dictionary 'luna_pinyin'.
E0405 11:10:28.882377  1472 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
I0405 11:10:28.882377  1472 deployer.cc:114] starting work thread for 1 tasks.
I0405 11:10:28.882377  6328 deployer.cc:83] running deployment tasks:
I0405 11:10:28.882377  6328 level_db.cc:233] trying to recover db 'luna_pinyin.userdb'.
I0405 11:10:28.882879  1472 engine.cc:126] updated option: ascii_mode
I0405 11:10:28.882879  1472 engine.cc:139] updated property: client_app
I0405 11:10:28.882879  1472 engine.cc:139] updated property: client_type
I0405 11:10:28.882879  1472 engine.cc:126] updated option: inline_preedit
I0405 11:10:28.882879  1472 engine.cc:126] updated option: soft_cursor
I0405 11:10:28.898783  6328 level_db.cc:236] repair finished.
E0405 11:10:28.898783  6328 level_db.cc:242] db recovery failed: OK
I0405 11:10:28.898783  6328 user_db_recovery_task.cc:43] recreating db file.
E0405 11:10:28.899785  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:10:28.899785  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
I0405 11:10:28.899785  6328 deployer.cc:95] 1 tasks ran: 0 success, 1 failure.
I0405 11:12:32.857908   720 engine.cc:71] starting engine.
I0405 11:12:32.858911   720 engine.cc:126] updated option: simplification
I0405 11:12:32.858911   720 engine.cc:126] updated option: _auto_commit
I0405 11:12:32.858911   720 dictionary.cc:265] loading dictionary 'luna_pinyin'.
E0405 11:12:32.859912   720 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
I0405 11:12:32.859912   720 deployer.cc:114] starting work thread for 1 tasks.
I0405 11:12:32.859912  6328 deployer.cc:83] running deployment tasks:
I0405 11:12:32.859912  6328 level_db.cc:233] trying to recover db 'luna_pinyin.userdb'.
I0405 11:12:32.859912   720 engine.cc:126] updated option: ascii_mode
I0405 11:12:32.859912   720 engine.cc:139] updated property: client_app
I0405 11:12:32.859912   720 engine.cc:139] updated property: client_type
I0405 11:12:32.859912   720 engine.cc:126] updated option: inline_preedit
I0405 11:12:32.859912   720 engine.cc:126] updated option: soft_cursor
I0405 11:12:32.875955  6328 level_db.cc:236] repair finished.
E0405 11:12:32.875955  6328 level_db.cc:242] db recovery failed: OK
I0405 11:12:32.876958  6328 user_db_recovery_task.cc:43] recreating db file.
E0405 11:12:32.877960  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:12:32.877960  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
I0405 11:12:32.877960  6328 deployer.cc:95] 1 tasks ran: 0 success, 1 failure.
I0405 11:12:44.777180  1472 simplifier.cc:35] initializing opencc: C:\Program Files (x86)\Rime\weasel-0.10.0\data\opencc\t2s.json
I0405 11:13:02.281204  5668 engine.cc:71] starting engine.
I0405 11:13:02.281204  5668 engine.cc:126] updated option: simplification
I0405 11:13:02.281204  5668 engine.cc:126] updated option: _auto_commit
I0405 11:13:02.281204  5668 dictionary.cc:265] loading dictionary 'luna_pinyin'.
E0405 11:13:02.296823  5668 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
I0405 11:13:02.296823  5668 deployer.cc:114] starting work thread for 1 tasks.
I0405 11:13:02.296823  6328 deployer.cc:83] running deployment tasks:
I0405 11:13:02.296823  6328 level_db.cc:233] trying to recover db 'luna_pinyin.userdb'.
I0405 11:13:02.296823  5668 engine.cc:126] updated option: ascii_mode
I0405 11:13:02.296823  5668 engine.cc:139] updated property: client_app
I0405 11:13:02.296823  5668 engine.cc:139] updated property: client_type
I0405 11:13:02.296823  5668 engine.cc:126] updated option: inline_preedit
I0405 11:13:02.296823  5668 engine.cc:126] updated option: soft_cursor
I0405 11:13:02.296823  6328 level_db.cc:236] repair finished.
E0405 11:13:02.296823  6328 level_db.cc:242] db recovery failed: OK
I0405 11:13:02.296823  6328 user_db_recovery_task.cc:43] recreating db file.
E0405 11:13:02.296823  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:13:02.296823  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
I0405 11:13:02.296823  6328 deployer.cc:95] 1 tasks ran: 0 success, 1 failure.
I0405 11:13:09.726820  5668 simplifier.cc:35] initializing opencc: C:\Program Files (x86)\Rime\weasel-0.10.0\data\opencc\t2s.json
I0405 11:13:11.083757  5668 engine.cc:126] updated option: ascii_mode
I0405 11:13:27.655957  6468 engine.cc:71] starting engine.
I0405 11:13:27.655957  6468 engine.cc:126] updated option: simplification
I0405 11:13:27.655957  6468 engine.cc:126] updated option: _auto_commit
I0405 11:13:27.655957  6468 dictionary.cc:265] loading dictionary 'luna_pinyin'.
E0405 11:13:27.655957  6468 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
I0405 11:13:27.655957  6468 deployer.cc:114] starting work thread for 1 tasks.
I0405 11:13:27.655957  6328 deployer.cc:83] running deployment tasks:
I0405 11:13:27.655957  6328 level_db.cc:233] trying to recover db 'luna_pinyin.userdb'.
I0405 11:13:27.655957  6468 engine.cc:126] updated option: ascii_mode
I0405 11:13:27.655957  6468 engine.cc:139] updated property: client_app
I0405 11:13:27.655957  6468 engine.cc:139] updated property: client_type
I0405 11:13:27.655957  6468 engine.cc:126] updated option: inline_preedit
I0405 11:13:27.655957  6468 engine.cc:126] updated option: soft_cursor
I0405 11:13:27.671584  6328 level_db.cc:236] repair finished.
E0405 11:13:27.671584  6328 level_db.cc:242] db recovery failed: OK
I0405 11:13:27.671584  6328 user_db_recovery_task.cc:43] recreating db file.
E0405 11:13:27.671584  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:13:27.671584  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
I0405 11:13:27.671584  6328 deployer.cc:95] 1 tasks ran: 0 success, 1 failure.
I0405 11:13:33.481039  6468 engine.cc:92] engine disposed.
I0405 11:14:04.085433  8092 engine.cc:71] starting engine.
I0405 11:14:04.085433  8092 engine.cc:126] updated option: simplification
I0405 11:14:04.085433  8092 engine.cc:126] updated option: _auto_commit
I0405 11:14:04.085433  8092 dictionary.cc:265] loading dictionary 'luna_pinyin'.
E0405 11:14:04.085433  8092 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
I0405 11:14:04.085433  8092 deployer.cc:114] starting work thread for 1 tasks.
I0405 11:14:04.085433  8092 engine.cc:126] updated option: ascii_mode
I0405 11:14:04.085433  8092 engine.cc:139] updated property: client_app
I0405 11:14:04.085433  8092 engine.cc:139] updated property: client_type
I0405 11:14:04.085433  8092 engine.cc:126] updated option: inline_preedit
I0405 11:14:04.085433  8092 engine.cc:126] updated option: soft_cursor
I0405 11:14:04.085433  6328 deployer.cc:83] running deployment tasks:
I0405 11:14:04.085433  6328 level_db.cc:233] trying to recover db 'luna_pinyin.userdb'.
I0405 11:14:04.101060  6328 level_db.cc:236] repair finished.
E0405 11:14:04.101060  6328 level_db.cc:242] db recovery failed: OK
I0405 11:14:04.101060  6328 user_db_recovery_task.cc:43] recreating db file.
E0405 11:14:04.101060  6328 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:14:04.101060  6328 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
I0405 11:14:04.101060  6328 deployer.cc:95] 1 tasks ran: 0 success, 1 failure.
I0405 11:15:43.669181  8092 simplifier.cc:35] initializing opencc: C:\Program Files (x86)\Rime\weasel-0.10.0\data\opencc\t2s.json
I0405 11:17:06.848287  6052 engine.cc:71] starting engine.
I0405 11:17:06.848287  6052 engine.cc:126] updated option: simplification
I0405 11:17:06.848287  6052 engine.cc:126] updated option: _auto_commit
I0405 11:17:06.848287  6052 dictionary.cc:265] loading dictionary 'luna_pinyin'.
E0405 11:17:06.848287  6052 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
I0405 11:17:06.848287  6052 deployer.cc:114] starting work thread for 1 tasks.
I0405 11:17:06.848287  6708 deployer.cc:83] running deployment tasks:
I0405 11:17:06.848287  6708 level_db.cc:233] trying to recover db 'luna_pinyin.userdb'.
I0405 11:17:06.848287  6052 engine.cc:126] updated option: ascii_mode
I0405 11:17:06.848287  6052 engine.cc:139] updated property: client_app
I0405 11:17:06.848287  6052 engine.cc:139] updated property: client_type
I0405 11:17:06.848287  6052 engine.cc:126] updated option: inline_preedit
I0405 11:17:06.848287  6052 engine.cc:126] updated option: soft_cursor
I0405 11:17:06.863916  6708 level_db.cc:236] repair finished.
E0405 11:17:06.863916  6708 level_db.cc:242] db recovery failed: OK
I0405 11:17:06.863916  6708 user_db_recovery_task.cc:43] recreating db file.
E0405 11:17:06.863916  6708 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:17:06.863916  6708 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
I0405 11:17:06.863916  6708 deployer.cc:95] 1 tasks ran: 0 success, 1 failure.
I0405 11:17:16.207363  8092 engine.cc:92] engine disposed.
I0405 11:18:32.379779  6500 engine.cc:71] starting engine.
I0405 11:18:32.379779  6500 engine.cc:126] updated option: simplification
I0405 11:18:32.379779  6500 engine.cc:126] updated option: _auto_commit
I0405 11:18:32.379779  6500 dictionary.cc:265] loading dictionary 'luna_pinyin'.
E0405 11:18:32.379779  6500 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
I0405 11:18:32.379779  6500 deployer.cc:114] starting work thread for 1 tasks.
I0405 11:18:32.379779  6708 deployer.cc:83] running deployment tasks:
I0405 11:18:32.379779  6708 level_db.cc:233] trying to recover db 'luna_pinyin.userdb'.
I0405 11:18:32.379779  6500 engine.cc:126] updated option: ascii_mode
I0405 11:18:32.379779  6500 engine.cc:139] updated property: client_app
I0405 11:18:32.379779  6500 engine.cc:139] updated property: client_type
I0405 11:18:32.379779  6500 engine.cc:126] updated option: inline_preedit
I0405 11:18:32.379779  6500 engine.cc:126] updated option: soft_cursor
I0405 11:18:32.411031  6708 level_db.cc:236] repair finished.
E0405 11:18:32.411031  6708 level_db.cc:242] db recovery failed: OK
I0405 11:18:32.411031  6708 user_db_recovery_task.cc:43] recreating db file.
E0405 11:18:32.411031  6708 level_db.cc:253] Error removing db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
E0405 11:18:32.411031  6708 user_db_recovery_task.cc:48] Error removing db file 'C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb'.
I0405 11:18:32.411031  6708 deployer.cc:95] 1 tasks ran: 0 success, 1 failure.
I0405 11:19:19.472134 10000 engine.cc:71] starting engine.
I0405 11:19:19.472134 10000 engine.cc:126] updated option: simplification
I0405 11:19:19.472134 10000 engine.cc:126] updated option: _auto_commit
I0405 11:19:19.472134 10000 dictionary.cc:265] loading dictionary 'luna_pinyin'.
E0405 11:19:19.472134 10000 level_db.cc:277] Error opening db 'luna_pinyin.userdb': IO error: acquiring lock C:\Users\outca\AppData\Roaming\Rime\luna_pinyin.userdb/LOCK failed
I0405 11:19:19.472134 10000 deployer.cc:114] starting work thread for 1 tasks.
I0405 11:19:19.472134  6708 deployer.cc:83] running deployment tasks:
I0405 11:19:19.472134  6708 level_db.cc:233] trying to recover db 'luna_pinyin.userdb'.
I0405 11:19:19.472134 10000 engine.cc:126] updated option: ascii_mode
I0405 11:19:19.472134 10000 engine.cc:139] updated property: client_app
I0405 11:19:19.472134 10000 engine.cc:139] updated property: client_type
I0405 11:19:19.472134 10000 engine.cc:126] updated option: inline_preedit
I0405 11:19:19.472134 10000 engine.cc:126] updated option: soft_cursor
I0405 11:19:19.519013  6708 level_db.cc:236] repair finished.

**Comment by lotem** [comment]
log 反映的是 无法以独占方式打开用户词典 尝试修复用户词典也失败了
我想问是不是用网盘同步了整个用户文件夹（用户词典所在）。按照设计用法只须同步 sync 文件夹。

**Comment by Hermittttt** [comment]
您好：
我是使用的教程里面的方式更改用户文件夹里面的installation.yaml中sync_dir的方式实现的用户同步，在网盘的同步文件夹下只有两个名字为UUID的文件夹（分别是我的两个终端），里面的文件有
default.custom.yaml
double_pinyin_flypy.schema.yaml
installation.yaml
luna_pinyin.userdb.txt
user.yaml
weasel.custom.yaml
这几个文件

**Comment by lotem** [comment]
听上去同步配置没有问题
那么是谁锁住了用户词典呢？
手动删除 `luna_pinyin.userdb` 再试试吧。

**Comment by Hermittttt** [comment]
好的我试一试，如果之后再出现这个情况的话再向您反馈

**Comment by LearZhou** [comment]
lotem，按照你說的步驟，手動刪除了luna_pinyin.userdb之後仍然會報錯，錯誤跟樓主所遇到的類似。這個錯誤出現的頻率非常高，稍微切換一下窗口或者是關閉、打開輸入法就可能會出現。

或者是輸入一段文字之後、切換一下輸入法狀態，再敲擊其他鍵，比如回車，很容易就會出現。

**Comment by HatuneMiku** [comment]
@LearZhou 你按照 #199 中提到直接在开始菜单启动 `小狼毫算法服务` 看是否能暂时性的解决这个问题。

**Comment by daszzzpg** [comment]
这个问题并没有解决，在win10，v0.15中复现
