### ISSUE TITLE
在多用戶同時運行時無法正確顯示候選頁

### ISSUE THREAD

**Issue by Fei1Yang** [rime/weasel#176]
當PC內有多個用戶,且有兩個及以上用戶均已登入並運行小狼毫算法服務後,候選頁將只會在最後一個用戶的屏幕上顯示,且該用戶無法控制改候選頁

**Comment by nameoverflow** [comment]
没有条件测试，应该解决了。

**Comment by Prcuvu** [comment]
随 0.11.0 发行先关闭。如果还有问题可以重开。
