### ISSUE TITLE
懇請把異體字「爲」（第一選項）改正成「為」（排序於很後面的選字）

### ISSUE THREAD

**Issue by transfabulation** [rime/weasel#177]
方便繁體中文使用者，懇請你把異體字「爲」（wei音的第一選項）改正成「為」（排序於很後面的選字）。謝謝！

**Comment by mrhso** [comment]
OpenCC 標是「爲」，所以不能動。
若是想要用台標的話請自行進行 OpenCC 轉換。
另外詞庫本身不要在該項目進行提問。

**Comment by nameoverflow** [comment]
默认词库标准使用「爲」。如果有需求可以自行配置台湾标准转换将所有的「爲」转换成「為」。
具体方法参考自带的「bopomofo_tw.schema」台湾标准注音输入法。

**Comment by lotem** [comment]
「爲」是正字。「為」纔是異體字。

**Comment by jsdryan** [comment]
> 這個要請你自己改essay.txt 這個八股文詞庫中的數值了 搜尋「為」目前數值為684，數值改成211329就跟「爲」一樣的順位了 改完儲存後，再重新部署輸入法，應該就會調上去了。
> 
> 「為」的部分我跟作者討論過，他應該是不會調高數值了，你只能自己改自己用了。 我本來是偏向讓「為」跟「爲」數值差不多，這樣詞的順序就能預設在1跟2的位置，不過被否決了。
> 
> @lotem

請問有具體的修改方式嗎？
在 `C:\Users\Administrator\AppData\Roaming\Rime` 目錄中沒有搜尋到 `essay.txt` 這個檔案。

**Comment by kenner116** [comment]
> > 這個要請你自己改essay.txt 這個八股文詞庫中的數值了 搜尋「為」目前數值為684，數值改成211329就跟「爲」一樣的順位了 改完儲存後，再重新部署輸入法，應該就會調上去了。
> > 「為」的部分我跟作者討論過，他應該是不會調高數值了，你只能自己改自己用了。 我本來是偏向讓「為」跟「爲」數值差不多，這樣詞的順序就能預設在1跟2的位置，不過被否決了。
> > @lotem
> 
> 請問有具體的修改方式嗎？ 在 `C:\Users\Administrator\AppData\Roaming\Rime` 目錄中沒有搜尋到 `essay.txt` 這個檔案。

在 C:\Program Files (x86)\Rime\weasel-0.15.0\data 可以找到 essay.txt

**Comment by r-auyeung** [comment]
問題2018年已被提出，想不到到了2025年還沒有改正。就算用搜狗也是用「為」的。對於開發人員的固執感到莫名其妙。

**Comment by lotem** [comment]
> 問題2018年已被提出，想不到到了2025年還沒有改正。就算用搜狗也是用「為」的。對於開發人員的固執感到莫名其妙。

「爲」是正字，「為」是異體字，何謂之「改正」？
推薦的做法是用 Rime/OpenCC 提供的字形轉換功能，比如轉換成以「為」爲準的臺灣字形。

**Comment by r-auyeung** [comment]
> > 問題2018年已被提出，想不到到了2025年還沒有改正。就算用搜狗也是用「為」的。對於開發人員的固執感到莫名其妙。
> 
> 「爲」是正字，「為」是異體字，何謂之「改正」？ 推薦的做法是用 Rime/OpenCC 提供的字形轉換功能，比如轉換成以「為」爲準的臺灣字形。

總之所有繁體字的地區都使用「為」，其他拼音輸入法例如搜狗、谷歌也是用「為」，而且相信不是所有繁體字字型都有「爲」字，不明白為什麼要為難我們去做轉換。

**Comment by fxliang** [comment]
「爲」和「為」是汉字「为」的两种不同字形变体，它们的**含义和用法完全相同**，区别仅在于字形来源和地域使用习惯：

1. **「為」**  
   - 是**日本新字体**、**韩国标准字形**以及**中国大陆旧字形**（见于繁体中文语境）的写法。  
   - 在台湾、香港等繁体中文地区，也普遍使用「為」作为标准字形。

2. **「爲」**  
   - 是**传统繁体字**的旧字形（多见于古籍、书法或历史文本），但现代繁体中文已逐渐统一为「為」。  
   - 该字形更接近甲骨文、小篆的象形起源（手牵象劳作，表示“做”的含义）。

3. **简体中文**  
   - 中国大陆简化后统一写作「为」，与日文新字体「為」形近但不同。

---

**总结**：  
- **意义无区别**，均表示“做、成为、作为”等义。  
- **现代繁体标准多用「為」**（港台日韩），「爲」多见于历史文献或艺术场景。  
- 简体中文统一用「为」。

例如：  
- 「为人民服务」（简体）→ 「為人民服務」（繁体）  
- 古籍中可能写「天下爲公」，但现代印刷通常作「天下為公」。

---

以上引用自AI。Rime的默认繁体如果没有记错是「传统繁体字」，所以是「爲」。

至于为什么那些主流输入法都用「為」大概是因为他们不严谨或者懒？

从可用性上来说，librime提供了基本方案，用户可以在这个基础上自行修改定制，如果用户更倾向于用「為」也已有方案可以实现。要求librime放弃「传统繁体字」似乎并不合适。

PS, 这个议题更多的是opencc或者librime相关了。

**Comment by lotem** [comment]
應該不難的。
不需要用家手動轉換詞庫，只要打開地區字形轉換的選項就可以。
簡化字也是這樣轉換出來的。

如果按照用家多寡，也輪不到「為」；簡化字「为」用家最多。
不止大陸用簡化字，臺灣常用的字形有很多俗字，如「為」「裡」「眾」，《康熙字典》以及近代以來的工具書都以「爲」「裏」「衆」爲正。大陸出版的繁體書籍、中文系教材一直使用「爲」「裏」「衆」。

這是個技術上的取捨。
用 OpenCC 整理好的傳統字形維護詞典，可以以最小的損耗轉換成各種常用的地區用字標準。
不然要陷入無休止的討論和反覆修改。
