### ISSUE TITLE
Windows Server 2016 中 Win+S 进行搜索时, 弹出的框会覆盖到选词框

### ISSUE THREAD

**Issue by RigHakiko** [rime/weasel#179]
![image](https://user-images.githubusercontent.com/17807588/38452225-62b03ddc-3a72-11e8-89d9-67f15a701bad.png)

这应该是Windows太垃圾的原因, 但不指望微软会去搞, 
所以希望能否可以在输入法上做一下妥协式的修复, 或是用什么其它的方式什么的

**Comment by zhtw2013** [comment]
這個下一版正式版就修復了，請耐心等待。
![image](https://user-images.githubusercontent.com/9501406/38452856-fe195f2c-3a7e-11e8-812b-b9854f7091de.png)
