### ISSUE TITLE
关于安装包的讨论

### ISSUE THREAD

**Issue by lifenjoiner** [rime/weasel#180]
有两点：
1. 什么时候完全转到 TSF 模式呢？要是不准备这么做，应该加个选择安装 IME 和 TSF 的选项吧？
2. 最近的安装包里怎么都打包了`ime-install-config.bat`和`ime-install.bat`呀？
就为了一个“获取理多输入方案”，安装整个庞大的开发环境的对普通用户不太合适吧？与 RIME 的风格不符啊~ 我的开发环境都是自己维护不写环境变量的😜

**Comment by lotem** [comment]
「權宜之計」嘛？

關於問題 2. 
這兩個文件是啓動腳本及其配置，非常小的純文本文件，且安裝過程中並不會自動調用。可謂安全環保。
用戶點擊「獲取更多輸入方案」的時候，會在線安裝配置管理器（全部由腳本組成）及必要的腳本運行環境（Git+Bash），而不是開發環境。

**Comment by lifenjoiner** [comment]
> 必要的腳本運行環境（Git+Bash），而不是開發環境

是的，之前我说的不够确切。`Git for windows`是在`MSYS2`的基础上构建运行的，安装后约200M，我是有的。

也就是提一下，各位有安排当然最好~

目前，我手动安装了几次，可行，准备写个解压覆盖安装脚本自己用，就可以不安装两个输入法再手动删除一个，一般也不用重启啦。

**Comment by GoodbyeNJN** [comment]
当前`0.11.1`版本点击“获取更多输入方案”的时候，脚本的直接自动下载 Git for Windows 的安装包，正确逻辑应该是先检测当前环境下`git`命令是否可用，然后再去判断是否下载

**Comment by Prcuvu** [comment]
> 正确逻辑应该是先检测当前环境下git命令是否可用，然后再去判断是否下载

我们检测是否能找到 bash，若不能则下载 Git for Windows。因为 Windows 的脚本只起引导作用，它最终还是要调用 Shell 脚本。若已安装 Git for Windows，请确保将其附带的 Unix 工具集目录加入 `PATH`。

**Comment by lotem** [comment]
@GoodbyeNJN @Prcuvu 這麼說，在腳本開頭（檢測 `bash` 之前）把默認安裝目錄加到 `PATH` 也許有幫助。

**Comment by lifenjoiner** [comment]
> Closed #180 via 2f3b283

使用 WinSSL 编译的 curl.exe 能大幅减小文件大小

**Comment by Prcuvu** [comment]
> 使用 WinSSL 编译的 curl.exe 能大幅减小文件大小

我们使用的正是链接了 WinSSL 的版本。
