### ISSUE TITLE
Firefox 下密码框不会直接输入也不显示选词框

### ISSUE THREAD

**Issue by lifenjoiner** [rime/weasel#182]
Build 68，win 7

输入时是带下划线的，但是又不显示选词框……
试了IE、chromium，是直接输入的。

**Comment by jiangming1399** [comment]
win10 with ff 59
使用非TSF输入法没有复现，使用TSF输入法会显示输入框。两种情况下都能使用。

**Comment by zzColin** [comment]
我和 @jiangming1399 的情况一样，Windows 10 x64 + Firefox 59.0.3 x64，虽然用起来没什么本质上的问题，但确实属于是不正常行为。

**Comment by lifenjoiner** [comment]
陈旧的。
Win10 22H2 + FF v115 + Weasel v0.15，显示选词框。
