### ISSUE TITLE
0.11.0 被判定為有害軟體且安裝後無法輸出中文

### ISSUE THREAD

**Issue by paultw** [rime/weasel#183]
使用作業系統：Windows 10 pro 64-bit
防毒軟體： AVAST
使用語言方案：台灣注音

安裝方式：由0.10版本反安裝之後，更新至0.11 

出現問題：
1. 防毒軟體將『uninstall.exe』判定為威脅，威脅名稱為：「FileRepMalware」並進行隔離。
2.無法輸出中文。。。 重開機、重新部署後也是一樣只有英文出現

**Comment by Guwalgiyakuan** [comment]
2.跟人经验是备份用户文件夹删除后重建

**Comment by ckimdotcn** [comment]
刚在开发者的协助下解决了这个问题，麻烦贴一下最近的一次错误日志。在%temp%里面搜索rime。查看最后一次的重新布署的ERROR。
——————
我的情况是因为default.ymal的key_binding部分无法合并导致的。

**Comment by paultw** [comment]
Log file created at: 2018/04/10 11:09:03
Running on machine: USR
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
 core_module.cc:20] registering core components.
 registry.cc:14] registering component: config_builder
 registry.cc:14] registering component: config
 registry.cc:14] registering component: schema
 registry.cc:14] registering component: user_config
 dict_module.cc:24] registering components from module 'dict'.
 registry.cc:14] registering component: tabledb
 registry.cc:14] registering component: stabledb
 registry.cc:14] registering component: plain_userdb
 registry.cc:14] registering component: userdb
 registry.cc:14] registering component: dictionary
 registry.cc:14] registering component: reverse_lookup_dictionary
 registry.cc:14] registering component: user_dictionary
 registry.cc:14] registering component: userdb_recovery_task
 levers_module.cc:23] registering components from module 'levers'.
 registry.cc:14] registering component: detect_modifications
 registry.cc:14] registering component: installation_update
 registry.cc:14] registering component: workspace_update
 registry.cc:14] registering component: schema_update
 registry.cc:14] registering component: config_file_update
 registry.cc:14] registering component: prebuild_all_schemas
 registry.cc:14] registering component: user_dict_upgrade
 registry.cc:14] registering component: cleanup_trash
 registry.cc:14] registering component: user_dict_sync
 registry.cc:14] registering component: backup_config_files
 registry.cc:14] registering component: clean_old_log_files
 deployment_tasks.cc:80] updating rime installation info.
 config_data.cc:65] loading config file 'C:\Users\user\RIME輸入法字庫\installation.yaml'.
 deployment_tasks.cc:98] installation info exists. installation id: fb51f28a-ddd9-4bd7-8ecc-bfd161e2f894
 deployment_tasks.cc:106] sync dir: C:\Users\user\RIME輸入法字庫\sync
 deployment_tasks.cc:108] previous distribution: Weasel
 deployment_tasks.cc:111] previous distribution version: 0.11.0
 deployment_tasks.cc:114] previous Rime version: 1.3.1
 deployment_tasks.cc:160] updating workspace.
 config_data.cc:65] loading config file 'C:\Users\user\RIME輸入法字庫\build/default.yaml'.
 config_data.cc:65] loading config file 'C:\Users\user\RIME輸入法字庫\build/default.yaml'.
 deployment_tasks.cc:183] updating schemas.
 deployment_tasks.cc:193] schema: bopomofo_tw
 config_data.cc:65] loading config file 'C:\Program Files (x86)\Rime\weasel-0.11.0\data\bopomofo_tw.schema.yaml'.
 config_data.cc:65] loading config file 'C:\Users\user\RIME輸入法字庫\build/bopomofo_tw.schema.yaml'.
 config_data.cc:65] loading config file 'C:\Users\user\RIME輸入法字庫\build/bopomofo_tw.schema.yaml'.
 deployment_tasks.cc:352] preparing dictionary 'terra_pinyin'.
 dict_compiler.cc:38] compiling dictionary for C:\Users\user\RIME輸入法字庫\build/bopomofo_tw.schema.yaml
 dict_compiler.cc:53] dict name: terra_pinyin
 dict_compiler.cc:54] dict version: 2018.03.23
 table.cc:299] loading table file: C:\Users\user\RIME輸入法字庫\build/terra_pinyin.table.bin
 prism.cc:77] loading prism file: C:\Users\user\RIME輸入法字庫\build/bopomofo_tw.prism.bin
 prism.cc:107] found double array image of size 4608.
 dict_compiler.cc:106] C:\Users\user\RIME輸入法字庫\terra_pinyin.dict.yaml[1 file(s)] (898191413)
 dict_compiler.cc:108] C:\Users\user\RIME輸入法字庫\build/bopomofo_tw.schema.yaml (2217744055)
 reverse_lookup_dictionary.cc:33] loading reversedb: C:\Users\user\RIME輸入法字庫\build/terra_pinyin.reverse.bin
 deployment_tasks.cc:370] dictionary 'terra_pinyin' is ready.
 config_data.cc:65] loading config file 'C:\Users\user\RIME輸入法字庫\build/bopomofo_tw.schema.yaml'.
 deployment_tasks.cc:193] schema: cangjie5
 config_data.cc:65] loading config file 'C:\Program Files (x86)\Rime\weasel-0.11.0\data\cangjie5.schema.yaml'.
 config_data.cc:65] loading config file 'C:\Users\user\RIME輸入法字庫\build/cangjie5.schema.yaml'.
I0410 11:09:03.230371  2084 config_data.cc:65] loading config file 'C:\Users\user\RIME輸入法字庫\build/cangjie5.schema.yaml'.
I0410 11:09:03.245996  2084 deployment_tasks.cc:352] preparing dictionary 'cangjie5'.
I0410 11:09:03.245996  2084 dict_compiler.cc:38] compiling dictionary for C:\Users\user\RIME輸入法字庫\build/cangjie5.schema.yaml
I0410 11:09:03.245996  2084 dict_compiler.cc:53] dict name: cangjie5
I0410 11:09:03.245996  2084 dict_compiler.cc:54] dict version: 0.18
 table.cc:299] loading table file: C:\Users\user\RIME輸入法字庫\build/cangjie5.table.bin
 prism.cc:77] loading prism file: C:\Users\user\RIME輸入法字庫\build/cangjie5.prism.bin
 prism.cc:107] found double array image of size 567808.
 dict_compiler.cc:106] C:\Program Files (x86)\Rime\weasel-0.11.0\data\cangjie5.dict.yaml[1 file(s)] (1358868578)
 dict_compiler.cc:108] C:\Users\user\RIME輸入法字庫\build/cangjie5.schema.yaml (3501380967)
 reverse_lookup_dictionary.cc:33] loading reversedb: C:\Users\user\RIME輸入法字庫\build/cangjie5.reverse.bin
 deployment_tasks.cc:370] dictionary 'cangjie5' is ready.
 deployment_tasks.cc:235] finished updating schemas: 2 success, 0 failure.
 config_data.cc:65] loading config file 'C:\Users\user\RIME輸入法字庫\user.yaml'.
 config_data.cc:199] write: var/last_build_time
 config_data.cc:85] saving config file 'C:\Users\user\RIME輸入法字庫\user.yaml'.
 legacy_module.cc:17] registering components from module 'legacy'.
 registry.cc:14] registering component: treedb
 registry.cc:14] registering component: legacy_userdb
 deployment_tasks.cc:579] clean up trash.
 config_data.cc:65] loading config file 'C:\Users\user\RIME輸入法字庫\build/weasel.yaml'.

**Comment by paultw** [comment]
Log file created at: 2018/04/10 09:06:28
Running on machine: USR
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0410 09:06:28.743525 11104 simplifier.cc:141] please upgrade opencc_config to an opencc 1.0 config file.
E0410 09:08:07.746757 10984 simplifier.cc:141] please upgrade opencc_config to an opencc 1.0 config file.

**Comment by paultw** [comment]
Log file created at: 2018/04/10 09:10:01
Running on machine: USR
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0410 09:10:01.205257  1912 config_data.cc:62] nonexistent config file 'C:\Users\user\RIME輸入法字庫\bopomofo_tw.custom.yaml'.
W0410 09:10:01.806370  1912 entry_collector.cc:192] duplicate word definition '蟡?: [mi4].
W0410 09:10:01.806370  1912 entry_collector.cc:192] duplicate word definition '蝘?: [mi4].
W0410 09:10:02.188642  1912 entry_collector.cc:144] Encode failure: '銝?.
W0410 09:10:02.240679  1912 entry_collector.cc:144] Encode failure: '銋?.
W0410 09:10:02.245682  1912 entry_collector.cc:144] Encode failure: '銋?.
W0410 09:10:02.245682  1912 entry_collector.cc:144] Encode failure: '銋?.
W0410 09:10:02.245682  1912 entry_collector.cc:144] Encode failure: '銋?.
W0410 09:10:02.245682  1912 entry_collector.cc:144] Encode failure: '銋?.
W0410 09:10:02.246683  1912 entry_collector.cc:144] Encode failure: '銋?.
W0410 09:10:02.246683  1912 entry_collector.cc:144] Encode failure: '銋?.
W0410 09:10:02.246683  1912 entry_collector.cc:144] Encode failure: '銋?.
W0410 09:10:02.267699  1912 entry_collector.cc:144] Encode failure: '鈭?.
W0410 09:10:02.277705  1912 entry_collector.cc:144] Encode failure: '隞?.
W0410 09:10:02.282709  1912 entry_collector.cc:144] Encode failure: '隞?.
W0410 09:10:02.287712  1912 entry_collector.cc:144] Encode failure: '隡?.
W0410 09:10:02.381779  1912 entry_collector.cc:144] Encode failure: '??.
W0410 09:10:02.427814  1912 entry_collector.cc:144] Encode failure: '??.
W0410 09:10:02.429814  1912 entry_collector.cc:144] Encode failure: '??.
W0410 09:10:02.460836  1912 entry_collector.cc:144] Encode failure: '??.
W0410 09:10:02.512874  1912 entry_collector.cc:144] Encode failure: '??.
W0410 09:10:02.577932  1912 entry_collector.cc:144] Encode failure: '??.
............................
W0410 09:10:08.677711  1912 entry_collector.cc:192] duplicate word definition '朣?': [yxseo].
W0410 09:10:08.677711  1912 entry_collector.cc:192] duplicate word definition '朣?銝??: [yomg].
W0410 09:10:08.677711  1912 entry_collector.cc:192] duplicate word definition '朣?銝??: [yomg].
..........................
LOG太多，後面一大堆都是類似訊息

**Comment by zhtw2013** [comment]
我已提交誤報了，等待Avast解除。
