### ISSUE TITLE
关于输入法候选框漂移问题

### ISSUE THREAD

**Issue by PawnXIE** [rime/weasel#184]
发现在一些特定软件里输入法的候选框经常不位于输入光标的下方，漂移到了屏幕中的其他地方，无法确定是输入法问题还是软件问题，如图1和图2，候选框完全盖住了输入框。
触发条件：Chrome浏览器网页界面，按ctrl+f进行搜索，第一次搜索会偶发这种情况，esc取消重新ctrl+f一般就正常了。
![weasel1](https://user-images.githubusercontent.com/37367889/38530955-255208aa-3ca0-11e8-88f6-8160abcdcea5.png)
图1
![weasel2](https://user-images.githubusercontent.com/37367889/38531028-8af9e95c-3ca0-11e8-897a-b4d8a4f93a17.png)
图2

另一个问题百分百复现的地方就是Android Studio 3.1，候选框会偏到屏幕角落里，如图3和4
![weasel3](https://user-images.githubusercontent.com/37367889/38531237-76797a5a-3ca1-11e8-96f9-77bc796a4818.png)
图3
![weasel4](https://user-images.githubusercontent.com/37367889/38531244-7bc4b1e6-3ca1-11e8-9d84-c24248bcf3fd.png)
图4
PS：微软自带输入法的候选框同样偏到屏幕角落里，初步怀疑是这个版本AS的问题，因为在之前小狼毫0.10.0+Android Studio 3.0.1无此问题（需要说明的是小狼毫0.10.0+Android Studio 2.3.2有此问题，感觉Google大锅，亦在AS内向Google反馈此问题），因为均发现了漂移现象，所以一并都讲出来

软件及系统版本清单：
Chrome 65.0.3325.181 64位稳定版

Android Studio 3.1
Build #AI-173.4670197, built on March 22, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Windows 10 1803（即17133.1，即将发布的1803rtm泄漏版？）

最后补一个其他的小bug：
电脑锁屏再登录，0.10.0和0.11.0这两版都会偶发输入法候选框样式缺陷问题，表现在：
1、偶发性丢失了候选框里的123456序号数字；
2、候选框字体变得模糊
解决办法是移除用户文件夹的weasel.custom.yaml重新部署完成后，再移入weasel.custom.yaml再部署一遍即可恢复正常

**Comment by nameoverflow** [comment]
AS 是因为 JB 自带 JDK 有问题，见#100

**Comment by PawnXIE** [comment]
@nameoverflow  Chrome里的问题依旧存在，早上复现比较容易，这会我试了一下倒是挺难复现了==感谢你们的工作~~

**Comment by nameoverflow** [comment]
https://github.com/rime/weasel/commit/5664481cc9ddd28db35c3155f7ddf83a55b65275 更改了定位方式，如果还有问题再 open 。

**Comment by zeleven** [comment]
@nameoverflow Linux （Deepin）下有相同的问题

**Comment by HymanZHAN** [comment]
@nameoverflow Linux (Fedora 30)有同样的问题，没有全部app都测试过但是electron-based的app都中招了
![Screenshot from 2019-08-22 10-38-37](https://user-images.githubusercontent.com/26806995/63524006-30efc000-c4c9-11e9-9107-1e87e4b01636.png)
![Screenshot from 2019-08-22 10-39-20](https://user-images.githubusercontent.com/26806995/63524008-30efc000-c4c9-11e9-83c3-b3266ef2680c.png)

**Comment by wmsxwdsh** [comment]
m1 mac 的chrome 还有此问题，不是 rime 的问题，是 chrome 的问题，中文输入框漂移，safari 就没有这个问题。几年过去了，这 bug 居然还在，真是服了
