### ISSUE TITLE
Excel中输入第一个字母无效

### ISSUE THREAD

**Issue by keman1984** [rime/weasel#185]
如：要输入“beijing”，实际输入的是“eijing”

**Comment by wrlssqi** [comment]
同样的问题，win10 1709， excel 2016。weasel 0.11.0版本。只在tsf模式下存在此问题。每选中一个单元格，输入，第一个字母就无效。
![image](https://user-images.githubusercontent.com/9946624/38540618-1a855f38-3ccf-11e8-87b7-cf6437cbb042.png)

**Comment by lifenjoiner** [comment]
因为焦点切换而被丢弃了吧……
选中时还没有进入编辑模式。双击进入后是正常的。

**Comment by deangl** [comment]
@Prcuvu Excel 2016，weasel 0.11.0，weasel.custom.yaml中加了
``` yaml
patch:
  "style/inline_preedit": true
```
也没有用，第一个字符在格子里会inline出来，但是还是被丢弃了。

**Comment by lifenjoiner** [comment]
能否新焦点在同一进程且可编辑的时候不丢弃？

**Comment by oopp1800** [comment]
希望早日修复，weasel 0.11.0 在使用 notation 过程中也经常出现输入拼音时未上屏内容丢失问题，猜测是在同步内容与列表时切换了焦点导致的

**Comment by bingo1021** [comment]
遇到同样问题，希望早日修复！

**Comment by fan123199** [comment]
一样出现，tsf模式。

**Comment by daf3707** [comment]
同样发现这样的问题，搜索到此处了。期待解决.

**Comment by nigel4zh** [comment]
Win10，Excel2013遇到同样问题

**Comment by truthciao** [comment]
excel 2019 1904 同样的问题

**Comment by nameoverflow** [comment]
现在 Excel 还有问题？

**Comment by dengshiyong** [comment]
对，现在wps表格里还有问题，我用的版本是weasel-0.14.3，比如我想打“同志们好”，我先输入“同志们”，然后等上几秒钟再输入“好”，但这时候出现的是“ao”，而不是“hao”
后面是我的截图
![image](https://user-images.githubusercontent.com/2323137/61454255-f5764900-a992-11e9-9cfc-91360aa445d6.png)

**Comment by ytao** [comment]
我也遇到同样的问题了。
win10系统：wps2019个人版出现此问题，office2016无此问题。
