### ISSUE TITLE
weasel.custom.yaml中app_options选项不起作用

### ISSUE THREAD

**Issue by dshbusiness** [rime/weasel#186]
patch:
  "style/color_scheme": android
  "style/display_tray_icon": true
  app_options/Xshell.exe:
    ascii_mode: true
  app_options/XshellCore.exe:
    ascii_mode: true
  app_options/notepad++.exe:
    ascii_mode: true

————————————————————————

配置如上，重新部署后发现在notepad++及xshell中仍然可以输入中文。

且，重新部署有概率引起界面无响应。

系统win7，rime版本，0.11.0.0
[weasel.custom.txt](https://github.com/rime/weasel/files/1893022/weasel.custom.txt)

**Comment by wrlssqi** [comment]
patch没写对吧。 "app_options/Xshell.exe/ascii_mode": true 这样子写

**Comment by lotem** [comment]
Duplicate of https://github.com/rime/weasel/issues/79

**Comment by wrlssqi** [comment]
我试了下按照帮助文档里格式写，也可以生效的。应该就是你把程序名称写错了。帮助文档里有提到要程序名称要用小写。patch有没有生效，只需要重新部署后，进到用户文件夹下的build文件夹里，打开对应的yaml文档，看看里面有没有自己打的patch的内容，就能知道patch写没写对。例如我加了个code.exe
![image](https://user-images.githubusercontent.com/9946624/38542122-9b94c150-3cd3-11e8-8995-4476376a5bc5.png)
