### ISSUE TITLE
糟糕了！升級新版本之後宮保拼音變得不好用了！

### ISSUE THREAD

**Issue by alsophila** [rime/weasel#187]
首先祝賀版本更新！
不過在更新版本之後，我發現了一個小問題。
我在測試宮保拼音功能（因為平時疏於練習只能把使用稱為測試）的時候，發現新版本的退格鍵無法像舊版本一樣消除一整個字音，只能一個一個拼音字母刪去。
宮保拼音的並擊功能很新穎很好用，在舊版本之中，如果輸入錯誤，按下退格鍵後會刪除之前敲下的一整個字音。而新版本只會消去最後一個字母（第一次敲空格鍵居然只會消去最後的一個分隔符！），要想刪除整個字音需要敲好幾下退格，如果刪除不完全，繼續打字更是會錯誤百出！
使用宮保拼音的用戶是不是還是回滾一下比較好……

**Comment by lotem** [comment]
同 https://github.com/rime/librime/issues/195

请更新宫保拼音输入方案 https://github.com/rime/rime-combo-pinyin
