### ISSUE TITLE
windows10下mrhso-prime可能更好用

### ISSUE THREAD

**Issue by yyy123zc** [rime/weasel#188]
我在Windows10下以前用的是PRIME-1.1.0，但偶尔会出现输入框不能捕捉及其它的一些小bug。在贴吧浏览时发现@石Sashi发布的mrhso-prime，试用后除偶尔输入法候选框漂移无bug发现，同PIME一样只有一个输入法选项，TSF模式输入正常，WPS excl输入正常。并且是[类 Nightly]版，来此推荐。
贴吧地址：http://tieba.baidu.com/p/5463113029?red_tag=k2265802873
开源代码地址：https://ci.appveyor.com/project/mrhso/pime
                          https://ci.appveyor.com/project/mrhso/pime/build/artifacts

**Comment by yyy123zc** [comment]
抱歉，我并不会编程，不知道哪里违规了。你可以删除这个帖子，我没百度出GitHub怎么删除issue，麻烦你了。

**Comment by ysc3839** [comment]
这并没有开源吧？ AppVeyor 只是个构建平台。

**Comment by lotem** [comment]
沒有。我想你發錯了地方。
你在題目裏比較了 PRIME 輸入法的兩個版本。然而 PRIME 是另一個輸入法項目，項目地址是：
https://github.com/osfans/PRIME
這兒只受理小狼毫輸入法的錯誤報告。因爲跟本項目無關，我已經把這條信息關閉。

**Comment by yyy123zc** [comment]
抱歉。麻烦你了。
