### ISSUE TITLE
新状态栏图标右键无「用户资料同步」选项

### ISSUE THREAD

**Issue by oopp1800** [rime/weasel#189]
刚使用小狼毫不久，用户词库还在不断训练中，平时会使用两台电脑，所以经常会使用「用户资料同步」选项去同步两台电脑上的词库（这用法应该没错吧？根据文档我的理解是选择同步后会将本机用户词典备份至同步文件夹对应 id 的用户下，再将同步文件夹中所有用户的词库合并后存放至本机用户词典 :joy: ）
在更新 weasel 0.11.0 后发现新状态栏图标右键没有该选项了，不知是实现上有困难还是基于其它考虑呢？
![image](https://user-images.githubusercontent.com/12545349/38617973-eed57a7e-3dca-11e8-99fe-93cf5987abbd.png)

**Comment by nameoverflow** [comment]
暂时用开始菜单里的吧，忘加了。7a0a8cc 已补。
