### ISSUE TITLE
Win7下弹出框冲突

### ISSUE THREAD

**Issue by Limlift** [rime/weasel#191]
版本0.11.0，在本地程序弹出框时（如Chrome的保存文件弹出框，Photoshop的新建文件框），输入法与弹出框冲突，导致弹出框不断闪烁

**Comment by nameoverflow** [comment]
最新的 CI build 还有这个问题吗？

**Comment by dshbusiness** [comment]
我也遇到类似问题了，不过是弹出框隐藏到chrome等窗口背后，但是输入焦点还在。

**Comment by Limlift** [comment]
@dshbusiness 问题是一样的，你键盘一开始输入，弹出框和程序主体程序窗口前后关系不断变化，视觉上看来就是不断闪烁，但是输入焦点还在

**Comment by dshbusiness** [comment]
@Limlift 嗯，谢谢回复。这样看来，感觉应该是需要升级代码版本来解决了。我之前以为是我的配置问题。

**Comment by dshbusiness** [comment]
升级最0.11.1版本，我这里的弹窗问题已经解决
