### ISSUE TITLE
powerpoint 2016 weasel TSF 复制有问题

### ISSUE THREAD

**Issue by code-moritz** [rime/weasel#195]
在powerpoint 2016 中， 画一个文本框， 按住ctorl+鼠标左键，拖动文本框。 在默认是可以复制文本。 但在最新的0.11版本中是复制不了的， 但在非TSF下是可的， 在微软拼音上也是可以。 

这应该是个bug。

**Comment by nameoverflow** [comment]
Duplicate of #193
