### ISSUE TITLE
0.11.0 Win10下获取更多输入方案失败

### ISSUE THREAD

**Issue by bugcat** [rime/weasel#196]
看了一下报错，安装完GIT后，直接使用curl命令，报错无此命令，就终止了。
然后重新获取的话，也会重复安装GIT，反复如此，反正就是无法正常安装rime-install

**Comment by lotem** [comment]
Git 是安裝到默認安裝位置嘛？
如果另選了安裝目錄，需要在安裝步驟裏選擇把 git 和 Unix tools 路徑加入系統 PATH 變量，下次啓動這個腳本（也許要重新打開輸入法設置程序？）才能找到。

另外，很快就有新腳本可用，Git 是可選的。

**Comment by bugcat** [comment]
确实习惯性地安装到非默认目录，那我再重新安装试试。
另外期待新脚本

**Comment by lotem** [comment]
已經寫好了：
https://github.com/rime/plum#windows-bootstrap-script
