### ISSUE TITLE
win10 x64 下不定時當掉程式

### ISSUE THREAD

**Issue by s793016** [rime/weasel#197]
win10 x64 1790 (16299.371)
自 0.10.0 升上來後，不定時在打字中當掉作用中程式。
如在 chrome 打字就掛掉 chrome。
如在 excel 打字就掛掉 excel。
etc.
但之後輸入法還是可以正常使用。

0.10 時沒有遇過這問題。

**Comment by s793016** [comment]
第二天開始又會當掉了 ... orz

使用的是我自編的倉頡輸法法表格，在0.11之前都很正常。
0.11原先的症狀：輸入「這」字，系統就會彈窗告知程式當掉。
0.11清除 userdb 後的症狀：輸入「您」字，系統就會彈窗告知程式當掉。

附上的我自編碼表。
[倉頡3代.zip](https://github.com/rime/weasel/files/1922245/3.zip)

**Comment by Guwalgiyakuan** [comment]
感觉新版本读取旧版本配置或自定义词库的时候会有不明错误出现。如果都是全新生成的配置文件不添加自定义词库和设置使用两天来没有任何报错。不知是新老语法冲突还是哪里。

**Comment by nameoverflow** [comment]
![image](https://user-images.githubusercontent.com/10287709/39096633-6bc702c4-4685-11e8-9842-0f8fc5d6f02a.png)
压缩包损坏还是文件有问题？

**Comment by s793016** [comment]
0x80004005 應該是您的系統或儲存媒體有問題

**Comment by nameoverflow** [comment]
换了台电脑也无法解压。没有的复现汇报的话只能先搁置了。

**Comment by Guwalgiyakuan** [comment]
win10 64x 1709  用7z可以解壓文件查看。但看不懂。

**Comment by s793016** [comment]
原本的確是用 7zip 壓的，那我改用 rar 壓好了
[1.zip](https://github.com/rime/weasel/files/1938707/1.zip)

**Comment by s793016** [comment]
0.11.1 回報：
還是會有這個現像，但更不定時發生了

現在觀察是打「這」字，大概3-4次後會掛掉，但只要一開始掛，以後打這字就都會掛。

清除userdb 後的症狀會暫時消失，但這樣就無法記憶常用字，所以還是只能主打 pime ... 雖然沒 rime 快但沒大問題 ... orz

**Comment by s793016** [comment]
0.12.0 回報：
狀況依然存在 ... 

有鑑於每次清除 userdb 後導致當掉的字會變，故此次放上我現在的 userdb 完整包以利除錯抓蟲，這包會當在「您」這個字，使用 changjei35q 這個輸入法，按序打 ofp ，應可重現。

又，雖然我不太懂程式，但我想了一下，這個問題在清除 userdb 後會暫時好，然後打字到一定程度後就會出現，像這次的「您」字，在頭幾天時並不會導致這個問題，但某時起就會了，之後每打必掛。

所以我猜測，可能是 rime 有某個內部記錄表格，然後在累積字數打到某個數後，存在那個「崁」位的字就變成地雷，所以後面只要打到卡在「崁」上的那個字就會導致掛掉。

最後附上這掛 userdb 百度盤連結：
https://pan.baidu.com/s/1N6xaR9AlAqnxEya2YdEa1g
