### ISSUE TITLE
能否考虑将中英文切换改成像搜狗那样？

### ISSUE THREAD

**Issue by liabco** [rime/weasel#198]
如果在已输入部分字符的情况下（在候选框中没有上屏的状态）再使用右边shift 切换时是直接把已输入的中文上屏，然后临时切换成英文状态，在本次输入完后（再次上屏后），又变回了中文状态。
因为现在是不同窗口是没有统一中英文的状态，就是说我在一个浏览器中把输入状态改成英文后可能我切换到另一个编辑器中输入法又自动变成了中文状态，始终不能很确定当前输入法是中文输入还是英文输入。
还希望大大们能够化繁为简，多个窗口共享中英文输入状态/shift 可以直接上屏已输入的英文字符并且切换成英文状态。

**Comment by zcunlin** [comment]
现在的Rime就支持你需要的方式。比如Shift_L键，有多种设置：（1）noop，屏蔽按键，无操作。（2）commit_code，已輸入的編碼字符上屏並切換至西文輸入模式。（3）inline_ascii：临时英文，就是你觉得别扭的这种情况。（4）commit_text，已輸入的候選文字上屏並切換至西文輸入模式。参考：https://gist.github.com/lotem/2981316
