### ISSUE TITLE
能否加入〖上屏朗读〗功能？以真正实现闭眼盲打

### ISSUE THREAD

**Issue by xmlfhs** [rime/weasel#201]
你好，我是双拼使用者，双拼在对字库词库熟悉的基础上，可以基本实现关闭候选盲打，如果能加入〖上屏朗读〗，再输入文字之后，有个语音反馈，就能真正实现闭眼盲打。希望能加入此功能，谢谢~

**Comment by Prcuvu** [comment]
这个需求太复杂，暂不予考虑。先关闭了。

**Comment by nameoverflow** [comment]
Accessibility 的事情大概很后期才会考虑。
