### ISSUE TITLE
Windows7 版本0.11.0无法在cmd下输入中文

### ISSUE THREAD

**Issue by bluebad** [rime/weasel#203]
貌似前一个版本没这问题

**Comment by bluebad** [comment]
亲测0.10.0可输入中文，0.11.0重装一次仍旧无法输入中文。

**Comment by nameoverflow** [comment]
![image](https://user-images.githubusercontent.com/10287709/39028935-e41b963c-448b-11e8-9369-52676a3dfb25.png)

**Comment by Prcuvu** [comment]
目前的最新版本 0.11.1 是正常的。
