### ISSUE TITLE
使用startlsback++透明化任务栏，浅色桌面背景下右下角中英文图标白板

### ISSUE THREAD

**Issue by zzl93** [rime/weasel#205]
![image](https://user-images.githubusercontent.com/15900227/39081595-bc828acc-4576-11e8-8083-348be038be01.png)
![image](https://user-images.githubusercontent.com/15900227/39081597-c35bf2de-4576-11e8-8443-e641388c2cb0.png)

上述两幅图是在使用了startlsback++透明化任务栏后，第一张使用深色背景没有问题， 第二张使用浅色背景就会导致图标白板 
额，这个用的工具太多，应该只是少数人的问题吧，但是不是说win10要更新各种界面样式，会不会以后也有透明任务栏呢？

**Comment by nameoverflow** [comment]
Win 10 17134 已经是透明的了，并没有发现这个问题。

**Comment by Prcuvu** [comment]
无法在这里保证使用第三方软件时语言栏图标的行为。
