### ISSUE TITLE
未更改任何设置，再次开机使用时弹出“有错误，请查看日志”

### ISSUE THREAD

**Issue by zaliccoff** [rime/weasel#208]
![image](https://user-images.githubusercontent.com/38611635/39094011-793c94f2-465b-11e8-9b93-787e2e9d82fe.png)
找不到日志位置><

起初以为是自行添加自然码双拼，编辑等没弄好；
后面试了几次默认使用初始配置，还是会出现错误 

现在多用一秒普通输入都是煎熬...  怎么办

**Comment by HatuneMiku** [comment]
应当很快会被修复了. 临时解决方案可以参考 #199 在开始菜单手动点击重开一次服务.

**Comment by nameoverflow** [comment]
和 #199 是同一个问题吗？

**Comment by nameoverflow** [comment]
Duplicate of #199
