### ISSUE TITLE
如何合并不同输入方案的用户词库？

### ISSUE THREAD

**Issue by skygate2012** [rime/weasel#209]
我想把朙月拼音的用户词库复制到地球拼音的词库里面，应该怎么做呢？

**Comment by nameoverflow** [comment]
朙月拼音的词库是不带声调的，地球是带声调的，词库不是一回事。

**Comment by skygate2012** [comment]
@nameoverflow 那有没有什么办法把朙月拼音里的词语导出，不带键码，然后导入到地球拼音呢？

**Comment by lotem** [comment]
針對原題的回答是，不可以。用戶詞典裏的詞條必須有對應編碼。

沒有編碼的詞可以加到固態詞典，即添加到 `terra_pinyin.dict.yaml`
