### ISSUE TITLE
NSIS打包出错，找不到opencc.dll

### ISSUE THREAD

**Issue by Prcuvu** [rime/weasel#21]
版本：commit 62fba4f06717701c167cb2584793263300cd17fd
NSIS打包失败，记录中显示：`File: "opencc.dll" -> no files found.`
通过搜索，整个编译过程中没有生成`opencc.dll`。不过，经过测试，这不影响简繁转换的功能。
`rime.dll`虽然被生成，但是没有被编译脚本自动复制到`weasel/output`，也导致了NSIS打包错误。
检查NSIS脚本后发现，`File "data\opencc\*.json"`没有被加入，旧的`File "data\opencc\*.ini"`和`File "data\opencc\*.txt"`也没有被移除。

**Comment by lotem** [comment]
NSIS 腳本是該改寫了…
opencc 鏈接進 rime.dll 去了

**Comment by Prcuvu** [comment]
Solved by commit ca69c82455ee2c3c783f5f96af2cc6447cfba0ce.
