### ISSUE TITLE
当安装目录含有中文时，切换成简体还是输出繁体

### ISSUE THREAD

**Issue by benojan** [rime/weasel#210]
试过换成英文则无此bug

**Comment by lotem** [comment]
如果推測的情況成立，而 [用戶文件夾](https://github.com/rime/home/wiki/UserData) 的路徑不包含中文，也可以把 `opencc` 文件夾複製到用戶文件夾下面。

**Comment by Prcuvu** [comment]
请将本问题转移到 [BYVoid/OpenCC 的问题收集区](https://github.com/BYVoid/OpenCC/issues)。
