### ISSUE TITLE
间歇性良性提示“有错误，请查看日志%TEMP%\rime.weasel.*.INFO”，另快捷键冲突太严重

### ISSUE THREAD

**Issue by xianghongai** [rime/weasel#211]
- [报错日志文件](http://p07j03lwk.bkt.clouddn.com//rime/weasel/bug/weasel.zip)

![2018-04-23_12-52-39](https://user-images.githubusercontent.com/2075006/39108415-ae30fc9e-46fa-11e8-82bf-6eb8b6e4a0fc.png)

![2018-04-23_13-17-44](https://user-images.githubusercontent.com/2075006/39108421-b32dfc2e-46fa-11e8-8e30-49e7d7cfc792.png)

default.yaml中的`key_binder/bindings:`部分与绝大多数开发软件冲突，如何屏蔽之？

我在`default.custom.yaml`中配置成：如`- { when: composing, accept: Control+d, send: noop }`不会生效。

**Comment by xianghongai** [comment]
快捷键冲突部分暂时解决方案为：
- 管理员权限`编辑程序文件夹`中`data/default.yaml`文件，将`key_binder/bindings:`所有内容注释掉，
- 用户文件夹中 `default.custom.yaml`文件设定：

```
  # 输入法只要输入方案设定、翻页、切换全半角、ASCII输入标点、删除指定候选词几个快捷键
  "switcher/hotkeys":
    - "Control+Alt+F8"

  key_binder/bindings:
    - { when: always, accept: Shift+space, toggle: full_shape }
    - { when: always, accept: Control+period, toggle: ascii_punct }
    - {accept: comma, send: Page_Up, when: paging}
    - {accept: period, send: Page_Down, when: has_menu}
```

**Comment by nameoverflow** [comment]
```yaml
# default.patch.yaml
patch:
  key_binder/bindings:
    # 只留下需要的
```
这样就行。

**Comment by nameoverflow** [comment]
Duplicate of #199

**Comment by xianghongai** [comment]
Windows10下五笔造词部分非常不稳定，“文本码表”中的已造词，一会儿能输入出来，一会儿无法输出。
并且，“文本码表”中的词极其紊乱，不建议“智能”处理用户输入，不拿输入法来说，就是目前机器对人类的自然语言识别句词检索和上下文识别都有一定难度。形码输入可以给用户一个自己造词关闭输入框架造词的入口。难得开发，就给一个模板让用户自己按一定规则填充。

**Comment by nameoverflow** [comment]
当然可以关。
```yaml
patch:
  translator/enable_user_dict: false
```

**Comment by xianghongai** [comment]
谢谢您的回复！
