### ISSUE TITLE
差点放弃RIME，开机输入法服务关闭，所有程式无法输入中文

### ISSUE THREAD

**Issue by JLucky** [rime/weasel#213]
操作系统：Windows7 x64专业版 Service Pack 1
问题：电脑开机后，小弹窗提示输入法服务需要重新部署，有“重新启动服务”和“调试服务”两个选项（Sorry，没截到图，不想再折腾一次了）
尝试：
1、尝试重新安装回0.10.0.0版本，问题依旧；
2、最后发现可能是输入法程式安装路径问题，出现问题的路径”D:\Program Files (x86)\Rime“（路径中带有空格），重新安装路径为”D:\Program Files“，问题暂时解决，现在输入着文字发现0.11.0.0版本更丝滑。

官网没找到其它版本下载地址，友情附上 0.10.0.0版本 下载链接：http://dl.bintray.com/rime/weasel/weasel-0.10.0.0-installer.exe

**Comment by nameoverflow** [comment]
WeaselServer 崩溃？

**Comment by lotem** [comment]
請根據自己的需要選用輸入法。作者對用家沒有任何期待。😀 

和安裝路徑沒有關係。`D:\Program Files` 也含有空格。
默認安裝位置是 `%ProgramFiles%\Rime`，變量展開後一般都是 `C:\Program Files` 或 `C:\Program Files (x86)`。
