### ISSUE TITLE
Encode failure，不知算不算问题

### ISSUE THREAD

**Issue by frdqx** [rime/weasel#214]
小狼毫Temp日志，显示如下：

> W0424 11:37:28.197743  9668 entry_collector.cc:144] Encode failure: '㛟'.
W0424 11:37:28.228994  9668 entry_collector.cc:144] Encode failure: '丆'.
W0424 11:37:28.291494  9668 entry_collector.cc:144] Encode failure: '乊'.
W0424 11:37:28.291494  9668 entry_collector.cc:144] Encode failure: '乤'.
W0424 11:37:28.291494  9668 entry_collector.cc:144] Encode failure: '乥'.
W0424 11:37:28.291494  9668 entry_collector.cc:144] Encode failure: '乧'.
W0424 11:37:28.291494  9668 entry_collector.cc:144] Encode failure: '乫'.
W0424 11:37:28.291494  9668 entry_collector.cc:144] Encode failure: '乷'.
W0424 11:37:28.291494  9668 entry_collector.cc:144] Encode failure: '乺'.
W0424 11:37:28.291494  9668 entry_collector.cc:144] Encode failure: '乼'.
W0424 11:37:28.322746  9668 entry_collector.cc:144] Encode failure: '亞歷山大·杜布切克'.
W0424 11:37:28.322746  9668 entry_collector.cc:144] Encode failure: '亞當·斯密'.
W0424 11:37:28.322746  9668 entry_collector.cc:144] Encode failure: '亞西爾·阿拉法特'.
W0424 11:37:28.322746  9668 entry_collector.cc:144] Encode failure: '亪'.
W0424 11:37:28.338371  9668 entry_collector.cc:144] Encode failure: '仒'.
W0424 11:37:28.338371  9668 entry_collector.cc:144] Encode failure: '伊娃·門德斯'.
W0424 11:37:28.353996  9668 entry_collector.cc:144] Encode failure: '伯納斯·李'.
W0424 11:37:28.353996  9668 entry_collector.cc:144] Encode failure: '伽利略·伽利雷'.
W0424 11:37:28.385246  9668 entry_collector.cc:144] Encode failure: '傑克·倫敦'.
W0424 11:37:28.385246  9668 entry_collector.cc:144] Encode failure: '傑夫·金尼'.
W0424 11:37:28.385246  9668 entry_collector.cc:144] Encode failure: '傑奎琳·肯尼迪'.
W0424 11:37:28.385246  9668 entry_collector.cc:144] Encode failure: '傑瑞·宋飛'.
W0424 11:37:28.385246  9668 entry_collector.cc:144] Encode failure: '傑西·歐文斯'.
W0424 11:37:28.385246  9668 entry_collector.cc:144] Encode failure: '傑西卡·艾爾芭'.
W0424 11:37:28.400871  9668 entry_collector.cc:144] Encode failure: '傻Ｂ'.
W0424 11:37:28.400871  9668 entry_collector.cc:144] Encode failure: '儒勒·凡爾納'.
W0424 11:37:28.400871  9668 entry_collector.cc:144] Encode failure: '克里斯汀·貝爾'.
W0424 11:37:28.432121  9668 entry_collector.cc:144] Encode failure: '六·二五戰爭'.
W0424 11:37:28.432121  9668 entry_collector.cc:144] Encode failure: '六·四'.
W0424 11:37:28.447746  9668 entry_collector.cc:144] Encode failure: '凱茜·弗里曼'.
W0424 11:37:28.463371  9668 entry_collector.cc:144] Encode failure: '列夫·托爾斯泰'.
W0424 11:37:28.494622  9668 entry_collector.cc:144] Encode failure: '動Ｌ'.
W0424 11:37:28.494622  9668 entry_collector.cc:144] Encode failure: '匁'.
W0424 11:37:28.494622  9668 entry_collector.cc:144] Encode failure: '北萊茵·威斯特法倫州'.
W0424 11:37:28.510247  9668 entry_collector.cc:144] Encode failure: '十·一'.
W0424 11:37:28.525872  9668 entry_collector.cc:144] Encode failure: '卡拉ＯＫ'.
W0424 11:37:28.525872  9668 entry_collector.cc:144] Encode failure: '卡斯蒂利亞·萊昂'.
W0424 11:37:28.525872  9668 entry_collector.cc:144] Encode failure: '卡爾·馬克思'.
W0424 11:37:28.525872  9668 entry_collector.cc:144] Encode failure: '厼'.
W0424 11:37:28.541497  9668 entry_collector.cc:144] Encode failure: '古斯塔夫·多雷'.
W0424 11:37:28.557122  9668 entry_collector.cc:144] Encode failure: '史蒂芬·哈珀'.
W0424 11:37:28.588373  9668 entry_collector.cc:144] Encode failure: '哈克貝利·芬歷險記'.
W0424 11:37:28.588373  9668 entry_collector.cc:144] Encode failure: '哈利·波特'.
W0424 11:37:28.588373  9668 entry_collector.cc:144] Encode failure: '哈莉·貝瑞'.
W0424 11:37:28.603998  9668 entry_collector.cc:144] Encode failure: '唐納德·川普'.
W0424 11:37:28.603998  9668 entry_collector.cc:144] Encode failure: '喬修亞·吉爾菲艾斯'.
W0424 11:37:28.603998  9668 entry_collector.cc:144] Encode failure: '喬治·奧威爾'.
W0424 11:37:28.603998  9668 entry_collector.cc:144] Encode failure: '喬治·布希'.
W0424 11:37:28.603998  9668 entry_collector.cc:144] Encode failure: '喬治·索羅斯'.
W0424 11:37:28.603998  9668 entry_collector.cc:144] Encode failure: '喬治·華盛頓'.
W0424 11:37:28.619623  9668 entry_collector.cc:144] Encode failure: '噶拉·多傑·仁波切'.
W0424 11:37:28.650874  9668 entry_collector.cc:144] Encode failure: '埃克托·柏遼茲'.
W0424 11:37:28.650874  9668 entry_collector.cc:144] Encode failure: '埃德加·愛倫·坡'.
W0424 11:37:28.650874  9668 entry_collector.cc:144] Encode failure: '埃德加·斯諾'.
W0424 11:37:28.650874  9668 entry_collector.cc:144] Encode failure: '埃爾維斯·普雷斯利'.
W0424 11:37:28.666499  9668 entry_collector.cc:144] Encode failure: '堂·吉河德'.
W0424 11:37:28.666499  9668 entry_collector.cc:144] Encode failure: '壭'.
W0424 11:37:28.666499  9668 entry_collector.cc:144] Encode failure: '夏洛特·勃良特'.
W0424 11:37:28.697749  9668 entry_collector.cc:144] Encode failure: '大衛·米利班德'.
W0424 11:37:28.697749  9668 entry_collector.cc:144] Encode failure: '大衛·艾登堡'.
W0424 11:37:28.728999  9668 entry_collector.cc:144] Encode failure: '妮可·基德曼'.
W0424 11:37:28.728999  9668 entry_collector.cc:144] Encode failure: '威廉·福克納'.
W0424 11:37:28.728999  9668 entry_collector.cc:144] Encode failure: '威廉·莎士比亞'.
W0424 11:37:28.744626  9668 entry_collector.cc:144] Encode failure: '安·海瑟薇'.
W0424 11:37:28.744626  9668 entry_collector.cc:144] Encode failure: '安妮·夏菲維'.
W0424 11:37:28.760251  9668 entry_collector.cc:144] Encode failure: '安妮·海瑟薇'.
W0424 11:37:28.807126  9668 entry_collector.cc:144] Encode failure: '尤利婭·季莫申科'.
W0424 11:37:28.807126  9668 entry_collector.cc:144] Encode failure: '尤里斯·伊文思'.
W0424 11:37:28.822751  9668 entry_collector.cc:144] Encode failure: '巴登·符騰堡州'.
W0424 11:37:28.838376  9668 entry_collector.cc:144] Encode failure: '布萊特妮·墨菲'.
W0424 11:37:28.838376  9668 entry_collector.cc:144] Encode failure: '布蘭妮·斯皮爾斯'.
W0424 11:37:28.838376  9668 entry_collector.cc:144] Encode failure: '希拉里·克林頓'.
W0424 11:37:28.838376  9668 entry_collector.cc:144] Encode failure: '希斯·萊傑'.
W0424 11:37:28.838376  9668 entry_collector.cc:144] Encode failure: '希蒙·佩雷斯'.
W0424 11:37:28.838376  9668 entry_collector.cc:144] Encode failure: '帕麗斯·希爾頓'.
W0424 11:37:28.854001  9668 entry_collector.cc:144] Encode failure: '庫爾特·瓦爾德海姆'.
W0424 11:37:28.854001  9668 entry_collector.cc:144] Encode failure: '康多莉扎·賴斯'.
W0424 11:37:28.869627  9668 entry_collector.cc:144] Encode failure: '弗洛倫蒂諾·佩雷斯'.
W0424 11:37:28.869627  9668 entry_collector.cc:144] Encode failure: '弗蘭西斯·培根'.
W0424 11:37:28.869627  9668 entry_collector.cc:144] Encode failure: '弗里德里希·席勒'.
W0424 11:37:28.900877  9668 entry_collector.cc:144] Encode failure: '怪人奧爾·揚科維奇'.
W0424 11:37:28.916502  9668 entry_collector.cc:144] Encode failure: '恩里科·費米'.
W0424 11:37:28.932127  9668 entry_collector.cc:144] Encode failure: '愛德華·達拉第'.
W0424 11:37:28.932127  9668 entry_collector.cc:144] Encode failure: '愛瑪·沃特森'.
W0424 11:37:28.963377  9668 entry_collector.cc:144] Encode failure: '托馬斯·阿奎納'.
W0424 11:37:28.994627  9668 entry_collector.cc:144] Encode failure: '拿破崙·波拿巴'.
W0424 11:37:29.010253  9668 entry_collector.cc:144] Encode failure: '提姆·羅賓斯'.
W0424 11:37:29.025878  9668 entry_collector.cc:144] Encode failure: '摩亨佐·達羅'.
W0424 11:37:29.025878  9668 entry_collector.cc:144] Encode failure: '摩根·弗里曼'.
W0424 11:37:29.072754  9668 entry_collector.cc:144] Encode failure: '斯文·海定'.
W0424 11:37:29.072754  9668 entry_collector.cc:144] Encode failure: '斯文·赫定'.
W0424 11:37:29.088379  9668 entry_collector.cc:144] Encode failure: '斯蒂芬·哈珀'.
W0424 11:37:29.119629  9668 entry_collector.cc:144] Encode failure: '普密蓬·阿杜德'.
W0424 11:37:29.119629  9668 entry_collector.cc:144] Encode failure: '曼蘇爾·達杜拉'.
W0424 11:37:29.150880  9668 entry_collector.cc:144] Encode failure: '朩'.
W0424 11:37:29.150880  9668 entry_collector.cc:144] Encode failure: '本·拉登'.
W0424 11:37:29.150880  9668 entry_collector.cc:144] Encode failure: '本傑明·富蘭克林'.
W0424 11:37:29.150880  9668 entry_collector.cc:144] Encode failure: '朰'.
W0424 11:37:29.166505  9668 entry_collector.cc:144] Encode failure: '查爾斯·格雷'.
W0424 11:37:29.166505  9668 entry_collector.cc:144] Encode failure: '查爾斯·狄更斯'.
W0424 11:37:29.166505  9668 entry_collector.cc:144] Encode failure: '柯南·道爾'.
W0424 11:37:29.182132  9668 entry_collector.cc:144] Encode failure: '梅里亞姆·韋伯斯特'.
W0424 11:37:29.213382  9668 entry_collector.cc:144] Encode failure: '歇洛克·福爾摩斯'.
W0424 11:37:29.229007  9668 entry_collector.cc:144] Encode failure: '比爾·蓋茨'.
W0424 11:37:29.260257  9668 entry_collector.cc:144] Encode failure: '沃倫·巴菲特'.
W0424 11:37:29.275882  9668 entry_collector.cc:144] Encode failure: '法蘭西斯·培根'.
W0424 11:37:29.275882  9668 entry_collector.cc:144] Encode failure: '法蘭西斯·斐迪南'.
W0424 11:37:29.275882  9668 entry_collector.cc:144] Encode failure: '泰格·伍茲'.
W0424 11:37:29.275882  9668 entry_collector.cc:144] Encode failure: '泰特斯·安德洛尼克斯'.
W0424 11:37:29.291507  9668 entry_collector.cc:144] Encode failure: '海倫·凱勒'.
W0424 11:37:29.322758  9668 entry_collector.cc:144] Encode failure: '湯姆·克蘭西'.
W0424 11:37:29.322758  9668 entry_collector.cc:144] Encode failure: '湯姆·克魯斯'.
W0424 11:37:29.322758  9668 entry_collector.cc:144] Encode failure: '湯姆·索亞歷險記'.
W0424 11:37:29.322758  9668 entry_collector.cc:144] Encode failure: '湯姆·羅賓斯'.
W0424 11:37:29.338382  9668 entry_collector.cc:144] Encode failure: '潔西卡·艾芭'.
W0424 11:37:29.369633  9668 entry_collector.cc:144] Encode failure: '熱比亞·卡德爾'.
W0424 11:37:29.369633  9668 entry_collector.cc:144] Encode failure: '熱比婭·卡德爾'.
W0424 11:37:29.385258  9668 entry_collector.cc:144] Encode failure: '牛Ｂ'.
W0424 11:37:29.400883  9668 entry_collector.cc:144] Encode failure: '狄奧多·阿多諾'.
W0424 11:37:29.416508  9668 entry_collector.cc:144] Encode failure: '珍·奧斯汀'.
W0424 11:37:29.416508  9668 entry_collector.cc:144] Encode failure: '琳·戴維斯'.
W0424 11:37:29.416508  9668 entry_collector.cc:144] Encode failure: '瑪麗蓮·夢露'.
W0424 11:37:29.432133  9668 entry_collector.cc:144] Encode failure: '畓'.
W0424 11:37:29.510259  9668 entry_collector.cc:144] Encode failure: '碧娜芝·布托'.
W0424 11:37:29.541510  9668 entry_collector.cc:144] Encode failure: '穆罕默德·歐瑪'.
W0424 11:37:29.572760  9668 entry_collector.cc:144] Encode failure: '簡·愛'.
W0424 11:37:29.572760  9668 entry_collector.cc:144] Encode failure: '約瑟夫·斯大林'.
W0424 11:37:29.572760  9668 entry_collector.cc:144] Encode failure: '約翰·厄普代克'.
W0424 11:37:29.572760  9668 entry_collector.cc:144] Encode failure: '約翰·拉貝'.
W0424 11:37:29.572760  9668 entry_collector.cc:144] Encode failure: '約翰·本仁'.
W0424 11:37:29.572760  9668 entry_collector.cc:144] Encode failure: '約翰·霍金斯'.
W0424 11:37:29.588385  9668 entry_collector.cc:144] Encode failure: '納撒尼爾·霍桑'.
W0424 11:37:29.604012  9668 entry_collector.cc:144] Encode failure: '綠壩·花季護航'.
W0424 11:37:29.604012  9668 entry_collector.cc:144] Encode failure: '維克多·雨果'.
W0424 11:37:29.619637  9668 entry_collector.cc:144] Encode failure: '罖'.
W0424 11:37:29.619637  9668 entry_collector.cc:144] Encode failure: '羅伯特·伯恩斯'.
W0424 11:37:29.619637  9668 entry_collector.cc:144] Encode failure: '羅伯特·佛洛斯特'.
W0424 11:37:29.619637  9668 entry_collector.cc:144] Encode failure: '羅伯特·路易斯·斯蒂文森'.
W0424 11:37:29.635262  9668 entry_collector.cc:144] Encode failure: '美國５１區'.
W0424 11:37:29.650887  9668 entry_collector.cc:144] Encode failure: '耶萊娜·揚科維奇'.
W0424 11:37:29.713387  9668 entry_collector.cc:144] Encode failure: '艾格尼絲·史沫特萊'.
W0424 11:37:29.713387  9668 entry_collector.cc:144] Encode failure: '艾薩克·牛頓'.
W0424 11:37:29.729012  9668 entry_collector.cc:144] Encode failure: '荷莉·貝瑞'.
W0424 11:37:29.729012  9668 entry_collector.cc:144] Encode failure: '莎拉·佩林'.
W0424 11:37:29.729012  9668 entry_collector.cc:144] Encode failure: '莎拉·布萊曼'.
W0424 11:37:29.729012  9668 entry_collector.cc:144] Encode failure: '莫尼卡·萊溫斯基'.
W0424 11:37:29.729012  9668 entry_collector.cc:144] Encode failure: '菲利克斯·米達麥亞'.
W0424 11:37:29.744638  9668 entry_collector.cc:144] Encode failure: '薩達姆·侯賽因'.
W0424 11:37:29.744638  9668 entry_collector.cc:144] Encode failure: '蘇珊·波伊爾'.
W0424 11:37:29.775888  9668 entry_collector.cc:144] Encode failure: '裘力斯·愷撒'.
W0424 11:37:29.791513  9668 entry_collector.cc:144] Encode failure: '裝Ｂ'.
W0424 11:37:29.791513  9668 entry_collector.cc:144] Encode failure: '西蒙·舒斯特'.
W0424 11:37:29.822762  9668 entry_collector.cc:144] Encode failure: '詹姆斯·喬伊斯'.
W0424 11:37:29.822762  9668 entry_collector.cc:144] Encode failure: '詹姆斯·龐德'.
W0424 11:37:29.838388  9668 entry_collector.cc:144] Encode failure: '諾姆·喬姆斯基'.
W0424 11:37:29.838388  9668 entry_collector.cc:144] Encode failure: '豪伊杜·比豪爾'.
W0424 11:37:29.838388  9668 entry_collector.cc:144] Encode failure: '豪伊杜·比豪爾州'.
W0424 11:37:29.854013  9668 entry_collector.cc:144] Encode failure: '貝·布托'.
W0424 11:37:29.854013  9668 entry_collector.cc:144] Encode failure: '貝娜齊爾·布托'.
W0424 11:37:29.869639  9668 entry_collector.cc:144] Encode failure: '赫曼·麥爾維爾'.
W0424 11:37:29.869639  9668 entry_collector.cc:144] Encode failure: '赫爾穆特·科爾'.
W0424 11:37:29.885265  9668 entry_collector.cc:144] Encode failure: '足利·義政'.
W0424 11:37:29.885265  9668 entry_collector.cc:144] Encode failure: '足利·義滿'.
W0424 11:37:29.885265  9668 entry_collector.cc:144] Encode failure: '路易·皮埃爾·阿爾都塞'.
W0424 11:37:29.885265  9668 entry_collector.cc:144] Encode failure: '路易斯·伊納西奧·盧拉·達席爾瓦'.
W0424 11:37:29.916515  9668 entry_collector.cc:144] Encode failure: '込'.
W0424 11:37:29.916515  9668 entry_collector.cc:144] Encode failure: '迪戈·加西亞島'.
W0424 11:37:29.947765  9668 entry_collector.cc:144] Encode failure: '道·瓊斯'.
W0424 11:37:29.947765  9668 entry_collector.cc:144] Encode failure: '道·瓊斯指數'.
W0424 11:37:29.947765  9668 entry_collector.cc:144] Encode failure: '道格拉斯·麥克阿瑟'.
W0424 11:37:29.947765  9668 entry_collector.cc:144] Encode failure: '達·芬奇'.
W0424 11:37:29.947765  9668 entry_collector.cc:144] Encode failure: '達科塔·芬妮'.
W0424 11:37:29.947765  9668 entry_collector.cc:144] Encode failure: '邁克爾·傑克遜'.
W0424 11:37:29.947765  9668 entry_collector.cc:144] Encode failure: '邁克爾·克萊頓'.
W0424 11:37:29.947765  9668 entry_collector.cc:144] Encode failure: '邁克爾·喬丹'.
W0424 11:37:29.947765  9668 entry_collector.cc:144] Encode failure: '那木巴爾·恩赫巴亞爾'.
W0424 11:37:29.994640  9668 entry_collector.cc:144] Encode failure: '錫霍特·阿林'.
W0424 11:37:29.994640  9668 entry_collector.cc:144] Encode failure: '錫霍特·阿林山脈'.
W0424 11:37:30.025892  9668 entry_collector.cc:144] Encode failure: '阿不來提·阿不都熱西提'.
W0424 11:37:30.025892  9668 entry_collector.cc:144] Encode failure: '阿加莎·克里斯蒂'.
W0424 11:37:30.025892  9668 entry_collector.cc:144] Encode failure: '阿斯頓·馬丁'.
W0424 11:37:30.025892  9668 entry_collector.cc:144] Encode failure: '阿爾法·羅密歐'.
W0424 11:37:30.025892  9668 entry_collector.cc:144] Encode failure: '阿諾·施瓦辛格'.
W0424 11:37:30.025892  9668 entry_collector.cc:144] Encode failure: '阿諾德·施瓦辛格'.
W0424 11:37:30.025892  9668 entry_collector.cc:144] Encode failure: '阿道司·赫胥黎'.
W0424 11:37:30.025892  9668 entry_collector.cc:144] Encode failure: '阿Ｑ'.
W0424 11:37:30.025892  9668 entry_collector.cc:144] Encode failure: '阿Ｑ正傳'.
W0424 11:37:30.057142  9668 entry_collector.cc:144] Encode failure: '雷·羅馬諾'.
W0424 11:37:30.104017  9668 entry_collector.cc:144] Encode failure: '額勒貝格·道爾吉'.
W0424 11:37:30.119642  9668 entry_collector.cc:144] Encode failure: '馬丁·路德'.
W0424 11:37:30.119642  9668 entry_collector.cc:144] Encode failure: '馬丁·路德·金'.
W0424 11:37:30.119642  9668 entry_collector.cc:144] Encode failure: '馬克·吐溫'.
W0424 11:37:30.119642  9668 entry_collector.cc:144] Encode failure: '馬克思·列寧主義'.
W0424 11:37:30.119642  9668 entry_collector.cc:144] Encode failure: '馬克斯·普朗克'.
W0424 11:37:30.150893  9668 entry_collector.cc:144] Encode failure: '鮑勃·伍德沃德'.
W0424 11:37:30.150893  9668 entry_collector.cc:144] Encode failure: '鮑勃·馬利'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: '齊內丁·齊達內'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ａ咖'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ａ片'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'ＡＡ制'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｂ型超聲'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｂ超'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｃ盤'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'ＤＮＡ親子鑑定'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'ＤＮＡ鑑定'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｇ點'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｋ書'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｋ粉'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｔ恤'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｕ形轉彎'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'ＵＳＢ手指'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'ＵＳＢ記憶棒'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｖ溝'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｘ光'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'Ｘ戰警'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'ｅ仔'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'ｋ他命'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: 'ｎ遍'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: '𠮶'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: '𡞵'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: '𩾀'.
W0424 11:37:30.182143  9668 entry_collector.cc:144] Encode failure: '𪎌'.

这些词均在八股文词典「essay.txt」中，大部分不影响输入，有些则输不出来。

问题1：人名中间的点「·」，是输不出来的，如「馬克·吐溫」，输入「maketuwen」，输出就是「馬克吐溫」。
建议1：「·」与其输不出来，不如在「essay.txt」中，就将「·」删掉；如此则不会「Encode failure」。尽管没什么影响（不弹错误，只在日志中显示），但为精益求精，可否改良。

问题2：有些输不出来，如「Ｖ溝」「動Ｌ」。
建议2：可否加上编码。

**Comment by lotem** [comment]
我主張保留正確的寫法。拼音暫時無法編碼，或許有些輸入方案可以。

以後考慮把這類詞語歸入另冊。

**Comment by frdqx** [comment]
多谢公子回复

**Comment by doubanchan** [comment]
日语中不需要间隔号，以下需要删除。
足利·義政
足利·義滿

**Comment by LeeiFrankJaw** [comment]
这里还涉及简繁转换的一个问题了。

大陆常见的间隔号确实是 middle dot（·），早期文件也有用 katakana middle dot （・）的。但是至少在台湾的规范用法中，用的是 fullwidth full stop（．），如果你用的台湾字体，这些标点符号，都是居中显示的，所以全角句号也被拿来当成间隔号来使用。

更妖孽的是，这个符号本来设计的用法，至少在日语中一直是这么用的，就是在日本的 STEM 科技类文献中，这个符号是用来当成句号来使的，替代小圆圈句号（。）。然而，在大陆的科技文献中（现在好像只有数学领域还在坚持使用小圆点句号），一般都是用英语的句号和空格组合（. ）来替代小圆圈句号（。）的。
