### ISSUE TITLE
Windows 7 無法 Deploy

### ISSUE THREAD

**Issue by Millhost** [rime/weasel#216]
如果在Windows 7 的 User Profile 以連結方式放在 C:\Users 內Deploy時會出現錯誤。
我會把User Profile 放在 D:\Profile，在C:\Users內建立一個連結到D:\Profile
例如使用者名稱是 peterchu，在C:\Users\peterchu是一個連結連到 D:\Profile (以mklink 建立)。
當做了這個設置後，WeaselDeployer.exe 就會無法正常運作。

而系統 log 會出現以下錯誤
I0425 16:06:53.286799   912 registry.cc:14] registering component: backup_config_files
I0425 16:06:53.286799   912 registry.cc:14] registering component: clean_old_log_files
I0425 16:06:53.364799   912 deployment_tasks.cc:80] updating rime installation info.
I0425 16:06:53.380399   912 config_data.cc:65] loading config file 'C:\Users\peterchu\AppData\Roaming\Rime\installation.yaml'.
I0425 16:06:53.380399   912 deployment_tasks.cc:98] installation info exists. installation id: 2c472714-a69d-4446-b90a-d828c0f4a687
I0425 16:06:53.380399   912 deployment_tasks.cc:106] sync dir: C:\Users\sindysyl\AppData\Roaming\Rime\sync
I0425 16:06:53.380399   912 deployment_tasks.cc:108] previous distribution: Weasel
I0425 16:06:53.380399   912 deployment_tasks.cc:111] previous distribution version: 0.11.0
I0425 16:06:53.380399   912 deployment_tasks.cc:114] previous Rime version: 1.3.1
I0425 16:06:53.380399   912 deployment_tasks.cc:123] creating installation info.
I0425 16:06:53.380399   912 config_data.cc:199] write: update_time
I0425 16:06:53.380399   912 config_data.cc:199] write: distribution_name
I0425 16:06:53.380399   912 deployment_tasks.cc:141] distribution: 小狼毫
I0425 16:06:53.380399   912 config_data.cc:199] write: distribution_code_name
I0425 16:06:53.380399   912 deployment_tasks.cc:146] distribution code name: Weasel
I0425 16:06:53.380399   912 config_data.cc:199] write: distribution_version
I0425 16:06:53.380399   912 deployment_tasks.cc:152] distribution version: 0.10.0
I0425 16:06:53.380399   912 config_data.cc:199] write: rime_version
I0425 16:06:53.380399   912 deployment_tasks.cc:155] Rime version: 1.3.0
I0425 16:06:53.380399   912 config_data.cc:85] saving config file 'C:\Users\peterchu\AppData\Roaming\Rime\installation.yaml'.
_**E0425 16:06:53.458400   912 deployment_tasks.cc:62] Error reading file information: boost::filesystem::last_write_time: 系統找不到指定的檔案。: "C:/Users\Profile**_
I0425 16:06:53.458400   912 rime_api.cc:113] changes detected; starting maintenance.
I0425 16:06:53.458400   912 deployer.cc:114] starting work thread for 3 tasks.
I0425 16:06:53.458400  1392 deployer.cc:83] running deployment tasks:
I0425 16:06:53.458400  1392 deployment_tasks.cc:160] updating workspace.

不知為何Deployer會讀錯目錄名而其他module是無問題的。
請問這問題可以怎修正？

**Comment by nameoverflow** [comment]
link 是 `/d` 还是 `/j` 还是 `/h` ？

**Comment by Prcuvu** [comment]
已移动到 rime/librime#202。

**Comment by lotem** [comment]
有一個辦法：設置用戶文件夾的路徑爲鏈接的目標位置。

**Comment by sunlin7** [comment]
遇到同样问题，版本是0.11.1；而0.9.30没有问题。
