### ISSUE TITLE
不支持win10,导致win10开始菜单、统一应用无法启动

### ISSUE THREAD

**Issue by OeinTwor** [rime/weasel#22]
在win10上输入法服务启动失败，同时使win10的开始菜单、win10统一应用全部无法启动。

**Comment by pingplug** [comment]
同样的问题

**Comment by Xuanwo** [comment]
同样的问题，Windows开始频繁出现错误报告

**Comment by KNCheung** [comment]
估计这项目要废了，没人维护。Win8出了多少时间都没支持

**Comment by lotem** [comment]
是的，這項目（單指 Windows 前端 https://github.com/rime/weasel ）不再維護了：
https://github.com/rime/home/issues/25

**Comment by dirdir** [comment]
不知道新的输入法何时能问世，可有开发计划？

**Comment by windhamwong** [comment]
我主力使用Python, Perl的，新輸入法的編寫需要幫忙嗎 我可以一起做阿 ^^

**Comment by lotem** [comment]
前端倒是已經能跑起來了，缺的是包裝成可發佈的產品所需的：安裝卸載升級那套東西。
沒有一個嚴密的計劃，還是不要冒然發佈吧。
所以近期能做到的，最多是整理好源碼和文檔，和一個給玩家和開發者體驗的散裝軟件包。

**Comment by windhamwong** [comment]
我真不知道Google Input有Framework的呢。。。文檔這些我不在行的 但源碼我沒問題呢 我也有些功能想加上去的 我們可以合作下阿XD

**Comment by lotem** [comment]
歡迎。很需要技術員。

加功能的話，如果偏前端，那就得一起研究 Google 的框架了。
而 librime 的代碼上手還不夠容易。就算幫忙做 code review 也好。

**Comment by windhamwong** [comment]
可以阿 源碼部份最大問題是沒有註釋 要費點時間
你邀請我加入吧？ 好像我不能按請求的

**Comment by windhamwong** [comment]
Google 的框架能發我一下嗎? 不然我不能開始呢....
我預計9月中會很有空的

**Comment by zaqzrh** [comment]
很好，有人參與了，是這個https://github.com/lotem/google-input-tools嗎？
不過這個好像是C++的

**Comment by windhamwong** [comment]
當然是這個 因為作者就是lotem -.-

**Comment by windhamwong** [comment]
暫時rime在win10內是不可用的，因為會做成太多的錯誤 導致windows不正常......
我只能等lotem回答我才知道我從那裡開始才好
open source合作需要知道對方的進度呢

**Comment by lotem** [comment]
https://github.com/lotem/google-input-tools 這是我的 fork。原作是這個：
https://github.com/googlei18n/google-input-tools

**Comment by windhamwong** [comment]
Ok. I was just asking for the commit permission only. btw I will work on it next week.
*Can't type chinese at the moment.*

**Comment by littleq0903** [comment]
想問一下這裏的進度怎麼樣了，想看看有沒有可以幫上忙的地方。

我也是 rime 愛好者 ：）

目前發現是 TSF 的版本才會在 Windows 10 上面 crash start bar，另外一個版本是可以用的，但是在 Universal App 會不能用（因爲不是 TSF）。

**Comment by lotem** [comment]
@littleq0903 已發出一個實驗版本 https://github.com/rime/home/issues/25

**Comment by windhamwong** [comment]
不push的話也沒辦法幫忙開發呢......

**Comment by lotem** [comment]
@windhamwong 是一個新的 project，不會在這裏更新了
新前端的代碼庫爲 https://github.com/lotem/rime-gits ，是 https://github.com/googlei18n/google-input-tools 的一個分支

**Comment by windhamwong** [comment]
但是新的beta 會更新到rime-gits嗎?

**Comment by OeinTwor** [comment]
@lotem
怎么rime-gits需求添加根证书信任呢？

**Comment by lotem** [comment]
@OeinTwor 你是说数字签名？那个 Google 自己发布才用的吧。

**Comment by OeinTwor** [comment]
在rime-gits的readme里写的
<code>
6. Install the certificates resources\test.cer into Trusted Root Certification Authorities.
</code>
看到这个反射性的问一下。
除了网银没办法外，根证书信任我一般都不加，比如12306,cnnic之流

**Comment by windhamwong** [comment]
@OeinTwor 其實不用簽都可以用的阿^^
google的已經過期了 但可以無視

**Comment by littleq0903** [comment]
where should I put my configuration? I found two places.

and currently the issue is off on gits-rime, where should I go for further
discuss of gits-rime?

**Comment by lotem** [comment]
@littleq0903 github.com/lotem/rime-gits/issues is open now.
You can also follow up https://github.com/rime/home/issues/25 .

**Comment by lotem** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by 17-qxm** [comment]
wondows10开启时有时rime算法服务会停止，但重新部署一下就好了
