### ISSUE TITLE
任务栏图标右键

### ISSUE THREAD

**Issue by freesoft0000** [rime/weasel#220]
![31](https://user-images.githubusercontent.com/30435921/39393904-5a18a148-4aba-11e8-9dac-b220eb976deb.png)
win7 32位系统。安装后，任务栏图标右键会同时出现系统的输入法右键菜单还有小狼豪的右键菜单，下面的部分被遮盖了。可以看到的右键菜单点击也不起作用。

2、现在默认没有五笔输入法了吗？

3、是否可以改进安装过程最后的注册服务部分，占用cpu太高了。我这里是100%

4、是否自动更新，是否可以做到安装后的配置界面，加一个选项就可以了。

**Comment by Prcuvu** [comment]
1. 语言栏图标在 Windows 10 的桌面版语言栏里是不显示的。正在调查原因。
2. 没有。请通过输入法设定的“获取更多输入方案”按钮来获取。
3. 初次注册时需要部署方案，必然会导致高 CPU 占用。这个解决不了。
4. 会考虑加入一个选项来开启或关闭自动更新。

**Comment by freesoft0000** [comment]
2、更多输入法是通过github下载的。国内下载有些无法下载到。不如把大众用的比较多的五笔集成到软件中。省去了再次下载。使用不高的可以不集成。

**Comment by lotem** [comment]
集成了大衆用得比較多的拼音。其他使用較少的輸入法不集成。

**Comment by xianghongai** [comment]
Windows 7 64位也存在这个问题，能否增加一个配置项，是否启用该菜单 Icon。
