### ISSUE TITLE
最新版本的Weasel在Windows10使用Word 2016出現括弧問題

### ISSUE THREAD

**Issue by Ostrichbeta** [rime/weasel#221]
在使用Word 2016時，如果使用TSF模式在中文下輸入左括弧時有時候需要按下兩次才會出來，而用非TSF模式則不會出現這個問題。

**Comment by Prcuvu** [comment]
小狼毫在 Word 2016 上的行为，可能因 Word 的 32 位和 64 位的区别而有不同。我这边 64 位的 Word 上没有这样的问题。

**Comment by nameoverflow** [comment]
我的 365 版没这个问题。

**Comment by ziyonghan** [comment]
0.11.1版本测试，在win10 2015LTSB，word 32版本上，右）需要两次才会出现。

**Comment by Guwalgiyakuan** [comment]
win 1709 (OS内部版本 16299.371) 64位
word 2016 MSO (16.0.4639.1000) 64位
没问题

**Comment by Ostrichbeta** [comment]
我的版本也是64位元的，而且也是word 2016 MSO (16.0.4639.1000) OS 16299.371

**Comment by ziyonghan** [comment]
可以复现，是空文档，首行无其他字符，直接输入括号，需要两次。如果前面已有字符则一次即可。

**Comment by nameoverflow** [comment]
复现的配置是什么样的？

**Comment by zzColin** [comment]
确实如此，貌似所有标点符号多少都受到影响，而且对于引号还会有额外的问题，不仅开头的左引号需要敲两下才上屏，而且当你打完引号里面的字之后，再敲一下引号键，它依然出来的是左引号，要再按一下才出来右引号。

不仅如此……这个问题的影响范围貌似还不仅限于 Windows 10 64 位 + Word 2016，而且应该很早之前就存在这个问题——我公司机器上的 64 位 Windows 7 上的 32 位 Outlook 2010 一样有此问题，而且这台机器上是之前的 0.9.30 版本（也是常态用的 TSF，因为工作上需要的某个奇葩软件用任何 IME 输入法都会出 Bug）。

**Comment by zzColin** [comment]
观察到一个新的现象，不知是否和此相关（Windows 10 1709 x64，Word 2016 32 位）：按下任何一个会呼出选字框的键（字母和部分标点符号），然后直接回车上屏原始字符，此后再进行的第一个按键操作一律会被吃掉，不论是什么键，甚至移动插入点的方向键都不能幸免。

**Comment by nameoverflow** [comment]
有种用了个假 word 的感觉……
可能需要参考一下出现问题时的配置和方案？

**Comment by nameoverflow** [comment]
内置输入法会有问题吗？

**Comment by Ostrichbeta** [comment]
這裡是所有更改的配置

![default](https://user-images.githubusercontent.com/25266479/39673041-a34014ee-5124-11e8-9fee-460bfd43a56b.PNG)

**Comment by zzColin** [comment]
[Rime.zip](https://github.com/rime/weasel/files/1983103/Rime.zip)
关于配置和方案，请见附件。这个问题现在看来必须得是 64 位的系统 + 32 位的 Office + TSF 模式才会出现，Windows 10 系统默认输入法无此问题。

**Comment by CXFeng409** [comment]
按照@zzColin 提到的现象测试了一下，确实如此，似乎是这样的规律：只要上屏的是键盘默认的原始字符（既英文状态时的 半角 字符），就会将跟着后面输入的任意按键“吃掉”，包括：
1）字母键：按下字母键+enter，使字母键直接上屏时；
2）标点键：如果标点的选单中有半角字符，则半角字符上屏后，“吃掉”后面按键，包括，。、－＝等；
3）按shift键上屏的半角字符：~!#$%^＊（）＿＋｛｝｜：＂＜＞？等；
4）数字键：数字键的现象不太稳定，有时“吃掉”后面1个键，有时吃2个键，有时则正常，没有摸清规律；

综上：中文模式下，上屏半角字符，则会导致后面紧跟的按键失效。

在：win10 1803 64位专业版+word 2013+小狼毫TSF；
       win7 专业版64位+word 2010+小狼毫TSF；中均有以上现象。
其它输入法中没有这个问题，包括小狼毫IME也没有。

@nameoverflow 删掉所有个人配置，使用内置的明有拼音方案同样有这个问题。

**Comment by nameoverflow** [comment]
我这段时间一直在使用 win 10 1803 x64 和 word 2013 x64 的环境从来没复现过这个问题；可能需要其它信息，然而并没有头绪。

**Comment by CXFeng409** [comment]
@nameoverflow 并不是只有32位office，我win10上装的是64位office也有问题，而且数字键的问题在win10 1709和1803上不一致，昨天升级到1803后，数字键的问题似乎没有了，但是其它按键的问题依然存在

**Comment by zzColin** [comment]
@nameoverflow 最新验证：
1. 吞标点问题似乎和退格键的操作有关，在使用退格键删除任意字符后，接在后面输入的直接上屏的标点符号会被吞掉（包括引号匹配问题也一样），不涉及退格键删除字符的操作时似乎不会出现问题；该问题在之前；该问题在之前 0.9.30 版本就存在，不是更新后引入的。
2. 不出输入框直接上屏的半角符号（明月拼音下如等号、加号、连字符兼减号、井号）一样会吞掉紧接在后面的按键操作，以至于尝试连续输等号时，输入第一个之后全部都得敲两下才出来一个；该问题尚未验证之前版本是否存在。

**Comment by llpub** [comment]
我的是全角下吞句号和逗号，而不吞括号(小狼毫TSF+word2016)，但不持续这样，偶尔出现。

**Comment by fanzhen1** [comment]
所以这个问题还是没有解决吗？
我的win10 64，word2016 64，及0.13小狼毫（20190128更新）依然如此，好困扰啊

**Comment by Hermittttt** [comment]
说一点不相关的，退格后出现符号无法输入的情况我曾经在微软拼音输入法上遇到过，当时也认为是输入法的bug，直到卸载了之前安装的盗版office重新安装365之后，这个问题再也没有出现过。
目前使用Rime 0.14.3，office 365版本16.0.10730.20348，无法复现问题。

**Comment by fnshiwu** [comment]
我的环境是win7 64，word2013，小狼毫0.14.3，不光是括号，是所有全角符号都需要按两次。
