### ISSUE TITLE
最後狀態無法保存

### ISSUE THREAD

**Issue by delphinuz** [rime/weasel#224]
目前是繁體/半角，按alt-shift換到英文，再按alt-shift換回rime，結果是變成英文/全角，無法恢復原本繁體/半角。

有時中文部分不變，但半角常常變成全角，要自己手動再切換。

有時中文會變成簡體。基本上各種情況都有遇過。

只希望能固定回到之前的狀態，不然切換一下，就還要手動再設定回原本的輸入狀態。

**Comment by fxliang** [comment]
长时间没有更新，大概问题已解决。如需可再打开。
