### ISSUE TITLE
设置preedit_type = preview后编码和拼音串没有了？

### ISSUE THREAD

**Issue by piiiiq** [rime/weasel#225]
就像标题说的，编码没有了啊？？
preedit_type只有两个值对吗？preview和composition，无论设置哪一个编码都没有了。

**Comment by lotem** [comment]
編碼和拼音串是一回事吧？爲什麼寫兩個問號。
開發者的確是這樣設計和實現的。

@nameoverflow 
我還沒看代碼。從需求上我認爲讓 `preedit_type` 只控制嵌入顯示的內容更妥。
是否隱藏候選窗上的編碼行乃至候選行，可以再添加一項配置。
比如：
style/hide_candidates_when: unique # always, never

另一種安排是再支持兩種樣式：`blank`, `preview+composition`。不過這樣解析起來比較麻煩，因爲他將同時控制兩部分的顯示內容。

**Comment by nameoverflow** [comment]
![image](https://user-images.githubusercontent.com/10287709/39824019-e76a1ed0-53e0-11e8-9380-bcd349bdb6ee.png)
![image](https://user-images.githubusercontent.com/10287709/39824081-12bfeede-53e1-11e8-95d6-3bcf44ca2402.png)

Composition 是显示编码串的。

编码串的显示模式再加改动的话感觉破坏性会很大了。

**Comment by lotem** [comment]
样
这个字我都不认识了😓

编码行我觉得可以有

**Comment by lotem** [comment]
這樣安排
大大不妥
非常不妥

**Comment by jack6th** [comment]
遇到同样的问题。当设置成下面二行的时候怎样在候选之上显示拼音？
inline_preedit: true
preedit_type: preview
