### ISSUE TITLE
爲何我只能輸出繁體字？

### ISSUE THREAD

**Issue by wordlesswind** [rime/weasel#227]
重新安裝、重新配置語言也沒有用。

Windows 10 x64 17134.48

**Comment by Guwalgiyakuan** [comment]
按 F4 键调出'方案选择‘菜单依次选择以下选项看看：
![screen_05-13_12-53-17](https://user-images.githubusercontent.com/37359970/39963996-08c5e126-56ad-11e8-8cfb-be69110487dc.png)

![screen_05-13_12-54-00](https://user-images.githubusercontent.com/37359970/39964001-12794f78-56ad-11e8-8f0a-d3500c8ea69a.png)

**Comment by wordlesswind** [comment]
@Guwalgiyakuan
感谢，是我疏忽了。
