### ISSUE TITLE
小狼毫在Word 2016下候选框闪烁或不显示-Win 10 64位（重装无效）

### ISSUE THREAD

**Issue by Karcundun** [rime/weasel#228]
最近爱上了rime输入法，也尝试了一些自主设置；
**在使用了几天后出现了在word 2016中打字不能正常显示候选框的现象：
使用朙月拼音简化字进行打字时，能正常输入但是候选框会闪烁一下后迅速消失，此时按空格能够输入首位的短语。**
计算机完全是小白，尝试卸载后用火绒清理垃圾并删掉电脑里所有的rime文件夹，再重新安装；并没有改善。
针对rime做的自我设置中，主要是来自rime增强计划中旧版本-精简整合去重复的部分。

**Comment by nameoverflow** [comment]
关掉火绒试试？

**Comment by Karcundun** [comment]
关闭word里面的输入法控制就好了！

**Comment by zzColin** [comment]
不知是不是相关，就在刚才，我在 Word 2016 里面遇到了和题主一模一样的问题（64 位 Windows 10 1709，32 位 Word 2016），之前一直好好的，完全没有做过任何操作，系统没有额外安装任何安全类的软件，但把 Word 关掉重开，问题就消失了……

**Comment by Sciroccogti** [comment]
365版Word也有这样的问题，按 @Karcundun 方法解决。

![image](https://user-images.githubusercontent.com/32357397/76157987-baa46980-614b-11ea-8467-c9fbde1b25f8.png)

此问题比较普遍，能否置顶？

**Comment by lqqgis** [comment]
> 
> 
> 关闭word里面的输入法控制就好了！

office2019也有这个问题，关了输入法控制，但是问题没有解决

**Comment by li666-cpu** [comment]
同样没有解决

**Comment by shenzhonghua** [comment]
同样有这个问题，闪烁不显示，但是有时又是正常的，字还是可以打的
另外，我的小狼毫算法服务偶尔会退出，会不会是这个原因？每天一次左右，要手工去菜单中重新启动服务才能继续使用

**Comment by lqqgis** [comment]
> 
> 
> 同样有这个问题，闪烁不显示，但是有时又是正常的，字还是可以打的
> 另外，我的小狼毫算法服务偶尔会退出，会不会是这个原因？每天一次左右，要手工去菜单中重新启动服务才能继续使用

因为RIME在office中的出现这个问题，我已经放弃小狼毫了，改用QQ拼音了，感觉还可以

**Comment by rockbenben** [comment]
出现闪烁问题，建议先排除键盘硬件问题。

之前全系统出现候选框闪烁，不限定于 Office。最后发现是 Media Next 键偶尔自动触发，导致候选框无法保持显示。禁用该键后，闪烁不再复现。

算法服务不能自启动，可以先参考[WeaselServerAutostart 脚本](https://github.com/rockbenben/rime-WeaselServer)临时解决，等待后续更新。

**Comment by realasking** [comment]
最近就在github上搜到一个PIME，也是用RIME的，用了几天，好像没有小狼毫这样的闪烁和掉服务问题。

**Comment by realasking** [comment]
用了一段时间的PIME，不会在office中闪烁，但也会掉服务，只是它家在托盘中设了个图标，一掉就可以restart一下。
最近从自然码转五笔了，一下选择就多了好多，王码自家的五笔大一统虽然也有bug，但相对来说还是好不少，适于暂时不想折腾的用户啊。

**Comment by Randonyld** [comment]
office word2021 ltsc  已经关闭选项中的输入法控制了，还是出现闪烁问题，重启算法服务或者重启word都不解决问题。而在新建的一个word文件中没有问题。

**Comment by fanzhen1** [comment]
问题一直不解决，停更两年，只好放弃

**Comment by baoang** [comment]
> 问题一直不解决，停更两年，只好放弃

我还在用Win10，反正工作电脑也懒得升级去，Office也用的旧版本，还是2010的升起来的，目前似乎没有主线贴说的问题，不过我也认为这个软件可以适当更新一下了。

**Comment by ieeyaY** [comment]
我在其他界面也遇到了一样问题, chrome等

**Comment by skypinglee** [comment]
我也有相同的问题，大家可以试下，如果出现界面闪烁的情况，把插入状态修改成改写状态就正常了，就是按下INSERT键，就可以正常输入了，但是这个有时需要插入时很麻烦。

**Comment by zzColin** [comment]
> 我也有相同的问题，大家可以试下，如果出现界面闪烁的情况，把插入状态修改成改写状态就正常了，就是按下INSERT键，就可以正常输入了，但是这个有时需要插入时很麻烦。

莫非这事和 preedit 有关？开 preedit 情况下，Word 里面插入状态和改写状态的一个区别，就是插入状态下是真正的 preedit，而改写状态下是贴一块膏药模拟出来的，真正的 preedit 似乎不支持改写模式。

……但小狼毫在 TSF 下的非 preedit 状态似乎是模拟出来的，实际还是有 preedit 出现，打字过程中仔细看的话会有一个 preedit 状态的空格（难道 TSF 强制 preedit？）

**Comment by skypinglee** [comment]
> > 我也有相同的问题，大家可以试下，如果出现界面闪烁的情况，把插入状态修改成改写状态就正常了，就是按下INSERT键，就可以正常输入了，但是这个有时需要插入时很麻烦。
> 
> 莫非这事和 preedit 有关？开 preedit 情况下，Word 里面插入状态和改写状态的一个区别，就是插入状态下是真正的 preedit，而改写状态下是贴一块膏药模拟出来的，真正的 preedit 似乎不支持改写模式。
> 
> ……但小狼毫在 TSF 下的非 preedit 状态实际还是有 preedit 出现，打字过程中仔细看的话会有一个 preedit 状态的空格（难道 TSF 强制 preedit？），所以关掉小狼毫的 preedit 恐怕未必解决问题。
> 
> #509 里面有人提到过 preedit

这个太专业了，就不知道原因了

**Comment by skypinglee** [comment]
还有一个可以解决问题的办法就是升级office到2021版本，这个问题就没有再出现

**Comment by mqpbjnsdjvbwl** [comment]
> 还有一个可以解决问题的办法就是升级office到2021版本，这个问题就没有再出现

我的2021还是有这种问题……一拖动word里面的标尺就出来这种毛病，只能重启word

**Comment by seszu** [comment]
> 

真是这样的，我的也是同样的问题，关闭输入法控制没用，拖动标尺百分百重现候选框闪烁的问题。

**Comment by Kai2510** [comment]
观察得好细致，我觉得可能有关。
word2019也是这样，平时没事，一用公式编辑器就会出问题；在Onenote2019里也出现闪烁问题，第一次打开时会闪，如果输入，会输入两次（打“文字”，上屏“文字文字”），切别的输入法再切回来就好了。



> > 我也有相同的问题，大家可以试下，如果出现界面闪烁的情况，把插入状态修改成改写状态就正常了，就是按下INSERT键，就可以正常输入了，但是这个有时需要插入时很麻烦。
> 
> 莫非这事和 preedit 有关？开 preedit 情况下，Word 里面插入状态和改写状态的一个区别，就是插入状态下是真正的 preedit，而改写状态下是贴一块膏药模拟出来的，真正的 preedit 似乎不支持改写模式。
> 
> ……但小狼毫在 TSF 下的非 preedit 状态实际还是有 preedit 出现，打字过程中仔细看的话会有一个 preedit 状态的空格（难道 TSF 强制 preedit？），所以关掉小狼毫的 preedit 恐怕未必解决问题。
> 
> #509 里面有人提到过 preedit

**Comment by jhonanon** [comment]
> 问题一直不解决，停更两年，只好放弃

2023年有一次commit，大佬快修复这个bug吧😭

**Comment by jiaojiaodubai** [comment]
> > 我也有相同的问题，大家可以试下，如果出现界面闪烁的情况，把插入状态修改成改写状态就正常了，就是按下INSERT键，就可以正常输入了，但是这个有时需要插入时很麻烦。
> 
> 莫非这事和 preedit 有关？开 preedit 情况下，Word 里面插入状态和改写状态的一个区别，就是插入状态下是真正的 preedit，而改写状态下是贴一块膏药模拟出来的，真正的 preedit 似乎不支持改写模式。
> 
> ……但小狼毫在 TSF 下的非 preedit 状态实际还是有 preedit 出现，打字过程中仔细看的话会有一个 preedit 状态的空格（难道 TSF 强制 preedit？），所以关掉小狼毫的 preedit 恐怕未必解决问题。
> 
> #509 里面有人提到过 preedit

在[思源笔记](https://github.com/siyuan-note/siyuan)的行内公式块后写入文字也出现闪烁，且出现一个空格宽度的虚线，用此方法更改插入模式后解决问题。👍

**Comment by zzColin** [comment]
> 在[思源笔记](https://github.com/siyuan-note/siyuan)的行内公式块后写入文字也出现闪烁，且出现一个空格宽度的虚线，用此方法更改插入模式后解决问题。+1

看了下思源笔记的 UI 是 Electron，合理怀疑所有用 Electron 的应用都可能会受影响

**Comment by llpub** [comment]
> > 
> 
> 真是这样的，我的也是同样的问题，关闭输入法控制没用，拖动标尺百分百重现候选框闪烁的问题。

被同样的问题困扰了很久。刚刚尝试再次拖动几次word标尺，候选框突然就不闪烁了，大家都试试看

**Comment by YQ-YSY** [comment]
诱发Rime在Word中闪烁的条件（故障可重现）以及临时解决方法

很多朋友都遇到了Rime输入法在word中闪烁，难以使用的问题。
我的电脑是：Win10系统，Office 2019，小狼毫weasel-0.14.3.0
经过多尝试和试验，终于发现诱发闪烁的条件（故障可重现）：关键是在Word的“标尺”上，

当我用鼠标拖动“标尺”下方的“小四方形（左缩进）”或者“向上小三角形（悬挂缩进）”几次后，用Rime打字就会闪烁。
临时的解决方法是：把鼠标放在标尺上，就能正常打字，不闪烁了。但是，如果鼠标从标尺上移开，打字又会闪烁。

所以记住，如果要在Word标尺上操作，就先切换为其他输入法，不用Rime。
如果不小心操作了Word标尺，已经造成Rime闪烁了，那么把鼠标放在标尺上，就能继续打字了。
应急打完字后，保存文件，关闭Word，再重新打开，Rime才恢复正常。目前就只能这样了。

——以上信息提供给Rime的开发者，希望能对修改调试程序有帮助。

**Comment by BH2WFR** [comment]
> 

目前的话，好像“把鼠标放在标尺上，就能正常打字” 是会大量占用CPU，电脑风扇疯狂转动
“如果要在Word标尺上操作，就先切换为其他输入法，不用Rime” 好像不管用，换回rime后照样闪烁

**Comment by BH2WFR** [comment]
> 诱发Rime在Word中闪烁的条件（故障可重现）以及临时解决方法
> 
> 很多朋友都遇到了Rime输入法在word中闪烁，难以使用的问题。 我的电脑是：Win10系统，Office 2019，小狼毫weasel-0.14.3.0 经过多尝试和试验，终于发现诱发闪烁的条件（故障可重现）：关键是在Word的“标尺”上，
> 
> 当我用鼠标拖动“标尺”下方的“小四方形（左缩进）”或者“向上小三角形（悬挂缩进）”几次后，用Rime打字就会闪烁。 临时的解决方法是：把鼠标放在标尺上，就能正常打字，不闪烁了。但是，如果鼠标从标尺上移开，打字又会闪烁。
> 
> 所以记住，如果要在Word标尺上操作，就先切换为其他输入法，不用Rime。 如果不小心操作了Word标尺，已经造成Rime闪烁了，那么把鼠标放在标尺上，就能继续打字了。 应急打完字后，保存文件，关闭Word，再重新打开，Rime才恢复正常。目前就只能这样了。
> 
> ——以上信息提供给Rime的开发者，希望能对修改调试程序有帮助。

目前的话，好像“把鼠标放在标尺上，就能正常打字” 是会大量占用CPU，电脑风扇疯狂转动
“如果要在Word标尺上操作，就先切换为其他输入法，不用Rime” 好像不管用，换回rime后照样闪烁

**Comment by daomiren** [comment]
fxliang大神实在是牛，最新版（6月3日）的竟然解决了这个问题。

**Comment by fxliang** [comment]
> fxliang大神实在是牛，最新版（6月3日）的竟然解决了这个问题。

这个是 @determ1ne 修好的👍👍👍

**Comment by BH2WFR** [comment]
> fxliang大神实在是牛，最新版（6月3日）的竟然解决了这个问题。

哪里下载？我从fxliang主页下载的artifact还是5月11日的版本

**Comment by fxliang** [comment]
> > fxliang大神实在是牛，最新版（6月3日）的竟然解决了这个问题。
> 
> 哪里下载？我从fxliang主页下载的artifact还是5月11日的版本

有merged了现在最新在主仓
[这里](https://github.com/rime/weasel/actions)

**Comment by BH2WFR** [comment]
> > > fxliang大神实在是牛，最新版（6月3日）的竟然解决了这个问题。
> > 
> > 
> > 哪里下载？我从fxliang主页下载的artifact还是5月11日的版本
> 
> 有merged了现在最新在主仓 [这里](https://github.com/rime/weasel/actions)

非常感谢！

**Comment by fanzhen1** [comment]
刚刚换成了fxliang大佬的最新版，但测试了一下问题依旧啊，拉动标尺可以不再导致闪烁，但是如果调整图片大小，还是会导致闪烁。
我是microsoft 365，word版本2305

**Comment by daomiren** [comment]
> 

是从这里[下载](https://github.com/rime/weasel/actions)最新的

**Comment by llpub** [comment]
weasel-0.15.0.0, Win10 22H2 x64, Word 2019还是存在候选框闪烁或不显示的bug。
在这个版本中，出现候选框闪烁或不显示后，来回拖动标尺似乎已不能解决这个问题。

**Comment by BH2WFR** [comment]
> weasel-0.15.0.0, Win10 22H2 x64, Word 2019还是存在候选框闪烁或不显示的bug。 在这个版本中，出现候选框闪烁或不显示后，“来回拖动标尺”似乎已不能解决这个问题。“鼠标放在标尺上”可以将就打字但是闪烁厉害。 Ps. 现在是拖动标尺必出现“候选框闪烁或不显示”

是的，我升级后刚开始还行，现在又出现这问题了，这下子字都打不出来了😭

**Comment by Newdea** [comment]
在Obsidan上也遇到了这个问题，不过更新到6月6号版的后可以了（https://github.com/rime/weasel/releases/tag/0.15.0）

**Comment by TurnOffNOD** [comment]
同样遇到这个问题了。weasel是最新的0.15.0版本，office是2021版本，输入法控制已经关闭。

> 出现闪烁问题，建议先排除键盘硬件问题。
> 
> 之前全系统出现候选框闪烁，不限定于 Office。最后发现是 Media Next 键偶尔自动触发，导致候选框无法保持显示。禁用该键后，闪烁不再复现。

硬件键盘没有问题，在其它程序中正常使用。
键盘没有Medaia Next功能键，不会被这个键触发。

**Comment by changzaicl** [comment]
这个问题在新的actions下依然会重现。office是2021版本，输入法控制已经关闭。
只需要在word中，通过调整拖动标尺就会出现。而且可以复现。

请帮助修复。谢谢~

**Comment by BH2WFR** [comment]
> 这个问题在新的actions下依然会重现。office是2021版本，输入法控制已经关闭。 只需要在word中，通过调整拖动标尺就会出现。而且可以复现。
> 
> 请帮助修复。谢谢~

可以尝试一下 [[Techines](https://github.com/Techince)](https://github.com/Techince/weasel) 这个分支版本，这个版本解决了word下标尺的问题

**Comment by uliuyt** [comment]
2024年了，Windwos11下使用0.15.0.0版本小狼毫Weasel，**每次**打开桌面版OneNote2021，都会触发候选框闪烁的问题，触发后在word、edge浏览器也会闪烁，但在微信输入框中不会闪烁。解决的办法是切换回微软自带的输入法，然后再切换回小狼毫，马上能恢复正常。

我一般习惯在Windows设置里面关掉自带输入法，只保留一个常用输入法，但因为这个问题一直开着两个输入法，强迫症很难受😭

**Comment by tp20c5** [comment]
> 2024年了，Windwos11下使用0.15.0.0版本小狼毫Weasel，**每次**打开桌面版OneNote2021，都会触发候选框闪烁的问题，触发后在word、edge浏览器也会闪烁，但在微信输入框中不会闪烁。解决的办法是切换回微软自带的输入法，然后再切换回小狼毫，马上能恢复正常。
> 
> 我一般习惯在Windows设置里面关掉自带输入法，只保留一个常用输入法，但因为这个问题一直开着两个输入法，强迫症很难受😭

如果只是说OneNote的光标不见问题，Nightly Build应该可解。早在去年就修复了，一直没发版而已

**Comment by uliuyt** [comment]
> > 2024年了，Windwos11下使用0.15.0.0版本小狼毫Weasel，**每次**打开桌面版OneNote2021，都会触发候选框闪烁的问题，触发后在word、edge浏览器也会闪烁，但在微信输入框中不会闪烁。解决的办法是切换回微软自带的输入法，然后再切换回小狼毫，马上能恢复正常。
> > 我一般习惯在Windows设置里面关掉自带输入法，只保留一个常用输入法，但因为这个问题一直开着两个输入法，强迫症很难受😭
> 
> 如果只是说OneNote的光标不见问题，Nightly Build应该可解。早在去年就修复了，一直没发版而已

老哥说的“光标”是指啥？我说的“候选框”是指输入拼音以后的汉字候选框。选框闪烁，但是能正常打字（就是看不见候选项是啥）。不知道说的是不是一回事儿。

https://github.com/rime/weasel/assets/69107226/0afae403-1815-467f-9540-90d01188e6b6

**Comment by tp20c5** [comment]
> > > 2024年了，Windwos11下使用0.15.0.0版本小狼毫Weasel，**每次**打开桌面版OneNote2021，都会触发候选框闪烁的问题，触发后在word、edge浏览器也会闪烁，但在微信输入框中不会闪烁。解决的办法是切换回微软自带的输入法，然后再切换回小狼毫，马上能恢复正常。
> > > 我一般习惯在Windows设置里面关掉自带输入法，只保留一个常用输入法，但因为这个问题一直开着两个输入法，强迫症很难受😭
> > 
> > 
> > 如果只是说OneNote的光标不见问题，Nightly Build应该可解。早在去年就修复了，一直没发版而已
> 
> 老哥说的“光标”是指啥？我说的“候选框”是指输入拼音以后的汉字候选框。候选框闪烁，但是能正常打字（就是看不见候选项是啥）。不知道说的是不是一回事儿。
> 
>  Video_2024-03-15_165940.mp4

是的。还有OneNote打字重复上屏的问题，预发布版都是解决了的

**Comment by uliuyt** [comment]
> > > > 2024年了，Windwos11下使用0.15.0.0版本小狼毫Weasel，**每次**打开桌面版OneNote2021，都会触发候选框闪烁的问题，触发后在word、edge浏览器也会闪烁，但在微信输入框中不会闪烁。解决的办法是切换回微软自带的输入法，然后再切换回小狼毫，马上能恢复正常。
> > > > 我一般习惯在Windows设置里面关掉自带输入法，只保留一个常用输入法，但因为这个问题一直开着两个输入法，强迫症很难受😭
> > > 
> > > 
> > > 如果只是说OneNote的光标不见问题，Nightly Build应该可解。早在去年就修复了，一直没发版而已
> > 
> > 
> > 老哥说的“光标”是指啥？我说的“候选框”是指输入拼音以后的汉字候选框。候选框闪烁，但是能正常打字（就是看不见候选项是啥）。不知道说的是不是一回事儿。
> > Video_2024-03-15_165940.mp4
> 
> 是的。还有OneNote打字重复上屏的问题，预发布版都是解决了的

刚刚安装了预发布版，确实解决问题了，感谢大佬🙏

**Comment by changzaicl** [comment]
![word中会跳动_2024-04-03_11-46-56](https://github.com/rime/weasel/assets/144407904/c68af582-733b-4fac-8357-a87f63b8d07d)
这个版本[fix_async](https://github.com/fxliang/weasel/tree/fix_async)解决了闪烁，但出现了新问题，打字会出现跳动一下 的情况。请核实。谢谢！
