### ISSUE TITLE
Windows 10 新版如何删除“小狼毫”桌面版？

### ISSUE THREAD

**Issue by netzrh** [rime/weasel#229]
![default](https://user-images.githubusercontent.com/39295518/40044862-3221df0e-5818-11e8-90f5-3b215f32a17f.PNG)

**Comment by lotem** [comment]
同 https://github.com/rime/weasel/issues/223

無法從這個界面刪除。
已知只有開始菜單＼小狼毫輸入法＼卸載小狼毫可以刪除他。

**Comment by broucetrong** [comment]
这个方法，亲测可用（简单来说，就是先给WIN10配置一个其他语言，把中文删掉，然后再把中文配置回来）：http://www.w10zj.com/Win10xy/Win10xf_6641.html

**Comment by h6fYe34KFSiH** [comment]
> 这个方法，亲测可用（简单来说，就是先给WIN10配置一个其他语言，把中文删掉，然后再把中文配置回来）：http://www.w10zj.com/Win10xy/Win10xf_6641.html

试了两遍 无效

**Comment by sde31c** [comment]
在注册表里把以下两项全部删掉。
`计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\CTF\TIP\{A3F4CDED-B1E9-41EE-9CA6-7B4D0DE6CB0A}\LanguageProfile\0x00000804\{3D02CAB6-2B8E-4781-BA20-1C9267529467}`

`计算机\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\CTF\TIP\{A3F4CDED-B1E9-41EE-9CA6-7B4D0DE6CB0A}\LanguageProfile\0x00000804\{3D02CAB6-2B8E-4781-BA20-1C9267529467}`

**Comment by huanfeng** [comment]
> 在注册表里把以下两项全部删掉。
> `计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\CTF\TIP\{A3F4CDED-B1E9-41EE-9CA6-7B4D0DE6CB0A}\LanguageProfile\0x00000804\{3D02CAB6-2B8E-4781-BA20-1C9267529467}`
> 
> `计算机\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\CTF\TIP\{A3F4CDED-B1E9-41EE-9CA6-7B4D0DE6CB0A}\LanguageProfile\0x00000804\{3D02CAB6-2B8E-4781-BA20-1C9267529467}`

这个实测有效!! WIN10 20H2版本!
