### ISSUE TITLE
输入法确实很好用，但是仍然有些小问题

### ISSUE THREAD

**Issue by JoySky** [rime/weasel#23]
首先感谢作者开发了这么好的输入法，是我唯一刚使用不久就喜欢的一款输入法。但是在使用过程中发现了一些小问题不知道该如何解决
1、在IDE中输入法不随光标移动。
2、后来发现是因为输入法在跟随外边的窗口光标移动（不是在当前窗口）

**Comment by lotem** [comment]
Merged into https://github.com/rime/home/issues/25
