### ISSUE TITLE
在wps表格中出现的奇怪的输入丢失问题

### ISSUE THREAD

**Issue by yext725** [rime/weasel#230]
[win10 x64 1709] WPS表格输入时按空格或者标点之后，同一个单元格内下一次输入出现第一个键丢失。
例如：我输入wo<space>上屏“我”，然后同个单元格输入de的时候就剩下一个e了。
此外，在WPS表格，<tab>跳格第一次也无效。

**Comment by nameoverflow** [comment]
Duplicate of #185
