### ISSUE TITLE
小狼毫(win10 1803/1709 + 0.11.1 tsf)非内嵌模式输入时光标占用一个字符的空白

### ISSUE THREAD

**Issue by llpub** [rime/weasel#231]
如题，win10 1803/1709 + 0.11.1/0.11 tsf ，在非内嵌模式输入时，光标后面会临时出现一个字符大小的空白。后面已有文字的情况下，后面的已有文字会被部分遮住(notepad++内)，或者临时后移约一个字符(word2016内)。
sougou等输入法没有这个情况。请教把这个空白去掉的方法，谢谢
![-1](https://user-images.githubusercontent.com/25077000/40288015-e74f9b80-5ce3-11e8-8b0f-1d8479249744.png)

**Comment by nameoverflow** [comment]
正常表现，有什么问题？

**Comment by llpub** [comment]
在word里面插入文字的时候，这个空白会把后面的文字后移一个字符的距离，给人一种缭乱的感觉。
正是介意这种情况，特意设置了inline_preedit: flase，然而这只是稍微缓解了后面文字的移动。
有办法让它只出现插入的符号（竖线），而不多出来一个空白吗？谢谢

**Comment by shynsun** [comment]
我遇到了同样的问题，不知道你解决了么？
在一些编辑器中，打完字后会把紧邻的换行符删掉，导致下一行文字与正在编辑行连接上。

**Comment by kidzgy** [comment]
不知道这个问题解决了吗？
