### ISSUE TITLE
windows 8.1 下, 任务栏(task bar)操作都会有5-10秒的停滞.

### ISSUE THREAD

**Issue by 2anyone** [rime/weasel#234]
在升级到weasel-0.10.0.0后就不时的在任务栏操作时候, 会遇到停滞, 我也没有特别的解决方案, 就等着weasel不知怎么触发一次崩溃, 导致file explorer退出. 常驻任务栏的weasel图标消失, 之后就好了. 

我从早期版本升级到0.10, 是采用的全新安装, 重新配置, 似乎不存在旧版升级的问题. 不过我也不是很清楚这之间的关联.

而所谓的任务栏操作, 就是包括: 点击开始按钮, 点击托盘(system tray)图标等.

在今日升级到了weasel-0.11.1.0后, 寄希望于能解决这个问题, 但是似乎这个问题就变得更加严重, 以前是不时的发生停滞, 而新版似乎每次任务栏操作都会停滞, 几乎导致我无法工作了. 

不知道如何才能提供debug信息, 进而能够改进weasel在我机器上的表现?

感谢.

**Comment by Guwalgiyakuan** [comment]
之前是因为个人配置里如果 “显示系统托盘图标”时会导致假死现象。清空或新建配置试试

**Comment by nameoverflow** [comment]
是由系统托盘图标导致的。现在的版本使用系统语言栏图标，可以取消掉托盘图标显示。

**Comment by lotem** [comment]
下个版本把托盘图标删掉吧？

**Comment by zhaozg** [comment]
个人认为系统托盘是鸡肋

**Comment by lotem** [comment]
@nameoverflow XP 也已經有開始菜單了。

**Comment by 2anyone** [comment]
@nameoverflow @lotem 请问如何关闭托盘图标，以及如何启用语言栏图标呢？

**Comment by nameoverflow** [comment]
@2anyone https://github.com/rime/weasel/blob/master/output/data/weasel.yaml#L20

**Comment by 2anyone** [comment]
感谢 @nameoverflow 已经禁用托盘图标, 而且启用了语言栏图标. 

似乎语言栏图标在切换的时候不如托盘图标及时. 似乎有一秒的延迟. 不过不影响使用. 

再次感谢各位的帮助.
