### ISSUE TITLE
Rime Tab快捷键问题求教

### ISSUE THREAD

**Issue by waterml** [rime/weasel#237]
在0.11以上的weasel (或者由最新代码编译出来的Squirrel)中, Tab键不再翻页, 而是(根据声母/韵母)前移/后移光标(光标移动了一个单词的距离而不是一次一个字母), 类似于toggle的功能, 感觉非常好用. 
但是fcitx/ibus以及Squirrel 0.9.26.2的Tab键还没有这个功能, 于是想在linux和Mac下把这个Tab键的hotkey 自定义一下, 实现上述的功能. 
但是由于不知道这个功能的具体名字, 无法自行设置. 望赐教, 指出这个功能的名字, 谢谢
_(这个问题或许应该放到fcitx-rime下面, 但是感觉他们很可能不知道, 就放到这里了, 请勿见怪)_

**Comment by nameoverflow** [comment]
我觉得更新一下 librime 的版本就可以了？

**Comment by waterml** [comment]
@nameoverflow 我用的linux发行版是debian, 装软件都是apt-get. apt-get带的librime是老版本. 怕把系统搞坏不太敢自己编译(小白一个).
等等看有没有直接设快捷键的方法.

**Comment by lotem** [comment]
配置在此
https://github.com/rime/rime-prelude/blob/master/default.yaml#L122

若 librime 版本較低，行爲可能不一樣

**Comment by waterml** [comment]
通过自行编译解决了，快捷键的方法确实不行，非常感谢@lotem , @nameoverflow 。
具体是这么操作的(Debian9 + fcitx-rime):

1. 编译librime，用得到的build/lib/librime.so.1.3.1替换原来的/usr/lib/librime.so；
2. 用build/bin/下的几个可执行文件（如rime_deployer）替换/usr/bin/下的相同文件；
3. 用build/bin/下的default.yaml替换/usr/share/rime-data的同名文件（不做这步TAB键还是老样子）。

luna_pinyin.schema.yaml可选替换，不替换的话会报错：deployment_tasks.cc:319] Error updating schema: nonexistent file '/home/XXX/.config/fcitx/rime/stroke.schema.yaml，但是不影响功能。替换的话在输入简体中文时，候选项后默认跟随对应的繁体中文（新版貌似就是这样？）。
附件是20180606在Debian9_x86_64上编译的librime。
[librime_build.on.debian9_x86_64.20180606.zip](https://github.com/rime/weasel/files/2075063/librime_build.on.debian9_x86_64.20180606.zip)

不过要注意如果在".custom.yaml"里用"key_binder/bindings"自定义过任何快捷键的话，tab键的这个新功能还是不能用。
