### ISSUE TITLE
key_binder中用右shift键切换simplification失败

### ISSUE THREAD

**Issue by zerobikappa** [rime/weasel#239]
win10小狼毫，
直接修改自己的输入方案中的几个模块，将F7和右shift都设为切换simplification的热键

`
key_binder:
  bindings:
    - { when: always, accept: F7, toggle: simplification } #設置F7为切换平片假名的快捷键
    - { when: always, accept: Shift_R, toggle: simplification } #设置右shift为切换平片假名的快捷键

ascii_composer:
  switch_key:
    Shift_L: inline_ascii
    Shift_R: noop    #设置左shift为切换中英，屏蔽右shift的切换中英功能，空出右shift键来切换平片假名

switches:
  - name: ascii_mode
    reset: 0
    states: ["日", "英"]
  - name: full_shape
    states: ["半", "全"]
  - name: simplification
    states: ["あ", "カ"]
  - name: ascii_punct
    states: ["。，", "．，"]
`

重新部署后发现用F7可以切换，但右shift没有反应
同一套输入方案在linux下的rime是可以正常使用的，所以应该是win10和小狼毫的问题吧？

**Comment by nameoverflow** [comment]
确实。

**Comment by nameoverflow** [comment]
应该写 `accept: "Shift+Shift_R"`。
