### ISSUE TITLE
Win10 x64 电脑刚开机，发现小狼毫输入法没有反应

### ISSUE THREAD

**Issue by broucetrong** [rime/weasel#241]
切换到 TFS 也是，按 Shift 和 F4 均无反应，打字只能打出纯英文来

**Comment by broucetrong** [comment]
另外，输入法有没有提供“多行候选”的功能

**Comment by ASC8384** [comment]
可能正在自动备份(重新部署)中。

**Comment by ASC8384** [comment]
@broucetrong 有，请看完https://github.com/rime/home/wiki 再说

**Comment by pphboy** [comment]
请问解决了吗，我现在的小狼毫也是开机无法即刻使用，不知道如何解决

**Comment by fxliang** [comment]
我相信这个问题在0.16.1中已解决
