### ISSUE TITLE
修改switches各開關的光標提示文字

### ISSUE THREAD

**Issue by ianzhuo** [rime/weasel#242]
switches選項simplification的預設文字是「漢字」、「汉字」
我如果修改為「繁體」「簡體」後，只有在方案選單會改變
輸入法光標的狀態變化仍然為「漢字」「汉字」
不知道要在那裡進行修改呢?

另外  由於highdpi環境下，中英狀態的提示圖案其實會變的超小有時不易看見，我會建議也可以
修改為顯示「英文(A)」、「中文(中)」這樣的顯示方式

**Comment by lotem** [comment]
需要修改源程序。

**Comment by ianzhuo** [comment]
謝謝，我有查到在那改了。
