### ISSUE TITLE
請問能否有方法新增符號表與更改為ctrl輸入

### ISSUE THREAD

**Issue by nan43** [rime/weasel#243]
您好，
最近因為微軟新注音的輸入法選詞實在太笨拙，用上了小狼毫，感覺相當好，但是在符號輸入上卻讓我遇到問題。

1.小狼毫輸入方式是shift加其他鍵，不知道有沒有可能有方法改成ctrl？我在網路上找了不少地方，好像沒有看到相關討論。
2.是否有可能新增符號表，能輸出一般符號甚至特殊符號？

感謝。

**Comment by nameoverflow** [comment]
shift + 其他键是指数字键上的符号？
可以在 key_binder 里作类似
```yaml
    - {accept: "Control+1", send: "Shift+1", when: always}
```
的设置。
新增符号表可以修改 symbols.yaml，具体可以搜索。
