### ISSUE TITLE
win10 输入法设置中小狼毫(仅桌面)无法被删除

### ISSUE THREAD

**Issue by hosxy** [rime/weasel#246]
如下图所示，小狼毫(TSF)和win10自带的微软拼音都是可以被删除的，而小狼毫(仅桌面)无法被删除。<br>
而且 小狼毫(仅桌面) 不支持 win10 的 UWP应用，然而却不能被删除，是否过于不合理？<br>
<br>
**Windows版本：1803**
<br>

![default](https://user-images.githubusercontent.com/17108640/41948778-e84e629e-79f0-11e8-9ebc-3d0e0bee95fe.PNG)

<br>
<br>
<br>

![1](https://user-images.githubusercontent.com/17108640/41948784-f0d47d40-79f0-11e8-96ae-66e572f4efa7.PNG)

<br>
<br>
<br>

![2](https://user-images.githubusercontent.com/17108640/41948786-f3981d98-79f0-11e8-95fb-3935782bb047.PNG)

**Comment by toiiggww** [comment]
标识为（仅桌面）的输入法，本身就不支持UWP应用，换句话说，仅TFS输入法支持UWP应用

**Comment by lotem** [comment]
可以删除。
然而这个界面不受输入法控制，是操作系统的一部分。

**Comment by rLry** [comment]
我卸载小狼毫之后，清理过注册表，但这个小狼毫 (仅桌面) 依旧无法被删除。

**Comment by ipcjs** [comment]
手动删除的链接：https://github.com/rime/weasel/issues/223

**Comment by ipcjs** [comment]
手动删除方法的链接：https://github.com/rime/weasel/issues/223
