### ISSUE TITLE
QUICK 輸入法 一問

### ISSUE THREAD

**Issue by lcmkevin** [rime/weasel#247]
想問一下QUICK輸入法使用時，有些字打了，但選擇時有點不方便， 第一頁沒出現時要用箭咀鍵向下才可選擇其它字，是只可用這方法嗎？
另，是否可加入關連字， 如的輸入了可字， 一些常用關連字會自動顯示作選擇，這樣更方便 .

**Comment by lotem** [comment]
用前次頁鍵 Page Up、Page Down。
預設配置中的還有 `, .` 及 `-=`兩組。
