### ISSUE TITLE
0.11.1版本的安装文件报有病毒（从curl里头）

### ISSUE THREAD

**Issue by clfsoft** [rime/weasel#248]
0.11.1版本的安装文件报有病毒
https://www.virustotal.com
把文件解压看了一下，好像是curl出的病毒
能否确认一下curl的版本？

https://www.virustotal.com/#/file/e1832b9e80e4a1d23eac9e7663f2f9de021863fd29af6e02bf41cb2091de6075/detection

https://www.virustotal.com/#/file/27625b912e2f96cf6e48d8a250e5fc0c5d4c0619bebd0046da109b8f03fead5d/detection

**Comment by windhamwong** [comment]
基本上virustotal 的值低於10 的話是很大機會誤報.
它顯示的問題是說由於檔案是打包好了所以有可疑, 但是沒有指明這檔案是有毒, 所以可以安心使用
