### ISSUE TITLE
Rime crashes Firefox while switching between languages

### ISSUE THREAD

**Issue by 29988122** [rime/weasel#252]
Steps to reproduce:
1.Start a clean Firefox 64bit under Windows 10 edu 64bit latest update.
2.Prepare at least 3 languages(likely not required). In my situation: ENG, TW, JP.
3.Using alt+shift to switch languages while input focus's in Firefox window.
4.When switched to Rime(TSF), Firefox *randomly* crashes, sometimes even without leaving time for crash report.
5.When crashing, whether the focus's on the webpage or on address bar(Firefox UI element) seemed irrelevant.

Possible Reason:
https://crash-stats.mozilla.com/report/index/32531689-0128-4868-8ba0-442b51180728
I've got one of the crashes here, it explicitly said that weasel.dll was the one who crashed Firefox.

I guess it has something to do again with TSF framework. Google Japanese IME does not cause Firefox to crash.

**Comment by nameoverflow** [comment]
Tried a lot in firefox 62.0b13 but nothing happened.

**Comment by 29988122** [comment]
Could possibly be this problem:
https://support.mozilla.org/zh-TW/questions/1163940

I'm still testing, but seems like the issue came from Firefox side.

**Comment by 29988122** [comment]
For future search engine reference:
it's unrelated to Firefox version nor windows version. It will happen randomly and I cannot reproduce this reliably.

To fix this issue, enter about:config and modify the value intl.tsf.enable to false. Default is true.
Although it will make Firefox's input box behave strangely in certain site like Facebook, but most of the time it will work correctly, without ever crashing Firefox.

**Comment by nameoverflow** [comment]
https://github.com/rime/weasel/commit/63d6d9ac94a0cbcf7651dbbdf2989e2d044ad366 should fix it.

**Comment by 29988122** [comment]
Thank you so much for finding and fixing this bug!
Developing and debugging windows application seems pretty difficult..

謝了，兄弟: D
