### ISSUE TITLE
关于小狼毫语音校对功能的问题请教

### ISSUE THREAD

**Issue by qjwshz** [rime/weasel#255]
据我试用，电脑端输入法方面，小小输入法与启程输入法均具备语音校正或者说语音输入功能。类似你写我读那个小工具实现的效果。手机输入法方面，同文输入法（衍生于小狼毫）在设置中也提供了上屏时朗读字符这个功能开关。在此发贴求问小狼毫能实现类似效果吗？ 请洒潘江，各倾陆海云尔。

**Comment by nameoverflow** [comment]
目前没有。

**Comment by nameoverflow** [comment]
Duplicate of #201
