### ISSUE TITLE
windows10下小狼毫TSF经常在IE、edge、chrome、firefox等浏览器调不出输入窗。

### ISSUE THREAD

**Issue by qq420100523** [rime/weasel#259]
小狼毫在多个浏览器中都会出现输入窗调不出来，只能输入字母。小狼毫版本是最新的0.11.1。

**Comment by nameoverflow** [comment]
没碰到过。
如果 64 位程序都不能用而 32 位程序（如 QQ）可以用的话，有可能是 64 位的 DLL 没有注册成功。试试重新安装。
