### ISSUE TITLE
符号显示问题...

### ISSUE THREAD

**Issue by silveryC** [rime/weasel#260]
想知道为啥我的符号有很多输入的时候显示是个方框

![image](https://user-images.githubusercontent.com/23414002/44711183-575e6380-aae0-11e8-9748-4a247b1ad2a8.png)

配置文件中是正常的，如下
![image](https://user-images.githubusercontent.com/23414002/44711152-46aded80-aae0-11e8-99b9-0c09544c1019.png)

**Comment by nameoverflow** [comment]
请为小狼毫界面设置一个能显示这些符号的字体。
