### ISSUE TITLE
点击输入框导致chrome浏览器关闭

### ISSUE THREAD

**Issue by Dy64** [rime/weasel#265]
流程：
1.打开chrome浏览器，随便输入一些文字
2.点击chrome浏览器空白处，输入框不消失，卡死？（有一定概率不消失）
3.鼠标点击输入框，chrome浏览器会直接关闭（100%）

环境
win10 1803 17134.254
rime：weasel小狼毫最新0.11.1
chrome浏览器版本：
版本 68.0.3440.106（正式版本） （64 位）
版本 69.0.3497.81（正式版本） （64 位）
![default](https://user-images.githubusercontent.com/35034348/45067195-a6b21e80-b0f4-11e8-9efb-77588fdce13c.png)

**Comment by nameoverflow** [comment]
似乎只有 chrome 有这种问题

**Comment by Dy64** [comment]
嗯嗯

今天换了台电脑，win7系统32位，chrome 32位。不会影响chrome自动关闭了，但也有点击空白处输入框不会消失情况。

**Comment by Prcuvu** [comment]
我这里用完全相同的两个版本没有重现这个问题。
