### ISSUE TITLE
遇到的一些问题

### ISSUE THREAD

**Issue by nY381v** [rime/weasel#271]
1，在Evernote，候选框失去了焦点之后不会自动消失，光标位置也极不准确。我试用了几种输入法，只有rime有这种低级错误。
2，候选框显示，而又因为失去焦点而隐藏之后，原窗口的热键都失效了。例如在Firefox，你打字显示了候选框，但你中途放弃输入，鼠标点击浏览器的标签让候选框失去焦点而消失。这时Firefox的所有热键都是失效的，复制粘贴都不行，唯一的解决方法是，重新显示候选框，删除所有输入。
3, 能否提供单独的版本？例如我只使用五笔，能否给我下载五笔的链接。现在我把设置找了遍，也没发现如何切换到五笔。大概只能去搜索教程了。

**Comment by ted423** [comment]
@LArctic 开始菜单里就有设置的快捷方式吧
@nameoverflow 星际争霸2里会遇到

**Comment by konaisland** [comment]
我也有这种情况，是在chrome浏览器里，文本框中输入文字后，在网页的其他地方单击，这时候应该失去焦点，但是并没有，小狼毫还在接受案件，导致chrome插件的案件接收出现问题。
