### ISSUE TITLE
小狼毫puncutor組件對chrome實現有bug，無法輸入逗點與句點，提供一個暫時性解法。

### ISSUE THREAD

**Issue by 29988122** [rime/weasel#273]
Windows 10 1703
Chrome 68
Rime最新版

Steps to reproduce:
打開Chrome
打開Google Doc
使用小狼毫注音中文輸入方案，shift+<或是shift+>輸入句點與逗點。

Expected behavior:
按下shift+<能夠馬上出現逗點，按下shift+>能夠馬上出現句點。

Actual behavior:
shift+<與shift+>需要按下兩次或以上，google doc才能識別讓小狼毫輸入句點與逗點。

Possible cause:
小狼毫
```
punctuator:
  full_shape:
    " " : { commit: "　" }
    "<" : { commit: "，" }
```
punctuator組件中的commit直接上屏行為與chrome/google doc不相容，所以無法順利輸入標點符號。

Workaround:
更改bopomofo_tw.custom.yaml
加入以下內容
```
patch:
  punctuator:
    full_shape:
      " " : { commit: "　" }
      "<" : ，
      ">" : 。
      "?" : [ ？, ／, ÷ ]
      ":" : [ ：, ； ]
      "'" : { pair: [ "‘", "’" ] }
      "\"" : { pair: [ "“", "”" ] }
      "\\" : [ 、, ＼ ]
      "|" : [ ·, ｜, "§", "¦" ]
      "`" : ｀
      "~" : ～
      "!" : ！
      "@" : [ ＠, ☯ ]
      "#" : [ ＃, ⌘ ]
      "%" : [ ％, "°", "℃" ]
      "$" : [ ￥, "$", "€", "£", "¥", "¢", "¤" ]
      "^" : { commit: …… }
      "&" : ＆
      "*" : [ ＊, ·, ・, ×, ※, ❂ ]
      "(" : （
      ")" : ）
      "_" : [ ——, － ]
      "+" : ＋
      "=" : ＝
      "[" : [ 「, 【, 《, 〔, ［ ]
      "]" : [ 」, 】, 》, 〕, ］ ]
      "{" : [ 『, 〖, 〈, ｛ ]
      "}" : [ 』, 〗, 〉, ｝ ]
    half_shape:
      "<" : ，
      ">" : 。
      "?" : [ ？, ／, "/", ÷ ]
      ":" : [ ：, ； ]
      "'" : { pair: [ "‘", "’" ] }
      "\"" : { pair: [ "“", "”" ] }
      "\\" : [ 、, "\\", ＼ ]
      "|" : [ ·, "|", ｜, "§", "¦" ]
      "`" : "`"
      "~" : "~"
      "!" : ！
      "@" : "@"
      "#" : "#"
      "%" : [ "%", ％, "°", "℃" ]
      "$" : [ ￥, "$", "€", "£", "¥", "¢", "¤" ]
      "^" : { commit: …… }
      "&" : "&"
      "*" : [ "*", ＊, ·, ・, ×, ※, ❂ ]
      "(" : （
      ")" : ）
      "_" : [ ——, －, "-" ]
      "+" : "+"
      "=" : "="
      "[" : [ 「, 【, 《, 〔, ［ ]
      "]" : [ 」, 】, 》, 〕, ］ ]
      "{" : [ 『, 〖, 〈, ｛ ]
      "}" : [ 』, 〗, 〉, ｝ ]
```
將句點，逗點與驚歎號使用傳統選字行為，不直接上屏。
這樣chrome能夠穩定的辯認小狼毫RIME的輸入行為與觸鍵。

不過這畢竟不是一個好的長期解法...

**Comment by nameoverflow** [comment]
可能和 #221 是一个问题，遗憾的是并没有任何开发者能复现这个问题。

**Comment by 29988122** [comment]
我研究所讀CS的，雖然不會做動態分析(IDA PRO?)，但是應該還是能想法子除錯然後送PR。

有沒有什麼教程願意提供的？因為我沒法子去trace codebase，能力不在那兒。如果能有detailed log啦、或是有什麼tool可以hook process(RIME TSF, browser/office)啦，錄製監測process interaction的做法，我可以自己想辦法分析。

RIME讓我的生產力提升了兩倍有餘，我自然希望能貢獻些code。

**Comment by nameoverflow** [comment]
由于 Windows 输入法注入进程运行的特殊性没有办法提供相对完整的 log。
执行插入文字的代码位于 https://github.com/rime/weasel/blob/master/WeaselTSF/EditSession.cpp#L20
如果想要使用 debugger 追踪执行情况我们可以提供 debug build 的 DLL 以及符号文件。

**Comment by 29988122** [comment]
我會在課餘的時間試試看，但是目前我只試過Windows Performance Analyzer這個軟體，其專注在記錄process time/resource consumed而已。
https://www.qa-knowhow.com/?p=2500
當然其原理看起來和IDA Pro, WinDbg, gdb之類的debugger有些相似。 

因為不是很清楚該怎麽compile，所以就麻煩提供下符號文件與相關的debugger需要用到的檔案了。我會再研究一下應該要如何進行。

我手邊有書，會當一個中期計劃來執行，試著追蹤調適看看RIME程序。
因為我能100%重現bug，我會試試看能不能夠對bug發生當下的情境有個更好的瞭解，再慢慢寫文件回報，能力允許的話我會試著上PR。

應該要花上好一段時間...

**Comment by 29988122** [comment]
最近練習了一下靜態分析，成功的改動了手上一個dot net binary。
不過動態分析可能還欠點火候，步進、調試、追蹤錄製的方式還不是很熟練，也看不太出來脈絡。

**Comment by 29988122** [comment]
謝謝lotem, open source 專案能夠穩定, 細水長流的維護這麼久, 真的不容易！（我自己就有一個半放棄維護的專案..）

因為您與各位開發的生產力工具RIME，讓我每日花在打字的時間上起碼少了一半。（臺灣人畢竟無法使用有cloud-based 詞庫的拼音輸入法，怎麼用都不對）

再次感謝各位！
