### ISSUE TITLE
小狼毫五笔拼音状态下，怎样打出特殊符号？

### ISSUE THREAD

**Issue by jzmswe** [rime/weasel#277]
朙月拼音可以打出特殊符号，但五笔拼音状态下，无法打出，请问应该怎样设置？

**Comment by CNMan** [comment]
需要对比以下两处修改`wubi_pinyin.schema.yaml`或给其打补丁

https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin.schema.yaml#L101
https://github.com/rime/rime-wubi/blob/master/wubi_pinyin.schema.yaml#L78
和
https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin.schema.yaml#L109
https://github.com/rime/rime-wubi/blob/master/wubi_pinyin.schema.yaml#L86

**Comment by IMLink** [comment]
以前用0.11，自己构建的五笔拼音混合一直没问题，今天升级0.14部署就失败。用了官方提供的五笔拼音，遇到和你一样的问题。研究了一下，在输入法方案中添加以下字段解决问题。
speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba/
