### ISSUE TITLE
请教一下小狼毫是怎么实现在edge里使用的？

### ISSUE THREAD

**Issue by setoutsoft** [rime/weasel#279]
我在也学习输入法开法，用微软的TSF例子编译了，安装后在edge里不能使用，不知道你们是怎么实现的？可以指导一下吗？
谢谢！

**Comment by nameoverflow** [comment]
一句两句说不清楚，参阅 WeaselTSF、WeaselIPC、WeaselIPCServer 中的代码。

**Comment by setoutsoft** [comment]
谢谢！
