### ISSUE TITLE
Support High DPI Display

### ISSUE THREAD

**Issue by fd74a05d0b** [rime/weasel#28]
On high DPI display, the floating selection dialog shifts from the cursor and text in it becomes blurry (not obvious on the picture).
![capture](https://cloud.githubusercontent.com/assets/13931231/9596783/3ddae366-50ac-11e5-930b-0a6400736e26.PNG)

**Comment by lotem** [comment]
Stay tuned for updates on https://github.com/rime/home/issues/25 .
Let's see if the new front-end work better for high DPI.
