### ISSUE TITLE
appveyor 为什么不同步最新的 librime ？

### ISSUE THREAD

**Issue by CNMan** [rime/weasel#280]
测试版本是不是前后端同步编译最新Commit比较好，两边都有修bug的
https://ci.appveyor.com/project/rime/librime

**Comment by CNMan** [comment]
https://github.com/rime/weasel/blob/master/appveyor.install.bat#L11

我的意思是：既然是测试，就应该测试`librime`和`weasel`的最新commit，而不是用`librime`的release版本。

**Comment by nameoverflow** [comment]
Weasel 的测试和 librime 的测试并不一定有相关性。如果要测试最新的 librime 可以自行替换 rime.dll。
