### ISSUE TITLE
win10（1709） 在切换输入法时会导致chrome69 挂掉

### ISSUE THREAD

**Issue by ych0537** [rime/weasel#281]
版本信息如下：
weasel 0.11.1
win10 1709
chrome 69

频度：几乎每天

另外几乎每天都会导致 psi＋ V0.16 挂掉。

**Comment by ych0537** [comment]
挂掉的程序越来越多，emeditor，Teraterm 等等也开始挂掉了。
把小狼毫关掉后，状况消失。
回归google拼音。
等下一个版本在重新尝试。

**Comment by ych0537** [comment]
@nameoverflow 如何下载？

**Comment by nameoverflow** [comment]
https://ci.appveyor.com/project/rime/weasel/build/artifacts

**Comment by ych0537** [comment]
我先安装试试。
