### ISSUE TITLE
如何升级非正规安装的0.9版的用户词典？

### ISSUE THREAD

**Issue by jack980517** [rime/weasel#282]
之前几年里因为一直都没更新，所以也懒得使用官方的安装程序，而是自己用土法安装：
```bat
if %PROCESSOR_ARCHITECTURE%==AMD64 set x64=x64
weaselsetup%x64% /i
weaseldeployer /install
```
于是0.11.0的安装程序似乎就检测不到旧版的存在了。有什么办法让安装程序检测到旧版，或者以其他方法手动升级旧的kct用户词典？

**Comment by nameoverflow** [comment]
直接装，用户文件夹路径对了就行。

**Comment by jack980517** [comment]
没有成功。原本的kct还在，且新的userdb文件夹下全是1KB的文件，实测也没有转移到用户词典的内容。

**Comment by jack980517** [comment]
我看到更新日志里的说明了，装的就是0.11.0

**Comment by Qeynos** [comment]
装0.9.30替换kct再升级？

**Comment by jack980517** [comment]
0.9.30的安装程序现在已经无法下载。bintray上只有0.10.0以后的东西了。

**Comment by lotem** [comment]
0.9.30 的安装程序在这个频道里：
https://bintray.com/lotem/rime/Weasel
如果不能自动升级，一个迂回的办法是在旧版本里同步用户词典，安装新版本后再同步一次，数据就会合并到新格式的用户词典。

**Comment by jack980517** [comment]
使用0.9.30的安装程序在原位置安装一遍以后，再安装0.11.0，成功升级用户词典。谢谢！
