### ISSUE TITLE
输入模式小图标

### ISSUE THREAD

**Issue by PeterBarofsky** [rime/weasel#283]
这几个图标过小，在高分屏下会出现模糊现象
![q](https://user-images.githubusercontent.com/37819754/47262138-c1a8e880-d512-11e8-85ef-acebb87ff29c.png)
![image](https://user-images.githubusercontent.com/37819754/47262140-d4232200-d512-11e8-8b4d-112baffa8804.png)

**Comment by a8568730** [comment]
It seems some icons has been updated. The size of icons are 256x256 now and should look better.

> lotem committed on 8 Feb 2019  
> 093fa80678422f972e7a7285060553eeedb0e591
``` 
feat(ui): high-res status icons; display larger icons in WeaselPanel
```
