### ISSUE TITLE
请问 0.11.1 版本中可以通过配置来实现所有窗口共享同一个中英文状态吗？

### ISSUE THREAD

**Issue by liabco** [rime/weasel#284]
使用过程中的一个问题，希望能够得到您的帮助，谢谢！

**Comment by noodlefighter** [comment]
这属于操作系统的功能，比如win10下你可以通过取消这一项来共享输入法状态（设置-时间和语言-区域与语言-高级键盘设置）：
![image](https://user-images.githubusercontent.com/5947186/47963214-d5506500-e063-11e8-9778-8de7cc6cf8ce.png)

**Comment by lotem** [comment]
沒有這項配置

關聯到相同問題 https://github.com/rime/weasel/issues/454
