### ISSUE TITLE
Win10下进入英雄联盟后，输入法无法打中文

### ISSUE THREAD

**Issue by BiYanzhao** [rime/weasel#285]
win10 1803
小狼毫 0.11.1
进入游戏对局后只能打英文，切换手心输入法后正常打中文

**Comment by Prcuvu** [comment]
0.12.0 除了候选框依旧不正常，应该可以使用了。

**Comment by kokutoukiritsugu** [comment]
调试lol别想了。。。有tp反作弊。
dota2 这游戏有点太大了。

我觉得可以先试试 魔兽争霸3
这游戏无壳，无加密，游戏小。

下面的是搜狗输入法游戏中打字的状态：
![snipaste_2019-03-03_19-30-13](https://user-images.githubusercontent.com/5471433/53694512-eb401d80-3dea-11e9-9e88-12067c476114.jpg)

**Comment by Hug125** [comment]
是可以输入中文的，0.11及之前版本的小狼毫切换成IME，0.12及之上的版本无需配置。
但是不论什么版本，都看不到候选框

**Comment by netroby** [comment]
+1， please support it

**Comment by ted423** [comment]
目前的版本我测试星际2和守望先锋都正常了，你们试一下?

**Comment by Prcuvu** [comment]
全屏游戏为同一类问题。之后所有的重复问题都将标记为本问题的重复。

**Comment by netroby** [comment]
能解决吗？大大们？

**Comment by ted423** [comment]
> 全屏游戏为同一类问题。之后所有的重复问题都将标记为本问题的重复。

幸苦，不过由于部分游戏需要购买，所以不少人无法测试同一个问题，另外就是。该问题是早前反馈的不能输入的问题，后面更新了一版后可以输入了。

但似乎是因为会在全屏游戏下弹输入法框造成，退出全屏或者闪屏。

还有就是可能游戏里不能像微软输入法一样识别当前输入法状态

**Comment by slbb** [comment]
切换中英文时，光标处会浮现的“中/A”小图标。全屏游戏中切换中英文，rime为了显示小图标，会导致全屏游戏自动最小化（弹出桌面）。请问可以加入一个“切换中英文时是否显示小图标”的开关吗？

**Comment by EternalXw** [comment]
安装最新版，在DOTA2里面可以输入中文，但是没法看到候选框，盲人打字

**Comment by Hug125** [comment]
> 安装最新版，在DOTA2里面可以输入中文，但是没法看到候选框，盲人打字

我LOL盲人打字好久了，最近打排位加上星露谷不能打字的问题，我又把微软拼音加回来了

**Comment by dhxsy1994** [comment]
有折中方法去开启IME么？最新版本

**Comment by NuclearBlast** [comment]
WIN10魔兽拼音输入可以选词，但是看不到输入的英文字母

**Comment by chengyuhui** [comment]
来反馈一下最终幻想14国服的状况（应该是类似的问题，就不单独开了）

不启用`inline_preedit`的话，可以输入，看得到候选词，但看不到输入的拼音；
启用该选项的话，可以正常看到候选词。其他游戏有类似问题的也可以尝试一下。

但是无论是否进行设置，都存在切换到聊天模式（有两种方式：点击输入框或者按下Enter）时输入的第一个按键变成w（WASD）的情况。

**Comment by Johnleegy** [comment]
> 
> 
> 全屏游戏为同一类问题。之后所有的重复问题都将标记为本问题的重复。

游戏设置为窗口模式，仍然不会出现候选框，按序号可以输入汉字，但没有候选框无法准确选择啊。

**Comment by whiteS18** [comment]
CSGO 全屏不能打字

**Comment by Asiimoviet** [comment]
csgo全拼不能打字 盲打也不行

**Comment by spphinslove** [comment]
dota2 我打字也看不到字

**Comment by shenlebantongying** [comment]
补充几点：

+ Dota2 在 mac 上原生的输入法 以及 linux 上的 ibus 和 fctix 都完全不能输入。
国服的 windows 客户端应该是添加了一些特别的东西才可以输入中文的。

+ 另外就游戏而言， linux 上大部分游戏也不会支持中文输入。在 steam linux 的相关讨论 <https://github.com/ValveSoftware/steam-for-linux/issues/3255>。不过那是 ibus 和 fctix 的问题了

+ 游戏以外，在 windows 和 mac 都有一些古老或者就是不支持中文的程序，但是输入时候会显示出单独的输入框。猜测是在这个独立的小框里面构成句子以后，再进行“复制粘贴”的操作。

![mac](https://user-images.githubusercontent.com/20123683/97745892-eb148b80-1abf-11eb-8bf4-59e9835e8c67.png)
![windows](https://user-images.githubusercontent.com/20123683/97746002-0b444a80-1ac0-11eb-9852-412577c07fb3.png)


+ 全屏游戏，尤其是 抢占整个屏幕 而非 全屏窗口模式(windowed fullscreen) 的那些，要显示一个输入框可能要做一个类似 steam overlay 的东西。像这两个项目一样 [Andrey1994/game_overlay_sdk](https://github.com/Andrey1994/game_overlay_sdk) 和 [hiitiger/gelectron](https://github.com/hiitiger/gelectron) 给 dx9 dx10 dx11 dx12 vulkan 分别做适配。

**Comment by lostpg** [comment]
LOL 更新了输入框架，现在使用小狼毫已经可以在游戏内看见候选框了。

**Comment by dhxsy1994** [comment]
> LOL 更新了输入框架，现在使用小狼毫已经可以在游戏内看见候选框了。

终于这个issue可以关闭了

**Comment by Prcuvu** [comment]
经亲自测试，已经可以正确显示候选框。关闭本问题。

**Comment by IanDaBest** [comment]
點樣係Minecraft fix呢個問題？
