### ISSUE TITLE
我有这种需求：主要输入简体字，部分字用繁体字替代。请问能做到吗？

### ISSUE THREAD

**Issue by eqbsaf** [rime/weasel#286]
比如：

> 今天天气不错，**後**街上非常热闹，有个女人在扮演皇太后。

『後』与『后』在简体字中简化成了一个字。因为表示方位的『後』字经常用，所以我想在简化字中，把『後』变成高频字，并且所有和『後』有关的詞，由『后』改成『後』。
『几』与『幾』也是同样的情况。
也就是说，如果简体字和繁体字一一对应的字，用简体字。如果一个简体字对应多个繁体字，那就把几个繁体字都显示出来，如果是词组，那就显示繁体字正确的词组（可以提前手动设定好，以后就不再改了）。

还有一种情况，我想把个别繁体字，出现在简体字候选框中，比如当我打 _ai_ 这个拼音时，同时出现『爱』与『愛』两个字，如果是词组拼音 _ai'qing_ ，那么『爱情』与『愛情』也同時出現在候选框，最好能设定哪个词组的前。

总的说来，我想修正简繁一对多的情况和个别的简体字用繁体字替换。

非常感谢！

**Comment by Guwalgiyakuan** [comment]
![image](https://user-images.githubusercontent.com/37359970/47696667-64134b00-dc3a-11e8-8506-44d1f81dff11.png)
![image](https://user-images.githubusercontent.com/37359970/47696757-c409f180-dc3a-11e8-8f6f-ab1bb0c4c65e.png)

我是这样设置，输入法选择朙月拼音简化字，  漢字-汉字。是可以簡體字繁體字同時出現在候選框內，但是出現頻率和簡體繁體組合的詞組要自己多多使用才會高頻率出現。

**Comment by eqbsaf** [comment]
这种方式好像达不到我的要求，可能要手动建立一个词频库才行
