### ISSUE TITLE
IME方式下inline_preedit和preedit_type设置项不起作用

### ISSUE THREAD

**Issue by noodlefighter** [rime/weasel#288]
如题，对inline_preedit和preedit_type进行了设置，但仅在TSF框架下起效，IME下不工作。

weasel.custom.yaml
```
patch:
  "style/color_scheme": doraemon
  "style/horizontal": true    
  "style/inline_preedit": true
  "style/font_point": 12
  "style/preedit_type": preview
```

TSF效果：
![image](https://user-images.githubusercontent.com/5947186/47963138-86ee9680-e062-11e8-92d3-c6d832795703.png)

IME效果：
![image](https://user-images.githubusercontent.com/5947186/47963139-8fdf6800-e062-11e8-8def-13adae2d9835.png)

weasel版本0.11.1
OS版本win10 1803

**Comment by lotem** [comment]
不支持的。详见 https://github.com/rime/home/wiki/CustomizationGuide#%E5%B0%8F%E7%8B%BC%E6%AF%AB%E5%A4%96%E8%A7%80%E8%A8%AD%E5%AE%9A

**Comment by hiuwo** [comment]
如果能用就完美了
