### ISSUE TITLE
如何绕过前端与输入法服务程序交互

### ISSUE THREAD

**Issue by piiiiq** [rime/weasel#299]
能不能绕过输入法现有的前端（选词面板），通过命令行或编程的方式传递给输入法服务程序一个编码，然后得到对应的候选词？
正在做一个程序，不想使用小狼毫的前端，想在程序里自己实现一个前端，希望将编码传递给小狼毫的服务程序，然后得到对应的候选词，然后在自己的程序的前端里显示出来。不知该怎么实现，难道非得调用librime吗？自己的程序是用java写的，不到万不得已不想调用C++库，另外也不知到哪里有librime的api文档可看。

**Comment by Prcuvu** [comment]
如果自己实现前端，最好直接调用 librime，不要试图和小狼毫算法服务通讯，因为那样需要使用 WeaselIPC 的通讯方式（命名管道和 boost::serialization），并不省事。
在 Java 中调用 librime 的话，可以参考下面两个文件编写 JNI 封装。
https://github.com/rime/librime/blob/master/src/rime_api.h
https://github.com/rime/librime/blob/master/src/rime_levers_api.h

**Comment by lotem** [comment]
可以通過標準輸入輸出與 `rime_console` 通信。
