### ISSUE TITLE
利用 UDP 加入"云输入"支持？

### ISSUE THREAD

**Issue by be5invis** [rime/weasel#3]
可以考虑。一个类似 DNS 的协议怎样？

**Comment by Xuanwo** [comment]
感觉云输入这种东西没啥用处= =

**Comment by lotem** [comment]
白度有在線輸入法接口，不過只支持拼音——這可以算進他的無用之處，用於其他輸入法會非常困難
http://olime.baidu.com/

實現上，目前輸入法引擎是在擊鍵後同步返回候選結果的，而雲輸入則是異步的，要在收到回應時以適當的形式插入到已顯示結果中

**Comment by alsophila** [comment]
雲輸入……這是原則性問題啊！
目前使用雲輸入的輸入法大多數都是為大眾打造的，雲端存儲的是大眾的輸入習慣。
我喜歡Rime就是因為……它只會為用戶一個人著想啊！自己的使用習慣不被大眾玷汙，這是多麼清澈而美好的事情啊！

**Comment by qwe7002** [comment]
我个人认为云输入对于rime这样的项目没有必要。如果说真的要有类似的功能，大概就是词库同步了吧。

**Comment by lotem** [comment]
不考慮支持雲輸入了。
目前的雲輸入服務只支持拼音、五筆。自己搭 Rime 輸入方案的雲服務工程較大。

就改善輸入質量，另有一個協同輸入、衆包式改進詞典的構想： https://github.com/rime/plum/issues/5
樓主如果有興趣，不妨瞧瞧，給些建議。
