### ISSUE TITLE
Win10启动时WeaselServer崩溃（偶发）

### ISSUE THREAD

**Issue by Krantz-XRF** [rime/weasel#302]
计算机刚启动时Windows弹出错误消息，WeaselServer崩溃，疑似是解引用空指针造成的，截图如下：
![default](https://user-images.githubusercontent.com/17098235/48882345-b10ec980-ee54-11e8-9bc6-30b1b90fbbc2.png)

本机环境Windows 10 x64，版本号 1803（OS 内部版本 17134.407）。

关闭这个错误提示窗口后，能正常使用输入法，并且这个错误在随后并未复现，目前也未发现其他显著问题。谨在此报告这个错误，顺祝开发顺利。

**Comment by determ1ne** [comment]
Closed as stale, reopen it if the problem still exists.
