### ISSUE TITLE
shift+8的3和4号位置半角全角点问题

### ISSUE THREAD

**Issue by iamsurfing** [rime/weasel#304]
我现在在用朙月拼音・简化字，0.12.0版本小狼毫

我想问一下shift+8的3和4号位置。

为什么看上去半角的点输出是全角的，而看上去全角的点输出半角的？

**Comment by nameoverflow** [comment]
![image](https://user-images.githubusercontent.com/10287709/48966615-fe836600-f00f-11e8-8aa1-6649645b8b53.png)
有什麼問題？

**Comment by iamsurfing** [comment]
![honeycam 2018-11-25 00-05-21](https://user-images.githubusercontent.com/16305191/48970397-a74cb800-f046-11e8-9a64-f24974c54b0c.gif)

**Comment by nameoverflow** [comment]
顯然輸入法字體的問題。

**Comment by iamsurfing** [comment]
你好，我的输入法字体设置为："style/font_face": "Source Han Sans SC"
notepad++字体设置为“思源黑体 HW Bold”
请问有什么问题呢？

**Comment by lotem** [comment]
從動圖上看輸入法用的不是思源黑體，類似Windows系統默認的宋體。
一些中文字體裏面中點符號 `·` 是按中文字符的寬度設計的。

**Comment by iamsurfing** [comment]
谢谢了，现在改好了，发现是配置文件的编码问题。
