### ISSUE TITLE
在游戏中无法切换至中文输入法

### ISSUE THREAD

**Issue by PinkD** [rime/weasel#305]
与 #285 应该是同样的情况 ，在输入法更新到最新版后这个问题并没有得到解决，另外，尝试过无边框和窗口化，也无法切换至中文，文本框右边的输入指示也是 `EN` 而不是 `中` 

猜测可能原因是没有适配 [游戏专用的输入法接口](https://docs.microsoft.com/en-us/windows/desktop/dxtecharts/using-an-input-method-editor-in-a-game)  
在下也曾尝试过读对应源码然后找出问题，但是能力有限，最后放弃了

看到有这么一则公告： [小狼毫前端的兼容性問題將不再修復](https://github.com/rime/home/issues/25)  ，但是此 `issue` 已经关闭，且现在issue中的某些问题已经得到了解决，是否意味着此公告已经作废，rime将继续优化兼容性问题？

因此，请问是否有对游戏中输入问题进行适配的打算？

------
信息：
OS: Win10 1809
Game: Overwatch 1.30.0.1.52926
Weasel: 0.12.0

**Comment by nameoverflow** [comment]
链接的文章并不是面向输入法的接口，是面向游戏开发者的接口。
现在的小狼毫对于全屏模式的接口是完备的，对特定的几个游戏会有问题（如英雄联盟）。目前[CI版](https://ci.appveyor.com/project/rime/weasel)可以在游戏中输入但是无法显示候选字列表，和 Windows 10 版微软拼音刚推出时类似。
限于目前的开发资源，与各种特定程序的兼容不是开发重点，只能保证完全适配平台规范。

**Comment by nameoverflow** [comment]
Duplicate of #285
