### ISSUE TITLE
win7 SP1 下出现内存泄漏

### ISSUE THREAD

**Issue by after1990s** [rime/weasel#306]
weaselServer.exe(32bit) 一直在申请内存，大约半小时后会耗尽8GB的内存。
下面是systeminfo的内容
> 
> Host Name:                 WIN-1VT7NDJ188S
> OS Name:                   Microsoft Windows 7 ??? 
> OS Version:                6.1.7601 Service Pack 1 Build 7601
> OS Manufacturer:           Microsoft Corporation
> OS Configuration:          Standalone Workstation
> OS Build Type:             Multiprocessor Free
> Registered Owner:          Windows ??
> Registered Organization:   
> Product ID:                xxx-xxxxxxxxxxxxxxxxx
> Original Install Date:     2018/1/1, 10:59:39
> System Boot Time:          2018/11/24, 10:13:50
> System Manufacturer:       VMware, Inc.
> System Model:              VMware Virtual Platform
> System Type:               x64-based PC
> Processor(s):              1 Processor(s) Installed.
>                            [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~3600 Mhz
> BIOS Version:              Phoenix Technologies LTD 6.00, 2015/7/2
> Windows Directory:         C:\Windows
> System Directory:          C:\Windows\system32
> Boot Device:               \Device\HarddiskVolume1
> System Locale:             en-us;English (United States)
> Input Locale:              zh-cn;Chinese (China)
> Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
> Total Physical Memory:     8,191 MB
> Available Physical Memory: 5,810 MB
> Virtual Memory: Max Size:  16,381 MB
> Virtual Memory: Available: 14,440 MB
> Virtual Memory: In Use:    1,941 MB
> Page File Location(s):     C:\pagefile.sys
> Domain:                    WORKGROUP
> Logon Server:              \\WIN-1VT7NDJ188S
> Hotfix(s):                 130 Hotfix(s) Installed.
>                            [01]: KB2849697
>                            [02]: KB2849696
>                            [03]: KB2841134
>                            [04]: KB2841134
>                            [05]: KB2670838
>                            [06]: KB2479943
>                            [07]: KB2491683
>                            [08]: KB2506014
>                            [09]: KB2506212
>                            [10]: KB2532531
>                            [11]: KB2533552
>                            [12]: KB2533623
>                            [13]: KB2552343
>                            [14]: KB2560656
>                            [15]: KB2564958
>                            [16]: KB2579686
>                            [17]: KB2585542
>                            [18]: KB2604115
>                            [19]: KB2620704
>                            [20]: KB2621440
>                            [21]: KB2631813
>                            [22]: KB2639308
>                            [23]: KB2653956
>                            [24]: KB2654428
>                            [25]: KB2667402
>                            [26]: KB2685939
>                            [27]: KB2690533
>                            [28]: KB2698365
>                            [29]: KB2705219
>                            [30]: KB2727528
>                            [31]: KB2729094
>                            [32]: KB2729452
>                            [33]: KB2731771
>                            [34]: KB2736422
>                            [35]: KB2742599
>                            [36]: KB2758857
>                            [37]: KB2770660
>                            [38]: KB2786081
>                            [39]: KB2807986
>                            [40]: KB2813430
>                            [41]: KB2834140
>                            [42]: KB2836943
>                            [43]: KB2840631
>                            [44]: KB2847927
>                            [45]: KB2861698
>                            [46]: KB2862330
>                            [47]: KB2862335
>                            [48]: KB2864202
>                            [49]: KB2868038
>                            [50]: KB2871997
>                            [51]: KB2882822
>                            [52]: KB2884256
>                            [53]: KB2888049
>                            [54]: KB2892074
>                            [55]: KB2893294
>                            [56]: KB2894844
>                            [57]: KB2900986
>                            [58]: KB2911501
>                            [59]: KB2912390
>                            [60]: KB2931356
>                            [61]: KB2937610
>                            [62]: KB2943357
>                            [63]: KB2952664
>                            [64]: KB2968294
>                            [65]: KB2972100
>                            [66]: KB2972211
>                            [67]: KB2973112
>                            [68]: KB2973201
>                            [69]: KB2977292
>                            [70]: KB2978120
>                            [71]: KB2978742
>                            [72]: KB2984972
>                            [73]: KB2991963
>                            [74]: KB2992611
>                            [75]: KB2999226
>                            [76]: KB3003743
>                            [77]: KB3004375
>                            [78]: KB3010788
>                            [79]: KB3011780
>                            [80]: KB3019978
>                            [81]: KB3021674
>                            [82]: KB3023215
>                            [83]: KB3030377
>                            [84]: KB3031432
>                            [85]: KB3035126
>                            [86]: KB3037574
>                            [87]: KB3042058
>                            [88]: KB3045685
>                            [89]: KB3046017
>                            [90]: KB3046269
>                            [91]: KB3055642
>                            [92]: KB3059317
>                            [93]: KB3060716
>                            [94]: KB3067903
>                            [95]: KB3071756
>                            [96]: KB3072305
>                            [97]: KB3074543
>                            [98]: KB3075220
>                            [99]: KB3078601
>                            [100]: KB3086255
>                            [101]: KB3092601
>                            [102]: KB3093513
>                            [103]: KB3097989
>                            [104]: KB3101722
>                            [105]: KB3108371
>                            [106]: KB3108664
>                            [107]: KB3109103
>                            [108]: KB3109560
>                            [109]: KB3110329
>                            [110]: KB3115858
>                            [111]: KB3122648
>                            [112]: KB3126587
>                            [113]: KB3127220
>                            [114]: KB3138612
>                            [115]: KB3138910
>                            [116]: KB3139398
>                            [117]: KB3139914
>                            [118]: KB3150220
>                            [119]: KB3155178
>                            [120]: KB3156016
>                            [121]: KB3159398
>                            [122]: KB3161949
>                            [123]: KB3177467
>                            [124]: KB3185319
>                            [125]: KB4019990
>                            [126]: KB4040980
>                            [127]: KB4457044
>                            [128]: KB976902
>                            [129]: KB976932
>                            [130]: KB4467107
> Network Card(s):           2 NIC(s) Installed.
>                            [01]: Intel(R) PRO/1000 MT Network Connection
>                                  Connection Name: ????
>                                  DHCP Enabled:    Yes
>                                  DHCP Server:     192.168.11.254
>                                  IP address(es)
>                                  [01]: 192.168.11.129
>                                  [02]: fe80::e95d:29b1:6f8c:569e
>                            [02]: Bluetooth ??(?????)
>                                  Connection Name: Bluetooth ????
>                                  Status:          Media disconnected

**Comment by nameoverflow** [comment]
系统补丁导致内存泄漏？这么魔幻？

**Comment by Prcuvu** [comment]
> 系统补丁导致内存泄漏？这么魔幻？

那个应该只是安装的补丁列表。

**Comment by after1990s** [comment]
@nameoverflow 我dump了一个内存泄漏状态的进程，应该有助于排查问题。

我再详细描述下问题触发的时机：
win7 开机后，调出rime输入法，拥有输入焦点的进程立即失去响应。然后weaselServer.exe(32bit)进程进入内存泄漏状态。
强行kill掉失去响应的进程再调出rime输入法可以正常进行输入，但是weaselServer进程一直在申请内存。

weaselServer的dump文件：
[weaselServer_dump.zip](https://github.com/rime/weasel/files/2613814/weaselServer_dump.zip)

崩溃进程的dump文件：
[notepadpp_crash.zip](https://github.com/rime/weasel/files/2613822/notepadpp_crash.zip)

**Comment by after1990s** [comment]
下面是失去响应后时notepad++的栈帧情况：

```
0:000> k
 # ChildEBP RetAddr  
00 00139cf4 7624de95 ntdll!ZwReadFile+0x15
01 00139d58 76d64029 KERNELBASE!ReadFile+0x118
*** WARNING: Unable to verify checksum for C:\Windows\SysWow64\weasel.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Windows\SysWow64\weasel.dll - 
02 00139da0 700a8dd2 kernel32!ReadFileImplementation+0xf0
WARNING: Stack unwind information not available. Following frames may be wrong.
03 00139df0 700a7cf8 weasel!DllUnregisterServer+0x2172
04 00139e68 700a7b4a weasel!DllUnregisterServer+0x1098
05 00139ea0 700a7734 weasel!DllUnregisterServer+0xeea
06 00139eb8 771aa063 weasel!DllUnregisterServer+0xad4
07 00139ecc 771aa260 MSCTF!CTip::Activate+0x2d
08 00139f58 7719153e MSCTF!CThreadInputMgr::_ActivateTip+0
...
```

**Comment by determ1ne** [comment]
Closed as stale, reopen it if the problem still exists.
