### ISSUE TITLE
win10 设置文件 menu/page_size 修改无效

### ISSUE THREAD

**Issue by kawori** [rime/weasel#307]
win10下修改default.yaml中menu/page_size，重新部署之后仍然只有5个候选词。
单独修改luna拼音的配置文件中的page_size结果同样如此。

**Comment by nameoverflow** [comment]
不应当修改 `default.yaml` 或 `luna_pinyin.schema.yaml`，应创建 `default.custom.yaml` 或 `luna_pinyin.custom.yaml`

**Comment by kawori** [comment]
在尝试创建default.custom.yaml、重新部署无效果之后，才不得已修改的default.yaml。weasel.yaml同理。


________________________________
发件人: nameoverflow <notifications@github.com>
发送时间: Saturday, November 24, 2018 5:35:56 PM
收件人: rime/weasel
抄送: kawori; Author
主题: Re: [rime/weasel] win10 设置文件 menu/page_size 修改无效 (#307)


不应当修改 default.yaml 或 luna_pinyin.schema.yaml，应创建 default.custom.yaml 或 luna_pinyin.custom.yaml

―

**Comment by Prcuvu** [comment]
请参考[这篇文档](https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%AF%8F%E9%A0%81%E5%80%99%E9%81%B8%E6%95%B8)，在用户文件夹建立文件进行设置。

**Comment by kawori** [comment]
Weasel0.12版本，默认设置文件default.yaml等在用户文件夹下的build文件夹内，如果将custom文件也放在build文件夹内则不会生效，置于用户文件夹主目录下才能生效。
我记得以前的设置文件是在用户文件夹主目录内的。

**Comment by Prcuvu** [comment]
build 文件夹中是合并了程序文件夹中的原始文件和用户文件夹的 custom 文件后的输出文件，用户不可编辑。请无视这个文件夹，只在用户文件夹中进行编辑。

**Comment by zhouyisu** [comment]
想接着这个问题继续问一下。我重装了win10之后也遇到了这个问题。Weasel 0.13，在用户文件夹下按照以下定义了default.custom.yaml，但候选字还是5个：

![WeChat Screenshot_20190324113910](https://user-images.githubusercontent.com/11703069/54874604-a461a880-4e29-11e9-94dd-cd0fe228932f.png)


尝试更改上面其他的参数（如把caption改成「切换111」），是可以生效的，就是page_size这一项不行。望赐教。
