### ISSUE TITLE
[功能建议]快速启动程序

### ISSUE THREAD

**Issue by WanderMax** [rime/weasel#309]
这个想法我是在拼音加加里面看到的，通过一个配置文件，设置键盘输入字母，候选提示词(一般为程序名)，启动程序路径的对应关系。当输入相应字母，候选框出现程序名候选，选择候选，启动相应程序。
例如 ut  [utorrent]D:\utorrent\utorrent.exe
当然具体格式可以变化，只要对应关系清楚即可。
那么输入 ut，候选框出行[utorrent]词条，选择就启动对应程序。当同一个输入字母对应多个程序，那么就显示多个候选词。
希望我的解释是清楚的，谢谢！

**Comment by ShynHan** [comment]
输入法只有在可编辑区域（编辑器，文本框之类的地方）才能打字，显示预览框，这就限制了应用场景。
还是一些专业的快速启动工具适用面更广，用起来也方便，功能上也更强大一些。输入法么，感觉还是老老实实的码字吧，但是小狼毫始终不支持当前时间和日期的快速输出有一点点的不方便。
