### ISSUE TITLE
为什么我的小狼输入法无法在状态栏显示小图标

### ISSUE THREAD

**Issue by shihuibei** [rime/weasel#31]
版本是最新的版本

**Comment by Prcuvu** [comment]
你需要在用户文件夹（链接在开始菜单可以找到）新建`weasel.custom.yaml`文件，输入以下内容：
```YAML
patch:
  "style/display_tray_icon": true
```
保存，重新部署。

**Comment by zaqzrh** [comment]
在win10中，display_tray_icon: true已有损伤了，开机时，状态栏无法显示这小图标了。

**Comment by shihuibei** [comment]
我的是windows7，已经按照上述方法成功解决

**Comment by Prcuvu** [comment]
@shihuibei 既然问题解决了，那就关掉这个issue吧。
