### ISSUE TITLE
中英文状态提示光标提示建议

### ISSUE THREAD

**Issue by ShynHan** [rime/weasel#310]
经常写一些文档，中英文混输的时候十分痛苦，经常忘记切换，打到一半发现中英文状态不对，还要删掉重写，时间长了感觉越来月难以忍受，寻求解决办法，最开始想的是智能切换之类的方法，但是实际操作起来感觉就是智障切换，很不适应。
然后想到一个感觉上简单的办法，光标提示输入法状态，因为总要用光标定位，基本上视线在哪里，光标就在哪里，所以通过光标上提示的输入法状态来提醒自己是否需要切换。
小狼毫本身就带有切换状态光标悬浮提示的功能，但是并不是十分好用，因为经常性的光标不跟随，而且只有在每次切换输入法的时候才会有提示。用度娘找到了一个 AHK 脚本，感觉十分好用，反映灵敏，基本没有延迟，但是只能用在搜狗输入法上。

**AHK脚本，后缀改成 txt 了，要不然不让上传**
[光标提示输入法状态.txt](https://github.com/rime/weasel/files/2653257/default.txt)

![honeycam 2018-12-06 21-18-28](https://user-images.githubusercontent.com/12025422/49587796-ead8e780-f99f-11e8-9b09-213d3c367663.gif)

这个脚本在编辑器或者可以输入文字的地方里每次点击或者按「Shift」都会在提示输入法状态，其他时候则不会提示（感觉是光标只要变成「工」型，点击就会提示，变成「箭头型」就恢复正常）。
最重要的是这个提示永远跟随光标，没出现过不跟随现象。
这个 AHK 脚本可以获取到搜狗的中英文状态，但是无法获取小狼毫的中英文状态，我想知道如何让这个脚本获取到小狼毫的中英文状态？
如果可以更希望这个功能可以添加到小狼毫上。
如果有大佬亲自出手修改就更好了，不会 AHK 脚本，看文档也是一知半解的，所以才上这里求助。

**Comment by ShynHan** [comment]
可以看到上面的gif里没有小狼毫的悬浮提示，因为小狼毫的悬浮提示一直屏幕的右下角不跟随，没录到

**Comment by ShynHan** [comment]
小狼毫有个常驻服务进程，可以让让 AHK 调用这个进程的什么功能之类的获得当前输入法的中英文状态么？

**Comment by ShynHan** [comment]
自己改写了一下脚本，已经可以正常使用蓝

**Comment by KhaosChow** [comment]
请问可以分享下你修改后的脚本代码吗？我也有类似的需求。

**Comment by q631263135** [comment]
@ShynHan 你好，你用的输入法版本和AHK的版本是多少，我弄了一天了没成功（win7环境）

**Comment by ShynHan** [comment]
@KhaosChow @q631263135 脚本重做系统时已经丢失了，现在小狼毫最新版本在修改中英文输入的时候已经可以在光标位置提示了，所以脚本的意义已经不是很大了，当时的思路是用的 AHK 图片搜索功能，截取小狼毫中英文两种状态栏图标，然后进行图片匹配，代码是在原有代码基础上改的，以后找到这段代码我会再分享给两位

**Comment by yu-soong** [comment]
@ShynHan 请问，你的AHK脚本找到了吗？能否分享给我？有一个AHK脚本，需要确定小狼毫的输入状态。谢谢！

**Comment by q631263135** [comment]
附件是三个 ahk 脚本，你看下 是否可以帮到你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rime/weasel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月18日(星期六) 上午8:21
收件人:&nbsp;"rime/weasel"<weasel@noreply.github.com&gt;;
抄送:&nbsp;"631263135"<631263135@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [rime/weasel] 中英文状态提示光标提示建议 (#310)





 
@ShynHan 请问，你的AHK脚本找到了吗？能否分享给我？有一个AHK脚本，需要确定小狼毫的输入状态。谢谢！

**Comment by q631263135** [comment]
使用 ctrl + shift&nbsp; +&nbsp;`，开启提示，像这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rime/weasel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月18日(星期六) 上午8:21
收件人:&nbsp;"rime/weasel"<weasel@noreply.github.com&gt;;
抄送:&nbsp;"631263135"<631263135@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [rime/weasel] 中英文状态提示光标提示建议 (#310)





 
@ShynHan 请问，你的AHK脚本找到了吗？能否分享给我？有一个AHK脚本，需要确定小狼毫的输入状态。谢谢！

**Comment by yu-soong** [comment]
@ShynHan 没有看到附件，可能GitHub 不支持附件。可以发送到我的邮箱吗？rainsoong@gmail.com。谢谢！
小狼毫用 IME_GET() 这个函数无法分辨是中文还是英文。你的“用的 AHK 图片搜索功能，截取小狼毫中英文两种状态栏图标”估计是唯一的办法了吧。

**Comment by komazhou** [comment]
> @ShynHan 没有看到附件，可能GitHub 不支持附件。可以发送到我的邮箱吗？[rainsoong@gmail.com](mailto:rainsoong@gmail.com)。谢谢！
> 小狼毫用 IME_GET() 这个函数无法分辨是中文还是英文。你的“用的 AHK 图片搜索功能，截取小狼毫中英文两种状态栏图标”估计是唯一的办法了吧。

IME_GET(WinTitle=""){ ;借鉴了某日本人脚本中的获取输入法状态的内容,减少了不必要的切换,切换更流畅了
;-----------------------------------------------------------
;   IMEの状態の取得
;   対象： AHK v1.0.34以降
;   WinTitle : 対象Window (省略時:アクティブウィンドウ)
;   戻り値  1:ON 0:OFF
;-----------------------------------------------------------
    ifEqual WinTitle,,  SetEnv,WinTitle,A
    WinGet,hWnd,ID,%WinTitle%
    DefaultIMEWnd := DllCall("imm32\ImmGetDefaultIMEWnd", Uint,hWnd, Uint)

    ;Message : WM_IME_CONTROL  wParam:IMC_GETOPENSTATUS
    DetectSave := A_DetectHiddenWindows
    DetectHiddenWindows,ON
    SendMessage 0x283, 0x005,0,,ahk_id %DefaultIMEWnd%
    DetectHiddenWindows,%DetectSave%
    ;Return ErrorLevel
;   以下内容专为rime输入法增加
    IME1 := ErrorLevel
    ImageSearch, , , 1600, 1000, A_ScreenWidth, A_ScreenHeight, rime_ahk.png
    IME2 := ErrorLevel
    if (IME1=0 or IME2=1)
        IME := 0
    else
        IME := 1
    Return IME
}
