### ISSUE TITLE
“英雄联盟”与“firefox”有些地方不能输入

### ISSUE THREAD

**Issue by iamsurfing** [rime/weasel#316]
火狐是在“选项-在选项中查找”不能输入（中文），但是能输入英文。
英雄联盟不能输入我是最不明白的。升级前有两个（小狼毫）输入法的时候，其中一个是可以输入的（另一个好像不能）。然后升级后只有一个小狼毫了，但是却不能输入了，请问为什么？还是说我应该回滚版本？

**Comment by KagefumiMerry** [comment]
因為最新的0.12版本把傳統IME和TSF兩個版本輸入給整合，而TSF版本在遊戲等特殊運用下反而沒有IME版本（Windows Desktops Only）那樣好用。
如果真的有需要就只能回滾上一個版本吧。

**Comment by iamsurfing** [comment]
@KagefumiMerry 
那火狐那个又是怎么回事？

**Comment by Hug125** [comment]
0.12之后的版本可以输入，只是看不到候选框。

**Comment by lotem** [comment]
同 https://github.com/rime/weasel/issues/285
