### ISSUE TITLE
切换输入之后，第一个字母总是没有了

### ISSUE THREAD

**Issue by 29e7e280-0d1c-4bba-98fe-f7cd3ca7500a** [rime/weasel#317]
切换输入之后，第一个字母总是没有了。
症状表现：
1. 切换输入法
2. 在中文输入装态下，打字（任意字母都可以）
3. 发现第一个字母没了，莫名其妙

操作系统 windows 10 x64 18.10
rime weasel 最新版

**Comment by netroby** [comment]
老板牛逼，大神牛逼， 感谢。 麻烦发布一个新版release，测试测试。

**Comment by netroby** [comment]
@sih4sing5hong5 感谢薛老板。非常深厚的功力。非常丰富的经验。也谢谢@lotem
