### ISSUE TITLE
windows 10 1803下，鼠标点击候选框使wps崩溃。

### ISSUE THREAD

**Issue by Fly4M** [rime/weasel#318]
系统：windows10 1803 17134.471
使用0.12.0版小狼毫在wps打字，用鼠标点选候选框内的字词，会是wps崩溃重启。（100%）

**Comment by magastzheng** [comment]
我也碰到类似问题，在有道笔记客户端里面。
系统：Windows7 SP1
小狼毫版本：0.13.0.0和0.14.3.0
有道笔记版本：Windows桌面版v6.8.0.0

在有道笔记客户端中，使用“明月拼音简化字”输入中文时，有道笔记经常会崩溃。在windows事件查看器里面，只看到有道笔记崩溃的信息。使用搜狗拼音输入法时，没有碰到过类似问题。

最开始使用 0.13.0.0版，崩溃太频繁，想着升级试试，升级之后，问题仍然存在。

错误应用程序名称: YoudaoNote.exe，版本: 6.8.0.0，时间戳: 0x5c91ab7d
错误模块名称: libcef.dll，版本: 3.3029.1613.0，时间戳: 0x590d6de1
异常代码: 0x4000001f
错误偏移量: 0x006f9abc
错误进程 ID: 0x1d40
错误应用程序启动时间: 0x01d52c7ea0ab0695
错误应用程序路径: C:\Program Files (x86)\Youdao\YoudaoNote\YoudaoNote.exe
错误模块路径: C:\Program Files (x86)\Youdao\YoudaoNote\libcef.dll
报告 ID: dd894611-996d-11e9-8d1c-480fcf3e4120
