### ISSUE TITLE
Windows 下无法保存任何设置

### ISSUE THREAD

**Issue by iugo** [rime/weasel#32]
E0919 16:06:39.291185  2008 tree_db.cc:162] Error opening db 'luna_pinyin.userdb.kct'.
E0919 16:06:39.292186  7816 tree_db.cc:175] Error opening db 'luna_pinyin.userdb.kct' read-only.
E0919 16:06:39.293187  7816 tree_db.cc:139] treedb recovery failed.

是 Windows 的权限出了问题吗？该如何修改？

**Comment by lotem** [comment]
用戶文件夾有沒有 `luna_pinyin.userdb.kct` 這個文件？刪除該文件能行嘛？

**Comment by iugo** [comment]
沒有找到 `luna_pinyin.userdb.kct` 這個文件。

將 UAC 關閉。重新安裝，還是類似錯誤。安裝之後選擇的界面配色在重啓後正常，但是其他設置，如更改拼音方案，切換簡繁等均被重置（不重啓不會被重置）。應該是哪裏的權限出錯了吧？

這次我切換到地球拼音，錯誤是類似這樣的：

```
E1108 23:54:38.487108  5052 tree_db.cc:162] Error opening db 'terra_pinyin.userdb.kct'.
E1108 23:54:38.487108  7592 tree_db.cc:175] Error opening db 'terra_pinyin.userdb.kct' read-only.
E1108 23:54:38.487108  7592 tree_db.cc:139] treedb recovery failed.
E1108 23:54:38.487108  7592 tree_db.cc:162] Error opening db 'terra_pinyin.userdb.kct'.
E1108 23:54:38.487108  7592 userdb_recovery_task.cc:54] Error creating db 'terra_pinyin.userdb.kct'.
```

在另外一臺 Windows 上沒有問題。應該是個例。

**Comment by lotem** [comment]
更改拼音方案，切換簡繁等——这些信息保存在 user.yaml，通常是在 WeaselServer.exe 退出时保存的（重新部署也会保存）。
我怀疑 Windows 没有正常关机，或者系统被修改过，关机时强制结束后台进程，所以没有保存上。

**Comment by iugo** [comment]
<img width="373" alt="default" src="https://cloud.githubusercontent.com/assets/499364/11053947/c435ee26-87a0-11e5-9dbd-6b474e608084.png">

**Comment by iugo** [comment]
我的 Windows 是从 7 升级到 10 的。

可能是权限问题。在非系统盘（C 盘符安装的系统，我这次将鼠须管安装到了 D）安装后正常了。

**Comment by iugo** [comment]
我在鼠鬚管上也遇到了類似的問題，本來已經進行了簡體繁體的切換，但當我切換到英文再切換回鼠鬚管時，剛纔的設置失效了。
