### ISSUE TITLE
Win10 LTSC 每次启动/重启系统，小狼毫不可用

### ISSUE THREAD

**Issue by mokapsing** [rime/weasel#320]
如题，每次启动系统小狼毫都不能打字，等待一段时间也不行，必须杀掉常驻进程，再从开始菜单启动一次小狼毫服务才能正常打字

**Comment by ijliym** [comment]
我的都没问题。

**Comment by oopp1800** [comment]
出现一样的问题，右键右下角输入法图标「退出算法服务」后再手动启动 WeaselServer 才可以，希望能够解决这个问题。

不知道 log 文件在哪里，如果有需要可以提供。
