### ISSUE TITLE
能否提供关闭候选框的接口

### ISSUE THREAD

**Issue by Gaeric** [rime/weasel#325]
在输入速度较高的情况下，闪烁的候选框让人极度不适；
能否实现一个关闭候选框的功能，并将接口提供给用户呢？
用户可以选择是否开启候选框，
默认为关闭时，在某个自定义的按键下可以临时弹出候选框。

**Comment by fxliang** [comment]
0.15.0起，只要设置`margin_x`或`margin_y`为负数即可实现隐藏，但是没有按键临时重开的功能
