### ISSUE TITLE
移除版本自适应代码的计划

### ISSUE THREAD

**Issue by Prcuvu** [rime/weasel#326]
现有的版本为了支持较低版本的 Windows，我引入了版本自适应代码，调用了 `ntdll.dll` 中的函数。这可能是 Windows Defender 报毒的原因。我希望在未来的版本逐步移除这些代码，使代码变得简明，把更多的精力用在新功能的开发上：
1. 新版本的 boost 线程库对 Windows XP 不友好，并且主流全屏游戏（LoL）即将抛弃 Windows XP，应在下一个版本移除对 Windows XP 的支持以迁移到新版本 boost；
2. 2020 年 Windows 7 停止扩展支持时移除检测 Windows Vista 和 Windows 7 的代码，最低操作系统要求提升到 Windows 8.1，以开发对彩色字体（彩色绘文字）渲染的支持。

**Comment by lotem** [comment]
好啊。支持啊。

**Comment by ysc3839** [comment]
看了一下代码，InitVersion 只在 WeaselServer 和 WeaselTSF 中用到
https://github.com/rime/weasel/blob/e2ead5f5ade5e326c47fc18fe4dc091aaa7dfeb9/WeaselServer/WeaselServer.cpp#L33
https://github.com/rime/weasel/blob/e2ead5f5ade5e326c47fc18fe4dc091aaa7dfeb9/WeaselTSF/Server.cpp#L115

对于 WeaselServer，可以在 manifest 中加入 [supportedOS](https://docs.microsoft.com/en-us/windows/desktop/sysinfo/targeting-your-application-at-windows-8-1) 进而通过受支持的 API 获取到准确的系统版本。
而对于 WeaselTSF，因为运行在别的进程中，无法修改，不过搜索代码只发现两处判断系统版本的地方：
https://github.com/rime/weasel/blob/e2ead5f5ade5e326c47fc18fe4dc091aaa7dfeb9/WeaselTSF/Register.cpp#L48
https://github.com/rime/weasel/blob/e2ead5f5ade5e326c47fc18fe4dc091aaa7dfeb9/WeaselTSF/Register.cpp#L137
没记错的话如果没有加入 supportedOS，获取到的系统版本会是 Windows 8，也不影响这两处。

**Comment by ysc3839** [comment]
对于旧系统支持，我认为停止支持 Windows XP 没什么问题。明年就停止支持 Windows 7 可能不太好。
