### ISSUE TITLE
右击小狼毫打开用户文件夹会卡住

### ISSUE THREAD

**Issue by bickman** [rime/weasel#329]
win10和win7都试过，右击小狼毫打开用户文件夹会卡住，然后explore会重启然后才能打开

**Comment by Prcuvu** [comment]
我无法重现。需要其他用户更详细的反馈。

**Comment by omgredfog** [comment]
win10-1803，win10-1809，以无密码管理员身份直进系统，只要开机后不打字，不碰键盘，直接进入系统，然后去托盘右键，点击程序文件夹或用户文件夹，就会100%卡死，表现为立刻白屏，卡上20~100秒不等，自动卡死当前所有进程，然后explorer会重启，之后才能打开相应文件夹。

**Comment by omgredfog** [comment]
维护小狼毫的开发人员坚持说无法重现，但是我与楼主一样的情形，非常困扰。因为我已在我司28位同事的win10上，100%复现了这个问题，现在我私下将右键代码改为调用内置cmd打开相应路径的方式，重新编译，暂时解决了这个问题。

**Comment by bickman** [comment]
嗯，楼主我之前0.12.0会有这个问题，13版本就好了

**Comment by omgredfog** [comment]
从0.12到0.13，改动的代码并产包含托盘右键，问题依然存在。楼主说的「好了」，可能只是你在win10的使用方式上有了一些变化，比如操作都是在weasel.exe被激活之后。我这边还是可以复现的，楼主可以再试试楼上的复现方式。

**Comment by nameoverflow** [comment]
> 调用内置cmd打开相应路径的方式

这是什么方式？
