### ISSUE TITLE
Vim 中能否记住 ESC 前的状态？

### ISSUE THREAD

**Issue by idnsunset** [rime/weasel#331]
更新到 0.13 版后，遇到如下情况：第一次进入 Insert 模式，激活输入法，按 Shift 切换到英文输入模式。回到 Normal 模式后，输入法会自动处于 inactive 状态。再次进入 Insert 模式，输入法总是会处于中文输入模式。对于大篇幅中英文混合的文本输入，每次从 Insert 模式回到 Normal 模式再进入 Insert 模式，都需要按一次 Shift 切换到英文输入模式，非常扰人。有没有办法在进入 Insert 模式后沿用前一次 Insert 模式下输入法的中/英文模式？

**Comment by mdmawat** [comment]
> 另外，在 Normal 模式下，输入法处在英文输入模式，但是按 R 键之后，会自动切换到中文，Vim 的替换命令无法执行。前一个版本没有这样的问题。

我用的 Windows7，确实有这样的问题，在插入模式下按回车换行，会自动切换到中文输入模式；在普通模式下按 R 替换字符，会自动切换到中文输入模式，所以我用回 0.11 版了。0.12 版本也有同样的问题。

**Comment by bickman** [comment]
我觉得在vim下面weasel的状态有点混乱，没有规律，大部分情况按插入模式，直接就进入非输入法状态，但是切换几次，又变成在命令模式进入非输入法状态，进入插入模式变成中文输入法的良好状态

**Comment by ijliym** [comment]
你们的 Vim 设置了这个吗？

```vim
" 插入模式时，启用输入法（For Win10+Rime; :h IME） 2018-07-31 19:43
set iminsert=2
```

我也觉得 Vim 的输入状态是点问题，比如，我在插入模式时，将输入法切换为英文输入（Shift），再输入 ()、[]、{}、''、"" 等符号或者使用复制、粘贴、剪切这些快捷键时，输入法状态都会切换为中文。

**Comment by idnsunset** [comment]
> 你们的 Vim 设置了这个吗？
> 
> ```viml
> " 插入模式时，启用输入法（For Win10+Rime; :h IME） 2018-07-31 19:43
> set iminsert=2
> ```
> 
> 我也觉得 Vim 的输入状态是点问题，比如，我在插入模式时，将输入法切换为英文输入（Shift），再输入 ()、[]、{}、''、"" 等符号或者使用复制、粘贴、剪切这些快捷键时，输入法状态都会切换为中文。

设定这个选项并没有什么用，你在 Vim 中调用 Rime 时，该选项自动变为 2。现在的问题并不是在普通模式下，Rime 无法切换到英文输入模式，而是当我在插入模式中已经把 Rime 切换成英文输入模式（因为我要大段输入英文），但回到普通模式（做一些编辑）再次进入插入模式（继续输入）时，它会自动切换到中文输入模式。

**Comment by superhxl** [comment]
我也有这个问题，win10，0.13版本。其他地方用的挺开心的，每到vim中就不开心了！按shift切换后，随便退格立马就切换为中文了。

**Comment by lotem** [comment]
過去版本可能相關的討論： https://github.com/rime/weasel/issues/232

**Comment by idnsunset** [comment]
> 過去版本可能相關的討論： #232

与这个 #232 并无关联。我安装了最新的 0.14.3 版本，问题依旧。

- 在 Normal mode 下按 R 键会激活输入法，导致 Vim 的替换命令无法执行。
- 在 Insert mode 中切换到 ascii mode，返回 Normal 后再次进入 Insert mode 后，变成中文模式。

0.11 版本不存在这样的问题。另外，在 Linux 上使用 fcitx-rime 也不存在这样的问题。
