### ISSUE TITLE
启动算法服务时，自动部署不完全

### ISSUE THREAD

**Issue by ijliym** [rime/weasel#335]
小狼毫“退出算法服务”后，删除 `%AppData%\Rime\build` 目录下的所有文件，再启动“小狼毫算法服務”时，会启动后自动部署，但是自动部署会不成全，不能生成“weasel.yaml”文件，要“重新部署”才能生成；或者有时自动部署会不启动。

**Comment by lotem** [comment]
是的。請務必重新部署。
原因是：自動部署不是小狼毫的功能，而是`librime`的一項功能，因此不會處理`weasel.yaml`。
Linux的軟件安裝通常在root賬戶下進行，在輸入法運行之前，沒有機會爲終端用戶執行部署操作。這般場景下`librime`的自動部署保證用戶首次使用的完整體驗。
對小狼毫來說，自動部署是一項冗餘功能。安裝程序會執行首次部署，用家修改了配置，不會自動生效，應手動觸發部署。
啓動算法服務時的自動檢測，只針對設計的使用場景，即不存在用戶數據的情況；出於效率考量，不會全面檢查是否有配置變更。因此不可以用重啓算法服務的方法代替重新部署。
