### ISSUE TITLE
任务栏图标大小问题

### ISSUE THREAD

**Issue by dupontjoy** [rime/weasel#336]
![default](https://user-images.githubusercontent.com/4965288/52694065-8344a700-2fa3-11e9-83a8-edc5b7324faf.png)
如图, rime右边那个图标, 鼠标悬停时可以看到边框太大了, 导致任务栏两列图标时图标未对齐, 视角错位了

**Comment by Guwalgiyakuan** [comment]
![default](https://user-images.githubusercontent.com/37359970/52835771-78605280-311a-11e9-8a98-7d7193c28a17.png)
0.13.0 版本貌似沒有這個問題了。

**Comment by Prcuvu** [comment]
Windows 10 语言栏与任务栏其余图标是不同的部件，在设计上右侧图标（用于切换输入法）就比较宽。

**Comment by dupontjoy** [comment]
右侧图标是底部阴影太大了, 调小一点就可以解决了吧

**Comment by Prcuvu** [comment]
不可以，右侧图标是固定宽度。
