### ISSUE TITLE
小狼毫 0.13.0 托盘图标显示不正常

### ISSUE THREAD

**Issue by lenhoo** [rime/weasel#338]
![1111](https://user-images.githubusercontent.com/2655856/52831102-52cd4c00-310e-11e9-98ce-16b7bcfe2c70.PNG)
显示的是模糊的文字

**Comment by lotem** [comment]
这不是新换的图标嘛。我看挺正常的。

不过我已经高清重制了旧版图标。因此可以关闭这一单。
