### ISSUE TITLE
windows版是不支持圆角吗？

### ISSUE THREAD

**Issue by lonelykid** [rime/weasel#340]
corner_radius好象无效

**Comment by Guwalgiyakuan** [comment]
候選詞外框目前win系統不支持圓角設置。內框可以設置。
![default](https://user-images.githubusercontent.com/37359970/53138985-b4803100-35ba-11e9-8e00-32b5b98655a1.png)

**Comment by Prcuvu** [comment]
由于系统原因不支持。

**Comment by 1478zhcy** [comment]
现在Windows 11出来了，未来还会支持圆角吗

**Comment by lotem** [comment]
準確地說是目前小狼毫使用的界面技術不支持透明窗體。
期待有高人來相助，用新技術改寫界面。

**Comment by plainee** [comment]
> 现在Windows 11出来了，未来还会支持圆角吗

已经支持了。
![image](https://github.com/rime/weasel/assets/54027179/7d9336cc-25bf-444c-994b-f6b1702ba8a4)

**Comment by AmazingRise** [comment]
> 已经支持了。 ![image](https://private-user-images.githubusercontent.com/54027179/303199326-7d9336cc-25bf-444c-994b-f6b1702ba8a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTUwMjksIm5iZiI6MTcxMDY5NDcyOSwicGF0aCI6Ii81NDAyNzE3OS8zMDMxOTkzMjYtN2Q5MzM2Y2MtMjViZi00NDRjLTk5NGItZjZiMTcwMmJhOGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE2NTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZGI1NjZhMzMyNTQ0Y2U5OTIzNzA2NjkzMmU4NGY0Nzc3MGZhYjgxYzE4YjEwMmI3N2ZjMzNkYzJhYWJlNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nHj7S1WaG16JpXugzv3674vhQVqdafdBll4O9K-eepQ)

@plainee Hi，请问可以发一下配置吗
以及你用的是nightly版本还是0.15.0？

**Comment by plainee** [comment]
> > 已经支持了。 ![image](https://private-user-images.githubusercontent.com/54027179/303199326-7d9336cc-25bf-444c-994b-f6b1702ba8a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTUwMjksIm5iZiI6MTcxMDY5NDcyOSwicGF0aCI6Ii81NDAyNzE3OS8zMDMxOTkzMjYtN2Q5MzM2Y2MtMjViZi00NDRjLTk5NGItZjZiMTcwMmJhOGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE2NTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZGI1NjZhMzMyNTQ0Y2U5OTIzNzA2NjkzMmU4NGY0Nzc3MGZhYjgxYzE4YjEwMmI3N2ZjMzNkYzJhYWJlNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nHj7S1WaG16JpXugzv3674vhQVqdafdBll4O9K-eepQ)
> 
> @plainee Hi，请问可以发一下配置吗 以及你用的是nightly版本还是0.15.0？ 我复制了[Wiki 页](https://github.com/rime/weasel/wiki/%E7%A4%BA%E4%BE%8B#%E7%AB%96%E6%8E%92-%E5%A4%A9%E5%9C%86%E5%9C%B0%E6%96%B9)给的配置，但是出来的候选框样式根本不对，不知道是不是版本的问题。
> 
> Wiki页给的配图是这样的： ![image](https://private-user-images.githubusercontent.com/76689045/309466942-19d8211e-a6b0-4bed-8677-4325f95410d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTUxNDMsIm5iZiI6MTcxMDY5NDg0MywicGF0aCI6Ii83NjY4OTA0NS8zMDk0NjY5NDItMTlkODIxMWUtYTZiMC00YmVkLTg2NzctNDMyNWY5NTQxMGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE3MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYzk5MjkxOWNjZWY5NmQ0ZjYwYmI1ZDAzZmFiMTU5MDlhMTUzYThkYWNlYWUwYTY3MTJlZGNiYzk0MmQ2ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KfBsuLTISctWx1Ka-rUZ2cBmzP2xfOwv8SeFSxDlmqQ)
> 
> 我实际看到的：
> 
> ![image](https://private-user-images.githubusercontent.com/8315221/313491074-92e40302-b10d-480d-87dc-e727c33248cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDcxNzAsIm5iZiI6MTcxMDg0Njg3MCwicGF0aCI6Ii84MzE1MjIxLzMxMzQ5MTA3NC05MmU0MDMwMi1iMTBkLTQ4MGQtODdkYy1lNzI3YzMzMjQ4Y2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMTExNDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njc3ZWQxMjgxODc4YzNmYmI5MDgzMTRiMzUzNzJkYzdiZjAwYmVmMWJhNWRkMzI2ODRkZTJhYWQxYmE2MTkwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nbdTkIgGvV2FBH4RMyBypiAFxc6qcX2LL1ODOkS0S9U)

用nightly版本，然后配置：
  style:
    color_scheme: bus_black
    comment_font_point: 14
    display_tray_icon: true
    font_face: "Microsoft YaHei"
    font_point: 14
    fullscreen: false
    horizontal: false
    inline_preedit: true
    label_font_point: 14
    layout: {border: 0, border_width: 0, candidate_spacing: 10, corner_radius: 9, hilite_padding: 8, hilite_spacing: 5, margin_x: 9, margin_y: 9, round_corner: 0, shadow_offset_x: 1, shadow_offset_y: 1, shadow_radius: 10, spacing: 10}
