### ISSUE TITLE
Future request: 增加候选框背景的透明度

### ISSUE THREAD

**Issue by ctaoist** [rime/weasel#341]
类似 win7 的 aero 那种效果。
不紧急，不重要。

**Comment by vintotal** [comment]
可以的話，會很方便！
用CSS的「opacity」嗎？

**Comment by lotem** [comment]
目前使用的不是基於HTML的界面。
據開發者說，爲保持兼容Windows XP的目標暫時不會換用較新的界面技術。

**Comment by laubonghaudoi** [comment]
如果採用了HTML+CSS的界面，那估計到時候界面可定製化程度會高很多，包括邊框圓角矩形扁平化設計等。

**Comment by 275761919** [comment]
如果采用 html + css 设计，也兼容 xp

**Comment by Guwalgiyakuan** [comment]
期待 如果有win10開始菜單磨砂半透明的效果就更棒了。

**Comment by hosxy** [comment]
如果使用HTML之类的东西，会不会引入性能问题

**Comment by fxliang** [comment]
fixed by 0.15.0 released

**Comment by fxliang** [comment]
fixed by 0.15.0 released
