### ISSUE TITLE
候选框未选字，直接按ctrl+空格切换到英文输入法，小狼毫仍旧占用。

### ISSUE THREAD

**Issue by benojan** [rime/weasel#342]
我用小狼毫打中文，
在输入一些拼音后，出现候选框，但是未选字。想直接换成英文输入法。
所以，我直接按ctrl+空格切换到英文输入法（而不是按shift临时换到英文），
此时，应该是英文输入法，但是小狼毫似乎仍旧占用着上屏的权限？无论打什么都出不来字母……

**Comment by benojan** [comment]
我用的是0.13.0和win10，以前似乎没有这样的情况发生。

**Comment by benojan** [comment]
也就是打字未上屏前，按ctrl+空格来切换输入法，小狼毫仍旧占用输入焦点。

**Comment by gdtv** [comment]
我也是这个问题，习惯了ctrl+空格切换，很难改过来。

**Comment by fxliang** [comment]
最新nightly 构建已可以在Ctrl+Space关闭键盘时清空composition
