### ISSUE TITLE
小狼毫无法切换简体字

### ISSUE THREAD

**Issue by Middle2Second** [rime/weasel#343]
试了很多次了都不行 win10 1809

**Comment by Guwalgiyakuan** [comment]
删除程序-彻底清除用户文件夹内容-再次安装试试
![图片](https://user-images.githubusercontent.com/37359970/54509712-0ed39e00-497d-11e9-9ee2-e87391547a32.png)

**Comment by songjiang951130** [comment]
![image](https://user-images.githubusercontent.com/20123559/57982038-22c97800-7a72-11e9-8a93-16fd84f1d9f5.png)
试试这样配置一下，注意换行哟

```
schema_list:
    - {schema: luna_pinyin_simp}
```
