### ISSUE TITLE
选字窗口变的好奇怪

### ISSUE THREAD

**Issue by dna1982** [rime/weasel#344]
上个月安装配置好输入法，一直使用都是正常的。今天早上开机，就变成这样了。
![image](https://user-images.githubusercontent.com/5440567/54004548-e97ead00-4190-11e9-9a0c-37dee4baa2da.png)

选字窗口外面的Padding没了，我的配置没有任何修改，就变成这样了……

**Comment by dna1982** [comment]
RimeWeasel 版本：0.13
Windows 版本：Win10 1809（LTSC）

**Comment by Guwalgiyakuan** [comment]
皮肤设置没有载入成功？试试换个皮肤看看

**Comment by dna1982** [comment]
> 皮肤设置没有载入成功？试试换个皮肤看看

换了其它颜色方案，都有这个问题。颜色没有异常，只是窗口的Padding没了，所以看起来很小。
而且每个颜色方案里只是色值不一样，没有边距之类的属性，所以感觉不像是颜色方案的问题。

**Comment by fxliang** [comment]
我也出现这样的情况，所以只好加了layout的设定之后似乎正常回来一点。

**Comment by lotem** [comment]
因爲樓主修改了配置文件，未設置padding。
