### ISSUE TITLE
小鹤双拼如何使用自定义符号或短语？

### ISSUE THREAD

**Issue by ghost** [rime/weasel#347]
RT。

**Comment by cililianjie** [comment]
同问！！

**Comment by lotem** [comment]
尚未實現這項配置。

**Comment by xiaocaomei39** [comment]
https://blog.csdn.net/neninee/article/details/83692270

这个不知道是不是你想要实现的效果，而且好像原作者就在楼上？

今天也正好想到这一块了，就找到这个帖子，自己整理了些特殊符号放进去了。

**Comment by Prcuvu** [comment]
Closing since the author has the account deleted.
