### ISSUE TITLE
在Chrome的IE內核插件中访问页面，打开搜索框进行搜索，切換到中文状态，开始输入时会导致搜索框窗口消失。

### ISSUE THREAD

**Issue by alivio-israu** [rime/weasel#350]
1. Chrome浏览器最新版，其中安装扩展程序IE Tab；
2. 地址栏中输入任意网址，本例中为http://www.zdaox.com/，点击IE Tab的图标，切換至IE內核浏览；
3. 在页面打开后，按Ctrl+F打开搜索框，切換至小狼毫中文状态，尝试输入文字；
4. 搜索框消失；

我把问题步骤放在附件中，请各位查看。

PS：我用的是蒼頡檢字法。
[RimeProblem20190321.zip](https://github.com/rime/weasel/files/2990765/RimeProblem20190321.zip)

**Comment by alivio-israu** [comment]
哦，对了，小狼毫的版本号，在0.11.1和0.13.0中都可以重现。

**Comment by alivio-israu** [comment]
@lotem 公子，请您百忙之中看看这个问题。

**Comment by lotem** [comment]
抱歉 我們的團隊資源有限 無法提供對非標準軟件的支持
