### ISSUE TITLE
在 Chrome75 中输入中文标点会自动删除前一个字符

### ISSUE THREAD

**Issue by KhaosChow** [rime/weasel#351]
Windows 版本：WIN10 1809
Chrome 版本：75.0.3748.0
小狼毫版本：0.13.0

在 Chrome 中输入中文标点后会自动删除前一个字符，如图：

![gif.gif](https://i.loli.net/2019/03/27/5c9b4acfa86a7.gif)

在输入中文标点前先按一下空格再输入会变正常，但实际上输入后的文字里是没有空格的。另外语句流标点自动上屏也是正常的。
除此之外，在 Chrome 中还有一些比较怪异但不太影响使用的现象，可能与上面的现象有关。
比如点击地址栏，输入中文标点，会残留 URL 最后一个字符。如图：

![gif1.gif](https://i.loli.net/2019/03/27/5c9b4acfef06d.gif)

我试过重新安装 Chrome 和小狼毫且不添加任何配置文件，依然会出现这个现象。而系统自带输入法是没有问题的。

**Comment by ysc3839** [comment]
听说是 Chrome 的 bug，不过我这里 Chrome 75.0.3745.4 (Official Build) dev (64-bit)，使用微软拼音的情况下没这个问题。试试微软拼音有没有问题？

**Comment by KhaosChow** [comment]
微软拼音没有问题的。 在2019年03月27日 23:16 ，Richard Yu写道： 听说是 Chrome 的 bug，不过我这里 Chrome 75.0.3745.4 (Official Build) dev (64-bit)，使用微软拼音的情况下没这个问题。试试微软拼音有没有问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by KhaosChow** [comment]
Chrome 75.0.3751.0 已无问题。
