### ISSUE TITLE
建议给小狼毫发布 Chocolatey 包

### ISSUE THREAD

**Issue by Hentioe** [rime/weasel#352]
Chocolatey  是一个成熟生态也不错的 Windows 包管理，很多开闭源软件都可以通过 `choco` 安装了。

如果发布到 Chocolatey  仓库，安装将会更加容易，就像这样

``` shell
choco install weasel
````

升级小狼毫

```` shell
choco upgrade weasel
````

希望能考虑

**Comment by sgalal** [comment]
我反对，Chocolatey 是商业软件，有一些功能是收费的。

Windows 上 pacman 已经很好了，不需要再有一个包管理器了。

**Comment by lotem** [comment]
這似前人未完成的工作：
https://github.com/chocolatey/chocolatey-package-requests/issues/324

@Hentioe  若有興趣可以幫忙完成並維護這個軟件包。

**Comment by Hentioe** [comment]
@lotem 很好。我有时间会考虑看看的。倒时候若有障碍会进一步联系你。

**Comment by yzlnew** [comment]
更建议通过 Scoop 发布

**Comment by younger-1** [comment]
scoop install weasel
scoop update weasel
Hopefully coming soon!

**Comment by BrandonKMLee** [comment]
https://chocolatey.org/packages/weasel ?
