### ISSUE TITLE
请问各位大神，如何把rime扩展成支持搜索在线词库啊？可以实时去服务器查询关键词然后返回搜索列表显示成输入法的提示

### ISSUE THREAD

**Issue by changingforyou** [rime/weasel#355]
如题

**Comment by lotem** [comment]
可以編寫一個[翻譯器](https://github.com/rime/librime/blob/master/src/rime/translator.h)。
翻譯器 [代碼示例](https://github.com/rime/librime/tree/master/sample/src)。

**Comment by yu-soong** [comment]
> 可以編寫一個[翻譯器](https://github.com/rime/librime/blob/master/src/rime/translator.h)。
> 翻譯器 [代碼示例](https://github.com/rime/librime/tree/master/sample/src)。

不好意思 ，您可以详细一点吗？
