### ISSUE TITLE
win10任务栏图标跳跃

### ISSUE THREAD

**Issue by zhanngkm** [rime/weasel#357]
使用这个输入法时，点击win10任务栏上的图标「中、英」图标就没了，导致win10任务栏图标无法点击，需要所有应用都切换其他输入法才可以解决。

**Comment by nameoverflow** [comment]
这是 Windows 的问题

**Comment by hyaray** [comment]
本质原因就是中文下会有两个图标，而英文只有一个图标！！
当前输入法和任务栏的输入法不同时，激活任务栏就会切换显示的输入法，然后就跳跃了！！
