### ISSUE TITLE
win10, 开机小狼毫输入法算法服务启动失败,必须手动打开,然后才能输入中文

### ISSUE THREAD

**Issue by CLannadZSY** [rime/weasel#359]

**Comment by feifeiadmim** [comment]
我也是这样的问题，每次开机后都要手动启用算法服务。我看过了。我是有开机启用算法服务的，但是没用，每次都是还有手动开启算法服务。

**Comment by CLannadZSY** [comment]
> 我也是这样的问题，每次开机后都要手动启用算法服务。我看过了。我是有开机启用算法服务的，但是没用，每次都是还有手动开启算法服务。

建议你更新一下win10的系统,我也是从1809更新到1903就没有这个问题了

**Comment by feifeiadmim** [comment]
> > 我也是这样的问题，每次开机后都要手动启用算法服务。我看过了。我是有开机启用算法服务的，但是没用，每次都是还有手动开启算法服务。
> 
> 建议你更新一下win10的系统，我也是从1809更新到1903就没有这个问题了

我就是1903版本的。一直需要手动启用。

**Comment by CLannadZSY** [comment]
> 我就是1903版本的。一直需要手动启用。
这种情况我就不清楚了,相同的系统版本,如果你也把小狼毫重装过很多次还是不行,我也无能为力了

**Comment by lotem** [comment]
無法重現。
可以檢查一下電腦上是否安裝了會干擾應用軟件開機啓動的黑客程序。

**Comment by feifeiadmim** [comment]
我已经换了多个版本的系统，貌似都不行。
我并没有装什么黑客程序。郁闷啊

**Comment by CLannadZSY** [comment]
> 我已经换了多个版本的系统，貌似都不行。
> 我并没有装什么黑客程序。郁闷啊

那可能小狼毫与你无缘,哈哈哈

**Comment by Hywfred** [comment]
我也是这种情况~每次开机都需要重新运行一下Server Deploy等。不知道原因，先升级一下系统试试吧

**Comment by ipcjs** [comment]
一直有着问题😅，我也提了个issue：#499
