### ISSUE TITLE
任务栏图标 在英文输入下 不能区分大小写状态

### ISSUE THREAD

**Issue by yu-soong** [rime/weasel#361]
英文状态下的图标都是大写的`A`，切换成大写还是`A`。可以小写时显示`En`，大写时切换到`A`吗？
![image](https://user-images.githubusercontent.com/43726125/56415511-370d3000-628e-11e9-8021-1c8390089899.png)
系统：windows 64位；version 1809
输入法：小狼毫； version 0.13.0

**Comment by thisistianqi** [comment]
附议，一直显示A容易误以为开启了大写

**Comment by zhanngkm** [comment]
win10的微软拼音也不可以区分大小写，如果电脑没有指示灯提示也是无法知道大小写的，一直也没在意这个。
