### ISSUE TITLE
gVim 英文状态下输入 ')'、']'、'}' 后必然自动切换到中文状态

### ISSUE THREAD

**Issue by Ace-Who** [rime/weasel#362]
Windows 7
Weasel 0.13.0

Vim 无此现象。

有时还有输入法失效，必须切换为其输入法，再切回 Weasel 的情况。还没找到规律，不过已经在连续几个版本中存在了。

**Comment by idnsunset** [comment]
与 #331 类似情况，0.11.0 版本暂没有这种情况。

**Comment by winstarst** [comment]
升级到新版本后暂无此问题

GVIM：8.2 2019 Dec 12 MS-Windows 64-bit GUI version 带 OLE 支持
小狼毫：0.14.3

**Comment by Ace-Who** [comment]
gVim: 8.2.184
Weasel: 0.14.3

问题依旧。

**Comment by Ace-Who** [comment]
采用了 `-u NONE --noplugin` 参数启动后，`) ] }` 不会触发切换。normal 模式下的 `f F t T r R` 命令总是会触发的。

**Comment by lthon-x** [comment]
今天我也遇到这个问题了，定位到应该是 auto-pair 插件造成的，我看你应该也装了这个插件。贴一个网友的[解决办法](https://github.com/mzlogin/config-files/issues/1#issuecomment-255521040)：

> 经排查是 jiangmiao/auto-pairs 插件映射了 <BS> 键造成的，会造成类似回到 Normal Mode 然后又进入 Insert Mode 的情况。

解决方法：

使用插件提供的选项 let g:AutoPairsMapBS = 0 禁用对 <BS> 键的映射，要删除成对括号时使用插件提供的另一个快捷键 <C-h>。

**Comment by Ace-Who** [comment]
我自己写的 `vim-autopair` 插件也和这个问题有关，不过我的插件定义的按键映射是 `<C-R>=...<CR>`，不是从 normal 模式切换到 insert 模式。经手动验证，insert 模式下使用 `<C-R>=` 确实会触发 rime 切换到中文。

**Comment by idnsunset** [comment]
> 我自己写的 `vim-autopair` 插件也和这个问题有关，不过我的插件定义的按键映射是 `<C-R>=...<CR>`，不是从 normal 模式切换到 insert 模式。经手动验证，insert 模式下使用 `<C-R>=` 确实会触发 rime 切换到中文。

确认 `<C-r>=` 会切换到中文。另外，与插件并关系，我没有安装 autopair 之类的插件，一样有问题。这些问题从 0.12 版本就开始存在，我已经退回到 0.11 版本。

**Comment by fxliang** [comment]
fixed by  #1096
