### ISSUE TITLE
[Feature Request] 希望能增加跟随win10系统颜色 

### ISSUE THREAD

**Issue by hosxy** [rime/weasel#365]
小狼毫皮肤颜色代码 能否加一个跟随win10系统颜色，这样输入法颜色总能和系统颜色保持一致

![批注 2019-04-30 152006](https://user-images.githubusercontent.com/17108640/56946089-cacae000-6b5b-11e9-821f-fc00ab79991c.png)

**Comment by fxliang** [comment]
Windows上的配色API变化很多，这个需求暂无计划。
