### ISSUE TITLE
[Question] performance comparison

### ISSUE THREAD

**Issue by jfhsu** [rime/weasel#366]
我自己同时有安装 rime 另一个版本 ： https://bintray.com/lotem/rime/rime-gits/0
发现在输入的反应明显比 小狼毫 0.13 快,
纯粹想了解这是不同框架的原因还是 小狼毫 0.13 还有优化的空间....

**Comment by hosxy** [comment]
这应该是使用Googlepinyin做前端的那个版本吧

**Comment by jfhsu** [comment]
是的...
这个版本打字感觉十分流畅.....
是因为 GoolePinyin 的框架比较特别吗？
会有这个问题纯粹是我在windows 7 下使用，两者打字的流畅明显有差别..

**Comment by lotem** [comment]
有趣的發現
