### ISSUE TITLE
多屏且分辨率不同的情况下，高分屏的候选框太小

### ISSUE THREAD

**Issue by oopp1800** [rime/weasel#367]
# 使用场景

## 显示器设置

主显示器：戴尔 U2417H，1920*1080，24 寸，Windows 缩放 100%
副显示器：XPS 13 自带显示屏，3200*1800，13 寸，Windows 缩放 250%

## 小狼毫设置

字号：16

# 具体描述

直接看图比较清楚，为了模拟显示效果，用开始图标作为参照物——

![image](https://user-images.githubusercontent.com/12545349/57062524-01872e80-6cf3-11e9-9a9a-5bbb7e087944.png)

在正常使用距离下，用副屏的时候打字感觉一直在看视力表最后几排 :joy:

希望能有比较好的解决方案

**Comment by YunofHD** [comment]
我也有这个问题，请问您后来解决了吗？

**Comment by oopp1800** [comment]
还没解决...我都忘记我还提过这个问题了... :joy:

**Comment by YunofHD** [comment]
> 还没解决...我都忘记我还提过这个问题了... 😂

我修改了字体大小，但是在chrome里还是很小。

**Comment by elxy** [comment]
多屏下仍然存在类似的问题，副屏似乎是按照主屏的缩放显示的，如下图所示（将1080p下的截图放大250%以匹配实际大小）：

![小狼毫多显示屏效果.png](https://i.loli.net/2020/03/02/zh2LfFAQUMXRiJG.png)

**Comment by kyle18th** [comment]
难受，1个4K，一个1080P，遇到同样的问题。

**Comment by gldsly** [comment]
同遇到该问题。一通折腾发现是主题的配置问题。
配置文件：weasel.custom.yaml
原本主题配置都在 preset_color_schemes  下面存放所有的配置。包含字体大小等配置。 这时直接修改主题中的配置字体大小。重新部署是无效的，本人解决办法如下：

把字体配置  
    font_point: 16              # 候选文字大小
    label_font_point: 16        # 候选编号大小

直接放到 style 下面，重新部署，就会生效。界面大小也会变正常。当然你也可以继续使用 color_scheme 来指定你自定义在 preset_color_schemes   下面的主题。
我的显示器是 4k 显示器 缩放  150%

**Comment by YunofHD** [comment]
感谢，在下会去尝试！
有新情况会跟进反馈，非常感谢回复！

**Comment by YunofHD** [comment]
> 同遇到该问题。一通折腾发现是主题的配置问题。 配置文件：weasel.custom.yaml 原本主题配置都在 preset_color_schemes 下面存放所有的配置。包含字体大小等配置。 这时直接修改主题中的配置字体大小。重新部署是无效的，本人解决办法如下：
> 
> 把字体配置 font_point: 16 # 候选文字大小 label_font_point: 16 # 候选编号大小
> 
> 直接放到 style 下面，重新部署，就会生效。界面大小也会变正常。当然你也可以继续使用 color_scheme 来指定你自定义在 preset_color_schemes 下面的主题。 我的显示器是 4k 显示器 缩放 150%

尝试了，还是没有效果。
尝试修改WeaselServer.exe的高dpi设置，发现win10的高dpi调整设置对它是不生效的。

**Comment by FeiLZX3Km** [comment]
真的好奇怪我所有的主题文件全没有了……我打开你们说的那个文件，里面全是一团糟的感觉，全都没有分行，也不知道原本是不是就是这样子的。

**Comment by YunofHD** [comment]
又研究了一下
WeaselSever它的DPI Awareness是 Per-Monitor Aware
Per-Monitor Aware: Per-monitor DPI-aware. These applications check for the DPI when they are started, and adjusts the scale factor whenever the DPI value changes. These applications are not automatically scaled by the system.
机翻了一下：每一显示器感知。每台显示器的DPI感知。这些应用程序在启动时检查DPI，并在DPI值改变时调整缩放系数。这些应用程序不会被系统自动缩放。
所以无论怎么应用系统的高DPI设置都是没用的，除非开发者适配。

**Comment by YunofHD** [comment]
最后我采取了折中的办法，把24寸1080P显示器放大到125%，把27寸4K显示器放大到200%，最后高DPI设置行为如下
![image](https://user-images.githubusercontent.com/17290044/154428249-4129d17f-5a18-45e2-8ee2-34bc97880804.png)
显示效果还行，不会再一个很大一个很小了。

**Comment by TaXue-DuBa** [comment]
我也是这种问题，我写过Qt，Qt6虽然说有原生的DPI自动适配，但是鼠标这类还是要根据具体屏幕的缩放情况进行像素乘除，希望开发者能够尽快解决这个问题，双屏缩放比例不同用真的超级难受

**Comment by xsrvmy** [comment]
有任何进展吗？

**Comment by chenlane** [comment]
更改系统兼容性设置即可解决这个问题：
找到WeaselServer.exe，打开属性，在「兼容性」设置中更改「更改高DPI设置」，勾选「替代高DIP缩放行为」，将缩执行切换为
「系统(增强)」。

**Comment by haphap** [comment]
测试了一下，只能解决部分问题，例如word主窗口的缩放无法改变，但替换文字窗口缩放又正常了。感觉整体缩放逻辑很奇怪，希望尽快解决。

**Comment by xjkdev** [comment]
我注意到中英文切换时这个提示窗的大小似乎也变得很大。我更改系统缩放测试过，似乎也是这个原因，不同缩放大小不一样。
![屏幕截图 2023-03-10 182830](https://user-images.githubusercontent.com/4402707/224293015-a10562a2-f141-41fa-8e7e-9f69b58d4b1d.png)

**Comment by fxliang** [comment]
仅支持8.1以上系统，win10目前初测ok(一个1080p调150%)
[这里](https://github.com/fxliang/weasel/actions/runs/4499946727) 

![dpi](https://user-images.githubusercontent.com/4023160/227251986-9614d4bf-7ac8-4b2c-9f0e-f66f5b1bee14.gif)

**Comment by qq823626715** [comment]
有解决吗？win11问题更严重，windows系统界面大的更离谱

**Comment by haphap** [comment]
更新0.15版发自我的 iPhone在 2023年8月30日，上午10:53，LiuShengRong ***@***.***> 写道：﻿
有解决吗？win11问题更严重，windows系统界面大的更离谱

**Comment by xbeta-zhang** [comment]
同关注这个问题，即多个屏幕的分辨率、缩放比例都不同，切换屏幕时输入界面要保持尽量一致。
ps. 冰凌五笔正常；多多五笔v4存在此问题，v5已经解决但未发布正式版。
