### ISSUE TITLE
我Clone了0.9.30版本的源码本地有VS2010和VS2015但是都无法打开项目

### ISSUE THREAD

**Issue by Nephalem-ZH** [rime/weasel#369]
解决方案下面的项目都是不可用状态 (缺少props？)
取得位置https://github.com/rime/weasel/releases
我查看了https://github.com/rime/weasel/blob/master/INSTALL.md
但是对于VS2015打开项目并且编译并没有任何帮助
请问我如何才能正确打开并编译这份源码

**Comment by lotem** [comment]
複製 `*.template` 文件、編輯環境變量、重命名爲 `*`

**Comment by Nephalem-ZH** [comment]
是的我进行了这样的操作但是还有有Error 请问我本地需要配置什么环境嘛 小白不是特别懂

**Comment by lotem** [comment]
按照 https://github.com/rime/weasel/blob/0.9.30/INSTALL.txt 的步驟操作
