### ISSUE TITLE
在word文档里打字的时候会出现候选框闪烁消失的现象

### ISSUE THREAD

**Issue by LoliLoita** [rime/weasel#372]
这个问题不是每次都有，但是出现过几次，打了字候选框就消失不见了按+-可以翻页，但是翻页过后马上闪烁不见。在打字的一瞬间又会出现。

**Comment by jdhao** [comment]
我在 word 里面使用 weasel 的时候也遇到了这个问题，录个一个 gif

![rime](https://user-images.githubusercontent.com/16662357/60159311-75dadb80-9825-11e9-816c-780b1d944b7d.gif)

**Comment by Qeynos** [comment]
有过同样的问题，关闭所有word进程重开后会恢复

**Comment by Sciroccogti** [comment]
Duplicate of #228

**Comment by toiiggww** [comment]
Ref： https://weibo.com/1025911734/Etnd2pdnk

**Comment by llpub** [comment]
win10 1909 + 1.4.3存在同样问题。重启word能暂时解决，但word开一阵子后又复现了。
之前win10 1903 + 小狼毫1.4.2以前的旧版都没有这个问题。
 有人提到的这个方法是没用的#228：
> 关闭word里面的输入法控制就好了！

**Comment by realasking** [comment]
同样问题，win10 1909+1.4.3+word2019。关闭输入法控制现在没用了，以前win10 1903+1.4.2+word2016的时候该方法有用，现在必须重启word，且发生频繁。

**Comment by mqpbjnsdjvbwl** [comment]
我的是office 2021，输入法控制关闭了，但是还是有这种问题

**Comment by determ1ne** [comment]
fixed in 0.15.0
