### ISSUE TITLE
卸载小狼毫输入法后会在键盘设置里产生不可删除的残留选项。

### ISSUE THREAD

**Issue by sde31c** [rime/weasel#373]
小狼毫版本：0.13.0
系统：windows 10  pro 1809 x64

卸载小狼毫后，会在语言键盘设置里产生一个不可删除的键盘选项。无法删除，无法选中。如下图
![1234243535436436345](https://user-images.githubusercontent.com/21274744/57977750-deb68300-7a31-11e9-947c-6e58177461d1.png)

**Comment by sde31c** [comment]
在注册表中把输入法在CTF框架下注册的相关项全部删除后，该键盘选项消失。
注册表中一共两个相关的项：
`计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\CTF\TIP\{A3F4CDED-B1E9-41EE-9CA6-7B4D0DE6CB0A}\LanguageProfile\0x00000804\{3D02CAB6-2B8E-4781-BA20-1C9267529467}`

`计算机\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\CTF\TIP\{A3F4CDED-B1E9-41EE-9CA6-7B4D0DE6CB0A}\LanguageProfile\0x00000804\{3D02CAB6-2B8E-4781-BA20-1C9267529467}`

**Comment by yanhuacuo** [comment]
确实遇着过，感谢 @sde31c

**Comment by hayabusa1997** [comment]
<img width="120" alt="Image" src="https://github.com/user-attachments/assets/87f357df-6b93-46ac-a132-31448aab12be" />
用geek 卸载之后  会出现此图标  有办法解决吗？
