### ISSUE TITLE
使用vscode时，terminal 中输入不显示

### ISSUE THREAD

**Issue by songjiang951130** [rime/weasel#374]
输入的时候光标消失了，一直不显示，
在其他地方输入后跳回vscode又好了，很无奈

--- 更新线 19-5-19 20:26
在终端上进行自定义切换输入法（我设置的是 capslock 作为输入法切换）的时候，中文切换英文会无法输入，中文可以

**Comment by fxliang** [comment]
未复现问题，请更新使用0.16.1~
