### ISSUE TITLE
输入时光标处闪烁厉害

### ISSUE THREAD

**Issue by blue-cosmos** [rime/weasel#376]
在VS Code里光标处似乎有两条竖线和一个小区域一起闪烁，在其它某些编辑器中光标之前有一小片白色区域不断闪烁。不影响功能，但比较影响心情。和这篇文章提到的现象类似：
http://tieba.baidu.com/p/6014234789

平台：Windows 10 1809，weasel 0.13.0

**Comment by fxliang** [comment]
Nightly 构建已修复
