### ISSUE TITLE
windows10浅色模式兼容请求

### ISSUE THREAD

**Issue by RoderickQiu** [rime/weasel#377]
windows 1903新推出的浅色模式下，任务栏图标都是黑色的。
rime就很违和了。
感觉改了这个就可以高高兴兴用浅色模式了。

**Comment by hiking93** [comment]
補個圖
![2019-05-26 19_25_54-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/3449834/58381120-36358f80-7fec-11e9-991d-08a344465620.png)
