### ISSUE TITLE
[new feature request][windows 10][weasel小狼毫]明月拼音-简化字增加自学习候选词方便删除功能

### ISSUE THREAD

**Issue by alexanderhou** [rime/weasel#379]
[new feature request][windows 10][weasel小狼毫]明月拼音-简化字增加自学习候选词方便删除功能

大陆现代流行的简体中文输入法基本都支持的一个小特性，非常的好用。

大概意思是这样的。比如我的环境是windows 10，我安装了小狼毫v0.13，在文本编辑器中（比如windows 自带的写字板），要输入用小狼毫输入一个明月拼音-简体字，默认没有的一个词。比如”海楼石“。
但是呢，第一次我输入的时候，我输入错了，拼音候选字，我选字时候我输入成了”亥楼石“，于是呢，”亥楼石“这个自造词，就被明月拼音记录下来，下次我输入hai lou shi这个拼音代码组合的时候，候选字第一个就是”亥楼石“，但这其实是我手误，不是我需要的，然后我用候选字选择数字键，从新组词组一个”海楼石“，那么，当我再度使用hai lkou shi这个拼音代码组合的时候，候选字前排就会出现2个选项，”亥楼石“和”海楼石“。然后我如果要删除”亥楼石“，这个错误的候选词语，要删掉自学习的这个组词组错用字的词语结果，那么我需要到小狼毫输入法的文件中，找到对应的词库，文件，然后删掉词库中的”亥楼石“这个词条，但是在词库文件中，”亥楼石“这个词，可能石繁体中文显示，并存储的，所以如果简体中文的用户不熟悉这个特点，可能他要找一阵了，搜索不到是因为不是他搜索关键词打错，而是因为存储是以繁体中文存储的。

这种情况其实还算好的。只是修改少数的一两个词。

如果，是那种很常见的发音，2个字那种，然后候选词本身就特别多。然后通过输入法的自学习功能，还组错词，那么在输入同一个发音的候选字的时候，是会带来很多困扰的。

传统大陆的常见拼音输入法，是这么解决的。它不是让用户去修改词库文件，或者词库修改编辑器改词库文件，而且是提供一个更方便的功能，就直接在输入法候选词的界面，当你输入一个拼音组合的时候，2个音，3个音，或者4个音，比如3个音的：海楼石，你输入hai lou shi这个3个音的拼音代码组合的时候，候选词的列表，比如会显示1”海楼石“，2”亥楼石“，3”海楼“，4”海“，5”还“，这个时候，拼音输入法提供几个快捷键组合，然后你按这个快捷键组合，比如alt-shift-1到alt-shift-5，就可以删掉候选词列表中的1，2，3，4，5中的任何一个词，而且是永久性地，从候选词自学习词库中，删除该词，删除后，比如我们这个例子，我选删除2”亥楼石“，那么删除后，
下次我再打hai lou shi这个拼音，候选词结果中，就再也不会出现”亥楼石“这个错误的组字选项了，只有”海楼石“这个正确的选项。虽然亥楼石，和海楼市都是我自造的词，但是我成功地从候选词词库中删掉了我组错的词。而且很方便。
现代简体中文输入法中，出了支持快捷键，有的甚至还支持鼠标右击，打出拼音，在候选词上，直接用鼠标右键右击，就能弹出一个小菜单，其中一个选项就是”从输入法词库中，删除该自学习来的候选词“，所以很方便。
我觉得，如果未来版本的windows 10的小狼毫输入法，能支持这个特性，这个输入法离完美就更近了。
现在小狼毫输入法已经很成功，在大陆的知名知识型社区，zhihu.com（知乎）上，有很多人推荐。随着这个输入法软件的改进，以后支持的估计会更多。

**Comment by sgalal** [comment]
这个就是 <kbd>Ctrl</kbd>+<kbd>Delete</kbd> 叭？

**Comment by Ace-Who** [comment]
我只读了前一半，就是 @sgalal 说的 <kbd>Ctrl</kbd>+<kbd>Delete</kbd>。

更多功能请阅读 [User Guide](https://github.com/rime/home/wiki/UserGuide) 和进阶的[定制指南](https://github.com/rime/home/wiki/CustomizationGuide)。

**Comment by alexanderhou** [comment]
试了一下control-delete组合键，确实可以在使用明月拼音-简体字时候，删除对应拼音的候选词5个候选选项中的自学习自造词，但是只能从第一个删起。。。也就是当时打错了，当时追回，日后一旦变了顺序，还是有不便的地方，而且这个组合键的功能，没明确写在楼上说的user guide页面中。。。好吧。有机会我以后向别人安利这个输入法的时候，我会提到这个组合键功能的。

**Comment by Ace-Who** [comment]
@alexanderhou
User Guide 里有这个，我当时还确认了。
先用方向键选中要删的词。

**Comment by Ace-Who** [comment]
https://github.com/rime/home/wiki/UserGuide#%E5%88%AA%E9%99%A4%E8%AA%A4%E4%B8%8A%E5%B1%8F%E7%9A%84%E9%8C%AF%E8%A9%9E

> 先把選字光標（用上、下鍵）移到要刪除的用戶詞組上，再按下 Shift+Delete 或 Control+Delete（蘋果鍵盤用 Shift+Fn+Delete）。
