### ISSUE TITLE
能否加入南京拼音輸入？

### ISSUE THREAD

**Issue by uliloewi** [rime/weasel#380]
能否開個新repository “rime-langjin”，把 https://github.com/uliloewi/lang2jin1 中的兩個yaml文件放進去，以便江淮官話和西南官話語民直接下載使用？（有的西南官話除了入聲變陽平個，聲母、韻母和南京官話完全一致）

**Comment by lotem** [comment]
可以直接從 https://github.com/uliloewi/lang2jin1 下載。

如果採用配方管理器 /[plum](https://github.com/rime/plum)/ 安裝，則有必要刪除該倉庫的 `default.custom.yaml` ；不覆蓋用家的自定義配置，對使用者比較友好。
