### ISSUE TITLE
小狼毫v14.0版，请问这个图标能调大小吗？

### ISSUE THREAD

**Issue by zgdlime** [rime/weasel#381]
![image](https://user-images.githubusercontent.com/13276912/59395723-e874a180-8db7-11e9-907a-e9eec8cf153c.png)

**Comment by chenrylee** [comment]
Just updated to latest version, and I have same question.

**Comment by jdhao** [comment]
同样的问题，这个输入状态的提示图标确实有点大，Windows 10 1803，使用的缩放级别是 100%。

![image](https://user-images.githubusercontent.com/16662357/59422059-4cbc5300-8e02-11e9-8fa3-fc6629343b2c.png)

**Comment by lotem** [comment]
就這麼大。符合設計。

**Comment by yzlnew** [comment]
我觉得不是大的问题，是和我主题颜色不对应的问题导致出戏。

**Comment by lotem** [comment]
大家可以到這裏討論：
https://github.com/rime/weasel/issues/298

**Comment by cbrjay** [comment]
确实现在变得太大了，一点都不符合Rime的优雅气质
还是说我们这些使用1080p分辨率的已经被抛弃了
