### ISSUE TITLE
0.14.0.135 librime 升级 1.5.0 之后分词出现问题

### ISSUE THREAD

**Issue by xqin** [rime/weasel#383]
分词的优先级好像出问题了.

具体见下图:

## 0.14.0.135
![image](https://user-images.githubusercontent.com/1265888/59407314-6ac68b00-8de3-11e9-9b33-912a3fb4dc89.png)

## 0.13.0.0
![image](https://user-images.githubusercontent.com/1265888/59407266-53879d80-8de3-11e9-843b-138ded764cfc.png)

## 0.9.30.0
![image](https://user-images.githubusercontent.com/1265888/59407281-5da99c00-8de3-11e9-9735-78cd64d80e4c.png)

**Comment by qq420100523** [comment]
同样问题,更新0.14后,分词不正常

**Comment by chowhoyin** [comment]
表示遇到同样的问题

**Comment by lotem** [comment]
這個地方要用新加的語言模型來計算，數據和配置還沒發佈出來。
不幸語言模型缺失時的默認估值跟原先不一樣了，導致常用字組合的權重偏高。
已在插件代碼中修復： https://github.com/lotem/librime-octagram/commit/3664bc9d0426397541e6dcfb7c3c7d6aaad73b2e

**Comment by lotem** [comment]
遇到這個問題的用家，可以
  - 從這裏 https://github.com/rime/librime/releases/tag/1.5.0 拿一份不帶插件的DLL
  - 或者，嘗試裝配語言模型： https://github.com/lotem/rime-octagram-data
