### ISSUE TITLE
[功能建议]统计输入文字

### ISSUE THREAD

**Issue by ferren-qf** [rime/weasel#384]

**Comment by ferren-qf** [comment]
只会java，看样子自己要学习一下c++，实现一下这个功能

ps：现在这些内容都是用新输入法输入的，感觉还是很不错，非常好用~

**Comment by sgalal** [comment]
「小狼毫輸入法」 -> 「【小狼毫】用戶詞典管理」 -> 「導出文本碼表」

![Word Cloud Example](https://user-images.githubusercontent.com/32255369/59558382-77392680-9023-11e9-8a4c-e7be54772deb.png)
