### ISSUE TITLE
不要欺负我们这些只会五笔的老年人了嘛

### ISSUE THREAD

**Issue by toiiggww** [rime/weasel#387]
如题，Ref: #297 #375

**Comment by lotem** [comment]
沒有這回事。

所有發佈過的[輸入方案](https://rime.im/download/#%E5%AE%89%E8%A3%9D%E6%9B%B4%E5%A4%9A%E8%BC%B8%E5%85%A5%E6%96%B9%E6%A1%88)都是開源的，可以自由使用。

至於說不打包方案到輸入法安裝包，已經充分討論過。總結起來就是：
本品發佈的主體是可配置的輸入法程序。
隨着軟件生態的發展，無法在輸入法安裝包內囊括所有的輸入方案。
目前打包的方案是使用中文的各主要地區基礎教育教授的漢字編碼方法，如拼音、注音、倉頡、筆畫等。
小衆的輸入法太多了。從政治正確的角度，只爲一部分少數人提供方便，才會有欺負人的嫌疑。舉個例子，任意一種方言的使用者，可能比會用一種小衆形碼的人都要多。甚至筆者的母語中原官話（有[輸入方案](http://github.com/lotem/rime-zhung)），能言者億衆，從未有機會隨輸入法發佈，是不是也感受到深深的不公呢。
我們有切實可行的計劃，最終要解決輸入方案分發的問題。
目前，輸入方案的發佈方式暫時要靠使用者自發完善。假設一種輸入法流行度高有大量用家，其中必不乏高手彙總資源甚至是做二次開發，方便使用者社羣。五筆如果不夠方便，可能確實比較小衆。

**Comment by Ace-Who** [comment]
好好说话。

**Comment by toiiggww** [comment]
现在使用五笔的人仍有很多，并不是到「小众」的程度。当然，从历史过程来看，这部分人确实不再年轻。

**Comment by nameoverflow** [comment]
和大众小众没有关系，自带方案只是作功能示例用途。

**Comment by lotem** [comment]
不懂究竟怎么受欺负了

**Comment by yanhuacuo** [comment]
汇总资源，二次打包，98五笔就做得很到位的：

主页：

http://www.98wubi.com/

简介：

https://98wb.github.io/input%20method/2019/05/22/007.98wb.html

https://98wb.github.io/input%20method/2019/05/22/008.trime.html

**Comment by GoGoogle** [comment]
这个问题有好几个人提过了
但打包的里面就没有五笔，即便解释了那么多，我也不明白这是什么原因，好歹预置一个五笔，那么多拼音，却没有一个五笔。

**Comment by Prcuvu** [comment]
> 那么多拼音，却没有一个五笔。

看来有用户被预设方案功能的完整迷惑了。也许只有仅预装 minimal 方案集，让预装的拼音也显得难用，才会令其他方案的用户感到比较“不受欺负”吧。

> 我只知道

现在让你多知道一些。

> 现在使用五笔的人仍有很多，并不是到「小众」的程度。

> 预装包里面半个五笔都没有，这不是”欺负“是什么？

预设方案集的收录标准是满足两岸三地用户可以打字的最低要求，使用人数是次要因素。

* 中国大陆：朙月拼音、地球拼音、五笔画。义务教育要求学习拼音和写字，可以假设任何受过义务教育的用户都可以在不需要额外记忆输入编码的条件下上手使用其中一种。
* 港澳：仓颉、五笔画。出于历史原因，这两个地区的用户没有受过任何拼音方案教育，应假设无法使用任何音码，故收录使用人数最多的仓颉（速成的来源）。
* 台湾：注音、地球拼音、五笔画。地球拼音作为带声调的拼音方案，是注音的依赖项。通过棱镜可将注音输入变换为对应的拼音。

很遗憾，五笔作为中国大陆拼音教育普及不足、拼音输入法不能满足生产需求时流行的替代方案，不满足收录标准。哪怕放到对应的历史时期，我们也会收录当时更难使用的拼音方案而不是五笔。

**Comment by toiiggww** [comment]
不用强制解释一波了，看不起你们。（还一句句的驳，什么态度）

**Comment by Ace-Who** [comment]
我用过的小鹤双拼、宫保拼音（lotem 本人的作品）、郑码、徐码，现在都没有预置，也没觉得受欺负了。自我中心主义要不得。

**Comment by Prcuvu** [comment]
> 不用强制解释一波了，看不起你们。（还一句句的驳，什么态度）

毕竟道理还是要讲清楚嘛。

![openit](https://user-images.githubusercontent.com/7923857/76582621-c60fe000-6511-11ea-9286-bb8456f3000a.png)

对于以这样的方式发言的用户，自认为礼数还是相当周到的。

**Comment by zhaozg** [comment]
建议把此问题的评论功能锁掉

**Comment by Prcuvu** [comment]
> 建议把此问题的评论功能锁掉

我能理解你的好意，但是我认为这种程度的负面情绪宜疏不宜堵。如果火药味最终升级，我会考虑封锁讨论。
