### ISSUE TITLE
每次更新，都要重新改很麻煩，希望設計不用解除舊版亦可搬舊設定至新版

### ISSUE THREAD

**Issue by LL-LLS** [rime/weasel#388]
更新頻率不高還好，但像這樣一星期更新三次，我每次都要改上30分鐘才能用……
而且改程式資料夾中的data是沒用的，每次都要去%appdata%\Roaming\Rime\build逐行改xx.schema.yaml以及default.yaml
能設計下不用解舊版本升級的方法？把舊設定都不用麻煩的搬到新版本上

每次都解除>重啟>重裝>逐行設定>還要再重啟才順利部署設定=花上30分鐘
這麼麻煩我都打算以後都不升級停留在某一版本算

**Comment by lotem** [comment]
有这样的设计。您的用法不符合设计。
https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97

**Comment by Ace-Who** [comment]
这 30 分钟用来读说明书吧。

**Comment by jdhao** [comment]
不读说明就使用的后果。。。
