### ISSUE TITLE
求助：gvim中的输入问题

### ISSUE THREAD

**Issue by superhxl** [rime/weasel#389]
win10操作系统，gvim8.1，偶尔会输入中文。通过shift切换为英文输入后，如果backspace或这回车，则又会切换为中文。请问是rime或gvim本身的兼容问题，还是我设置有误。有没有人遇到过？

**Comment by Ace-Who** [comment]
不是个例。除了退格和回车，还有一些符号也会触发，https://github.com/rime/weasel/issues/362。

**Comment by superhxl** [comment]
果然，1.1可以用。换回了版本1.1。

**Comment by gitQqqHs** [comment]
使用最新版本

**Comment by superhxl** [comment]
最新版问题依然存在啊，难道是我的gvim有问题，或者我的rime配置问题。

**Comment by winstarst** [comment]
存在同样的问题，环境如下：

- 机器：小新Pro 13 2019
- 系统：win 10 家庭中文版，1909
- GVIM：8.2  2019 Dec 12 MS-Windows 64-bit GUI version 带 OLE 支持
- 小狼毫：0.14.3

set ininsert 保持默认 0，未手动设置。

现象如下：
- 在 insert 模式下输入英文时，只要 backspace 或 enter 就会变成中文；
- 在 nomal 模式下输入字母 R 进行替换时，会默认为中文，需要 Shift 切换为英文；

基本上就是下面的情况：
- https://github.com/rime/weasel/issues/331 
- https://github.com/rime/weasel/issues/362

困扰很久了，一旦遇到中英文混合输入的情况，只能切换到微软五笔了。

如果有兄弟解决了，请指点一下。

**Comment by fxliang** [comment]
fixed by #1096
