### ISSUE TITLE
[GIT] Unable to arrange the candicate list horizontally

### ISSUE THREAD

**Issue by be5invis** [rime/weasel#39]

**Comment by Prcuvu** [comment]
You should post your issues in [rime-gits repository] (https://github.com/lotem/rime-gits) provided the [GIT] tag stands for Google Input Tools,

**Comment by be5invis** [comment]
@Prcuvu There's no issue tracker on `rime-gits`.

**Comment by Prcuvu** [comment]
You can move to [this page](https://github.com/rime/home/issues), as indicated in bintray page.
