### ISSUE TITLE
进入系统后，打开第一个程序，无法实现日文键盘布局

### ISSUE THREAD

**Issue by dayudaoren** [rime/weasel#390]
系统：win7-x64；
小狼毫： 0.14.2；
键盘布局：日文；
bug：采用日文键盘布局后，当进入系统后，打开第一个程序时，小狼毫无法应用日文键盘布局，而采用了美式键盘。当关闭第一个打开的程序后，再打开程序就没问题了。每次进入系统都会复现此bug。

**Comment by fxliang** [comment]
这个应该是因为小狼毫并没有注册日文键盘布局所以无法使用吧
