### ISSUE TITLE
plum下的语言模型数据包需要手动放到data中

### ISSUE THREAD

**Issue by yanhuacuo** [rime/weasel#391]
当自助编译时，各部分组件都编译正常，但是：
实测最新版的 weasel 打包流程不会将 plum 下的语言模型自动添加到 output 下的 data 下。
是不是可以改进，或者我的操作有什么问题？
另外，build all 时，weasel/include 或 librime/include，不会向 dist 下拿取编译出的

- rime_api.h  
- rime_levers_api.h

这个部分，目前只好手动补齐。

**Comment by lotem** [comment]
沒發現這些問題。
「最新版」是哪個版本？
你可以在 https://ci.appveyor.com/project/rime/weasel/history 找對應版本對照看看 CI 上面的日誌。

**Comment by yanhuacuo** [comment]
> 沒發現這些問題。
> 「最新版」是哪個版本？
> 你可以在 https://ci.appveyor.com/project/rime/weasel/history 找對應版本對照看看 CI 上面的日誌。

现在清楚了，原来我并没有表述错误，确实是 weasel 的本地构建脚本有问题：

原来[appveyor.install.bat](https://github.com/rime/weasel/blob/master/appveyor.install.bat) 的行为，与[build.bat](https://github.com/rime/weasel/blob/master/build.bat) 的行为不同：

比如 CI 的日志中：

``````
.\build.bat data hant installer
``````

即是完成了去「plum/lotem」下拿语言模型的动作：

``````
Downloading package: lotem/rime-octagram-data 
Cloning into 'plum/package/lotem/octagram-data'...
Installing: grammar.yaml
Updated ~ 1 files from 1 packages in 'output/data'
Updating package: lotem/rime-octagram-data
From https://github.com/lotem/rime-octagram-data
 * [new branch]      hans       -> origin/hans
 * [new branch]      hant       -> origin/hant
Branch 'hant' set up to track remote branch 'hant' from 'origin'.
Switched to a new branch 'hant'
Installing: zh-hant-t-essay-bgc.gram
Installing: zh-hant-t-essay-bgw.gram
Updated ~ 2 files from 1 packages in 'output/data'
``````
但是weasel/build.bat并不会。

另外，比如[「CI脚本」](https://github.com/rime/weasel/blob/master/appveyor.install.bat)中有如下：

``````
copy /Y librime\dist\include\rime_*.h include\
``````
但是「weasel/build.bat」下就是没有的。

weasel/build.bat 下添加下面两句，才可以编译通过：

``````
if %build_rime% == 1 (
  cd %WEASEL_ROOT%\librime
  if not exist librime\thirdparty\lib\opencc.lib (
    call build.bat thirdparty
  )
  call build.bat
  cd %WEASEL_ROOT%
  rem copy /Y librime\thirdparty\lib\*.lib lib\
  copy /Y librime\build\include\rime_*.h include\
  + copy /Y librime\dist\include librime\
  + copy /Y librime\dist\include\* .\include\
  copy /Y librime\build\lib\Release\rime.dll output\
)

``````

至于「plum/package/lotem/octagram-data」的数据，好像需要在「weasel.bat」下添加同类令命，才可以使用「build_all」。

**Comment by yanhuacuo** [comment]
CI的构建脚本中，有这么一句：

[copy /Y librime\dist\lib\rime.dll output\](https://github.com/rime/weasel/blob/05e5938364747d9d9b766a354adb399739696d29/appveyor.install.bat#L15)

dist 下的 rime.dll 是从 「librime\build\lib\Release\rime.dll」下拷过来的，
如果 librime 编译失败，dist 目录下面，旧版本的 rime.dll 并不会被覆盖掉，它依然是存在的。
因此，CI 脚本可以在 rime.dll 并没有实际生成的情形下，完成封包工作。
这与「weasel/build.bat」下的动作是不同的：

[copy /Y librime\build\lib\Release\rime.dll output\](https://github.com/rime/weasel/blob/05e5938364747d9d9b766a354adb399739696d29/build.bat#L99)

weasel/build.bat 下，关于 rime.dll 的动作才是合理的。

有人反馈说 rime官网 释出的 1.5.2 里的 rime.dll 实际上是 1.5.1 ，可能与此有关。

**Comment by lotem** [comment]
那兩個腳本流程不一樣。CI 腳本不編譯 librime。
`build.bat` 的確沒及時更新，一直在等 submodule librime 升級時一起改，最後竟忘記了。

CI每次構建都是全新的虛擬機環境，只有boost等第三方庫會讀取cache，因此不需要擔心有文件殘留；
而且，編譯失敗則整個構建任務失敗，不會繼續執行發佈的步驟。

plum 腳本我測了一下沒有問題。

語言模型文件本品是不包含的。有單獨的安裝包 https://bintray.com/rime/weasel/data#files

**Comment by yanhuacuo** [comment]
https://github.com/rime/weasel/commit/d1ac7b420162b7719303d050067a6e0a4cc4225b

修复了「weasel/include」下 

- rime_levers_api.h
- rime_api.h

文件缺失的问题，但实际上，WeaselServer.vcxproj 还涉及到对 「librime/include」的调用，比如代码中就有调用声明：

https://github.com/rime/weasel/blob/0c9dcddff4aa5251b7f7c7ff29da7098293b4405/WeaselServer/WeaselServer.vcxproj#L153

但是在「build_librime」时，librime 并不会自动生成 include 文件夹。

群里有人反馈公子的修复并没有能使 build_all 的整个流程生效，添加复制 dist下的 include 文件夹，到librime的根目录后，报复消除了。

公子再看一下？

```
 + copy /Y librime\dist\include librime\
```

**Comment by lotem** [comment]
不管
