### ISSUE TITLE
桌面輸入時不出現候選欄、ctrl+grave也不出現菜單，但是能打字

### ISSUE THREAD

**Issue by nicewise** [rime/weasel#393]
桌面輸入時不出現候選欄、ctrl+grave也不出現菜單，但是能打字，只是看不見。。。
小狼毫版本：0.14.3
系統：Windows10 版本：17134.829

**Comment by alivio-israu** [comment]
这个问题和我以前提的那个问题#350是一样的。
实话说，这种情況出现的还是挺多的，比如在Chrome中进行打印页面操作，另存为PDF，点击保存，在输入的时候也是能打字，但看不到候选框。
![image](https://user-images.githubusercontent.com/17839839/60645585-a2b57100-9e6b-11e9-81c0-cbb8910f881b.png)
那个保存页面和小狼毫的候选框无法同时存在。

**Comment by archerc** [comment]
我也遇到类似的问题，但是只在Word里是这样，打字的时候候选框一闪而过，隐藏在后面，按键能出字上屏，但是看不到候选框。而且只在word里是这样，其它程序里正常。不记得是什么时候出现的状况，以前好像不是这样

**Comment by fxliang** [comment]
久远问题，应该已经解决了，如未解决可再打开此issue
