### ISSUE TITLE
改变小狼毫布局~就是输入法整个的方框变成圆的要怎么改样式文件~大概效果如图

### ISSUE THREAD

**Issue by ASHENXZH** [rime/weasel#394]
![image](https://user-images.githubusercontent.com/23288916/60311340-4f35b580-9989-11e9-9322-3f8f6655da77.png)

**Comment by lotem** [comment]
这个需要编程实现。
现在的界面不支持这样的布局样式。

**Comment by Prcuvu** [comment]
Windows API 没有直接提供圆角窗口的功能（macOS 则有提供），而目前基于 GDI 的绘制方式并不支持适应 DPI 缩放的弧形窗口裁剪。

**Comment by CROXIE** [comment]
> 这个需要编程实现。
> 现在的界面不支持这样的布局样式。

那能请问下你在V2EX发的那个代码是在macOS才能用的吗，在windows不能用是吗？
