### ISSUE TITLE
windows xp安装weasel-0.14.3.0-installer报错

### ISSUE THREAD

**Issue by gy0715** [rime/weasel#396]
软件版本：0.14.3.0
Windows XP SP3下安装报错如下：
![002](https://user-images.githubusercontent.com/23148767/60383934-af704880-9aaa-11e9-93a9-015f5dc3a293.png)
重新安装报错如下：
![001](https://user-images.githubusercontent.com/23148767/60383944-c9119000-9aaa-11e9-93a8-1984a78bcd78.png)

软件版本：0.13.0
Windows XP系统的电脑安装报错如下：
![003](https://user-images.githubusercontent.com/23148767/60383956-ef373000-9aaa-11e9-8b22-0d15a34f0bd0.png)

软件版本：0.12.0
Windows XP系统的电脑安装正常

**Comment by lotem** [comment]
討論決定不再更新支持XP的版本。

更新了下載頁 https://rime.im/download
