### ISSUE TITLE
在atom里按完退格后无法输入/ can not type after pressing backspace in atom

### ISSUE THREAD

**Issue by nyaachen** [rime/weasel#398]
在atom中输入的话，按下退格删除完字符后如果直接输入有概率无法打出字来。
这个issue也被提交到了atom那边。

After pressing backspace in atom, if you directly input there is high possibility that you can not type chinese character.
this issue is also listed [here](https://github.com/atom/atom/issues/19619) on atom.

**Comment by fxliang** [comment]
atom g了
