### ISSUE TITLE
word 2013里，退格任意字符后大概率无法立刻输入

### ISSUE THREAD

**Issue by 1316695312** [rime/weasel#400]
视频请见：
https://pan.baidu.com/s/18npNql3pxel5Cn9uzaDwqQ
提取码：
rii7

**Comment by ted423** [comment]
唔，我这试了下没有再现，一直用的office 2013 ,win 10 1903 64位

**Comment by ted423** [comment]
0.14.3 的软件版本

**Comment by 1316695312** [comment]
> 唔，我这试了下没有再现，一直用的office 2013 ,win 10 1903 64位

是别的什么bug也说不定。

**Comment by sezhai** [comment]
有这个问题。设置为直接上屏的符号，在Word2016中一开始输入需要按两下才能上屏，后面连续输入就正常 了。如果删除一部分内容再输入，又会需要按两下才有反应

**Comment by sih4sing5hong5** [comment]
This was fixed by #537 .
