### ISSUE TITLE
部分程序放在那一段时间后小狼毫会无法使用

### ISSUE THREAD

**Issue by ted423** [rime/weasel#403]
win 10 x64 1903
小狼毫0.14.3
比方说excel，放在那不管，右下角语言栏会变成X，必须把进程关掉重打开才能继续使用(由于excel是1个进程多个表格，必须把所有表格都关了)这个时候其他已经开在那的程序都会有同样现象，必须关掉重开，不知道是不是进程崩溃之类的问题导致的。
![image](https://user-images.githubusercontent.com/7042766/61168101-eea69b00-a57a-11e9-82fa-10b23d07065b.png)
类似这样

Win10自身的输入法会比较稳定，但在机子被rdp连接有时会出现类似现象(我有好几台电脑，都是同样系统)

但小狼毫是无论连和被连的电脑都有同样现象

**Comment by determ1ne** [comment]
Closed as stale, reopen it if the problem still exists.
