### ISSUE TITLE
简体 字 切换大写时无法删除修改的问题

### ISSUE THREAD

**Issue by yyt6801** [rime/weasel#404]
在 默认简体时切换大写后 输入的 字母无法修改删除，只能切换成英文后再删除

**Comment by Ace-Who** [comment]
没遇到过。什么方案？

**Comment by yyt6801** [comment]
明月拼音`简体字luna_pinyin_simp
就改动了如下配置
patch:
  "ascii_composer/switch_key":
    Shift_L: commit_code
    Shift_R: commit_code
  "menu/page_size": 9
  schema_list:
    - {schema: luna_pinyin}
    - {schema: luna_pinyin_simp}

patch:
  "style/color_scheme": google
  "style/display_tray_icon": false
  "style/font_point": 13
  "style/horizontal": true

**Comment by yyt6801** [comment]
#405 的问题和这个汇总到一起， 用明月拼音`简体字方案时，就输入一个字母还为选中时再删除它时会在当前输入位置后输入一个空格，如图1为 输入一个字母时，图 2为删除那个字母后光标处会自动添加一个空格
![image](https://user-images.githubusercontent.com/18433720/61281826-dfc71f00-a7ec-11e9-92b9-731fde0b31f1.png)
 
删除字母后是这样
![image](https://user-images.githubusercontent.com/18433720/61281928-0be2a000-a7ed-11e9-8207-be2325f303b6.png)

**Comment by MetalGearBronya** [comment]
> 
> 
> #405 的问题和这个汇总到一起， 用明月拼音`简体字方案，只输入一个字母还未选中词时 删除它后会在当前输入位置后自动出现一个空格，如图1为 输入一个字母时，图 2为删除那个字母后光标处会自动添加一个空格
> 
> ![image](https://user-images.githubusercontent.com/18433720/61281826-dfc71f00-a7ec-11e9-92b9-731fde0b31f1.png)
> 
> 删除字母后是这样
> 
> ![image](https://user-images.githubusercontent.com/18433720/61281928-0be2a000-a7ed-11e9-8207-be2325f303b6.png)

这个问题我无法复现，使用「朙月拼音」内「漢字→汉字」选项 或「朙月拼音·簡化字」均无此问题

**Comment by MetalGearBronya** [comment]
> 
> 
> 明月拼音`简体字luna_pinyin_simp
> 就改动了如下配置
> patch:
> "ascii_composer/switch_key":
> Shift_L: commit_code
> Shift_R: commit_code
> "menu/page_size": 9
> schema_list:
> - {schema: luna_pinyin}
> - {schema: luna_pinyin_simp}
> 
> patch:
> "style/color_scheme": google
> "style/display_tray_icon": false
> "style/font_point": 13
> "style/horizontal": true

尝试在配置文件中搜索`Caps_Lock: `（大小写敏感），若后面为noop，改为clear或commit code即可解决此问题。

以下为测试过程：

这个问题实际应该是
设置为
```
ascii_composer:
  good_old_caps_lock: true # false情况一致
  switch_key:
    Caps_Lock: noop
```
时，在中文模式下，进入大写锁定状态并输入一个英文字母后，控制按键对小狼毫行为异常，典型如退格完全失效；回车不commit_code而是清除输入框；若在切换到大写锁定后先回车，再输入字母，控制键有效但光标在文档内而非候选栏上方的输入框内，怀疑是处理退格和回车等基础控制按键时将Capslock锁定视为了一个状态，因而 Caps on + 按键 不同于 Caps off + 按键，虽然实际上行为应当一致。default.yaml中其他switch key的效果正常触发（即被直接接管识别的控制键工作正常）佐证了这个猜想。
这个问题在Capslock不为noop时不会出现，也即用户未作修改时不会有此问题，故优先级不高。默认行为符合期待，即重新安装可以保证修复此问题。

目前看来修复此bug需要调整输入法对键盘状态的响应，较为复杂，推荐用户将switch key中capslock的行为还原为Caps_Lock: commit_code或Caps_Lock: clear，此时可用capslock快速输入英文标点，还可避免全大写字母进入输入框后再按Enter上屏这样的额外操作。

问题来源可能是导入了其他人做的非以patch形式修改的配置文件或按教程直接在配置文件中间修改了此栏，所以noop没有表现在patch部分。

以上。

**Comment by fxliang** [comment]
看上去像是解决了，暂关闭此issue
