### ISSUE TITLE
win7 x64 ， weasel-0.14.3.0 ，在Notepad++中，有概率要导致 nptepad++

### ISSUE THREAD

**Issue by headstrong2** [rime/weasel#406]
不清楚是不是notepad++自己 不够健壮

1 打开notepad++
2 正常输入汉字，用鼠标点候选 字

3 问题出现：notepad++自己崩了。

**Comment by nicknameNothing** [comment]
虽然我输入中文时没有使用鼠标点选，但是我刚刚在我windows 10 1903版本中尝试在typora、firefox、webstorm、microsoft edge、microsoft word中输入汉字然后鼠标点选候选，输入法的候选框都自动消失了且候选字没有选中和输入，没有出现应用崩溃的情况。

**Comment by llpub** [comment]
在以前的某个微信桌面版中也是这种情况。
华硕小狼毫的鼠标选词我怎么没成功过

**Comment by ted423** [comment]
> 虽然我输入中文时没有使用鼠标点选，但是我刚刚在我windows 10 1903版本中尝试在typora、firefox、webstorm、microsoft edge、microsoft word中输入汉字然后鼠标点选候选，输入法的候选框都自动消失了且候选字没有选中和输入，没有出现应用崩溃的情况。

我这是同样现象，并且之后没法输中文了

**Comment by mgdreamingstar** [comment]
notepad++ 打开后 weasel 就显示已禁用
其他软件还没有发现这样的情况
系统是 win 10

**Comment by qbycs** [comment]
网易云笔记下使用weasel最新版会导致网易云笔记闪退

**Comment by gitQqqHs** [comment]
有道词典也是哦！输入也存在问题。输入框没有文字时，难以输入，好像是没有获取到输入焦点。应用崩溃倒是没有见到过

**Comment by Prcuvu** [comment]
出于特殊原因，不再为与Notepad++相关的问题提供支持。

**Comment by oishi81** [comment]
> notepad++ 打开后 weasel 就显示已禁用
> 其他软件还没有发现这样的情况
> 系统是 win 10

这个问题是不是一直存在？最近刚用小狼毫，win10，有道云笔记输入时，经常卡顿，偶尔有道云笔记会崩溃退出。
