### ISSUE TITLE
如何关闭拼音分词空白?

### ISSUE THREAD

**Issue by ouweiya** [rime/weasel#408]
![Snipaste_2019-07-30_20-50-25](https://user-images.githubusercontent.com/28357731/62130547-dae58d80-b30b-11e9-9ff2-2bd4eed39e77.png)

**Comment by redchenjs** [comment]
想用其他字符来区分每个字的拼音？

**Comment by ouweiya** [comment]
不, 就是不要有空白, 就像一串引文一样, 强迫症看着难以适应, 拜托告知方法.

**Comment by redchenjs** [comment]
修改`luna_pinyin.schema.yaml`，在`translator:` 的`preedit_format:`下添加一條`- xform/\s//`，重新部署後生效，不知道是不是你要的樣子。
![Deepin 截圖_select-area_20190730225652](https://user-images.githubusercontent.com/9910809/62140626-e772e180-b31d-11e9-98f6-1c707769d31a.png)
![Deepin 截圖_select-area_20190730225701](https://user-images.githubusercontent.com/9910809/62140633-eb066880-b31d-11e9-911b-df7035831827.png)

**Comment by ouweiya** [comment]
不知道为什么不起作用
![c](https://user-images.githubusercontent.com/28357731/62141948-05414600-b320-11e9-94c2-9d610eeae142.gif)

配置

![Snipaste_2019-07-30_23-14-53](https://user-images.githubusercontent.com/28357731/62141988-1be79d00-b320-11e9-8d81-4eeb791888eb.png)

**Comment by redchenjs** [comment]
trash中的配置是无效的，把它移动到rime文件夹下，并且确保`default.custom.yaml`中启用了`luna_pinyin`，并重新部署。
![Deepin 截圖_select-area_20190730233450](https://user-images.githubusercontent.com/9910809/62143720-20fa1b80-b323-11e9-8500-173e2affcb04.png)

**Comment by ouweiya** [comment]
始终还是失败了, 我不知道哪里出错了, 目前忙于开发React Native就放弃研究了. 
要是能有个GUI控制面板就好了. 这样就能增强产品易用性, 令人不那么沮丧,.
我有开发Electron混合运用的经验, 可以使用GUI控制面板来动态修改配置文件, 自动运行部署, 将产生的变化反映到GUI上, 这样就能大大增强用户信心, 也可以尝试使用web来提供渲染, 使用css ,svg, 可以
作出各种魔幻的效果, 
打个字符图标, 还是黑白了
![11](https://user-images.githubusercontent.com/28357731/62178234-e02df100-b37a-11e9-80cd-3e6bc9f1c2d3.png)

在未来,我可能尝试做这件事

**Comment by sgalal** [comment]
It's wield that you are able to develop React Native but failed to configure a simple YAML...

**Comment by ouweiya** [comment]
> It's wield that you are able to develop React Native but failed to configure a simple YAML...

很有可能是我有什么地方文件弄错了, 有空远程协助下?

**Comment by lotem** [comment]
@ouweiya 
四樓給出的代碼是 `- xform/\s//`，您寫成了 `- "xform/\s//"`

**Comment by redchenjs** [comment]
@ouweiya 我將修改好的配置打包傳上來了，你可以拿去測試。
[rime.zip](https://github.com/rime/weasel/files/3449753/rime.zip)

**Comment by ouweiya** [comment]
> @ouweiya 我將修改好的配置打包傳上來了，你可以拿去測試。
> [rime.zip](https://github.com/rime/weasel/files/3449753/rime.zip)

我總算知道爲什麼你們給的設置，我不能生效了，因爲我用的簡體，你們給的默認繁體。
請告知簡體對應什麼字段？
![t](https://user-images.githubusercontent.com/28357731/62184853-7883a000-b392-11e9-9aa1-e1789ec9dd95.png)

但是有个BUG一直都存在， 就是在切换中英文状态时会发生以下问题。
![c](https://user-images.githubusercontent.com/28357731/62184511-0b233f80-b391-11e9-8cf0-b4e4ef7b19ce.gif)

其他窗口也有这个问题，总是会有一个下划线
![c2](https://user-images.githubusercontent.com/28357731/62184612-68b78c00-b391-11e9-9097-4c25dc404364.gif)

**Comment by redchenjs** [comment]
按F4出来的菜单中能直接切换简繁

**Comment by ouweiya** [comment]
但是设置对应的是翻译字， 目前这个设置只能在翻译下生效啊

```yaml
translator:
  dictionary: luna_pinyin
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/
    - xform/\s//
```

**Comment by ouweiya** [comment]
简体字典叫什么？

**Comment by redchenjs** [comment]
方案：
https://raw.githubusercontent.com/rime/rime-luna-pinyin/master/luna_pinyin_simp.schema.yaml
字典：
https://raw.githubusercontent.com/rime/rime-essay-simp/master/essay-zh-hans.txt

**Comment by ouweiya** [comment]
![Snipaste_2019-07-31_13-15-32](https://user-images.githubusercontent.com/28357731/62185505-58a1ab80-b395-11e9-9403-20d82e1740f5.png)
![Snipaste_2019-07-31_13-15-55](https://user-images.githubusercontent.com/28357731/62185509-593a4200-b395-11e9-9cee-279cf1e272a3.png)

**Comment by ouweiya** [comment]
之前搜到了 dictionary: luna_pinyin_simp， 设置了也没有用。 难道只有我电脑有这个问题？

**Comment by ouweiya** [comment]
这么简单的需求， 其实不分空白更好， 有点烦躁

**Comment by ouweiya** [comment]
总算行了， 创建一个 `una_pinyin_simp.schema.yaml` 文件，把配置复制过去就行了。

**Comment by ouweiya** [comment]
强烈建议造个GUI面板

**Comment by ouweiya** [comment]
下划线BUG的问题可以解决吗？

![c](https://user-images.githubusercontent.com/28357731/62185872-a36ff300-b396-11e9-9d5a-66af36d9da52.gif)

**Comment by redchenjs** [comment]
无法复现

**Comment by ouweiya** [comment]
我刚刚想起来我当初弃用微软输入法,就是因为这个原因,  但是现在测试一下微软, 问题解决了, 感觉又回到了原点.
