### ISSUE TITLE
Windows10 1809:SystemSettingsBroker错误

### ISSUE THREAD

**Issue by zhaoyewei** [rime/weasel#409]
如题，我感觉是rime的问题导致的，因为每次出现这个问题后rime都会打不开。查看日志卧病不能确定是什么原因，因为找不到。有没有遇到过类似的问题的？这个问题影响关机，好几次明明关机了却被这个错误挡着电脑开了一夜，很烦

**Comment by ted423** [comment]
方便截个图么？
没弄懂这个问题的类型

**Comment by zhaoyewei** [comment]
后来，更新了之后没有这个问题了（抱歉没有即时看到回复
