### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by ghost** [rime/weasel#411]
反馈问题
在玩“风暴英雄”游戏输入，想切换大小写或则切换中英文的时候会推出到桌面
系统环境：WIN10工作站

**Comment by ted423** [comment]
https://github.com/rime/weasel/issues/401
感觉跟这个问题类似的

**Comment by ted423** [comment]
主要就是切换时，输入法会显示下那个更改中英文的输入法的小图标，可能影响了全屏

**Comment by GartuLee** [comment]
应该是，我把分辨率改成窗口模式就没问题了。

**Comment by Prcuvu** [comment]
Duplicate of #285

**Comment by fxliang** [comment]
已添加参数禁用切换tip
#1055
