### ISSUE TITLE
paging的改进建议

### ISSUE THREAD

**Issue by hyaray** [rime/weasel#412]
假设用逗号和句号翻页。
目前paging应该是按了一次【句号】就生效了。
建议改成【页数>1】才生效，这样按了【句号】再按【逗号】回到第一页（paging就失效了），再按【逗号】还是能直接上屏汉字并输出。这样也许更完美？

**Comment by Ace-Who** [comment]
会容易误操作，因为往回翻页尤其是想回到第一页时，常常不会数页数，而是反复按 <kbd>,</kbd> 键或者按住不放，直到视觉确认翻页已停止。

**Comment by hyaray** [comment]
这个很有道理，如果能增加一个页数>1的选项会更自由，也不太重要。
顺便提下，paging的含义是我自己摸索的，建议wiki里直接说清楚，
不过类似这样没说得非常清楚的说明文档还是挺多的，给学习增加了难度。
