### ISSUE TITLE
单个音节对应多字问题

### ISSUE THREAD

**Issue by Hermittttt** [rime/weasel#414]
小狼毫0.14.3，系统win10，使用方案为小鹤双拼。
希望单个音节不会出现对应多字的现象，具体情况描述如下：

在键入某些特定的单词时，词典会将某个词组归于词干中的某组音节。比如我输入“na ni”的时候，第一次输入通过单字选取成功输入，第二次再输入的时候“那你”这个单词会被归入“na”这个音节中，导致“na ni”这两个音节输出“那你你”三个字，或者说直接输入“na”就会出现“那你”的候选。同时这两个音节组成的词语中“纳尼”的权重异常的高，多次输入“那你”也无法将其提高到第一位。

另一个例子是当输入“ri ka ze”（日喀则）这个词语时，第一次通过单字选取成功输入，第二次再输入的时候“日喀则”这个词被归于“ri ka”这两个音节下，输入“ri ka ze”会导致输出“日喀则则”这样的单词。

不知道是设置有问题还是其他的问题，希望不吝赐教

**Comment by Ace-Who** [comment]
无法重现，应该是配置问题。

**Comment by Hermittttt** [comment]
尝试了一些配置改动后问题依旧，贴出主要的一些patch

weasel.custom.yaml
`customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Wed Jul 17 17:05:29 2019"
  rime_version: 1.5.3
patch:
  "style/color_scheme": google
  "style/horizontal": true
  "style/layout/candidate_spacing": 12`

default.custom.yaml
`customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Rime::SwitcherSettings"
  modified_time: "Wed Jul 17 11:06:46 2019"
  rime_version: 1.5.3
patch:
  schema_list:
    - {schema: luna_pinyin}
    - {schema: luna_pinyin_simp}
    - {schema: double_pinyin_flypy}`

double_pinyin_flypy.custom.yaml
`patch:
  "translator/dictionary": luna_pinyin.extended
  "translator/preedit_format": {}
  translator/enable_sentence: false
  punctuator/full_shape:
    "/" : [ "/", ／, ÷ ]
    "%" : "%"
  punctuator/half_shape:
    "/" : [ "/", ／, ÷ ]
    "%" : "%"
  'recognizer/patterns/punct': ^/[a-z0-9][a-z]*$
  'punctuator/import_preset': symbols
`

symbols.custom.yaml 过长只贴一部分
`# Rime's punctuation and symbols
# encoding: utf-8
#
# Usage: patch your Rime schema to enable /X symbols

config_version: '1.3'

patch:
  punctuator/import_preset: symbols
  recognizer/patterns/punct: '^/([0-9]0?|[A-Za-z]+)$'

punctuator:
  full_shape:`

同时在double_pinyin_flypy.schema.yaml的tranlator中添加了
`    - table_translator@custom_phrase
    - table_translator`
并在结尾添加了
`custom_phrase: 
  dictionary: ""
  user_dict: custom_phrase
  db_class: stabledb
  enable_completion: false
  enable_sentence: false
  initial_quality: 1`
以启用自定义短语。

没有其他的修改，不知道可能是哪里的配置出了问题。

如上，似乎没有发现什么能够导致bug的修改。程序文件夹中的原始文件没有改动，

**Comment by Hermittttt** [comment]
再次确认了一下，是shift+ctrl对自造词进行删除的问题。我会关闭这个问题重新开另一个问题。
