### ISSUE TITLE
[BUG]利用shift+del删除自造词的时候出现bug

### ISSUE THREAD

**Issue by Hermittttt** [rime/weasel#415]
在[之前的问题](https://github.com/rime/weasel/issues/414)中进行一番测试发现原因在于shift+del进行自造词删除的时候出现了bug。
和之前的描述相同，虽然表面上看起来是出现了音节<字符的候选词，根本原因是在进行输入的时候对自造候选词进行了shift+del的删除。

例如：
在输入“日喀则”这个单词时，键入“rikaze”，选择候选，成功打出这个单词。然后再次击打“rikaze”，出现第一位的“日喀则”候选后使用shift+del删除这个候选。你会发现候选被删除，但是在下一次输入“rika”的时候就会出现“日喀则”的候选，并进一步的在输入“rikaze”的时候出现“日喀则则”的候选。

应该能够确定是一个bug，不知道有没有人能够帮忙复现一下。更改配置和使用全新安装的小狼毫均会出现这个问题。

**Comment by Ace-Who** [comment]
还是无法重现，应该是问题配置所导致的自造词编码留在了用户词典中，重装不会改动用户词典。可以删除用户词典来解决。

**Comment by Hermittttt** [comment]
您好，谢谢您的回复。
在重装的时候我删除了所有的用户词典和配置，仍然出现了这个问题。

**Comment by Hermittttt** [comment]
在用户词典中我发现了很多的单音节对应多字的词条，请问这是正常现象吗？如果是的话，可以加个开关吗？很影响输入体验，而且我想知道这样的词条是如何被记入词典中的，按理来说打一个音是无法得到两个字的。目前的观察是键入“kele”选择“克”和“了”之后，再单独键入“ke”就会出现“克了”的候选词。
词典如下：
![image](https://user-images.githubusercontent.com/32975934/73421756-e3259080-4361-11ea-9ede-a0f8aa12418b.png)
甚至还有这样的无法对上首音节的词条：
![image](https://user-images.githubusercontent.com/32975934/73421855-1c5e0080-4362-11ea-937a-bf43056abd0f.png)
一部分的输入法配置：
**double_pinyin.schema.yaml**(/appdata/roaming/rime)
……
translator:
  dictionary: luna_pinyin
  prism: double_pinyin
  preedit_format:
……

**double_pinyin_flypy.custom.yaml**(/appdata/roaming/rime)
patch:
  "translator/dictionary": luna_pinyin.extended
  "translator/preedit_format": {}
  translator/enable_sentence: false
  punctuator/full_shape:
    "/" : [ "/", ／, ÷ ]
    "%" : "%"
  punctuator/half_shape:
    "/" : [ "/", ／, ÷ ]
    "%" : "%"
  'recognizer/patterns/punct': ^/[a-z0-9][a-z]*$
  'punctuator/import_preset': symbols

**double_pinyin_flypy.schema.yaml**(/appdata/roaming/rime)
……
engines:
  translators:
    - punct_translator
    - reverse_lookup_translator
    - script_translator
    - table_translator@custom_phrase
    - table_translator
……
translator:
  dictionary: luna_pinyin
  prism: double_pinyin_flypy
  preedit_format:
……

**luna_pinyin.custom.yaml**(/appdata/roaming/rime)
patch:
  "translator/dictionary": luna_pinyin.extended
  "speller/algebra/@before 0": xform/^([b-df-hj-np-tv-z])$/$1_/

**double_pinyin_flypy.schema.yaml**(/appdata/roaming/rime/build)
……
engines:
  translators:
    - punct_translator
    - reverse_lookup_translator
    - script_translator
    - "table_translator@custom_phrase"
    - table_translator
……
translator:
  dictionary: luna_pinyin.extended
  enable_sentence: false
  preedit_format:
    {}
  prism: double_pinyin_flypy

如果需要其他配置文件的话也请告诉我，目前这个bug比较影响输入体验

**Comment by Ace-Who** [comment]
请点击评论框右下角的 <kbd>M↓</kbd> 了解如何呈现代码。

```yaml
engines:
  translators:
    - punct_translator
    - reverse_lookup_translator
    - script_translator
    - "table_translator@custom_phrase"
    - table_translator  # 去掉这行
```

代码比较乱，先简单看了一下发现一个问题。

**Comment by Hermittttt** [comment]
感谢！经过修改之后问题解决了！
