### ISSUE TITLE
喃字輸入法 選項框中有部分字形無法顯示

### ISSUE THREAD

**Issue by lzy371** [rime/weasel#417]
![image](https://user-images.githubusercontent.com/54947670/64351519-09523900-d02d-11e9-8ab5-1bdffb4ac799.png)

**Comment by Ace-Who** [comment]
字体的问题，和输入法程序没关系。

**Comment by Ace-Who** [comment]
可以在 weasel.custom.yaml 中修改字体。

**Comment by lzy371** [comment]
> 可以在 weasel.custom.yaml 中修改字体。

請問 該如何修改啊？沒有找到custom 的文件夾。謝謝！

**Comment by lzy371** [comment]
> 可以在 weasel.custom.yaml 中修改字体。

您好，我已到 weasel.custom.yaml文件，但是yaml文件如何打開呢？

**Comment by lzy371** [comment]
> 可以在 weasel.custom.yaml 中修改字体。

感觉可能和字库有关。输入程序框中显示不出来的字形，放到word里面换一种字体即可显示。

**Comment by Ace-Who** [comment]
用文本编辑器（如记事本、Notepad++）打开此文件，找到这一行：

```yaml
patch:
```

根据需求添加一行或多行，修改为

```yaml
patch:
  style/font_face: <此处连同尖括号替换为字体名称>
  style/font_point: <字号，如 16>
```

除替换部分外，其余部分须保持原样，不要省略或添加任何一个空格。
字体名称须准确无误，可在系统字体设置面板中查看字体，打开一个字体的预览窗口后，找到「字体名称：***」一行。

**Comment by lotem** [comment]
> 喃字輸入法
——本品不包含這個輸入方案。
除了嘗試 https://github.com/rime/weasel/issues/417#issuecomment-538797769 建議的修改，還請查看方案源文件內是否由 `style/font_face` 指定了顯示所需的字體。

（問題涉及本品未提供的軟件／未知的配置，因此關閉）

**Comment by lzy371** [comment]
谢谢！

**Comment by lzy371** [comment]
> > 喃字輸入法
> 
> ——本品不包含這個輸入方案。
> 除了嘗試 [#417 (comment)](https://github.com/rime/weasel/issues/417#issuecomment-538797769) 建議的修改，還請查看方案源文件內是否由 `style/font_face` 指定了顯示所需的字體。
> 
> （問題涉及本品未提供的軟件／未知的配置，因此關閉）

您好！我已修改了 weasel.custom.yam，但还是不行。我想问下，在哪里查看方案源文件內是否由 style/font_face 指定了顯示所需的字體？谢谢！

**Comment by lzy371** [comment]
> 用文本编辑器（如记事本、Notepad++）打开此文件，找到这一行：
> 
> ```yaml
> patch:
> ```
> 
> 根据需求添加一行或多行，修改为
> 
> ```yaml
> patch:
>   style/font_face: <此处连同尖括号替换为字体名称>
>   style/font_point: <字号，如 16>
> ```
> 
> 除替换部分外，其余部分须保持原样，不要省略或添加任何一个空格。
> 字体名称须准确无误，可在系统字体设置面板中查看字体，打开一个字体的预览窗口后，找到「字体名称：***」一行。

谢谢您！我已修改，但还是不行。

**Comment by Ace-Who** [comment]
@lzy371
> 您好！我已修改了 weasel.custom.yam，但还是不行。我想问下，在哪里查看方案源文件內是否由 style/font_face 指定了顯示所需的字體？谢谢！

方案配置文件是 `<schema_id>.schema.yaml`，不知道你的输入方案的 `schema_id` 是什么，但是其内容包含了方案名称，可自行查验。

**Comment by lzy371** [comment]
> @lzy371
> 
> > 您好！我已修改了 weasel.custom.yam，但还是不行。我想问下，在哪里查看方案源文件內是否由 style/font_face 指定了顯示所需的字體？谢谢！
> 
> 方案配置文件是 `<schema_id>.schema.yaml`，不知道你的输入方案的 `schema_id` 是什么，但是其内容包含了方案名称，可自行查验。

 <schema_id> 是 hannomPS。我所需要的字體 是 Nom Na Tong。我已把 schema_id 改為 Nom Na Tong，但還是不行。
![image](https://user-images.githubusercontent.com/54947670/66450314-9eac7700-ea8a-11e9-9715-dd4e03fe9ce7.png)
![image](https://user-images.githubusercontent.com/54947670/66450342-b7b52800-ea8a-11e9-8009-a626280db6f8.png)

**Comment by Ace-Who** [comment]
> <schema_id> 是 hannomPS。我所需要的字體 是 Nom Na Tong。我已把 schema_id 改為 Nom Na Tong，但還是不行。

1. 不要修改文件名，修改之后，此方案配置即失效。须准确改回文件的原名，再进行以下操作。
2. 不要移动、无需复制字体文件。
3. 前述修改 `weasel.custom.yaml` 的方法，似乎忘讲了最后要运行「重新部署」，先做这步。如果无效再往下看。
4. 同样用文本编辑器打开 `hannomPS.schema.yaml`，查找 `style` 节点下的 `font_face` 节点，如果有这样的节点，就参照前述方法修改 `font_face: ` 右边的字体名称为 `Nom Na Tong`。同样需要「重新部署」。

**Comment by lzy371** [comment]
> > <schema_id> 是 hannomPS。我所需要的字體 是 Nom Na Tong。我已把 schema_id 改為 Nom Na Tong，但還是不行。
> 
> 1. 不要修改文件名，修改之后，此方案配置即失效。须准确改回文件的原名，再进行以下操作。
> 2. 不要移动、无需复制字体文件。
> 3. 前述修改 `weasel.custom.yaml` 的方法，似乎忘讲了最后要运行「重新部署」，先做这步。如果无效再往下看。
> 4. 同样用文本编辑器打开 `hannomPS.schema.yaml`，查找 `style` 节点下的 `font_face` 节点，如果有这样的节点，就参照前述方法修改 `font_face: ` 右边的字体名称为 `Nom Na Tong`。同样需要「重新部署」。

我把程序重裝了一下，居然可以顯示了。再次感謝您！
