### ISSUE TITLE
中文切到英文，已输入的字符没有清空也没有变成英文输入模式

### ISSUE THREAD

**Issue by crosslife** [rime/weasel#426]
打字的时候以为是英文，打了之后才发现是中文，这时候 shift 切输入法，既没有清空之前输入的字符，也没有把之前输入的字符变成英文输入的方式，而是进入了一种奇怪的状态，比较尴尬。

![image](https://user-images.githubusercontent.com/1802419/65811690-eb709200-e1ee-11e9-8ab2-f0c2507448f9.png)

**Comment by lotem** [comment]
詳見這篇文檔：
https://github.com/rime/home/wiki/UserGuide#%E4%B8%AD%E8%A5%BF%E6%96%87%E5%88%87%E6%8F%9B
