### ISSUE TITLE
用visual studio 2019编译weasel时，出现未找到的导入项目

### ISSUE THREAD

**Issue by gitQqqHs** [rime/weasel#427]
**下面是错误输出：**
D:\Downloads\weasel-master\WeaselDeployer\WeaselDeployer.vcxproj : error  : 未找到导入的项目“D:\Downloads\weasel-master\weasel.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。  D:\Downloads\weasel-master\WeaselDeployer\WeaselDeployer.vcxproj

D:\Downloads\weasel-master\WeaselSetup\WeaselSetup.vcxproj : error  : 未找到导入的项目“D:\Downloads\weasel-master\weasel.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。  D:\Downloads\weasel-master\WeaselSetup\WeaselSetup.vcxproj

**Comment by lotem** [comment]
是按照 https://github.com/rime/weasel/blob/master/INSTALL.md 的步驟做嘛？

如果在IDE裏打開，可能需要修改模板文件`weasel.props.template`創建`weasel.props`。

**Comment by gitQqqHs** [comment]
thanks！！

**Comment by lotem** [comment]
按照 https://github.com/rime/weasel/blob/master/INSTALL.md 的步驟做。脚本会自动创建该文件。

**Comment by ryysoft** [comment]
git下载weasel总是中断，所以后面步骤也就没有了。我现在手工加上了v142这样的属性，但是编译boost的相关头文件代码时，出内部编译错误，好像是说c++高标准在Vs2019里要打补丁，请问遇到过这样问题吗？
我编译librime用你们window.readme很顺序，但是weasel的git下载不下来，特别是librime的下载，git上下载很慢，有时候报checksum错误

**Comment by ryysoft** [comment]
fatal error C1001: 内部编译器错误。
佛振大大，遇到过吗？
