### ISSUE TITLE
在 mintty 中激活 weasel 输入法，会导致光标颜色无法切换

### ISSUE THREAD

**Issue by jdhao** [rime/weasel#428]
如题，我使用 [mintty](https://github.com/mintty/mintty) 作为 ssh 客户端登录服务器，设置了当 IME 中文输入激活的时候光标变成红色，本来的颜色是绿色。

登录服务器，然后打开文件，如果激活 weasel 输入法，当前的光标就会变成红色，按 Shift 键切换成英语模式也不行，还是红色。但是如果我使用 Win 10 系统自带的拼音输入法，切换成英语模式，我的光标颜色就会变成本来的颜色（绿色）。

![mintty_imecolor](https://user-images.githubusercontent.com/16662357/67006375-93ef8300-f117-11e9-882f-bd45a091078f.gif)

Mintty 的开发者说是 weasel 输入法实现的 bug 导致，具体可以参考 [这里](https://github.com/mintty/mintty/issues/930#issuecomment-542673213).

**Comment by Prcuvu** [comment]
mintty 的发言引用如下：
> I observe weird and buggy behaviour of the weasel tool.
Particularly, it never sends a WM_IME_NOTIFY message with IMN_SETOPENSTATUS command. This would be used to switch the IME status.
It sends lots of WM_IME_NOTIFY messages, even if nothing is happening on the keyboard, it does not always refocus to the terminal window, its popup placement is not always proper, it lays a white box over the text...

**Comment by atauzki** [comment]
win10，19041预览版，连微软拼音都会有相同的bug

**Comment by yu-soong** [comment]
@jdhao 请问您这个光标根据输入法改变颜色，是对所有 App 都有效还是只在 mintty 里生效？是用 AutoHotkey 还是别的软件实现的？可以方便分享一下你的代码吗？谢谢！

**Comment by jdhao** [comment]
@yu-soong  这个是 mintty 的功能，需要自己设置：

```
IMECursorColour=255,0,0
```

参考：https://jdhao.github.io/2019/10/16/useful_mintty_tips_configs/#change-cursor-when-ime-is-on
