### ISSUE TITLE
东风破的用户文件夹不正确

### ISSUE THREAD

**Issue by trim21** [rime/weasel#429]
![image](https://user-images.githubusercontent.com/13553903/67216860-78a5b000-f456-11e9-8119-f6f346abfeee.png)

出现问题的情况：设置了自定义的用户文件夹

我的用户文件夹被设置在了非`%APPDATA%/rime`的地方，而且小狼毫能从对应文件夹中正常加载配置

但是东风破显示的用户文件夹位置是错误的，造成安装的包并不会正常起效，我是安装了双拼，手动拷贝描述文件才能正常使用

**Comment by lotem** [comment]
解法：給 rime-install 也設置一下用戶文件夾的路徑。
https://github.com/rime/plum#use-git-for-incremental-updates-optional

配置腳本模板：
https://github.com/rime/plum/blob/master/rime-install-config.bat#L15

**Comment by fxliang** [comment]
最新plum和nightly 构建已修复
