### ISSUE TITLE
发现小狼毫一个bug，输入一个字符，按 “ .” 进行翻页，再输入一个字符得不到候选字。。。

### ISSUE THREAD

**Issue by llf10811020205** [rime/weasel#43]

**Comment by osfans** [comment]
ibus也有類似問題，它是把"."輸進去了
比如`n.i`，這樣就搜不到了。

**Comment by llf10811020205** [comment]
是的，有规避的方法吗？

**Comment by llf10811020205** [comment]
@osfans

**Comment by osfans** [comment]
用page_up/down翻页好像就没有问题。

**Comment by llf10811020205** [comment]
@osfans page_up/down，那我应该发送一些什么东西来代表翻页操作

**Comment by osfans** [comment]
https://github.com/rime/brise/blob/master/default.yaml#L123
https://github.com/rime/librime/blob/develop/src/gear/selector.cc#L32

**Comment by lotem** [comment]
It's a feature, not bug.
It'll allow you to input URLs (eg. "www.google.com") without needing to switch to ascii mode.
Implemented by this option:
https://github.com/rime/brise/blob/master/default.yaml#L142
