### ISSUE TITLE
在word2019中输入文字看不清提示条

### ISSUE THREAD

**Issue by beforesun** [rime/weasel#437]
参照下图，看不清后面的候选字。由于GIF显示慢，看上去可以看清候选字。
![Rime-Wubi86](https://user-images.githubusercontent.com/45909516/68191705-136fc400-ffeb-11e9-9964-4fae5a6fe380.gif)
而在QQ、Tim或者其它的软件中是正常的显示。

重启之后，又可以看清。
OS: win10
rime版本: 0.14.3

**Comment by Sciroccogti** [comment]
Duplicate of #228

**Comment by determ1ne** [comment]
已于新版本中解决
