### ISSUE TITLE
將小狼毫註冊到繁體中文（香港）等其他區域

### ISSUE THREAD

**Issue by sgalal** [rime/weasel#438]
目前安裝小狼毫時，只可以選擇註冊到中文（中國／臺灣）。希望可以增加繁體中文（香港）這一區域的選項。

如果支援自定義區域則更好，例如某些用家可能只使用日語羅馬字方案，此時註冊到日本語是較好的選擇。

**Comment by lotem** [comment]
有待研究。
目前註冊輸入法到中文（中國／臺灣）的做法是編譯出兩份輸入法前端的DLL/IME模塊，分別註冊到不同語言／地區選項，代價不小。這種實現方式不容易擴展到更多地區。

**Comment by Reniastyc** [comment]
今天作了一箇大膽的嘗試。
我首先用WeaselSetup.exe刪除了輸入法的註冊，如此情況下，是沒有中文輸入法的狀態。
之後，我同時開啓兩箇WeaselSetup.exe，這兩箇WeaselSetup.exe都顯示我沒有安裝小狼毫。
第三步，我對兩箇程序分別選擇簡體和繁體，分別安裝，然後得到了這麼一箇結果
![image](https://user-images.githubusercontent.com/37499529/98651234-f21b8380-2374-11eb-9d82-b0ff5f253eef.png)
如圖所示，這樣我就同時安裝上了簡體和繁體的小狼毫。
此時在Word中分別切換簡中和繁中輸入法，能夠分別將字體切成簡中和繁中字體，也就是說確實實現了共存。
打開註冊表，HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\CTF\TIP\{A3F4CDED-B1E9-41EE-9CA6-7B4D0DE6CB0A}\LanguageProfile
![image](https://user-images.githubusercontent.com/37499529/98651582-681fea80-2375-11eb-914e-8e6deab01252.png)
上下兩箇0404、0804分別是繁中和簡中的語言識別碼，可以看到他們之下有一箇GUID相同的項，點開可以看到正是小狼毫。 
![image](https://user-images.githubusercontent.com/37499529/98651766-9f8e9700-2375-11eb-826e-92c50b65826c.png)
![image](https://user-images.githubusercontent.com/37499529/98651788-a61d0e80-2375-11eb-95fe-dd7800603ceb.png)
區別僅僅在於最後一項語言識別碼部份。 
然後我把任意一項導出，將語言識別碼改爲0c04，刪除中文臺灣，重裝中文香港語言包後，得到了這箇
![image](https://user-images.githubusercontent.com/37499529/98652846-327c0100-2377-11eb-9945-edc225663bfb.png)
所以我想，是不是衹要調整一下WeaselSetup.exe的註冊表寫入部份，就能解決區域語言的問題？甚或可以改成多選，比如同時裝中文簡體和繁體（不過Win10好像不支持同時安裝臺灣中文和香港中文這兩箇語言包，或者說不能同時裝兩箇繁中或兩箇簡中？）

**Comment by Reniastyc** [comment]
補充一下，確定了你的註冊表相應路徑之後，可以使用如下代碼直接寫入，以免去逐項複製的繁瑣
建立文本文檔，改後綴名爲reg即可。

=======此行不要複製=======
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\CTF\TIP\{A3F4CDED-B1E9-41EE-9CA6-7B4D0DE6CB0A}\LanguageProfile\0x00000404\{3D02CAB6-2B8E-4781-BA20-1C9267529467}]
"Enable"=dword:00000001
"Description"="小狼毫"
"IconFile"="C:\\WINDOWS\\system32\\weasel.dll"
"IconIndex"=dword:00000000
"SubstituteLayout"="0xe0200404"
"HiddenInSettingUI"=dword:00000000
"SubItemInSettingUI"=dword:00000000
=======此行不要複製=======
其中0404是臺灣繁中，改爲0c04則是香港繁中，0804則是大陸簡中。具體的語言識別碼見https://docs.microsoft.com/zh-tw/windows-hardware/manufacture/desktop/available-language-packs-for-windows

**Comment by Reniastyc** [comment]
但如此會不會帶來穩定性上的問題，我是不確定的，僅僅是出於系統識別機理出發所作的嘗試。（但我既然成功發了帖，至少證明不會爆炸對吧

**Comment by lotem** [comment]
哦，现在只有一份DLL了？那应该没有问题。
我记得以前是要把语言号编译到程序资源里的。这个再查证一下。

**Comment by lotem** [comment]
这个还是不对的。
https://github.com/rime/weasel/blob/96e53a5069c316b5f5a5f3edf7d623309a665dc1/WeaselSetup/imesetup.cpp#L77
简繁中文分别做成两个DLL，同时安装会发生文件覆盖。这样用的结果，就是无论选择哪个语言，调用的都是后安装的那个版本，不知道有没有问题。
其他区域也有这个问题，需要对每个语言和地区专门编译出一个版本。

**Comment by Reniastyc** [comment]
不，問題的關鍵似乎不在這裏，而在於Windows的輸入法語言識別機制。
Windows的輸入法識別語言並不是從DLL的標註語言完成的，而是通過當前輸入法被註冊的語言完成的。
換言之，就算調用同一份DLL文件，不論其註冊語言爲何，在Windows的識別下都是以其註冊爲輸入法的語言作爲當前的輸入語言。
實用方面的查證手段也很簡單，打開Office，這軟件會根據你所使用的輸入法的語言自動切換默認字體，比如用簡中輸入法的時候，如果你使用繁中字體，就會自動給你切成等綫（簡中默認字體），相應地，當使用繁中輸入法時，如果使用簡中字體，則會自動切成細明體（繁中默認字體），而使用註冊表，同時註冊了簡中和繁中兩箇語言的小狼毫後，切換不同的小狼毫，會順利觸發對應語言的默認字體規則，這一點我在兩臺不同的電腦上分別測試後，得到了同樣的結果

**Comment by Reniastyc** [comment]
可以進行一項簡單的測試。請編譯一箇語言標註爲英文的DLL，然後註冊給簡中版小狼毫，並測試可用與否，即可驗證

**Comment by Reniastyc** [comment]
方纔，在下進行了另一項測試，使用註冊表，將小狼毫註冊到了阿拉伯語言區0401，
然後得到了一箇阿拉伯區的小狼毫。
![image](https://user-images.githubusercontent.com/37499529/98778754-c3adaf00-242d-11eb-8bc9-92c80397a302.png)

當我切換爲這一輸入法時，Office將所用字體自動切爲了相應的阿拉伯字體
![image](https://user-images.githubusercontent.com/37499529/98778579-8e08c600-242d-11eb-9887-41a3ba14b67f.png)
甚至在Github網䈎端也能在切成阿拉伯字體時輸出我完全不認識的阿拉伯文字
شكسمينبتسشميكنبت
這是否可以說明，在實用意義下，根本無需考慮輸入法所用DLL的標註語言？

**Comment by BrandonKMLee** [comment]
Hope that this can be fixed

**Comment by Raymonf** [comment]
@BrandonKMLee I don't know if this issue is easily fixable, but certainly not very important for your Chocolatey issue.

In Windows, the language ID 0xC04 (Chinese, Hong Kong) is an alias for 0x404 (Chinese, Taiwan) with different date/time settings. (More specifically, 0xC04 falls back to 0x404 for everything except for date/time formats.)

With that in mind, it makes sense that 0xC04 and 0x404 input method editors cannot coexist. If you add "Chinese, Taiwan" to your language list (for example, adding Microsoft Cangjie to your IME list after specifically selecting the Taiwan language option), you will no longer be able to add any other Traditional Chinese locale, including "Chinese, Hong Kong".

The solution is to select "Chinese, Hong Kong" from the beginning. Then, when Weasel is set up, it will install and show as "Chinese, Hong Kong".

![kpBP7J66oU](https://user-images.githubusercontent.com/8991740/114657148-6c05bf00-9cbd-11eb-9e9b-fa791e68e009.png)

**Comment by BrandonKMLee** [comment]
@Raymonf I think it has a similar bug property to the "force install Chinese Pinyin" issue for others. Other than that, for the original issue, the Simplified Chinese was on the panel but not available to uninstall (while the system default IS Hong Kong Chinese), so I have to force install then uninstall Pinyin to flush the system, and then reinstall Weasel.

**Comment by BrandonKMLee** [comment]
@Raymonf most of the time I use the "Chinese (Hong Kong)" option as default on computer, but when it is invoked through Chocolatey, it auto-installs "Chinese (China)" causing heavy bugs. If I were to download it directly, the bug disappears.

**Comment by Raymonf** [comment]
@BrandonKMLee It actually is possible to automate; I believe the `/t` flag is required on the Weasel setup package for Traditional Chinese (it will pass the flag to `WeaselSetup` later). I saw your comment on the Chocolatey repository issue, I'll let the maintainer know there as well.

**Comment by BradKML** [comment]
Hoping the next update can come for RIME, thanks

**Comment by fxliang** [comment]
> Hoping the next update can come for RIME sooner, thanks

https://github.com/rime/weasel/releases/tag/latest   nightly build is available before that. 
and yes, it will come soon.
