### ISSUE TITLE
有沒有可能增加給殘障人士使用的部首輸入功能？

### ISSUE THREAD

**Issue by vitrum** [rime/weasel#442]
有些殘障人士可能手指無法正常操作鍵盤，但是可以使用滑鼠，用部首輸入的方式可能會比較適合使用。

使用虛擬鍵盤的形式，展示部首，滑鼠點選部首，展示對應文字供輸入。輸入效率要比使用滑鼠點擊拼音方式會高很多。

參考文章：https://www.ithome.com/0/457/483.htm

**Comment by determ1ne** [comment]
Closed as stale, reopen it if the problem still exists.
