### ISSUE TITLE
weasel-0.14.3.0在Windows 7里运行使用时，右键点击输入框会导致explorer崩溃

### ISSUE THREAD

**Issue by Dunkelicht** [rime/weasel#445]
大家好， 

rime输入法是自由的，我很喜欢，但是害怕引起潜在的兼容性问题，例如在

在windows7 里运行使用时，右键点击输入框会导致explorer奔溃

请问可否跟踪一下这个错误？ 在32位和64位都会引起这个问题。 是否别的类似情形也会导致该问题？

再次感谢 祝愿weasel和rime一直更新下去！

**Comment by fxliang** [comment]
这个是0.14.3中的bug，在新版中已修复。旧版不再维护了~
