### ISSUE TITLE
如何在鼠须管中导入小狼毫的词库？

### ISSUE THREAD

**Issue by iugo** [rime/weasel#45]
方法一: 直接复制
本来想直接复制, 但是在 Windows 10 中复制 `terra_pinyin.userdb.kct` 文件的时候遇到了权限问题. (鼠须管中自带的该文件比我在中州韵中使用过一段时间的文件体积还大)

方法二: 鼠须管自带用户词库管理工具
无法导入 `terra_pinyin.userdb.kct` 这种格式的文件, 似乎只能 txt.

**Comment by Youxikong** [comment]
github有一个叫做深蓝词库转换的项目可以转换词库的格式。

**Comment by lotem** [comment]
kct 格式已经不支持了
下个版本 小狼毫 0.11 会把旧版本的 kct 词典升级到新格式
