### ISSUE TITLE
可否加入v和u特殊功能，可以计算简单的加减乘除和其他彩蛋功能

### ISSUE THREAD

**Issue by Franklyn1987** [rime/weasel#451]
可否加入v和u特殊功能，可以计算简单的加减乘除和其他彩蛋功能

**Comment by lotem** [comment]
可以。
librime 可以通過編程擴展。

**Comment by Franklyn1987** [comment]
关闭了,可否给我个思路如何添加

**Comment by lotem** [comment]
需要寫個翻譯器
參考示例代碼 https://github.com/rime/librime/tree/master/sample
