### ISSUE TITLE
如何正确安装？

### ISSUE THREAD

**Issue by masterrite** [rime/weasel#456]
在windows 10系统中安装看似成功，但无法呼出输入框，也无法选择输入方案。右键点击图标之后任何选项都没有作用。
 
我的安装步骤：
1. 解压缩到指定文件夹（C:/Program/RIME）
2. 点击setup.exe
3. 默认文件夹安装
4. 进入windows设置->语言，调出输入法键盘

这个时候Ctrl+`和F4没有任何用

5. 点击rime-install.bat
6. 把安装包的zip文件夹拖入bat，然后回车

问题依然存在。重启多次，没有任何作用。

**Comment by Ace-Who** [comment]
安装步骤：

1. 运行 weasel-xxxxxx-installer.exe

**Comment by masterrite** [comment]
> 安装步骤：
> 
> 1. 运行 weasel-xxxxxx-installer.exe

官网下载的文件包里没有这个

**Comment by rtransformation** [comment]
确实上的是官网么？
https://rime.im/download/

**Comment by masterrite** [comment]
> 确实上的是官网么？
> https://rime.im/download/

是啊，下载下来是个zip压缩文件。后缀改成exe之后好了，但是不知道为什么会下载一个zip下来
