### ISSUE TITLE
使用了特殊字符的自定方案无法直接编译

### ISSUE THREAD

**Issue by WhiverFichos** [rime/weasel#457]
如下三行，`punctuator: ` 下：
```
    "/": "́"
    "\\": ["\\", "/", "-", "'"]
    "'": "·"
```
若在用户文件夹中 .schema.yaml 中直接添加后部署，会无效；而修改 build 文件夹中的 .schema.yaml，部署后功能正常。

**Comment by lotem** [comment]
兩處解析YAML文件的代碼是一樣的，可知不是因特殊字符的處理而出錯。
請檢查一下部署時的錯誤日誌。
