### ISSUE TITLE
dvorak layout

### ISSUE THREAD

**Issue by goog** [rime/weasel#46]
hello. when i change **regedit** like here http://fatduck.org/dvorak/ , for some application , the layout does not change , such as RTX, ON firefox is ok

**Comment by Prcuvu** [comment]
Probably it is because Weasel TSF makes use of keyboard layout of US keyboard. Modify `HKLM\SYSTEM\ControlSet001\Control\Keyboard Layouts\00000804` to apply Dvorak for Weasel TSF.

**Comment by goog** [comment]
thx! resolved。TSF 是什麼呀
