### ISSUE TITLE
Windows 10上 WeaselSetup.exe，应该只安装TSF(*.DLL) 输入法

### ISSUE THREAD

**Issue by CharlesMengCA** [rime/weasel#461]
在Windows 10上 WeaselSetup.exe，是不是应该只安装TSF(*.DLL) 输入法？而没有必要安装旧的.ime 输入法？
retval += install_ime_file(ime_src_path, L".ime", hant, silent, &register_ime);
retval += install_ime_file(ime_src_path, L".dll", hant, silent, &register_text_service);

**Comment by Prcuvu** [comment]
应用程序对输入法的支持依赖于对输入法提供的接口的实现。对于 IME 来说，需要实现 IME 消息处理；对于 TSF 来说，需要实现对应的 TSF 接口。
TSF 作为较新的技术，有大量应用程序使用的旧文本控件没有实现 TSF 接口。这些旧应用程序需要利用 IME 版本的输入法。
TSF 提供了为这种情况回退到一个 IME 输入法的机制，即使两个版本都安装，系统也只显示一个。这样一来就没有视觉上的不便。
所以出于对旧应用程序的兼容考虑，需要两个都安装。
