### ISSUE TITLE
WeaselSetup.cpp 防止重复安装

### ISSUE THREAD

**Issue by CharlesMengCA** [rime/weasel#463]
static int Run(LPTSTR lpCmdLine)
{
	const bool silent = true;

	**if (has_installed()) return -1;**

	bool uninstalling = !wcscmp(L"/u", lpCmdLine);
	if (uninstalling) return uninstall(silent);
	
	bool hans = !wcscmp(L"/s", lpCmdLine);
	if (hans) return install(false, silent);
	
	bool hant = !wcscmp(L"/t", lpCmdLine);
	if (hant) return install(true, silent);
	
	bool installing = !wcscmp(L"/i", lpCmdLine);
	
	return CustomInstall(installing);
}

另外has_installed()也应该同时检查weasel.dll。如果windows10 只安装TSF IME （*.dll) 则只检查weasel.ime是不够的。

**Comment by Reniastyc** [comment]
不，我倒是正需要同時安裝一份繁中版小狼毫和一份簡中版小狼毫（
就像這樣
![image](https://user-images.githubusercontent.com/37499529/98654765-ae774880-2379-11eb-850e-5fb84d0252cd.png)

**Comment by lotem** [comment]
重复安装应该不是该工具而是调用者需要考虑的。此处最好确定地执行参数指定的命令。
另外，若按楼主给出的代码修改，如楼上所述无法注册到不同语言/区域，也会无法卸载。
