### ISSUE TITLE
建议开放自定义字符集过滤功能

### ISSUE THREAD

**Issue by sezhai** [rime/weasel#464]
Rime的生僻字过滤有些问题。用gb2312会打不出一些中文标点，如破折号“——”、间隔号“・”等，用gbk的话各种生僻字又都出来了，对于像五笔之类需要减少重码的输入方式不太方便。
建议修正一下gb2312字符集的问题。或者最好能开放自定义字符集过滤功能。这一点，小小输入法已经做了。如果rime能实现，那就太好了。

**Comment by lotem** [comment]
同 https://github.com/rime/home/issues/91

**Comment by LEOYoon-Tsaw** [comment]
其實現在已可借`lua_filter`做到
食用方法：
1. 一張以過濾字集爲內容的碼表，編碼爲字集標識
2. 以此碼表做一傀儡方案，僅含最基本方案內容，能生成`table.bin`即可
3. 用`lua_filter`在主方案中對候選項中的每個漢字做反查，即以上述傀儡方案反查
4. 僅輸出包含目標字集標識的選項。

**Comment by lotem** [comment]
完全沒有必要。可將詞典製作成只包含所需的字符集。

**Comment by LEOYoon-Tsaw** [comment]
> 完全沒有必要。可將詞典製作成只包含所需的字符集。

不能這麼說，字符集和方案可以由不同人維護，同一個字符集可以應用於多個方案，同一個方案也可以應用多個字符集。
強行把字符集和方案字典捆綁只會使得本可以分工各自完成的事情變得複雜而繁重。

**Comment by lotem** [comment]
> > 完全沒有必要。可將詞典製作成只包含所需的字符集。
> 
> 不能這麼說，字符集和方案可以由不同人維護，同一個字符集可以應用於多個方案，同一個方案也可以應用多個字符集。
> 強行把字符集和方案字典捆綁只會使得本可以分工各自完成的事情變得複雜而繁重。

這樣分工很好，但按照自定義字符集過濾碼表應該做在生成成品詞典之前。
如果在輸入法運行時用filter做過濾，資源佔用高、執行效率低，還無法克服組詞造句結果缺失的錯誤。
既然投入了資源編制字符集，讓他發揮最佳效果的方式，就是用他裁剪要製作的詞典。

特別針對樓主的需求，選擇編碼字符集的過程一定是與五筆碼表一起完成的，這樣才能兼顧重碼等情況。那麼最佳實踐就是縮減碼表規模實現對重碼的優化，同時把表外的字收錄到擴充詞典，用 `import_tables` 定義生成詞典的字符集規模。
