### ISSUE TITLE
这个功能应该如何实现？

### ISSUE THREAD

**Issue by Girsun** [rime/weasel#465]
请问一下，怎样可以像“小鹤音形”那个输入法一样， 按分号再按U可以实现删除上次输入。比如按wsm，打出“为什么”，按分号再按U直接删掉已经输入的这三个字？ 这样比按三次退格键效率要高！

**Comment by Ace-Who** [comment]
不支持。

**Comment by Girsun** [comment]
> 不支持。

那能定义什么？  自定义的东西不能提高输入效率的话，那就没什么亮点了，而且入门门槛还高！输入法就是要提高效率才是最好的，像打形码，四码定长，有时候按错一个键可能出来一长串，此时如果有一个快捷键可以撤销上次输入就可以提高很多效率！多多输入法都可以为什么这个还不行。。。

**Comment by VaslD** [comment]
输入过（所谓“上屏”，而非在“候选状态”）的文字理论上已经不归输入法管了。

提高输入/打字/排版效率的软件有很多，就个人而言我认为输入法应该只实现文字转换功能，快捷操作/宏（快速删除词句、自动重复输入等）之类的功能由具体这方面的软件实现。每个人都希望输入法中加入与文字转换没有太多关联功能就会导致输入法臃肿。

很多手机上的输入法自带屏幕截图、管理联系人、网络搜索、查询词典、下载动图等功能，虽然对于真正有需要的人很实用、很提高效率，但总感觉偏离了输入法的发展方向。“其它输入法有这个功能，为什么这款没有”不是个很好的例子。

**Comment by lotem** [comment]
本品未实现该功能。为跨平台设计的输入法接口不支持这样的操作。
