### ISSUE TITLE
开始菜单项目退出时弹错

### ISSUE THREAD

**Issue by CNMan** [rime/weasel#466]
小狼亳版本：`0.14.3.0`
操作系统：`Windows XP Pro wSP3 繁体中文版`
```
【小狼毫】用戶文件夾.lnk
【小狼毫】用戶詞典管理.lnk
【小狼毫】用戶資料同步.lnk
【小狼毫】安裝選項.lnk
【小狼毫】重新部署.lnk
【小狼毫】程序文件夾.lnk
【小狼毫】說明書.lnk
【小狼毫】輸入法設定.lnk
【小狼毫】檢查新版本.lnk
```

![error1](https://user-images.githubusercontent.com/8692234/73245490-4b9c3280-41e7-11ea-84de-af7d3b537eb7.png)
![error2](https://user-images.githubusercontent.com/8692234/73245492-4c34c900-41e7-11ea-8bb9-03695224b4e6.png)
![error3](https://user-images.githubusercontent.com/8692234/73245494-4c34c900-41e7-11ea-99ab-e7797965110c.png)

不用更改选项，直接点x关闭就可复现
不过设置均可生效，倒是不影响使用，就是每次都弹窗有点烦:(

链接:https://pan.baidu.com/s/1dJz75yJ3E9l25QfUba3v9Q 提取码:pc9a 
繁体XP虚拟机文件，一个原版，一个打了全部补丁+AdobeReader+Office2010wSP2

**Comment by fxliang** [comment]
0.14.3不再支持Windows xp
