### ISSUE TITLE
tsf框架问题

### ISSUE THREAD

**Issue by i258559** [rime/weasel#469]
在软件axure中，使用tsf框架会导致崩溃，而老板ime框架不会，不知道能否在配置里面增加
某些软件仅激活ime的配置？
谢谢提供这么好用的输入法

**Comment by fxliang** [comment]
![image](https://github.com/rime/weasel/assets/4023160/2fa1b2bc-8d4e-472c-a685-867e80820136)
如果是8.1或更新的系统，可以试下[Nightly Build](https://github.com/rime/weasel/releases/tag/latest)，目前看没有问题
