### ISSUE TITLE
将小狼毫的两种模式合并

### ISSUE THREAD

**Issue by SilverBut** [rime/weasel#47]
小狼毫的TSF和桌面模式会显示为两个不同的输入法，希望能合并为一种

**Comment by Prcuvu** [comment]
IME和TSF本来就是两个不同的框架，这两个没法合并。如果不喜欢，可以去输入法设置关掉其中一个。

**Comment by SilverBut** [comment]
@Prcuvu 是的，我清楚这是不同的框架
但是微软拼音只用其中的一个就完成了所有功能
而且在Windows 10 下，似乎不能单独删除这两种模式之一

**Comment by Prcuvu** [comment]
如果是Windows 10，建议改用rime-gits。
小狼毫在Windows 10上有兼容性问题，且不会被解决。

**Comment by methou** [comment]
弱弱的问如何关掉其中一个，我想关掉 IME 一直没有找到设置位置。

**Comment by rimefans** [comment]
直接删除即可

**Comment by methou** [comment]
我是在 Win10  下面，发现删除不掉。后来顺着安装部分的代码找到对应的注册表项删掉了。Thx anyway.

**Comment by q158073378252010** [comment]
各位大哥能解决下 游戏中不能输入文字? 游戏：腾讯CF

**Comment by Prcuvu** [comment]
@q158073378252010 
* 在一个问题的讨论串下讨论另一个问题是不礼貌的行为。
* 请参阅该公告：[小狼毫前端的兼容性問題將不再修復] (https://github.com/rime/home/issues/25)

**Comment by q158073378252010** [comment]
@Prcuvu  我不太会用。对不起。

**Comment by chickenjohn** [comment]
我尝试在win10下进入“控制面板-区域和语言选项”中可以删除其中的一者， 但在系统托盘直接打开输入法设置时，是没法删除的。希望删除的windows用户可以打开控制面板删除。

**Comment by JokerQyou** [comment]
Windows 10 更新到 1803 之后，控制面板没有了「区域和语言选项」，现在只有「区域」设置，在此对话框中点击「语言首选项」，会直接打开系统托盘打开的那个语言设置界面。在这个界面中是无法删除任何一个小狼毫输入法的。
![image](https://user-images.githubusercontent.com/1465267/39974036-75c98808-5758-11e8-8553-f1c349127904.png)
![image](https://user-images.githubusercontent.com/1465267/39974043-8064b3a0-5758-11e8-8b79-65bbe6ec775a.png)
![image](https://user-images.githubusercontent.com/1465267/39974048-8dec8336-5758-11e8-9804-33a4b02f7657.png)

**Comment by luyi7338** [comment]
可以不用管这个里面有哪些输入法，手工调整HKEY_CURRENT_USER\Keyboard Layout\Preload的值就好了

**Comment by HougeLangley** [comment]
是的，正如楼上朋友所说

**Comment by Pagliacii** [comment]
可以通过在注册表里搜索 weasel.ime，找到对应的注册表项，然后将整个 key 删除，再到语言设置里就可以删除掉一个了，不过貌似升级后又会回来。。。
