### ISSUE TITLE
按键绑定没有区分 Return 和 KP_Enter

### ISSUE THREAD

**Issue by Ace-Who** [rime/weasel#471]
KP_Enter 的绑定对 Return 同样生效了，反之亦然。

**Comment by Prcuvu** [comment]
请试用一下修复的版本：
[return_key_fix.zip](https://github.com/rime/weasel/files/4202794/return_key_fix.zip)

**Comment by Ace-Who** [comment]
谢谢，替换后再重启算法服务，再重新部署，我的测试结果是 `KP_Enter` 的绑定对两个键都不生效，`Return` 的绑定对两个键都生效。不过换回去之后再测试也是如此，不知道之前是不是测错了。

**Comment by Ace-Who** [comment]
替换后重启系统再测试，也是如此。

**Comment by Prcuvu** [comment]
需要将 weasel.dll 替换到 SysWOW64，weaselx64.dll 替换到System32 才可以生效。

**Comment by Ace-Who** [comment]
不好意思，这样替换后，还是如此。另外方案内的 `style` 配置有一部分失效了，包括 `inline_preedit`、`horizontal`、 `font_point` 等。不行的话等下一次发布直接安装吧。
