### ISSUE TITLE
共享文件夹中的 essay.txt 没有与主库同步？

### ISSUE THREAD

**Issue by CNMan** [rime/weasel#473]
小狼毫自带版本比 https://github.com/rime/rime-essay 中的多了约1.6万行
[essay.txt_diff.txt](https://github.com/rime/weasel/files/4196326/essay.txt_diff.txt)
@lotem

**Comment by lotem** [comment]
软件安装的数据文件是软件发布日当天的文件版本。

**Comment by CNMan** [comment]
即使按“软件安装的数据文件是软件发布日当天的文件版本”标准，也是不同步。
