### ISSUE TITLE
高分屏下侯选框过小

### ISSUE THREAD

**Issue by YunofHD** [rime/weasel#476]
Dear Developer
在具有两个不同分辨率且一个屏幕为高分屏（4K）的情况下，小狼毫候选框过小。已经调整了windows 高DPI设置并且修改了小狼毫的字体大小，但是在高分屏下chrome的搜索框和输入框还是太小了，请问有解决方法或者Guide吗？

**Comment by lotem** [comment]
同 https://github.com/rime/weasel/issues/367
