### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sgalal** [rime/weasel#477]
<div lang="zh-HK">

目前的 CI build script 並不會生成安裝包，因此我 fork 了這個倉庫，按照 INSTALL.md 中的指引把

```yaml
  - .\build.bat data hant installer
```

改為

```yaml
  - .\build.bat all
```

然後就出現 build error。

</div>

links:

- <https://github.com/sgalal/weasel/tree/ci>
- <https://ci.appveyor.com/project/chromezh/weasel/builds/30869024>

**Comment by lotem** [comment]
不要改
