### ISSUE TITLE
将shell.bat中有关vs2013编译环境改动

### ISSUE THREAD

**Issue by yxmline** [rime/weasel#48]
vs2013安装后会在系统环境加入vs120comntools变量名
shell.bat中vs2013默认安装位置不一定有效,每个人安装位置可能不同
将
%comspec% /k ""C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"" x86
改成
%comspec% /k ""%vs120comntools%\..\..\VC\vcvarsall.bat"" x86
比较好

**Comment by lotem** [comment]
的確比較好

https://github.com/rime/librime/blob/develop/shell.bat
這個腳本的路徑檢測比 weasel/shell.bat 完善，如果先檢查一下環境變量更好

**Comment by Prcuvu** [comment]
Fixed.
