### ISSUE TITLE
非输入状态，小狼毫能实现自动切换到英文吗？

### ISSUE THREAD

**Issue by ednykissyou** [rime/weasel#481]
这或许是中文输入法的一个通病，
就是任何状态你打字，中文输入法都会出现。

可是有真的不需要他出现。不止Adobe家族，有许多软件是单个字母就是快捷键，比如V就是pa的工具。但如果你按V时你没注意是中文输入法，那弹出的输入面版会让你很反感。

还有资源管理器里，你想按首字母快速找到某个文件或文夹夹，输入面版也会不受欢迎的出现了。

感觉中文输入法没有获得英文输入法一样的识别状态特权……

**Comment by lotem** [comment]
不能。輸入法軟件里不存在「非輸入狀態」。操作系統調用輸入法就是爲了將按鍵轉換爲輸入法所支持的文字。
所謂「非輸入狀態」的判斷應當由應用軟件和操作系統完成。因爲只有應用軟件自身才知道軟件當前應用場景下是否需要輸入文字，從而告知操作系統啓用或禁用輸入法。
然而許多軟件的設計並未考慮與輸入法兼容。操作系統也並未將與輸入法的交互作爲應用程序開發必須的一環。你可以理解爲這些軟件不兼容中文輸入法。
