### ISSUE TITLE
某些App下Enter动作异常? 

### ISSUE THREAD

**Issue by nutnutwin** [rime/weasel#490]
# 使用版本
  0.14.3
  Windows 10 1809
# 现象
  某些App 下输入Enter会产生奇怪的效果
  比如现在在用的DoubleCommander(文件管理器)里输入Enter后会出现｢选择了整个字符串｣的现象, 好像是按了Ctrl+A一样

  其他一些输入法(GooglePinyin, Microsoft Pinyin, 以及日文的GoogleIME)都不会发生问题

# 具体现象
## 小狼毫
- 小狼毫输入前
<img width="308" alt="Weasel1_输入前" src="https://user-images.githubusercontent.com/34512273/77818551-ae8e4500-7116-11ea-923d-83852fd063ab.png">

- 小狼毫输入中
<img width="191" alt="Weasel2_输入中" src="https://user-images.githubusercontent.com/34512273/77818557-b948da00-7116-11ea-8158-654a459e4302.png">

- 小狼毫敲回车
<img width="169" alt="Weasel3_敲回车" src="https://user-images.githubusercontent.com/34512273/77818561-c06fe800-7116-11ea-89e7-77bfd795ebd0.png">
↑光标位置不明, 好像按Ctrl+A选中了所有文字, DoubleCommander并未做任何设置修改
※因为词库里没有自己要的词, 所以选择了敲回车, 平时也用中文模式输入英语

## GoogleIME(日语, 其他输入法也类似)

- GoogleIME输入前
<img width="160" alt="J1_输入前" src="https://user-images.githubusercontent.com/34512273/77818545-9f0efc00-7116-11ea-8fa2-2283d833bb13.png">

- GoogleIME输入中
<img width="258" alt="J2_输入中" src="https://user-images.githubusercontent.com/34512273/77818588-f6ad6780-7116-11ea-964a-49aaabac9e63.png">

- GoogleIME敲回车(光标出现在最后输入的｢てすと｣之后)
<img width="185" alt="J3_敲回车" src="https://user-images.githubusercontent.com/34512273/77818594-00cf6600-7117-11ea-8d02-79860b56fb1b.png">

请问这是什么原理呢? 能否改yaml来修正? 

比如重新Enter时候的动作? 

感谢制作/维护小狼毫, 我的｢custom_phrase.txt｣里有20,000个词汇, 真的很方便, 谢谢
不好意思拿第三方的软件来麻烦大家

**Comment by lotem** [comment]
沒有設計這樣的動作。應該是前端（TSF）的BUG。
由於TSF的接口比較複雜，兼有和特定應用軟件的交互，這類問題需要Windows編程高手來研究。

**Comment by nutnutwin** [comment]
好的谢谢
我现在Workaround 了
麻烦你
我Close 这个issue

**Comment by nutnutwin** [comment]
后续: 改用了XYplorer
