### ISSUE TITLE
关于使用 Caps Lock 清屏的问题

### ISSUE THREAD

**Issue by cubercsl** [rime/weasel#491]
设置了`key_binder` 的 `bindings` ：`- {accept: "Caps_Lock", send: Escape, when: composing} `
这样设置以后，在中文输入时使用 `CAPS_LOCK` 可以清屏，但同时也切换成了大写。

**Comment by fxliang** [comment]
这个是正常行为，因为小狼毫/Rime后端并没有吃掉这个系统按键
