### ISSUE TITLE
Weasel 98-Wubi 'z' function key

### ISSUE THREAD

**Issue by WingDust** [rime/weasel#492]
i am js deveploper , not good at C++ ,I am use weasel 98-Wubi . it's `z` can be a function key , I always use Atom . Can you set `z` for back to last times input status ? 
for example
i want to input a word `五笔` but i realize i input a wrong word . So i press `z` to get `五笔` back and cursor back to original location
Why i suggest it
1. if have such as back word this key ,can estremely improve need to change input wrong word 's efficiency 
2. Weasel and Atom has a input problem although i don't where is probem , it can improve this 

**the best of both worlds**

if can improve ,Thank you for work.

**Comment by Ace-Who** [comment]
既然没有正确输入过「五笔」，何谈 get back？难道是指撤销上次输入？何不使用系统的撤销功能及其快捷键？同 https://github.com/rime/weasel/issues/465
