### ISSUE TITLE
有沒有辦法在電腦上安裝兩箇RIME

### ISSUE THREAD

**Issue by Reniastyc** [rime/weasel#496]
問題是這樣的，RIME有一箇能夠切換安裝爲「簡體中文輸入法」和「繁體中文輸入法」的選項，但在使用Word的時候，輸入法設置爲簡體時無法正常使用繁中字體，設置爲繁體時則無法正常使用簡中字體
那麼能不能裝兩箇RIME分別對應於簡中輸入法和繁中輸入法呢？

**Comment by lotem** [comment]
理論上可以。但安裝程序沒有提供這樣的選項。因爲這樣用起來也很麻煩，大多數用家不需要這樣做。
這個問題出在個別應用軟件根據輸入語言自動設定文字的字體屬性。輸入法本身是和字體無關的。如果能從應用軟件入手，研究能否關閉該應用按語言選擇字體的機制，會是最理想的解法。

**Comment by Reniastyc** [comment]
好的，瞭解了。
多謝。
