### ISSUE TITLE
部署行爲異常

### ISSUE THREAD

**Issue by IceCodeNew** [rime/weasel#497]
使用的是測試版的 weasel（0.14.3.148＠Nov 29, 2019），同時安裝了語言模型數據包。
異常行爲指的是我看到用戶文件夾下的 build 目錄內生成的`luna_pinyin.schema.yaml`文件裏，少了我在自定義配置文件裏定義的項目。
我在測試時是先把整個目錄徹底刪除，然後再運行部署命令的，具體差異如下：

![圖片](https://user-images.githubusercontent.com/32576256/79465606-28d32a80-802e-11ea-9f4d-a2cc11b58dbc.png)

**Comment by IceCodeNew** [comment]
![image](https://user-images.githubusercontent.com/32576256/79468871-0fcc7880-8032-11ea-9233-581f57c97528.png)

左边是自定义配置，右侧是部署生成出来的 schema 方案文件，可以看到就只少了模糊音的配置……这点很奇怪。

**Comment by IceCodeNew** [comment]
但是并不是说部署生成的方案文件里就没有一点自定义配置的内容了，奇怪就奇怪在诸如
`patch:"menu/page_size": 9`
`patch:"custom_phrase/user_dict": custom_phrase`
这些都可以在部署后生成的文件里找到：

![image](https://user-images.githubusercontent.com/32576256/79469519-da745a80-8032-11ea-99f8-9d9f3e10f619.png)

**Comment by IceCodeNew** [comment]
最初提 issue 时写的自定义配置文件是这样的，欢迎拍砖：https://pastebin.com/rtbk2ZEV
我后来又仔细读了遍 [wiki](https://github.com/rime/home/wiki/Configuration)，觉得原来自定义配置里面又有 `__patch:`根节点，又有 `patch:` 根节点，可能不太好——所以我先是通过 plum 把明月拼音方案文件更新（重置）成了原版的模样，然后再在方案文件的开头手动添加了如下内容：
```
__patch:
  __include: grammar:/hant
# Rx: emoji:customize:schema {
  - patch/+:
      __include: emoji_suggestion:/patch
# }
# Rx: BlindingDark/rime-easy-en:customize:schema {
  - patch/+:
      __include: easy_en:/patch
# }
  - luna_pinyin.custom:/patch?
```
这样一来，方案文件中只有 `__patch:`根节点，然后理论上它应该会跑去我的自定义配置文件里拉取其中 `patch:` 根节点的内容。
事实上我确实看到模糊音配置重新在部署后的文件中出现了，初始的问题得以解决。

---
**现在我的疑惑是，为何在生成的明月拼音方案文件里，搜索 `easy_en`、`emoji`、`grammar` 关键词都搜索不到结果？**
我的感觉就像是 __patch 节点下的内容并没有生效，无论是从生成的方案文件内容上来说，还是输入同样的拼音观察候选词是否符合加载了语法配置文件、easy_en 方案后的应有的效果。

**Comment by IceCodeNew** [comment]
https://pastebin.com/r12kN7X4

反覆實驗後終於改出了一個可以正常工作的版本。
幾個心得：
0. [__include 不可連用](https://github.com/rime/librime/issues/318)，這一點如果不是對 YAML 語法瞭然於心，那真的是很容易踩坑啊，不過 [官方wiki](https://github.com/rime/home/wiki/Configuration) 對這點也有說明，遇到問題的時候多看幾遍。我因爲過了平時睡覺的時間所以智商開始下線了，要不是開頭這篇 issue 我還真想不到這個問題。
1. 我曾在自定義配置文件中寫了下面這段話：
```YAML
patch:
  __include: "luna_pinyin.include:/"
```
然後在 `luna_pinyin.include.yaml` 文件裏這樣寫：
```YAML
__patch:
  - emoji_suggestion:/patch
  - easy_en:/patch
  - grammar:/hant
```
結果發現雖然部署能正常產生 `.bin` 之類的相關文件，但使用輸入法時卻不能打出漢字，按 f4 發現菜單裏朙月拼音變成了 luna_pinyin。我現在也理不清楚爲什麼會發生這種事，但我最後的解決方案就是把 include 文件刪掉，然後把 `emoji_suggestion:/patch`、`easy_en:/patch` 下的內容直接粘貼進自定義配置文件就可以了。
我覺得這個可能和 `__include: "{filename}:/"` 這裏用到的根目錄 `/` 有關係，應該是 import 的節點位置不對。

但是總之直接貼進自定義配置文件壞處也不大，最初寫成 `__include: "{filename}:/patch"` 也只是因爲我用 `plum` 安裝配方時自動生成了這樣的內容而已。
但其實大家可以看出，`plum` 在安裝配方的時候並沒有考慮如果用戶給一個輸入法（朙月拼音）上面掛了多個其他配方的話會怎麼樣（比如像我一樣同時掛 `easy_en` 和 `emoji_suggestion`）
——這就是我要說的第三點了，如果你要掛很多個配方來自定義你的輸入法，然後又不是對 YAML 語法摸得底透，最好是避開用 `__include` 而是直接將 patch 內容貼進自定義配置（儘管這麼做會讓你的自定義配置顯得非常亢長，如果你掛的配方太多的話。

**Comment by lotem** [comment]
> 最初提 issue 时写的自定义配置文件是这样的，欢迎拍砖：https://pastebin.com/rtbk2ZEV
> 我后来又仔细读了遍 [wiki](https://github.com/rime/home/wiki/Configuration)，觉得原来自定义配置里面又有 `__patch:`根节点，又有 `patch:` 根节点，可能不太好——所以我先是通过 plum 把明月拼音方案文件更新（重置）成了原版的模样，然后再在方案文件的开头手动添加了如下内容：
> 
> ```
> __patch:
>   __include: grammar:/hant
> # Rx: emoji:customize:schema {
>   - patch/+:
>       __include: emoji_suggestion:/patch
> # }
> # Rx: BlindingDark/rime-easy-en:customize:schema {
>   - patch/+:
>       __include: easy_en:/patch
> # }
>   - luna_pinyin.custom:/patch?
> ```
> 
> 这样一来，方案文件中只有 `__patch:`根节点，然后理论上它应该会跑去我的自定义配置文件里拉取其中 `patch:` 根节点的内容。
> 事实上我确实看到模糊音配置重新在部署后的文件中出现了，初始的问题得以解决。
> 
> **现在我的疑惑是，为何在生成的明月拼音方案文件里，搜索 `easy_en`、`emoji`、`grammar` 关键词都搜索不到结果？**
> 我的感觉就像是 __patch 节点下的内容并没有生效，无论是从生成的方案文件内容上来说，还是输入同样的拼音观察候选词是否符合加载了语法配置文件、easy_en 方案后的应有的效果。

有关 `grammar` 配置不正确。详见手工配置的示例：

https://github.com/lotem/rime-octagram-data#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

或者用 rime-install 脚本安装配方，也可以正确配置。
https://github.com/lotem/rime-octagram-data#%E9%80%9A%E9%81%8E%E9%85%8D%E7%BD%AE%E7%AE%A1%E7%90%86%E5%99%A8%E5%AE%89%E8%A3%9D

plum 支持安装多个配方，除非配方里自定义配置的内容互相冲突。

**Comment by IceCodeNew** [comment]
> 
> 有关 `grammar` 配置不正确。详见手工配置的示例：
> 
> [lotem/rime-octagram-data#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6](https://github.com/lotem/rime-octagram-data#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)
> 
> 或者用 rime-install 脚本安装配方，也可以正确配置。
> [lotem/rime-octagram-data#%E9%80%9A%E9%81%8E%E9%85%8D%E7%BD%AE%E7%AE%A1%E7%90%86%E5%99%A8%E5%AE%89%E8%A3%9D](https://github.com/lotem/rime-octagram-data#%E9%80%9A%E9%81%8E%E9%85%8D%E7%BD%AE%E7%AE%A1%E7%90%86%E5%99%A8%E5%AE%89%E8%A3%9D)
> 
> plum 支持安装多个配方，除非配方里自定义配置的内容互相冲突。

我最初就是通过 rime-install 脚本安装配方的，可以看到自定义配置被改成了：
```json
Rx: emoji:customize:schema {
- patch/+:
    __include: emoji_suggestion:/patch
}
Rx: BlindingDark/rime-easy-en:customize:schema {
- patch/+:
    __include: easy_en:/patch
}
```

这样连用多个 include 导致了自动配置的配方失效。

**Comment by lotem** [comment]
> ```yaml
> # Rx: emoji:customize:schema {
> - patch/+:
>     __include: emoji_suggestion:/patch
> # }
> # Rx: BlindingDark/rime-easy-en:customize:schema {
> - patch/+:
>     __include: easy_en:/patch
> # }
> ```
> 
> 这样连用多个 include 导致了自动配置的配方失效。

這段代碼裏 `__incliude` 沒有連用，每個`__include`作用於一個不同的 `patch/+` 節點。
