### ISSUE TITLE
Windows10 Version1903 下出现无法自动调频和记录用户短语问题

### ISSUE THREAD

**Issue by ArtrixTech** [rime/weasel#498]
![GIF 4-17-2020 10-36-45 AM](https://user-images.githubusercontent.com/25822991/79530590-52c63480-80a2-11ea-9352-d1b71bbd7c91.gif)
如图，始终无法记录用户短语。

怀疑过是UAC导致db无法读取，尝试给予WeaselServer.exe管理员权限，重新部署后有效，但是在使用过程中依然无法自动调频，重新部署后效果才会出现。

尝试卸载后清空用户文件夹，重启重新安装Weasel，无效。

附件是最近一次重载的Log ->
[rime.weasel.DESKTOP-ICMSDSC.Artri.log.INFO.20200417-112723.log](https://github.com/rime/weasel/files/4490839/rime.weasel.DESKTOP-ICMSDSC.Artri.log.INFO.20200417-112723.log)

**Comment by lotem** [comment]
参考 https://github.com/rime/home/issues/128
