### ISSUE TITLE
Rime在VS2015中输入法窗口始终在左上角

### ISSUE THREAD

**Issue by LazierCode** [rime/weasel#50]
对于开源的rime,在windows上最强大的IDE中简直是耻辱,希望尽快修复.

**Comment by osfans** [comment]
應該不修復了，有新產品rime-gits了。

**Comment by Prcuvu** [comment]
参见公告：[小狼毫前端的兼容性問題將不再修復] (https://github.com/rime/home/issues/25)

**Comment by Prcuvu** [comment]
目前看来，IME版本确实有光标不跟随的问题，TSF没有。

**Comment by uname2p** [comment]
@Prcuvu TSF在Win7 SP1打上几百个安全补丁之后会导致其他进程内存占用飙升，亲测Chrome，uTox先后挂掉，uTox本来只需要30M的内存就可以跑起来，一旦开启TSF，在软件里面输入汉字聊天的时候，不出一个小时，内存由30M上升的占用8G（我电脑有大内存），一个进程占用8G内存太恐怖了，Chrome的进程也会发生类似的问题，怀疑开启TSF后存在某种内存溢出的问题

**Comment by lotem** [comment]
言重了。Windows 上最強大的 IDE，比記事本 BUG 還多，吾深以爲恥。
Windows 衆請加油 :P 揮發強大 IDE 的一點點能力貢獻開源代碼。

**Comment by nameoverflow** [comment]
据我所知 VS 2015 本身不支持 TSF 和 IME 的定位……

VS 2017 就没有问题。
