### ISSUE TITLE
VS2013编译不过。

### ISSUE THREAD

**Issue by wpchenit** [rime/weasel#503]
环境vs2013 debug 32位，
boost_1_66_0,
编译WeaselTSF和WeaselIME报错。 信息为：
![image](https://user-images.githubusercontent.com/64248379/80184174-aa354900-863c-11ea-8812-26b3af9565ae.png)

**Comment by lotem** [comment]
請參考
https://github.com/rime/weasel/blob/master/INSTALL.md
