### ISSUE TITLE
使用 Sandboxie下的程式不能輸入中文

### ISSUE THREAD

**Issue by cj900** [rime/weasel#506]
使用 Sandboxie打開的程式，輸入法顯示中文模式，但只能打出英文

windows 10 1909   64bit
sabdboxie 5.30   64bit

**Comment by lotem** [comment]
符合设计。沙盒软件用于隔离应用程序，因此无法与沙盒外的输入法程序通信。

**Comment by Prcuvu** [comment]
Duplicate of #143
