### ISSUE TITLE
idea 按下 alt + insert 的快捷键后，小狼毫自动从英文切换到中文

### ISSUE THREAD

**Issue by wanglongbiao** [rime/weasel#507]
我是 win7 环境，在默认英文输入的状态下，idea 按下 alt + insert 的快捷键后，小狼毫自动从英文切换到中文。
还有一个问题，在 idea 点一下右键，然后按一下换行，也会从英文切换到中文。

---- 
我刚刚又试了下，好像只要弹出这个菜单，就会切换到中文，无论是右键，还是别的提示
![微信截图_20200428171615](https://user-images.githubusercontent.com/7327187/80469722-8abb5a80-8973-11ea-8832-e5917abbf842.png)

---

两台 win7 上都有这个问题，但 win10 好像没问题
idea 的弹框好像触发了 rime 的切换到中文的快捷键或命令，因为每次在 idea 按下 `alt + insert` 的时候，在松开 alt 后，能看到右下角这个切换到中文的状态。
![image](https://user-images.githubusercontent.com/7327187/80552117-39a17a00-89f8-11ea-83f0-fe14e7905f3e.png)

**Comment by JiangtaoTian** [comment]
alt+Enter也有同样的问题,暂时无法得知如何触发了中英文切换,望告知

**Comment by teekcode** [comment]
alt+Enter同有问题，会导致中英文切换

**Comment by wanglongbiao** [comment]
> 好像是idea的弹窗会导致中英文切换。比如右击的弹窗，alt+enter的弹窗，alt+insert的弹窗。甚至是智能提示补全的弹窗。

的确，这个应该是和 idea 冲突了。

**Comment by wanglongbiao** [comment]
这个方法可以避免这个问题：平时默认英文键盘，只用 rime 作为中文输入法。

**Comment by teekcode** [comment]
> 这个方法可以避免这个问题：平时默认英文键盘，只用 rime 作为中文输入法。

确实我也搞成这样了。
