### ISSUE TITLE
Win10 1909+Weasel.0.14.3+word2019打字闪烁

### ISSUE THREAD

**Issue by realasking** [rime/weasel#509]
之前在Win10 1903+Weaseal 0.14.2+word2016上也遇到过，当时按#228 的方法解决，
但是Win10 1909+Weasel.0.14.3+word2019中这么做了之后有时还是会遇到，必须关闭word重开才行。
昨天和人聊天，被告知他没有遇到，他不记得下载地址了，但把他的安装文件拷贝给我，卸载原来的重装此版后用到今天都没有出毛病，感觉好像是解决了。我看这个版本是0.14.3.148，但从release里下载的是0.14.3.0，那个版本应该是在哪里下载的？新版本今后该在哪里下载？

**Comment by Eason0210** [comment]
我这边在开启`  "style/inline_preedit": true # 嵌入式候选窗单行显示` 的时候也是会在Word中出现闪烁，但在excel正常。
请问下您的问题的解决了吗？

**Comment by realasking** [comment]
已经是用的148了，但昨天更新windows10 20TH2后又出现闪烁问题，已知办法都尝试了，还是无效，暂时卸载小狼毫了。祝好。

**Comment by realasking** [comment]
最近找到了一个PIME，也包括了RIME，用了几天，似乎没有打字闪烁和掉服务的问题，不过输入框要丑很多，这项目也在github上，有感兴趣的可以试试。
