### ISSUE TITLE
请问一下，可否实现如下功能？

### ISSUE THREAD

**Issue by iDragonfly2050** [rime/weasel#51]
1.按下Esc键时，中文状态下切换为英文状态，英文状态下的话就保留原状。
因为我用vim写代码的时候，插入模式下的写入中文注释，再按Esc时转换为普通模式，希望这个时候时处于英文状态下。

2.设置Ctrl+i为中英文互换，Shift和Ctrl不进行切换。
因为这两个键在写代码的时候经常用，很容易不小心按成中文状态下输入了。

**Comment by lotem** [comment]
目前需要修改程序才能实现所求。
在 gvim 里，会在 ESC 键之后切换到英文。终端里不会。

**Comment by lotem** [comment]
Shift 作切换键可以禁用掉，然后用 Control+` 进菜单选，或 Control+Shift+2。这个快捷键能改的。

**Comment by 1099965906** [comment]
Thanks.
希望能直接改配置文件实现这个需求，win下的gvim似乎也不会切换为英文。我是用VS2015装vim插件用的。
Thanks again!

**Comment by 1099965906** [comment]
对了，虽然可以用Ctrl+Shift+2切换，但是似乎又导致无法选择inline_ascii或commit_text的方式切换。

**Comment by lotem** [comment]
同 https://github.com/rime/weasel/issues/51
