### ISSUE TITLE
”卡巴斯基漏洞扫描“检测rime（PC）存在High等级的漏洞，希望开发者辛苦修复一下，谢谢

### ISSUE THREAD

**Issue by t-xw** [rime/weasel#512]
https://threats.kaspersky.com/en/vulnerability/KLA11240/ ，这个是卡巴斯基报告的网址，是一些详细信息介绍，希望有用，谢谢开发者提供这么绿色简单的输入法，期待不断完善

**Comment by Sandothers** [comment]
看起来是7zip的相关漏洞
