### ISSUE TITLE
 托盘上输入法显示状态错误。

### ISSUE THREAD

**Issue by yu-soong** [rime/weasel#514]
中文状态下，`WIN+空格`，将输入法切换到英文时（US keyboard），托盘上显示状态是“中”字，而不是“A”。
![image](https://user-images.githubusercontent.com/43726125/82132828-37a32d80-97e4-11ea-85f3-e1aa5af73e2b.png)

**Comment by lotem** [comment]
不推薦再用托盤圖標。
輸入法激活時的語言欄圖標已基本覆蓋了舊有托盤圖標的功能，而當切換到其他輸入法／鍵盤時語言欄圖標會自動消失。而托盤圖標無法用來反映另一個輸入法（英文鍵盤）的狀態。

**Comment by yu-soong** [comment]
> 不推薦再用托盤圖標。
> 輸入法激活時的語言欄圖標已基本覆蓋了舊有托盤圖標的功能，而當切換到其他輸入法／鍵盤時語言欄圖標會自動消失。而托盤圖標無法用來反映另一個輸入法（英文鍵盤）的狀態。

谢谢回复!@lotem!
“當切換到其他輸入法／鍵盤時語言欄圖標會自動消失” 这个“自動消失”很麻烦。因为切换到US keyboard的时候，“语言栏图标自動消失”会使得托盘图标动来动去。右键选择托盘某个图标时，有时候动来动去的就选不准了。
所以我理想中的状态是：要么，切换到US keyboard的时候不消失（好像有点太霸道了）；要么，保留语言栏图标，但是切换到US keyboard的时候提醒我是EN或换一个图标以示区别。
不知道这个实现起来是不是有点很难。谢谢!

**Comment by yu-soong** [comment]
我可能没表述清楚。因为rime有两个图标，US keyboard只有一个图标，所以切换时会导致右下角托盘区移动。
所以第三个方案是，能不能选择关闭掉rime的图标？

**Comment by lotem** [comment]
不知原題中的「托盘」是不是確指「System tray」，姑且認爲配圖上的是舊有的托盤圖標吧，看着像。
語言欄是另外一個系統界面元素，與系統托盤圖標有別，是一組由當前選中的輸入法指定要系統顯示的按鈕，因此切換到「英文鍵盤」時，理論上語言欄會顯示「英文鍵盤」的語言欄按鈕，而他僅僅是一個鍵盤佈局，並沒有任何狀態圖標／按鈕。而小狼毫因爲不再是活動的輸入法，其語言欄按鈕也不再被系統顯示。這個不是輸入法能控制的。

**Comment by yu-soong** [comment]
谢谢您的快速回复。是「System tray」。
所以，现在的解决方案是，可以可以选择关闭小狼毫的标。下图，右边的标。这样的话切换到 [英文键盘] 时以点击「System tray」就不会引起 「System tray」的图标左右移动了。
![image](https://user-images.githubusercontent.com/43726125/82154099-02dab900-986c-11ea-8456-faf5bb472599.png)

**Comment by elxy** [comment]
这个问题确实很烦：![小狼毫](https://github.com/rime/weasel/assets/4527440/fc1f6924-ff84-4373-8bba-e050a7e44fb0)

**Comment by byzod** [comment]
一个妥协方案：允许隐藏输入法图标（中），只显示语言图标（㞢）

「中」的左右键操作完全通过开始菜单进行
