### ISSUE TITLE
请求增加英文输入自动加空格的功能

### ISSUE THREAD

**Issue by pengruifei** [rime/weasel#515]
与中文不同，英文的每个单词之间都需要加空格，请求将这项功能加上：
- 空格选词自动加空格
- 数字键选词自动加空格

**Comment by yu-soong** [comment]
我曾经把 easy_EN 字典库里的每个词都加上一个空格。这样打出来的英文单词就是有空格的了。字典文件单词自动加空格不难，很多语言可以做 比如Linux bash等。

**Comment by fxliang** [comment]
这个更多是后端关联内容，如你所描述的需求应该是有英文输入方案，潜在解决方案应该是方案里加载预期的lua processor之类的处理，或者其translator处理，望知悉。
