### ISSUE TITLE
在 Firefox 的设置的搜索框里，无法输入中文

### ISSUE THREAD

**Issue by Kennnnnnji** [rime/weasel#518]
[UTOOLS1590121826999.png](http://yanxuan.nosdn.127.net/49665d0fe0edd71df27e0b1d44b09660.png)
如上图，在这一搜索框中，无法直接输入中文，但是可以输入英文。另外，在输入一段英文后，又可以继续输入中文。
[UTOOLS1590121947273.png](http://yanxuan.nosdn.127.net/20e6c28b7896db86898b8daf7cc2d291.png)
应用版本：
Firefox 76.0.1 (64 位)
Rime weasel 0.14.3
Windows 10 1909 (Home)

**Comment by tangdou1** [comment]
我也是这样的情况，有时是在libreoffice中突然不能输入中文了，重新部署输入法又可以了。

**Comment by Y-Shy** [comment]
发现同样问题，无法在Firefox选项的搜索框中输入中文。版本：
* Firefox 83.0
* Rime weasel 0.14.3, luna_pinyin_simp
* Win10 LTSC

**Comment by fxliang** [comment]
fixed by #1122
