### ISSUE TITLE
隐藏中英切换的图标提示

### ISSUE THREAD

**Issue by yu-soong** [rime/weasel#520]
我有一个很奇葩的要求，就是切换中英文时，不想要光标下方的中英文输入状态提示。就是大概闪现两秒钟的红色的 [A」，黑色的 [中] 提示框。

![image](https://user-images.githubusercontent.com/43726125/82682600-d0580400-9c4f-11ea-9ee0-f51ac4f7bf36.png)

我这个要求很奇葩，因为我自己自定义了一个特殊的输入法切换方案，并自己做了一个简单的提示框。这个提示框就有点冲突了，经常闪我一下子。

不知道可不可以取消。当然如果可以自定义提示框的位置就更好了。谢谢！

**Comment by sih4sing5hong5** [comment]
You can modify [this code](https://github.com/rime/weasel/blob/master/RimeWithWeasel/RimeWithWeasel.cpp#L404-L407)

**Comment by yu-soong** [comment]
Thanks a lot!

Yu Song

________________________________

**Comment by nzooherd** [comment]
> Thanks a lot!

您好，请问你是改源码后自己编译了一个吗。

**Comment by ifhjl** [comment]
请问应该怎么修改呢,我不太懂这个,求大佬指点

**Comment by ysy** [comment]
参考[这个问题 ](https://github.com/rime/weasel/issues/698#issuecomment-3372173195)，

在 weasel.custom.yaml 里加一段配置：
```yaml
patch:
  show_notifications: false
  show_notifications_time: 1200
```
就可以了。也可以用 show_notifications_time 设定显示的时间。
