### ISSUE TITLE
请问control+shift+enter的CommitComment()是什么功能呢？

### ISSUE THREAD

**Issue by yys-github** [rime/weasel#522]
void Editor::CommitComment(Context* ctx) {
  if (auto cand = ctx->GetSelectedCandidate()) {
    if (!cand->comment().empty()) {
      **engine_->sink()(cand->comment());**
      ctx->Clear();
    }
  }
}
上面sink comment一句似乎是把候选词发到了一个什么listener去。但是因为没有调试环境，想再进一步地理解sink()是什么就很困难了……
关于control+shift+enter的功能，或是CommitComment()这段代码的理解，请不吝赐教，谢谢~

**Comment by yys-github** [comment]
在源码和yaml里搜了一圈都没看到commit comment的用法，在我的luna_pinyin下敲也没有任何反应。
但是两个if应该是都成立了的，所以enigne_->sink()(...)似乎的确对我进行了某些操作，但究竟是什么呢？好奇（不安）中……

**Comment by Ace-Who** [comment]
上屏注释（有注释时）。

**Comment by yys-github** [comment]
> 上屏注释（有注释时）。

看来没反应是因为我没有注释大概……（捂脸）
感谢解惑~

**Comment by lotem** [comment]
shi

**Comment by lotem** [comment]
是誰設計的這個功能，用在什麼地方？
