### ISSUE TITLE
大佬，小狼毫输入法， 已经好几个月都没有更新了

### ISSUE THREAD

**Issue by ghost** [rime/weasel#523]
@lotem 感谢大佬给我们带来这么好用的输入法。 但是，看起来， 好几个月都没有更新了。 
啥时候会更新最新版本的输入法呢？

**Comment by lotem** [comment]
要等選好執鍵人

**Comment by weidongzhou1994** [comment]
一直在维护中，什么时候能好啊

**Comment by zjsailor** [comment]
不更新才是这款输入法最大的优点，当然前提是没有bug。如果有bug，还是希望修复。
