### ISSUE TITLE
输入法列表出现了2个小狼毫

### ISSUE THREAD

**Issue by Kennnnnnji** [rime/weasel#524]
System OS：Win10 2004
weasel：最新版
![image](https://user-images.githubusercontent.com/34367558/84055163-071b7180-a9e7-11ea-8e47-57974df13344.png)

**Comment by cpc1854** [comment]
我也有相同問題。

**Comment by cpc1854** [comment]
我在window內language, 中文(臺灣)語言刪除後，再重新執行小狼毫安裝選項後，就正常了，只出現一個輸入法表列。

**Comment by determ1ne** [comment]
Closed as stale, reopen it if the problem still exists.
