### ISSUE TITLE
给不同小狼毫输入方案添加不同的托盘图标

### ISSUE THREAD

**Issue by thudjx** [rime/weasel#527]
我自己尝试构造了一个输入法用来方便输入英文和unicode字符，但是方案的托盘图标始终只有“中”，不是很舒服。官方的说明里也没有提到这一点，网上也没有找到相关的问题。但是我觉得给不同的方案添加不同的托盘图标是个不错的主意，这应该是可定制的很棒的一方面。不知道诸位开发大佬有没有想过这个问题呢。

**Comment by thudjx** [comment]
> ibus-rime 已有這項功能，取輸入方案的第一個字用來顯示中文輸入的狀態。
> 
> 小狼毫裏托盤圖標（tray icon）的功能已經廢棄了，取代以語言欄圖標。
> 這裏需要一個真的圖標而不是顯示文字，對方案作者來說製作成本稍高一些。

抱歉，没理解你说的“托盘图标”和“语言栏图标”是什么，分别是下图中的“中”字和“ㄓ”字图标吗。我其实就是想更改“中”字图标（我理解的托盘图标）。另外，你说的“真的图标”是一个.icon文件吗，感觉成本并不高啊QAQ
![image](https://user-images.githubusercontent.com/32637321/84985044-9dc9fa00-b16e-11ea-9b8e-2a24122ff7bb.png)

**Comment by lotem** [comment]
系统托盘和語言欄是不同的操作系統界面。系統托盤區可供任何應用程序添加一個長駐的可以與用戶交互的圖標，語言欄是系統顯示由當前活動輸入法提供的狀態按鈕的區域。

成本高低是相對於美工技能和添加這項功能的意願來說的。對大部分輸入方案開發者來說這會是一項額外的成本。不妨先由有需求又有製作能力的用家做起來、用起來。

**Comment by cabins** [comment]
感觉我也很需要这个功能。我同时在使用小鹤双拼，小鹤音形，五笔86，经常不知道当前激活的是那个方案。

**Comment by yu-soong** [comment]
Mark 一下，希望在小狼毫和鼠鬚管上也能尽快实现

**Comment by fxliang** [comment]
如您在用Windows 8.1 或更高版本系统，新发布的0.15.0已支持该特性

**Comment by plainee** [comment]
Mark 一下，希望在小狼毫上也能尽快实现

**Comment by 132123wddw** [comment]
请问怎么把上面的评论中提到的"中"字图标关闭使其不显示呢

**Comment by CDOccc** [comment]
> 请问怎么把上面的评论中提到的"中"字图标关闭使其不显示呢

我目前也正在找，小狼豪的图标我能接受 但是那个 “中” “A” 真的太丑了，我现在在找怎么把这两图标替换掉或者隐藏掉

**Comment by Master5hen9** [comment]
https://www.bilibili.com/video/BV1u94y1i72L/?spm_id_from=333.337.search-card.all.click&vd_source=98edabad74dc75ecd89c76a8ab92254b 这个 视频中有说



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2026年02月25日 08:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [rime/weasel] 给不同小狼毫输入方案添加不同的托盘图标 (#527) |
CDOccc left a comment (rime/weasel#527)

请问怎么把上面的评论中提到的"中"字图标关闭使其不显示呢

我目前也正在找，小狼豪的图标我能接受 但是那个 “中” “A” 真的太丑了，我现在在找怎么把这两图标替换掉或者隐藏掉
