### ISSUE TITLE
小狼毫 0.14.3.148 测试版，在 win10 下依然无法识别调用 KP_Enter 按键，且在 Word 里一闪一闪的

### ISSUE THREAD

**Issue by YQ-YSY** [rime/weasel#528]
小狼毫 0.14.3.148 测试版，在 win10 下依然无法识别调用 KP_Enter 按键，且在 Word 里一闪一闪的，通常是第一次调用时看似正常，切换几次窗口后，再回到 Word 里打字，浮动的候选栏就好像被隐藏（掩盖）在 Word 下面看不见，只有打字按一下建的时候才闪现一下，然后又马上不见……

我的“单手笔顺输入法”正在对编码和词库进行修缮、精编和调整，计划几周后发布 2.0 版，也希望小狼毫能越来越好用。

**Comment by siuze** [comment]
至今尚未修复 #538

**Comment by YQ-YSY** [comment]
诱发Rime在Word中闪烁的条件（故障可重现）以及临时解决方法

很多朋友都遇到了Rime输入法在word中闪烁，难以使用的问题。
我的电脑是：Win10系统，Office 2019，小狼毫weasel-0.14.3.0
经过多尝试和试验，终于发现诱发闪烁的条件（故障可重现）：关键是在Word的“标尺”上，

当我用鼠标拖动“标尺”下方的“小四方形（左缩进）”或者“向上小三角形（悬挂缩进）”几次后，用Rime打字就会闪烁。
临时的解决方法是：把鼠标放在标尺上，就能正常打字，不闪烁了。但是，如果鼠标从标尺上移开，打字又会闪烁。

所以记住，如果要在Word标尺上操作，就先切换为其他输入法，不用Rime。
如果不小心操作了Word标尺，已经造成Rime闪烁了，那么把鼠标放在标尺上，就能继续打字了。
应急打完字后，保存文件，关闭Word，再重新打开，Rime才恢复正常。目前就只能这样了。

——以上信息提供给Rime的开发者，希望能对修改调试程序有帮助。

**Comment by 34292885** [comment]
#930 KP_Enter
