### ISSUE TITLE
最近经常出现卡死现象

### ISSUE THREAD

**Issue by toiiggww** [rime/weasel#53]
动图：http://ww2.sinaimg.cn/large/3d262bb6gw1f24jq98i19g20ey03w77l.gif

**Comment by Prcuvu** [comment]
参见公告：[小狼毫前端的兼容性問題將不再修復] (https://github.com/rime/home/issues/25)

**Comment by desperadoshi** [comment]
貌似这个链接可以一定程度上解决一些问题[解决Rime在Win10中影响开始菜单的问题](http://www.fonaix.com/905.html)。亲测Win10开始菜单正常了。

**Comment by toiiggww** [comment]
后台服务进程WeaselServer.exe的优先级不够，后端响应不及时，前端卡死
