### ISSUE TITLE
win10 2004 升级5月份后，无法使用

### ISSUE THREAD

**Issue by cntest-oss** [rime/weasel#530]
使用确实是个神品，就是兼容性太差了
ModLoad: 76cd0000 76d57000   C:\WINDOWS\SysWOW64\shcore.dll
ModLoad: 00000000`71d80000 00000000`71da1000   C:\WINDOWS\SysWOW64\SspiCli.dll
ModLoad: 00000000`753c0000 00000000`753cf000   C:\WINDOWS\SysWOW64\kernel.appcore.dll
ModLoad: 00000000`75c00000 00000000`75c5c000   C:\WINDOWS\SysWOW64\bcryptPrimitives.dll
(f8.2c94): C++ EH exception - code e06d7363 (first chance)
ModLoad: 00000000`71d70000 00000000`71d7d000   C:\WINDOWS\SysWOW64\atlthunk.dll
WinSparkle: ----------------------------
WinSparkle: *** USING INSECURE URL: appcast feed from http://rime.github.io/release/weasel/appcast.xml ***
WinSparkle: ----------------------------
ModLoad: 00000000`71b40000 00000000`71d6a000   C:\WINDOWS\SysWOW64\iertutil.dll
ModLoad: 00000000`76cd0000 00000000`76d57000   C:\WINDOWS\SysWOW64\shcore.dll
ModLoad: 00000000`70970000 00000000`70f76000   C:\WINDOWS\SysWOW64\windows.storage.dll
ModLoad: 00000000`71b10000 00000000`71b33000   C:\WINDOWS\SysWOW64\Wldp.dll
ModLoad: 00000000`76d90000 00000000`76dd5000   C:\WINDOWS\SysWOW64\shlwapi.dll
ModLoad: 00000000`71af0000 00000000`71b08000   C:\WINDOWS\SysWOW64\profapi.dll
ModLoad: 00000000`71ad0000 00000000`71ae2000   C:\WINDOWS\SysWOW64\ondemandconnroutehelper.dll
ModLoad: 00000000`71a00000 00000000`71ac2000   C:\WINDOWS\SysWOW64\winhttp.dll
ModLoad: 00000000`719a0000 00000000`719f2000   C:\WINDOWS\SysWOW64\mswsock.dll
ModLoad: 00000000`71960000 00000000`71992000   C:\WINDOWS\SysWOW64\IPHLPAPI.DLL
ModLoad: 00000000`71950000 00000000`71958000   C:\WINDOWS\SysWOW64\WINNSI.DLL
ModLoad: 00000000`76400000 00000000`76407000   C:\WINDOWS\SysWOW64\NSI.dll
ModLoad: 00000000`717a0000 00000000`71948000   C:\WINDOWS\SysWOW64\urlmon.dll
ModLoad: 00000000`708e0000 00000000`70970000   C:\WINDOWS\SysWOW64\DNSAPI.dll
ModLoad: 00000000`708d0000 00000000`708d8000   C:\Windows\SysWOW64\rasadhlp.dll
(f8.2c94): C++ EH exception - code e06d7363 (first chance)
(f8.2c94): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify checksum for WeaselServer.exe

**Comment by francistw** [comment]
我這邊的解決方法是：

1. 將 WeaselServer.exe 設成相容 Windows 8
2. 將 WeaselServer.exe 的捷徑放到 %Appdata%\Microsoft\Windows\Start Menu\Programs\Startup 開機自啟

你看看行不行

**Comment by cntest-oss** [comment]
直接用兼容模式，还是不能用

**Comment by Mister-Kin** [comment]
我的OS是v2004（内部版本 19041.329），一开始刚装小狼毫时可以正常使用无问题，后来突然就遇到大家所说的问题「2004版本下小狼毫无法输入中文」。在多次尝试后，我发现是小狼毫算法服务程序的问题。手动运行算法服务程序后就可以正常使用了。

![图片](https://user-images.githubusercontent.com/34863761/87219522-7db4e180-c38e-11ea-96fa-c8e682b77e24.png)

重启系统，算法服务程序本身可以自启动运行时，但是不能正常工作，需要再次手动运行它才可以。我索性写了个脚本，让脚本自启后自动运行「小狼毫算法服务」程序，类似于@francistw 的做法。目前来说，算是解决这个问题。

@cntest-oss 可以尝试下手动运行「小狼毫算法服务」看看能不能工作（不需要兼容模式win8）

**Comment by cntest-oss** [comment]
我手动运行了一下,输入字母时，没有中文

**Comment by cntest-oss** [comment]
我的OS和你版本一致(OS是v2004内部版本 19041.329)，我的是企业版！

**Comment by Mister-Kin** [comment]
> 
> 
> 我的OS和你版本一致(OS是v2004内部版本 19041.329)，我的是企业版！

@cntest-oss 我的是专业工作站版，但版本区别应该没影响（329 版本已经是 v2004 的 06 累积更新了）。

我在使用「脚本自启算法服务程序」解决「2004 版本下小狼毫无法输入中文」的问题后，偶尔开机后小狼毫还是会抽风（我推测是偶尔开机时脚本程序设置的启动时间早于程序自启时间导致的）。由于我懒得进行相关测试以改进脚本，所以我又尝试了重装小狼毫，发现问题又解决了，一切正常，也不需要二次手动启动算法服务程序了。

你的情况或许该排查下系统问题或者尝试下重装小狼毫。因为，至少在 v2004 版本中，v0.14.3.0 的小狼毫是可以使用的。但不可否认的是，该版本小狼毫在 Win10 OS v2004 中的稳定性不佳。问题诸多，如#530 和 #524。

建议尝试以下方法：
- 使用终端排查并修复系统问题
  - 命令：`sfc /scannow`
  - 命令：`dism /online/cleanup-image /scanhealth` 和 `dism /online/cleanup-image /restorehealth`
- 若上述命令提示无法修复系统时，请使用 [MCT 工具](https://www.microsoft.com/zh-cn/software-download/windows10) 修复系统。
- 重装 v0.14.3.0 的小狼毫。
- 安装小狼毫的测试版（不知道有无改善），下载地址详见 #509。

**Comment by pnqx** [comment]
以管理员身份执行 "C:\Program Files (x86)\Rime\weasel-0.14.3\WeaselServer.exe" 后就行了。
![image](https://user-images.githubusercontent.com/12554018/89637395-af14c480-d8dc-11ea-82b4-865dc8c7fce4.png)

**Comment by q631263135** [comment]
我个人觉得是“管理员运行”的问题，右键属性“以管理员身份运行”，win10上面我碰到多数可能是兼容的问题，都是未勾选管理员运行导致的

**Comment by realasking** [comment]
结合@francistw @Mister-Kin @pnqx 所说的，就是正确的方法了。

经过尝试后，我的处理如下，已经用了一段时间，没再出过毛病：

1. 安装v0.14.3.148的小狼毫

2. 禁用开机启动小狼毫算法服务

3. 新建一个本地的任务计划，名为“小狼毫算法服务正确启动方案”: 

（a）安全选项设置以Administrators运行，并勾选使用最高权限

（b）配置选择Windows Vista, Windows Server 2008

（c）新建触发器，内容为登录时，设置为所有用户，勾选已启用

（d）新建操作“启动程序”，“程序或脚本”填写"C:\Program Files (x86)\Rime\weasel-0.14.3\WeaselServer.exe"

其它选项默认。

4. 重启计算机

5. 计算机重启后会弹出是否自动更新小狼毫的选项，点击否，然后再次重启计算机

之后就一切正常了。

**Comment by lotem** [comment]
> 结合@francistw @Mister-Kin @pnqx 所说的，就是正确的方法了。

恐怕不能說是「正確」方法，也許只是個可行的權宜之計。
以「所有用戶可以訪問」的設置運行算法服務，在多用戶的使用場景下行爲未必正確，還可能存在數據安全問題。
Windows這次升級飽受詬病，還須觀察後續版本能否兼容本品。

**Comment by pessoalzy** [comment]
使用的 Windows 11 更新到 22518.1000 后也出现了这个问题，通过以管理员身份运行 `WeaselServer.exe` 暂时解决了。
