### ISSUE TITLE
弱弱的问下，要看懂引擎以及weasel的代码需要需要学习哪些编程知识？

### ISSUE THREAD

**Issue by shenkuantipang3333** [rime/weasel#54]
比如c++要学到哪些程度？ 哪些不用学？ windows编程要学哪些？哪些不用学？ 还需要学习其他语言么？

**Comment by lotem** [comment]
好奇看代碼的目的。
如果只是要用 Rime 做輸入法，學 YAML、正則表達式和 Rime 文檔就夠了。

---

語言是表達思想的載體。這點和自然語言類似。不好講要哪些程度，比如有些文章每個字都懂、卻未必能理解。語法好學。這是個實用的東西，其程度要用實踐來檢驗：每個字都讀懂了，就學成了。但能從書本學到的到此爲止。剩下的要靠想，字面背後的含義。

Windows 編程，也是實用的東西，不必全部學成再去讀碼寫碼，有啥需求才去看對應文檔。
這些知識對於讀懂代碼是次要的。不學也幾乎不影響理解。
