### ISSUE TITLE
莫名奇妙的会发生 已禁用输入法状态

### ISSUE THREAD

**Issue by hosxy** [rime/weasel#540]
这几天已经发生好多次了，已禁用输入法状态，而且没有办法解除禁用，只能重装解决，我也没搞什么特殊操作，搞不懂究竟是什么原因引起的
win10 自带的微软拼音一切正常，感觉是 weasel 的问题。

![image](https://user-images.githubusercontent.com/17108640/86768379-0b878880-c080-11ea-9c68-48cb6181adaa.png)

OS：Windows10   2004

**Comment by nigel4zh** [comment]
Win7, same problem
![rime_bug](https://user-images.githubusercontent.com/16618947/87115335-7ebe1400-c2a5-11ea-8b58-7ba42eaf4962.png)

**Comment by Mintonmu** [comment]
Manjaro Linux， Same problem

**Comment by edu-future** [comment]
一样的问题，也不知道因为啥

**Comment by DWY-wuyong** [comment]
> 这几天已经发生好多次了，已加入输入法状态，而且没有办法解除替换，只能重装解决，我也没搞什么特殊操作，搞不懂究竟是什么原因引起的
> win10自带的微软拼音一切正常，感觉是weasel的问题。
> 
> ![图片](https://user-images.githubusercontent.com/17108640/86768379-0b878880-c080-11ea-9c68-48cb6181adaa.png)
> 
> 操作系统：Windows10 2004

一样的问题不知道怎么解决

**Comment by weipiaoyun** [comment]
> 这几天已经发生好多次了，已禁用输入法状态，而且没有办法解除禁用，只能重装解决，我也没搞什么特殊操作，搞不懂究竟是什么原因引起的
> win10 自带的微软拼音一切正常，感觉是 weasel 的问题。
> 
> ![image](https://user-images.githubusercontent.com/17108640/86768379-0b878880-c080-11ea-9c68-48cb6181adaa.png)
> 
> OS：Windows10 2004


权限问题，因为你需要编辑的软件是通过管理员权限打开的。把你的小狼毫也设置管理员权限就好了。方法： 右击程序-〉属性-〉兼容性- 〉更改所有用户的设置-〉勾选以管理员身份运行此程序    然后重启电脑

**Comment by DWY-wuyong** [comment]
谢谢你的回复，我现在已经不用小狼毫了，因为我怕自己解决不了它以后可能会出现问题，现在在用QQ五笔




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rime/weasel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 上午10:03
收件人:&nbsp;"rime/weasel"<weasel@noreply.github.com&gt;;
抄送:&nbsp;"止"<1825489599@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [rime/weasel] 莫名奇妙的会发生 已禁用输入法状态 (#540)





  
这几天已经发生好多次了，已禁用输入法状态，而且没有办法解除禁用，只能重装解决，我也没搞什么特殊操作，搞不懂究竟是什么原因引起的
 win10 自带的微软拼音一切正常，感觉是 weasel 的问题。
 

 
OS：Windows10 2004
  
权限问题，因为你需要编辑的软件是通过管理员权限打开的。把你的小狼毫也设置管理员权限就好了。方法： 右击程序-〉属性-〉兼容性- 〉更改所有用户的设置-〉勾选以管理员身份运行此程序    然后重启电脑

**Comment by hkahfakh** [comment]
ctrl + space 会解除禁用

**Comment by isPoto** [comment]
> ctrl + space 会解除禁用

解除禁用是指输入法恢复正常？因为很多情景下都会遇到 Rime 已禁用问题。如果 Rime 可以默认以管理员身份运行就好啦。

**Comment by Janzulene** [comment]
禁用 `Ctrl + Space` 能起作用吗？有点好奇
https://github.com/rime/weasel/issues/717#issuecomment-1464936922
