### ISSUE TITLE
切换语言的悬浮提示导致游戏跳回桌面或卡死

### ISSUE THREAD

**Issue by shu307** [rime/weasel#541]
就是这个![图片](https://raw.githubusercontent.com/shu307/111/master/111.png)
刚才切中英文，这个图标在输入框一闪，游戏卡死，重启后测试，都是跳回桌面

有没有**非编译**，仅通过修改配置文件就能实现的方法

应用：国服激战2，使用[d912pxy插件](https://github.com/megai2/d912pxy)

硬件信息如下
系统		Windows10专业版64位版本号19041.329
处理器		AMDRyzen5 3600
显卡		AMDRadeon RX5700

**Comment by shu307** [comment]
https://github.com/rime/weasel/issues/520

**Comment by fxliang** [comment]
closed by #1031
