### ISSUE TITLE
反馈小狼毫输入法只能输入英文之问题

### ISSUE THREAD

**Issue by kalsangphuntsok** [rime/weasel#542]
1 win 10系统。
2 每次重启电脑时，便出现只能输入英文而不能输入中文的现象。
3 用重新部署也未能解决问题。

**Comment by mokapsing** [comment]
https://github.com/rime/weasel/issues/563

**Comment by DonCN** [comment]
我也遇到了，在wps下无法切换为中文，只能输入英文。重新部署、重启算法服务都不行。而在别的软件下输入正常。

**Comment by DonCN** [comment]
我发现360把weasel的安装程序和weasel.dll都视为病毒隔离了，可能是因为这个原因造成的无法输入中文。在360中将上述程序添加到信任区，重装后，可以输入中文。

**Comment by fxliang** [comment]
尝试#1194 产出试试？
