### ISSUE TITLE
明月拼音userdb内持续产生Compaction error

### ISSUE THREAD

**Issue by wx40217** [rime/weasel#543]
2020/07/27-18:38:02.157000 3536 Recovering log #426
2020/07/27-18:38:02.159000 3536 Delete type=0 #426
2020/07/27-18:38:02.159000 3536 Delete type=2 #427
2020/07/27-18:38:02.160000 3536 Delete type=3 #425
2020/07/27-18:38:02.160000 13724 Compacting 9@0 + 1@1 files
2020/07/27-18:38:02.161000 13724 compacted to: files[ 9 1 0 0 0 0 0 ]
2020/07/27-18:38:02.161000 13724 Compaction error: Corruption: not an sstable (bad magic number)
每次重新部署或开机后都会产生 用户词库似乎一直没有更新 是因为这个的原因吗

**Comment by lotem** [comment]
leveldb 的故障，恕我無能爲力了。如果不是最新的輸入法程序，請到 https://rime.im/download 升級。

**Comment by wx40217** [comment]
> leveldb 的故障，恕我無能爲力了。如果不是最新的輸入法程序，請到 https://rime.im/download 升級。

感谢 删除用户文件夹重装后恢复正常了
