### ISSUE TITLE
如何设置rime使候选区（列显示）每行的显示的文字不超过一定长度？输出则按原文输出

### ISSUE THREAD

**Issue by Nonenever** [rime/weasel#545]
如何设置rime使候选区（列显示）每行的显示的文字不超过一定长度？输出则按原文输出
![超长](https://user-images.githubusercontent.com/30862179/88933514-1796ec80-d2b2-11ea-87c0-04553eab3519.png)
只显示 超长的文字文字文字文…字文字文字 ，
而输出为正确的 超长的文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字

**Comment by LEOYoon-Tsaw** [comment]
換行，隔壁鼠鬚管已經有人做了

**Comment by Nonenever** [comment]
> 換行，隔壁鼠鬚管已經有人做了
https://github.com/rime/squirrel/issues?page=5&q=is%3Aissue+is%3Aopen
没有找到呀
是哪一个？

**Comment by Nonenever** [comment]
有实现这个功能的吗？

换行显示有办法实现，
https://github.com/fxliang/weasel/actions/runs/3709588190
 -- 方案patch中要添加以下两行
--  engine/filters/+:
--  - lua_filter@Multiline_filter
function Multiline_filter(input)
	for cand in input:iter() do
		if cand.text:match("\\r\\n") then
			local nt = string.gsub(cand.text, "\\r\\n", utf8.char(13)..utf8.char(10))
			local cnd = Candidate("", cand.start, cand._end, nt, cand.comment)
			yield(cnd)
		elseif cand.text:match("\\r") then
			local nt = string.gsub(cand.text, "\\r", utf8.char(13))
			local cnd = Candidate("", cand.start, cand._end, nt, cand.comment)
			yield(cnd)
		elseif cand.text:match("\\n") then
			local nt = string.gsub(cand.text, "\\n", utf8.char(10))
			local cnd = Candidate("", cand.start, cand._end, nt, cand.comment)
			yield(cnd)
		else
			yield(cand)
		end
	end
end

但如何使显示与输出的结果不一致？

如：
![sshot-1](https://user-images.githubusercontent.com/30862179/213847346-a95ac9bc-40b5-44c9-a7a3-ecf934792ba1.png)
![20230121-](https://user-images.githubusercontent.com/30862179/213847347-00547745-4341-40c3-aaa5-dc0f7b45e593.png)

**Comment by Nonenever** [comment]
https://github.com/iDvel/rime-ice
https://github.com/tumuyan/rime-melt
参考这两个 实现 只显示部分数据
![2023-02-07_101046](https://user-images.githubusercontent.com/30862179/217130718-79cbb863-2691-459e-a286-1fc447c11450.png)
https://github.com/tumuyan/rime-melt/blob/master/lua/melt.lua

**Comment by LEOYoon-Tsaw** [comment]
這種時候唯有折行顯示才是正道，輸入的內容當然是要完整看到才符合輸入法的目的

**Comment by Nonenever** [comment]
> 這種時候唯有折行顯示才是正道，輸入的內容當然是要完整看到才符合輸入法的目的

修改后面的那个lua 应该能满足要求，只能是大神给修改一下了

**Comment by Nonenever** [comment]
`----------------------------------------------------------------
--在使用Lua的过程中，经常会遇到需要截取字符串或者获得字符串真实长度的情况，而Lua自带的string.sub()对于中文字符会当作3个字符来处理，截取时会造成乱码。所以需要自己改造下，下面的SubStringUTF8()方法是我改编的SubString方法，经测试可以识别中英混合的字符串，不管是英文字符还是中文字符都当作一个字符来计算index，并且可以像系统的string.sub()一样使用负数来从末尾截取字符。其他的几个方法是SubStringUTF8()的依赖方法，也可以单独拿来使用。
--版权声明：本文为CSDN博主「菰城茧」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
--原文链接：https://blog.csdn.net/fenrir_sun/article/details/52232723
--截取中英混合的UTF8字符串，endIndex可缺省
function SubStringUTF8(str, startIndex, endIndex)
  if startIndex < 0 then
    startIndex = SubStringGetTotalIndex(str) + startIndex + 1;
  end

  if endIndex ~= nil and endIndex < 0 then
    endIndex = SubStringGetTotalIndex(str) + endIndex + 1;
  end

  if endIndex == nil then 
    return string.sub(str, SubStringGetTrueIndex(str, startIndex));
  else
    return string.sub(str, SubStringGetTrueIndex(str, startIndex), SubStringGetTrueIndex(str, endIndex + 1) - 1);
  end
end

--获取中英混合UTF8字符串的真实字符数量
function SubStringGetTotalIndex(str)
  local curIndex = 0;
  local i = 1;
  local lastCount = 1;
  repeat 
    lastCount = SubStringGetByteCount(str, i)
    i = i + lastCount;
    curIndex = curIndex + 1;
  until(lastCount == 0);
  return curIndex - 1;
end

function SubStringGetTrueIndex(str, index)
  local curIndex = 0;
  local i = 1;
  local lastCount = 1;
  repeat 
    lastCount = SubStringGetByteCount(str, i)
    i = i + lastCount;
    curIndex = curIndex + 1;
  until(curIndex >= index);
  return i - lastCount;
end

--返回当前字符实际占用的字符数
function SubStringGetByteCount(str, index)
  local curByte = string.byte(str, index)
  local byteCount = 1;
  if curByte == nil then
    byteCount = 0
  elseif curByte > 0 and curByte <= 127 then
    byteCount = 1
  elseif curByte>=192 and curByte<=223 then
    byteCount = 2
  elseif curByte>=224 and curByte<=239 then
    byteCount = 3
  elseif curByte>=240 and curByte<=247 then
    byteCount = 4
  end
  return byteCount;
end
----------------------------------------------------------------
--返回用换行符分隔后的字符串  --太长字符串增加换行，之前有<br>替换为换行，并不再拆分为多行
function insert_newline_sub_str(str,length)
--   local length =25
--print(length)
 if length == nil then 
   length =25
 end
 
    local text =""
   if string.find(str, "<br>")~=nil then
     text = string.gsub(str,"<br>",utf8.char(13))
     else


  local temptext =""
  local templength=0
  local textlength =SubStringGetTotalIndex(str)
  for i=1 ,textlength , length do

    templength =templength + SubStringGetTotalIndex(temptext)
    temptext= SubStringUTF8(str, templength+1, templength+length)


 -- print(" 开始：" .. templength+1 .. " 结束：" .. templength+length .. " string.len:" ..  string.len(temptext)  .. " SubStringGetTotalIndex:" ..  SubStringGetTotalIndex(temptext) .. " 处理后：" .. temptext )
    if text=="" then
      text = temptext
    else
--      text =text .. utf8.char(13) .. "  " .. temptext
       text =text .. utf8.char(13) ..  temptext
    end

end

end
--print("----------------------")
  return text
  
end


function insert_newline_sub_string(inputstr,length)---多行拆分 处理，并本行太长的也按换行处理
  local t={}

  for str in string.gmatch(inputstr, "([^<br>]+)") do

    table.insert(t, str)

  end
  local text =""
  for _, v in ipairs(t) do 
   -- print(v)
    if text=="" then
      text = insert_newline_sub_str(v,length)
    else
      text =text .. utf8.char(13) ..  insert_newline_sub_str(v,length)
    end


  end


  return text

end
----------------------------------------------------
local history_str = ""
local history_oo = ""
local history_ii = ""
local history_uu = 1
-- Windows 小狼毫输出\r\n会崩溃，故需判断系统为Windows则只输出\r
local next_line = "\n"
if package.config:sub(1,1) == "\\" then
  next_line = "\r"
end

-- 包含3个功能：把Oo转换为变量值, <br>转换为换行, 过长的内容切分并缓存,在候选栏仅提供预览（节约屏幕空间的同时避免输入法崩溃）
local oo_buffer= {}

local function oo_filter(input,env)
  oo_buffer= {}
  local input_len = string.len(env.engine.context.input)

  if string.len(history_oo)>0 then
    for cand in input:iter() do
      local text= string.gsub(cand.text,"<br>",next_line)
      text= string.gsub(text,"&nbsp"," ")

      local comment = cand.comment

      if string.find(text, "Oo")~=nil then
        text = string.gsub(text,"Oo",history_oo)
        if string.len(history_ii)>0 then
          text = string.gsub(text,"Xx",history_ii)
        end
        comment =  "=" .. history_oo
      end

      if string.len(text)>120 then
        local key = get_sub_string(text,100)
--        local key = string.sub(text,0,100)
        oo_buffer[key] = text
        yield(Candidate(cand.type, 0,input_len, key, "..-." ..  comment ))
      elseif text ~= cand.text then
        yield(Candidate(cand.type, 0,input_len, text, comment ))
      else
        yield(cand)
      end
    end
  else
    for cand in input:iter() do
      local text = cand.text
        local textcomment =cand.comment --env.engine.context:get_commit_text()
--        textcomment  = textcomment .. next_line .."测试"
        textcomment= insert_newline_sub_str(textcomment,20) --注释掉本行  候选的注释 原样显示
       
      if string.len(text)>110 then
        text= string.gsub(text,"&nbsp"," ")
            local key = insert_newline_sub_string(text)-----新增修改 超一过长度后增加换行符     
--        local key = get_sub_string(text,100)---原先
--        local key = string.sub(text,0,100)
        text= string.gsub(text,"<br>",next_line)---原先 -实际输出项目-不用修改
--           text= string.gsub(text,"<br>",utf8.char(13)) .. "^_^"-----新增修改
        oo_buffer[key] = text
--        yield(Candidate(cand.type, 0,input_len, key, "..." .. cand.comment ))--原数据
         yield(Candidate(cand.type, 0,input_len, key, textcomment ))---新修改
       
      else

        --yield(cand) --原先的语句
        ------------------------------ "&nbsp" 替换为空格 显示到候选项内-开始
        if string.find(text, "&nbsp")~=nil  then


          local nt = string.gsub(text, "&nbsp", " ")
          if string.len(nt) ==string.len(" ") then
             yield(Candidate("", cand.start, cand._end,  text, textcomment))
--            yield(cand)
          else
            local cnd = Candidate("", cand.start, cand._end, nt, textcomment)
            yield(cnd)
          end
        else
                yield(Candidate("", cand.start, cand._end,  text, textcomment))
--          yield(cand) --不含"&nbsp"的 原样输出
        end
        ------------------------------"&nbsp" 替换为空格 显示到候选项内-结束

      end
    end
  end
end

-- 包含2个功能，输入 值=oo 设置 history_oo，输入数字完成长候选词取值上屏
local function oo_processor(key, env)
  local context = env.engine.context
  local commit_text = context:get_commit_text()
  if commit_text == nil then 
    return 2
  end

  local ch = key.keycode
  local engine=env.engine
  local done=false

  if  context:has_menu() then
    if key.keycode == 32  then
      done = true
    elseif ch <58 and ch>48 then
      local composition = context.composition
      local segment = composition:back()
      local index = segment.selected_index + ch -49
      local candidate_count = segment.menu:candidate_count()
      if candidate_count <= index or index < 0 then
        return 2
      end
      --  -48为键盘数字 -49 第一个候选序号0
      commit_text = segment:get_candidate_at(index).text
      done = true
    end

    if string.len(commit_text)>80 and done then
      context:clear()
      if oo_buffer[commit_text] ~= nil then
        engine:commit_text(oo_buffer[commit_text])
      else
        engine:commit_text(commit_text)
      end
      return 1
    end

  end


  local v = commit_text:match("(.+)=")
  local k = context.input:match("=(.+)$")
  if k == nil or v == nil then
    return 2
  end
-- k 和 v只要能够匹配到，长度一定大于0
--  local file = io.open("C:\\Users\\Yazii\\AppData\\Roaming\\Rime\\history.txt","a")
--  file:write("\n" .. commit_text .. "\tk=" .. k .. " v=" .. v)
--  file:close()

  if(k == "oo") then
    history_oo = v
    context:clear()
    return 1
  elseif (k == "ii") then
    history_ii = v
    context:clear()
    return 1
  end
  return 2
end
--return {getdate= get_date, jpcharsetfilter= jpcharset_filter,autocapfilter=autocap_filter, longwordfilter=long_word_filter,ooprocessor=oo_processor ,oofilter=oo_filter}

return {ooprocessor=oo_processor ,oofilter=oo_filter}

-----rime.lua---------------
--local M= require("****")
--oo_processor = M.ooprocessor
--oo_filter =M.oofilter
--------------schema-----------------
--  processors:  
--    - "lua_processor@oo_processor"  
--  filters:  
--    - "lua_filter@oo_filter"  `

> 
![20230211](https://user-images.githubusercontent.com/30862179/218256297-e5230953-e698-43ce-8b14-42048461e1dd.gif)

**Comment by Nonenever** [comment]
目前功能实现了(换行显示)，照别的改的，可能有其他问题

**Comment by Nonenever** [comment]
[melt-修改为换行显示.lua.txt](https://github.com/rime/weasel/files/10720623/melt-.lua.txt)

**Comment by fxliang** [comment]
#1037 可设置候选字数超长缩略
![image](https://github.com/rime/weasel/assets/4023160/5906cc5a-9981-4efe-92f7-8381e81f9dbd)

0.15.0起可以用以下参数自动折行，同时支持`\r`换行
`style/layout/max_width: 1024 `

#1169 支持`\n`换行转义
