### ISSUE TITLE
選單無法使用也無法打字

### ISSUE THREAD

**Issue by pig858** [rime/weasel#546]
右下角的設定選單 點了都沒反應
也無法進行打字

**Comment by pig858** [comment]
版本是win10

**Comment by pig858** [comment]
將C槽User/{使用者名稱}/AppData/Roaming/下的RIME資料夾整個刪除並解除安裝輸入法後重開機再重安裝就解決了

**Comment by zerobikappa** [comment]
按照这里的方法操作了，还是不行，不知道是不是windows最近的更新所致。选单无法使用也无法打字，就像是完全没有加载输入法一样，但是windows输入法状态的确是有选择小狼毫的，而小狼毫算法服务也是正在运行的。

**Comment by pig858** [comment]
@zerobikappa 那時候我的版本號1903 (OS Build 18362.1016) 但我另一台有自動更新的也是用同樣方式操作就可以使用了
先用Windows內建安裝移除程式刪除小狼毫後 再去C槽User/{使用者名稱}/AppData/Roaming/下將RIME資料夾整個刪除 重開機之後再重新安裝一次試試看
