### ISSUE TITLE
win10 CTRL+空格 切换后，导致Backspace键失效

### ISSUE THREAD

**Issue by donjan-deng** [rime/weasel#547]
过程，随便输入，出现侯选栏，不上屏。CTRL+空格切换非输入法，此时可以输入英文，但光标异常，Backspace无效。 再次按CTRL+空格切换回来，侯选词仍在。测试环境：win10 64位+windows记事本、微信聊天框、qq聊天框等

**Comment by Crasleepish** [comment]
试了一下，可以这样规避
```
patch:
  "key_binder/bindings/@next": { when: composing, accept: Control+space, send: Escape }
```
虽然不是很完美，CTRL+空格切换过去之后会莫名其妙丢失一次键盘消息

**Comment by lotem** [comment]
不太明白，不過出現這樣的問題倒是很有意思啊。
Control+空格默認是Windows的關閉中文IME的快捷鍵吧？那麼我理解中問題在於輸入法被系統禁用時應當有所察覺並清除當前未完成的輸入。有賴TSF高手研究。

不能假設Control+空格一定綁定到這個系統功能。我自己是把這個系統快捷鍵禁用了（難）。因爲宮保拼音需要用Control和空格輸入。

**Comment by StewartXiang** [comment]
> 
> 
> 不太明白，不過出現這樣的問題倒是很有意思啊。
> Control+空格默認是Windows的關閉中文IME的快捷鍵吧？那麼我理解中問題在於輸入法被系統禁用時應當有所察覺並清除當前未完成的輸入。有賴TSF高手研究。
> 
> 不能假設Control+空格一定綁定到這個系統功能。我自己是把這個系統快捷鍵禁用了（難）。因爲宮保拼音需要用Control和空格輸入。

但是我的win10这个快捷键让我很头疼。使用weasel时，把这个快捷键禁用后win的系统又会自动给加上这个快捷键。如果使用MS自带的输入法，则禁用有效。我开始以为是win的问题，但我现在感觉也可能是weasel的问题……

**Comment by gdtv** [comment]
> 
> 
> 试了一下，可以这样规避
> 
> ```
> patch:
>   "key_binder/bindings/@next": { when: composing, accept: Control+space, send: Escape }
> ```
> 
> 虽然不是很完美，CTRL+空格切换过去之后会莫名其妙丢失一次键盘消息

是不太完美，切换成英文后，第一次按键会无效

**Comment by fxliang** [comment]
最新构建已解决😀
