### ISSUE TITLE
WeaselTSF::_InitThreadMgrEventSink 是否有泄露？

### ISSUE THREAD

**Issue by cloudwu** [rime/weasel#55]
https://github.com/rime/weasel/blob/develop/WeaselTSF/ThreadMgrEventSink.cpp#L31-L43

成功调用 `pSource->AdviseSink` 后，似乎没有 `pSource->Release` 释放 QueryInterface 出来的 pSource   .

**Comment by lotem** [comment]
正確。應該調用 `pSource->Release();`。

**Comment by lotem** [comment]
交了一行代碼
https://github.com/rime/weasel/commit/61af3671be8ca19da7d16f72fa22433cfb5d2689
