### ISSUE TITLE
UILELEMENTENABLEONLY状态下，无法获取到composition string

### ISSUE THREAD

**Issue by Windmill-City** [rime/weasel#553]
测试程序
https://github.com/Windmill-City/libtf/files/5147877/Test-Window.zip
https://github.com/Windmill-City/libtf

**Comment by Windmill-City** [comment]
https://github.com/rime/weasel/blob/371e08e4c799beef15ec93b461b17125c77f166b/WeaselTSF/EditSession.cpp#L39
这里应该改成if (_IsComposing() && (config.inline_preedit || ITfThreadMgrEx::GetActiveFlags == TF_TMF_UIELEMENTENABLEDONLY)

**Comment by fxliang** [comment]
![image](https://github.com/rime/weasel/assets/4023160/9644050d-fe1a-4b84-82e8-3585cf561d01)
最新版未就此位置修改，但是问题似乎已解决。
