### ISSUE TITLE
小狼毫五笔拼音状态下，怎样集成easy_en?

### ISSUE THREAD

**Issue by moyuns-dev** [rime/weasel#557]
现在使用的是五笔和拼间混拼， 但是现在想把easy_en的库集成在一起？ 这个就不用ctrl + ` 去手动切换了？

**Comment by lotem** [comment]
easy_en 是什麼？

**Comment by moyuns-dev** [comment]
easy_en.dict.yaml  这个东西。
搞定了， 就是多方案反查功能， 谢谢！
