### ISSUE TITLE
高分屏1920x1080分辨率下，配置界面显示模糊

### ISSUE THREAD

**Issue by ghost** [rime/weasel#558]
![image](https://user-images.githubusercontent.com/60801469/92865790-9b64ee00-f3b3-11ea-81dc-4a44459caae8.png)
如图所示，我用的是Windows 10系统2004，显示屏分辨率是1920x1080，缩放比例1.25，但是配置界面中字体非常模糊且极小，根本看不清设置选项
请问如何修复

**Comment by moposx** [comment]
是否使用了 MacType ？

**Comment by David-H-1** [comment]
我用的Windows系统，没有所谓的mactype

**Comment by David-H-1** [comment]
终于解决了，在兼容性疑难解答中启用dpi强制缩放就显示正常了

**Comment by David-H-1** [comment]
希望能早日解决高分屏适配问题，谢谢！

**Comment by fxliang** [comment]
最新Nightly构建已修复，留意确认
