### ISSUE TITLE
拼音模式下可以输入前4个字就将整句词显示出来吗？

### ISSUE THREAD

**Issue by meme90** [rime/weasel#560]
这个输入法很棒，但发现一个小缺陷。
在别的拼音输入法（搜狗/微软）中，输入前4个字，就会将词库中对应的长句子显示出来。
比如打“一枝红杏”，然后下面候选列表里就出现了“一枝红杏出墙来”，这样的话打诗词就非常方便了。
但rime里非要把七个字打完，这句诗才能出现在候选列表里。
我学习了一下配置文件，貌似没办法实现这个功能。如果这个能改好的话，那对我来说就是一个完美的输入法了。

**Comment by meme90** [comment]
刚刚又想了一下，如果配置里不能实现，那么有一个变通的方法，就是新建一个词库，把所有大于4个字的词放在里面，然后拼音只保留前4个音，这样应该就可以在输入4个字的时候出现整句词了。但缺点就是当打第5个/第6个字的时候，这个词反而不见了。除非再建5/6个音的词库，但这样感觉就有点麻烦了。

**Comment by Humwq** [comment]
这样得重新搞词库啊  很痛苦。。。

**Comment by fxliang** [comment]
最新的librime已有此功能，最新nightly build已使用上，留意体验
