### ISSUE TITLE
win7下程序有bug

### ISSUE THREAD

**Issue by redream123** [rime/weasel#562]
通过输入法设定中的“获取更多输入方案”功能来安装其它输入方案时，新安装的方案被安装到了默认用户文件夹，而不是用户在安装程序时所指定的自定义文件夹，这样导致新安装的方案无法起作用。
希望新版本能修正此错误！

**Comment by lotem** [comment]
同 https://github.com/rime/plum/issues/2 、 https://github.com/rime/home/issues/615 ！
