### ISSUE TITLE
小狼毫当使用shift+鼠标操作时，会错误地触发中英文切换

### ISSUE THREAD

**Issue by Crasleepish** [rime/weasel#566]
Shift+鼠标操作在文本编辑中是常用的功能，但是会使输入法的中英文状态发生切换。

环境：
Windows10 1903
小狼毫 0.14.3

复现方式：
1.文本编辑器中随意编辑一段文字
2.将光标定位在任意位置，按住左Shift，鼠标点击文中中另一个位置，以选择一个文本块。
如果第2步在较短的时间内（约1秒）完成，就会发生中英文切换

Shift+任意键盘操作都是没有问题的，应该只是没有考虑鼠标点击事件

**Comment by lotem** [comment]
這個問題以前討論過吧。
大概鼠標消息不走輸入法，所以這樣。
額外監聽鼠標事件的話，恐怕會被當成監控輸入的公害軟件。

解法：Shift鍵按得時間長一些，可以避免觸發狀態切換。

**Comment by Crasleepish** [comment]
@lotem 
多谢，还是选择更换绑定热键了
