### ISSUE TITLE
Quicker 文本指令功能执行后会切换小狼毫输入法为中文输入状态

### ISSUE THREAD

**Issue by oopp1800** [rime/weasel#567]
### 问题
如题，当使用 [Quicker](https://getquicker.net/) 的文本指令功能后，小狼毫输入法会自动切换到中文输入状态，测试微软默认输入法无此问题。可稳定复现，重启电脑无法解决问题。

### Quicker 开发者回复
已给 Quicker 提 issue: https://getquicker.net/QA/Question/2520
以下是 Quicker 开发者的回复：

> 文本指令在执行之前会检测输入法状态，如果开启的话，会暂时关闭，执行完再开启（为了避免模拟输入内容的时候受到输入法影响）。 这个API有可能对某些输入法、或者某些状态下不能正常工作，所以或许是这个原因的。

### 环境配置
已配置默认输入法状态为英文：
```yaml
patch:
  "switches/@0/reset": 1  #表示將 switcher 列表中的第一個元素（即 ascii_mode 開關）的初始值重設爲狀態1（即「英文」）。
```

Quicker: 最新版 1.10.15.0
小狼毫: 最新版 0.14.3
Windows: win10 最新版

**Comment by a0193143** [comment]
某些遊戲也會遇到這個問題(例如osu)
