### ISSUE TITLE
Win10中小狼毫显示异常

### ISSUE THREAD

**Issue by nebulas-star** [rime/weasel#568]
![image](https://user-images.githubusercontent.com/33574791/95345764-abf28080-08ed-11eb-9296-ccac90e494df.png)
如图。语言栏无法正常显示小狼毫的「中」字图标，亦无法打开配置菜单。
同时，如下图，「替代默认输入法」选项中无法选定小狼毫。
![image](https://user-images.githubusercontent.com/33574791/95346082-05f34600-08ee-11eb-9e94-8d928be1ce59.png)
操作系统：windows 10 专业版
版本号：2004
内核版本：19041.508
正版激活
屏幕分辨率3840*2160

**Comment by maxwellETL** [comment]
你好，请问这种情况解决了吗？
我好像见过这种情况，我猜是你在设置里把选项「可用时，使用桌面语言栏」勾上了(对应最后一张图的 'Use the desktop language bar when it's [available')，下面的图是该选项的位置：
![Time Language](https://user-images.githubusercontent.com/48290158/96364186-19af6f80-116c-11eb-9e79-0b698b7ee5d5.png)
![method](https://user-images.githubusercontent.com/48290158/96364190-1caa6000-116c-11eb-99b3-8744161da64b.png)
![bar](https://user-images.githubusercontent.com/48290158/96364233-5bd8b100-116c-11eb-97e4-824ebe074a32.png)

**Comment by nebulas-star** [comment]
> 你好，
> 请问这种情况解决了吗？我好像见过这种情况，我猜是你在设置里把选项“可用时，使用桌面语言栏”勾上了（对应最后一张图的'使用桌面语言栏[可用时]，下面的图是该选项的位置：

是的，确实是这个问题。感谢您的帮助。

**Comment by yippeesoft** [comment]
我是一個WIN10有中，一個WIN10沒中。。。
都沒勾選 使用桌面语言栏。

**Comment by fxliang** [comment]
> 我是一個WIN10有中，一個WIN10沒中。。。 都沒勾選 使用桌面语言栏。

试试最新的构建看看

**Comment by yippeesoft** [comment]
从CI下载了5.11的包.好像图标多了三个字.
但是更惨,都没中文输入了.只能看着语言栏...

**Comment by fxliang** [comment]
5.11的包？
[这个](https://github.com/rime/weasel/actions/runs/5077099967)

**Comment by yippeesoft** [comment]
你好 是 https://github.com/fxliang/weasel/actions/runs/4943448374 这个的包。。

**Comment by determ1ne** [comment]
> 你好 是 https://github.com/fxliang/weasel/actions/runs/4943448374 这个的包。。

先删除系统中的小狼毫软件，再用这个 repo 的最新构建安装一下

**Comment by yippeesoft** [comment]
https://github.com/rime/weasel/actions/runs/5077099967 这个可以输入了,只是还是没有 中 图标.
把custom.yaml全刪除也沒有。
重啓服務的時候會短暫出現 重啓 圖標。
看了下rime..log...也沒什麼出錯信息。就是warn.log記錄幾個yanl不存在。

**Comment by fxliang** [comment]
> 手工添加 "style/display_tray_icon": true 后 中 图标出现了。但是只有右键单击和双击可用，左键单击不会切换中英文。
而用shift切换后图标能变化成 A 。

原来这个trayicon也没有左键点击切换中英文状态的功能代码吧，是语言栏里面才有。建议使用语言栏

**Comment by yippeesoft** [comment]
`STDAPI CLangBarItemButton::GetTooltipString(BSTR *pbstrToolTip)
{
	*pbstrToolTip = SysAllocString(L"左鍵切換模式，右鍵打開菜單");
	return (*pbstrToolTip == NULL)? E_OUTOFMEMORY: S_OK;
}

STDAPI CLangBarItemButton::OnClick(TfLBIClick click, POINT pt, const RECT *prcArea)
{
	if (click == TF_LBI_CLK_LEFT)
	{
		_pTextService->_HandleLangBarMenuSelect(ascii_mode ? ID_WEASELTRAY_DISABLE_ASCII : ID_WEASELTRAY_ENABLE_ASCII);
		ascii_mode = !ascii_mode;
		if (_pLangBarItemSink) {
			_pLangBarItemSink->OnUpdate(TF_LBI_STATUS | TF_LBI_ICON);
		}
	}`

根据提示语查了下好像是这段代码

**Comment by fxliang** [comment]
这段代码是tsf语言栏的，display_tray_icon对应的是另外一个原来ime下模拟语言栏的托盘图标
下面的图我是设置了display_tray_icon: true 的状态，两个图标都显示，但是左击只有语言栏是有切换中英文状态的对应功能代码的。

![enicon](https://github.com/rime/weasel/assets/4023160/82ab854c-20e7-41af-8505-1bbd9f309011)

**Comment by yippeesoft** [comment]
|     | WEASEL release |  ci版本  |
| ------| ------ | ------ |
| 下载来源| [lotem] released this May 4, 2021 | Merge pull request #876 from fxliang/sp_issue #33 |
| 操作系统| win10 lts | win10 专业（release 版本无图标后改为ci版本）  |
| 图标| 显示 中 图标 |加display_tray_icon 显示|
| 提示 | 左鍵切換模式，右鍵打開菜單  | 小狼毫  |
| 点击 | 左鍵切換中英文  | 无反应  |

![image](https://github.com/rime/weasel/assets/1516538/5b8959c9-9f13-4a52-b6e3-f5f362fec0e6)
![image](https://github.com/rime/weasel/assets/1516538/d3286de3-a78d-4c1f-b097-9096e2c5d1fd)

**Comment by fxliang** [comment]
#876 测试
![lclick_language_button_pr876](https://github.com/rime/weasel/assets/4023160/f788af33-b68a-4115-b85f-261dfcef837a)


目前我手头最新的代码状态（当然这个部分没有修改）
![lclick_language_button](https://github.com/rime/weasel/assets/4023160/d0288d3c-66a8-45c5-b912-a20795e0bce0)
