### ISSUE TITLE
小狼毫可不可以不替换Win10的中英图标。

### ISSUE THREAD

**Issue by QingW-7023** [rime/weasel#570]
现在Win10已经快普及了，小狼毫在Win10上会替换掉自带的“中”“英”图标，可不可以不替换！我试过了，搜狗输入法虽然没有替换图标，但是右击“中英”图标，也能出现菜单。这样的问题虽小，但是如果能做到，也能提升外观观感。
如果可以，请求能有自己的选择，是否出现浮动的提示标签，和是否替换Win10默认的右下角图标。

**Comment by lotem** [comment]
沒有這回事。
輸入法狀態欄圖標是輸入法程序自己添加的。沒有替換任何系統的東西！
