### ISSUE TITLE
基本体验不太好

### ISSUE THREAD

**Issue by zhl111** [rime/weasel#574]
在什么配置也没有改动的情况下，有时只是shift切换了下，就莫名其妙的无法输入中文了。开了很多文件又不想折腾重启，死活找不到解决办法，只能切换到别的输入法救急。

> 输入法并没有禁用算法服务，我也不知道怎么退出算法服务

这个输入法很多年了吧，这不应该比手心输入法更好用吗？

**Comment by lotem** [comment]
Shift鍵在缺省設置下是中西文切換的開關。您需要再按一下Shift鍵回到中文模式。

**Comment by zhl111** [comment]
谢谢您告诉了这众人皆知的解决问题的方法，谢谢
