### ISSUE TITLE
無法預覽配色樣式以及其他問題

### ISSUE THREAD

**Issue by MisterFISHUP** [rime/weasel#577]
### 問題
- 我在 Win10 上安裝 RIME 後，無法預覽配色樣式 (我猜測是因為我安裝使用自訂路徑導致的)
- RIME 不知道為什麼有時會完全失去功能(並不是重新佈署時)，包括 `F4`, `Ctrl`+` 以及右鍵選單的所有項目。這個極大幅度的降低了使用體驗與使用意願 (不知道跟自訂路徑是否有關)
- RIME 注音是不是沒辦法輸入注音符號？像是ㄅㄆㄇ這樣。如果可以，要怎麼輸入？如果不行，希望可以加入。
### 建議
- 感覺把**配色選擇**跟**方案選擇**分開比較符合使用者體驗：方案選擇後可以接配色選擇，但要選配色 每次都要先經過方案選擇，覺得相當莫名其妙。

**Comment by lotem** [comment]
没有单项的设置界面。
目前的设置界面主要为了安装时弹出的安装向导而制作，功能比较简单。
业余项目，没有技术力实现完美奢华的使用者体验，敬请见谅。

用<kbd>Control+Return</kbd>提交按键字符，<kbd>Shift+Return</kbd>提交注音符号。

**Comment by MisterFISHUP** [comment]
謝謝你的回覆！瞭解了！
另外我之前用火狐下載，exe 會變 zip 壓縮檔，我是解壓縮後點擊裡面 exe 檔安裝的，剛剛才發現正常應該是能夠直接下載 exe 檔一鍵安裝。可能是這樣才導致上述問題！

再次感謝開發者的努力！
