### ISSUE TITLE
小狼毫在Word中输入问题

### ISSUE THREAD

**Issue by Mintonmu** [rime/weasel#579]
小狼毫在Word中输入，输入框一闪一闪的，没办法看到候选框，但是可以选择候选字

OS：windows 10 1909
小狼毫：0.14.3

希望官方能够修复这个bug

**Comment by sfzylx** [comment]
我也是是这样，打开一个word文件时没有问题，再同时打开第二个word文件后就看不到候选框了。
我用的是office365
小狼毫是0.14.3

**Comment by lifansama** [comment]
#228

**Comment by toshiya14** [comment]
#594 我也是出现了一闪一闪的，不过是锁屏恢复以后。我这边倒是可以切换输入法再切换回来解决。

**Comment by huquanjun** [comment]
也遇到了这个问题，重启小狼毫算法服务的话问题还是存在，但是把word都关掉然后再开就又好了

**Comment by zjsailor** [comment]
+1,关闭word的输入法控制，仍然无效，重启算法，或者关闭word再重启仍然无效，但最简单的就是重启电脑，就可以解决。
这个问题偶尔出现，所以还是可以忍受，用了个把月出现一次，就重启电脑解决。

**Comment by momotu** [comment]
感觉实际上是一个问题，用office365 word关闭的输入法控制，在word里面正常了，但是在onenote里面又开始闪烁了，有没有什么办法解决这个问题，只能关了onenote然后再切换一下输入法才能恢复正常。但是在onenote里面已然打不了字

**Comment by QianmuZ** [comment]
> 感觉实际上是一个问题，用office365 word关闭的输入法控制，在word里面正常了，但是在onenote里面又开始闪烁了，有没有什么办法解决这个问题，只能关了onenote然后再切换一下输入法才能恢复正常。但是在onenote里面已然打不了字

可以在选项->语言中将创作语言和校对 选项的英语设置为首选就没有问题了

**Comment by zzColin** [comment]
我现在唯一觉得有点意思的，是 #228 里有人提到用改写模式就不会闪，这就让我怀疑这事情可能和 preedit 有关——因为据我观察，TSF 的 preedit 在插入模式下永远是开着的，而在改写模式下永远是关掉的。具体而言，插入模式下，即便输入法关掉 preedit，word 中输入时插入点位置还是会出现一个带虚线的空格，本质上只是 preedit 区域的字符串为空而已；而换成改写模式后，preedit 才真正被关掉，即便输入法的 preedit 设置成打开，实际也不是「真 preedit」，而是在插入点旁边贴一块膏药模拟出来的效果。

话说这个问题是真的会耍猴……你做了个操作发现好了，就以为是这个操作解决了问题，可实际上它只是凑巧在这个时间忽然又不抽风了而已……

**Comment by determ1ne** [comment]
fixed in 0.15.0

**Comment by johnxm913** [comment]
> > 感觉实际上是一个问题，用office365 word关闭的输入法控制，在word里面正常了，但是在onenote里面又开始闪烁了，有没有什么办法解决这个问题，只能关了onenote然后再切换一下输入法才能恢复正常。但是在onenote里面已然打不了字
> 
> 可以在选项->语言中将创作语言和校对 选项的英语设置为首选就没有问题了

感谢大佬

**Comment by uliuyt** [comment]
> > 感觉实际上是一个问题，用office365 word关闭的输入法控制，在word里面正常了，但是在onenote里面又开始闪烁了，有没有什么办法解决这个问题，只能关了onenote然后再切换一下输入法才能恢复正常。但是在onenote里面已然打不了字
> 
> 可以在选项->语言中将创作语言和校对 选项的英语设置为首选就没有问题了

我在win11上用的最新0.15版weasel，目前只会在OneNote中触发候选框闪烁的问题（触发后问题后，在word、edge浏览器上都闪烁，微信输入框不闪烁）😭。按照大佬的这个设置，会不会影响OneNote和其他Office套件的正常使用？
