### ISSUE TITLE
升级到 Windows 10 2020H2 以后，输入时按 w 键会导致当前程序崩溃

### ISSUE THREAD

**Issue by mmqmzk** [rime/weasel#580]
必然出现，例如在 Tim, Chrome 里面。
Weasel 本身没有出现错误日志。
尝试过重新安装 Weasel，问题依然存在。

**Comment by Kennnnnnji** [comment]
bug太严重了，项目组是不是弃坑了……

**Comment by lotem** [comment]
Windows 10 20H2、Chrome 88.0.4324.150、小狼毫0.14.3未重現問題。
