### ISSUE TITLE
关闭/打开输入法，ascii_mode会强制变为中文状态

### ISSUE THREAD

**Issue by tlannaax** [rime/weasel#581]
对于当前大多主流输入法而言，中英模式与打开/关闭输入法状态是统一的。
对于小狼毫并非如此，因而输入法会有三种状态，中，英 (ascii_mode off/on) ，以及输入法关闭状态(图标显示为x)。

当前行为：在英文模式下关闭输入法，再打开输入法，会被强制切换为中文模式。(若自行定制了默认英文模式也不会生效)
(应该是在0.11版本之前，打开输入法会恢复为关闭之前的状态)

为什么这是一个bug？先来看这几种状态的区别：

1. 中英模式切换可自行定制(左右shift，左右ctrl，capslock，内嵌英文，编码/候选上屏，清除编码等)
2. 英文模式下，输入法快捷键(以默认为例，如ctrl+`方案选单，ctrl+shift+12345切换输入法/中英/全半角/简繁/标点)仍然生效。当然这些快捷键也可定制。可以切换状态输入全角英文/标点。
3. 输入法关闭状态，则只能通过系统快捷键 (默认ctrl+space，可定制) 进行切换，切换行为似乎不可定制(只能清除编码)
4. 输入法关闭状态，所有输入法快捷键均不会生效。
5. 输入法关闭状态基本等于 英语/美式键盘，除了切换方式不同 (win+space，除键盘映射外不可定制)。若定制了默认英文，则使用win+space切换到小狼毫会进入英文模式。

 
相信对于大多数场景，可自行定制的中英模式切换是更好的中英混输方式。输入法关闭状态基本只在快捷键冲突(PS，IDE等，靠定制快捷键可以解决特定程序，但是除非完全取消快捷键，不然总是会有冲突)的情形有用。

当前的行为“打开输入法强制中文状态”可能是考虑到用户手工(ctrl+space)切换到打开状态**应该**是想要输入中文。但是：

1. 基于以上讨论，只使用中英切换或打开/关闭切换的一种已经足够满足多数需求。用户若同时手工进行中英切换及打开/关闭状态切换，必有其特定需求，如既需要方便的中英混输，又需要偶尔屏蔽快捷键。对于这种需求，打开输入法时想输入中文还是英文并不确定，程序不应该**自作聪明**的进行猜测，应该保持之前的状态方便用户预测。
2. 以gvim为代表的一些程序会利用系统api**自动**打开/关闭输入法。gvim中，进入normal mode会自动关闭输入法，进入insert mode (已 set iminsert=2 的情形下)会自动打开输入法，此时小狼毫会**强行进入中文模式**。若使用了某些在insert mode下会自动进入normal mode再返回的mapping或插件(如coc.nvim，autopair等)，则会导致英文模式被自动切换为中文模式。coc.nvim触发补全时就会导致此行为，导致强大的补全插件与小狼毫实际上无法共用。在这种应用程序自行打开/关闭输入法的情况下，打开输入法强制中文模式的行为就导致输入法的状态更加无法预测。

综上，希望能够采用旧版行为**打开输入法恢复为关闭之前的状态**。

**Comment by lotem** [comment]
不，沒有任何針對Control+space的特殊考慮。
因爲Rime不是專門爲Windows設計的，而Control+space禁用輸入法是Windows系統特有的行爲，Rime不處理這個按鍵。
之所以有這樣的表現，在Control+space切換之後，輸入法已經被系統重置，沒有之前的狀態了，因此重新初始爲默認狀態。而不是所謂根據Control+space切換而改變輸入模式。
如果樓主找到哪個舊版本有合適的行爲，或者有技術實現上的方案，請回帖告知。

**Comment by tlannaax** [comment]
> 不，沒有任何針對Control+space的特殊考慮。
> 因爲Rime不是專門爲Windows設計的，而Control+space禁用輸入法是Windows系統特有的行爲，Rime不處理這個按鍵。
> 之所以有這樣的表現，在Control+space切換之後，輸入法已經被系統重置，沒有之前的狀態了，因此重新初始爲默認狀態。而不是所謂根據Control+space切換而改變輸入模式。
> 如果樓主找到哪個舊版本有合適的行爲，或者有技術實現上的方案，請回帖告知。

已经退回到0.11.0版本的小狼毫进行过确认。在这个版本(IME或TSF均可)，英文模式按ctrl+space切换两次仍为英文模式，同样中文模式按ctrl+space切换两次仍为中文模式。因此最新版0.14.3的行为必然是一个bug。即便如楼上所说，新版中输入法被重置，那么为何在我设定了初始英文模式的前提下，使用win+space可以实现初始英文，使用ctrl+space却会被强制为初始中文呢？

0.11.0与0.14.3使用同一套配置文件测试，因此我认为大概率不是后端Rime，而是windows前端weasel的bug，这也是我把issue发在这里的原因。另外还测试了0.12.0，此bug已经开始出现，推测可能是合并IME与TSF时引入的新bug。

**Comment by Ace-Who** [comment]
GVim 下默认 iminsert=0 也会在进入 insert mode 时自动切换到中文状态。另外中文状态又时常会失效，即小狼毫图标显示为「中」而实际为英文状态，必须切换到非输入法状态，再切换回输入法状态，才能解决，bug 触发条件不明。

**Comment by tlannaax** [comment]
好像找到问题根源了。
@nameoverflow #232 #263 

> 最好还是不要把系统的输入法开关和 ascii_mode 混为一谈。
> 可以在关闭输入法时让语言栏显示成这样：
> ![image](https://user-images.githubusercontent.com/10287709/44894425-3d13c800-ad22-11e8-87be-4bec18be20a7.png)
> 
> 然后在重新开启输入法时强制将 ascii_mode 设为 FALSE。

以前加入输入法disable图标的时候添加了这个“重新开启输入法时强制将 ascii_mode 设为 FALSE“的行为。
现在希望不要将ascii_mode强制设为false，而是恢复为关闭输入法前的状态。

**Comment by idnsunset** [comment]
> 不，沒有任何針對Control+space的特殊考慮。
> 因爲Rime不是專門爲Windows設計的，而Control+space禁用輸入法是Windows系統特有的行爲，Rime不處理這個按鍵。
> 之所以有這樣的表現，在Control+space切換之後，輸入法已經被系統重置，沒有之前的狀態了，因此重新初始爲默認狀態。而不是所謂根據Control+space切換而改變輸入模式。
> 如果樓主找到哪個舊版本有合適的行爲，或者有技術實現上的方案，請回帖告知。

0.11 版本就没有问题。在 Insert 模式下是英文输入状态（ascii_mode = true），进入 Normal 再回到 Insert 时，依然是英文输入状态。另外也不存在 Normal 状态下键入 r，f 等 motion command 时会激活输入法。恢复到 0.11 版本的行为就行。

**Comment by YeMeiLiHui** [comment]
也有这方面的困惑，希望关闭输入法和再恢复时，不要改变之前的ascii_mode状态。

**Comment by superhxl** [comment]
一直关注这个问题，目前使用Rime输入法最大的痛苦就是在Vim中输入法总是会切换到中文。

**Comment by nobk** [comment]
> 一直关注这个问题，目前使用Rime输入法最大的痛苦就是在Vim中输入法总是会切换到中文。

在Windows 10语言设置中加上英语，输入法会增加一个英文键盘。然后改变自己的使用习惯从按Ctrl+space改为按Alt+shift，就能从根本上解决问题。在按过Alt+shift切换输入法为英文键盘后，使用Vim绝对不会和英语用户有任何差别，需要输入中文时再按Alt+shift就立即回到了RIME。

**Comment by nobk** [comment]
> 也有这方面的困惑，希望关闭输入法后再恢复时，不要改变之前的ascii_mode状态。

反对，理由见我的上一楼。如果我按Alt+shift切回中文输入法后，不能立即输入中文，会很麻烦，还需要记忆上一个状态，降低使用体验。

**Comment by YeMeiLiHui** [comment]
> > 也有这方面的困惑，希望关闭输入法后再恢复时，不要改变之前的ascii_mode状态。
> 
> 反对，理由见我的上一楼。如果我按Alt+shift切回中文输入法后，不能立即输入中文，会很麻烦，还需要记忆上一个状态，降低使用体验。

1、你还没理解到这个问题的实质。关闭输入法和切换输入法是两个不同的操作。切换输入法到RIME后ascii_mode状态是可以通过配置文件设置的。但关闭输入法后再打开输入法是无法通过配置文件设置的。
2、切换输入法只能通过你手动按键（比如Alt+shift），但关闭输入法除了WINDOWS的CTR+SPACE来切换，也可以由当前程序软关闭（无需使用者有任何操作）。
3、这个问题的痛点是，当使用者在某些程序中使用RIME的英文输入的时候，有些界面，程序自动关闭（不是切换）了RIME输入法，等鼠标进入某些编辑框进行输入时，程序会自动又打开RIME，但这时的RIME没有记住之前的英文状态，默认设置为中文，而这时的中文不是我期待的。
4、问题的关键就是，这个过程中我压根没进行任何操作，但输入法被从英文调成了中文。
5、解决的关键就是希望RIME能记住“关闭输入法”之前的ascii_mode状态，并在再次打开输入法时，恢复这个状态。
6、更理想的解决方式是：输入法由程序关闭再打开时，记住ascii_mode状态；但由使用者手动关闭输入法（比如CTR+SPACE）再打开时，默认设置为中文（因为使用者手动打开RIME，目的一定是中文输入）。

**Comment by nobk** [comment]
@YeMeiLiHui 所以我就不使用这个不可靠的RIME英文状态啊，不需要中文输入的时候，我不用单击Shift或者WIN7以前的使用习惯按CTRL+SPACE让RIME到英文输入状态，因为windows 10的Ctrl+SPACE功能语义完全和以前的版本不同了，我改变自己的习惯（需要大概一周时间），忘记了CTRL+SPACE，永远不去按它。如果你实在忘不了CTRL+SPACE，而且不玩网游，可以用ahk将CTRL+SPACE按键组合映射为ALT+SHFIT。
而在英语键盘下，无论程序自动关闭还是打开IME，它都是英语，不会有任何意外。

**Comment by nobk** [comment]
@YeMeiLiHui 这是我的AHK脚本，按Ctrl+space出Alt+shift

```
;^Space::#Space
^Space::
KeyWait Space
KeyWait Ctrl
Send {LAlt Down}{RShift}{LAlt Up}
Return

```

**Comment by YeMeiLiHui** [comment]
@nobk 可能是我太迷恋SHIFT键了吧。我目前的解决办法跟你一样，添加一个简体英文键盘，通过切换键盘来使用英文输入。
但还是希望RIME的英文输入上能更完美，这样我就可以一个键盘方案和一个输入法就够了，也可以只用一个键（SHIFT）就能切换中英输入方式了。

**Comment by nobk** [comment]
按SHFIT改成Alt+SHIFT其实动作上并没增加多少，什么都不用安装修改就解决了。
都是微软产品经理干的坏事，不应该都推给输入法解决。

> @nobk 可能是我太迷恋SHIFT键了吧。我目前的解决办法跟你一样，添加一个简体英文键盘，通过切换键盘来使用英文输入。
> 但还是希望RIME的英文输入上能更完美，这样我就可以一个键盘方案和一个输入法就够了，也可以只用一个键（SHIFT）就能切换中英输入方式了。

**Comment by nobk** [comment]
@YeMeiLiHui 要是能提供一个可选项，两者都支持，其实我也没意见。

**Comment by superhxl** [comment]
> 不，沒有任何針對Control+space的特殊考慮。
> 因爲Rime不是專門爲Windows設計的，而Control+space禁用輸入法是Windows系統特有的行爲，Rime不處理這個按鍵。
> 之所以有這樣的表現，在Control+space切換之後，輸入法已經被系統重置，沒有之前的狀態了，因此重新初始爲默認狀態。而不是所謂根據Control+space切換而改變輸入模式。
> 如果樓主找到哪個舊版本有合適的行爲，或者有技術實現上的方案，請回帖告知。

你好，我测试了一下在gvim中如果不加载vim插件，可以愉快的使用rime输入中英文。请问，据你所知除了coc和autopair外，youcomplteme是否也会导致失效？还有没有其他的插件。我再考虑是否从gvim插件入手，避开此类插件。我目前使用的插件包括：ctrlp，vim-airline，ale，indentline，autopairs，nerdcommenter，ultisnips，vim-snippetrs，vim-template，coc，fastfold

**Comment by superhxl** [comment]
> 对于当前大多主流输入法而言，中英模式与打开/关闭输入法状态是统一的。
> 对于小狼毫并非如此，因而输入法会有三种状态，中，英 (ascii_mode off/on) ，以及输入法关闭状态(图标显示为x)。
> 
> 当前行为：在英文模式下关闭输入法，再打开输入法，会被强制切换为中文模式。(若自行定制了默认英文模式也不会生效)
> (应该是在0.11版本之前，打开输入法会恢复为关闭之前的状态)
> 
> 为什么这是一个bug？先来看这几种状态的区别：
> 
> 1. 中英模式切换可自行定制(左右shift，左右ctrl，capslock，内嵌英文，编码/候选上屏，清除编码等)
> 2. 英文模式下，输入法快捷键(以默认为例，如ctrl+`方案选单，ctrl+shift+12345切换输入法/中英/全半角/简繁/标点)仍然生效。当然这些快捷键也可定制。可以切换状态输入全角英文/标点。
> 3. 输入法关闭状态，则只能通过系统快捷键 (默认ctrl+space，可定制) 进行切换，切换行为似乎不可定制(只能清除编码)
> 4. 输入法关闭状态，所有输入法快捷键均不会生效。
> 5. 输入法关闭状态基本等于 英语/美式键盘，除了切换方式不同 (win+space，除键盘映射外不可定制)。若定制了默认英文，则使用win+space切换到小狼毫会进入英文模式。
> 
> 相信对于大多数场景，可自行定制的中英模式切换是更好的中英混输方式。输入法关闭状态基本只在快捷键冲突(PS，IDE等，靠定制快捷键可以解决特定程序，但是除非完全取消快捷键，不然总是会有冲突)的情形有用。
> 
> 当前的行为“打开输入法强制中文状态”可能是考虑到用户手工(ctrl+space)切换到打开状态**应该**是想要输入中文。但是：
> 
> 1. 基于以上讨论，只使用中英切换或打开/关闭切换的一种已经足够满足多数需求。用户若同时手工进行中英切换及打开/关闭状态切换，必有其特定需求，如既需要方便的中英混输，又需要偶尔屏蔽快捷键。对于这种需求，打开输入法时想输入中文还是英文并不确定，程序不应该**自作聪明**的进行猜测，应该保持之前的状态方便用户预测。
> 2. 以gvim为代表的一些程序会利用系统api**自动**打开/关闭输入法。gvim中，进入normal mode会自动关闭输入法，进入insert mode (已 set iminsert=2 的情形下)会自动打开输入法，此时小狼毫会**强行进入中文模式**。若使用了某些在insert mode下会自动进入normal mode再返回的mapping或插件(如coc.nvim，autopair等)，则会导致英文模式被自动切换为中文模式。coc.nvim触发补全时就会导致此行为，导致强大的补全插件与小狼毫实际上无法共用。在这种应用程序自行打开/关闭输入法的情况下，打开输入法强制中文模式的行为就导致输入法的状态更加无法预测。
> 
> 综上，希望能够采用旧版行为**打开输入法恢复为关闭之前的状态**。

你好，我测试了一下在gvim中如果不加载vim插件，可以愉快的使用rime输入中英文。请问，据你所知除了coc和autopair外，youcomplteme是否也会导致失效？还有没有其他的插件。我再考虑是否从gvim插件入手，避开此类插件。我目前使用的插件包括：ctrlp，vim-airline，ale，indentline，autopairs，nerdcommenter，ultisnips，vim-snippetrs，vim-template，coc，fastfold

**Comment by tlannaax** [comment]
> 你好，我测试了一下在gvim中如果不加载vim插件，可以愉快的使用rime输入中英文。请问，据你所知除了coc和autopair外，youcomplteme是否也会导致失效？还有没有其他的插件。我再考虑是否从gvim插件入手，避开此类插件。我目前使用的插件包括：ctrlp，vim-airline，ale，indentline，autopairs，nerdcommenter，ultisnips，vim-snippetrs，vim-template，coc，fastfold

问题根源不在于插件。我开issue的时候已经说的很清楚了，只要从insert返回normal再进入insert就会重置中文。即使不用插件，中英混输加修改编辑的情况也很常见，比如改带中文，中文注释的代码（说的就是你rime的配置文件！）。自行定义一个imap，比如 imap \<M-B\> \<ESC\>bi，就可以重现这个bug，打断在insert模式中的英文状态。你所谓的愉快的输入中英文，可能只有前期专心输入不做修改的时候没问题。
一个插件完全不定义从insert临时切换normal执行一些命令的mapping和宏才能避免这个bug。这种插件要么完全不在insert模式工作，要么完全在insert模式工作。稍微有点复杂逻辑的补全插件就避免不了这个bug，特别是coc和autopair。

**Comment by idnsunset** [comment]
用Vim写代码这种基本用不到中文的情况下，按什么组合键切换都无所谓，反正极少用到。但是用Vim写大篇幅的中文文档时，就很痛苦了。单个Shift键一定比 Alt+Shift这种组合键高效的多，尤其是在输入（Insert mode）和编辑（Normal mode）频繁切换的情况下。为什么 0.11版本完全正常，到了0.12开始就不行了？

**Comment by idnsunset** [comment]
> > 对于当前大多主流输入法而言，中英模式与打开/关闭输入法状态是统一的。
> > 对于小狼毫并非如此，因而输入法会有三种状态，中，英 (ascii_mode off/on) ，以及输入法关闭状态(图标显示为x)。
> > 当前行为：在英文模式下关闭输入法，再打开输入法，会被强制切换为中文模式。(若自行定制了默认英文模式也不会生效)
> > (应该是在0.11版本之前，打开输入法会恢复为关闭之前的状态)
> > 为什么这是一个bug？先来看这几种状态的区别：
> > 
> > 1. 中英模式切换可自行定制(左右shift，左右ctrl，capslock，内嵌英文，编码/候选上屏，清除编码等)
> > 2. 英文模式下，输入法快捷键(以默认为例，如ctrl+`方案选单，ctrl+shift+12345切换输入法/中英/全半角/简繁/标点)仍然生效。当然这些快捷键也可定制。可以切换状态输入全角英文/标点。
> > 3. 输入法关闭状态，则只能通过系统快捷键 (默认ctrl+space，可定制) 进行切换，切换行为似乎不可定制(只能清除编码)
> > 4. 输入法关闭状态，所有输入法快捷键均不会生效。
> > 5. 输入法关闭状态基本等于 英语/美式键盘，除了切换方式不同 (win+space，除键盘映射外不可定制)。若定制了默认英文，则使用win+space切换到小狼毫会进入英文模式。
> > 
> > 相信对于大多数场景，可自行定制的中英模式切换是更好的中英混输方式。输入法关闭状态基本只在快捷键冲突(PS，IDE等，靠定制快捷键可以解决特定程序，但是除非完全取消快捷键，不然总是会有冲突)的情形有用。
> > 当前的行为“打开输入法强制中文状态”可能是考虑到用户手工(ctrl+space)切换到打开状态**应该**是想要输入中文。但是：
> > 
> > 1. 基于以上讨论，只使用中英切换或打开/关闭切换的一种已经足够满足多数需求。用户若同时手工进行中英切换及打开/关闭状态切换，必有其特定需求，如既需要方便的中英混输，又需要偶尔屏蔽快捷键。对于这种需求，打开输入法时想输入中文还是英文并不确定，程序不应该**自作聪明**的进行猜测，应该保持之前的状态方便用户预测。
> > 2. 以gvim为代表的一些程序会利用系统api**自动**打开/关闭输入法。gvim中，进入normal mode会自动关闭输入法，进入insert mode (已 set iminsert=2 的情形下)会自动打开输入法，此时小狼毫会**强行进入中文模式**。若使用了某些在insert mode下会自动进入normal mode再返回的mapping或插件(如coc.nvim，autopair等)，则会导致英文模式被自动切换为中文模式。coc.nvim触发补全时就会导致此行为，导致强大的补全插件与小狼毫实际上无法共用。在这种应用程序自行打开/关闭输入法的情况下，打开输入法强制中文模式的行为就导致输入法的状态更加无法预测。
> > 
> > 综上，希望能够采用旧版行为**打开输入法恢复为关闭之前的状态**。
> 
> 你好，我测试了一下在gvim中如果不加载vim插件，可以愉快的使用rime输入中英文。请问，据你所知除了coc和autopair外，youcomplteme是否也会导致失效？还有没有其他的插件。我再考虑是否从gvim插件入手，避开此类插件。我目前使用的插件包括：ctrlp，vim-airline，ale，indentline，autopairs，nerdcommenter，ultisnips，vim-snippetrs，vim-template，coc，fastfold

跟插件没有任何关系，即使一个插件都没加载，一样有问题。

**Comment by oopp1800** [comment]
#567 似乎也是同样的原因造成的，因为 Quicker 会暂时关闭并重新开启输入法，导致小狼毫变为中文输入

**Comment by slbb** [comment]
> 不，沒有任何針對Control+space的特殊考慮。
> 因爲Rime不是專門爲Windows設計的，而Control+space禁用輸入法是Windows系統特有的行爲，Rime不處理這個按鍵。
> 之所以有這樣的表現，在Control+space切換之後，輸入法已經被系統重置，沒有之前的狀態了，因此重新初始爲默認狀態。而不是所謂根據Control+space切換而改變輸入模式。
> 如果樓主找到哪個舊版本有合適的行爲，或者有技術實現上的方案，請回帖告知。

即使不考虑 windows api 的问题。小狼毫的 weasel.custom.yaml 是可以设置特定 exe 窗口下的 ascii_mode 默认开/关的，如果禁用再启用，应该根据 weasel.custom.yaml 的设置来决定。
但是我实验过，在 weasel.custom.yaml 设置了 xxx.exe 窗口下 ascii_mode 默认打开，平常是生效的，但是在禁用再启用之后，小狼毫就会无视这个设定切换到中文状态。

**Comment by winstarst** [comment]
> > > 也有这方面的困惑，希望关闭输入法后再恢复时，不要改变之前的ascii_mode状态。
> > 
> > 
> > 反对，理由见我的上一楼。如果我按Alt+shift切回中文输入法后，不能立即输入中文，会很麻烦，还需要记忆上一个状态，降低使用体验。
> 
> 1、你还没理解到这个问题的实质。关闭输入法和切换输入法是两个不同的操作。切换输入法到RIME后ascii_mode状态是可以通过配置文件设置的。但关闭输入法后再打开输入法是无法通过配置文件设置的。
> 2、切换输入法只能通过你手动按键（比如Alt+shift），但关闭输入法除了WINDOWS的CTR+SPACE来切换，也可以由当前程序软关闭（无需使用者有任何操作）。
> 3、这个问题的痛点是，当使用者在某些程序中使用RIME的英文输入的时候，有些界面，程序自动关闭（不是切换）了RIME输入法，等鼠标进入某些编辑框进行输入时，程序会自动又打开RIME，但这时的RIME没有记住之前的英文状态，默认设置为中文，而这时的中文不是我期待的。
> 4、问题的关键就是，这个过程中我压根没进行任何操作，但输入法被从英文调成了中文。
> 5、解决的关键就是希望RIME能记住“关闭输入法”之前的ascii_mode状态，并在再次打开输入法时，恢复这个状态。
> 6、更理想的解决方式是：输入法由程序关闭再打开时，记住ascii_mode状态；但由使用者手动关闭输入法（比如CTR+SPACE）再打开时，默认设置为中文（因为使用者手动打开RIME，目的一定是中文输入）。

说的太对了，三个事情要分清楚：

1、不同输入法之间切换， Alt + Shift 
2、单个输入法的关闭和打开，Ctrl + Space
3、单个输入法的中英文状态切换，一般是 Shift 

Rime 在 GVIM 中的问题就是**中英文状态没有起作用，只能关闭和打开输入法，但打开之后默认是英文，没办法输入中文**，导致的问题就是：

1、Insert 模式，中文输入，此时中英文状态为中文；
2、Esc 为 Normal 模式，上下左右调整输入的位置，此时 Rime 被关闭（此项可在 GVIM 通过 set iminsert=2 配置）；
3、i 重新进入 Insert 模式，此时 Rime 输入法重新打开，默认为英文，**必须再按 Shift 进入中文状态**。

**Comment by HaoHao-Ting** [comment]
不知道现在问题解决了没有，看到上述有些解决方案。准备有时间尝试一下。我在使用NeoVim还有Visual Studio Code 的Vim插件。如果带自动切换输入法的，都会重置Rime到中文状态，每次都需要多按一个Shift。现在的解决方案不用切换插件。然后只有Rime，然后人工切换，至少思路不会被打断。缺点是一直要手动切换输入法。这样很麻烦。要是能记录切换前的Rime的ascii_mode就好了

**Comment by Gowa2017** [comment]
我用 vscode 是，总是给我切到英文状态。。。。非常的纳闷。

**Comment by draftman9** [comment]
其实也不一定要看字，看颜色就可以了。

**Comment by wliu88ca** [comment]
keepass 也有这个问题，英文状态下所有地方强制给我转换成中文输入

**Comment by zhuzhzh** [comment]
我用vsc的neovim mode， 中英文切换也是非常麻烦

**Comment by madjxatw** [comment]
没想到这个issue开了两年都没解决，vim重度用户在Windows平台已经放弃rime了。

**Comment by zhylmzr** [comment]
这里有一个[pull](https://github.com/rime/weasel/pull/856#issuecomment-1514041586)解决了这个问题

**Comment by fxliang** [comment]
fixed by #1096

**Comment by liuliping0315** [comment]
> > 也有这方面的困惑，希望关闭输入法后再恢复时，不要改变之前的ascii_mode状态。
> 
> 反对，理由见我的上一楼。如果我按Alt+shift切回中文输入法后，不能立即输入中文，会很麻烦，还需要记忆上一个状态，降低使用体验。

我和你习惯是一样的，我有不会轻易变化的英文语言用来敲命令行（我用shift敲大写字母），和一个可以变化的搜狗/RIME。中文打字时，至多两次win+space 或者 alt+shift就能找到中文输入法。而微软拼音会记住ascii mode，按一辈子也找不到中文。
