### ISSUE TITLE
Bug? 求助：定义模糊音之后特定编码没有候选词

### ISSUE THREAD

**Issue by Y-Shy** [rime/weasel#582]
平台：Rime weasel-0.14.3 on Win10，输入方案 luna_pinyin_simp.

根据 [wiki: 模糊音](https://github.com/rime/home/wiki/CustomizationGuide#%E6%A8%A1%E7%B3%8A%E9%9F%B3) 和 [【朙月拼音】模糊音定製模板](https://gist.github.com/lotem/2320943)，当在luna_pinyin_simp.custom.yaml中的patch下添加模糊音设置语句后：
 ```
  'speller/algebra':
    - erase/^xx$/                      # 第一行保留

    # 自動糾正一些常見的按鍵錯誤
    - derive/([aeiou])ng$/$1gn/        # dagn => dang 
    - derive/([dtngkhrzcs])o(u|ng)$/$1o/  # zho => zhong|zhou
    - derive/ong$/on/                  # zhonguo => zhong guo
    - derive/ao$/oa/                   # hoa => hao
    - derive/([iu])a(o|ng?)$/a$1$2/    # tain => tian
```

会出现有些编码（拼音）没有候选词的现象，比如在中文状态下输`my`（“没有”的拼音缩写），看不到候选词。

注释掉上面的模糊音设置语句然后重新部署，再在中文状态下输`my`则能看到候选词。如图：
![Snipaste_2020-11-18](https://user-images.githubusercontent.com/55436543/99537570-d0f70a80-29e6-11eb-8b2b-4d661b392939.png)

**Comment by lotem** [comment]
應該不是模糊音設置導致的問題。請排查同時進行的其他修改。

**Comment by Y-Shy** [comment]
> 應該不是模糊音設置導致的問題。請排查同時進行的其他修改。

wc大神亲自回复了....明天排查试试，怀疑可能是添加了含有英语的词库

**Comment by lotem** [comment]
[不要](https://github.com/rime/librime/issues/72)在拼音词库里加入拼音以外的编码。

**Comment by Y-Shy** [comment]
> 
> 
> [不要](https://github.com/rime/librime/issues/72)在拼音词库里加入拼音以外的编码。

很详细的讨论。。。然而当我在luna_pinyin_simp.custom.yaml中仅添加模糊音定义，不进行其他设置时，
* 在luna_pinyin.my.dict.yaml中仅import luna_pinyin，仍有 特定编码没有候选词的问题；
* 在luna_pinyin.my.dict.yaml中什么都不import的时候，任何编码都没有了候选词；
    ↓
* 不是luna_pinyin以外其他词库的问题，也许是luna_pinyin缺少了对my等特定编码的解释？以下是上面排查的配置文件：
luna_pinyin_simp.custom.yaml
```
# luna_pinyin_simp.custom.yaml
patch:
  "translator/dictionary": luna_pinyin.my   # 指定自定义词库位置
  
  'speller/algebra':
    - erase/^xx$/                      # 第一行保留
    
    # 自動糾正一些常見的按鍵錯誤
    - derive/([aeiou])ng$/$1gn/        # dagn => dang 
    - derive/([dtngkhrzcs])o(u|ng)$/$1o/  # zho => zhong|zhou
    - derive/ong$/on/                  # zhonguo => zhong guo
    - derive/ao$/oa/                   # hoa => hao
    - derive/([iu])a(o|ng?)$/a$1$2/    # tain => tian
    
    # Nothing more
```

luna_pinyin.my.dict.yaml
```
---
name: luna_pinyin.my
version: "2020.11.14"
sort: by_weight
use_preset_vocabulary: true
# 此处为扩充词库（基本）默认链接载入的词库
import_tables:
  - luna_pinyin     # 從 luna_pinyin.dict.yaml 導入包含單字的碼表
...
# Nothing more
```

（luna_pinyin.dict.yaml不是我创建的文件，用户文件夹里也没有，./weasel/data\文件夹倒是有的，有教程说import它则能导入包含单字的码表）

**Comment by lotem** [comment]
`my` 不是正確的拼音。（你是不是要輸入`mi` 或者 `mai`？）
拼音詞庫裏沒有這個編碼，模糊音規則也沒有定義這個拼寫形式，所以不會有候選詞。

**Comment by Y-Shy** [comment]
> 
> 
> `my` 不是正確的拼音。（你是不是要輸入`mi` 或者 `mai`？）
> 拼音詞庫裏沒有這個編碼，模糊音規則也沒有定義這個拼寫形式，所以不會有候選詞。

不是——`my` 是“没有”的拼音缩写；添加模糊音不是想用来修正`my` 的，添加模糊音之前`my` 还是有候选词的，加了就没了。
