### ISSUE TITLE
鼠标选取候选词

### ISSUE THREAD

**Issue by jieekie** [rime/weasel#583]
weasel-0.14.3，
1.无法用鼠标选取候选词，点击之后无效。
2.微信3.0.0.47，用鼠标选取候选词后（也不会输入），输入法无法继续输入。需要重新打开微信输入框才能正常输入。

**Comment by nukupanda** [comment]
我也遇到了这个问题，版本weasel-0.14.3，鼠标点击候选框，就不能输入中文了，切换电脑界面才可以恢复正常，或者手动重新拉起“小狼毫算法服务”。

**Comment by nukupanda** [comment]
我也遇到了这个问题，版本weasel-0.14.3，鼠标点击候选框，就不能输入中文了，切换电脑界面才可以恢复正常，或者手动重新拉起“小狼毫算法服务”。

**Comment by tyf2018** [comment]
> weasel-0.14.3，
> 1.无法用鼠标选取候选词，点击之后无效。
> 2.微信3.0.0.47，用鼠标选取候选词后（也不会输入），输入法无法继续输入。需要重新打开微信输入框才能正常输入。

遇到此问题+1

**Comment by zjsailor** [comment]
在word 2016中用，鼠标取词的话，整个word直接崩溃。

**Comment by fxliang** [comment]
0.15.0（最低系统要求Windows 8.1）起，已实现该功能
