### ISSUE TITLE
Rime假死！（四处bug）

### ISSUE THREAD

**Issue by iesv** [rime/weasel#585]
一、win10 1809 x64系统（LTSC2019），打开“用户文件夹”或“程序文件夹”桌面有时会假死。
二、在黑暗模式下，菜单的有时是黑色，有时是白色。
三、gvim复制粘贴时，英文状态会变成中文状态。
四、/fh不能使用。

**Comment by c6767** [comment]
win10 ltsc2019 64位，从右下角的图标打开“用户文件夹”或“程序文件夹”桌面卡死过一两次，毕竟已经用了四五个月了。

**Comment by iesvme** [comment]
对，我的系统和你一样。三台电脑也都是这样。

**Comment by yuhixyz** [comment]
win10 20H2 问题同上

**Comment by fxliang** [comment]
问题1 已修复，问题2因为语言栏的主题依赖当前激活应用如果激活应用不支持暗色主题那是没办法的，问题3已修复 问题4是什么功能？
