### ISSUE TITLE
建议新版只支持Win10。旧版系统早被淘汰，旧瓶装新酒，不好。

### ISSUE THREAD

**Issue by iesvme** [rime/weasel#587]
建议新版只支持Win10。旧版系统早被淘汰，旧瓶装新酒，不好。

**Comment by ted423** [comment]
Win10反而不怎么需要装输入法。
反而是Win7需求才会比较强烈

**Comment by xtay573269555** [comment]
> 
> 
> 建议新版只支持Win10。旧版系统早被淘汰，旧瓶装新酒，不好。

早被淘汰？井底之蛙

**Comment by cyh0** [comment]
win7包括之前的微软都停止维护了，的确不用花太多心思去兼容，而且win11都要来了，以后主力放在win10和win11，老系统就用旧版本吧。
