### ISSUE TITLE
与IDEA编辑器的快捷键冲突

### ISSUE THREAD

**Issue by szhgoldeneye** [rime/weasel#59]
使用小狼毫时，在IDEA里Reformat代码时，快捷键`Ctrl+Alt+L`无效

注释掉default.yaml中的几个hotkeys也没有用

**Comment by lotem** [comment]
抱歉。暫時無力調查這個問題。

**Comment by wuwenyao** [comment]
我也有这个问题

**Comment by panpsky** [comment]
我也有这个问题，而且不知道小狼毫哪个功能占用了Ctrl+Alt+L还是怎么的。
求解决。

**Comment by panpsky** [comment]
@wuwenyao @szhgoldeneye 可以在IDEA下使用Ctrl+Shift+Alt+L这个快捷键格式化代码。

**Comment by codethereforam** [comment]
我也有这个问题

**Comment by panpsky** [comment]
@codethereforam 用Ctrl+Shift+Alt+L格式化吧. 暂时切到win10自带的输入法了,能凑合着用, 虽然比rime差很多, 但是好在兼容性还可以, 而且联想词库比rime挂载词库稍微好一点儿.

**Comment by codethereforam** [comment]
@panpsky 谢谢，目前用Ctrl+Shift+Alt+L解决

**Comment by fan123199** [comment]
还有reformat的快捷键也失效， Ctrl+Alt+R

**Comment by Prcuvu** [comment]
快捷键冲突的话，也需要考虑其他应用是否占用快捷键。暂时无法确定，先关闭了。

**Comment by GitHubllj2018** [comment]
bye

**Comment by BlackTomm** [comment]
个人选择使用了luna_pinyin_simp，也存在大量快捷键被绑定问题，于是注释掉了程序文件夹下data内luna_pinyin_simp.schema.yaml文件的 import_preset: default，重新部署后解决问题，应该可以通过修改对应的*.schema.yaml解除快捷键绑定
