### ISSUE TITLE
小狼毫输入法自动复制粘贴已有内容

### ISSUE THREAD

**Issue by syusuyly** [rime/weasel#595]
Amazing Marvin 是一个任务管理软件，小狼毫在其网页端和桌面端均无法正常键入，而切换至 Microsoft Pinyin 则表现正常，软件网页端的地址为 https://app.amazingmarvin.com/ 。
错误表现为添加任务时无法使用 Rime 输入法键入任何内容，不出现候选框，编辑已有任务时每次敲击会复制粘贴输入框前所有非空格分隔的所有文本内容。例如输入框内已有「中国 2020年12月31日」，切换至 Rime 输入法后将输入「2020年12月31日」。

**Comment by Syusyuly** [comment]
已注册一个临时账户帮助 Rime 开发团队 Debug，希望能够解决此问题
账户：jud05393@zwoho.com
密码：jud05393@zwoho.com
