### ISSUE TITLE
在魔兽世界中，Rime不显示已输入的字符

### ISSUE THREAD

**Issue by Humwq** [rime/weasel#596]
在魔兽世界中，Rime不显示已输入的字符；只选择候选词。
![图片](https://user-images.githubusercontent.com/9313456/102384285-81b4f180-4007-11eb-8df5-15aa643d9590.png)

**Comment by Humwq** [comment]
版本:小狼毫 0.14.3

**Comment by qingyaoyao789** [comment]
搜狗输入法正常，华宇输入法也存在这个问题。

**Comment by Humwq** [comment]
国内常见的输入法基本都没问题  什么QQ 百度 都没问题的  包括win10自带的拼音输入法.
这么大个问题，怎么没人提呢？
难道都是不打游戏的?全都是桌面用户，不需要在其他程序里使用输入法的吗？

**Comment by lotem** [comment]
該不是需要設置爲內嵌編碼行？

對不打這個遊戲的人來說不算啥大問題。
可能問題出在本品稱不上「國內常見的輸入法」。既是我等數人業餘的作品，可比不了大公司養着一個開發團隊有專人解決兼容遊戲的問題。恐怕真得某個用家恰巧玩這款遊戲，自身又是Windows編程高手，大神一個不爽，順手就解決了。

**Comment by Humwq** [comment]
是这样的嘛
那么，有什么好的解决方案呢？

**Comment by lotem** [comment]
> 是这样的嘛
> 那么，有什么好的解决方案呢？

打開「[內嵌編碼](https://github.com/rime/home/wiki/CustomizationGuide#%E5%B0%8F%E7%8B%BC%E6%AF%AB%E5%A4%96%E8%A7%80%E8%A8%AD%E5%AE%9A)」試試？

**Comment by Humwq** [comment]
OK  能用了  看起来没问题了

**Comment by qingyaoyao789** [comment]
确实可以了，赞一个。其它输入法可以删了。

**Comment by lotem** [comment]
> OK 能用了 看起来没问题了

> 确实可以了，赞一个。其它输入法可以删了。

怎麼解決的？

**Comment by Humwq** [comment]
Wow.exe

**Comment by Humwq** [comment]
就是  打開「內嵌編碼」啊  
重新部署完后  进游戏就可以显示了

**Comment by lotem** [comment]
那可以設置爲在這個程序裏打開。
