### ISSUE TITLE
当候选框在输入的上方时，会遮盖一部分输入的文字

### ISSUE THREAD

**Issue by VimWei** [rime/weasel#597]
在屏幕底部输入时，候选框会在上部，此时，会遮盖一部分输入的文字，特别是当  "style/inline_preedit": true 时，很不方便。

请教该如何设置候选框与输入的距离？ demo 看图：

![image](https://user-images.githubusercontent.com/25874852/102651003-b57a4d80-41a6-11eb-934f-c097b2a67e6c.png)

**Comment by fxliang** [comment]
最新Nightly构建已修复
