### ISSUE TITLE
如何避免部署时自动将 luna_pinyin.schema.yaml 等文件删除

### ISSUE THREAD

**Issue by BavonChao** [rime/weasel#598]
Windows 作业系统在重新部署输入法时会将 luna_pinyin.schema.yaml 和 default.yaml 等配置文件移入 trash 资料夹。我在使用中会将配置文件整体备份起来，供Windows和Linux使用，Windows下这个行为会让Linux下使用产生麻烦，请问有没有办法避免这个行为。

**Comment by lotem** [comment]
這些文件由輸入法負責維護並升級，請避免手動編輯。
參考： https://github.com/rime/home/issues/301#issuecomment-453763075

**Comment by BavonChao** [comment]
> 
> 
> 這些文件由輸入法負責維護並升級，請避免手動編輯。
> 參考： [rime/home#301 (comment)](https://github.com/rime/home/issues/301#issuecomment-453763075)

如果设定档中没有default.yaml文件，Linux下使用fcitx-rime是否能够正确部署？

**Comment by BavonChao** [comment]
> 
> 
> > 這些文件由輸入法負責維護並升級，請避免手動編輯。
> > 參考： [rime/home#301 (comment)](https://github.com/rime/home/issues/301#issuecomment-453763075)
> 
> 如果设定档中没有`default.yaml`和`luna_pinyin.schema.yaml`文件，Linux下使用fcitx-rime是否能够正确部署？

我回头在Linux机器上测试一下，谢谢回复

**Comment by lotem** [comment]
> > 這些文件由輸入法負責維護並升級，請避免手動編輯。
> > 參考： [rime/home#301 (comment)](https://github.com/rime/home/issues/301#issuecomment-453763075)
> 
> 如果设定档中没有`default.yaml`和`luna_pinyin.schema.yaml`文件，Linux下使用fcitx-rime是否能够正确部署？

https://github.com/rime/home/wiki/UserData 和 https://github.com/rime/home/wiki/SharedData 兩處都沒有 `default.yaml` 則輸入法無法正常工作。是否需要 `luna_pinyin.schema.yaml` 取決於是否啟用了該輸入方案。

**Comment by BavonChao** [comment]
经过测试，Linux下上述两个文件删除后重新部署会自动生成，所以即使配置资料夹中没有上述两个文件也不影响正常部署。
