### ISSUE TITLE
错误：“服务进程启动不起来:("

### ISSUE THREAD

**Issue by zky999** [rime/weasel#60]
OS：Windows 10 x64
小狼毫版本：0.9.30.0
错误情景再现：双击打开MS word文件时（关联Word 2016），小狼毫弹出提示错误。
截图如下：
![err](https://cloud.githubusercontent.com/assets/2784820/17433193/d6204f3c-5b35-11e6-9557-f31ea80acbc6.png)

**Comment by Prcuvu** [comment]
参见：[小狼毫前端的兼容性問題將不再修復] (https://github.com/rime/home/issues/25)

**Comment by Prcuvu** [comment]
小狼毫更新后去掉了自动激活服务程序的功能，这个问题不再有效。
