### ISSUE TITLE
功能需求：希望增加打汉字输出拼音(含声调符号)的功能

### ISSUE THREAD

**Issue by nobk** [rime/weasel#601]
启用该功能后，无论用什么输入法(拼音、五笔、仓颉、注音)打出汉字后，不输出汉字而是输出汉字对应的含声调汉语拼音。
例如输入“考验”，输出“kǎoyàn”；输入“西安”，输出“Xī'ān”。
希望新增这个功能的理由是，目前还没有一种能迅速输出带声调拼音字母的输入软件，导致大部分人不愿意为拼音配上声调，无法更准确的使用拼音。

例如：
I come from Ch**ā**ngpíng(昌平). 
和 
I come from Ch**á**ngpíng(长平).
显然是两个地点，因为目前没有方便的拼音输出方法，统统被写为：
I come from Changping.
从而无法区分。

人名更是如此：
汪峰 王峰 王凤 旺封
wāngfēng wángfēng wángfèng wàngfēng
统统都是wangfeng，无法区分。

例句：王峰和王凤是两兄妹，他们都是汪峰的歌迷。
Wang Feng and Wang Feng are two siblings, they are both Wang Feng's fans. 
无区分，不知道在说什么，哪怕是华人都读不懂，一切都只能靠猜。
Wáng Fēng and Wáng Fèng are two siblings, they are both Wāng Fēng's fans.
有区分，峰和凤声调不同，王和汪声调不同。老外能看出区别来：这是三个不同的人名，华人甚至能猜出具体的名字。

输出可选方案，最好能支持多种输出格式：

- 格式1、只输出拼音，例如：kǎoyàn

- 格式2、输出字词并且在中括号内输出拼音，例如：烎[yín] 饕餮[tāotiè] 猰貐[yàyǔ]。
常用于为某字词注明拼音读法，方括号是标注音标的国际通用符号，各国字典均采用这种排版。

- 格式3、输出拼音并且在圆括号内输出字词，例如：Xiàmén(厦门)。
常用于在英语或其它外语句子中的汉语拼音并且备注对应中文字词，拼音放前面有利于英语整句的阅读连贯性。例句：
The last stop of my trip is Xiàmén(厦门).
The name of this instrument is Gǔzhēng(古筝).

其他输出格式欢迎补充。

增强功能，能够以词确定多音字的选音选调，例如多音字“长”：长安[**Cháng**'ān] 成长[chéng**zhǎng**]。
以及地名、人名的姓、名首字母自动大写，例如：成都[Chéngdū] 李子柒[Lǐ Zǐqī]。通过热键为windows剪贴板中的汉字整句输出全部对应拼音的功能等等。

最好还能提供打字母及调号出带声调拼音的功能，以便不会汉字输入的外国人书写带声调拼音。

**Comment by Ace-Who** [comment]
1. 可通过具体方案实现。
1. 消歧义不是一个依靠带调拼音交流的充分理由，因为带调拼音远不足以消歧义。

**Comment by nobk** [comment]
> 2. 消歧义不是一个依靠带调拼音交流的充分理由，因为带调拼音远不足以消歧义。

是的，但带调拼音至少在汉语读音上是信息完备的了，对应中文的含义存在多个映射那是语言学层面的问题无需输入法来解决，字母体系只能到语言层面，无法拓展到中文这种真正的文字。
一个能迅速打出带调拼音的输入法，我认为很有意义，往大了说，对于中华文明在世界舞台上提升影响力，影响其他语言的演化发展，规范外语中的汉字词正确读音，是具有一定作用的；往小了说，也方便了需要在自己的作品文字中书写带调拼音的各种用户，提升使用体验。

**Comment by nobk** [comment]
又想到一条，补充一下
最好还能提供打字母及调号出带声调拼音的功能，以便不会汉字输入的其他外国人书写带声调拼音。

**Comment by nobk** [comment]
带调拼音资源补充 汉字拼音数据 和 词语拼音数据。 MIT License
https://github.com/mozillazg/pinyin-data
https://github.com/mozillazg/phrase-pinyin-data

**Comment by nobk** [comment]
AI分词技术 整段文字转拼音需要全文分析进行分词，按单字和词语进行拼音转换，以便正确处理多音字。
这是采用大规模语料训练而成的人工智能分词技术。MIT License
https://github.com/ownthink/Jiagu

**Comment by lotem** [comment]
樓主提出了幾項不同的需求。

可以使用[地球拼音](https://github.com/rime/rime-terra-pinyin)輸入完整的拼音。

如果只需輸入拼音文，可以用[拉丁字母](https://github.com/biopolyhedron/rime-latin-international)方案輸入帶聲調的字母。

若使用其他字形輸入法，可以利用你收集的數據製作漢字轉拼音的OpenCC字典。

**Comment by nobk** [comment]
@lotem 我写得很清楚，是**输出**带调拼音，你的回复全部是输入。
拉丁字母方案并不能**迅速**输出带调拼音，还需要手工确定调号的韵母元音字母是哪一个，然后选择该元音字母的调号，效率极低。
能用，但是同上述目标，让用户能轻松输出带调拼音，从而愿意经常书写带调拼音的目标相差甚远。

**Comment by sbxlmdsl** [comment]
人家回答得很清楚了：“可以利用你收集的數據製作漢字轉拼音的OpenCC字典。”

另外，提需求是不是应该客气点？你这语气太……。毕竟开发者都是开源社区的贡献者，而不是拿你钱干事的乙方。要存有感激之心，不要让人心凉。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rime/weasel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 下午5:35
收件人:&nbsp;"rime/weasel"<weasel@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [rime/weasel] 功能需求：希望增加打汉字输出拼音(含声调符号)的功能 (#601)





 
@lotem 我写得很清楚，是输出带调拼音，你的回复全部是输入。
 拉丁字母方案并不能迅速输出带调拼音，还需要手工确定调号的韵母元音字母是哪一个，然后选择该元音字母的调号，效率极低。
 能用，但是同上述目标，让用户能轻松输出带调拼音，从而愿意经常书写带调拼音的目标相差甚远。

**Comment by nobk** [comment]
我是参与，又不是求人办事，难道自己提需求自己完成代码不行么。提需求在顶楼，我不认为我顶楼任何文字体现不客气点儿。
用户自己最熟悉的输入法，用自己最熟悉的方式完成带调拼音的输出，这个才是开篇就提到的目标。
开这一贴，也是考虑到这个功能能够使很多人受益，也让输入法更有特色，而不是我自己好用。
我能上谷歌，偶尔需要打出带调拼音，用谷歌翻译的拼音输出就基本满足需要了，但不是每个人都能访问谷歌翻译网站。
我发帖也是花了时间的，@lotem 不仔细看就结贴，我这么回复的语气我认为完全没问题，我不高兴难道还不能表达出来了么？开源社区任何人都可以参与，并不需要低声下气吧。

**Comment by Ace-Who** [comment]
> 
> 
> @lotem 我写得很清楚，是**输出**带调拼音，你的回复全部是输入。
> 拉丁字母方案并不能**迅速**输出带调拼音，还需要手工确定调号的韵母元音字母是哪一个，然后选择该元音字母的调号，效率极低。
> 能用，但是同上述目标，让用户能轻松输出带调拼音，从而愿意经常书写带调拼音的目标相差甚远。

拉丁字母方案是「输出」拉丁字母，不是「输入」。我观察了一下码表，已经是高效的方案了，既然要输出拼音，最好的方式就是直接给拼音文字编码。你设想的能够「迅速」输出带调拼音的解法的具体操作是怎样的？比较一下快在哪里。

**Comment by Ace-Who** [comment]
> 
> 
> 我是参与，又不是求人办事，难道自己提需求自己完成代码不行么。提需求在顶楼，我不认为我顶楼任何文字体现不客气点儿。
> 用户自己最熟悉的输入法，用自己最熟悉的方式完成带调拼音的输出，这个才是开篇就提到的目标。
> 开这一贴，也是考虑到这个功能能够使很多人受益，也让输入法更有特色，而不是我自己好用。
> 我能上谷歌，偶尔需要打出带调拼音，用谷歌翻译的拼音输出就基本满足需要了，但不是每个人都能访问谷歌翻译网站。
> 我发帖也是花了时间的，@lotem 不仔细看就结贴，我这么回复的语气我认为完全没问题，我不高兴难道还不能表达出来了么？开源社区任何人都可以参与，并不需要低声下气吧。

这些功能应该由具体方案实现，而不是通过输入法引擎，且具体方案不是 rime 项目的主要内容。lotem 已经提供了现成方案和方案制作的一点思路。如果现成方案不能满足需求，那么用户自行设计方案正是 rime 的宗旨和想方设法为之提供可能和自由的贡献方式。

**Comment by lotem** [comment]
最優解：用[地球拼音](https://github.com/rime/home/wiki/UserGuide#%E5%9C%B0%E7%90%83%E6%8B%BC%E9%9F%B3)輸入完整拼音，<kbd>Shift+回車</kbd>上屏拼音。

其他辦法還有很多，樓主可以自己發散研究。相對於上來就誇誇其談，前人已經做出不少嘗試：https://github.com/rime/librime/issues/86, https://github.com/rime/home/issues/161

> 我发帖也是花了时间的，@lotem 不仔细看就结贴，……

不存在不仔細看的情況。其中試圖包羅萬象的需求描述，我都看清楚了。
已經可以判斷本項目不需要繼續追蹤本話題，於是結帖。好讓大家充分利用時間關注對項目有價值的問題。

> ……理由是，目前还没有一种能迅速输出带声调拼音字母的输入软件，
前提就錯了。並非沒有這樣的軟件，而是需求不大，因此不是大衆普遍配備的工具軟件。

> 导致大部分人不愿意为拼音配上声调，无法更准确的使用拼音。
恐怕顛倒了因果關係。

這些非技術問題，暫且不論。

和輸入有關的需求，如
> 最好还能提供打字母及调号出带声调拼音的功能，以便不会汉字输入的外国人书写带声调拼音。
本品已經有完善的支持。

而大部分需求其實是在談「漢字轉拼音」。
這個問題與輸入過程相關度不大，即不必是現行的輸入才能做轉換，也可以是既有的中文文本，因此適合做成獨立於輸入法的文本轉換軟件。

**Comment by nobk** [comment]
> 最優解：用[地球拼音](https://github.com/rime/home/wiki/UserGuide#%E5%9C%B0%E7%90%83%E6%8B%BC%E9%9F%B3)輸入完整拼音，Shift+回車上屏拼音。

形码输入法用户恐怕不会认为这个最优解是最优，用不惯就是用不惯。何况有些字能打出来但是不会念。我才提到应提供对所有输入法有效的通用输出方案。

> 而大部分需求其實是在談「漢字轉拼音」。
> 這個問題與輸入過程相關度不大，即不必是現行的輸入才能做轉換，也可以是既有的中文文本，因此適合做成獨立於輸入法的文本轉換軟件。

需要打出拼音的很多场合，例如论坛回帖，写论文等等，本来就处于键盘打字过程中，拼写带调拼音由输入法来完成，而不是采用第三方软件来完成，是最效率的方式。也就是你前面提到的词，最优解。

**Comment by nobk** [comment]
> 拉丁字母方案是「输出」拉丁字母，不是「输入」。我观察了一下码表，已经是高效的方案了，既然要输出拼音，最好的方式就是直接给拼音文字编码。你设想的能够「迅速」输出带调拼音的解法的具体操作是怎样的？比较一下快在哪里。

拼音并不是独立存在的事物，它是依附于汉字的。相信大部分人没有受过快速带调拼音录入训练，也包括我。
所以让我打汉字，由于三十年的打字经验，可以毫不费力的完成。
而写出每个汉字的带调拼音，每个汉字我都需要0.5到1秒钟的时间在大脑中确定音调，不能像打汉字那样不假思索。汉字的全部读音的确存在我们脑子里了，但是大脑里其实只记忆了每个字的读音，而没有记忆这个音到底是阴平阳平上声去声中的哪一个，每次需要从记忆中提取出来做四声的匹配。
所以用原本的打字习惯进行输入，只是变成打出的不是汉字而是带调拼音的话，用户的培训时间为0。

**Comment by lotem** [comment]
樓主還是先把需求具體化，再針對一個具體問題試做。

你的發言混雜了太多東西，恨不得把拼音的各種應用場景合到一塊，搞個大新聞。
現在似乎整理出了一些思路，大概就是用形碼輸入漢字對應的拼音，那開篇給出的理由就扯遠了：

> 希望新增这个功能的理由是，目前还没有一种能迅速输出带声调拼音字母的输入软件，导致大部分人不愿意为拼音配上声调，无法更准确的使用拼音。

結果不是沒有軟件，而是有高效的軟件但用不慣；輸入拼音時不願花費額外腦力對拼音作出反應，那再談要「更準確」地「使用拼音」就有點兒扯。

即使用形碼輸入中文，在需要寫拼音的地方，完全不思考字的讀音也不可能，有多音字的問題，再者不覈對標註的拼音也是十分不負責任的。像打漢字那樣不假思索，不需要任何額外的腦力負擔和訓練，把拼音的部分全交給電腦，恐怕過於理想化。

另外所提的需求也不是針對「大部分人」，而是不熟悉拼音的、慣用字形輸入法的人。您的三十年打字經驗，請不要想象成大部分人的經驗。您認爲這個辦法最高效省力，是因爲這是您最熟練使用的輸入方式。而拋開個人經驗看，如果只需要拼音，則輸入漢字的過程提供了遠多於拼音的信息量，同時由於多音字的關係，還不夠精確，可謂捨近求遠。
而大部分人是用拼音輸入法打字的，也有衆多（主要爲注音輸入法）用家可以熟練輸入聲調，同樣毫不費力，甚至比形碼更不假思索（沒有數據，是精通多種編碼的輸入法專家想當然的結論）。無論從理論上，還是社會實踐上，抑或所錄即所得即最簡的樸素邏輯，都可以得出用拼音本身輸入拼音是最優解。

所謂「用不慣」「沒受過訓練」「無暇思考」正反映了，輸入拼音不是一項頻繁使用的功能，甚至極小的成本用家也不願投入。至於資深專業用家我，書寫拼音或注音符號是再自然不過的事。

**Comment by nobk** [comment]
@lotem 杠精你好，你成功把我劝退了。原先在项目主页看到“欢迎提交pull request”我才过来的，本身也不是这个输入法的用户，我主要使用谷歌拼音和微软五笔。
现在看到你的态度，哪怕我写完代码，提交pull request也会遇到麻烦，就不在这个项目上消耗生命了。
临走顺便说一句，这个输入法名字起得不是一般烂，也许起名者自我感觉不错，我只能呵呵。

**Comment by lotem** [comment]
沒事，您開心就好。雖沒有PR，但滿懷熱情來指導我做輸入法的人，我見得太多了。一般我也建議他們用市面上的成熟產品。

**Comment by Ace-Who** [comment]
心智低幼又一例。

**Comment by necoic** [comment]
> > 拉丁字母方案是「输出」拉丁字母，不是「输入」。我观察了一下码表，已经是高效的方案了，既然要输出拼音，最好的方式就是直接给拼音文字编码。你设想的能够「迅速」输出带调拼音的解法的具体操作是怎样的？比较一下快在哪里。
> 
> 拼音并不是独立存在的事物，它是依附于汉字的。相信大部分人没有受过快速带调拼音录入训练，也包括我。
> 所以让我打汉字，由于三十年的打字经验，可以毫不费力的完成。
> 而写出每个汉字的带调拼音，每个汉字我都需要0.5到1秒钟的时间在大脑中确定音调，不能像打汉字那样不假思索。汉字的全部读音的确存在我们脑子里了，但是大脑里其实只记忆了每个字的读音，而没有记忆这个音到底是阴平阳平上声去声中的哪一个，每次需要从记忆中提取出来做四声的匹配。
> 所以用原本的打字习惯和输入法进行输入，只是变成打出的不是汉字而是带调拼音的话，用户的培训时间为0。因为出的虽然是拼音，但是脑子里想的依然是拼音对应的那个字词，而定音调之类的工作，就由计算机替用户完成了，无需思考匹配定调问题。

打字需要啥音调？字不认识请翻字典 请善用搜索 再不济去问问你小学语文老师 不知道在这里说这啥呢？准备逼着作者做个完美项目 你拿出去倒卖挣钱呢？

**Comment by RimuruW** [comment]
@necoic 打字需要声调我窃以为本质上没什么问题，问题在这个提问者的提问方式、个人需求及态度上。

**Comment by SuLingGG** [comment]
> @necoic 打字需要声调我窃以为本质上没什么问题，问题在这个提问者的提问方式、个人需求及态度上。

这个提问者就是个 SB，
移步：https://github.com/coolsnowwolf/lede/pull/6241
建议仓库开发者也预防性 Block。@lotem

**Comment by ulpyuxa** [comment]
提这么傻B的功能，你是找打吗？什么叫拼音输入法，你字都不认识还能打出字来？先有鸡还是先有蛋的概念都分不清，别出来混了。

**Comment by win1010525** [comment]
赶紧给nobk这智障禁了吧，打字用的拼音，输入法输出拼音，怕不是他脑子坏掉了

**Comment by nobk** [comment]
@lotem 最近这些发文是Lean翻墙路由器固件的 @1715173329 因和我的一点小矛盾，以删设备树为威胁，裹挟一批无素质用户到处谩骂，你要是觉得被骚扰就删帖吧，帖子我已经保存，删贴我没意见，本身就是我带来的麻烦。

**Comment by lotem** [comment]
> > @necoic 打字需要声调我窃以为本质上没什么问题，问题在这个提问者的提问方式、个人需求及态度上。
> 
> 移步：[coolsnowwolf/lede#6241](https://github.com/coolsnowwolf/lede/pull/6241)
> 建议仓库开发者也预防性 Block。@lotem

看起來跟本案沒有關係。​我覺得就事論事比較好。
