### ISSUE TITLE
就不小心点了下 退出算法服务，然后软件开始崩溃了，系统直接卡死了

### ISSUE THREAD

**Issue by ioldyao** [rime/weasel#602]
就不小心点了下 退出算法服务，然后软件开始崩溃了，系统直接卡死了，打字也没有中文候选框出现，只出现英文，而且还很卡

[Temp.zip](https://github.com/rime/weasel/files/5761833/Temp.zip)

**Comment by Ace-Who** [comment]
手动结束 WeaselServer.exe 进程，再启动算法服务。

**Comment by lotem** [comment]
看來應該去掉這個菜單項。
