### ISSUE TITLE
請問會更新到 librime 1.6.1

### ISSUE THREAD

**Issue by markwu** [rime/weasel#603]
你好，請問最近有計畫將 weasel 的 librime 跟 squirrel 一樣更新到 1.6.1 嘛？謝謝。

**Comment by lotem** [comment]
沒有這個計劃。
librime 1.6.1 問題也不少。如： https://github.com/rime/librime/issues/425

**Comment by lotem** [comment]
不會更新到這個版本。

**Comment by Ace-Who** [comment]
要想个含最新 librime-lua 的版本啊，手里攒了一年多的脚本没法给别人用。

**Comment by lotem** [comment]
> 要想个含最新 librime-lua 的版本啊，手里攒了一年多的脚本没法给别人用。

更新 `rime.dll`。你可以當小白鼠嗎試用1.7.0。

**Comment by Ace-Who** [comment]
@lotem 好嘞。https://github.com/rime/librime/issues/427 问题依然存在。
