### ISSUE TITLE
weasel crash : comment 字串造成 ，但是在 librime tools rime_api_console 正常

### ISSUE THREAD

**Issue by shewer** [rime/weasel#604]
在 weasel  輸入 thi 時 application 會關閉 
在 rime_api_console  正常 
覺得 在候選字menu 造成的

------rime_api_console 
thi
schema: whaleliu1 / 鯨魚舞倉頡1
status: composing
[thi]|(english)
page: 1  (of size 9)
1. [thi][english]|
2.  thi abbr. 温度-湿度指数（Temperature Humidity Index）
3.  thiamin  n. 硫胺, 维生素B1
4.  thiamin  [医] 硫胺, 维生素B-1
5.  thiamine  n. 硫胺, 维生素B1
6.  thiamine  [化] 硫胺素; 盐酸硫胺; 维生素B-1
7.  thick  a. 厚的, 粗壮的, 浓的, 迟钝的, 浑浊的, 多雾的, 过分的, 口齿不清的
8.  thick  adv. 厚地, 密地, 浓浓地
9.  thick  n. 最浓处, 最厚处, 最密集处
------

**Comment by lotem** [comment]
怎樣重現問題？

**Comment by shewer** [comment]
th  " i" 時   卡住然後  app 就關閉 
在weasel log.info 只有  engine start 
之前 做詞庫  reverse_lookup  comment  太長 某些 詞組也是固定會發生

**Comment by shewer** [comment]
--- 長字串 昜 crash
#acceptance     [әk'septәns]; n. 接受, 接納, 承認, 同意, 贊同, 容忍, 相信\n [經] 承兌, 認付, (工程)驗收

#berners        (berner 的複數)  [人名]; [英格蘭人姓氏] 伯納來源於諾曼底教名+日耳曼語, 含義是“熊+軍隊”(bear+army); [人名] [英格蘭人姓氏] 伯納職業名稱, 燒石灰或木炭者, 來源於古英, 含義是“燒”(to burn); [人名] [英格蘭人姓氏] 伯納職業名稱, 養犬者, 來源於古北方法語, 含義是“麩皮”(bran), 由麩皮喂之而得名; [人名] [英格蘭人姓氏] 伯納 Barnes,Bourne的變體

#BHS    abbr. 行李處理系統（baggage handling system）；井眼狀況（borehole status）；貝克絕望感量表（Beck Hopelessness Scale）；德國斯圖嘎版希伯來文卷本（書名, Biblia Hebraica Stuttgartensia）

#BMA    abbr. 英國醫師協會（British Medical Association）；塊匹配算法（Block Matching Algorithm）；甲基丙烯酸丁酯（butyl methacrylate）

#Bonaparte      ['bәunәpɑ:t]; 波拿巴(①姓氏, 法國科西嘉島上的家族 ②Napoleon, 1769-1821, 法國皇帝, 1804-1815在)位

#C      [si:]; [計] 調用, 訪問, 呼叫, 電容, 進位, 通道, 字符, 清除, 常數, 控制, 週期\n [化] 碳的化學符號; 胞苷

#cle    abbr. 克利夫蘭（Cleveland, 美國城市名）；建構主義學習環境（Constructivist Learning Environment）；漢語培訓中心（Chinese Language Education）

#commercialism  [k'm\\\\:ʃә'liz(ә)m]; n. 商業主義, 商業精神, 利潤第一主義, 商業習慣, 商業用語\n [經] 商業主義, 利潤第一主義, 商業精神

#cpl    abbr. 中央公共圖書館（Central Public Library）；化學物理實驗室（Chemistry and Physics Laboratory）；普通程序語言（Common Programming Language）；計算機程序庫（Computer Program Library）；全稱電子職業聯賽（Cyberathelete Professional League）

#crs    abbr. 計算機預訂系統（Computer Reservation System）；國會研究處（Certified Release Signatory）；阻風門回位系統（Choke Return System）；兒童專用安全裝置（Child Restraint System）；克羅地亞船舶登記局, 克羅地亞船級社；冷軋鋼材（Cold Rolled Steel）

#fdr    abbr. 富蘭克林·德蘭諾·羅斯福（美國第三十二任總統）（Franklin Delano Roosevelt）；飛行資料記錄器（ flight data recorder ）；x射線量刻度盤讀數（fluorometer dial readings）

#filet  [fi'lei, 'fi:lei]; n. 頭帶, 輪廓線, 帶狀物, 帶子, 束髮帶, 肉片, 魚片, 襻, 嵌條, 丘帶, (內)圓角\n vt. 用帶縛, 把(肉/魚)切成片, 用飾帶裝飾

#graduates      [ˈɡrædjuits]; n. <美>畢業生( graduate的名詞複數 ); <英>大學畢業生; （已經取得學士學位正在攻讀高級學位的）研究生; 量筒\n v. 漸變( graduate的第三人稱單數 ); 漸漸變為
（與into連用）; 漸漸消逝（與away連用）; 取得資格（與as連用）

#thickened      ['θɪkənd]; v. （使）變厚（或粗、濃、密）, 使更厚（或更密、更濃、更粗）( thicken的過去式和過去分詞 ); 使（話等）不清晰, 使模糊; 使（情節等）複雜; 變得不清晰, 變得模
糊

**Comment by shewer** [comment]
-- 容昜 carch 長字串
228:    #berners        (berner 的複數)  [人名]; [英格蘭人姓氏] 伯納來源於諾曼底教名+日耳曼語, 含義是“熊+軍隊”(bear+army); [人名] [英格蘭人姓氏] 伯納職業名稱, 燒石灰或木炭者, 來源於古英語, 含義是“燒”(to burn); [人名] [英格蘭人姓氏] 伯納職業名稱, 養犬者, 來源於古北方法語, 含義是“麩皮”(bran), 由麩皮喂之而得名; [人名] [英格蘭人姓氏] 伯納 Barnes,Bourne的變體
146:    #BHS    abbr. 行李處理系統（baggage handling system）；井眼狀況（borehole status）；貝克絕望感量表（Beck Hopelessness Scale）；德國斯圖嘎版希伯來文卷本（書名, Biblia Hebraica Stuttgartensia）
106:    #BMA    abbr. 英國醫師協會（British Medical Association）；塊匹配算法（Block Matching Algorithm）；甲基丙烯酸丁酯（butyl methacrylate）
85:     #Bonaparte      ['bәunәpɑ:t]; 波拿巴(①姓氏, 法國科西嘉島上的家族 ②Napoleon, 1769-1821, 法國皇帝, 1804-1815在位)
114:    #cle    abbr. 克利夫蘭（Cleveland, 美國城市名）；建構主義學習環境（Constructivist Learning Environment）；漢語培訓中心（Chinese Language Education）
95:     #commercialism  [k'm\\\\:ʃә'liz(ә)m]; n. 商業主義, 商業精神, 利潤第一主義, 商業習慣, 商業用語\n [經] 商業主義, 利潤第一主義, 商業精神
197:    #cpl    abbr. 中央公共圖書館（Central Public Library）；化學物理實驗室（Chemistry and Physics Laboratory）；普通程序語言（Common Programming Language）；計算機程序庫（Computer Program Library）；全稱電子職業聯賽（Cyberathelete Professional League）
187:    #crs    abbr. 計算機預訂系統（Computer Reservation System）；國會研究處（Certified Release Signatory）；阻風門回位系統（Choke Return System）；兒童專用安全裝置（Child Restraint System）；克羅地亞船舶登記局, 克羅地亞船級社；冷軋鋼材（Cold Rolled Steel）
130:    #fdr    abbr. 富蘭克林·德蘭諾·羅斯福（美國第三十二任總統）（Franklin Delano Roosevelt）；飛行資料記錄器（ flight data recorder ）；x射線量刻度盤讀數（fluorometer dial readings）
104:    #filet  [fi'lei, 'fi:lei]; n. 頭帶, 輪廓線, 帶狀物, 帶子, 束髮帶, 肉片, 魚片, 襻, 嵌條, 丘帶, (內)圓角\n vt. 用帶縛, 把(肉/魚)切成片, 用飾帶裝飾
159:    #graduates      [ˈɡrædjuits]; n. <美>畢業生( graduate的名詞複數 ); <英>大學畢業生; （已經取得學士學位正在攻讀高級學位的）研 究生; 量筒\n v. 漸變( graduate的第三人稱單數 ); 漸漸變為（與into連用）; 漸漸消逝（與away連用）; 取得資格（與as連用）
112:    #thickened      ['θɪkənd]; v. （使）變厚（或粗、濃、密）, 使更厚（或更密、更濃、更粗）( thicken的過去式和過去分詞 ); 使（話 等）不清晰, 使模糊; 使（情節等）複雜; 變得不清晰, 變得模糊

-- 不會 crash 長字串
146:    wigg     [人名]; [英格蘭人姓氏] 威格綽號, 來源於中世紀英語, 含義是“甲蟲, 臭蟲”(beetle,bug); [人名] [英格蘭人姓氏] 威格職業 名, 烤成圓形再分成楔形的花樣麵包製作者, 來源於中世紀英語、中世紀荷蘭語, 含義是“楔形餅”(wedgeshaped cake)
88:     wild    [waild]; n. 荒野, 荒地\n a. 野性的, 野蠻的, 野生的, 失控的, 任性的, 雜亂的, 輕率的, 狂熱的, 瘋狂的\n adv. 狂暴地, 失
控地
96:     will    [wil]; n. 意志, 決心, 意願, 意向, 幹勁, 遺囑\n vt. 用意志的力量驅使, 決意, 願意, 立遺囑\n vi. 下決心, 願意\n aux. 將, 願意, 必須
90:     Wilts   n. (Wilts)人名；(英、德)威爾茨\n 使畏縮\n 枯萎\n 畏縮（wilt的第三人稱單數）\n 威爾特郡（英格蘭南部的一郡）（Wiltshire）\n 使枯萎

**Comment by shewer** [comment]
input: ta    page_down 
input: tan  crash  
----- crash
#tang   [tæŋ]; n. 強烈味道, 特殊的氣味, 特性, 柄腳, 噹的一聲, 墨角藻\n vt. 使發氣味, 裝刀柄於, 使發出噹的一聲\n vi. 發出噹的一聲
tanq 

去掉 tang  字典  正常
input: ta   page_down
input: tan  page_down
input: tang page_down

**Comment by fxliang** [comment]
fixed by #1169 
在此之前有调整了ipc 的buffer size到64k完全够用的了，由上文看应该是\n问题。上述pr已可解决这个问题
