### ISSUE TITLE
在VS Code中的终端无法输入中文

### ISSUE THREAD

**Issue by Python-37** [rime/weasel#605]
上个月开始VS Code的终端无法输入中文，但是Windows Terminal或者直接使用powershell可以正常使用。由于我在上个月大规模更新过配置文件，以为是配置文件的变动导致的，尝试过回滚小狼毫的配置文件到较早的版本之后，发现问题仍然存在，所以想请教造成这种状况可能的原因是什么，有没有什么解决的思路，谢谢。

**Comment by BavonChao** [comment]
在VS Code中编写代码完全正常，同样配置文件在Linux下也没有任何问题。

**Comment by Bpazy** [comment]
相同的问题，第一次可以正常输入中文，第二次就不行了。我上个 GIF：
![1](https://user-images.githubusercontent.com/9838749/105275541-8fe3c800-5bda-11eb-8eca-85b34dea8e6e.gif)

weasel: `0.14.3`
VSCode 和 OS 等其它信息：
```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by lidedongsn** [comment]
遇到同样问题 终端无法输入中文

**Comment by LightAPIs** [comment]
从 vscode 1.52.0 起就存在这个问题，到目前最新的 1.53.0 依旧存在这个问题，我现在也只能是停留在 1.51.1 版本。
vscode issues 那边也已经有人在提了， https://github.com/microsoft/vscode/issues/115814，不清楚什么时候才能修复。

**Comment by Python-37** [comment]
https://github.com/microsoft/vscode/issues/115814#issuecomment-792257321
有了进展

**Comment by YanjunLee** [comment]
`weasel.custom.yaml` 添加以下 patch:

`style/inline_preedit: true`

windows 10 20H2，VS CODE 1.54.2 亲测可用。

**Comment by Python-37** [comment]
最新的 insider 版本已经修正了这个BUG，此 issue 将会关闭

**Comment by 2catycm** [comment]
> 最新的 insider 版本已经修正了这个BUG，此 issue 将会关闭
到2024年，最新的insider版本重新出现了这个bug

**Comment by 2catycm** [comment]
> > 最新的 insider 版本已经修正了这个BUG，此 issue 将会关闭
> > 到2024年，最新的insider版本重新出现了这个bug

我的版本如下：
版本: 1.92.0-insider (system setup)
提交: 4d17e85cfd911fb6b116e08a4d7c37cd725a966a
日期: 2024-07-26T13:12:28.318Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26120

**Comment by sakurasang** [comment]
> > > 最新的 insider 版本已经修正了这个BUG，此 issue 将会关闭
> > > 到2024年，最新的insider版本重新出现了这个bug
> 
> 我的版本如下： 版本: 1.92.0-insider (system setup) 提交: 4d17e85cfd911fb6b116e08a4d7c37cd725a966a 日期: 2024-07-26T13:12:28.318Z Electron: 30.1.2 ElectronBuildId: 9870757 Chromium: 124.0.6367.243 Node.js: 20.14.0 V8: 12.4.254.20-electron.0 OS: Windows_NT x64 10.0.26120

好像1.93.1依然没有修复这个bug，我尝试了好几个方法也没有成功解决这个问题，大家都有这个问题吗

**Comment by MetaSquared** [comment]
现在也没有修复这个bug

**Comment by wiuid** [comment]
这个问题和输入法好像有关系，可是试着更换为微软输入法，或者其他的最新的版本的输入法
我这边是手心输入法，更新为最新版本后修复
