### ISSUE TITLE
发现一款疑似修改小狼毫的输入法

### ISSUE THREAD

**Issue by mokapsing** [rime/weasel#606]
该输入法名为极简输入法，官网http://geek-input.officeoncloud.cn/ ，这个输入法改的小狼毫，但是未看到有开放源码，应该涉及侵权

**Comment by lotem** [comment]
牛啊。界面很主流啊，比小狼毫厲害。
是國內的小作坊吧。
臺灣人早就仿製過。
也無奈何。
如果有用戶論壇什麼的，可以借勢去宣傳 RIME：
好用的輸入法懂我心意，請認準式恕堂註冊商標。

**Comment by poorich** [comment]
某官方组织还十分看重它
见 http://www.catticenter.com/ggl/2367 条目3
