### ISSUE TITLE
獲取輸入方案時遇到的一些問題

### ISSUE THREAD

**Issue by Francis-Hsu** [rime/weasel#607]
使用輸入法設定>獲取更多輸入方案……時遇到一些問題，如用package name安裝時會出現如下錯誤：
```
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
```
修改`rime-install.bat`，給`curl`添加`--ssl-no-revoke`參數後可以正常安裝。另外完全卸載`Git Bash`後安裝最新版本（2.30）似乎也能解決問題。

在上述修改後安裝[`lotem/rime-kana`](https://github.com/lotem/rime-kana)包仍會遇到如下錯誤：
```
curl: (23) Failed writing body (0 != 4055)
```
手動輸入下載好的zip文件路徑則可以正常安裝，不知何故。系統爲Windows 10 Build 19041。

另外不知是否可以給小狼毫添加一個更新輸入方案的功能？即讓下載好的方案和package的repo保持同步。

**Comment by fxliang** [comment]
更新小狼毫，plum组件有更新，应该已经解决您的问题了
