### ISSUE TITLE
我可以提个 CMake 的 PR 吗？

### ISSUE THREAD

**Issue by AllanZyne** [rime/weasel#608]
现有的构建方案 `build.bat` 不是很方便，无法用比较新的工具链编译。
现有的 `weasel.sln` 也不能用 vs2019 打开。
所以不如用 CMake 自动生成 `sln`，减少开发时的麻烦。
而且 `weasel` 主要依赖的 `librime` 已经支持 CMake 了，可以为 `weasel` 减少很多麻烦。

**Comment by lotem** [comment]
設置好環境變量就可以用新的工具鏈了：
https://github.com/rime/weasel/blob/master/env.bat.template
VS高版本可以打開低版本創建的工程吧？所以沒有用最新的格式。VS2019可以的。
用CMake倒是可以避免轉換，但不知道工作量有多少，以及生成工程的保真程度。

**Comment by AllanZyne** [comment]
> 設置好環境變量就可以用新的工具鏈了：
> https://github.com/rime/weasel/blob/master/env.bat.template

这个文件的内容并不够，还需要从开始菜单使用类似 `x64 Native Tools Command Prompt` 所打开的终端中使用才行。
直接用 VS2019 编译主要是卡在 boost 的版本了，如果换个新版的 boost 可能没问题。
但接下来如果卡在 `msbuild` 的话就很难办了。
我也试过从 `Visual Studio Installer` 下载  VS2017 的工具链使用，记得不是卡在 `librime` 就是 `msbuild` 了吧。
我觉得直接用 `build.bat` 不够稳定。

> VS高版本可以打開低版本創建的工程吧？所以沒有用最新的格式。VS2019可以的。

可能因为项目文件太旧了，VS2019 打开后所有子项目都是无法加载。

> 用CMake倒是可以避免打開IDE的格式轉換，但不知道工作量有多少，以及生成工程的保真程度。

我在网上找到一个 [cmake-converter](https://pypi.org/project/cmake-converter/) 的工具，可以方便把 `sln` 项目转成 `CMakeLists.txt` 文件，编译命令的保真度看起来可以。

其实我个人还是更希望能用 Visual Studio IDE 或者 Visual Studio Code (+CMake 插件) 来开发。
如果这个项目支持 CMake 的话，对其他想要做贡献的开发者来说的话会降低不少门槛吧。

**Comment by lotem** [comment]
不以爲然。我覺得使用cmake會增加門檻。如果不需要改動librime，只開發/修改輸入法前端的功能，直接用VS開發，對部分開發者比較方便。

項目無法加載，有可能是因爲缺少 `weasel.props` 文件。這個文件由 `build.bat` 生成，主要作用就是把`BOOST_ROOT`等變量設置好。
如果從來沒執行過 `build.bat`，那麼需要手動複製[模板](https://github.com/rime/weasel/blob/master/weasel.props.template)建立該文件，再打開工程。

**Comment by AllanZyne** [comment]
看来 `build.bat` 已经有段时间没维护了。
还没编译完，在此先记录一下遇到的问题吧。

`build.bat` 的问题：
1. [build.bat#L112](https://github.com/rime/weasel/blob/master/build.bat#L112) 应该删除 `librime\`
2. [build.bat#L116](https://github.com/rime/weasel/blob/master/build.bat#L116) 已经和 `librime/build.bat` 不兼容了，我猜应该用 `shared`
3. 应该把 `env.bat` 拷贝到 `librime\env.bat`

编译工程时遇到的问题：
1. 用 Win SKD 10.0 时，`VersionHelpers.hpp` 是多余的
2. C++ 头文件 `$(SolutionDir)\librime\include` 改成 `$(SolutionDir)\librime\src` 


如果一起用 CMake 的话，环境变量就能自动传递了，头文件目录的也能自动传递给父项目。
`VersionHelpers.hpp` 问题的大概可以[这样](https://stackoverflow.com/a/31464515)吧。
```cpp
#include <ntverp.h>
#if VER_PRODUCTBUILD > 9600
// Windows 10+ SDK code goes here
#else
// Windows 8.1- SDK code goes here
#endif
```

**Comment by lotem** [comment]
> 1. [build.bat#L112](https://github.com/rime/weasel/blob/master/build.bat#L112) 应该删除 `librime\`

是的。

> 2. [build.bat#L116](https://github.com/rime/weasel/blob/master/build.bat#L116) 已经和 `librime\build.bat` 不兼容了，我猜应该用 `shared`

不要用`shared`。新的选项已经在`librime`脚本里支持，需要更新git子模组。

> 3. 应该把 `env.bat` 拷贝到 `librime\env.bat`
没有必要。环境变量会传给子进程。

> 1. 用 Win SKD 10.0 时，`VersionHelpers.hpp` 是多余的
听说过这个问题，有待研究。

> 2. C++ 头文件 `$(SolutionDir)\librime\include` 改成 `$(SolutionDir)\librime\src`
这个路径早就不用了，应该删除。

**Comment by AllanZyne** [comment]
还有一个是 `WinSparkle` 在 Link 时会出问题，出现一些未定义的符号。
我简单调查了一下是 `WinSparkle.lib` 导出的符号和 msvc 不兼容，
于是写了一个 `def` 文件用来生成可以用的 lib 文件

WinSparkle.def
```def
LIBRARY WINSPARKLE
EXPORTS
  win_sparkle_check_update_with_ui
  win_sparkle_check_update_with_ui_and_install
  win_sparkle_check_update_without_ui
  win_sparkle_cleanup
  win_sparkle_get_automatic_check_for_updates
  win_sparkle_get_last_check_time
  win_sparkle_get_update_check_interval
  win_sparkle_init
  win_sparkle_set_app_build_version
  win_sparkle_set_app_details
  win_sparkle_set_appcast_url
  win_sparkle_set_automatic_check_for_updates
  win_sparkle_set_can_shutdown_callback
  win_sparkle_set_did_find_update_callback
  win_sparkle_set_did_not_find_update_callback
  win_sparkle_set_dsa_pub_pem
  win_sparkle_set_error_callback
  win_sparkle_set_lang
  win_sparkle_set_langid
  win_sparkle_set_registry_path
  win_sparkle_set_shutdown_request_callback
  win_sparkle_set_update_cancelled_callback
  win_sparkle_set_update_check_interval
```

```cmd
lib /def:WinSparkle.def /out:WinSparkle.lib /machine:x64
```

算是用这种方式搞定了。
然后发现 WeaselServer 少 x64 的配置，添加后总算编译完成了。
最后发现 WeaselServer 启动不了，原因是 `WinSparkle.dll` 是 x86 的！

唉，算了，要么重编 `librime`，要么重编 `WinSparkle`，如果重编 `WinSparkle` 就不需要上面那么麻烦了。
以及 `build.bat` 不像有 clean 功能吧。
