### ISSUE TITLE
能否添加个简体中文界面？

### ISSUE THREAD

**Issue by XGSZZ** [rime/weasel#610]

**Comment by CODE-7z** [comment]
什么意思？

**Comment by dqwyy** [comment]
不如换个问题：如何为程式UI介面贡献i18n？

**Comment by mariohide** [comment]
你得说清楚是哪个界面

**Comment by XGSZZ** [comment]
您好！
如果软件能自动识别操作系统的语言，比如简体中文，输入法根据系统语言默认设置输入语言为“简体中文”，输入法软件的其他界面应该自动切换为简体中文。另外，如果输入法能根据系统版本自动选择是安装32位还是安装64位版本，就更好了。
下面是软件安装过程的界面和安装后的开始菜单，都是繁体中文的。











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rime/weasel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 上午10:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rime/weasel] 能否添加个简体中文界面？ (#610)





 
你得说清楚是哪个界面

**Comment by heheda123123** [comment]
![image](https://github.com/rime/weasel/assets/97490782/c4e756fa-ba72-412c-9ed1-f9c4d99a22f2)
这个界面，包括“输入法设定”里面
![image](https://github.com/rime/weasel/assets/97490782/cba4ad59-c72e-48d4-a43e-74f8698283d7)

**Comment by XGSZZ** [comment]
邮件已收到！

**Comment by fxliang** [comment]
#988 已实现
