### ISSUE TITLE
隔壁的更新了，win的啥时候更新0.15呢？

### ISSUE THREAD

**Issue by CANBAAA** [rime/weasel#611]

**Comment by markwu** [comment]
我也很期待新版的小狼毫。

**Comment by Prcuvu** [comment]
小狼毫当前最新版本 0.14.3 发布于 2019 年。
根据“小狼毫 4 年必有更新”定律，最晚 2023 年会有新版本。

**Comment by markwu** [comment]
因為 librime 更新了， opencc 也更新了，所以很期待新版的小狼毫。 macOS 版的鼠鬚管我可以自己 compile，Windows 版的小狼毫實在不會。

**Comment by lotem** [comment]
> 因為 librime 更新了， opencc 也更新了，所以很期待新版的小狼毫。 macOS 版的鼠鬚管我可以自己 compile，Windows 版的小狼毫實在不會。

​那只要下載、替換 rime.dll 就行了。

**Comment by markwu** [comment]
謝謝！請問替換了 dll 後， data 內的資料包含 opencc 需要替換嗎？

**Comment by ASC8384** [comment]
> 
> 
> @lotem 謝謝！請問替換了 dll 後， data 內的資料包含 opencc 需要替換嗎？

应该（起码我自己）不需要

**Comment by huquanjun** [comment]
自己编译了一个版本，大家可以试试: https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe

**Comment by pingshunhuangalex** [comment]
@lotem 请问weasel还支持吗？为何与squirrel相差如此巨大？谢谢
![image](https://user-images.githubusercontent.com/17170199/109286188-0927a800-7876-11eb-9e1f-cda2ac20a0b3.png)
![image](https://user-images.githubusercontent.com/17170199/109286198-0c229880-7876-11eb-8da1-b08e25eb5e3d.png)

**Comment by pphboy** [comment]
> 自己编译了一个版本，大家可以试试: https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe

请问做了什么修改吗

**Comment by huquanjun** [comment]
> > 自己编译了一个版本，大家可以试试: https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe
> 
> 请问做了什么修改吗

基于2021-02-25 clone的weasel，使用vs2019编译
使用了rime-with-plugins-1.7.2-win32
修正了opencc的文件为ocd2，否则输出一直是繁体中文

**Comment by lotem** [comment]
> @lotem 请问weasel还支持吗？为何与squirrel相差如此巨大？谢谢
> ![image](https://user-images.githubusercontent.com/17170199/109286188-0927a800-7876-11eb-9e1f-cda2ac20a0b3.png)
> ![image](https://user-images.githubusercontent.com/17170199/109286198-0c229880-7876-11eb-8da1-b08e25eb5e3d.png)

支持，我用着沒有問題。

哪方面相差巨大？

**Comment by pphboy** [comment]
> > > 自己编译了一个版本，大家可以试试: https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe
> > 
> > 
> > 请问做了什么修改吗
> 
> 基于2021-02-25 clone的weasel，使用vs2019编译
> 使用了rime-with-plugins-1.7.2-win32
> 修正了opencc的文件为ocd2，否则输出一直是繁体中文

太棒了，我安装了，试试

**Comment by pingshunhuangalex** [comment]
> > @lotem 请问weasel还支持吗？为何与squirrel相差如此巨大？谢谢
> > ![image](https://user-images.githubusercontent.com/17170199/109286188-0927a800-7876-11eb-9e1f-cda2ac20a0b3.png)
> > ![image](https://user-images.githubusercontent.com/17170199/109286198-0c229880-7876-11eb-8da1-b08e25eb5e3d.png)
> 
> 支持，我用着沒有問題。
> 
> 哪方面相差巨大？

就Win上次更新是19年 而Mac一直在积极的更新……

**Comment by lotem** [comment]
> > > @lotem 请问weasel还支持吗？为何与squirrel相差如此巨大？谢谢
> > > ![image](https://user-images.githubusercontent.com/17170199/109286188-0927a800-7876-11eb-9e1f-cda2ac20a0b3.png)
> > > ![image](https://user-images.githubusercontent.com/17170199/109286198-0c229880-7876-11eb-8da1-b08e25eb5e3d.png)
> > 
> > 
> > 支持，我用着沒有問題。
> > 哪方面相差巨大？
> 
> 就Win上次更新是19年 而Mac一直在积极的更新……

這只是近期的趨勢。有Mac用家在積極地爲Mac前端提交代碼並推動版本更新。長期看更新的頻率沒有太大差異。

**Comment by marryton007** [comment]
> 自己编译了一个版本，大家可以试试: https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe

非常感谢你的分享，结果比较遗憾，无论是使用官方的0.14.3，还是你的版本，都无法正确的输入中文。

我的系统信息：
Win10家庭版，系统版本：21H1，内部版本号：19043.844

具体表现：
1. 无法输入中文
2. 任务栏菜单(system tray)可以弹出，但点击没有响应。
3. 从开始菜单进入的菜单可以响应，如进入“输入法设定”，但还是不能输入中文。

PS: 暂时不知道哪里可以找到一些出错的日志信息，如果有需要，请告知

**Comment by cnlog** [comment]
> 
> 
> > 自己编译了一个版本，大家可以试试: https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe
> 
> 非常感谢你的分享，结果比较遗憾，无论是使用官方的0.14.3，还是你的版本，都无法正确的输入中文。
> 
> 我的系统信息：
> Win10家庭版，系统版本：21H1，内部版本号：19043.844
> 
> 具体表现：
> 
>     1. 无法输入中文
> 
>     2. 任务栏菜单(system tray)可以弹出，但点击没有响应。
> 
>     3. 从开始菜单进入的菜单可以响应，如进入“输入法设定”，但还是不能输入中文。
> 
> 
> PS: 暂时不知道哪里可以找到一些出错的日志信息，如果有需要，请告知
https://github.com/cnlog/warehouse/blob/main/weasel-0.14.3.0-installer.exe
刚编译的。vs2019最新更新+boost_1_75_0+librime最新源码+weasel最新源码编译,data配置数据为官版配置。windows 10专业版 20H2 19042.844。自己用着没啥问题，你试试。

**Comment by lotem** [comment]
​如果沒做任何新的修改，從[測試頻道](https://bintray.com/rime/weasel/testing)下載自動構建版即可。

**Comment by blackhole889** [comment]
> 
> 
> > 自己编译了一个版本，大家可以试试: https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe
> 
> 非常感谢你的分享，结果比较遗憾，无论是使用官方的0.14.3，还是你的版本，都无法正确的输入中文。
> 
> 我的系统信息：
> Win10家庭版，系统版本：21H1，内部版本号：19043.844
> 
> 具体表现：
> 
>     1. 无法输入中文
> 
>     2. 任务栏菜单(system tray)可以弹出，但点击没有响应。
> 
>     3. 从开始菜单进入的菜单可以响应，如进入“输入法设定”，但还是不能输入中文。
> 
> 
> PS: 暂时不知道哪里可以找到一些出错的日志信息，如果有需要，请告知

程序不能安装在中文目录。

**Comment by otakutyrant** [comment]
@marryton007 https://github.com/rime/home/issues/748#issue-832319234 和我的表现一样吗？

**Comment by marryton007** [comment]
> > > 自己编译了一个版本，大家可以试试: https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe
> > 
> > 
> > 非常感谢你的分享，结果比较遗憾，无论是使用官方的0.14.3，还是你的版本，都无法正确的输入中文。
> > 我的系统信息：
> > Win10家庭版，系统版本：21H1，内部版本号：19043.844
> > 具体表现：
> > ```
> > 1. 无法输入中文
> > 
> > 2. 任务栏菜单(system tray)可以弹出，但点击没有响应。
> > 
> > 3. 从开始菜单进入的菜单可以响应，如进入“输入法设定”，但还是不能输入中文。
> > ```
> > 
> > 
> > PS: 暂时不知道哪里可以找到一些出错的日志信息，如果有需要，请告知
> 
> 程序不能安装在中文目录。

没有安装到中文目录，安装时一直都是默认选项。

**Comment by marryton007** [comment]
> @marryton007 [rime/home#748 (comment)](https://github.com/rime/home/issues/748#issue-832319234) 和我的表现一样吗？

表现类似，无法输入中文，没有输入跟随栏。
运气没你好，检查更新，程序错误退出，重新部署，问题依旧。

**Comment by crackself** [comment]
> 
> 
> > @marryton007 [rime/home#748 (comment)](https://github.com/rime/home/issues/748#issue-832319234) 和我的表现一样吗？
> 
> 表现类似，无法输入中文，没有输入跟随栏。
> 运气没你好，检查更新，程序错误退出，重新部署，问题依旧。

或许可以试下我这个[测试包](https://github.com/crackself/weasel/releases/download/0.15.0/Pre-build_weasel-0.15.0.0-installer.exe)。使用librime1.7.3核心。
较原版改动：预置[lua plugin](https://github.com/hchunhui/librime-lua.git)，支持输入实时时间；预置输入法为拼音、五笔，预置emoji。
在win10 19043.844版本使用无大问题。
已知问题：无法打开设置面板则需要在用户文件夹内添加`default.custom.yaml文件（空文件亦可）

**Comment by marryton007** [comment]
> > > @marryton007 [rime/home#748 (comment)](https://github.com/rime/home/issues/748#issue-832319234) 和我的表现一样吗？
> > 
> > 
> > 表现类似，无法输入中文，没有输入跟随栏。
> > 运气没你好，检查更新，程序错误退出，重新部署，问题依旧。
> 
> 或许可以试下我这个[测试包](https://github.com/crackself/weasel/releases/download/0.15.0/Pre-build_weasel-0.15.0.0-installer.exe)。使用librime1.7.3核心。
> 较原版改动：预置[lua plugin](https://github.com/hchunhui/librime-lua.git)，支持输入实时时间；预置输入法为拼音、五笔，预置emoji。
> 在win10 19043.844版本使用无大问题。
> 已知问题：无法打开设置面板则需要在用户文件夹内添加`default.custom.yaml`文件（空文件亦可）

厉害，真可以用！
那原来不能用的原因是什么呢？是需要升级Librime吗？

**Comment by crackself** [comment]
> 
> 
> > > > @marryton007 [rime/home#748 (comment)](https://github.com/rime/home/issues/748#issue-832319234) 和我的表现一样吗？
> > > 
> > > 
> > > 表现类似，无法输入中文，没有输入跟随栏。
> > > 运气没你好，检查更新，程序错误退出，重新部署，问题依旧。
> > 
> > 
> > 或许可以试下我这个[测试包](https://github.com/crackself/weasel/releases/download/0.15.0/Pre-build_weasel-0.15.0.0-installer.exe)。使用librime1.7.3核心。
> > 较原版改动：预置[lua plugin](https://github.com/hchunhui/librime-lua.git)，支持输入实时时间；预置输入法为拼音、五笔，预置emoji。
> > 在win10 19043.844版本使用无大问题。
> > 已知问题：无法打开设置面板则需要在用户文件夹内添加`default.custom.yaml`文件（空文件亦可）
> 
> 厉害，真可以用！
> 那原来不能用的原因是什么呢？是需要升级Librime吗？

这得问发布的朋友

**Comment by marryton007** [comment]
......
> 这得问发布的朋友

一点小问题，使用”五笔-拼音“混合输入方案的时候，只能使用五笔，临时想用拼音没有生效，需要重新安装输入方案。

**Comment by cnlog** [comment]
做了一个比较大的更新，试试看有无大问题，小问题估计肯定有。得重视windows用户啊，毕竟Windows用户数量是最多的
https://github.com/rime/home/issues/769

**Comment by lotem** [comment]
悲報： @Prcuvu 
bintray.com 要停止提供下載點了
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter
按照目前進度 下一次發佈就得改用新的發佈流程

**Comment by jfhsu** [comment]
> 做了一个比较大的更新，试试看有无大问题，小问题估计肯定有。得重视windows用户啊，毕竟Windows用户数量是最多的
> [rime/home#769](https://github.com/rime/home/issues/769)

用了几个月，so far so good. 没什么问题，在 win10使用下都很正常

**Comment by QingW-7023** [comment]
求更新，加入小狼毫以来，从未更新过，以前更新对我来说简直缘故的事情。😄️

**Comment by QingW-7023** [comment]
求更新，加入小狼毫以来，从未更新过，以前的更新对我来说简直远古的事情。😄️

**Comment by QingW-7023** [comment]
求更新！
加入小狼毫以来，从未更新过。
以前的更新对我来说简直远古的事情。😄️

**Comment by moxuanyuan** [comment]
如果一台PC上没有安装小狼毫，我发现我是不会打字。。。

**Comment by QingW-7023** [comment]
> 如果一台PC上没有安装小狼毫，我发现我是不会打中文。。。

我才是呢，因为我的输入法方案是其他输入法上没有的，很难实现。。每次重装系统后，一开始的打字总会变得难受。

**Comment by lane19** [comment]
> 自己编译了一个版本，大家可以试试: https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe

谢谢，0.14.3版很久没更新，我是win10，运行一段时间后总会出现空格上屏时总会多出一个空格，希望这一版能解决

**Comment by aaa1999** [comment]
哎主要是我连编译的门槛都进不去哈哈。

**Comment by tiujejauci** [comment]
> 悲報： @Prcuvu
> bintray.com 要停止提供下載點了
> https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter
> 按照目前進度 下一次發佈就得改用新的發佈流程

請問能否上載**所有舊版本**小狼毫？譬如：0.11.1

**Comment by lotem** [comment]
​沒有了！發行過的舊版本已經無法取得了。

代碼還在，有標籤。如果需要可以嘗試重新構建。

> > 悲報： @Prcuvu  @lotem
> > bintray.com 要停止提供下載點了
> > https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter
> > 按照目前進度 下一次發佈就得改用新的發佈流程
> 
> 請問能否上載 **所有舊版本** 小狼毫？譬如：0.11.1

**Comment by pphboy** [comment]
是停止维护了吗

**Comment by pingshunhuangalex** [comment]
> 是停止维护了吗

对啊 不维护了 上面有几个民间的版本 将就着用吧（我没测试过）
https://github.com/cnlog/warehouse/blob/main/weasel-0.14.5.0-installer.exe
https://github.com/crackself/weasel/releases/download/0.15.0/Pre-build_weasel-0.15.0.0-installer.exe
https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe

**Comment by Endif12** [comment]
WIN11都发了，希望能早点见到更新

**Comment by aaa1999** [comment]
更新有啥意义，一个打字软件，你还想要什么高级特性。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月16日(周二) 凌晨0:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rime/weasel] 隔壁的更新了，win的啥时候更新0.15呢？ (#611)




 
WIN11都发了，希望能早点见到更新
 
&mdash;

**Comment by pingshunhuangalex** [comment]
> 更新有啥意义，一个打字软件，你还想要什么高级特性。

别吧，高级特性我是做梦也不敢想，但是说更新没意义可就太扯了。

bug无数，性能感人，适配着急，可以改进的地方数不胜数。你觉得没意义，更新完你别下就完了。真的别再给这种想当然的评论了，更新频率已经很蛋疼了。。。

**Comment by Endif12** [comment]
> 更新有啥意义，一个打字软件，你还想要什么高级特性。
现在已经有一些bug了，我想可能来自两方面，一方面是自带的，另一方面是睡着系统的更新，软件没有跟上产生的。所以我认为更新是有积极意义的。

**Comment by Endif12** [comment]
> 更新有啥意义，一个打字软件，你还想要什么高级特性。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月16日(周二) 凌晨0:07 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [rime/weasel] 隔壁的更新了，win的啥时候更新0.15呢？ (#611) WIN11都发了，希望能早点见到更新 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

现在已经有一些bug了，我想可能来自两方面，一方面是自带的，另一方面是睡着系统的更新，软件没有跟上产生的。所以我认为更新是有积极意义的。

**Comment by tiujejauci** [comment]
windows小狼毫[weasel 0.11.1.0 installer.zip](https://github.com/rime/weasel/files/7769476/weasel.0.11.1.0.installer.zip)

**小狼毫0.10.0 (2018-03-14) 致0.11.1 (2018-04-26)**
此系列版本是佛振先生自14年後終於發布的小狼毫版本。
新功能我這裡主要添加了新版的emoji
另外在mac上可以使用bash命令行添加詞庫，而Windows上也有相應的工具，不過不好用。 我是主要在github上下載相應詞庫後直接丟到用戶文件夾下面
值得注意的是，此系列版本未主動添加詞庫，如果你在 default.custom.yaml 中添加了一些輸入方案而在用戶文件夾當中未有相應的詞典文件和輸入方案則會報錯
這系列版本在 桌面模式 下可以在遊戲當中直接使用輸入了。 因為我是一個英雄聯盟一個骨灰級黑鐵玩家，所以截止到目前(2019/01/03)，我始終使用此版本的weasel-0.11.1.0-installer.exe
此系列版本對應的mac版則是 鼠须管 0.10.0(2019-01-01) 致 0.11.0(2019-01-21)
[原文在此](https://github.com/halfmoonvic/Rime/blob/master/Rime%E7%B3%BB%E5%88%97%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E.md)

**Comment by jack6th** [comment]
直接替换rime.dll有问题。我替换了1.7.3的rime.dll，自带的明月拼音简体可以输入，但是换成四叶草拼音输入方案会无法输入中文，替换回原来的rime.dll又能输入了。
最好每次发布新版rime.dll后都发布一个重新编译的weasel的新版本。

**Comment by KeithW0726** [comment]
23年了，依然没有更新，这应该是寄了吧。。。

**Comment by fxliang** [comment]
https://github.com/rime/weasel/actions

有空可以试下~

> 23年了，依然没有更新，这应该是寄了吧。。。

**Comment by KeithW0726** [comment]
> [rime/weasel/actions](https://github.com/rime/weasel/actions)
> 
> 有空可以试下~
> 
> > 23年了，依然没有更新，这应该是寄了吧。。。

哇，谢谢大佬的更新。
其实是最近用了大佬版本的，最近是出现了bug：同样的配置原版没问题，但用了最新CI出来的版本，Emoji怎样出不来。。。
我大致排查了下，
1. 我是先卸载重启原版再安装最新CI版的；
2. Symbol的Emoji能正常显示出来
3. 简繁转换也出了问题

大概率问题是在opencc那里。但具体实在判断不出来的核心问题点在哪，于是就回退原版了。。。

**Comment by fxliang** [comment]
建议直接使用rime/weasel下的构建，我那边有些可能是实验性质的东西。opencc这个目前据说有可能和中文路径有相关，之前也有 issue有提和librime有关系，这个我用的不多，目前測試似乎沒有問題（最後這些繁體就是opencc的產出）

**Comment by tiujejauci** [comment]
> https://github.com/rime/weasel/actions
> 
> 有空可以试下~
> 
> > 23年了，依然没有更新，这应该是寄了吧。。。
我順手傳到virustotal
https://www.virustotal.com/gui/file/716ecfec50a53680bfb15905ab937fc54aa6a220537617b56df75d0572d875b5?nocache=1

**Comment by KeithW0726** [comment]
谢谢楼上两位的反馈，那我再试下这两个，看到好几个PR都被merged，期待早日发版

**Comment by determ1ne** [comment]
已发版 0.15.0 ，更新了一些新功能，解决了一些 bug ，刚好在 2023 年
