### ISSUE TITLE
请问能否解决小狼毫开机无法立即使用的问题？

### ISSUE THREAD

**Issue by pphboy** [rime/weasel#612]
我在win10系统上，小狼毫开机无法立刻使用，需要等待什么加载一样。不知道是什么问题，很多人都有这个问题。
但我在win7上，开机又能立刻使用。
请问能否解决此问题

**Comment by lotem** [comment]
我從沒有遇到過。​不瞭解這個情況。

**Comment by pphboy** [comment]
> 我從沒有遇到過。​不瞭解這個情況。

请问您的win10版本是多少？
难道是我的版本问题吗

**Comment by sbxlmdsl** [comment]
如果电脑配置低的话，会出现需要等待的情况，因为需要等小狼毫算法服务启动后才能使用。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;皮皮豪&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月14日(星期天) 中午12:07
收件人:&nbsp;&quot;rime/weasel&quot;<weasel@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [rime/weasel] 请问能否解决小狼毫开机无法立即使用的问题？ (#612)

**Comment by pphboy** [comment]
> 如果电脑配置低的话，会出现需要等待的情况，因为需要等小狼毫算法服务启动后才能使用。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;皮皮豪&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年2月14日(星期天) 中午12:07 收件人:&nbsp;&quot;rime/weasel&quot;<weasel@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [rime/weasel] 请问能否解决小狼毫开机无法立即使用的问题？ (#612)

懂了，谢谢

**Comment by lotem** [comment]
大家都說Windows 20H2 這個版本輸入法問題很多，甚至完全不能用。我想：這麼嚴重？升級能搞的輸入法都不兼容了。
而我自己電腦上Windows升級總是失敗，最近才終於成功升級。
然後發現輸入法的表現跟升級前的Windows 10沒什麼差別。
我的Windows電腦就是專門開發和測試輸入法用的，沒安裝什麼系統級的軟件。
據用戶說某些軟件對系統的「優化」會影響到輸入法的正常使用。

**Comment by lotem** [comment]
啊。重新登錄一次後，我也不幸中招了。
輸入法版本是0.14.3。
待我測試一下最新代碼。

**Comment by pphboy** [comment]
> 啊。重新登錄一次後，我也不幸中招了。
> 輸入法版本是0.14.3。
> 
> 可能只有第一次使用維護的時間較長，我才注意到。或者是因爲我動作慢，後來又試幾回，打開記事本再切換完輸入法就已經能用了。

是的，每次开机的时候都会这样，虽然我一天都只开一次机，但每次开机的时候都无法立即投入工作

**Comment by lotem** [comment]
打算去掉啓動時自檢的程序。正好能避免這種情況。

**Comment by lotem** [comment]
​相同問題： https://github.com/rime/weasel/issues/241

**Comment by shyangs** [comment]
剛在父母的電腦用重開機解的.

可能是這個問題. （WeaselServer 小狼毫算法服務未啟動）

ref: [小狼毫Rime输入法只能打英文](https://blog.csdn.net/The_Time_Runner/article/details/89513879)

**Comment by jerryc127** [comment]
原来是bug
我重装了好多次都是不能打中文

**Comment by Youxikong** [comment]
做成Windows服务是不是可以保证电脑启动后可以立即使用呢。

**Comment by jerryc127** [comment]
看来是不打算修复这个问题

**Comment by schalldemz** [comment]
windows有开机优先级的吧，powertoys的启动优先级就很高，经常第一个启动

**Comment by light2001** [comment]
看起来应该是等待的问题，需要等算法服务启动才可以

**Comment by JW9506** [comment]
很簡單: 祇要
1: Win+R輸入`shell:startup` 進行一個打開文件夾的操作
2: 在小狼毫的安裝目录裡面找到`WeaselServer.exe`
3: 把以上的exe文件製作成一个「快倢方式」放進去這個文件夾就ok

**Comment by hong26** [comment]
> 很簡單: 祇要 1: Win+R輸入`shell:startup` 進行一個打開文件夾的操作 2: 在小狼毫的安裝目录裡面找到`WeaselServer.exe` 3: 把以上的exe文件製作成一个「快倢方式」放進去這個文件夾就ok

这个方法已经测试过了，并没有效果，开机依然无法自动启动算法服务。

**Comment by DKming** [comment]
> 很簡單: 祇要 1: Win+R輸入`shell:startup` 進行一個打開文件夾的操作 2: 在小狼毫的安裝目录裡面找到`WeaselServer.exe` 3: 把以上的exe文件製作成一个「快倢方式」放進去這個文件夾就ok

![image](https://user-images.githubusercontent.com/20635261/230758375-7a7ea115-afa4-4a72-be7a-e1e2c5cb0815.png)

開機已經把3個文件放進啓動文件夾，依然無效，每次開機都要手動打開 WeaselServer.exe，實在很麻煩

**Comment by JW9506** [comment]
> > 很簡單: 祇要 1: Win+R輸入`shell:startup` 進行一個打開文件夾的操作 2: 在小狼毫的安裝目录裡面找到`WeaselServer.exe` 3: 把以上的exe文件製作成一个「快倢方式」放進去這個文件夾就ok
> 
> ![image](https://user-images.githubusercontent.com/20635261/230758375-7a7ea115-afa4-4a72-be7a-e1e2c5cb0815.png)
> 
> 開機已經把3個文件放進啓動文件夾，依然無效，每次開機都要手動打開 WeaselServer.exe，實在很麻煩

你要把 shortcut「快捷方式」放进去... 你直接把.exe放进去是不对的.. 😂

**Comment by chwt163** [comment]
力大砖飞，直接在win系统的任务计划里，创建任务，目前启动正常。

**Comment by fxliang** [comment]
早前小狼毫加了重复运行服务退出的问题，上游针有性能改进和崩溃bug修复，可试下nightly build 看看问题是否修复

另外#1194 微调了启动项设置的问题，欢迎测试反馈

**Comment by mirtlecn** [comment]
这个原因是目前在注册表里面添加启动项，优先级比服务和任务计划低，

进入桌面后，小狼毫服务还没有拉起来

搜狗等输入法是依靠注册服务自启动的，所以没有这个问题

所以解决方法就是改用服务，或者任务计划。
