### ISSUE TITLE
扩展词库大小有限制吗?

### ISSUE THREAD

**Issue by 0x2CA** [rime/weasel#620]
当我想扩展我当词库时候，当table.bin大小小于200时候正常构建，但是当我加多了超过这个大小就会构建中卡死，不停当重新构建。不看什么词库，只要构建超过这个大小就卡死

**Comment by lotem** [comment]
相關問題及文檔鏈接： https://github.com/rime/librime/issues/410#issuecomment-788014012

**Comment by 0x2CA** [comment]
在windows安装当版本并没有对应当工具rime_deployer，是需要自己编译吧

**Comment by lotem** [comment]
Windows版本用`WeaselDeployer.exe`

**Comment by jhy1234** [comment]
试用了一下词典扩展包，有些疑问：

试用环境：小狼毫，librime更新到1.7.2，windows10
试用方法：在terra_pinyin.schema.yaml中直接添加
```
translator:
  packs:
    - pack.dict.yaml
(其它内容不变)
```
新建 pack.dict.yaml

问题：
1 新建或修改 pack.dict.yaml 后，重新部署无效，须删除主词典的 table.bin 后再部署才会生效
2 pack.dict.yaml 里的词条，打字时不会显示其提示码，如果主词典里有相同词条，则会显示主词典里的提示码
3 有些奇怪的字，比如𰻝 biang，写到 pack.dict 里无法打出来

另，超大的词库只有在小狼毫里会部署失败，其它平台都没问题，所以似乎不是librime的问题，而是小狼毫这个前端的问题

**Comment by SogaSuga** [comment]
试用了一下词典扩展包，有些疑问：

试用环境：小狼毫，librime更新到1.7.2，windows10
试用方法：在terra_pinyin.schema.yaml中直接添加
```
translator:
  packs:
    - pack.dict.yaml
(其它内容不变)
```
新建 pack.dict.yaml

问题：
1 新建或修改 pack.dict.yaml 后，重新部署无效，须删除主词典的 table.bin 后再部署才会生效
2 pack.dict.yaml 里的词条，打字时不会显示其提示码，如果主词典里有相同词条，则会显示主词典里的提示码
3 有些奇怪的字，比如𰻝 biang，写到 pack.dict 里无法打出来

另，超大的词库只有在小狼毫里会部署失败，其它平台都没问题，所以似乎不是librime的问题，而是小狼毫这个前端的问题

**Comment by Johnleegy** [comment]
> 试用了一下词典扩展包，有些疑问：
> 
> 试用环境：小狼毫，librime更新到1.7.2，windows10 试用方法：在terra_pinyin.schema.yaml中直接添加
> 
> ```
> translator:
>   packs:
>     - pack.dict.yaml
> (其它内容不变)
> ```
> 
> 新建 pack.dict.yaml
> 
> 问题： 1 新建或修改 pack.dict.yaml 后，重新部署无效，须删除主词典的 table.bin 后再部署才会生效 2 pack.dict.yaml 里的词条，打字时不会显示其提示码，如果主词典里有相同词条，则会显示主词典里的提示码 3 有些奇怪的字，比如𰻝 biang，写到 pack.dict 里无法打出来
> 
> 另，超大的词库只有在小狼毫里会部署失败，其它平台都没问题，所以似乎不是librime的问题，而是小狼毫这个前端的问题

这个功能看起来已经无效且无人处理。
@lotem
