### ISSUE TITLE
安装包文件损坏

### ISSUE THREAD

**Issue by summiry** [rime/weasel#630]
是在官网 https://rime.im/  下载的，电脑是win10系统。下载软件安装包之后解压时提示文件损坏
![image](https://user-images.githubusercontent.com/31307902/116020665-58713580-a679-11eb-83ca-8e903f33af57.png)

**Comment by crackself** [comment]
请尝试修改下载文件的后缀名为.exe，不要解压。

**Comment by Youxikong** [comment]
根据打包方式不同，有些exe是不能解压的。

**Comment by Ace-Who** [comment]
官网没有提供 zip 包下载吧。

**Comment by summiry** [comment]
官网下载的就是zip压缩包，改了后缀为exe之后可以安装了。

**Comment by Ace-Who** [comment]
官网的下载链接是
https://dl.bintray.com/rime/weasel/weasel-0.14.3.0-installer.exe

我下载多年还没遇到过 zip 包。经搜索发现，存在一种「下载文件时扩展名被自动更改为 .zip」的现象，与本地软件有关，具体不明。
