### ISSUE TITLE
bintray already sunset

### ISSUE THREAD

**Issue by palxex** [rime/weasel#632]
[Source](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)
But rime.im still points there for windows user, which results a "Forbidden!" alert page.
Please consider upload a temporary installer to github releases page, or anywhere else that users could touch.

**Comment by keke-cute** [comment]
REMINDER: JFrog is sunsetting Bintray services on May 1st, 2021

**Comment by lotem** [comment]
工單 https://github.com/rime/home/issues/701
