### ISSUE TITLE
无法下载安装包

### ISSUE THREAD

**Issue by Matt-wzy** [rime/weasel#633]
此链接<https://dl.bintray.com/rime/weasel/weasel-0.14.3.0-installer.exe> 于山东地区打开显示`Forbidden!`

**Comment by clarkking** [comment]
之前另一個帖子里提到bintray要停止下載貼服務了，應該是這個問題，估計還得等等。。

**Comment by lotem** [comment]
工單 https://github.com/rime/home/issues/701
