### ISSUE TITLE
请问刚发布的14.3和之前的有什么区别? 

### ISSUE THREAD

**Issue by nutnutwin** [rime/weasel#634]
@lotem 
刚才(20分钟前)来了一个邮件说Release 了14.3
确认了一下PC上之前就是同样版本

谢谢

**Comment by lotem** [comment]
沒有區別。
Bintray停業了，原來的下載點失效。因此把安裝包上傳到Github Releases。稍後會更新官網下載鏈接。

**Comment by lotem** [comment]
工單 https://github.com/rime/home/issues/701

**Comment by nutnutwin** [comment]
THX 
Release Note
