### ISSUE TITLE
請問有無移動設備開發計劃？

### ISSUE THREAD

**Issue by biaoyinzi** [rime/weasel#65]
能否將輸入法引擎遷移至Android和iOS平臺？

**Comment by sisyphus886** [comment]
已經有了，安卓端trime同文輸入法（結構輸入法），iOS有iRime不是很穩定

**Comment by osfans** [comment]
结构输入法是其他人重新打包同文的。目前同文只在github qq群 酷市场发布。 https://github.com/osfans/trime
