### ISSUE TITLE
对整句输入有优化吗？

### ISSUE THREAD

**Issue by biaoyinzi** [rime/weasel#66]
有时候输入整句会产生不太合理的结果，这方面似乎不如操作系统自带的输入法，不知道有没有计划改进？

**Comment by Prcuvu** [comment]
这是后端问题，请到[这里] (https://github.com/rime/librime/issues)提问。

**Comment by Prcuvu** [comment]
另外，[小狼毫已经停止维护了] (https://github.com/rime/home/issues/25)，即使改进也无法体现出来。建议使用更新频繁的[新前端] (https://github.com/EasyIME/PIME)。

**Comment by lotem** [comment]
新前端对整句输入有优化吗？

**Comment by biaoyinzi** [comment]
问题已经转到librime了，如果前端没有处理可以关闭

**Comment by osfans** [comment]
沒有，那我關閉了。
