### ISSUE TITLE
如何禁止小狼毫输入法自动更新？

### ISSUE THREAD

**Issue by lopengye** [rime/weasel#666]
如题，是更改配置文件还是禁用小狼毫算法服务自启动？

**Comment by Python-37** [comment]
没这么干过，试试屏蔽rime.github.io，rime.im两个域名？

**Comment by mokapsing** [comment]
哪用这么麻烦，第一次点了不自动更新，它后面就不会自己更新了吧，另外要是禁用了小狼毫算法服务就没法打字了

**Comment by lotem** [comment]
如樓上所言，在第一次詢問的時候選擇不自動檢查更新。

**Comment by vvsolo** [comment]
修改注册表
[HKEY_CURRENT_USER\Software\Rime\Weasel\Updates]
"DidRunOnce"="1"
"CheckForUpdates"="0"

**Comment by lopengye** [comment]
> 修改注册表
> [HKEY_CURRENT_USER\Software\Rime\Weasel\Updates]
> "DidRunOnce"="1"
> "CheckForUpdates"="0"

**Comment by lopengye** [comment]
> > 修改注册表
> > [HKEY_CURRENT_USER\Software\Rime\Weasel\Updates]
> > "DidRunOnce"="1"
> > "CheckForUpdates"="0"

太感谢了！！！！！！！！！！！

**Comment by lopengye** [comment]
> 哪用这么麻烦，第一次点了不自动更新，它后面就不会自己更新了吧，另外要是禁用了小狼毫算法服务就没法打字了

第一次询问是否需要更新是在系统重启之后。。
