### ISSUE TITLE
下一版，小狼毫能实现非输入状态按键不出现输入状态么？

### ISSUE THREAD

**Issue by ednykissyou** [rime/weasel#667]
有时我在资源管理器中，我本想按D，快速指向D开头的文件或文件夹，结果小狼毫出现了……

有时我在PS中，想按键B键，打开画笔，结果小狼毫出现了……
（好像其他中文输入法也有这个毛病）

但如果在英文输入法状态下，好像它能判断是不是输入状态，如果不是，就针对的是当前软件的快捷键。

**Comment by lotem** [comment]
是不是輸入狀態不由輸入法決定，由應用決定。應用說是輸入狀態，系統再調輸入法。
另外，用戶也可以手動控制是否使用輸入法。
