### ISSUE TITLE
同样配置鼠须管好好的，移植到小狼毫各种问题，请看日志，什么问题啊？

### ISSUE THREAD

**Issue by aaron2wh** [rime/weasel#669]
[rime.weasel.DESKTOP-1KE6S8I.aaron.log.WARNING.20210924-172621.6976.txt](https://github.com/rime/weasel/files/7224626/rime.weasel.DESKTOP-1KE6S8I.aaron.log.WARNING.20210924-172621.6976.txt)
 全拼，双拼都完全无法使用扩展词库 luna_pinyin.extended.dict.yaml ，双拼无法使用 动态日期时间脚本，无法调用 custome_phrases，请教一下问题出在那里呢。
这些所有配置在鼠须管下完全没问题
对了，我的鼠须管配置如下：https://github.com/aaron2wh/Rime/releases/tag/bible

**Comment by aaron2wh** [comment]
Log file created at: 2021/09/24 17:26:21
Running on machine: DESKTOP-1KE6S8I
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0924 17:26:21.290565  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\punctuation.custom.yaml'.
W0924 17:26:21.295562  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\key_bindings.custom.yaml'.
W0924 17:26:21.346334  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\pinyin.yaml'.
E0924 17:26:21.346334  7192 config_compiler.cc:428] resource could not be loaded: pinyin
E0924 17:26:21.346334  7192 config_compiler.cc:536] unresolved dependency: Patch(pinyin:/abbreviation)
E0924 17:26:21.346334  7192 config_compiler.cc:536] unresolved dependency: PendingChild(luna_pinyin.schema:/speller/algebra)
E0924 17:26:21.346334  7192 config_compiler.cc:536] unresolved dependency: PendingChild(luna_pinyin.schema:/speller)
E0924 17:26:21.346334  7192 config_component.cc:250] error building config: luna_pinyin.schema
W0924 17:26:21.587046  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\stroke.custom.yaml'.
W0924 17:26:21.587046  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\punctuation.custom.yaml'.
W0924 17:26:21.602670  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\key_bindings.custom.yaml'.
W0924 17:26:22.517020  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\grammar.yaml'.
E0924 17:26:22.517020  7192 config_compiler.cc:428] resource could not be loaded: grammar
E0924 17:26:22.517020  7192 config_compiler.cc:536] unresolved dependency: Include(grammar:/hant)
E0924 17:26:22.517020  7192 config_compiler.cc:536] unresolved dependency: PendingChild(double_pinyin.custom:/patch)
W0924 17:26:22.517020  7192 config_compiler.cc:367] accessing blocking node with unresolved dependencies: double_pinyin.custom:
W0924 17:26:22.517020  7192 config_compiler.cc:529] circular dependencies detected in double_pinyin.custom:/patch
W0924 17:26:22.522027  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\punctuation.custom.yaml'.
W0924 17:26:22.527067  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\key_bindings.custom.yaml'.
W0924 17:26:22.776873  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\numbers.custom.yaml'.
W0924 17:26:22.776873  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\punctuation.custom.yaml'.
W0924 17:26:22.791978  7192 config_data.cc:62] nonexistent config file 'C:\Users\aaron\AppData\Roaming\Rime\key_bindings.custom.yaml'.

**Comment by Python-37** [comment]
日志里说在用户文件夹里缺东西，你安装好了之后有把自带的配置删掉吗？

**Comment by aaron2wh** [comment]
没有啊,安装好之后,就只有这几个文件（见截图），根本不存在上面提到的文件啊
![捕获](https://user-images.githubusercontent.com/43267693/134657339-6070758e-681a-4b58-8aa5-05f70d3dde63.PNG)

**Comment by Python-37** [comment]
> 
> 
> 没有啊,安装好之后,就只有这几个文件（见截图），根本不存在上面提到的文件啊
> ![捕获](https://user-images.githubusercontent.com/43267693/134657339-6070758e-681a-4b58-8aa5-05f70d3dde63.PNG)

安装时要勾选你需要使用的方案，你可能跳过了

**Comment by lotem** [comment]
​配置不完整，缺少文件。
