### ISSUE TITLE
stroke相關的文件可以從個人和程序文件夾都刪除嗎？

### ISSUE THREAD

**Issue by aaron2wh** [rime/weasel#671]
因爲本人不需要用到筆畫輸入，而且我發現這個相關的文件是體積最大的，我想刪除，會出問題嗎？

**Comment by lotem** [comment]
​可以刪除。
會出問題的是拼音等輸入方案的筆畫反查功能。最好一併刪除相關的配置代碼：
https://github.com/rime/rime-luna-pinyin/blob/6e677427764b542313858eaed22c2951d8ec22fe/luna_pinyin.schema.yaml#L18
https://github.com/rime/rime-luna-pinyin/blob/6e677427764b542313858eaed22c2951d8ec22fe/luna_pinyin.schema.yaml#L50

**Comment by aaron2wh** [comment]
謝謝指點
