### ISSUE TITLE
中国大陆貌似无法通过HTTPS更新submodules

### ISSUE THREAD

**Issue by Prcuvu** [rime/weasel#68]
将submodules的地址改成HTTPS的话，在中国大陆更新仓库会导致connection refused的错误。SSH就没有这样的问题。

**Comment by rexdf** [comment]
我的可以 电信的网络

**Comment by rexdf** [comment]
![weasel](https://cloud.githubusercontent.com/assets/4038241/19319810/34d4aa4c-90e1-11e6-93a1-b2d1d44a53ef.png)
