### ISSUE TITLE
请教一下vs2109该怎么编译？

### ISSUE THREAD

**Issue by jack2583** [rime/weasel#685]
使用visual studio编译一直不成功，有大佬提供一下编译方法吗？

**Comment by lotem** [comment]
把 `INSTALL.md` 裏面的VS2017換成VS2019、升級Boost庫、以 `env.vs2019.bat` 爲模板寫好 `env.bat`，其他沒啥特別的了吧。

**Comment by lotem** [comment]
哦，原來網絡操作失靈，我最近幾個月的修改都沒有成功推到GitHub。
失敬失敬。
