### ISSUE TITLE
明月输入法自定义配置文件patch取消逗号句号翻页问题

### ISSUE THREAD

**Issue by wsspsb** [rime/weasel#688]
我在自带的配置文件中观察到明月输入法默认设置了逗号句号翻页,我想输入逗号句号时直接提交上屏之前输入的内容再上屏符号.
比如输入ceshi.则上屏测试.
我patch后基本上可以做到,但是发现符号用英文标点时逗号句号只能上屏之前输入的内容.
比如输入ceshi.则上屏测试(句号没有上屏)
请教下我是不是哪里没patch完善
![图片](https://user-images.githubusercontent.com/23711469/145715041-cdf1be79-5aa5-4942-bafd-f59971a06a55.png)
![图片](https://user-images.githubusercontent.com/23711469/145715068-cead76a6-b6e3-4a86-bb40-2268800fa1c6.png)
# 明月拼音自定义配置
patch:
  'translator/dictionary': my_dict_pinyin_all # 指定自定义总词典位置
  'key_binder/bindings':
    - { when: paging, accept: comma, send: comma } # 取消逗号翻页
    - { when: has_menu, accept: period, send: period } # 取消句号翻页

**Comment by wsspsb** [comment]
这个按键方案能达道我想要的效果,就很奇怪(区别只是英文标点变成了中文标点,不过我日常是是用英文标点的)
![图片](https://user-images.githubusercontent.com/23711469/145715152-747f09bb-57ae-4f7c-8d18-029cdf4ba756.png)

**Comment by wsspsb** [comment]
![图片](https://user-images.githubusercontent.com/23711469/145715344-4d738bf1-bc9f-459a-9d84-5d8a3bb432e7.png)
我是根据默认配置文件这里改的,把default.yaml中对应的删除掉当然就完全能达到我想要的效果(已经试过了可以),但是为了升级也能兼容,所以还是想patch.请教下有没有好的办法,
![图片](https://user-images.githubusercontent.com/23711469/145715570-cae19ac3-12e8-40e1-8644-e330f0e8cd2d.png)

**Comment by Ace-Who** [comment]
https://github.com/rime/home/issues/754

**Comment by wsspsb** [comment]
> [rime/home#754](https://github.com/rime/home/issues/754)
谢谢,大概明白了   就是patch覆盖这一部分把不想添加的取消掉
key_binder:
    bindings:
      __patch:
