### ISSUE TITLE
像FFmpeg 设立个耻辱柱吧

### ISSUE THREAD

**Issue by ghost** [rime/weasel#692]
我是这个月才开始用小狼毫，也是这个月才发现卡饭出了输入法，下载过卡饭输入法，发现

与小狼毫及其相似，同时网络上也搜索到了有关卡饭使用小狼毫源码且未开源的帖子

感觉小狼毫这边不做回应容易让相关贡献者寒心，毕竟多数开源软件都是靠爱发电，莫名被
商业公司拿去使用且不按照协议开源又未作贡献，部分人可能会逐渐脱离

虽然中国法律属于谁钱多谁有理，一切开源协议皆是形体虚设，
而设立个耻辱柱估计是一个开源软件对不遵守协议者最低的回应了

**Comment by mokapsing** [comment]
最初版本确实是修改自小狼毫，不过最新版本已经没有使用小狼毫了，只是用到librime，后者是bsd协议，开源声明中也有提及

**Comment by lotem** [comment]
懒得管。早先弯弯也有一家公司全平台抄了一遍。关键是又不准备打官司，没有收益还得自己费劲取证，不划算啊。

**Comment by ewjy** [comment]
> 懒得管。早先弯弯也有一家公司全平台抄了一遍。关键是又不准备打官司，没有收益还得自己费劲取证，不划算啊。

方便了解一下是哪家吗？据我所知台湾比较出名基于RIME框架的输入法是意传公司做的，不过他们都有照开源协议公布修改后的源代码。

**Comment by mokapsing** [comment]
> > 懒得管。早先弯弯也有一家公司全平台抄了一遍。关键是又不准备打官司，没有收益还得自己费劲取证，不划算啊。
> 
> 方便了解一下是哪家吗？据我所知台湾比较出名基于RIME框架的输入法是意传公司做的，不过他们都有照开源协议公布修改后的源代码。

这家所谓的意传有网站吗，我想看看他们家的输入法好不好用

**Comment by ewjy** [comment]
> > > 懒得管。早先弯弯也有一家公司全平台抄了一遍。关键是又不准备打官司，没有收益还得自己费劲取证，不划算啊。
> > 
> > 
> > 方便了解一下是哪家吗？据我所知台湾比较出名基于RIME框架的输入法是意传公司做的，不过他们都有照开源协议公布修改后的源代码。
> 
> 这家所谓的意传有网站吗，我想看看他们家的输入法好不好用

[](https://sujiphuat.ithuan.tw/)
他们做的是台语输入法，据说未来还会做客语输入法。
