### ISSUE TITLE
 LINK : fatal error LNK1181: 无法打开输入文件“rime.lib”

### ISSUE THREAD

**Issue by rtransformation** [rime/weasel#694]
我用的是visual studio 2017 community对小狼毫进行编译，输入build.bat thirdparty的时候遇到如下错误：

“E:\download\common\weasel\weasel.sln”(Build 目标) (1) ->
“E:\download\common\weasel\WeaselServer\WeaselServer.vcxproj”(默认目标) (6) ->
(Link 目标) ->
  LINK : fatal error LNK1181: 无法打开输入文件“rime.lib” [E:\download\common\weasel\WeaselServer\WeaselServer.vcxproj]

“E:\download\common\weasel\weasel.sln”(Build 目标) (1) ->
“E:\download\common\weasel\WeaselDeployer\WeaselDeployer.vcxproj”(默认目标) (11) ->
  LINK : fatal error LNK1181: 无法打开输入文件“rime.lib” [E:\download\common\weasel\WeaselDeployer\WeaselDeployer.vcxproj]

这个该如何解决呢？

**Comment by red-co** [comment]
+1, 请问这个是怎么解决的？
