### ISSUE TITLE
就不能把“词库导入”这个功能弄简便一点么？

### ISSUE THREAD

**Issue by LiuZengqiang** [rime/weasel#696]
就不能加入 直接 选择yaml文件导入词库的功能么？头疼。。。。

**Comment by lotem** [comment]
理論上可以。
做一個界面程序根據用戶的選擇編輯YAML代碼。
估計大部分用戶用不到這項定製功能，而高手又不止要定製這一項，大多習慣編輯YAML源文件，所以沒人專門做簡化。
