### ISSUE TITLE
请问下词库能不能设置自动补全

### ISSUE THREAD

**Issue by wsspsb** [rime/weasel#697]
比如我导入了一个词库，有一个12345的词，输入开头的一部分123并不能提示，需要输入到1234甚至12345才会使用到这个词，可以设置为输入12甚至1，就提示这个12345吗。
ps：我是用的是明月输入法
下面是实际遇到的问题截图
![no auto complete](https://user-images.githubusercontent.com/23711469/147432528-e5adeb0f-1e00-49c5-8baa-3543a995d4e6.jpg)
![auto complete](https://user-images.githubusercontent.com/23711469/147432538-085bc44b-504a-426c-aaa1-b2cbb442e9a6.jpg)

**Comment by rtransformation** [comment]
我沒試過中文拼音輸入法設置中加入  "spelling_hints: 9"會怎麼樣，你試試，比如把這個9換成小一點的數字。

**Comment by wsspsb** [comment]
> 

![图片](https://user-images.githubusercontent.com/23711469/148011421-82cb2515-ceb0-4de3-9c3d-7be2816735d2.png)
目前是有这个配置的

**Comment by wsspsb** [comment]
> 我沒試過中文拼音輸入法設置中加入 "spelling_hints: 9"會怎麼樣，你試試，比如把這個9換成小一點的數字。
![图片](https://user-images.githubusercontent.com/23711469/148011475-c1d4e3fd-345e-4253-a136-b2e07a6f8cb3.png)
目前是有这个配置的

**Comment by wsspsb** [comment]
> 我沒試過中文拼音輸入法設置中加入 "spelling_hints: 9"會怎麼樣，你試試，比如把這個9換成小一點的數字。

不好意思我之前好像加错地方了, 然后我参照[雪齋的文檔](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md)里面的说明,修改明月拼音的配置文件,9和3都试过了没效果,如下图输入最后一个字的q字母才会提示正确的字典
![图片](https://user-images.githubusercontent.com/23711469/148504100-0d1111d5-372f-434d-b07b-126623c38224.png)

**Comment by zeng-y-l** [comment]
与 rime/home#904 相同，似乎还没有解决

**Comment by ksqsf** [comment]
librime 1.11 已有该功能。目前只能在输入 4 个或多于 4 个音节时提示长词。
