### ISSUE TITLE
谁给编译一下最新版的小狼毫，或者给指点一下如何编译

### ISSUE THREAD

**Issue by blueflagbj** [rime/weasel#70]
如题：
谁给编译一下最新版的小狼毫，或者给指点一下如何编译？
拜谢。。。

**Comment by Prcuvu** [comment]
现在的编译脚本还是VS2013，但是librime已经是VS2015了。我把它整理一下。

**Comment by Prcuvu** [comment]
更新好了，请参考[INSTALL.md] (https://github.com/rime/weasel/blob/develop/INSTALL.md)。

**Comment by biaoyinzi** [comment]
在win7下用vs2017编译通过了。但是从output运行安装文件后，不能正常输入。

**Comment by ding** [comment]
为何无人打包最新版本呢？

**Comment by Prcuvu** [comment]
@ding
最新版[永久链接](https://ci.appveyor.com/api/projects/lotem/weasel/artifacts/output%2Farchives%2Fweasel-0.9.30.0-installer.exe)。
