### ISSUE TITLE
weasel.custom.yaml设置中用于自动设定英文输入模式的app_options在终端中失效

### ISSUE THREAD

**Issue by longguzzz** [rime/weasel#700]
win10电脑，设置 code.exe, powershell.exe, cmd.exe, nvim.exe 的ascii_mode 为 true 可以实现预期效果
如果对 openconsole.exe 或 windowsterminal.exe 或 conhost.exe 设置，则 weasel.custom.yaml 中的所有配置都会失效

**Comment by lotem** [comment]
不會的。

失效通常是因爲YAML寫法有錯誤。

**Comment by cdc94** [comment]
请问win11系统，为什么code.exe等程序可以设置默认英文输入，而powershell.exe、cmd.exe、git-bash.exe却都不生效是怎么回事？
