### ISSUE TITLE
windows 下切换输入方案后模糊音设置会失效

### ISSUE THREAD

**Issue by iamalexblue** [rime/weasel#702]
# 环境
- 设备：Windows 11 22000.434
- Rime 版本：0.14.3
# 问题描述
Windows 下配置文件中输入方案有小鹤双拼和全拼，同时设置了ing-in 和 eng-en 模糊音，当方案选单中选中两者后模糊音没有丢失，但是在不同的条件下输入的时候有时是小鹤，有时候是全拼，貌似并不能固定。

然后当把全拼从方案选单中取消勾选之后，模糊音配置便会消失。

查看配置文件之后发现之前添加的模糊音设置丢失了，起初我以为是云盘同步的原因导致丢失的，重新设置部署一遍之后可以复现这个问题。

**Comment by lotem** [comment]
不能確定程序有問題。
需要討論具體的配置。
參考 https://github.com/rime/home/wiki/CustomizationGuide#定製指南

**Comment by fxliang** [comment]
没有更新更新的信息，无法判断，暂关此issue。如需可再打开。
