### ISSUE TITLE
设置horizontal后上下左右键未切换

### ISSUE THREAD

**Issue by Rothes** [rime/weasel#703]
如题. 系统为 Windows 11 x64
设置 horizontal 为 true 后, 仍然需要使用上下键切换候选词.

**Comment by Youxikong** [comment]
切换的快捷键和布局横纵是独立设置的。

**Comment by Rothes** [comment]
> 切换的快捷键和布局横纵是独立设置的。

尝试过修改 key_bindings.yaml 中的 emacs_editing, (交换Up Down/Left Right) 仍然没有变化, 是我的操作有问题吗?

**Comment by lotem** [comment]
尚未實現這套邏輯。
