### ISSUE TITLE
輸入文字自動切換字體問題

### ISSUE THREAD

**Issue by SadPencil** [rime/weasel#704]
小狼毫輸入法要麼安裝在`中文（簡體，中國大陸）`語言下，要麼安裝在`中文（繁體，臺灣）`語言下，這會導致在 Word、WordPad（寫字板）等支持富文本輸入的軟件中出現字體問題，具體表現爲：

在Word中，如果當前字體是簡體中文字體，將小狼毫安裝在`中文（繁體，臺灣）`語言下，則會導致輸入文字後字體被強制更改爲`新細明體`；如果當前字體是繁體中文字體，且小狼毫安裝在`中文（簡體，中國大陸）`語言下，則會導致輸入文字後字體被強制更改爲`等線`（簡體中文字體之一）。

**Comment by Bobo-alcazar** [comment]
![圖片](https://github.com/rime/weasel/assets/62412037/fa246c9f-f386-448d-87ba-fda143db5e9e)

**Comment by fxliang** [comment]
这个是word的逻辑，他会根据当前language profile的langid调整应用的响应，当小狼毫注册到简体中文或者繁体中文下的时候，langid是不一样的，因此Word对应作出了调整。换其他tsf输入法也会有这个问题。无解。

待#1181 合并后，可以同时存在小狼毫简体和小狼毫繁体的输入法，可以根据需要切换。就此关闭此issue。如有需要可以重开。

**Comment by SadPencil** [comment]
@fxliang 感谢回复 不过一般不是在PR里写fixes 这个issue id，然后等PR被合并时自动关闭此issue嘛

**Comment by fxliang** [comment]
也行
