### ISSUE TITLE
bug report：在 office word 2016/2019/2021 中 拖动 文本标尺后 打字时输入法候选框 不显示

### ISSUE THREAD

**Issue by BH2WFR** [rime/weasel#707]
在 office word 2016/2019/2021 中 拖动 文本标尺后 打字时输入法候选框 不显示

GIF 录屏链接如下：（imgur）
     [GIF录屏链接：https://imgur.com/a/pwccsG9  ](https://imgur.com/a/pwccsG9)

**Comment by Python-37** [comment]
试过这个吗 https://github.com/rime/weasel/issues/228

**Comment by mqpbjnsdjvbwl** [comment]
> 试过这个吗 #228

试过，还是无用

**Comment by seszu** [comment]
我如何给你点赞，我也遇到一样的问题，只要拖动标尺后，候选框就会一闪而过，重启word后正常

**Comment by YQ-YSY** [comment]
诱发Rime在Word中闪烁的条件（故障可重现）以及临时解决方法

很多朋友都遇到了Rime输入法在word中闪烁，难以使用的问题。
我的电脑是：Win10系统，Office 2019，小狼毫weasel-0.14.3.0
经过多尝试和试验，终于发现诱发闪烁的条件（故障可重现）：关键是在Word的“标尺”上，

当我用鼠标拖动“标尺”下方的“小四方形（左缩进）”或者“向上小三角形（悬挂缩进）”几次后，用Rime打字就会闪烁。
临时的解决方法是：把鼠标放在标尺上，就能正常打字，不闪烁了。但是，如果鼠标从标尺上移开，打字又会闪烁。

所以记住，如果要在Word标尺上操作，就先切换为其他输入法，不用Rime。
如果不小心操作了Word标尺，已经造成Rime闪烁了，那么把鼠标放在标尺上，就能继续打字了。
应急打完字后，保存文件，关闭Word，再重新打开，Rime才恢复正常。目前就只能这样了。

——以上信息提供给Rime的开发者，希望能对修改调试程序有帮助。

**Comment by determ1ne** [comment]
fixed in 0.15.0

**Comment by YQ-YSY** [comment]
> fixed in 0.15.0

很高兴看到问题得到解决，谢谢！
