### ISSUE TITLE
使用暗色主题(如lost_temple)时, 中英文状态悬浮提示很难看清, 黑乎乎一团

### ISSUE THREAD

**Issue by xuanqing** [rime/weasel#709]
应该是WeaselServer.exe中的资源图标的"中"/"英"两字颜色0x323233 与 color_schemes中的back_color相近导致的
建议1: 在主题中加入明/暗选项以区分不同背景色
或是
建议2: 让中英文状态文字同步color_schemes的字体颜色以统一显示

**Comment by fxliang** [comment]
0.15.0之后，支持方案自定义图标，已解
