### ISSUE TITLE
Windows下vim_mode可否支持？

### ISSUE THREAD

**Issue by liang-0131** [rime/weasel#713]
mac下`vim_mode: true`很好用 但是Windows无效。希望也支持

**Comment by liang-0131** [comment]
neovim没有这个机制😂

**Comment by lotem** [comment]
可現在也沒現成的。
過去在微軟用IME框架時候做過。如今都用TSF框架了，老代碼也不能用。

**Comment by liang-0131** [comment]
那只能这样了

**Comment by zhuzhzh** [comment]
我在vscode里设成vim mode，  经常在normal mode下， 输入中文，然后字符还修改了我的源代码， 也就是rime会突破normal model不能输入的限制

**Comment by WingDust** [comment]
能开放一个接口 ，让外部程序可以切换中英吗，也省了去适配多个程序

**Comment by windily-cloud** [comment]
这就有点难受了......

**Comment by g0ne150** [comment]
难受加+

**Comment by qujihan** [comment]
> 可現在也沒現成的。 過去在微軟用IME框架時候做過。如今都用TSF框架了，老代碼也不能用。
你好，vim_mode会不考虑支持了么？

**Comment by qujihan** [comment]
> 可現在也沒現成的。 過去在微軟用IME框架時候做過。如今都用TSF框架了，老代碼也不能用。

你好，vim_mode会不考虑支持了么？

**Comment by newbieQQ** [comment]
难受+n

**Comment by wutianjun5858** [comment]
难受+n+1

**Comment by qujihan** [comment]
大家可以参考我的这个文章， 在win下曲线救国实现vim mode
https://zhuanlan.zhihu.com/p/654489636

**Comment by fxliang** [comment]
#1047
