### ISSUE TITLE
如何关闭禁用输入法这个功能

### ISSUE THREAD

**Issue by DouYou-DianShuai** [rime/weasel#717]
使用过程中, Ctrl+Space快捷键会使输入法进入禁用状态, 由于习惯了Ctrl+N来选择输入项然后使用空格上屏, 但由于禁用输入法这个快捷键,  容易因输入完毕后被禁用而打不上字。
尝试在快捷键映射中, 将Ctrl+Space (即Control+space) 设置为候选项上屏, 也不起作用。(设置后此快捷键依旧是 "已禁用输入法")

反复翻阅了多遍文档, 没发现此功能的介绍, 想知道关闭Ctrl+Space对应的功能的有效方法
![image](https://user-images.githubusercontent.com/65339064/162489161-6aa03766-dc7f-46f7-8d68-075b737e3619.png)

**Comment by DouYou-DianShuai** [comment]
系统是win11

**Comment by DouYou-DianShuai** [comment]
非常感谢您对我的帮助

**Comment by DouYou-DianShuai** [comment]
> 由于使用过程中,习惯了Ctrl+N/P进行选择.   因此输入过程中容易产生Ctrl按下时按Space来"上屏候选项".   (所以添加了如下配置)
>> ![image](https://user-images.githubusercontent.com/65339064/164459783-5c469226-1ecb-4ced-b742-f98ebbaf67ea.png)

> 随后 win系统下原有会造成输入法关闭的 Ctrl+Space 的功能,   也已经按回答的方法成功关闭了.


**可是并没有产生效果.     Ctrl+Space 清空已有输入的问题依旧存在**

经过尝试, 目前还没发现解决方法.
如果可以的话,希望能够继续获得您的帮助

**Comment by DouYou-DianShuai** [comment]
* 打开注册表, 按中括号路径选择后,  修改对应值, 即可禁用win下的  ctrl+space   , 若失效重新设置即可
**[参考链接](https://superuser.com/questions/327479/ctrl-space-always-toggles-chinese-ime-windows-7)**
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Input Method\Hot Keys\00000010]
"Key Modifiers"=hex:00,c0,00,00
"Virtual Key"=hex:ff,00,00,00

[HKEY_CURRENT_USER\Control Panel\Input Method\Hot Keys\00000070]
"Key Modifiers"=hex:00,c0,00,00
"Virtual Key"=hex:ff,00,00,00
```

**Comment by DouYou-DianShuai** [comment]
> * 打开注册表, 按中括号路径选择后,  修改对应值, 即可禁用win下的  ctrl+space   , 若失效重新设置即可
>   **[参考链接](https://superuser.com/questions/327479/ctrl-space-always-toggles-chinese-ime-windows-7)**
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_CURRENT_USER\Control Panel\Input Method\Hot Keys\00000010]
> "Key Modifiers"=hex:00,c0,00,00
> "Virtual Key"=hex:ff,00,00,00
> 
> [HKEY_CURRENT_USER\Control Panel\Input Method\Hot Keys\00000070]
> "Key Modifiers"=hex:00,c0,00,00
> "Virtual Key"=hex:ff,00,00,00
> ```

# 对上述解决方案做下补充哈
* 若通过修改注册表的方式来关闭`Ctrl+Space`,  则勿在`修改输入法热键`中做操作。
* 若遇到后续由于系统更新而使得`Ctrl+Space`重新打开, 则按下面配置后重启即可:
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_USERS\.DEFAULT\Control Panel\Input Method\Hot Keys\00000010]
> "Key Modifiers"=hex:00,c0,00,00
> "Virtual Key"=hex:ff,00,00,00
> 
> [HKEY_USERS\.DEFAULT\Control Panel\Input Method\Hot Keys\00000070]
> "Key Modifiers"=hex:00,c0,00,00
> "Virtual Key"=hex:ff,00,00,00
> ```

**Comment by w3l7** [comment]
这个好像要重启才能生效

**Comment by Janzulene** [comment]
# 对上面的方案进行补充

首先感谢 @srackhall ，跟着你的线索我找到了解决的办法。不过你的方案好像对全局安装的小狼毫不起作用，然后我找到了一个更普适的注册表方案：
* 在上面的基础上，除了修改 `User` 下面的注册表，还修改了 `.DEFAULT` 下面的注册表
* 把下面的代码保存到一个文本文件中，然后重命名为 `CloseIME.reg`，双击执行就完成修改了。保存为一个注册表文件的好处是可以很方便的重复执行（比如系统升级覆盖了之前的设定），不用一个一个打开注册表进行修改。

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Input Method\Hot Keys\00000010]
"Key Modifiers"=hex:00,c0,00,00
"Virtual Key"=hex:ff,00,00,00

[HKEY_CURRENT_USER\Control Panel\Input Method\Hot Keys\00000070]
"Key Modifiers"=hex:00,c0,00,00
"Virtual Key"=hex:ff,00,00,00

[HKEY_USERS\.DEFAULT\Control Panel\Input Method\Hot Keys\00000010]
"Key Modifiers"=hex:02,c0,00,00
"Target IME"=hex:00,00,00,00
"Virtual Key"=hex:ff,00,00,00

[HKEY_USERS\.DEFAULT\Control Panel\Input Method\Hot Keys\00000070]
"Key Modifiers"=hex:02,c0,00,00
"Target IME"=hex:00,00,00,00
"Virtual Key"=hex:ff,00,00,00
```

**Comment by MiXiaomu** [comment]
> # 对上面的方案进行补充
> 首先感谢 [@srackhall](https://github.com/srackhall) ，跟着你的线索我找到了解决的办法。不过你的方案好像对全局安装的小狼毫不起作用，然后我找到了一个更普适的注册表方案：
> 
> * 在上面的基础上，除了修改 `User` 下面的注册表，还修改了 `.DEFAULT` 下面的注册表
> * 把下面的代码保存到一个文本文件中，然后重命名为 `CloseIME.reg`，双击执行就完成修改了。保存为一个注册表文件的好处是可以很方便的重复执行（比如系统升级覆盖了之前的设定），不用一个一个打开注册表进行修改。
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_CURRENT_USER\Control Panel\Input Method\Hot Keys\00000010]
> "Key Modifiers"=hex:00,c0,00,00
> "Virtual Key"=hex:ff,00,00,00
> 
> [HKEY_CURRENT_USER\Control Panel\Input Method\Hot Keys\00000070]
> "Key Modifiers"=hex:00,c0,00,00
> "Virtual Key"=hex:ff,00,00,00
> 
> [HKEY_USERS\.DEFAULT\Control Panel\Input Method\Hot Keys\00000010]
> "Key Modifiers"=hex:02,c0,00,00
> "Target IME"=hex:00,00,00,00
> "Virtual Key"=hex:ff,00,00,00
> 
> [HKEY_USERS\.DEFAULT\Control Panel\Input Method\Hot Keys\00000070]
> "Key Modifiers"=hex:02,c0,00,00
> "Target IME"=hex:00,00,00,00
> "Virtual Key"=hex:ff,00,00,00
> ```

你好，我的小狼毫输入法也是全局安装的，使用这个方案时，我发现有可能会出现一个问题：快捷键没有关闭，而是会从 Ctrl+Space 变成单个 Ctrl。
我发现问题在于后半部分的 “Key Modifiers” =hex:02,c0,00,00 可能对应了 Ctrl，改为 hex:00,c0,00,00 可以解决这个问题。
以下是在此基础上修改的方案（也就是 [srackhall](https://github.com/srackhall) 所给方案的组合）：

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Input Method\Hot Keys\00000010]
"Key Modifiers"=hex:00,c0,00,00
"Virtual Key"=hex:ff,00,00,00

[HKEY_CURRENT_USER\Control Panel\Input Method\Hot Keys\00000070]
"Key Modifiers"=hex:00,c0,00,00
"Virtual Key"=hex:ff,00,00,00

[HKEY_USERS\.DEFAULT\Control Panel\Input Method\Hot Keys\00000010]
"Key Modifiers"=hex:00,c0,00,00
"Virtual Key"=hex:ff,00,00,00

[HKEY_USERS\.DEFAULT\Control Panel\Input Method\Hot Keys\00000070]
"Key Modifiers"=hex:00,c0,00,00
"Virtual Key"=hex:ff,00,00,00
```
