### ISSUE TITLE
小狼毫inline嵌入/内嵌模式，第一候选词在各程序体现形式不一，在word微信里阴影闪烁

### ISSUE THREAD

**Issue by jacklondon2022** [rime/weasel#718]
1. 在wps文字里，只输入单字，第一候选字没有下划线。输入词语，下划线虚线，正常。
2. 在word里，第一候选字没用阴影（灰色）体现，但是键入新编码会闪烁，让眼睛疲劳。
3. 在微信里，阴影是黑色。
4. 在QQ里，阴影是蓝色。
5. 在浏览器里，下划线是实线，正常（只输入单字也正常）。

遵请大佬修复该不完美，让在每个程序下，都用下划线强调第一候选词，最好能调整是适用虚线还是实线。（谷歌输入法，启程输入法该功能均正常）。该功能对形码用户高速正确输入很重要，谢谢。
![2](https://user-images.githubusercontent.com/102937511/162552896-14e0ed5d-c5b4-45a2-8ba0-b8303afefae3.jpg)

![1](https://user-images.githubusercontent.com/102937511/162552890-c3558990-67f4-4e65-aa66-9fa27a4ed090.jpg)
![3](https://user-images.githubusercontent.com/102937511/162552907-edda4399-ca90-47cb-a729-d31fb935ea44.jpg)
![4](https://user-images.githubusercontent.com/102937511/162552911-c71e61e1-f947-482c-838a-97a64fe7037c.jpg)
![5](https://user-images.githubusercontent.com/102937511/162552912-883b2ee0-88a6-4538-89c2-28895d18a4b5.png)

**Comment by haoenz** [comment]
我这边在微信里输入时光标后面会跟一个空格，不知道为什么…

**Comment by lotem** [comment]
你误会了。内嵌的字不是输入法画的。输入法只告诉系统要显示的内容。绘制是是系统和应用程序的事。

**Comment by haoenz** [comment]
> 你误会了。内嵌的字不是输入法画的。输入法只告诉系统要显示的内容。绘制是是系统和应用程序的事。

有点好奇为什么其他输入法（虽然我只试了微软输入法）不会出现这个问题…

虽然它在word和微信里的表现也不一致就是了（但至少看起来不像是有bug）

**Comment by wxyzh** [comment]
确实会有这个问题，我在edge浏览器中输入的字体是正常的，但是在记事本和微信中的字体会有变化
