### ISSUE TITLE
build.bat opencc时找不到路径，librime代码git下载不了，直接拷贝和RIME_ROOT都这样

### ISSUE THREAD

**Issue by ryysoft** [rime/weasel#719]
CMake Warning (dev) at CMakeLists.txt:137 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:146 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Use bundled marisa library.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/librime7/thirdparty/src/opencc/build
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

  marisa.vcxproj -> D:\librime7\thirdparty\src\opencc\build\deps\marisa-0.2.6\Release\marisa.lib
  libopencc.vcxproj -> D:\librime7\thirdparty\src\opencc\build\src\Release\opencc.lib
  opencc_dict.vcxproj -> D:\librime7\thirdparty\src\opencc\build\src\tools\Release\opencc_dict.exe
  Copying libopencc to directory of opencc_dict
  opencc.vcxproj -> D:\librime7\thirdparty\src\opencc\build\src\tools\Release\opencc.exe
  opencc_phrase_extract.vcxproj -> D:\librime7\thirdparty\src\opencc\build\src\tools\Release\opencc_phrase_extract.exe
  -- Install configuration: "Release"
  -- Up-to-date: d:/librime7/thirdparty/lib/pkgconfig/opencc.pc
  -- Up-to-date: d:/librime7/thirdparty/lib/opencc.lib
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Common.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Config.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Conversion.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/ConversionChain.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Converter.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Dict.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/DictConverter.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/DictEntry.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/DictGroup.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Exception.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Export.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Lexicon.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/MarisaDict.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/MaxMatchSegmentation.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Optional.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/PhraseExtract.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Segmentation.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/Segments.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/SerializableDict.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/SerializedValues.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/SimpleConverter.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/TextDict.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/UTF8StringSlice.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/UTF8Util.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/opencc.h
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/opencc_config.h
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/BinaryDict.hpp
  -- Up-to-date: d:/librime7/thirdparty/include/opencc/DartsDict.hpp
  -- Up-to-date: d:/librime7/thirdparty/bin/opencc.exe
  -- Up-to-date: d:/librime7/thirdparty/bin/opencc_dict.exe
  -- Up-to-date: d:/librime7/thirdparty/bin/opencc_phrase_extract.exe
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/STCharacters.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/STPhrases.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/TSCharacters.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/TSPhrases.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/TWVariants.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/TWVariantsRevPhrases.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/HKVariants.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/HKVariantsRevPhrases.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/JPVariants.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/JPShinjitaiCharacters.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/JPShinjitaiPhrases.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/TWPhrases.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/TWPhrasesRev.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/TWVariantsRev.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/HKVariantsRev.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/JPVariantsRev.ocd2
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/hk2s.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/hk2t.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/jp2t.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/s2hk.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/s2t.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/s2tw.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/s2twp.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/t2hk.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/t2jp.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/t2s.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/t2tw.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/tw2s.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/tw2sp.json
  -- Up-to-date: d:/librime7/thirdparty/share/opencc/tw2t.json
系统找不到指定的路径。
error building weasel...

**Comment by wei804378140** [comment]
我也遇到了这个问题，请求解决了吗

**Comment by fxliang** [comment]
librime路径怎么修改了？`librime7`
weasel中的build.bat opencc会依赖librime的路径.

参照ci的编译流程执行即可解决
