### ISSUE TITLE
关于Ctrl+Space 清空已有输入的问题

### ISSUE THREAD

**Issue by DouYou-DianShuai** [rime/weasel#720]
> 由于使用过程中,习惯了Ctrl+N/P进行选择.   因此输入过程中容易产生Ctrl按下时按Space来"上屏候选项".   (所以添加了如下配置)
>> ![image](https://user-images.githubusercontent.com/65339064/164459783-5c469226-1ecb-4ced-b742-f98ebbaf67ea.png)

> 随后 win系统下原有会造成输入法关闭的 Ctrl+Space 的功能,   也已经按 #717 中一位大佬回答的方法成功关闭了.

**可是并没有产生效果.     Ctrl+Space 清空已有输入的问题依旧存在**

经过尝试, 目前还没发现进一步的解决方法.

**Comment by lotem** [comment]
相同提問 https://github.com/rime/weasel/issues/717
