### ISSUE TITLE
建议将 rime-install.bat 里的 git.io 短链接替换为原链接

### ISSUE THREAD

**Issue by Lehmaning** [rime/weasel#722]
在 rime-install.bat 初始化的时候，https://git.io/rime-install 这个地址经常连接失败，代理也不行，之后手动将其替换为长连接 https://raw.githubusercontent.com/rime/plum/master/rime-install 后才解决。个人感觉脚本里也没必要使用短链接，所以希望未来的版本能将这个 git.io 的链接替换掉。

**Comment by phlinsia** [comment]
从2022年4月29日起，git.io上的所有链接将停止重定向。在新电脑上安装小狼毫时同样遇到了这个问题。

**Comment by lotem** [comment]
fixed by https://github.com/rime/plum/commit/9588b5af3c1c0256df4f4d3b3eb508274a95dc42

**Comment by ImpleLee** [comment]
该问题尚未解决，因为此项目的plum submodule未更新，0.15.0的`rime-install.bat`中仍从`git.io`下载代码。

**Comment by ImpleLee** [comment]
不知道怎么reopen issue……@lotem看一下？
