### ISSUE TITLE
繁简混合输入

### ISSUE THREAD

**Issue by tomatl45** [rime/weasel#723]
你好，

我想实现这样一种功能：在输入文字的时候，可以不必按 Ctrl + ` 切换繁简，直接同时输入包含繁体和简体的词语或短句。

一个可能的方法：将简体和繁体视为不同的字符，共存于一个输入方案内，分别记忆词频、自造词等。

请问这种功能该通过哪些操作实现？

谢谢。

**Comment by arockshan** [comment]
这个不是rime的任务吧，可以考虑某种支持简繁双打的输入方案，比如徐码，它就是完全按字形编码的，同一个汉字简繁两体编码不同。

**Comment by lotem** [comment]
繁簡漢字本身就是不同的字符。同時在詞典中收錄，不使用字形轉換功能即可。

**Comment by nutnutwin** [comment]
> 繁簡漢字本身就是不同的字符。同時在詞典中收錄，不使用字形轉換功能即可。

lotem 你好谢谢你一直以来的努力

请问你说的｢不使用字形转换｣是说在配置文件里(yaml)修改, 还是说在菜单(F4调出的菜单, 请见附件)里选择呢? 谢谢
![20231207_Thu -103257](https://github.com/rime/weasel/assets/34512273/2ae3c16d-d11b-416e-b0e1-442bfd2ae973)

**Comment by mirtlecn** [comment]
> > 繁簡漢字本身就是不同的字符。同時在詞典中收錄，不使用字形轉換功能即可。
> 
> lotem 你好谢谢你一直以来的努力
> 
> 请问你说的｢不使用字形转换｣是说在配置文件里(yaml)修改, 还是说在菜单(F4调出的菜单, 请见附件)里选择呢? 谢谢
> ![20231207_Thu -103257](https://github.com/rime/weasel/assets/34512273/2ae3c16d-d11b-416e-b0e1-442bfd2ae973)
> 
> 

就是说把这样的短语直接写进词典

```yaml
# demo.dict.yaml

張三法律事务所 zhang san fa lv shi wu suo
```

**Comment by fxliang** [comment]
> > 繁簡漢字本身就是不同的字符。同時在詞典中收錄，不使用字形轉換功能即可。
> 
> lotem 你好谢谢你一直以来的努力
> 
> 请问你说的｢不使用字形转换｣是说在配置文件里(yaml)修改, 还是说在菜单(F4调出的菜单, 请见附件)里选择呢? 谢谢 ![20231207_Thu -103257](https://private-user-images.githubusercontent.com/34512273/288594989-2ae3c16d-d11b-416e-b0e1-442bfd2ae973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNjE5MjAsIm5iZiI6MTcxMTE2MTYyMCwicGF0aCI6Ii8zNDUxMjI3My8yODg1OTQ5ODktMmFlM2MxNmQtZDExYi00MTZlLWIwZTEtNDQyYmZkMmFlOTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDAyNDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NmJlMDk0MDlmNjk4OTA5ODEzY2FlMWI0MmMyZjU5ZWFmZmNiZTdmYjQxNjkyOTEwNGU2MWRjYmZiZTY2NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-emQmg43CUvM7iInn68XzPGEk0iWQ5ZFeNna39Ugd48)

删除 （或者注释）engine/filters下的simplifier，重新部署
