### ISSUE TITLE
项目编译过程中出现“无法解析的外部符号”

### ISSUE THREAD

**Issue by Mechorca** [rime/weasel#727]
你好，我是一个编程新手，正在学习如何编译这个项目，但是我在编译的过程中遇到了很多问题，在最后msbuild执行的过程中出现了很多“无法解析外部符号”的错误。请问我该如何解决。以及可否更新编译的教程？感谢

**Comment by Mechorca** [comment]
![96{IE`$SG{AQ@P 3 MNE~B8](https://user-images.githubusercontent.com/87187802/168971650-b5f33889-9747-4636-970f-8ba44fc794dc.png)

**Comment by lotem** [comment]
不知是怎麼做到的。是不是刪了什麼文件。

教程： https://github.com/rime/weasel/blob/master/INSTALL.md

**Comment by pmxiao** [comment]
出现了同样的问题，按这里记录的[编译过程](https://www.xrat.net/dev/2023/05/07/build-rime-weasel-with-vs2019.html)，编译通过了，看来只能分开编译。

**Comment by fxliang** [comment]
编译过程中这类问题通常是两种，1是lib文件缺失，2是文件位数不当，检查下具体问题。或者参照ci 中的流程执行即可。如还有问题可以再打开此issue.
