### ISSUE TITLE
想顯示重複的候選字

### ISSUE THREAD

**Issue by philipposkhos** [rime/weasel#728]
各位好

我想設置一套和繁體排位一致的簡體輸入，但簡體會將不同的繁體字合成一字，導致字典的候選字會有重複，而這些重複字又會給過濾，導致排位不同。所以想說是否有辦法可以把重複的候選字照樣顯示出來?

(我在網上可以找到的資料說 filter 中有個 uniquifier 是會過濾掉重複的候選字，但我測試移除後，好像也沒有用。)

麻煩各位了

**Comment by lotem** [comment]
这个想法我有同感可能对使用繁体为主又经常需要切换简繁的用家会有帮助。
先不谈实现上的问题。讨论一下这种设计是否具有可用性？

简体字用家应该不会这样思考，即把一个字不同的繁体义项看作两个字条。对用家来说，就只有一个字而已。
我曾问自己：
看到如下候选界面：`1. 运 2. 云 3. 晕`
我能否不假思索地意识到，向后翻页还会有一项 `?. 云[雲] `，而首页这一项只是传承字”云“呢？
似乎对于熟悉简化字读写的人，这样的设计并不符合直觉，甚至影响思考和输出的效率。

**Comment by philipposkhos** [comment]
是的，如果是熟悉簡化字，並且是按詞頻選字的用家是不需要這個功能的。

會出現這個需求的是用像傳統速成這種固定候選字，但又需要輸出為簡體的人。因為對於我們來說候選字的位置其實已經是那個字碼的一部份，例如「天干地支 」的「干」，取碼是 `一十1`，而「幹事」的「幹」，取碼是 `十十7`，這些候選字的位置已經默記於心，需要打哪個字時就會直接打出對應的候選字號。

而在做固定候選字傳統速成那個方案時，我就遇到一個情況，如果是使用內置的繁簡切換，對應的字典會把一對多的簡化字都顯示出來，導致到要輸出簡化字時，那個位置會有不同。
例如「動作」的「動」，取碼是 `竹尸7` 
在繁體情況下:
輸入 `竹尸` 時，出現的候選字是 ，`1.戶 2.乍 3.彷 4.秀 5.房 6.舫 7.動 8.笮 9.甥`
但在繁轉簡的情況下，因為字體的對照，「彷」字就會出現了 「仿、彷」這兩個字，如下:
輸入 `竹尸` 時，出現的候選字是 ，`1.户 2.乍 3.彷 4.仿 5.秀 6.房 7.舫 8.动 9.笮`
這種情況下再按取款 `竹尸7` 輸入，出來的字就會是 「舫」，而不是「动」。關於這個問題，我在幾年前做這個方案時就已經請教過大家，那時候我用了這個方案幾年了，這個問題一直困擾著，往往碰上了，就要刪掉重打。但關於這個問題，我在幾年前做這個方案時就已經請教過各位，是否可以繁轉簡時，還保持著一字對一字的關係，那時候有回覆說這個是涉及到 opencc 的字典，很難實現。所以也沒辦法，只能自己去適應。

但儘管我已經用這個方案打字好幾年了，每逢要輸出為簡體時，這個候選字位置不同的問題依然困擾著我，最近我突然想，是不是不用這個繁轉簡的功能，就直接在碼表上做處理，直接弄一個傳統速度(簡體)的輸入法，碼表放的就是簡化字，不打開繁轉簡功能，這樣要輸出簡體時，就直接切換輸入法。但是卻碰到了因為碼表轉換成簡體字，在同一個編碼中，會出現相同的字，程式判斷是重複候選字而過濾掉，最終還是候選字位置會不同。

因此我才想向各位查詢一下，是否有可能把可以把重複的候選字顯示出來，來保持簡體輸出時，候選字的位置一樣

**Comment by lotem** [comment]
上一條回覆講的是「一繁對多簡」的問題，這與原題所述「一簡對多繁」屬不同問題。

倉頡方案詞典通常以繁體爲主，方案中啓用繁轉簡。要避免以上提到的「彷→彷、仿」的「一繁對多簡」轉換，須修改OpenCC字典 `TSCharacters.txt` 中繁、簡字的對應關係，使之一一對應。如此修改的弊端是會缺少對「一繁對多簡」的轉換，例如輸入「十十人弓=乾」無法輸出簡化字「干」、或者無法輸出「乾」本字，兩者只能取其一。

此文件中類似「彷→彷、仿」的對應關係正是因爲簡化字文本中「彷」「仿」 兩種字形皆有用，如果只留其一若「仿」，另一字「彷」將無法輸入。

`uniquifier` 消除候選字中文字相同的重複項。例如用拼音輸入「gan」得到「干、幹、乾」，經過簡化得到「干、干、干」，即爲重複項。而後述一例中簡化所得「彷、仿」是不同的漢字，候選字中並無重複項。

**Comment by philipposkhos** [comment]
不好意思，是我沒有表達清楚。我上面舉的例子是關於「一繁對多簡」的轉換問題，但就如您說明的，會導致打不了「乾」字。而且改了 OpenCC 字典也會影響整個輸入法。因為我想在碼表上做處理。如以下引用所說的。

> 但儘管我已經用這個方案打字好幾年了，每逢要輸出為簡體時，這個候選字位置不同的問題依然困擾著我，最近我突然想，是不是不用這個繁轉簡的功能，就直接在碼表上做處理，直接弄一個傳統速度(簡體)的輸入法，碼表放的就是簡化字，不打開繁轉簡功能，這樣要輸出簡體時，就直接切換輸入法。但是卻碰到了因為碼表轉換成簡體字，在同一個編碼中，會出現相同的字，程式判斷是重複候選字而過濾掉，最終還是候選字位置會不同。

補充例子: 
例如 `人木` 的繁體候選字是 
第一頁 : `1.仔 2.他 3.休 4.余 5.侏 6.保 7.俘 8.氣 9.條`  
第二頁 : `1.傑 2.集 3.餘 4.柋 5.栠`
當中，餘額的餘，排位就是空格換頁後的第3位，在固定字碼輸入是 `人木 3`。

但是在碼表轉成簡體後，就會出現
第一頁 : `1.仔 2.他 3.休 4.余 5.侏 6.保 7.俘 8.气 9.条`  
第二頁 : `1.傑 2.集 3.柋 4.栠`
本來出現在第二頁的 餘(余) ，因為在碼表簡化後，就按忽略重複這條規則忽略掉了。導致到輸入`人木 3`會出了 「柋`」，也導致到在那個重複字之後的候選字編碼字號都不同了。

所以想說是否可以做到 不忽略重複候選字 這個效果?

**Comment by lotem** [comment]
理解了。可以。

Rime词典并非以YAML源文件的一行对应一个候选项。而是以「文字+编码」的内容界定一个词条。该格式允许同一词条在码表中重复出现，例如：在一个词典文件里引用其他码表，不会造成同一词语重复定义，然各个码表中定义的词频会累加。因为很难保证引用的另一份码表中没有重复的字词。特别是Rime有「预设词汇表」的设计，众多输入方案的词典都会引用预设词汇表利用其中的词组和词频信息，只需在码表中定义字词的编码。同一字词势必在输入方案的词典和预设词汇表中同时出现。

要让同一文字、同一编码作为多个候选项并列，不能用上述Rime提供的词典编译程序，只能另写程序直接生成二进制格式的Rime词典。

或许更可行的办法是在码表中把不同的繁体字转换为不同的简化字，如「余→余」「餘→馀」。
甚至爲了統一處理，可以通过标记的办法在码表层面区分：「余〔余〕」「余〔餘〕」，然後再用一個特製的OpenCC字典輸出無標記的簡化字：

    余〔余〕→余
    余〔餘〕→余
