### ISSUE TITLE
有没有限制码长的参数？编码长度过长会导致严重卡顿

### ISSUE THREAD

**Issue by FanXiangTM** [rime/weasel#733]
使用朙月拼音的时候，如果连续录入几十个字符，就会变得特别卡顿，小狼毫算法服务占用CPU飙升。特别是配置了扩展词库的情况下，这个问题更为严重。输入的字符越多，就越卡顿。
我观察了其他输入法，它们大部分都有限制码长，一次输入的字符数量达到限制的时候就不再接受输入，这就完全避免了卡顿现象。

有一些情况，比如我输入过快的时候，连续输入几十个字符而没有上屏就可能直接导致电脑卡死；再比如不小心压住了键盘上的某个按键，只需要两秒钟就录入几十个字符，同样会导致严重的卡顿，如果是低配电脑可能直接就卡死了

为什么不能添加一个参数来限制编码 长度？

**Comment by lotem** [comment]
沒有的。

**Comment by LawssssCat** [comment]
你可以试试这段代码
``````lua
--[[
  限制用户输入长度（避免编码过长导致卡顿、闪退、死机）

  *.schema.yaml
  ```yaml
    processors:
      - "lua_processor@code_length_limit_processor@code"
    code:
      length_limit: 50 # 限制输入长度
  ```

  rime.lua
  ```lua
    code_length_limit_processor = require("code")
  ```
--]]

local M = {}

local kRejected = 0 -- 输入法拒绝处理
local kAccepted = 1 -- 输入法接受处理，并由本processor处理
local kNoop = 2 -- 交由输入法下一个processor判断是否处理

function M.func(key, env)
  local ctx = env.engine.context
  local config = env.engine.schema.config

  -- 限制
  local length_limit = config:get_string(env.name_space .."/length_limit")
  if(length_limit~=nil) then
    if(string.len(ctx.input) > tonumber(length_limit)) then
      -- ctx:clear()
      ctx:pop_input(1)
      return kAccepted
    end
  end

  -- 放行
  return kNoop
end

return M
``````

**Comment by FanXiangTM** [comment]
> 你可以试试这段代码
> 
> ```lua
> --[[
>   限制用户输入长度（避免编码过长导致卡顿、闪退、死机）
> 
>   *.schema.yaml
>   ```yaml
>     processors:
>       - "lua_processor@code_length_limit_processor@code"
>     code:
>       length_limit: 50 # 限制输入长度
>   ```
> 
>   rime.lua
>   ```lua
>     code_length_limit_processor = require("code")
>   ```
> --]]
> 
> local M = {}
> 
> local kRejected = 0 -- 输入法拒绝处理
> local kAccepted = 1 -- 输入法接受处理，并由本processor处理
> local kNoop = 2 -- 交由输入法下一个processor判断是否处理
> 
> function M.func(key, env)
>   local ctx = env.engine.context
>   local config = env.engine.schema.config
> 
>   -- 限制
>   local length_limit = config:get_string(env.name_space .."/length_limit")
>   if(length_limit~=nil) then
>     if(string.len(ctx.input) > tonumber(length_limit)) then
>       -- ctx:clear()
>       ctx:pop_input(1)
>       return kAccepted
>     end
>   end
> 
>   -- 放行
>   return kNoop
> end
> 
> return M
> ```

不会用，能不能把注释写清除一点

**Comment by LawssssCat** [comment]
怎么用，你可以参考这个修改记录：
https://github.com/LawssssCat/rime-aurora/commit/998cd8a3ee3b729e8beee27bc17cb53fd8a853a4

**Comment by FanXiangTM** [comment]
> 

反复尝试，结果还是不生效

**Comment by LawssssCat** [comment]
![preview_debug_prefix](https://user-images.githubusercontent.com/18041500/192744233-a5e0b343-4f15-4da4-bcb2-d04d4278f810.gif)

你是想要这样的效果吗？

**Comment by FanXiangTM** [comment]
> ![preview_debug_prefix](https://user-images.githubusercontent.com/18041500/192744233-a5e0b343-4f15-4da4-bcb2-d04d4278f810.gif) [ ![preview_debug_prefix](https://user-images.githubusercontent.com/18041500/192744233-a5e0b343-4f15-4da4-bcb2-d04d4278f810.gif) ](https://user-images.githubusercontent.com/18041500/192744233-a5e0b343-4f15-4da4-bcb2-d04d4278f810.gif) [ ](https://user-images.githubusercontent.com/18041500/192744233-a5e0b343-4f15-4da4-bcb2-d04d4278f810.gif)
> 
> 你是想要这样的效果吗？

对，是这样的效果。但是脚本的使用方法我搞不清楚，所以反复尝试总是不生效

**Comment by LawssssCat** [comment]
哪不清楚呢？
配置看不懂？<https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%83lua>
配置语法看不懂？<https://github.com/rime/home/wiki/Configuration>
脚本代码看不懂？<https://github.com/hchunhui/librime-lua/wiki/Scripting>
工作流程不清楚？<https://github.com/rime/home/wiki/RimeWithSchemata#%E8%BC%B8%E5%85%A5%E6%B3%95%E5%BC%95%E6%93%8E%E8%88%87%E5%8A%9F%E8%83%BD%E7%B5%84%E4%BB%B6>

**Comment by FanXiangTM** [comment]
> 哪不清楚呢？ 配置看不懂？https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%83lua 配置语法看不懂？https://github.com/rime/home/wiki/Configuration 脚本代码看不懂？https://github.com/hchunhui/librime-lua/wiki/Scripting 工作流程不清楚？https://github.com/rime/home/wiki/RimeWithSchemata#%E8%BC%B8%E5%85%A5%E6%B3%95%E5%BC%95%E6%93%8E%E8%88%87%E5%8A%9F%E8%83%BD%E7%B5%84%E4%BB%B6

谢谢
