### ISSUE TITLE
Rime输入法配置symbols时，如何在选项右侧设置批注

### ISSUE THREAD

**Issue by 10cks** [rime/weasel#735]
![image](https://user-images.githubusercontent.com/47177550/173019773-bb5a7466-1546-449f-ac36-eaec33bdf4f6.png)
类似这样的，平时敲代码记不住命令，要是能添加这样的代码注释就好了

**Comment by lotem** [comment]
`punctuator` 暂无这项功能。

可以通过反查翻译器实现。主词典用来根据输入码 `/dash` 检索符号，反查词典用来通过符号反查出提示码`[EN DASH]`

**Comment by oniondelta** [comment]
利用`opencc`

![image](https://i.imgur.com/iRi7h5Y.png)

**Comment by LawssssCat** [comment]
> 利用`opencc`
> 
> ![image](https://camo.githubusercontent.com/63671430f366d010d20b1bf960cd36201fb4d32c699ca197b2b5692f1afe2bf8/68747470733a2f2f692e696d6775722e636f6d2f695269376835592e706e67)

能分享个现成的码表吗？

**Comment by oniondelta** [comment]
> 能分享个现成的码表吗？
https://github.com/oniondelta/Onion_Rime_Files/blob/master/allfiles/opencc/punct_mark.txt

**Comment by LawssssCat** [comment]
> > 能分享个现成的码表吗？
> 
> https://github.com/oniondelta/Onion_Rime_Files/blob/master/allfiles/opencc/punct_mark.txt

谢谢
