### ISSUE TITLE
我使用rime-wubi-master五笔86配置输入法时，发现只要是CJK-A以上的都无法输入。这是哪里设置？

### ISSUE THREAD

**Issue by cndpi** [rime/weasel#736]

**Comment by lotem** [comment]
有個開關。[方案選單](https://github.com/rime/home/wiki/UserGuide#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE) > 常用 → 增廣，選「增廣」。
