### ISSUE TITLE
请问一下小狼毫的 key_binder 快捷键设置功能 能不能设置一些 标准键盘不存在的键？

### ISSUE THREAD

**Issue by BH2WFR** [rime/weasel#738]
按理来说，键盘的按键事件最多支持255（或比这个多）的键数，但是我看小狼毫的文档里面按键脚本好像只支持那些标准键盘存在的键，我目前想用powertoys把一些键映射到这些非标准按键上（如日文键盘多出的那几个键），再用小狼毫当快捷键映射到功能上，能不能这样做？

**Comment by lotem** [comment]
https://github.com/rime/weasel/blob/8462b83b355c444e59d37bbff04d14260b825333/WeaselTSF/KeyEvent.cpp#L63
此處Windows按鍵代碼轉換成ibus按鍵代碼的，都可以在Rime引擎裏處理。
