### ISSUE TITLE
在《堡垒之夜》（Fortnite）里无法使用小狼毫

### ISSUE THREAD

**Issue by ruleroller** [rime/weasel#740]
错误提示如下，已尝试重新安装过weasel-0.14.3.0，还是会在进入游戏的时候报如下图的错误。

游戏是能玩的，只是无法在游戏里用小狼毫输入中文。

![image](https://user-images.githubusercontent.com/3047708/178929201-4f3491a8-cdb8-48f8-b204-2423eedb505d.png)

**Comment by lotem** [comment]
應該不是輸入法的問題。遊戲可能禁止了不認識的DLL程序在遊戲裏運行。
