### ISSUE TITLE
请问怎么把小狼毫设为新世纪五笔呢？

### ISSUE THREAD

**Issue by Immortal-Sty** [rime/weasel#744]
请问怎么把小狼毫设为新世纪五笔呢？我只在里面看到了86版。

**Comment by lotem** [comment]
和五筆86一樣，需要製作輸入方案和詞典（碼表）。有輸入方案，就可以在輸入法設置裏啓用。

**Comment by Immortal-Sty** [comment]
> 和五筆86一樣，需要製作輸入方案和詞典（碼表）。有輸入方案，就可以在輸入法設置裏啓用。

***

那有没有像新世纪五笔一样的现成的输入方案呢？如果没有，该怎么制作呢？

**Comment by lotem** [comment]
有碼表的話，可以參考其他類似的方案編寫輸入方案。
製作方法詳見[輸入方案設計書](https://github.com/rime/home/wiki/RimeWithSchemata)。

流行的輸入法應該有人做過的。可以在GitHub上面搜索。

**Comment by Immortal-Sty** [comment]
> 有碼表的話，可以參考其他類似的方案編寫輸入方案。 製作方法詳見[輸入方案設計書](https://github.com/rime/home/wiki/RimeWithSchemata)。
> 
> 流行的輸入法應該有人做過的。可以在GitHub上面搜索。

***

谢谢
