### ISSUE TITLE
小狼毫不能像鼠鬚管一样有圆角界面吗？

### ISSUE THREAD

**Issue by Immortal-Sty** [rime/weasel#745]
小狼毫不能像鼠鬚管一样有圆角界面吗？

希望小狼毫也能支持圆角呢，毕竟 Windows 11 已经是圆角界面了，小狼毫还是直角的话有点点违和。

**Comment by guixin233** [comment]
https://github.com/fxliang/weasel/releases

**Comment by fxliang** [comment]
最新构建已有圆角

[https://github.com/rime/weasel/actions](https://github.com/rime/weasel/actions)
