### ISSUE TITLE
小狼毫win11在终端或者git-bash中不支持默认英文输入

### ISSUE THREAD

**Issue by cdc94** [rime/weasel#746]
weasel.custom.yaml
 ……
patch:
  app_options:
    bash.exe: {ascii_mode: true}  # 不生效
    cmd.exe: {ascii_mode: true}  #不生效
    git-bash.exe: {ascii_mode: true}  #不生效
    matlab.exe: {ascii_mode: true}  # 生效
    notepad++.exe: {ascii_mode: true}  # 生效
    pycharm64.exe: {ascii_mode: true} # 不生效
……
对于一些应用是生效的，但是对于一些应用则不生效，特别是对于cmd、git-bash这种应用，默认英文输入是很重要的

**Comment by PanWang3** [comment]
是不是没找到真正的exe窗口？要不你试试我的？我的生效。

app_options:
  cmd.exe:
    ascii_mode: true
  conhost.exe:
    ascii_mode: true
  dbeaver.exe:
    ascii_mode: true
  Ssms.exe:
    ascii_mode: true
  mintty.exe:
    ascii_mode: true
  devenv.exe:
    ascii_mode: true
  dbeaver.exe:
    ascii_mode: true
  Ssms.exe:
    ascii_mode: true
  pycharm64.exe:
    ascii_mode: true
  cmd.exe:
    ascii_mode: true
  powershell.exe:
    ascii_mode: true
  WindowsTerminal.exe:
    ascii_mode: true
  OpenConsole.exe:
    ascii_mode: true
  conhost.exe:
    ascii_mode: true

**Comment by cdc94** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    使用WindowsTerminal.exe生效了，确实是程序名称的问题，但是要全部小写才行。不知道如何才能找到正确的程序名，git工具的git-bash.exe就一直无法生效
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1094392181
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年10月6日 16:57
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [rime/weasel] 小狼毫win11在终端或者git-bash中不支持默认英文输入 (Issue #746)
        
      
    
  
  

是不是没找到真正的exe窗口？要不你试试我的？我的生效。

app_options:

cmd.exe:

ascii_mode: true

conhost.exe:

ascii_mode: true

dbeaver.exe:

ascii_mode: true

Ssms.exe:

ascii_mode: true

mintty.exe:

ascii_mode: true

devenv.exe:

ascii_mode: true

dbeaver.exe:

ascii_mode: true

Ssms.exe:

ascii_mode: true

pycharm64.exe:

ascii_mode: true

cmd.exe:

ascii_mode: true

powershell.exe:

ascii_mode: true

WindowsTerminal.exe:

ascii_mode: true

OpenConsole.exe:

ascii_mode: true

conhost.exe:

ascii_mode: true



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by PanWang3** [comment]
git-bash 应该是这个mintty.exe

**Comment by cdc94** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    果然可以了！！！
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1094392181
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年10月6日 20:22
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [rime/weasel] 小狼毫win11在终端或者git-bash中不支持默认英文输入 (Issue #746)
        
      
    
  
  


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by zhuzhzh** [comment]
我在weasel.custom.yaml中：

patch:
  "app_options/WindowsTerminal.exe":
    ascii_mode: true
  "app_options/Runtime Broker.exe":
    ascii_mode: true
  "app_options/powershell.exe":
    ascii_mode: true
  "app_options/Code.exe":
    ascii_mode: true
  "app_options/OpenConsole.exe":
    ascii_mode: true
  "app_options/uTools.exe":
    ascii_mode: true
  "app_options/speedcrunch.exe":
    ascii_mode: true
  "app_options/gvim.exe":
    ascii_mode: true

这样在wt和utools.exe里都不生效

**Comment by choyy** [comment]
> 是不是没找到真正的exe窗口？要不你试试我的？我的生效。
> 
> app_options: cmd.exe: ascii_mode: true conhost.exe: ascii_mode: true dbeaver.exe: ascii_mode: true Ssms.exe: ascii_mode: true mintty.exe: ascii_mode: true devenv.exe: ascii_mode: true dbeaver.exe: ascii_mode: true Ssms.exe: ascii_mode: true pycharm64.exe: ascii_mode: true cmd.exe: ascii_mode: true powershell.exe: ascii_mode: true WindowsTerminal.exe: ascii_mode: true OpenConsole.exe: ascii_mode: true conhost.exe: ascii_mode: true

请问devenv.exe是visual studio的吧，你在项目代码界面自动切换输入法生效吗，我只在选择项目界面生效进入项目代码界面就无效了
