### ISSUE TITLE
希望可以快捷键直接切换方案

### ISSUE THREAD

**Issue by Immortal-Sty** [rime/weasel#748]
现在的方案切换需要按两下键盘，即：`F4`、`数字`，感觉有点麻烦。

希望可以像系统切换输入法一样，一个固定的快捷键按顺序依次循环切换方案。

或者让我们能给每个方案设置自己的快捷键也行，一键切换到想要的输入法。

**Comment by Ace-Who** [comment]
配置 `key_binder` 即可，动作为 `select: <schema_id>`。
