### ISSUE TITLE
反切改唔到顯示出嚟嘅字符

### ISSUE THREAD

**Issue by JacoChong** [rime/weasel#749]
我想將反切輸入法打字嘅時候顯示出嚟嘅中文上下字改成粵拼嗰啲英文。
較早前嘗試改過顯示出嚟嘅字符，但係凈係改到大部分聲母。

而家打字係正常地出到字嘅，但顯示個部分：
- 聲母大部分改咗（只係撳v佢照顯示v而唔係ng）；
- 撳韻母嘅時候就彈一堆混合咗唔同字符嘅嘢。

唔太清楚yaml嘅語法，想請開發人員幫忙。

## 例子1：
![image](https://user-images.githubusercontent.com/85819362/182176446-21bce307-1e10-4aa5-878f-b9571adfbbbd.png)
聲母「f」顯示為「f」✅
韻母「aan」顯示為「----m」👎🏻 

聲母「c」顯示為「c」✅
韻母「it」顯示為「5t」👎🏻

## 例子2：
![image](https://user-images.githubusercontent.com/85819362/182176777-57f94786-53a8-4bd5-a36d-71f1c11c2384.png)
聲母「s」顯示為「s」✅
韻母「yu」顯示為「34」👎🏻

聲母「j」顯示為「j」✅
韻母「ap」顯示為「-p」👎🏻

聲母「f」顯示為「f」✅
韻母「aat」顯示為「---6-m」👎🏻

唔該晒！！ 🙏🏻🙏🏻

**Comment by fxliang** [comment]
信息量太少，无方案文件，表述太粤语方式大部分人看不懂的。如有需要需补充方案文件和调整下表述方式再开，或者在home/discuss 区开issue
