### ISSUE TITLE
关于制作小狼毫便携版的可行性

### ISSUE THREAD

**Issue by Prcuvu** [rime/weasel#75]
QQ群报告的需求。
将小狼毫的二进制文件做一个压缩包，把用户文件夹设置在程序文件夹下。这样把所有文件解压到U盘，在另一台电脑上插上U盘后，执行安装脚本，注册输入法，读写用户文件夹，就可以物理同步用户设置。是一种有别于联网同步的做法。
有没有必要做一个这样的版本？

**Comment by lotem** [comment]
需要處理的是：拔掉 U 盤以後，如何優雅地不吭聲。最好還能指導用戶卸載。
*.ime 是要放到系統 system32 目錄去的，還有註冊表裏的信息以及添加到系統輸入法列表裏的項目，這些都會留存。

**Comment by Prcuvu** [comment]
便携的输入法依赖于特殊的设计。例如，[小小输入法] (http://yong.dgod.net/)彻底脱离了IME/TSF的设计，通过一个后台程序捕捉键盘事件，绘制输入窗口，并输出到文本框。这种设计完全不需要注册表，而且拔下U盘后也很干净，不会有残留。

**Comment by lotem** [comment]
外掛式輸入法完全繞開系統輸入法 API，這樣做會有更多安全和兼容性問題。比如外掛輸入法通過鍵盤掛鉤可以截獲輸入到密碼框的字符。因此所謂「安全軟件」對掛鍵盤鉤子的程序會重點攔截。

**Comment by ieew** [comment]
@lotem 我有一个建议，可以设计一个自我卸载程序，在启动输入法之后自动把个这自我卸载程序放到某个目录中，并且启动这个程序，当这个程序发现电脑里没有小狼亳之后就自动开始清理痕迹和自我删除，这样是否可行
