### ISSUE TITLE
输入法兼容性修复建议（可能需要？）

### ISSUE THREAD

**Issue by ztjal** [rime/weasel#752]
起因：
https://github.com/LiMinggang/madedit-mod/issues/325#issue-1277003519

和weasel有关系：
https://github.com/LiMinggang/madedit-mod/issues/325#issuecomment-1202703244

解决方法：
https://github.com/LiMinggang/madedit-mod/issues/325#issuecomment-1211724320

**Comment by zhylmzr** [comment]
看了一下博客中是获取 `ITfThreadMgrEx` 组件时传入的是一层指针，改成了2层指针就解决了。
weasel 中没有用到 `ITfThreadMgrEx` 组件，应该没有这个问题
