### ISSUE TITLE
请问：weasel_0.14.3_dev_0.88的序号、注释的颜色怎么改？

### ISSUE THREAD

**Issue by wwzrh** [rime/weasel#753]
**https://github.com/fxliang/weasel/releases
fxliang／weasel_0.14.3_dev_0.88的版本在界面改变了很多，但在rime／weasel还没有整合，在这里向@fxliang 提个问题：
目前对候选序号、注释的字体、字号都能改了，
  label_font_face: Microsoft YaHei   # 指定候选序号文字的字体
  comment_font_face: Microsoft YaHei # 指定候选注释文字的字体
  label_font_point: 14               # 指定候选序号文字的字号
  comment_font_point: 14             # 指定候选注释文字的字号
但请教候选序号、注释的颜色怎么改？
@fxliang** 

![无标题](https://user-images.githubusercontent.com/12047479/185028988-1dc5858c-e7cc-4cdb-8401-d071becce6eb.png)

**Comment by fxliang** [comment]
> **https://github.com/fxliang/weasel/releases fxliang／weasel_0.14.3_dev_0.88的版本在界面改变了很多，但在rime／weasel还没有整合，在这里向@fxliang 提个问题： 目前对候选序号、注释的字体、字号都能改了， label_font_face: Microsoft YaHei # 指定候选序号文字的字体 comment_font_face: Microsoft YaHei # 指定候选注释文字的字体 label_font_point: 14 # 指定候选序号文字的字号 comment_font_point: 14 # 指定候选注释文字的字号 但请教候选序号、注释的颜色怎么改？ @fxliang**
> 
> ![无标题](https://user-images.githubusercontent.com/12047479/185028988-1dc5858c-e7cc-4cdb-8401-d071becce6eb.png)

和原版兼容一致，颜色主题下以下项
label_color
hilited_label_color
comment_text_color
hilited_comment_text_color
