### ISSUE TITLE
两个光标的问题

### ISSUE THREAD

**Issue by ls148478** [rime/weasel#758]
我在使用过程中发现如果没有使用空格来确认候选，会出现两个光标
![image](https://user-images.githubusercontent.com/38435967/187570658-c64fa926-0bb6-4b2a-bb27-446145f8aeea.png)
我想确认这是配置文件的原因还是输入法自身的原因 刚入门 想先确认问题方向 之后再深入修复

**Comment by lotem** [comment]
怎樣操作的？

**Comment by ls148478** [comment]
> 怎樣操作的？

正常在微信聊天窗口中使用

**Comment by lotem** [comment]
這個區域是應用程序的文本框繪製的。輸入法告訴他正在編輯的文字區間和光標位置。
