### ISSUE TITLE
用lua自定义输入translator,如果含有\r或\n,会导致异常

### ISSUE THREAD

**Issue by songrubo** [rime/weasel#760]
以下是可以正常输出
yield(Candidate("date", seg.start, seg._end, "while(true){\t}", ""))

yield(Candidate("date", seg.start, seg._end, "while(true){\r}", ""))
yield(Candidate("date", seg.start, seg._end, "while(true){\n}", ""))
这种不支持,会导致编辑器推]退出.
怎么样才能打出换行的字符呢?

**Comment by mirtlecn** [comment]
现在支持了吧，之前的版本不能换行

**Comment by fxliang** [comment]
fixed by #1169
