### ISSUE TITLE
weasel-0.14.3_dev_0.91：在Windows11系统应用中无法使用中文

### ISSUE THREAD

**Issue by ls148478** [rime/weasel#763]
如标题所说 在微软应用商店或按下Win键搜索时 都只能输入英文 无法输入中文
Windows11_version： 25197.1000
好像是在把小狼毫设置为默认输入法后实现
设置默认输入法：设置->时间与语言->输入->高级键盘设置->替代默认输入法

**Comment by fxliang** [comment]
已知问题，没有记错在8462b83提交就已经存在的，原因不明，修复方法未知

> 如标题所说 在微软应用商店或按下Win键搜索时 都只能输入英文 无法输入中文 Windows11_version： 25197.1000 好像是在把小狼毫设置为默认输入法后实现 设置默认输入法：设置->时间与语言->输入->高级键盘设置->替代默认输入法

**Comment by fxliang** [comment]
check [this](https://github.com/fxliang/weasel/releases/tag/0.14.3_dev_0.94)
