### ISSUE TITLE
“躝”字的繁转简问题

### ISSUE THREAD

**Issue by Serious54088** [rime/weasel#766]
起初是想查一下“躝”字，输入汉字搜索，在结果中看到这句话：

> (康熙字典未收录“𨅬”字头，请参考“躝”字。)

我意识到RIME输入法打出来的 lan 字并不是我想要的那个字形。

查了一下两个字的 Code Point ： 𨅬（U+2816C）躝（U+8E9D）

RIME输出的是第一个，而我想要的是第二个。

于是我去修改码表，结果无论怎么修改编码、甚至把 U+2816C 删掉，输出依然是 U+2816C 。

琢磨一下，我怀疑是繁简转换的问题，于是用 OpenCC 测试了一下，结果证实了我的猜测——  
繁转简，OpenCC 会把 U+8E9D 转换为 U+2816C 。

为什么会把 U+8E9D 转换为 U+2816C ？这是 bug  还是有什么说法？

**Comment by ywxt** [comment]
不是Bug，這是「門」部件的類推簡化。只是《通用規範漢字表》中沒有收「𨅬」這個字，但其他的字典可能做了類推簡化，Unicode收了，OpenCC自然也收就了。

你應該修改OpenCC的轉換表，而不是碼表。

**Comment by Serious54088** [comment]
This is an automatic reply, confirming that your email was received. I will reply as soon as possible. Thank you!
