### ISSUE TITLE
请问目前支持Windows 11吗？

### ISSUE THREAD

**Issue by funnybones2015** [rime/weasel#768]
如题，想装一个，不知道支持win 11系统吗

**Comment by ls148478** [comment]
支持 一样使用 win10 和 win11 感觉区别不大 应该是核心还没开始改

**Comment by 107295472** [comment]
新版本哪里下，现在都是0.14.3吗

**Comment by ls148478** [comment]
> 新版本哪里下，现在都是0.14.3吗

可以去

**Comment by ls148478** [comment]
> 新版本哪里下，现在都是0.14.3吗

https://github.com/fxliang/weasel

**Comment by 107295472** [comment]
这是开发版，稳定吗?

**Comment by 107295472** [comment]
有纯净版吗，就是装完后里面没有其他码的

**Comment by e71828** [comment]
皮肤少，边框不够圆润。
