### ISSUE TITLE
最新版存在问题

### ISSUE THREAD

**Issue by blueflagbj** [rime/weasel#77]
1、在xp下任何方案都失效
2、在win7 下，能够在原版小狼毫上使用的方案，不能使用 了，主要就是大写的状态下，直接就是英文了，没有办法进行定制了~

**Comment by biaoyinzi** [comment]
我在win7看到的情况也一样。我是第一次编译，然后直接运行output里面的weaselsetupx64。语言栏有图标，但是输入不了中文，选字框也出不来，直接打出英文。不知道是不是我的问题？

**Comment by biaoyinzi** [comment]
原來是我的問題。原來需要到librime目錄下，執行build編譯出這個lib纔可以。

**Comment by Prcuvu** [comment]
已确认在Windows XP下存在彻底失灵的问题。

**Comment by biaoyinzi** [comment]
请问下哪个branch有这个问题？我在做一个fork的release, 需要一个稳定版本。

**Comment by blueflagbj** [comment]
能否给予解决这个问题啊？

**Comment by Prcuvu** [comment]
这个问题很可能不予以解决，因为Windows XP早在2014年4月14日官方停止支持。
我放弃的时候会给这个问题加上wontfix标签。

**Comment by osfans** [comment]
希望不放棄，不然就只剩下win7可用了？

**Comment by blueflagbj** [comment]
估计是不予修复了，现在哪里能找到支持XP的小狼毫呢？现在找到的版本编译都编译不了，都报错啊~ 郁闷死了~

**Comment by lotem** [comment]
http://rime.im/download/

**Comment by blueflagbj** [comment]
@lotem 谢谢，我主要是想找0.9.30能够顺利编译下来的源码~ 

新版我一直找不到大写状态下，能够输出繁体的方法，能够指点一下吗？

**Comment by mrhso** [comment]
XP 失霊的問題応該是 VS2015 的鍋，難道還特地出個 XP 専版？

**Comment by mrhso** [comment]
我個人認為可以編訳両次，輸出両個版本。

**Comment by lotem** [comment]
我記得最後一版支持 Windows XP SP3。也不能用了？

**Comment by mrhso** [comment]
我之前譲 @Prcuvu 一個個 Commit 查，然後他就懐疑是 VS2015 的問題。
因為 VS2015 不再支持 XP 了。

**Comment by Prcuvu** [comment]
@mrhso 说得不准确。我后来用编译脚本还在 VS 2013 时候的 commit 用 VS 2015 编译，结果 Windows XP 也不能使用。我就认为是 VS 2015 的 runtime 有问题。

**Comment by nameoverflow** [comment]
vs2013以上版本由于实现了 C++ 11 标准，默认支持 threadlocal 的 static 变量初始化，但是 Windows XP 缺少 thread local 的支持，所以默认情况下如果代码中使用了全局 static 就会有问题，必须在 vc 中禁用 thread local 特性，即使用命令行选项 `/Zc:threadSafeInit-`。坑爹的是 vc140_xp 工具链并没有自动加上这个选项。我认为要使现在的代码兼容 xp，不仅代码编译时要加上这个选项，依赖项(包括 boost 和 librime)也要额外加上这个选项之后编译。

参见 https://docs.microsoft.com/en-us/cpp/build/reference/zc-threadsafeinit-thread-safe-local-static-initialization

**Comment by nameoverflow** [comment]
我还没实验，只是这两天看了资料觉得和这个有关。

**Comment by lotem** [comment]
試試在 `build.bat` 設置 `set CL=/Zc:threadSafeInit-`
另外 Boost 也需要添加參數 `cxxflags="/Zc:threadSafeInit- "` （[添加空格](https://svn.boost.org/trac10/ticket/11909)）

**Comment by sbxlmdsl** [comment]
Downloaded the newest version Weasel by Nameoverflow. It can work nice on Windows 10 Edge and Notepad. Excited for your great job. But for TSF and Edge, when inputting  Chinese characters with auto selection followed by space selection, only the last character retains and all others get lost.
