### ISSUE TITLE
如何去掉切换中英时的悬浮提示?

### ISSUE THREAD

**Issue by starYomate** [rime/weasel#770]
![image](https://user-images.githubusercontent.com/55619594/190947278-eae0662f-23fe-4f05-9bee-bcf8776a1f70.png)

**Comment by miloweimo** [comment]
https://github.com/rime/weasel/issues/520

You can modify [this code](https://github.com/rime/weasel/blob/master/RimeWithWeasel/RimeWithWeasel.cpp#L404-L407)

---
@starYomate 
我也遇到了，游戏切换会弹出到桌面，不少程序都有这个问题

**Comment by HwangBmw** [comment]
有没有简单的修改办法啊，这个中英文切换，太碍事了，需要关闭提示啊

**Comment by fxliang** [comment]
不怕新写的bug可以试这个
https://github.com/fxliang/weasel/actions/runs/6157965901

**Comment by yimmy23** [comment]
我也想知道如何关闭

**Comment by yimmy23** [comment]
> 不怕新写的bug可以试这个 https://github.com/fxliang/weasel/actions/runs/6157965901
> 
> ```yaml
> style/show_ascii_tip: false
> ```
请问这部分代码加载在哪个文件当中哇？

**Comment by fxliang** [comment]
> > 不怕新写的bug可以试这个 https://github.com/fxliang/weasel/actions/runs/6157965901
> > ```yaml
> > style/show_ascii_tip: false
> > ```
> 
> ## 请问这部分代码加载在哪个文件当中哇？
> 我找到了在哪里配置啦，一下子就舒服了，十分感谢！
> 
> @fxliang 谢谢你修改的小狼毫，希望能早点发布正式版！你的代码写的很好！赞！
> 
> ### 解决办法
> 在用户文件夹中weasel.custom.yaml添加：
> 
> ```yaml
> patch:
>   "style/+":
>     __include: "weasel_style_copy:/style"
> ```
> 
> 并在weasel_style_copy.yaml（复制weasel_style.yaml并重命名为weasel_style_copy.yaml）中style部分添加:
> 
> ```yaml
> show_ascii_tip: false
> ```

这个设置目前只对我那个action 的ci产出有效

**Comment by calmwaves111** [comment]
> 不怕新写的bug可以试这个 https://github.com/fxliang/weasel/actions/runs/6157965901
> 
> ```yaml
> style/show_ascii_tip: false
> ```

请问这个过期了 expired， 还有别的地方可以下载吗

**Comment by doglex** [comment]
weasel.yml 里设置show_notifications_time: 0 可以

**Comment by hbuboy** [comment]
weasel.yaml里设置 `show_notifications: false` 成功解决
