### ISSUE TITLE
Weasel 0.14.3.92 版本在开始菜单和 Microsoft 邮件应用中不能使用

### ISSUE THREAD

**Issue by ChihSee-Hsie** [rime/weasel#773]
https://github.com/fxliang/weasel/releases

如题，首先感谢 @fxliang 公在 Rime 基础上开发了适用于 Windows 11 的输入方案。但我在使用时发现一个问题——当希望在开始菜单和 Microsoft 邮件应用使用时，输入法似乎没有反应。

我注意到之前有过类似的讨论，但我无力修改代码，所以这里再反映一次。此至　祝安

**Comment by 107295472** [comment]
开始菜单win10也不能用

**Comment by ls148478** [comment]
作者说已知问题 修复方法未知

**Comment by fxliang** [comment]
是的，这个是在[rime/weasel最后一版提交](https://github.com/rime/weasel/commit/8462b83b355c444e59d37bbff04d14260b825333)上就有的问题（试过数次编译对比），可能更多是涉及系统输入法底层的相关内容，这个我不懂改不了。目前已知的开始菜单，explorer的搜索栏，桌面便签，部分uwp应用，都有无法输入的情况。

**Comment by Youxikong** [comment]
应该是tsf模式不能用了，所以uwp相关的程序都不能输入。

**Comment by Oyami-Srk** [comment]
![图片](https://user-images.githubusercontent.com/6939913/195674530-511e8eff-4aa1-4bf4-b01c-96dc05e0118e.png)
但是我用Rime.im上下载的小狼毫就可以在开始菜单中输入中文，不知道什么原因

**Comment by Youxikong** [comment]
> ![图片](https://user-images.githubusercontent.com/6939913/195674530-511e8eff-4aa1-4bf4-b01c-96dc05e0118e.png)
> 但是我用Rime.im上下载的小狼毫就可以在开始菜单中输入中文，不知道什么原因

是可以用的，但Dev版有bug。

**Comment by fxliang** [comment]
奆佬[这个提交](https://github.com/rime/weasel/commit/a56348786c8ee07bfefd29d604bb40f076e199d5) 有bug，已修复，等吧

![3f4834e8c676baab](https://user-images.githubusercontent.com/4023160/195825377-4f4c8745-4023-4599-8b0e-99d1c83571bd.png)

**Comment by fxliang** [comment]
check [this](https://github.com/fxliang/weasel/releases/tag/0.14.3_dev_0.94)
