### ISSUE TITLE
prompt 能否固定在最右边

### ISSUE THREAD

**Issue by LawssssCat** [rime/weasel#775]
当我 输入 nihao 然后左移 caret 后，prompt 也跟着移动了

![image](https://user-images.githubusercontent.com/18041500/192931806-f96c696d-68c5-45a4-a5d7-91c9f89b6b2c.png)

看起来不太舒服吧？

请问能否把 prompt 固定在最右，或者固定在 preedit 的最后？

![image](https://user-images.githubusercontent.com/18041500/192932384-d373b884-a65e-4df9-926d-86401ae4a04c.png)

**Comment by fxliang** [comment]
上游未将此内容单独拆分出来，暂无法独立实现。暂关闭此issue
