### ISSUE TITLE
能否推出便捷版

### ISSUE THREAD

**Issue by vstar37** [rime/weasel#776]
既然是本地存储数据的输入法，直接推出一个便捷版本应该会更利于备份。

**Comment by 107295472** [comment]
有啊
![image](https://user-images.githubusercontent.com/6436116/193507232-2169e437-199b-41c4-9240-1af4b22b888e.png)

**Comment by vstar37** [comment]
> 有啊 ![image](https://user-images.githubusercontent.com/6436116/193507232-2169e437-199b-41c4-9240-1af4b22b888e.png)

啊？在哪里下的？

**Comment by 107295472** [comment]
https://github.com/fxliang/weasel

**Comment by digitalstationol** [comment]
> https://github.com/fxliang/weasel
下哪個啊大佬
