### ISSUE TITLE
守望先锋2  开始游戏则会弹出错误

### ISSUE THREAD

**Issue by Wszl** [rime/weasel#777]
![image](https://user-images.githubusercontent.com/19342733/194009850-c7fb6ca6-4343-4cdd-85ce-6c0f4b0a2a37.png)

**Comment by SSSSSSSan** [comment]
同样遇到 win11 22H2  25211.1010

**Comment by rhuba8324** [comment]
win11 22H2 22621.608
同樣問題
fxliang的fork也是一樣狀況

**Comment by carrotvcgt** [comment]
> 



> 用 [Procmon.exe](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) 看了下游戏进程的文件访问记录，确实是读取了 `weasel.dll` 的，估计是被反作弊干掉了，毕竟输入法会注入到游戏进程里，很奇怪， ow1 就没这个问题。尝试自签证书放进系统 CA 里然后用证书给 dll 签名，也不行。看起来可能得找微软搞个专门的证书来签名才行

请问之后解决了么？微软证书是不是还需要付费呢？

**Comment by PinkD** [comment]
> 请问之后解决了么？微软证书是不是还需要付费呢？

没有解决，证书应该是要收费的。可以考虑开个微软输入法，或者使用语音沟通

**Comment by carrotvcgt** [comment]
> > 请问之后解决了么？微软证书是不是还需要付费呢？
> 
> 没有解决，证书应该是要收费的。可以考虑开个微软输入法，或者使用语音沟通

不是所有人都会进语音，应该是ow2的问题，我换用了另一款小众的第三方输入法（小鹤音形），相关的DLL文件也会有这个问题，但是用手心输入法，就正常。

**Comment by carrotvcgt** [comment]
> 用 [Procmon.exe](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) 看了下游戏进程的文件访问记录，确实是读取了 `weasel.dll` 的，估计是被反作弊干掉了，毕竟输入法会注入到游戏进程里，很奇怪， ow1 就没这个问题。尝试自签证书放进系统 CA 里然后用证书给 dll 签名，也不行。看起来可能得找微软搞个专门的证书来签名才行

游戏的问题，今天看论坛，有玩家用win11系统，微软自己家的dll文件也报相同错误。等修复游戏吧。

**Comment by j1g5awi** [comment]
游戏官方貌似已经修复了此问题
