### ISSUE TITLE
E1006  key_event.cc:72] parse error: unrecognized modifier 'Control '

### ISSUE THREAD

**Issue by PanWang3** [rime/weasel#778]
E1006 16:14:24.660436 15904 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:14:40.305300  6240 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:17:31.881249 31384 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:19:39.272063 27952 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:26:26.823514 22148 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:26:33.018853  2416 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:27:03.746663 32216 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:28:53.188719 26024 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:33:40.375800 30844 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:34:50.545763 24948 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:34:53.547098 28936 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:37:35.880364 33256 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:43:20.852258  4836 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:43:54.337514 31036 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:44:12.744208  1628 key_event.cc:72] parse error: unrecognized modifier 'Control '
E1006 16:44:45.695631 32200 key_event.cc:72] parse error: unrecognized modifier 'Control '

**Comment by lotem** [comment]
这是由错误的配置文件产生的日志。
您将自定义配置文件删除、用回原厂的默认配置就可以恢复正常了。
