### ISSUE TITLE
0.14.3_dev_0.92 版本卡顿不跟手

### ISSUE THREAD

**Issue by ls148478** [rime/weasel#779]
在个别软件中会出现很卡顿 不跟手的情况发生，貌似所有软件都是 只是有些应用不明显
为方便测试，使用方式为设置键盘驱动快速输入字母打字
这个使用原版是没有问题的 不知道能修复吗 挺影响体验的

https://user-images.githubusercontent.com/38435967/195256212-62bc1487-f66f-438d-b5ff-351e2e217ea8.mp4

**Comment by ls148478** [comment]
补一个原版输入速度：

https://user-images.githubusercontent.com/38435967/195256634-fb623371-1454-4e2b-87c1-b13fc25bc8b9.mp4

**Comment by ls148478** [comment]
> > 在个别软件中会出现很卡顿 不跟手的情况发生，貌似所有软件都是 只是有些应用不明显 为方便测试，使用方式为设置键盘驱动快速输入字母打字 这个使用原版是没有问题的 不知道能修复吗 挺影响体验的
> > 2022-10-12_13-00-49.mp4
> 
> 除了长按一个字母未试过输入这么快所以之前未有发现这个问题，有这个慢是因为： 1-做圆角使用了layeredwindows，比原版多了一道内存复制 2-然后为了按键按下的时候就有字显示，比原版多了一次界面重绘
> 
> 附档的文件可以试下（**切记覆盖要重新注册输入法否则后果很严重**）
> 
> +理论上如果要接近和原版一样的速度，潜在的方法是不使用目前这个圆角和透明的相关特性，这样就可以将上述的两个增项删减了。
> 
> [weasel-0.14.3_patch_only.zip](https://github.com/rime/weasel/files/9781526/weasel-0.14.3_patch_only.zip)

感谢解答相关疑问 我试了下 结果差不多 而且使用的是输入法自带的皮肤 理论上不具备圆角和透明相关特性

**Comment by fxliang** [comment]
> > > 在个别软件中会出现很卡顿 不跟手的情况发生，貌似所有软件都是 只是有些应用不明显 为方便测试，使用方式为设置键盘驱动快速输入字母打字 这个使用原版是没有问题的 不知道能修复吗 挺影响体验的
> > > 2022-10-12_13-00-49.mp4
> > 
> > 
> > 除了长按一个字母未试过输入这么快所以之前未有发现这个问题，有这个慢是因为： 1-做圆角使用了layeredwindows，比原版多了一道内存复制 2-然后为了按键按下的时候就有字显示，比原版多了一次界面重绘
> > 附档的文件可以试下（**切记覆盖要重新注册输入法否则后果很严重**）
> > +理论上如果要接近和原版一样的速度，潜在的方法是不使用目前这个圆角和透明的相关特性，这样就可以将上述的两个增项删减了。
> > [weasel-0.14.3_patch_only.zip](https://github.com/rime/weasel/files/9781526/weasel-0.14.3_patch_only.zip)
> 
> 感谢解答相关疑问 我试了下 结果差不多 而且使用的是输入法自带的皮肤 理论上不具备圆角和透明相关特性
我提到的圆角和透明，是指的代码层面的删除特性，下面这个是我粗暴删减这两个特性的小修改，原理上来说应该是和原版差不多的了（手停即停）
 
[weasel-0.14.3_patch_only.7z.zip](https://github.com/rime/weasel/files/9781889/weasel-0.14.3_patch_only.7z.zip)

https://user-images.githubusercontent.com/4023160/195746982-5e1dd852-4436-4e6d-894a-b1e03d463fe5.mp4

**Comment by fxliang** [comment]
> > > 在个别软件中会出现很卡顿 不跟手的情况发生，貌似所有软件都是 只是有些应用不明显 为方便测试，使用方式为设置键盘驱动快速输入字母打字 这个使用原版是没有问题的 不知道能修复吗 挺影响体验的
> > > 2022-10-12_13-00-49.mp4
> > 
> > 
> > 除了长按一个字母未试过输入这么快所以之前未有发现这个问题，有这个慢是因为： 1-做圆角使用了layeredwindows，比原版多了一道内存复制 2-然后为了按键按下的时候就有字显示，比原版多了一次界面重绘
> > 附档的文件可以试下（**切记覆盖要重新注册输入法否则后果很严重**）
> > +理论上如果要接近和原版一样的速度，潜在的方法是不使用目前这个圆角和透明的相关特性，这样就可以将上述的两个增项删减了。
> > [weasel-0.14.3_patch_only.zip](https://github.com/rime/weasel/files/9781526/weasel-0.14.3_patch_only.zip)
> 
> 感谢解答相关疑问 我试了下 结果差不多 而且使用的是输入法自带的皮肤 理论上不具备圆角和透明相关特性
我提到的圆角和透明，是指的代码层面的删除特性，下面这个是我粗暴删减这两个特性的小修改，原理上来说应该是和原版差不多的了（手停即停）
 
[weasel-0.14.3_patch_only.7z.zip](https://github.com/rime/weasel/files/9781889/weasel-0.14.3_patch_only.7z.zip)

https://user-images.githubusercontent.com/4023160/195746982-5e1dd852-4436-4e6d-894a-b1e03d463fe5.mp4

**Comment by fxliang** [comment]
另外您反馈的这个卡顿的问题，我在我一台旧的手提电脑上有复现，在另外一台配置高的电脑上就没有这个问题。

**Comment by ls148478** [comment]
> > > > 在个别软件中会出现很卡顿 不跟手的情况发生，貌似所有软件都是 只是有些应用不明显 为方便测试，使用方式为设置键盘驱动快速输入字母打字 这个使用原版是没有问题的 不知道能修复吗 挺影响体验的
> > > > 2022-10-12_13-00-49.mp4
> > > 
> > > 
> > > 除了长按一个字母未试过输入这么快所以之前未有发现这个问题，有这个慢是因为： 1-做圆角使用了layeredwindows，比原版多了一道内存复制 2-然后为了按键按下的时候就有字显示，比原版多了一次界面重绘
> > > 附档的文件可以试下（**切记覆盖要重新注册输入法否则后果很严重**）
> > > +理论上如果要接近和原版一样的速度，潜在的方法是不使用目前这个圆角和透明的相关特性，这样就可以将上述的两个增项删减了。
> > > [weasel-0.14.3_patch_only.zip](https://github.com/rime/weasel/files/9781526/weasel-0.14.3_patch_only.zip)
> > 
> > 
> > 感谢解答相关疑问 我试了下 结果差不多 而且使用的是输入法自带的皮肤 理论上不具备圆角和透明相关特性
> 
> 我提到的圆角和透明，是指的代码层面的删除特性，下面这个是我粗暴删减这两个特性的小修改，原理上来说应该是和原版差不多的了（手停即停）
> 
> [weasel-0.14.3_patch_only.7z.zip](https://github.com/rime/weasel/files/9781889/weasel-0.14.3_patch_only.7z.zip)
> 
>  default.mp4

如果确定已经去除相关特性的话 那我这边依然复现 性能方面如你所定也有可能 因为我没有插独立显卡
![image](https://user-images.githubusercontent.com/38435967/195752618-cb589aea-9ca0-4e5c-9657-3b2287b752c0.png)
我发现应该还有问题 在输入一些不参与编码的符号的时候也不会直接上屏 比如 "-" 符号
还有直接上屏的编码 比如我的这个方案 字母 'e' 就只有一个选项 '有'  这种情况 我设置的是直接上屏 但貌似也会参与编码 不会直接上屏

https://user-images.githubusercontent.com/38435967/195753031-befd5c5b-04bd-4633-879a-5816e6a340e5.mp4

**Comment by fxliang** [comment]
你这个配置已经比我的电脑高了，我的是i7 旧版本+16g，独立显卡

另外可以试试使用style/color_font: false 试下，默认使用的color_font: true 目前还是之前的分层窗口的方式绘制会有额外开销
我试了如果还设定style/color_font: false的话输入 - 的时候确实会有类似你视频展示的状态，如果设定了color_font: false就响应会正常下来。目前来评估应该是directwrite和gdi兼容的要求产生的额外绘制开销。
看来是要大改一下才可能了

**Comment by ls148478** [comment]
> 你这个配置已经比我的电脑高了，我的是i7 旧版本+16g，独立显卡
> 
> 另外可以试试使用style/color_font: false 试下，默认使用的color_font: true 目前还是之前的分层窗口的方式绘制会有额外开销 我试了如果还设定style/color_font: false的话输入 - 的时候确实会有类似你视频展示的状态，如果设定了color_font: false就响应会正常下来。目前来评估应该是directwrite和gdi兼容的要求产生的额外绘制开销。 看来是要大改一下才可能了

我试了您说这种方法 发现延迟降低了非常非常多 在人为正常输入的情况下 已经感觉不到那种慢一拍的感觉了 很流畅了

**Comment by ls148478** [comment]
> 你这个配置已经比我的电脑高了，我的是i7 旧版本+16g，独立显卡
> 
> 另外可以试试使用style/color_font: false 试下，默认使用的color_font: true 目前还是之前的分层窗口的方式绘制会有额外开销 我试了如果还设定style/color_font: true的话输入 - 的时候确实会有类似你视频展示的状态，如果设定了color_font: false就响应会正常下来。目前来评估应该是directwrite和gdi兼容的要求产生的额外绘制开销。 看来是要大改一下才可能了

经过再次实测 已经没问题了 之前我设置的10ms为间距输入字母 因为其他输入法都没问题 所以先入为主认为很卡 现在想想这个速度已经非常苛刻了 无论是10ms还是20ms 人都很难保持这个速度打字

https://user-images.githubusercontent.com/38435967/195762067-465a1ea3-0c8e-471a-913e-b92d164931bf.mp4

目前看来造成卡顿的主要原因还是style/color_font

**Comment by fxliang** [comment]
比对你的配置和我的配置，就差独立显卡，可能是directwrite吃gpu性能。我那台手提也是没有独立显卡。之前去了分层窗口有改善，但是集显上还是补不回来吧大概。

**Comment by fxliang** [comment]
> 经过再次实测 已经没问题了 之前我设置的10ms为间距输入字母 因为其他输入法都没问题 所以先入为主认为很卡 现在想想这个速度已经非常苛刻了 无论是10ms还是20ms 人都很难保持这个速度打字

难怪，我就想为什么你这个输入速度这么恐怖……不过这个也是好的，挖出一点东西潜在后面可能有用😁

**Comment by fxliang** [comment]
@ls148478 
可以试试下面的patch，我这边测试10ms的间隔基本上可以在style/color_font: true的时候响应基本满足要求没有卡顿的情况了。
[weasel-0.14.3_patch_only.7z.zip](https://github.com/rime/weasel/files/9806351/weasel-0.14.3_patch_only.7z.zip)

**Comment by ls148478** [comment]
> @ls148478 可以试试下面的patch，我这边测试10ms的间隔基本上可以在style/color_font: true的时候响应基本满足要求没有卡顿的情况了。 [weasel-0.14.3_patch_only.7z.zip](https://github.com/rime/weasel/files/9806351/weasel-0.14.3_patch_only.7z.zip)

我在刚才尝试了下 感觉问题是差不多的
为了确保失误 我录制了安装流程及测试 而且我刚发现在windows自带应用中终于可以正常打字了（看来这个持续了很久的问题得到了解决）

https://user-images.githubusercontent.com/38435967/196435399-707192e2-0ac9-44fe-8fc4-36d2622337e8.mp4

**Comment by ls148478** [comment]
> @ls148478 可以试试下面的patch，我这边测试10ms的间隔基本上可以在style/color_font: true的时候响应基本满足要求没有卡顿的情况了。 [weasel-0.14.3_patch_only.7z.zip](https://github.com/rime/weasel/files/9806351/weasel-0.14.3_patch_only.7z.zip)

因为发现修复了windows自带应用无法打字的问题 所以打了几个字 但我手打的时候就发现了不跟手的情况 就像最开始的情况一样 但是这次我的配置中 style/color_font: fals 这貌似是新的问题 下面是对比视频

https://user-images.githubusercontent.com/38435967/196438917-52f3a204-83ea-402d-9baa-b21e91c7ed80.mp4

**Comment by fxliang** [comment]
> > @ls148478 可以试试下面的patch，我这边测试10ms的间隔基本上可以在style/color_font: true的时候响应基本满足要求没有卡顿的情况了。 [weasel-0.14.3_patch_only.7z.zip](https://github.com/rime/weasel/files/9806351/weasel-0.14.3_patch_only.7z.zip)
> 
> 因为发现修复了windows自带应用无法打字的问题 所以打了几个字 但我手打的时候就发现了不跟手的情况 就像最开始的情况一样 但是这次我的配置中 style/color_font: fals 这貌似是新的问题 下面是对比视频
> 
>  2022-10-18_21-06-15.mp4

这个是你输入内容之后开始菜单还有一个搜索的动作影响 了显示吧。我试过windows 10上的开始菜单输入，有微软的输入法输入也是一样的问题的,只要长按一个按键就可以复现。

**Comment by fxliang** [comment]
> > @ls148478 可以试试下面的patch，我这边测试10ms的间隔基本上可以在style/color_font: true的时候响应基本满足要求没有卡顿的情况了。 [weasel-0.14.3_patch_only.7z.zip](https://github.com/rime/weasel/files/9806351/weasel-0.14.3_patch_only.7z.zip)
> 
> 我在刚才尝试了下 感觉问题是差不多的 为了确保失误 我录制了安装流程及测试 而且我刚发现在windows自带应用中终于可以正常打字了（看来这个持续了很久的问题得到了解决）
> 
>  2022-10-18_20-46-09.mp4

我在Windows10上试记事本和相关的常见的应用是明显有比之前有改善的，当然发现在一些程序比如企业微信上会没有记事本上响应的快速。你目前这个结果，可能看看重启或者重新登陆之后是不是会有一样的结果，不然只能理解成输入应用的偏差了。

输入比如 - （减号）的时候明显是比之前的状态要顺了很多了，之前长按减号是会有卡顿的情况的。

此外有在Windows10下对比测试的是同样的输入（ahk实现的连续输入），在notepad(系统自带）、notepad3, write.exe(系统自带）三个应用上的响应情况是有巨大差异的。

**Comment by ls148478** [comment]
> > > @ls148478 可以试试下面的patch，我这边测试10ms的间隔基本上可以在style/color_font: true的时候响应基本满足要求没有卡顿的情况了。 [weasel-0.14.3_patch_only.7z.zip](https://github.com/rime/weasel/files/9806351/weasel-0.14.3_patch_only.7z.zip)
> > 
> > 
> > 我在刚才尝试了下 感觉问题是差不多的 为了确保失误 我录制了安装流程及测试 而且我刚发现在windows自带应用中终于可以正常打字了（看来这个持续了很久的问题得到了解决）
> > 2022-10-18_20-46-09.mp4
> 
> 我在Windows10上试记事本和相关的常见的应用是明显有比之前有改善的，当然发现在一些程序比如企业微信上会没有记事本上响应的快速。你目前这个结果，可能看看重启或者重新登陆之后是不是会有一样的结果，不然只能理解成输入应用的偏差了。
> 
> 输入比如 - （减号）的时候明显是比之前的状态要顺了很多了，之前长按减号是会有卡顿的情况的。
> 
> 此外有在Windows10下对比测试的是同样的输入（ahk实现的连续输入），在notepad(系统自带）、notepad3, write.exe(系统自带）三个应用上的响应情况是有巨大差异的。

我尝试了你说的三个方案，基本上只要style/color_font: false 的情况下，都是键盘停就停 键盘按下就出字 不会再像以前那样键盘停下还会在输入的情况发生 但是如果值为true的话 效果还是不大
不过毕竟可以修改配置文件来改变结果 这只能说是性能没符合要求 是可以接受的
就是这个在高速连续输入的时候不会直接上屏 而是等输入完成后再上屏这个不知能否优化

**Comment by fxliang** [comment]
check [this](https://github.com/fxliang/weasel/releases/tag/0.14.3_dev_0.94)
