### ISSUE TITLE
windows下输入法设置默认为英文失败

### ISSUE THREAD

**Issue by hairuo** [rime/weasel#78]
问题描述：
想将rime输入法默认设置为英文，参考帖子http://linfan.info/blog/2013/11/15/rime-ime-config/ 的做法，在电脑里找到所有的luna_pinyin_simp.schema.yaml文件，将其中的内容修改为：
switches:
  - name: ascii_mode
    reset: 1
    states: [ 中文, 西文 ]

具体操作是找到reset的值0将其用gvim改为1，让后保存退出。并确认所有luna_pinyin_simp.schema.yaml文件都这样修改了。发现还是不行，重启电脑再查看，发现输入法还是默认为中文。

系统配置：
Windows 7 Ultimate, SP1, 64-bit
weasel-0.9.30.0-installer

谢谢！

**Comment by lotem** [comment]
修改的是「朙月拼音·簡化字」這個輸入方案，是否選用了這個方案？

**Comment by hairuo** [comment]
不是，我用的是小鹤双拼。请问这样怎么修改？谢谢!
