### ISSUE TITLE
Weasal 0.14.3_dev_0.92 請問之後的版本能把label也跟"style/layout/align_type"嗎？

### ISSUE THREAD

**Issue by DamienLeung** [rime/weasel#782]
現在label和text的align的方式是分開的，label只能居中，而comment和text是用"style/layout/align_type"。

**Comment by fxliang** [comment]
bottom
![image](https://user-images.githubusercontent.com/4023160/196658973-53251ad2-97e2-4309-85cd-b28429bb55ec.png)
![image](https://user-images.githubusercontent.com/4023160/196658979-9a8bc82f-e44c-4db0-b956-157a13132f40.png) 

center
![image](https://user-images.githubusercontent.com/4023160/196659165-bd5ef440-c86b-4efa-b8b2-c707fa0263f7.png) 
![image](https://user-images.githubusercontent.com/4023160/196659791-bfe2ff66-0702-44ed-9490-6169ed85cd12.png)

看上去挺正常的
