### ISSUE TITLE
Weasel 0.14.3.93：有没有可能将加入了 lua 插件的 rime.dll 放在安装包中？

### ISSUE THREAD

**Issue by ChihSee-Hsie** [rime/weasel#783]
如题，首先感谢 @fxliang 公的改进工作。Rime 中有编码过滤的扩展功能，如在 engine/filter 中选择加入 charset_filter@gbk+emoji 即可使出字限制在 GBK 编码的同时还能显示不在 GBK 编码内的 emoji。然而这种功能需要特制的、加入过 lua 插件的 rime.dll 才能实现，目前这种 rime.dll 可以在 [此网页](https://github.com/rime/librime/releases) 的 rime-with-plugins-1.7.3-win32.zip 中找到。

另外，不知道是否是我的使用问题，我发现 Weasel 0.14.3.93 v中 font_face 字段在 color_font 开启时似乎失效了。此至　顺颂祺安

**Comment by ChihSee-Hsie** [comment]
我在 weasel.yaml 中有关的配置如下：
    style:  
    color_scheme: purity_of_form  
    color_font: true  
    #color_font: false  
    display_tray_icon: false  
    font_face: SimSun   #为使效果明显而使用
    #font_face: "Noto Sans SC Medium"  
    font_point: 11  
    label_font_face: "Noto Sans"  
    label_font_point: 11  
    comment_font_face: Noto Sans SC  
    horizontal: true  
    inline_preedit: true  
    #preedit_style": preview # 默认是 composition。`

但是确实没有效果，界面显示的是黑体字，如果改用 color_font: false 则可以。

**Comment by fxliang** [comment]
> font_face: SimSun

哈哈，新写的bug：字体设置不能马上对已经使用的窗口生效。
如果另外开一个窗口就没有问题的，问题已收到，原因也基本明确，有空改完放个补丁。

**Comment by fxliang** [comment]
@ChihSee-Hsie 已修订可用，自行更新了~

**Comment by ChihSee-Hsie** [comment]
感谢更新。不过我在使用中发现在 Firefox 浏览器里重新部署的结果仍然不能即时体现。我直接将 hotfix 的 patch_only 文件夹中的内容提取出来替换程序文件夹中对应的文件，另外 rime.dll 使用的是前面提到的版本，即 [这里](https://github.com/rime/librime/releases) 的内容。

**Comment by fxliang** [comment]
> 感谢更新。不过我在使用中发现在 Firefox 浏览器里重新部署的结果仍然不能即时体现。我直接将 hotfix 的 patch_only 文件夹中的内容提取出来替换程序文件夹中对应的文件，另外 rime.dll 使用的是前面提到的版本，即 [这里](https://github.com/rime/librime/releases) 的内容。

不生效这个和librime不相关

覆盖之后还要重新注册一下输入法的，之前已经在运行的应用要重新启动一下才能启用到新注册的程式。

上面不知道你有没有处理。我这边试是没有问题的。如下测试

重新部署前宋体字
![图片](https://user-images.githubusercontent.com/4023160/196896693-58dad228-c9f3-4cca-9400-44bd78103d29.png)
修改字体重新部署后楷体字
![图片](https://user-images.githubusercontent.com/4023160/196896922-0501c616-9d3b-45f5-b07e-495622f356bc.png)

**Comment by ChihSee-Hsie** [comment]
试过了。感谢！

**Comment by ChihSee-Hsie** [comment]
Rime 原有的图标有些篆意，根据这个试着重做了全角和半角的图标，以下包括 .svg 文件和作例子的 .ico 文件：

[Icons.zip](https://github.com/rime/weasel/files/9846255/Icons.zip)

**Comment by fxliang** [comment]
图标不是我擅长，但是如果说要篆风，还不如这样？

![full](https://user-images.githubusercontent.com/4023160/197388241-23a1c99f-a89e-4955-acd2-8bbd19579cb8.svg)
![half](https://user-images.githubusercontent.com/4023160/197388252-41066f3a-fc95-4187-9f1e-86ccecb18b5c.svg)

**Comment by ChihSee-Hsie** [comment]
啊，因为 Rime 现有标记的风格是将篆书的笔画取直改方嘛，比如主要的图标就是「之」的篆体（或者说是注音字母 ㄓ），等等——所以我这么画了画😂️

**Comment by swwrww** [comment]
咦，奇怪了，最新版0.14.3_dev_0.98的不是用上最新的librime 1.7.3了，我装上后还是老问题不能显示emoji的滤镜和其他lua功能。最终还是手动换上[rime-with-plugins-1.7.3-win32.zip](https://github.com/rime/librime/releases/download/1.7.3/rime-with-plugins-1.7.3-win32.zip)里的rime.dll，才都正常了。
