### ISSUE TITLE
切換中英文的提示 in 0.14.3_dev_0.93

### ISSUE THREAD

**Issue by ywxt** [rime/weasel#785]
在切換中英文時

![image](https://user-images.githubusercontent.com/25864091/197390187-b0355f40-c56f-40a2-b3f6-c3df268bb90f.png)

在白色背景下沒有問題，但黑色時就看不清了。

![image](https://user-images.githubusercontent.com/25864091/197390306-b5f7e497-bedb-4646-9466-634d1512d539.png)

還有一個問題，當只有一個候選時，留白太多了。

![image](https://user-images.githubusercontent.com/25864091/197390346-5b6f02f0-42dc-4360-bfe0-adbeafe6bf02.png)

嘗試修改`candidate_spacing`，`margin_x`，`hilite_padding` 這幾個選項都不行。

**Comment by fxliang** [comment]
> 在切換中英文時
> 
> ![image](https://user-images.githubusercontent.com/25864091/197390187-b0355f40-c56f-40a2-b3f6-c3df268bb90f.png)
> 
> 在白色背景下沒有問題，但黑色時就看不清了。
> 
> ![image](https://user-images.githubusercontent.com/25864091/197390306-b5f7e497-bedb-4646-9466-634d1512d539.png)
> 
> 還有一個問題，當只有一個候選時，留白太多了。
> 
> ![image](https://user-images.githubusercontent.com/25864091/197390346-5b6f02f0-42dc-4360-bfe0-adbeafe6bf02.png)
> 
> 嘗試修改`candidate_spacing`，`margin_x`，`hilite_padding` 這幾個選項都不行。

第一个问题，检查当前使用的配色主题的back_color项的不透明度(0xaabbggrr中的aa)是否设置太小，如果背景不透明度太低的话(aa接近0)，这种问题无法避免的（因为text color是定的back color不确定）。我目前使用的主题下切换正常未见异常。
![image](https://user-images.githubusercontent.com/4023160/197429057-0f648d98-b0e2-44d7-bc32-2a24a300eeb1.png)

第二个问题，请检查style/layout/min_width项设置，默认160，如需可以调整到更少的值上~下图是我patch为60之后的表现
![image](https://user-images.githubusercontent.com/4023160/197429230-384bbe52-9d19-4564-a9fa-a36a7c78b111.png)

麻烦确认一下

**Comment by ywxt** [comment]
第二個問題已解決，感謝！

關於第一個問題，我的`back_color`是`0xFFFFFFFF`，而且按道理如果`a`爲0的話是整個候選框的底色都透明了，但目前我的情況是只有中英文切換時的狀態指示器透明，候選框是正常的。

@fxliang

**Comment by JaHIY** [comment]
我这边也有第一个问题，按照设置`back_color`的方式依旧无法解决。
我在`weasel.custom.yaml`中打了patch，具体如下：
```yaml
patch:
  "menu/page_size": 6
  "preset_color_schemes/metroblue/back_color": 0xffffffff
  "style/color_scheme": metroblue
  "style/horizontal": true
  "style/inline_preedit": true
```

**Comment by fxliang** [comment]
确认流程：
1、退出服务
2、覆盖文件
3、使用weaselsetup.exe重新安装
4、启动服务，如有修改配置重新部署一次
5、启动新的输入应用测试切换中英文提示显示

目前未有发现一次失败的操作，显示都是正常的。

**Comment by fxliang** [comment]
> 小狼毫自带的配色方案即在`weasel.yaml`中的`preset_color_schemes`内的配色方案，里面的颜色基本上都是设置成形如`0xrrggbb`的形式，而不是包含透明度的`0xaarrggbb`形式，通过`0xrrggbb`设置的颜色，它的透明度应该默认就是不透明的吧，即`0xrrggbb`与`0xFFrrggbb`是等价的，我这样理解对不对？

0xaabbggrr
等价0xbbggrr

aa==ff时全不透明
aa==00时全透明

**Comment by JaHIY** [comment]
> > 小狼毫自带的配色方案即在`weasel.yaml`中的`preset_color_schemes`内的配色方案，里面的颜色基本上都是设置成形如`0xrrggbb`的形式，而不是包含透明度的`0xaarrggbb`形式，通过`0xrrggbb`设置的颜色，它的透明度应该默认就是不透明的吧，即`0xrrggbb`与`0xFFrrggbb`是等价的，我这样理解对不对？
> 
> 0xaabbggrr 等价0xbbggrr
> 
> aa==ff时全不透明 aa==00时全透明

那只写`0xbbggrr`的时候，默认的`aa`是`ff`咯？

**Comment by fxliang** [comment]
> > > 小狼毫自带的配色方案即在`weasel.yaml`中的`preset_color_schemes`内的配色方案，里面的颜色基本上都是设置成形如`0xrrggbb`的形式，而不是包含透明度的`0xaarrggbb`形式，通过`0xrrggbb`设置的颜色，它的透明度应该默认就是不透明的吧，即`0xrrggbb`与`0xFFrrggbb`是等价的，我这样理解对不对？
> > 
> > 
> > 0xaabbggrr 等价0xbbggrr
> > aa==ff时全不透明 aa==00时全透明
> 
> 那只写`0xbbggrr`的时候，默认的`aa`是`ff`咯？

当然，不然就和原版不兼容了。

**Comment by JaHIY** [comment]
你好，我刚才排查了一下发现，当我在`weasel.custom.yaml`用以下配置时，就会发生第一个问题：
```yaml
patch:
  "style/inline_preedit": true
```
当我把`"style/inline_preedit": true`删除之后，问题就消失了，可能这其中有什么bug？

**Comment by fxliang** [comment]
可能算？我是一直在滚动更新修改的版本，一直没有发现你提的问题似乎，这个相关的部分也没有专门留意去处理什么相关内容的。
当然可能是我没有去留意这个，而且我主要没有去设置 inline_preedit。

在**做好在运行应用数据保存的前提下**，可以试试这个我在用的最新编译。
[weasel-0.14.3_patch_only.zip](https://github.com/rime/weasel/files/9857550/weasel-0.14.3_patch_only.zip)

**Comment by ywxt** [comment]
删除`inline_preedit`指示器好了，但是这样就成了多行了☹。

**Comment by JaHIY** [comment]
> 可能算？我是一直在滚动更新修改的版本，一直没有发现你提的问题似乎，这个相关的部分也没有专门留意去处理什么相关内容的。 当然可能是我没有去留意这个，而且我主要没有去设置 inline_preedit。

您可以设置一下看看是不是有复现出这个bug，我目前用的就是您开发的最新版本`0.14.3.93-hotfix01`，当然这个问题在之前的版本里也存在着，不单单是在最新版本里，可能是您一直没注意到……

**Comment by fxliang** [comment]
> > 可能算？我是一直在滚动更新修改的版本，一直没有发现你提的问题似乎，这个相关的部分也没有专门留意去处理什么相关内容的。 当然可能是我没有去留意这个，而且我主要没有去设置 inline_preedit。
> 
> 您可以设置一下看看是不是有复现出这个bug，我目前用的就是您开发的最新版本`0.14.3.93-hotfix01`，当然这个问题在之前的版本里也存在着，不单单是在最新版本里，可能是您一直没注意到……

可能是我发布之后很快又更新了，在新版上没有再复现这个问题所以没有发现吧大概，不是大问题。快了快了。

**Comment by fxliang** [comment]
@JaHIY @ywxt 
check [this](https://github.com/fxliang/weasel/releases/tag/0.14.3_dev_0.94)

**Comment by ywxt** [comment]
已解決
