### ISSUE TITLE
状态提示窗口的圖標 in 0.14.3_dev_0.94

### ISSUE THREAD

**Issue by ywxt** [rime/weasel#788]
當候選框太小時，状态提示窗口的圖標會超出窗口，希望可以把圖標縮放一下。

![image](https://user-images.githubusercontent.com/25864091/198036218-81d91cc7-8b64-4f0f-989e-acba341aea57.png)

**Comment by fxliang** [comment]
> 當候選框太小時，状态提示窗口的圖標會超出窗口，希望可以把圖標縮放一下。
> 
> ![image](https://user-images.githubusercontent.com/25864091/198036218-81d91cc7-8b64-4f0f-989e-acba341aea57.png)

缩放是不可能缩放的了，建议合理设置字体大小、margin_x、margin_y的大小

在字体大小和margin大小没有限制的情况下无法通过图标的大小缩放解决所有问题，比如当font_point设定为1，margin设定为0或绝对值接近0的值的时候，太小的图标就没有存在的意义了。
当然也有可能程序自动根据字体大小调整margin、或者布局运算自动限制窗体最小高度，但是这些做法都会引入报异常：明明设置了一个margin为何结果和设定有偏差。

与其这样不如让用家自己选择设定参数解决这个问题

**Comment by ywxt** [comment]
> > 當候選框太小時，状态提示窗口的圖標會超出窗口，希望可以把圖標縮放一下。
> > ![image](https://user-images.githubusercontent.com/25864091/198036218-81d91cc7-8b64-4f0f-989e-acba341aea57.png)
> 
> 缩放是不可能缩放的了，建议合理设置字体大小、margin_x、margin_y的大小
> 
> 在字体大小和margin大小没有限制的情况下无法通过图标的大小缩放解决所有问题，比如当font_point设定为1，margin设定为0或绝对值接近0的值的时候，太小的图标就没有存在的意义了。
> 
> 当然也有可能程序自动根据字体大小调整margin、或者布局运算自动限制窗体最小高度，但是这些做法都会引入报异常：明明设置了一组font_point和margin，为何结果和设定有偏差。
> 
> 与其这样不如让用家自己选择设定参数解决这个问题

那可以給個選項把這個圖標去掉嗎？用指示器用文字就夠了。

**Comment by ChihSee-Hsie** [comment]
我这里出现的情况是，当 margin_x 远远小于 0 时（我设置的数值是 -1000😂️），在 Firefox 浏览器上切换中西文输入状态，状态提示窗口会覆盖整个屏幕——当然将 margin 的绝对值改小就不会了。margin 小于 0 时（甚至不论 margin 取任何值），有没有方法将状态栏大小设置为不随 margin 改变的定值呢？因为用家修改 margin，重点关注的似乎是输入框，而状态栏似乎更多作为程序框架的一部分，它不改变也许还说得过去。

**Comment by fxliang** [comment]
为什么要-1000呢？
因为在计算布局的时候，如果使用一个负值不做绝对值去计算的时候，会出来各种各样的异常，所以在计算布局的时候会使用margin的绝对值来计算这样可以避免这些异常。

换句话来理解就是负值的margin本来就是一个异常的、没有物理意义的值，只能将其正负来判断是不是要隐藏候选窗口

当margin是负值时，窗口的布局计算使用的margin的绝对值，只是为了节省运算，正常的候选窗口的布局计算和绘制都直接跳过（如果不跳过也用的margin的绝对值），而提示窗、方案选单的情况没有跳过罢了。

所以**不要设置绝对值过大的margin**。

PS，0.94有点内存泄漏的问题，如果打开过太多窗口，占用内在会增长到几十M，因此暂时删了release避免扩大影响了。

**Comment by ywxt** [comment]
在最新的版本中，中英文只顯示圖標了，但繁簡轉換的提示還沒有改過來。

![image](https://user-images.githubusercontent.com/25864091/199220271-765093aa-15ca-4828-bdf0-0580e9baf503.png)

@fxliang

**Comment by fxliang** [comment]
> 在最新的版本中，中英文只顯示圖標了，但繁簡轉換的提示還沒有改過來。
> 
> ![image](https://user-images.githubusercontent.com/25864091/199220271-765093aa-15ca-4828-bdf0-0580e9baf503.png)
> 
> @fxliang

因为就不是为这个改的呀

**Comment by ywxt** [comment]
> 因为就不是为这个改的呀

好吧
