### ISSUE TITLE
输入法状态显示问题

### ISSUE THREAD

**Issue by Eyion** [rime/weasel#790]
问题：在小狼毫输入法下，使用ImTip切换为英文状态，但追踪仍显示中文状态。截图如下：
![图片](https://user-images.githubusercontent.com/26318038/199146354-fe11eefb-2738-4b98-9ed0-dbaaa937a216.png)
ImTip作者反馈截图如下：
![图片](https://user-images.githubusercontent.com/26318038/199145940-d4f7a05b-f53a-4daf-a544-1777b31e64a6.png)
ImTip官网：https://imtip.aardio.com/
诉求：希望作者更新支持，谢谢！

**Comment by fxliang** [comment]
closed by #956
