### ISSUE TITLE
请问 Ctrl+` 快捷键能否更改的？

### ISSUE THREAD

**Issue by LawssssCat** [rime/weasel#791]
打开选项菜单我用 F4 就够了，`` Ctrl+` `` 快捷键我想取消，给 vscode 打开 控制台使用。

但是，我尝试修改配置 `key_binder/bindings` 或者 `editor/bindings` 均无法取消 `` Ctrl+` ``  快捷键。

源码全局搜 weasel 和 librime 也没找到在哪里定义的。
 
![image](https://user-images.githubusercontent.com/18041500/199758085-865cf6ec-333c-4291-b81f-cabe56fd9e35.png)

**Comment by lotem** [comment]
https://github.com/rime/rime-prelude/blob/master/default.yaml#L19-L19

修改 `switcher/hotkeys`
