### ISSUE TITLE
Windows 10深色主題下右鍵選單時而黑色時而白色

### ISSUE THREAD

**Issue by ashton2914** [rime/weasel#792]
時而白色
![image](https://user-images.githubusercontent.com/17692778/199925554-d501022a-08b4-463e-99fa-687b76b8400f.png)
時而黑色
![image](https://user-images.githubusercontent.com/17692778/199925609-0aefb480-429a-4ccd-a354-1c353e62a482.png)

**Comment by fxliang** [comment]
这个取决于当前输入法所处的应用是否支持深色主题，一些较新的适配了深色模式的APP就黑色，反之则浅色。
