### ISSUE TITLE
关于0.14.3_dev_0.95在Windows 11上诱发的连续性程序崩溃

### ISSUE THREAD

**Issue by ryanlo713** [rime/weasel#794]
环境：Windows 11 22H2

前提：卸载原版0.14.3后使用安装包安装，用户数据沿用。

情况：切换至小狼毫后，凡是带有文字输入框的程式窗口处于活动状态时，程式崩溃而停止工作。

截图：

![image](https://user-images.githubusercontent.com/12672523/200179731-0b04304b-8521-4f88-82aa-2004bccb73a3.png)

![image](https://user-images.githubusercontent.com/12672523/200179734-ecfd6829-2b05-4dcb-8ee2-e04c0da83fd7.png)

除了这两个之外，Chrome和按Win+R呼叫出来的运行也会崩溃，还会弹出一些背景服务已停止工作的窗口；当所有符合条件的窗口全部被迫关闭后，Windows资源管理器崩溃，任务栏和壁纸消失，并不断来回重启关闭，必须按Win+空格切换成别的输入法（任务管理器没有带有文字输入框所以还能运行，所以也可通过对小狼毫算法服务「结束任务」暂时恢复正常）

![image](https://user-images.githubusercontent.com/12672523/200179679-ba25060d-ff45-4099-8681-a509d9648fc7.png)

部署处于活动窗口时也会因此崩溃

![image](https://user-images.githubusercontent.com/12672523/200179822-8250c54c-12f7-4260-aed9-23f2a7dcd8c1.png)

**Comment by fxliang** [comment]
抱歉造成这么令人不愉快的情况~

由于没有Windows 11测试环境，所以没有办法亲测。

建议安装前切换到其他输入法，安装后重启系统或者注销后重新登陆。如果顺利的话问题有可能消失了~

**Comment by fxliang** [comment]
整了个11的虚拟机试了，一切正常。您描述的问题，根本原因大概率是更新安装方式不对导致的。如果是旧版长上来最好还是切换到其他输入法，安装，注销或重启。

**Comment by fxliang** [comment]
> 

那个通常是熟练跟进只想下载少量文件的同志使用，他们通常有批处理脚本快速处理相关操作的了。
如果应用有更新新增参数的话，通常会引起此前使用过的app崩。所以如果用那个patch_only，最好的办法是解注册(weaselsetup.exe), 注销，登陆，注册添加，运行server服务，（如果想再稳点的话加登出登入一次），运行正常的App正常使用。

**Comment by fxliang** [comment]
问题解决建议关闭issue
