### ISSUE TITLE
0.14.3_dev_0.95中文方案使用了opencc实现的emoji表情和symbol失效，无法正常显示

### ISSUE THREAD

**Issue by DreamAfar** [rime/weasel#795]
系统：Windows 11 22H2

升级到0.14.3_dev_0.95版本，使用了opencc实现emoji表情和symbol，在中文方案中失效，无法显示Emoji表情和symbol符号，
在0.14.3的是可以正常显示使用的。

而同样使用了opencc实现emoji表情和symbol的日语方案，却能正常显示Emoji表情。

Emoji表情的opencc 配置文件是这个库的：https://github.com/rime/rime-emoji
symbol符号的opencc 配置文件是使用四叶草拼音方案中，相关的opencc文件：https://github.com/fkxxyz/rime-symbols
![image](https://user-images.githubusercontent.com/69999980/200298781-2322e923-48c5-4abb-9d78-d60c5d27e621.png)

![image](https://user-images.githubusercontent.com/69999980/200298866-7a626bd7-199d-460f-b877-5b8dc0a0e274.png)

**Comment by fxliang** [comment]
可能是我带上的opencc文件和rime.dll的问题？这两个是直接复制的，如果有问题可以将旧的其中可用的文件移来使用即可。

**Comment by fxliang** [comment]
了解，我用回旧的版本应该就可以了，谢谢反馈~
