### ISSUE TITLE
0.14.3 dev 0.96新特性capture_type的一些不便

### ISSUE THREAD

**Issue by guixin233** [rime/weasel#796]
当我设置capture_type: candidates时，我发现它在我每一次上屏候选时都会截图到剪切板，这带来了一些不便。
或许可以添加一些按键控制是否当前需要截图，如上屏前按ctrl+c时，才截图候选，这样既满足了交流需要，也不会污染剪切板
![](https://s2.loli.net/2022/11/09/cPY5RXnqWMJx47l.png)

**Comment by fxliang** [comment]
> 当我设置capture_type: candidates时，我发现它在我每一次上屏候选时都会截图到剪切板，这带来了一些不便。 或许可以添加一些按键控制是否当前需要截图，如上屏前按ctrl+c时，才截图候选，这样既满足了交流需要，也不会污染剪切板 ![](https://camo.githubusercontent.com/2480ae9ea32709350d1c46a5dd5b6b71295abeb35e65a5a1f32e5bc01ca6d392/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f31312f30392f6350593552586e71574d4a7834376c2e706e67)



目前没有办法直接按键截图，但是可能提供一段ahk脚本快速修改这个选项
细节路径那些要自行调整


```ahk
If (A_Is64bitOS=1)
SetRegView, 64
If (A_Is64bitOS=0)
SetRegView, 32

if (A_Is64bitOS=1)
RegRead, weasel_root, HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Rime\Weasel, WeaselRoot
If (A_Is64bitOS=0)
RegRead, weasel_root, HKEY_LOCAL_MACHINE\SOFTWARE\Rime\Weasel, WeaselRoot
RegRead, rime_user_dir, HKEY_CURRENT_USER\SOFTWARE\Rime\Weasel, RimeUserDir

;msgbox %weasel_root%  %rime_user_dir%
deployer = %weasel_root%\WeaselDeployer.exe
;your sed path
sed = C:\Git\usr\bin\sed.exe
weasel_config = %rime_user_dir%\weasel.custom.yaml
;msgbox %deployer% %sed% %weasel_config%

F9::
{
	runwait, %sed% -i 's/capture_type:\s\+\w\+$/capture_type: highlighted/g' %weasel_config%
	runwait, %deployer% /deploy
	return
}
!F9::
{
	runwait, %sed% -i 's/capture_type:\s\+\w\+$/capture_type: none/g' %weasel_config%
	runwait, %deployer% /deploy
	return
}

```

**Comment by fxliang** [comment]
新修订已改为点击截图，欢迎尝试反馈
