### ISSUE TITLE
0.14.3 dev 0.96p1：仅输入大写字母时输入内容无法显示

### ISSUE THREAD

**Issue by Xenapte** [rime/weasel#798]
当 `style/color_font` 设为 `false` 时开启中文输入并尝试键入任意大写字母时屏幕上不显示字母，但按 Shift 键（我设置的是按下切换中英文输入时已输入内容自动上屏）后之前输入的大写字母能成功上屏。
![20221111010234](https://user-images.githubusercontent.com/17661805/201160290-4e42cadd-0e11-4db5-8c5b-0b9aef1265b2.png)
如图所示，按住 Shift 键并输入任意大写字母后屏幕上出现下划线（但 `inline_preedit` 为 `false`，本来就不应该直接上屏）和空输入框，但大写字母并未显示。
将 `color_font` 设置为 `true` 后尝试在相同条件下输入大写字母会导致当前使用的程序直接崩溃。

备注：系统上安装并启用了 MacType，不知道对此处是否有影响

**Comment by fxliang** [comment]
> 

style/color_font: false
style/inline_preedit: false
mactype 已安装运行
windows 10
未复现问题

----------------------------
style/color_font: false
![image](https://user-images.githubusercontent.com/4023160/201233415-3c775a1b-918f-4f6a-bffe-85fedc29ce80.png)
![image](https://user-images.githubusercontent.com/4023160/201233208-fbf0bdd1-4516-48cc-b93d-7806b2b347f8.png)

----------------------------
style/color_font: true
![image](https://user-images.githubusercontent.com/4023160/201233371-d92d6fba-62a5-4f90-96bd-7e6478dae860.png)

![image](https://user-images.githubusercontent.com/4023160/201233313-b9a00e47-25f9-4400-9ebe-dcec824ef4a2.png)

**Comment by Xenapte** [comment]
![2022-11-11 13-25-34-085](https://user-images.githubusercontent.com/17661805/201270018-eb06435c-b623-426b-98e0-0b925c117574.gif)
放在 Windows 沙盒内的环境下重新全新安装了一遍，不知为何默认设置仍然有类似问题

**Comment by fxliang** [comment]
试一下[这个](https://github.com/fxliang/weasel/releases/tag/0.14.3_dev_0.96p1)

**Comment by Xenapte** [comment]
> 试一下这个[weasel-0.14.3_patch_only-202211111142.zip](https://github.com/rime/weasel/files/9986320/weasel-0.14.3_patch_only-202211111142.zip)

仍然有上述问题

**Comment by fxliang** [comment]
> > 试一下这个[weasel-0.14.3_patch_only-202211111142.zip](https://github.com/rime/weasel/files/9986320/weasel-0.14.3_patch_only-202211111142.zip)
> 
> 仍然有上述问题

未能复现目前我也没有办法处理😂

**Comment by Xenapte** [comment]
这样就非常奇怪了，因为我用沙盒或者虚拟机里面进行全新安装后或者直接使用您的配置时（`fxliang/weasel_config`）都有一样的问题（即使不装 MacType 并且将系统编码设为 GBK，`inline_preedit` 为 `true` 时也一样）。

**Comment by Xenapte** [comment]
0.97p1 经测已没有此问题
