### ISSUE TITLE
0.14.3_dev_0.96p1 情况报告

### ISSUE THREAD

**Issue by ChihSee-Hsie** [rime/weasel#799]
首先感谢 fxliang 公孜孜不倦地维护这一项目。然而在这次更新中，我发现程序在只输入一个字符时可能不绘制候选框，情况如下：

![Untitled](https://user-images.githubusercontent.com/91021998/201253707-30dbe044-4333-4698-90dc-53143c8cd693.png)

我使用的是小鹤双拼方案，对应的输入码应该是「kai」，但此时候选框没有绘制出来。不过这种情况并不是每次都有，似乎在输入编码后不确认上屏而退格清空（有时输入出错是可能这样），然后重新输入编码，这时出现所述情况的概率比较大。此至　祝安！

**Comment by fxliang** [comment]
目前的隐藏窗体的基本前提是
1、inline_preedit and no candidates, and not show_tip mode( ascii swiching/half-full switching/simp-trad switching/error msg)
or
2、 margin negative(x or y) and not show_tip mode, and not schema menu mode.

随手GitHub上下了一个试了，未有复现问题。
可以试下附件这个包看看情况，这个主要是修了inline_preedit 时tip no shown的问题了。
[weasel-0.14.3_patch_only-202211111142.zip](https://github.com/rime/weasel/files/9986320/weasel-0.14.3_patch_only-202211111142.zip)

**Comment by ChihSee-Hsie** [comment]
感谢！目前看来上述问题解决了。另外之前还有一个问题忘了提到，是在切换简繁状态以及全半角状态时程序没有绘制状态图标，但您给出的补丁中这个问题也没有出现了。

**Comment by fxliang** [comment]
> 感谢！目前看来上述问题解决了。另外之前还有一个问题忘了提到，是在切换简繁状态以及全半角状态时程序没有绘制状态图标，但您给出的补丁中这个问题也没有出现了。

我刚给出的就是解决在inline_preedit设置为true时那个tips（简繁/中英/半全）不显示的问题的，之前没有发现这个问题，昨晚主要只是处理了那个崩溃的问题，后来早上自己用的时候发现就改了几行解决了的
