### ISSUE TITLE
WIN10 下启用 TSF 模式可能会导致“开始菜单”崩溃

### ISSUE THREAD

**Issue by KazamaSion** [rime/weasel#80]
系统：1607(14393.693)
![gif](https://cloud.githubusercontent.com/assets/13185633/22293229/cc05b086-e349-11e6-9f01-ae733da41ea2.gif)
注：这个过程可能需要一定时间，不会马上出现。但是中间一定会发生卡顿的情况。

也没有装MSE以外的杀毒软件（用其它比如 Google IME也不会出现这个问题），基本排除其它程序干扰可能。

**Comment by Prcuvu** [comment]
Duplicate of #13.
