### ISSUE TITLE
0.14.3_dev_0.96p1反馈

### ISSUE THREAD

**Issue by DreamAfar** [rime/weasel#800]
系统：windows 11 22H2 正式版
小狼毫：0.14.3_dev_0.96p1版本

weasel.custom.yaml的
style配置
![image](https://user-images.githubusercontent.com/69999980/201829419-6edd32fd-4496-4cba-bfb9-0c8c42f30ada.png)

bug1：竖向显示时，开启hilited_mark_color标记符号，会导致候选的圆角失效，并且显示会往左偏移。
![剪贴板图片 (3)](https://user-images.githubusercontent.com/69999980/201814864-827664a8-d480-46a1-8aa2-2b014469d9ad.jpg)

横向显示，圆角正常
![剪贴板图片 (2)](https://user-images.githubusercontent.com/69999980/201815060-047f7741-f5f8-48aa-87da-89e9b4e06d58.jpg)

不开启hilited_mark_color标记符号，竖向显示圆角正常
![剪贴板图片 (4)](https://user-images.githubusercontent.com/69999980/201815303-8c00562f-3a7e-4b1f-912e-a4a0f7a3c39b.jpg)

bug2：开启编码嵌入式显示时，有时不显示候选框。还有候选框很大概率会漂移到屏幕最左上角，当输入长度够长时又会回到输入焦点处，关闭编码嵌入式显示，会正常显示。
https://user-images.githubusercontent.com/69999980/201815803-21919cbd-f32b-4f5f-9cd3-86b391de5778.mp4

bug3：在windows 10和windows 11的任务栏的搜索栏输入，开启彩色Emoji 或 编码嵌入式显示，都会导致显示的性能下降，显示延迟严重，退格删除也是显示延迟严重，在其他界面输入显示延迟严重感知不大
目前我只试过096～96p1版本，都会有性能下降问题。

关闭彩色Emoji显示 和 不开启编码嵌入式显示，候选栏显示的性能正常，不会太大的延迟（跟系统输入差不到）
https://user-images.githubusercontent.com/69999980/201816450-10121dad-2bc9-4b0f-99d5-ebbbb53d0192.mp4

**Comment by fxliang** [comment]
try [this](https://github.com/fxliang/weasel/actions/runs/3469134877)

**Comment by fxliang** [comment]
> > try [this](https://github.com/fxliang/weasel/actions/runs/3469134877)
> > with librime [here](https://github.com/rime/librime/releases/download/1.7.3/rime-1.7.3-win32.zip)
> 
> 测试了会儿，没有出现 bug2 了
> 
> bug3 还是有，附带我的 bug3 情况：
> 
> 配置：
> 在chrome（地址栏，如下图）或者记事本等快速输入时就会出现卡顿。如下图
> 
> ![image](https://user-images.githubusercontent.com/25723505/201915305-39df87af-00e4-45e4-9af9-98e0d05c706b.png)
> 
> ![image](https://user-images.githubusercontent.com/25723505/201915140-e7ad88e3-aca6-440b-8727-1c932982fbfb.png)
> 
> 似乎是这个嵌入编码的蓝色背景导致，因为在不出现蓝色背景的编辑框里使用小狼毫快速输入时并不会卡顿，比如这个issue的回复框中以及vscode中。
> 
> ![image](https://user-images.githubusercontent.com/25723505/201917814-a930e627-14eb-4cb4-9f0a-1be77991d177.png)
> 
> 另外输入卡顿时，候选框还是会以正常速度出现响应，仅仅只是嵌入编码卡顿。没有找到相关调整嵌入编码背景色块的配置项。

那个部分不是小狼毫绘制的，是应用绘制，小狼毫只是提供了内容。这个部分我并没有改动。

**Comment by bemarkt** [comment]
> > > try [this](https://github.com/fxliang/weasel/actions/runs/3469134877)
> > > with librime [here](https://github.com/rime/librime/releases/download/1.7.3/rime-1.7.3-win32.zip)
> > 
> > 
> > 测试了会儿，没有出现 bug2 了
> > bug3 还是有，附带我的 bug3 情况：
> > 配置：
> > 在chrome（地址栏，如下图）或者记事本等快速输入时就会出现卡顿。如下图
> > ![image](https://user-images.githubusercontent.com/25723505/201915305-39df87af-00e4-45e4-9af9-98e0d05c706b.png)
> > ![image](https://user-images.githubusercontent.com/25723505/201915140-e7ad88e3-aca6-440b-8727-1c932982fbfb.png)
> > 似乎是这个嵌入编码的蓝色背景导致，因为在不出现蓝色背景的编辑框里使用小狼毫快速输入时并不会卡顿，比如这个issue的回复框中以及vscode中。
> > ![image](https://user-images.githubusercontent.com/25723505/201917814-a930e627-14eb-4cb4-9f0a-1be77991d177.png)
> > 另外输入卡顿时，候选框还是会以正常速度出现响应，仅仅只是嵌入编码卡顿。没有找到相关调整嵌入编码背景色块的配置项。
> 
> 那个部分不是小狼毫绘制的，是应用绘制，小狼毫只是提供了内容。这个部分我并没有改动。

明白了，但是为何在同一个输入框中，小狼毫和微软拼音会是两种不同的嵌入编码样式呢？

**Comment by fxliang** [comment]
同样的设置，你可以试试记事本等其他应用，响应又是不一样的。目前这个部分没有去深挖了解，可能是因为小狼毫要支持并击按键按下和升起都发了分别一次更新，然后应用更将响应慢了吧，当然只是猜测。

至于Bug2,这个似乎是长久以来的问题？反正我是没有遇到过，不论是旧版还是我修改的。今天下午尝试改了一个地方也许有机会解决，待你们这些有复现问题的用户测试反馈了。

bug1应该是修复完了，当然如果有其他细节可以再反馈。

谢谢~

**Comment by bemarkt** [comment]
> 同样的设置，你可以试试记事本等其他应用，响应又是不一样的。目前这个部分没有去深挖了解，可能是因为小狼毫要支持并击按键按下和升起都发了分别一次更新，然后应用更将响应慢了吧，当然只是猜测。
> 
> 至于Bug2,这个似乎是长久以来的问题？反正我是没有遇到过，不论是旧版还是我修改的。今天下午尝试改了一个地方也许有机会解决，待你们这些有复现问题的用户测试反馈了。
> 
> bug1应该是修复完了，当然如果有其他细节可以再反馈。
> 
> 谢谢~

就是在所有编辑栏的嵌入编码为带有蓝色背景时会响应慢，不带背景的嵌入编码就很快。不过问题不大，不太影响使用。

Bug2漂移的问题我只在更新[0.14.3_dev_0.96p1](https://github.com/fxliang/weasel/releases/tag/0.14.3_dev_0.96p1)后出现，在使用你发的ci版本后，已经没有复现了。

也非常感谢你能接手维护这个项目，让小狼毫重新能活跃起来！

**Comment by fxliang** [comment]
[0.14.3_dev_0.96p1](https://github.com/fxliang/weasel/releases/tag/0.14.3_dev_0.96p1)
是修崩临时发的

**Comment by DreamAfar** [comment]
> 试试[这个](https://github.com/fxliang/weasel/actions/runs/3469134877)
> 
> [在这里](https://github.com/rime/librime/releases/download/1.7.3/rime-1.7.3-win32.zip)有自由[](https://github.com/rime/librime/releases/download/1.7.3/rime-1.7.3-win32.zip)

今天测试了会儿，暂时没有出现 1和2的问题了，
bug3开启嵌入式显示响应还是有延迟，但比之前版本有所改善，会好一些。
开启彩色Emoji问题依旧，在系统搜索栏候选的显示响应延迟还是比较严重的，其他的地方正常，不影响使用。

非常感谢你能积极维护这个项目！希望小狼毫能越来越好。
