### ISSUE TITLE
0.14.3_dev_0.96p1 关于emoji的使用问题反馈

### ISSUE THREAD

**Issue by dyxang** [rime/weasel#801]
使用环境：Windows10 
使用方案：[四叶草拼音](https://github.com/SivanLaai/rime-pure/tree/master/schemes/Clover%E5%9B%9B%E5%8F%B6%E8%8D%89%E6%8B%BC%E9%9F%B3)
并对该方案无改动
用户文件夹下 `opencc` 文件夹[内容齐全](https://github.com/SivanLaai/rime-pure/tree/master/schemes/%E5%9F%BA%E7%A1%80%E6%96%87%E4%BB%B6)
在开启了符号和Emoji输入后，无法显示emoji候选符号，特殊符号也是
![D@N)}R%21@P4XK4$OD8ZULS](https://user-images.githubusercontent.com/36600710/202163642-2b53bfeb-5a61-46a4-85a1-b84230435dd3.png)

使用回 0.14.3 版本后显示正常 
![image](https://user-images.githubusercontent.com/36600710/202164702-d05ff448-8818-4cf0-af21-c09ba96ce601.png)

**Comment by fxliang** [comment]
看这个#795

**Comment by fxliang** [comment]
> > 看这个#795
> > 照着这个 issue 里，用 rime-with-plugins-1.7.3-win32.zip 里面的rime.dll 文件替换程序文件夹下的rime.dll 后，程序卡死，打不了字

因为librime没有重新编译，所以如果有opencc的问题应该换rime.dll就可以解决了

**Comment by fxliang** [comment]
> > > > 看这个#795
> > > > 照着这个 issue 里，用 rime-with-plugins-1.7.3-win32.zip 里面的rime.dll 文件替换程序文件夹下的rime.dll 后，程序卡死，打不了字
> > 
> > 
> > 因为librime没有重新编译，所以如果有opencc的问题应该换rime.dll就可以解决了
> 
> 所以是得等待dev更新吗？

使用你原来没有问题的那个rime.dll一般可以解决问题，opencc或者方案相关的内容并没有在我的改动范围里面的。

**Comment by fxliang** [comment]
这个版本是紧急修崩处事发现的，发布时使用的本地环境中的一些文件存在问题引起的。可以试ci里的新发布版，那个不会有问题

**Comment by fxliang** [comment]
> 找半天不知道CI里的新发布版下载在哪，现在把链接放在这给后来人看： [此次编译过程](https://github.com/fxliang/weasel/actions/runs/3494391551) 点击截图所示位置下载就是 ![image](https://user-images.githubusercontent.com/36600710/202629113-9635c568-56f7-4fb1-b76c-c42499f7f0c8.png)

就是下方这个artifact的压缩包，里面有一个安装包，如果不想使用安装包运行的方式可以使用压缩软件解压提取其中的文件手动批处理安装。当然安装包里面的数据文件建议也更新了
