### ISSUE TITLE
0.14.3_dev_0.97一打中文，程式就當掉

### ISSUE THREAD

**Issue by nijawang** [rime/weasel#802]
剛裝了0.14.3_dev_0.97，不過開了幾個程式打中文，發現只要一打中文程式就當掉。
是要打中文的程式當掉，不是weasel當掉；移除後再重裝回0.14.3_dev_0.96p1就正常。

OS: Win11 Pro 22H2 22621.819

**Comment by ChihSee-Hsie** [comment]
附议。在 Sublime Text 4 中键入中文时，新版本的响应速度显得有些卡顿，而一旦使用 Shift + Space 作全半角切换，输入法程序立刻自动退出，不再响应。此时编辑器也容易卡死。使用 release 中发布的 dev_0.96p1 则无此问题。

再次感谢 fxliang 公的维护！

**Comment by fxliang** [comment]
😂自己试了这么些天都没有试出来岂有此崩溃级bug。。。
方便的话贴下style配置我看看吧
看来很快又可以hotfix了

**Comment by ChihSee-Hsie** [comment]
[weasel_exg.txt](https://github.com/rime/weasel/files/10041211/weasel_exg.txt)

以上是 weasel.custom.yaml 的配置，隐去了一些无关的内容。这个设置在 0.96 与 0.97 之间没有改动。

**Comment by ChihSee-Hsie** [comment]
另外，昨天试用 [这一版本的 CI](https://github.com/fxliang/weasel/actions/runs/3489370325) 时在 Sublime Text 也出现了类似的问题。

**Comment by fxliang** [comment]
> 还有，rime.dll 在更新到 0.97 时也随之使用了安装包的新版本，此前更新时一直留着 [别处下载的版本（下载链接）](https://github.com/rime/librime/releases/download/1.7.3/rime-with-plugins-1.7.3-win32.zip) 没有替换（过滤 GBK 字符集的需要）——不过推测不是这个导致的，因为昨天试用 [这一版本的 CI](https://github.com/fxliang/weasel/actions/runs/3489370325) 时 rime.dll 同样是没有换过的，在 Sublime Text 也出现了类似的问题。

用你发出的设定试了，不论是我本地新编译构建的还是从github release下载的文件，在记事本测试正常，另外下载安装sublime text 4测试，全角半角切换等，一切都正常。

环境， i5 5200u, 16+128, windows 10 64bit自动更新的可能最新的patch。未见有明显的卡顿表现，毕竟我这台设备应该够多老旧的了，性能也行可够用。

是否已经确认安装正确？或者可以试下action 下同版本的CI文件。莫非我本地打包的文件还是有问题？

**Comment by ChihSee-Hsie** [comment]
退出算法服务——解安装——删注册表——重启——替换文件——安装——启动算法服务，这套流程应该是没有问题的。然而我方才发现不只是在 Sublime Text，在 Firefox 上一样存在切换全半角立刻自动退出的问题😰️。

[default_custom_yaml_exg.txt](https://github.com/rime/weasel/files/10041727/default_custom_yaml_exg.txt)

以上是有关的 default.custom.yaml，但只保留了小鹤双拼一种方案。

**Comment by fxliang** [comment]
为何你的default.custom.yaml这么复杂………………看的头大

[install.bat.txt](https://github.com/rime/weasel/files/10041764/install.bat.txt)

这个是我在用的批处理，注意32行和36行的目录设定适当修改成实际的路径

退出服务，覆盖，运行批处理，授权，选4，运行服务，新开的程序正常使用（旧的程序还会使用旧的session)

因我在调试时数据目录是和源代码同目录
weasel-src
        |
        |---------  output           #编译产出，对应weasel 应用目录
        |---------  data               #用户文件目录

**Comment by fxliang** [comment]
> 退出算法服务——解安装——删注册表——重启——替换文件——安装——启动算法服务，这套流程应该是没有问题的。然而我方才发现不只是在 Sublime Text，在 Firefox 上一样存在切换全半角立刻自动退出的问题😰️。
> 
> [default_custom_yaml_exg.txt](https://github.com/rime/weasel/files/10041727/default_custom_yaml_exg.txt)
> 
> 以上是有关的 default.custom.yaml，但只保留了小鹤双拼一种方案。

新增了参数 style/mark_text, 您是不是没有覆盖weasel.yaml？
试一下在patch里面添加这个设定看看，虽然按说不会有问题才是，毕竟那个参数程序内部默认是空字符串

**Comment by ChihSee-Hsie** [comment]
写入 mark_text: ""，没有明显改善。在 Firefox 中敲 Shift + Space，没有出现全半角转换的图标，输入字母，程序在一段时间不响应之后直接按英文键盘输出了，如同下图：

![Untitled](https://user-images.githubusercontent.com/91021998/202723907-9f8fd6ef-eb4b-40a0-bf8f-ef79c5b7c2a8.png)

使用小鹤双拼，输入字符实际上是「zheyangde」。在「就像」之后敲击 Shift + Space，程序一段时间不响应之后输出空格与输入码。

**Comment by fxliang** [comment]
@ChihSee-Hsie 
试了下，触发条件似乎是

color_font: false 加inline_preedit: false

**Comment by ChihSee-Hsie** [comment]
似乎只需要 color_font: false 就可以了，我的 inline_preedit 一直都是 true 的。

经过测试，将 color_font 调成 true 之后就没有问题，但这样输入法的响应速度还是有些慢，所以我一般都选择 false。

**Comment by fxliang** [comment]
@nijawang @ChihSee-Hsie 问题基本确认点了，看看[这个CI](https://github.com/fxliang/weasel/actions/runs/3503333988)的产出。

**Comment by ChihSee-Hsie** [comment]
问题目前没有出现了。感谢！

**Comment by nijawang** [comment]
裝了0.97p1後就正常了！
感謝fxliang！

ps: 不好意思這兩天比較忙，沒能回傳資訊…

**Comment by applearound** [comment]
> @nijawang @ChihSee-Hsie 问题基本确认点了，看看[这个CI](https://github.com/fxliang/weasel/actions/runs/3503333988)的产出。

0.97p1在我的机器上似乎仍有让前台程序当掉的问题，但是我目前暂时没有发现稳定触发的条件。
系统是Win11，配置采用的是小鹤音形默认的挂接配置。
我现在的感觉是，在部分游戏内，比较明显的是原神，使用win+space键切换语言时，容易触发使游戏直接崩溃退出。
但是这个触发并不稳定，不知道还需要提供什么额外信息。

**Comment by fxliang** [comment]
> > @nijawang @ChihSee-Hsie 问题基本确认点了，看看[这个CI](https://github.com/fxliang/weasel/actions/runs/3503333988)的产出。
> 
> 0.97p1在我的机器上似乎仍有让前台程序当掉的问题，但是我目前暂时没有发现稳定触发的条件。 系统是Win11，配置采用的是小鹤音形默认的挂接配置。 我现在的感觉是，在部分游戏内，比较明显的是原神，使用win+space键切换语言时，容易触发使游戏直接崩溃退出。 但是这个触发并不稳定，不知道还需要提供什么额外信息。

不好复现，那我也不知道可能怎么信息。不如就试新CI的情况看看有没有解决了。有时候原本只是为了让代码好看的修改会不小心改好了一些隐藏的问题的。。
试试[这个CI的产出](https://github.com/fxliang/weasel/actions/runs/3548319864)

**Comment by applearound** [comment]
> > > @nijawang @ChihSee-Hsie 问题基本确认点了，看看[这个CI](https://github.com/fxliang/weasel/actions/runs/3503333988)的产出。
> > 
> > 
> > 0.97p1在我的机器上似乎仍有让前台程序当掉的问题，但是我目前暂时没有发现稳定触发的条件。 系统是Win11，配置采用的是小鹤音形默认的挂接配置。 我现在的感觉是，在部分游戏内，比较明显的是原神，使用win+space键切换语言时，容易触发使游戏直接崩溃退出。 但是这个触发并不稳定，不知道还需要提供什么额外信息。
> 
> 不好复现，那我也不知道可能怎么信息。不如就试新CI的情况看看有没有解决了。有时候原本只是为了让代码好看的修改会不小心改好了一些隐藏的问题的。。 试试[这个CI的产出](https://github.com/fxliang/weasel/actions/runs/3548319864)

我试了试，感觉崩溃的次数是少了，但是就在我写这个反馈的前10分钟，它又崩溃了。

这次崩溃的情况是，使用Win+Space快捷键，从小狼毫切换到Win11英语语言默认的美式键盘的时候，触发了游戏的崩溃。
不知道小狼毫在进行这样的切换的时候会执行什么代码导致前台程序可能崩溃。
