### ISSUE TITLE
有機會提供 ARM64 版本嗎？

### ISSUE THREAD

**Issue by david50407** [rime/weasel#803]
更新： librime 已經原生支援 ARM64 了
https://github.com/rime/librime/pull/582

另外，我自己嘗試 build 的結果是我卡在不知道怎麼生出 installer 的地方，感覺只差最後一步

--
原標題： 有機會提供 ARM64EC 版本嗎？

微軟針對 ARM 機器提供了新的相容解決方案，可以由新的 ARM64EC PE 格式與 x64/ARM64EC 格式混合鏈接並執行在 Win11 ARM 平臺上，這個解決方案不要求全部的原始碼都編譯成 ARM64EC 而是可以保留 x64 部分從而減少初期 porting 的成本

加上最近 VS 也提供 ARM 原生支援了，ARM 機器應該會如雨後春筍般增加
~~（但其實是自肥，想在自己的 ARM 機器上看到清一色 ARM64 的程序）~~

ref: https://learn.microsoft.com/en-us/windows/arm/arm64ec

**Comment by driver1998** [comment]
试了一下，输入法不支持ARM64的话，在ARM64程序里根本就调不出来
起码TSF Client要支持ARM64

**Comment by david50407** [comment]
是的，所以 weasel 至少需要有 ARM64 的版本才能用

**Comment by driver1998** [comment]
看了一下，估计必须要将weasel.dll和weasel.ime编译成ARM64X文件（ARM64+x64混合二进制）才可以实现arm64和x64程序都能用
刚刚编译了个正常的arm64版本替换进了system32，然后x64程序就用不了了

**Comment by david50407** [comment]
其實我也不確定 ARM64X 到底能不能解決問題，但至少目前只用 ARM64 或 x64 是沒法解決問題的

**Comment by mio-19** [comment]
> 试了一下，输入法不支持ARM64的话，在ARM64程序里根本就调不出来 起码TSF Client要支持ARM64

得到了相同结果

**Comment by driver1998** [comment]
https://github.com/driver1998/weasel/releases/tag/v0.14.3-arm64-preview.1
https://github.com/rime/weasel/pull/836

可以试一下，11应该是没问题的，10我没机器测

**Comment by david50407** [comment]
@driver1998  這個版本在 win11 on arm64 的機器上可以正常運作

**Comment by FEI352** [comment]
> https://github.com/driver1998/weasel/releases/tag/v0.14.3-arm64-preview.1 #836
> 
> 可以试一下，11应该是没问题的，10我没机器测
> 
> ~emmm自己装了一下发现缺default.yml等几个文件，RIME初始化个人数据失败。如果新安装发现无法启动的话，先装主线的0.14.3，然后覆盖这个版本即可。 有时间我看一下缺的几个文件怎么补~
> 
> 更新：现在好了，重新到原发布页下载即可。

大佬可以更新这个arm版本的小狼毫吗？我发现这个版本的.lua不像新版的起作用。我用单单的倾心两笔延迟顶，在新版的Rime是可以正常使用的。http://error.ysepan.com/

**Comment by driver1998** [comment]
boost 1.83 有个bug在ARM上编译不过：https://github.com/boostorg/json/pull/928
1.84修了但我还没试

**Comment by ryanwuson** [comment]
> boost 1.83 有个bug在ARM上编译不过：[boostorg/json#928](https://github.com/boostorg/json/pull/928) 1.84修了但我还没试

请问可以更新 v0.15 arm64 版本吗？

**Comment by driver1998** [comment]
rebase 到目前master
https://github.com/driver1998/weasel/releases/tag/v0.15.0-arm64-preview.1

**Comment by driver1998** [comment]
PR已经合并，刚刚试了一下CI上最新的build，工作正常。
如无意外这个issue可以关了。

**Comment by lotem** [comment]
已由 https://github.com/rime/weasel/pull/836 完成。
