### ISSUE TITLE
weasel-0.14.3.97p1在windows 11 22H2输入问题（已解决）

### ISSUE THREAD

**Issue by hjfgt** [rime/weasel#805]
在windows 11 22H2安装weasel-0.14.3.97p1，使用https://github.com/fxliang/weasel_config配置，输入按空格上屏不是字符而是图形，选择序号上屏是字符，当输入时四码唯一可以正常字符上屏。是不是配置问题还bug？
<img width="594" alt="2022-11-22_202027" src="https://user-images.githubusercontent.com/3166855/203315995-48f1c098-3130-4142-8ee4-ce88da386132.png">

**Comment by fxliang** [comment]
style/capture_type: none

**Comment by hjfgt** [comment]
修改为style/capture_type: none后重新部署和重启电脑，输入第一个字正常，第二、三个字还是输入是图形了。
<img width="308" alt="2022-11-22_213248" src="https://user-images.githubusercontent.com/3166855/203331203-76c6c796-df82-420f-80aa-87fe0c9c2718.png">
<img width="594" alt="2022-11-22_214622" src="https://user-images.githubusercontent.com/3166855/203331245-b6a7b9e3-3f20-4931-9bc9-c85f2d0717be.png">

**Comment by fxliang** [comment]
截屏功能只是处理到剪贴板，未知你的应用是什么，我这边未测试到当设置为none时还有影响剪贴板人情况，也未发现异常（有测wps）

**Comment by hjfgt** [comment]
没有安装WPS，在EDGE、傲游浏览器、office 2021、记事本输入不正常，但在搜索能正常输入。
<img width="580" alt="2022-11-22_222002" src="https://user-images.githubusercontent.com/3166855/203338662-df8f30a0-6b42-4c55-ad88-5d8cb73d6d6f.png">

**Comment by fxliang** [comment]
> 没有安装WPS，在EDGE、傲游浏览器、office 2021、记事本输入不正常，但在搜索能正常输入。 <img alt="2022-11-22_222002" width="580" src="https://user-images.githubusercontent.com/3166855/203338662-df8f30a0-6b42-4c55-ad88-5d8cb73d6d6f.png">

删除weasel.custom.yaml配置重新部署看是否有问题。
可能，这个截图功能应该删掉吧😄

**Comment by hjfgt** [comment]
还是一样
<img width="593" alt="2022-11-22_224834" src="https://user-images.githubusercontent.com/3166855/203344494-125ddb55-2197-4128-bdfc-311995e4f09d.png">

**Comment by hjfgt** [comment]
找到原因了，是小狼毫助手造成的，退出小狼毫助手就正常。

**Comment by fxliang** [comment]
> 找到原因了，是小狼毫助手造成的，退出小狼毫助手就正常。

关闭issue即可

**Comment by rtransformation** [comment]
97p1这个版本号是从哪儿下的，我咋没看到呀

**Comment by spew8712** [comment]
https://github.com/fxliang/weasel/releases
這
