### ISSUE TITLE
weasel-0.14.3.97p1问题

### ISSUE THREAD

**Issue by rtransformation** [rime/weasel#806]
跟0.14.3问题一样，当只有一个候选的时候，选词框仍然很长，但0.14.3.97p1出了个新问题，0.14.3的背景色块没有那么长，只包裹了唯一侯选自己的那一块儿，现在0.14.3.97p1的背景色块更大了。
![屏幕截图 2022-11-24 091118](https://user-images.githubusercontent.com/11702676/203672627-6cfdd6a3-163b-4070-9a7a-e2d31467db66.png)

**Comment by fxliang** [comment]
> 跟0.14.3问题一样，当只有一个候选的时候，选词框仍然很长，但0.14.3.97p1出了个新问题，0.14.3的背景色块没有那么长，只包裹了唯一侯选自己的那一块儿，现在0.14.3.97p1的背景色块更大了。 ![屏幕截图 2022-11-24 091118](https://user-images.githubusercontent.com/11702676/203672627-6cfdd6a3-163b-4070-9a7a-e2d31467db66.png)

修改style/layout/min_width 这个参数，想尽量小就设成0吧

全框是因为比框一部分更协调

**Comment by rtransformation** [comment]
> 

原来是这个参数控制的呀，我一直没改过这个参数。。。
另外，我还有一个问题，就是设置皮肤颜色的时候，为什么设置的16进制颜色和实际呈现出来的颜色不一样，这个是bug吗，比如我设置的是蓝色，但是实际显示出来的颜色是黄色？

**Comment by fxliang** [comment]
> > 
> 
> 原来是这个参数控制的呀，我一直没改过这个参数。。。 另外，我还有一个问题，就是设置皮肤颜色的时候，为什么设置的16进制颜色和实际呈现出来的颜色不一样，这个是bug吗，比如我设置的是蓝色，但是实际显示出来的颜色是黄色？


颜色表示
0xaabbggrr
0xbbggrr   等效于0xffbbbggrr

**Comment by rtransformation** [comment]
> > > 
> > 
> > 
> > 原来是这个参数控制的呀，我一直没改过这个参数。。。 另外，我还有一个问题，就是设置皮肤颜色的时候，为什么设置的16进制颜色和实际呈现出来的颜色不一样，这个是bug吗，比如我设置的是蓝色，但是实际显示出来的颜色是黄色？
> 
> 颜色表示 0xaabbggrr 0xbbggrr 等效于0xffbbggrr

谢谢

**Comment by rtransformation** [comment]
> > > 
> > 
> > 
> > 原来是这个参数控制的呀，我一直没改过这个参数。。。 另外，我还有一个问题，就是设置皮肤颜色的时候，为什么设置的16进制颜色和实际呈现出来的颜色不一样，这个是bug吗，比如我设置的是蓝色，但是实际显示出来的颜色是黄色？
> 
> 颜色表示 0xaabbggrr 0xbbggrr 等效于0xffbbggrr

感觉还是不对呀，色彩选择器给的结果，设置以后变了颜色，还是没搞懂。
![屏幕截图 2022-11-24 145209](https://user-images.githubusercontent.com/11702676/203714156-673fa4cf-fa40-4dfa-b988-d03fb1d9da17.png)
![屏幕截图 2022-11-24 145231](https://user-images.githubusercontent.com/11702676/203714185-11ca3553-b052-4037-b387-ae0d7454514d.png)

**Comment by fxliang** [comment]
你取色器的是RGB顺序，weasel里面是BGR顺序。你取色的#fddb00在weasel里面应该写成0x00dbfd,如果要一半透明度则写成0x7f00dbfd

0xaabbggrr 这个再好好理解下是什么意思

**Comment by rtransformation** [comment]
> 

原来小狼毫里面是BGR这个顺序呀，知道这个信息就好了[捂脸]
