### ISSUE TITLE
天珩全字库的字体下沉比较多

### ISSUE THREAD

**Issue by rtransformation** [rime/weasel#807]
如图：
![image](https://user-images.githubusercontent.com/11702676/204010613-846f1e2b-18d8-4718-96d7-1a9da3001ed9.png)
这个怎么解决呢？

**Comment by fxliang** [comment]
只使用天珩字体一个字体

**Comment by Bobo-alcazar** [comment]
这个自己去调字体参数吧，很容易的。把升部髙和降部髙改一改。
