### ISSUE TITLE
Dev版本 卡键后无法切换中英

### ISSUE THREAD

**Issue by ls148478** [rime/weasel#810]
视频中的操作 间隔为10ms shift按下与弹起间隔 30ms
感觉输入法都有这个问题 不过在小狼毫里出现了 完全无法切换的情况发生
我尝试搜索了下相关问题 发现确实有这种情况存在 但无法解决我的问题
提出这个issues的原因也主要想明白这个是系统的问题 还是 输入法的问题

由于视频大小的原因 采取视频链接的方式
[视频](https://share.weiyun.com/GrtKLPH6)

**Comment by fxliang** [comment]
未明问题是什么。然后我的问题是你怎么做到这么高的手速…...如果要细查，可以fork代码在相关的位置插入写文件Log的行编译排查吧

**Comment by ls148478** [comment]
不是手速 是键盘驱动 我设置了相应的键 使其在按下某个键时触发 一些操作 所以比较快
我已找到具体问题 正在寻求答案 #454
