### ISSUE TITLE
版本0.14.3.97p1下关于候选框显示异常的bug反馈

### ISSUE THREAD

**Issue by swwrww** [rime/weasel#814]
环境：win11、win10，weasel-0.14.3.97p1版本加最新的rime-1.7.3的 rime.dll
方案上屏规则：
speller:
  auto_clear: max_length
  auto_select: true
  max_code_length: 4
  alphabet: "[;'zyxwvutsrqponmlkjihgfedcba]"
  auto_select_pattern: ^;\w+
在此规则下，4码满码出字后，由第五码顶字上屏，但第五码应该显示的候选字时而有候选出现，时而没有。在0.14.3下正常。望能修复此bug。佬辛苦了！
<img width="136" alt="image" src="https://user-images.githubusercontent.com/11620898/208025224-b289ad87-0910-4775-863d-f608d9ae9939.png">
<img width="102" alt="image" src="https://user-images.githubusercontent.com/11620898/208025582-f8bc43cf-dfe8-4740-a046-ce5ac0001166.png">

**Comment by swwrww** [comment]
https://user-images.githubusercontent.com/11620898/208025712-093d86b7-f7f8-40a1-9469-48272c6eb0e9.mp4

补上视频

**Comment by fxliang** [comment]
因为我使用的方案从未使用auto_select_pattern，暂未遇到类似问题
上传完整的方案文件，或者试试这个（替换&重新注册输入法&新开应用im测试）
[weasel-0.14.3.zip](https://github.com/rime/weasel/files/10243819/weasel-0.14.3.zip)

**Comment by swwrww** [comment]
> 因为我使用的方案从未使用auto_select_pattern，暂未遇到类似问题 上传完整的方案文件，或者试试这个（替换&重新注册输入法&新开应用im测试） [weasel-0.14.3.zip](https://github.com/rime/weasel/files/10243819/weasel-0.14.3.zip)

装上这个后，还是不行。候选框更是全黑了。以下是我用的形码的方案，劳烦佬看看这个是否属于bug。
[tiger-code.zip](https://github.com/rime/weasel/files/10244522/tiger-code.zip)

**Comment by fxliang** [comment]
> > 因为我使用的方案从未使用auto_select_pattern，暂未遇到类似问题 上传完整的方案文件，或者试试这个（替换&重新注册输入法&新开应用im测试） [weasel-0.14.3.zip](https://github.com/rime/weasel/files/10243819/weasel-0.14.3.zip)
> 
> 装上这个后，还是不行。候选框更是全黑了。以下是我用的形码的方案，劳烦佬看看这个是否属于bug。 [tiger-code.zip](https://github.com/rime/weasel/files/10244522/tiger-code.zip) 举个例子： 满码字 mbbb 爽， werw 瓷 ， 单字打法下： 正常打“爽的“ =”mbbbu_" 这个打到u时正常上屏了“爽”字，并在候选框显示了“的”。 ![A44YJKU6{N`MARHG@A5C27Y](https://user-images.githubusercontent.com/11620898/208070507-cbf95a02-2d94-4baa-819e-01e5ab71b01f.png)
> 
> 我单字打法要打“瓷器”=“werwdd_”这个就异常了， ![EJY `JOMCJEJD 6WU}U6NP](https://user-images.githubusercontent.com/11620898/208070740-dd5525a8-ac7f-4ec8-8ab1-d7d13a199b68.png)

未见异常，再细查一下你的设置？

刚上传的状态
![tiger_auto_test](https://user-images.githubusercontent.com/4023160/208076861-5d9ed913-9fbc-46a6-bfa4-8df2ff439c17.gif)
97p1
![tiger_97p1_auto_select](https://user-images.githubusercontent.com/4023160/208078409-1f6034f8-03e9-4c55-bda3-d77ec6e4a777.gif)

**Comment by r3n4ive** [comment]
我这边装上测试是调用“ctrl+`”切换菜单稳定触发。
版本：0.14.3_dev_0.97p1
![GIF 2022-12-16 23-31-46](https://user-images.githubusercontent.com/14960404/208133391-0c167e1e-89ab-4a00-a46f-d937e6e610d0.gif)
但不确定是小狼毫的问题还是方案配置文件的问题。

**Comment by r3n4ive** [comment]
单独用五笔+这五行speller未发现问题，应该不是这几行配置的问题。

**Comment by swwrww** [comment]
不知是否为自制字集滤镜引起，在第二字首字母带出的候选为唯一候选时就不出候选框了，但一样的配置在官版下没有任何问题。后作了个临时解决方案，给26个字母的一简字都加上了次选，都能正常出候选了。

**Comment by fxliang** [comment]
> 不知是否为自制字集滤镜引起，在第二字首字母带出的候选为唯一候选时就不出候选框了，但一样的配置在官版下没有任何问题。后作了个临时解决方案，给26个字母的一简字都加上了次选，都能正常出候选了。

如果这样试试page_size为1看看情况?

**Comment by fxliang** [comment]
这个在最新的构建分支里面应该有修复了，可以试试看是不是已经解决了

**Comment by swwrww** [comment]
> 这个在最新的构建分支里面应该有修复了，可以试试看是不是已经解决了

初步测试没有问题了。谢佬！
