### ISSUE TITLE
weasel 0.14.3_dev_0.98导致应用程序崩溃

### ISSUE THREAD

**Issue by llpub** [rime/weasel#815]
weasel 0.14.3_dev_0.98 (https://github.com/fxliang/weasel) crashed WORD2019/editplus for many times.
原来用0.14.3稳定版无此情况，但是在Word下偶尔候选框闪烁，于是干净卸载了老版本并安装0.14.3_dev_0.98，结果出现bug。
An example of Application Error log (Windows 10 企业版21H1):
```
错误应用程序名称: editplus.exe，版本: 5.4.3430.0，时间戳: 0x604acd84
错误模块名称: weasel.dll，版本: 0.0.0.0，时间戳: 0x63a037eb
异常代码: 0xc000041d
错误偏移量: 0x000000000001bf31
错误进程 ID: 0x12d4
错误应用程序启动时间: 0x01d9167385a60c22
错误应用程序路径: C:\Program Files\EditPlus\editplus.exe
错误模块路径: C:\Windows\system32\weasel.dll
报告 ID: d763467c-c0dd-4e6a-9c64-8da0f897d071
错误程序包全名: 
错误程序包相对应用程序 ID: 
```

**Comment by fxliang** [comment]
留意[最新CI构建](https://github.com/rime/weasel/actions/runs/5157548523) ， 麻烦确认下问题是否已解决😄

**Comment by determ1ne** [comment]
Closed as stale, reopen it if the problem still exists.

**Comment by llpub** [comment]
感谢各位开发者的付出，小狼毫0.15未再出现此问题
