### ISSUE TITLE
挂接 rime.lua 后，windows系统时间在每年 1 月份时，不能输入日期和时间

### ISSUE THREAD

**Issue by FisherfromCanton** [rime/weasel#817]
在小狼毫用户目录增加了 rime.lua 并相应地修改了有关配置文件后，到每年 1 月份（一般是在 20 日之前，下旬没问题。但具体日期也不是特别固定，不同年份一般差一两天），无法正常输入日期和时间，但过了 1 月份就好了。
其实，加入或设定的类似日期和时间的其它词条，也无法输入，过了1月份也就好了。
不知道这是rime.lua的问题，还是小狼毫本身的问题。
希望获得大侠们的帮助！

我也试了网上介绍的加入日期时间的一些rime.lua，都存在这个问题。

**Comment by lotem** [comment]
小狼毫裏面沒有這個文件呀。
要是網上尋來的腳本出了問題，還是聯繫一下作者爲好。
