### ISSUE TITLE
0.14.3_dev_0.98 在中文输入过程中切换中/英默认键盘状态会导致一些应用崩溃

### ISSUE THREAD

**Issue by Puxirepublic** [rime/weasel#819]
OS: WIndows 10

Firefox 108 下，在网页输入框中敲打中文时，如果频繁切换中英默认键盘状态会导致 Firefox 随机崩溃；甚至在 Firefox 地址栏里中文输入过程中反复切换中英键盘状态也有机率崩溃。

foobar2000 2.0 Beta 下，如果使用键盘快捷键是在中文输入法下执行的话，这时再切回英文默认键盘必导致 foobar2000 崩溃。

**Comment by fxliang** [comment]
收到，年后看看

**Comment by fxliang** [comment]
目前有复现在输入至少一个字符之后Ctrl+Space切换成英文，在一些应用下会引起应用崩溃，在记事本下表现为不能退格。
再查这个现象在weasel-0.14.3原始版本也是有的，似乎是composition状态下disable输入法后的  按键处理 异常，具体细节原因未明。应该不是我新修改的代码引入的问题。等奆佬查吧，那个不太了解

> OS: WIndows 10
> 
> Firefox 108 下，在网页输入框中敲打中文时，如果频繁切换中英默认键盘状态会导致 Firefox 随机崩溃；甚至在 Firefox 地址栏里中文输入过程中反复切换中英键盘状态也有机率崩溃。
> 
> foobar2000 2.0 Beta 下，如果使用键盘快捷键是在中文输入法下执行的话，这时再切回英文默认键盘必导致 foobar2000 崩溃。

**Comment by fxliang** [comment]
@ryanlo713 @Puxirepublic 留意[最新CI构建](https://github.com/rime/weasel/actions/runs/5157548523) ，这个问题应该已经解决了 via #892 
麻烦确认下

**Comment by Puxirepublic** [comment]
@fxliang, 刚更新测试了下，目前没再出现任何崩溃。太棒了，这个最膈应的陈年 bug 终于修复了！
