### ISSUE TITLE
TFS模式下，Word中存在汉字上屏之后消失的情况

### ISSUE THREAD

**Issue by toiiggww** [rime/weasel#82]
如题，录屏：[http://wx2.sinaimg.cn/mw1024/3d262bb6gy1fc9uyxpa9gg20ly063gqf.gif](url)
输入法版本：weasel-0.9.30
似乎仅Word中出现，PPT用得少不知道，Excel里面似乎没碰到过

**Comment by nameoverflow** [comment]
已由 #146 修复。
