### ISSUE TITLE
可否考虑更新librime-lua版本

### ISSUE THREAD

**Issue by siuze** [rime/weasel#821]
[librime-lua](https://github.com/hchunhui/librime-lua)近期的更新中增加了lua插件自载机制，可以通过在配置文件中使用“*”引入外来模块，不需要额外改动rime.lua来require模块。

![https://github.com/hchunhui/librime-lua/wiki/Scripting](https://user-images.githubusercontent.com/54578647/213361446-97a2f3a9-1110-435c-9812-1d0c67a8a37b.png)

https://github.com/hchunhui/librime-lua/pull/189

https://github.com/hchunhui/librime-lua/pull/158

经过测试，使用项目[Actions](https://github.com/hchunhui/librime-lua/actions)下的最新构件替换到@fxliang 所维护[小狼毫v0.14.3_dev_0.98](https://github.com/fxliang/weasel/releases/tag/0.14.3_dev_0.98)的rime.dll文件后该功能方可正常生效。

**Comment by fxliang** [comment]
目前上传的包是我正常在用的带lua插件的rime.dll，但是没有去追新到hchunhui/librime-lua下的最新产出，毕竟新产出未必稳定，而且也没有稳定的release下载链接。


> [librime-lua](https://github.com/hchunhui/librime-lua)近期的更新中增加了lua插件自载机制，可以通过在配置文件中使用“*”引入外来模块，不需要额外改动rime.lua来require模块。
> 
> ![https://github.com/hchunhui/librime-lua/wiki/Scripting](https://user-images.githubusercontent.com/54578647/213361446-97a2f3a9-1110-435c-9812-1d0c67a8a37b.png)
> 
> [hchunhui/librime-lua#189](https://github.com/hchunhui/librime-lua/pull/189)
> 
> [hchunhui/librime-lua#158](https://github.com/hchunhui/librime-lua/pull/158)
> 
> 经过测试，使用项目[Actions](https://github.com/hchunhui/librime-lua/actions)下的最新构件替换到@fxliang 所维护[小狼毫v0.14.3_dev_0.98](https://github.com/fxliang/weasel/releases/tag/0.14.3_dev_0.98)的rime.dll文件后该功能方可正常生效。

**Comment by fxliang** [comment]
> [librime-lua](https://github.com/hchunhui/librime-lua)近期的更新中增加了lua插件自载机制，可以通过在配置文件中使用“*”引入外来模块，不需要额外改动rime.lua来require模块。
> 
> ![https://github.com/hchunhui/librime-lua/wiki/Scripting](https://user-images.githubusercontent.com/54578647/213361446-97a2f3a9-1110-435c-9812-1d0c67a8a37b.png)
> 
> [hchunhui/librime-lua#189](https://github.com/hchunhui/librime-lua/pull/189)
> 
> [hchunhui/librime-lua#158](https://github.com/hchunhui/librime-lua/pull/158)
> 
> 经过测试，使用项目[Actions](https://github.com/hchunhui/librime-lua/actions)下的最新构件替换到@fxliang 所维护[小狼毫v0.14.3_dev_0.98](https://github.com/fxliang/weasel/releases/tag/0.14.3_dev_0.98)的rime.dll文件后该功能方可正常生效。

留意这个 action build 产出，已经使用最新librime 版本1.8.5，经测已带lua
