### ISSUE TITLE
小狼毫在不同的視窗不用一樣的方案 | Weasel uses different input schemes for different windows

### ISSUE THREAD

**Issue by leafpool243** [rime/weasel#822]
（不好意思，我中文講得不太好，希望我寫得通。）

切換輸入方案只在一個視窗裡改掉，在其他視窗還是繼續用之前的方案。

假如說我開了兩個視窗，記事本和 Chrome。我現在在用的方案是拼音。我在 Chrome 用 Ctrl+\` 把方案改成注音。如果我回到記事本，小狼毫就繼續用拼音。

請問能不能改掉這個設定。我不想要小狼毫在不同的視窗用不同的方案。

<hr>

Changing input schemes in one window doesn't change it for other windows.

For example, let's say I am using the Pinyin scheme. If I have two windows open: Notepad and Chrome, and I change the scheme to Zhuyin in Chrome with Ctrl+\`, when I go back to Notepad, Weasel still uses the Pinyin scheme.

Is there a way to change this setting? I don't want Weasel to use different schemes in different windows.

**Comment by lotem** [comment]
關聯到相同問題 https://github.com/rime/weasel/issues/454

**Comment by fxliang** [comment]
不同应用session的状态在不同的session中维护，或者只使用一个方案是解法。
