### ISSUE TITLE
小狼毫0.14.3與Blender不兼容

### ISSUE THREAD

**Issue by fengwusan** [rime/weasel#825]
windows 10
Blender 3.4
小狼毫0.14.3，五筆•簡入繁出
最近使用小狼毫為我的默認輸入法，在Blender裏，開始沒有問題，可是只要產生輸入操作，Blender快捷鍵就失效，切換英文環境也沒用。

**Comment by lingchuanbo** [comment]
小狼毫1.5版本也有此问题！

**Comment by fxliang** [comment]
至于提到的快捷键无效的情况，实际是blender的问题吗？我试过微软的输入法，只要有激活输入框（在输入框点击光标闪烁），也是会表现出来快捷键失效的情况的. 要点击输入框以外的位置消除输入框的激活状态就可以正常了。请核对情况 @fengwusan 

没有vs2022，但是Azuk在用的就是vs2022,如果他在vs2022中无法输入那肯定走不到release这一步的，麻烦再细确认其他影响情况。@yulinxx

blender确认是可以输入中文的
![image](https://github.com/rime/weasel/assets/4023160/bcace616-9ee5-48a8-a01a-dcd142715e8a)

**Comment by mirtlecn** [comment]
这问题好多软件都有，几个版本都是，特别是改了配置，重新部署后，就会偶发候选框全部消失。

表现有能打字但没候选框，或者不能打字

重新部署几次，切到别的输入法再切回来就莫名奇妙好了

所以才会出现有的人碰到过，一些人没碰到，一开始行，一会又不行了。只有长期用某个软件才能有明显感觉

似乎 electron 这类比较明显
