### ISSUE TITLE
Cannot deploy customized scheme in weasel 

### ISSUE THREAD

**Issue by hk3f** [rime/weasel#829]
Environment:
Windows10 19045.2486 Chinese Simplified version
Weasel: 0.14.3
Scheme: japanese customized version based on https://github.com/gkovacs/rime-japanese
Bug:
When using dictionary including japanese.mozc.dict.yaml, deployer crashed without useful bug report or log.
While this scheme worked fine in archlinux ibus rime:
ibus-rime: 1.5.0-1
librime: 1.7.3-15
[rime.weasel.log.zip](https://github.com/rime/weasel/files/10674436/rime.weasel.log.zip)
Scheme:
[rime-japanese-cust3.zip](https://github.com/rime/weasel/files/10674447/rime-japanese-cust3.zip)

**Comment by fxliang** [comment]
that's librime 32bit dll OOM issue

with #1006 solve this problem, 

or 


    [rimedeployerx64.zip](https://github.com/rime/weasel/files/12496136/rimedeployerx64.zip)
    这个里面的文件丢到算法服务目录里面，运行rimedeployerx64.exe就可以部署大词库了，不用另外复制粘贴文件了

_Originally posted by @fxliang in https://github.com/rime/weasel/issues/953#issuecomment-1702396237_
