### ISSUE TITLE
如果可以暴露一些API来让其它软件控制rime就好了

### ISSUE THREAD

**Issue by landao314** [rime/weasel#83]
比如打开，关闭，切换输入法等。典型应用是用vim时模式切换时，vim通过API控制rime。

**Comment by nameoverflow** [comment]
VIM 可以在系统层面关闭输入法 https://github.com/vim/vim/blob/master/src/glbl_ime.cpp

**Comment by elxy** [comment]
这个需求还是存在的，比如WSL中的程序无法调用WIN32 API，SSH服务端的程序也无法调用本地的API。

**Comment by Prcuvu** [comment]
> 比如WSL中的程序无法调用WIN32 API，SSH服务端的程序也无法调用本地的API

这是无法解决的。因为 Linux tty 原生只支持键盘布局而不支持输入法，WSL 和 SSH 也没有传递并控制输入法状态的机制。

**Comment by elxy** [comment]
> 这是无法解决的。因为 Linux tty 原生只支持键盘布局而不支持输入法，WSL 和 SSH 也没有传递并控制输入法状态的机制。

是的，所以可以考虑RPC或者REST来调用API。不过weasel似乎是利用Input Method Manager来管理程序的输入法状态，不能直接控制某个程序内的输入法状态，只能进行全局的设置。

**Comment by elxy** [comment]
用取巧的办法实现了Windows下WSL里vim自动切换输入法的逻辑。
首先加入美式键盘布局，并设置快捷键用于切换输入法，如下图所示：
![hot_keys_for_IME.png](https://i.loli.net/2020/01/21/OXC6MY7qp3ZmbgS.png)
然后编译一个Windows命令行程序，用于发送快捷键以切换输入法：
```c++
#include <iostream>

#include <Windows.h>
#include <Winuser.h>

int send_keys(int size, WORD vks[])
{
    INPUT *input = new INPUT[2 * size];

    memset(input, 0, 2 * size * sizeof(INPUT));
    for (int i = 0; i < size; i++) {
        input[i].type = INPUT_KEYBOARD;
        input[i].ki.wVk = vks[i];
        input[i + size].type = INPUT_KEYBOARD;
        input[i + size].ki.wVk = vks[i];
        input[i + size].ki.dwFlags = KEYEVENTF_KEYUP;
    }
    ::SendInput(2 * size, input, sizeof(INPUT));

    delete[] input;
    return 0;
}

int main(int argc, char **argv)
{
    WORD switchENG[3] = {VK_CONTROL, VK_SHIFT, '8'};
    WORD switchCHN[3] = {VK_CONTROL, VK_SHIFT, '9'};
    WORD switchIME[2] = {VK_LMENU, VK_SHIFT};

    if (argc > 1) {
        if ((strcmp(argv[1], "en") == 0) ||
            (strcmp(argv[1], "eng") == 0)) {
            std::cout << "Switch to English IME\n";
            return send_keys(sizeof(switchENG) / sizeof(WORD), switchENG);
        } else if ((strcmp(argv[1], "cn") == 0) ||
            (strcmp(argv[1], "chn") == 0)) {
            std::cout << "Switch to Chinese IME\n";
            return send_keys(sizeof(switchCHN) / sizeof(WORD), switchCHN);
        }
    }
    std::cout << "Toggle IME\n";
    return send_keys(sizeof(switchIME) / sizeof(WORD), switchIME);
}
```
将编译好的程序(switchIME.exe)放在`PATH`环境下，同时修改`.vimrc`：
```vim
if executable("fcitx") || executable("switchIME.exe")
  if executable("fcitx")
    let g:ime2en_cmd = "fcitx-remote -c"
    let g:ime2cn_cmd = "fcitx-remote -o"
  else
    let g:ime2en_cmd = "switchIME.exe en"
    let g:ime2cn_cmd = "switchIME.exe cn"
  endif

  " 设置输入法为英文模式
  function! IME2en()
    if executable("fcitx")
      let s:input_status = system("fcitx-remote")
    else
      let s:input_status = 2
    endif
    if s:input_status == 2
      let g:input_toggle = 1
      let l:a = system(g:ime2en_cmd)
    endif
  endfunction

  " 设置输入法为中文模式
    function! IME2zh()
    if exists("g:input_toggle") == 1
      if g:input_toggle == 1
        let l:a = system(g:ime2cn_cmd)
        let g:input_toggle = 0
      endif
    endif
  endfunction

  autocmd InsertLeave * call IME2en()
  autocmd InsertEnter * call IME2zh()
endif
```
然后就像Linux下一样自动切换输入法了~

**Comment by liang-0131** [comment]
> 用取巧的办法实现了Windows下WSL里vim自动切换输入法的逻辑。 首先加入美式键盘布局，并设置快捷键用于切换输入法，注意避免快捷键冲突，如下图所示： ![hot_keys_for_IME.png](https://camo.githubusercontent.com/19e02c7659b0f439556ef8f37cda784926c3727ddbf9b636e5a9c8361c90519e/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30312f32312f4f5843364d59377170335a6d6267532e706e67) 然后编译一个Windows命令行程序，用于发送快捷键以切换输入法：
> 
> ```c++
> #include <iostream>
> 
> #include <Windows.h>
> #include <Winuser.h>
> 
> int send_keys(int size, WORD vks[])
> {
>     INPUT *input = new INPUT[2 * size];
> 
>     memset(input, 0, 2 * size * sizeof(INPUT));
>     for (int i = 0; i < size; i++) {
>         input[i].type = INPUT_KEYBOARD;
>         input[i].ki.wVk = vks[i];
>         input[i + size].type = INPUT_KEYBOARD;
>         input[i + size].ki.wVk = vks[i];
>         input[i + size].ki.dwFlags = KEYEVENTF_KEYUP;
>     }
>     ::SendInput(2 * size, input, sizeof(INPUT));
> 
>     delete[] input;
>     return 0;
> }
> 
> int main(int argc, char **argv)
> {
>     WORD switchENG[3] = {VK_CONTROL, VK_SHIFT, '8'};
>     WORD switchCHN[3] = {VK_CONTROL, VK_SHIFT, '9'};
>     WORD switchIME[2] = {VK_LMENU, VK_SHIFT};
> 
>     if (argc > 1) {
>         if ((strcmp(argv[1], "en") == 0) ||
>             (strcmp(argv[1], "eng") == 0)) {
>             std::cout << "Switch to English IME\n";
>             return send_keys(sizeof(switchENG) / sizeof(WORD), switchENG);
>         } else if ((strcmp(argv[1], "cn") == 0) ||
>             (strcmp(argv[1], "chn") == 0)) {
>             std::cout << "Switch to Chinese IME\n";
>             return send_keys(sizeof(switchCHN) / sizeof(WORD), switchCHN);
>         }
>     }
>     std::cout << "Toggle IME\n";
>     return send_keys(sizeof(switchIME) / sizeof(WORD), switchIME);
> }
> ```
> 
> 将编译好的程序(switchIME.exe)放在`PATH`环境下，同时修改`.vimrc`：
> 
> ```viml
> if executable("fcitx") || executable("switchIME.exe")
>   if executable("fcitx")
>     let g:ime2en_cmd = "fcitx-remote -c"
>     let g:ime2cn_cmd = "fcitx-remote -o"
>   else
>     let g:ime2en_cmd = "switchIME.exe en"
>     let g:ime2cn_cmd = "switchIME.exe cn"
>   endif
> 
>   " 设置输入法为英文模式
>   function! IME2en()
>     if executable("fcitx")
>       let s:input_status = system("fcitx-remote")
>     else
>       let s:input_status = 2
>     endif
>     if s:input_status == 2
>       let g:input_toggle = 1
>       let l:a = system(g:ime2en_cmd)
>     endif
>   endfunction
> 
>   " 设置输入法为中文模式
>     function! IME2zh()
>     if exists("g:input_toggle") == 1
>       if g:input_toggle == 1
>         let l:a = system(g:ime2cn_cmd)
>         let g:input_toggle = 0
>       endif
>     endif
>   endfunction
> 
>   autocmd InsertLeave * call IME2en()
>   autocmd InsertEnter * call IME2zh()
> endif
> ```
> 
> 然后就像Linux下一样自动切换输入法了~

请问有编译好的switchIME.exe么？

**Comment by liang-0131** [comment]
> 用取巧的办法实现了Windows下WSL里vim自动切换输入法的逻辑。 首先加入美式键盘布局，并设置快捷键用于切换输入法，注意避免快捷键冲突，如下图所示： ![hot_keys_for_IME.png](https://camo.githubusercontent.com/19e02c7659b0f439556ef8f37cda784926c3727ddbf9b636e5a9c8361c90519e/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30312f32312f4f5843364d59377170335a6d6267532e706e67) 然后编译一个Windows命令行程序，用于发送快捷键以切换输入法：
> 
> ```c++
> #include <iostream>
> 
> #include <Windows.h>
> #include <Winuser.h>
> 
> int send_keys(int size, WORD vks[])
> {
>     INPUT *input = new INPUT[2 * size];
> 
>     memset(input, 0, 2 * size * sizeof(INPUT));
>     for (int i = 0; i < size; i++) {
>         input[i].type = INPUT_KEYBOARD;
>         input[i].ki.wVk = vks[i];
>         input[i + size].type = INPUT_KEYBOARD;
>         input[i + size].ki.wVk = vks[i];
>         input[i + size].ki.dwFlags = KEYEVENTF_KEYUP;
>     }
>     ::SendInput(2 * size, input, sizeof(INPUT));
> 
>     delete[] input;
>     return 0;
> }
> 
> int main(int argc, char **argv)
> {
>     WORD switchENG[3] = {VK_CONTROL, VK_SHIFT, '8'};
>     WORD switchCHN[3] = {VK_CONTROL, VK_SHIFT, '9'};
>     WORD switchIME[2] = {VK_LMENU, VK_SHIFT};
> 
>     if (argc > 1) {
>         if ((strcmp(argv[1], "en") == 0) ||
>             (strcmp(argv[1], "eng") == 0)) {
>             std::cout << "Switch to English IME\n";
>             return send_keys(sizeof(switchENG) / sizeof(WORD), switchENG);
>         } else if ((strcmp(argv[1], "cn") == 0) ||
>             (strcmp(argv[1], "chn") == 0)) {
>             std::cout << "Switch to Chinese IME\n";
>             return send_keys(sizeof(switchCHN) / sizeof(WORD), switchCHN);
>         }
>     }
>     std::cout << "Toggle IME\n";
>     return send_keys(sizeof(switchIME) / sizeof(WORD), switchIME);
> }
> ```
> 
> 将编译好的程序(switchIME.exe)放在`PATH`环境下，同时修改`.vimrc`：
> 
> ```viml
> if executable("fcitx") || executable("switchIME.exe")
>   if executable("fcitx")
>     let g:ime2en_cmd = "fcitx-remote -c"
>     let g:ime2cn_cmd = "fcitx-remote -o"
>   else
>     let g:ime2en_cmd = "switchIME.exe en"
>     let g:ime2cn_cmd = "switchIME.exe cn"
>   endif
> 
>   " 设置输入法为英文模式
>   function! IME2en()
>     if executable("fcitx")
>       let s:input_status = system("fcitx-remote")
>     else
>       let s:input_status = 2
>     endif
>     if s:input_status == 2
>       let g:input_toggle = 1
>       let l:a = system(g:ime2en_cmd)
>     endif
>   endfunction
> 
>   " 设置输入法为中文模式
>     function! IME2zh()
>     if exists("g:input_toggle") == 1
>       if g:input_toggle == 1
>         let l:a = system(g:ime2cn_cmd)
>         let g:input_toggle = 0
>       endif
>     endif
>   endfunction
> 
>   autocmd InsertLeave * call IME2en()
>   autocmd InsertEnter * call IME2zh()
> endif
> ```
> 
> 然后就像Linux下一样自动切换输入法了~

在WSL2下无效是怎么回事？

**Comment by elxy** [comment]
> 在WSL2下无效是怎么回事？

可以试试这个，不用快捷键触发，直接用Windows的API切换键盘布局：

```c
#include <iostream>

#include <windows.h>
#include <winuser.h>

int GetWindowsKeyboardLayout(const HWND hwnd) {
    HKL hkl;
    DWORD tid = GetWindowThreadProcessId(hwnd, NULL);
    hkl = GetKeyboardLayout(tid);
    return reinterpret_cast<intptr_t>(hkl) & 0xFFFF;
}

int main(int argc, char **argv) {
    const int US_HKL = 0x0409;
    const int ZH_HKL = 0x0804;
    HWND hwnd = GetForegroundWindow();

    if (argc > 1) {
        if ((strcmp(argv[1], "en") == 0) || (strcmp(argv[1], "eng") == 0) ||
            (strcmp(argv[1], "off") == 0)) {
            std::cout << "Switch to English IME\n";
            return SendMessage(hwnd, WM_INPUTLANGCHANGEREQUEST, 0, US_HKL);
        } else if ((strcmp(argv[1], "cn") == 0) ||
                   (strcmp(argv[1], "chn") == 0) ||
                   (strcmp(argv[1], "on") == 0)) {
            std::cout << "Switch to Chinese IME\n";
            return SendMessage(hwnd, WM_INPUTLANGCHANGEREQUEST, 0, ZH_HKL);
        } else if (strcmp(argv[1], "query") == 0) {
            int hkl = GetWindowsKeyboardLayout(hwnd);
            if (hkl == ZH_HKL) {
                std::cout << "Current window's input layout is 0x" << std::hex
                          << hkl << " (Chinese)" << std::endl;
                return 2;
            } else if (hkl == 0) {
                std::cout << "Cannot get input layout of current window"
                          << std::endl;
                return 0;
            } else {
                std::cout << "Current window's input layout is 0x" << std::hex
                          << hkl << " (English)" << std::endl;
                return 1;
            }
        }
    }
    std::cout << "Toggle IME\n";
    return SendMessage(hwnd, WM_INPUTLANGCHANGEREQUEST, INPUTLANGCHANGE_FORWARD,
                       0);
}
```

**Comment by liang-0131** [comment]
@elxy 谢谢。WSL2下可以用

**Comment by fxliang** [comment]
#1047 vim_mode done
#1113 ascii mode control by command line
