### ISSUE TITLE
小狼毫的用戶資料同步功能不復制rime.lua和lua文件夾

### ISSUE THREAD

**Issue by wakin20** [rime/weasel#831]
![QQ图片20230209132817](https://user-images.githubusercontent.com/59874098/217726836-388c58de-a703-45f1-91d5-60b1f0085394.png)
這兩个重要的文件（夹）不能備份話，這個功能真是形同虛設了。

**Comment by yanhuacuo** [comment]
lua文件及 lua 目录，是最近才有的，所以以前的设计没有覆盖到这里。
暂时可以使用「中州韵98五笔助手」：

- [pic](https://raw.githubusercontent.com/yanhuacuo/css/master/pic/2023-03-10_130252.png)

**Comment by mirtlecn** [comment]
这个 sync 的逻辑是 librime 那边做的，前端们都是这个行为，目前只能手动复制或者借助第三方工具了
