### ISSUE TITLE
任务栏输入指示图标或这任务栏托盘图标是否可以自定义

### ISSUE THREAD

**Issue by qwert-f** [rime/weasel#832]
两者都是显示输入模式的中英文，无法显示当前所使用的输入方案

**Comment by qwert-f** [comment]
差不多，我知道有个fork的大佬项目有这个，但是不确定官方是否有

**Comment by qwert-f** [comment]
> 类似这样？
> ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)

谢谢回复。差不多，我知道有个fork的大佬项目有这个，但是不确定官方是否有

**Comment by pdog18** [comment]
> 类似这样？ ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif) [ ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif) ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif) [ ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)

你的 branch 有这功能吗？

**Comment by fxliang** [comment]
> > 类似这样？ ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> >       
> >         [
> >           
> >             ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> >           
> >         ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> >         
> >        [ ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif) ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> >       
> >         [
> >           
> >             ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> >           
> >         ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> 
> 你的 branch 有这功能吗？

如图，有的

**Comment by pdog18** [comment]
> > > 类似这样？ ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >       
> > >         [
> > >           
> > >         
> > >             ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >           ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >         
> > >       
> > > ```
> > >     [
> > >       
> > >         ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >       
> > >     ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >     
> > >    [ ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif) ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >   
> > >     [
> > >       
> > >         ![图片](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >       
> > >     ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > >     
> > >    [ ](https://user-images.githubusercontent.com/4023160/208444318-8b3fbbf6-d1fe-4546-a4f6-d4a8b6221977.gif)
> > > ```
> > 
> > 
> > 你的 branch 有这功能吗？
> 
> 如图，有的

您的分支已经在许多提交上超越了 rime 主分支，并引入了大量新特性。但我未能找到关于这些新增特性的说明，是否有相关文档可供参考？
只因：[有需要文档的原因](https://github.com/pdog18/rime-soak/discussions/4)

**Comment by fxliang** [comment]
release page

**Comment by fxliang** [comment]
新修订中已可通过方案下设定schema/icon和schema/ascii_icon定义采用的ico图标文件
见#882
![enicon](https://github.com/rime/weasel/assets/4023160/82ab854c-20e7-41af-8505-1bbd9f309011)
