### ISSUE TITLE
Win11，覆盖安装0.14.3-dev-0.98后无法打开【输入法设定】和【重新部署】

### ISSUE THREAD

**Issue by Howard-Zhou-77** [rime/weasel#834]
原本是装的稳定版0.14.3，由于需要打生僻字装上了0.14.3-dev-0.98，重启之后打字正常，但【输入法设定】和【重新部署】无反应
装回稳定版后将weasel.custom.yaml按dev版的格式修改加入fallback和圆角输入框内容后再次覆盖安装dev，样式正常，但【输入法设定】和【重新部署】仍然无反应。

**Comment by fxliang** [comment]
已修复
