### ISSUE TITLE
rime文档-个人版

### ISSUE THREAD

**Issue by limaofu** [rime/weasel#839]
https://limaofu.github.io/t3doc/Rime%E4%B8%AD%E5%B7%9E%E9%9F%BB%E8%BE%93%E5%85%A5%E6%B3%95%E9%85%8D%E7%BD%AE%E6%89%8B%E5%86%8C-back-0901.docx

**Comment by determ1ne** [comment]
可以在 [Discussion 版块](https://github.com/rime/home/discussions)讨论非 bug 修复以及亟待实现的新功能等一般话题
