### ISSUE TITLE
切换到小狼毫输入法导致其他应用程序未响应

### ISSUE THREAD

**Issue by Epilepsy-YDF** [rime/weasel#84]
Win10，安装小狼毫输入法之后每次切换到小狼毫想要输入字符的时候应用程序（比如Notepad）都会卡住，是怎么回事？

**Comment by Epilepsy-YDF** [comment]
我现在只能进安全模式卸载小狼毫才能正常使用电脑……烦

**Comment by Prcuvu** [comment]
无法重现这个问题。

**Comment by lotem** [comment]
目前只支持 Windows XP、Windows 7。
Windows 10 可能不兼容。有問題就先不要用了。
