### ISSUE TITLE
好奇问下有没整合chatgpt的计划

### ISSUE THREAD

**Issue by Jackiexiao** [rime/weasel#840]
我没有使用过此项目，但期望将chatgpt整合到输入法中

**Comment by baoang** [comment]
继而chatgpt可以从用户的输入收集更多的信息以针对性的发展出更细致的智能？
集成的话，翻了墙、干净IP，以及一个至少非中国的电话号码才能用，那这个输入法可就肿了。

**Comment by Oyami-Srk** [comment]
你可以使用Lua插件来实现这种功能，不难，十分简单。

**Comment by rainzee** [comment]
非常愚蠢的一个想法
