### ISSUE TITLE
WeaselDeployer 大约支持多大规模的部署？

### ISSUE THREAD

**Issue by ChihSee-Hsie** [rime/weasel#841]
如题，我尝试着部署大约 60 MB 的词典文件，并将其分成六份，每份大约 10 MB。在部署时我发现最多可以将其中五份的内容部署完成，但再增加就会卡死。打开任务管理器，发现 WeaselDeployer 在此时的内存占用快速增长，到大约 1,200,000 KB 时程序退出运行。然而如果部署的词典大小在 50 MB 左右，WeaselDeployer 占用的内存最多可以达到 1,700,000 KB，仍然完成部署。我考虑 WeaselDeployer 可能有内存限制，特此来询问。如果能有解答，我在这里预先表示感激。

我的系统配置是 Windows 11 22H2 build 22621.1413，RAM 容量 16 GB。此至，祝安！

**Comment by ASC8384** [comment]
80MB的词典文件，[fxliang](https://github.com/fxliang)的最新版本，32GB内存无法部署。
日志里一直有：
```
a work thread is already running
```

**Comment by Techince** [comment]
> 80MB的词典文件，[fxliang](https://github.com/fxliang)的最新版本，32GB内存无法部署。 日志里一直有：
> 
> ```
> a work thread is already running
> ```
可以试试64位版本，如果还存在这个问题，估计就是对词典大小有限制。

**Comment by ASC8384** [comment]
> > 80MB的词典文件，[fxliang](https://github.com/fxliang)的最新版本，32GB内存无法部署。 日志里一直有：
> > ```
> > a work thread is already running
> > ```
> 
> 可以试试64位版本，如果还存在这个问题，估计就是对词典大小有限制。

发现把`use_preset_vocabulary`设置成 false 可以部署，但是设置成 true还是不行。

版本是[fxliang](https://github.com/rime/weasel/actions/runs/5749772543)最近的 PR，里面没有 64 位版本。看 @Techince 您 release 了一个 [64 位的版本](https://github.com/Techince/weasel/releases)，但 commit 似乎与现在的差距过大，不知道该如何选择了。

**Comment by Techince** [comment]
> 不知道该如何选择了。

我的本地代码基本上跟着Fxliang做的，由于64位与32位不兼容的地方比较多，自动同步会有较多的冲突，网上的源码只增加一些个人添加的代码。Release包是本地编译上传的。

**Comment by ASC8384** [comment]
> > 不知道该如何选择了。
> 
> 我的本地代码基本上跟着Fxliang做的，由于64位与32位不兼容的地方比较多，自动同步会有较多的冲突，网上的源码只增加一些个人添加的代码。Release包是本地编译上传的。

也就是说，[action](https://github.com/Techince/weasel/actions/runs/5777186198)里的资源包并非[release](https://github.com/Techince/weasel/releases)的版本？

不知道您是否打算提PR:smile:

**Comment by Techince** [comment]
PR会有比较多的冲突，对于公共部分，我修改的代码会通过QQ告知fxliang的。目前官方还没计划升级到64位。

**Comment by Techince** [comment]
> > > 不知道该如何选择了。
> > 
> > 
> > 我的本地代码基本上跟着Fxliang做的，由于64位与32位不兼容的地方比较多，自动同步会有较多的冲突，网上的源码只增加一些个人添加的代码。Release包是本地编译上传的。
> 
> 也就是说，[action](https://github.com/Techince/weasel/actions/runs/5777186198)里的资源包并非[release](https://github.com/Techince/weasel/releases)的版本？
> 
> 不知道您是否打算提PR😄

PR会有比较多的冲突，对于公共部分，我修改的代码会通过QQ告知fxliang的。目前官方还没计划升级到64位。

**Comment by fxliang** [comment]
[rimedeployer_win.zip](https://github.com/rime/weasel/files/12289854/rimedeployer_win.zip)


提供个玩具，不负责任，哈哈

**Comment by ASC8384** [comment]
> [rimedeployer_win.zip](https://github.com/rime/weasel/files/12289854/rimedeployer_win.zip)
> 
> 提供个玩具，不负责任，哈哈

请问这个是不是会把`default.custom.yaml`重置了呀

**Comment by fxliang** [comment]
> > [rimedeployer_win.zip](https://github.com/rime/weasel/files/12289854/rimedeployer_win.zip)
> > 提供个玩具，不负责任，哈哈
> 
> 请问这个是不是会把`default.custom.yaml`重置了呀

这个目标是外部部署，只看词典产出就好

**Comment by ASC8384** [comment]
> > > [rimedeployer_win.zip](https://github.com/rime/weasel/files/12289854/rimedeployer_win.zip)
> > > 提供个玩具，不负责任，哈哈
> > 
> > 
> > 请问这个是不是会把`default.custom.yaml`重置了呀
> 
> 这个目标是外部部署，只看词典产出就好

可以使用，非常感谢

**Comment by ChihSee-Hsie** [comment]
> > > [rimedeployer_win.zip](https://github.com/rime/weasel/files/12289854/rimedeployer_win.zip)
> > > 提供个玩具，不负责任，哈哈
> > 
> > 
> > 请问这个是不是会把`default.custom.yaml`重置了呀
> 
> 这个目标是外部部署，只看词典产出就好

感谢提供这样一个工具。在实际使用中，x64 的 deployer 编译出了 prism、table、bin 三个文件，但复制到 build 文件夹后，开启对应方案时会自动重新编译，结果程序仍然卡死，而三个词典文件中 prism 被删除了（应该是意图重新编译 prism，但不能成功的结果）。

**Comment by fxliang** [comment]
[rimedeployer_win.zip](https://github.com/rime/weasel/files/12297571/rimedeployer_win.zip)
之前随手整的没考虑完整，这个如果user目录下有default.yaml的话是不会覆写的，将小狼毫的共享数据复制到shared/下，用户目录的内容放user目录下，再部署看看，我试了一下没有问题了
