### ISSUE TITLE
weasel 0.14.3_new_features win11 无法使用

### ISSUE THREAD

**Issue by expoli** [rime/weasel#843]
所使用的版本：[0.14.3_new_features](https://github.com/fxliang/weasel/releases/tag/0.14.3_new_features)
- 出现的问题：
- 只要在应用程序中调出小狼毫输入法，那么这个应用程序就会直接崩溃（比如微信，资源管理器等）。

- 系统版本信息
OS 名称:          Microsoft Windows 11 专业版
OS 版本:          10.0.22621 暂缺 Build 22621
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎3/‎1
操作系统版本	22621.1413

**Comment by fxliang** [comment]
试试
[这个](https://github.com/fxliang/weasel/actions/runs/4459109786) 看有没有解决

**Comment by SkyBird233** [comment]
> 试试 [这个](https://github.com/fxliang/weasel/actions/runs/4459109786) 看有没有解决

遇到相同问题，尝试此版本后已解决
