### ISSUE TITLE
请问source code怎么用

### ISSUE THREAD

**Issue by jiezi506** [rime/weasel#845]
fxliang大佬的更新releases都是source code，没有exe
还有说“后续应该不太会怎么做release,直接在github action下更新吧”

小白请问一下怎么用，是要自己编译exe文件么，不怎么会

**Comment by lakent** [comment]
> 后续应该不太会怎么做release,直接在github action下更新吧
你可以在[他的 gitHub action](https://github.com/fxliang/weasel/actions) 页面找到每次的 ci，点击进入其中的一个，比如[这个](https://github.com/fxliang/weasel/actions/runs/4499946727)，拉到最下面有个，Artifacts 栏目，下载其中的 zip 文件即可。
![image](https://user-images.githubusercontent.com/22787048/227378620-c0fec144-a7b5-4f23-8dc7-d68afa25b5ef.png)
