### ISSUE TITLE
Windows下自定义profile folder以后，安装插件还是会下载到AppData下面

### ISSUE THREAD

**Issue by fallenwood** [rime/weasel#847]
1. 安装时候选择自定义用户资料文件夹到 C:\RimeData
2. 輸入法設定->獲取更多輸入方案->double-pinyin
3. 發現double pinyin相關的yaml存放在Appdata\Roaming\Rime下面，而且rime沒有讀取到
4. 把Appdata\Roaming\Rime的內容複製到C:\RimeData, rime讀取到了double pinyin的配置

感覺應該是個bug

**Comment by lotem** [comment]
可以支持這種用法，不過需要額外的配置。
這是因爲配置管理器和輸入法是作爲獨立的兩個程序開發的，技術所限，沒有把這項設置自動關聯起來。

需要爲配置管理器定義 `rime_dir`：
https://github.com/rime/plum/blob/6f502ff6fa87789847fa18200415318e705bffa4/rime-install-config.bat#L15

參考：
https://github.com/rime/plum#advanced-usage

**Comment by lotem** [comment]
可以支持這種用法，不過需要額外的配置。
這是因爲配置管理器和輸入法是作爲獨立的兩個程序開發的，技術所限，沒有把這項設置自動關聯起來。

需要爲配置管理器定義 `rime_dir`：
https://github.com/rime/plum/blob/6f502ff6fa87789847fa18200415318e705bffa4/rime-install-config.bat#L15

參考：
https://github.com/rime/plum#advanced-usage
