### ISSUE TITLE
fxliang的新版本小狼毫在哪里下载？

### ISSUE THREAD

**Issue by rtransformation** [rime/weasel#848]
如题，找了半天没找到

**Comment by zhyoch** [comment]
https://github.com/fxliang/weasel/releases

**Comment by rtransformation** [comment]
> https://github.com/fxliang/weasel/releases
> 
> fxliang说：
> 
> > 后续应该不太会怎么做 release , 直接在 github action 下更新吧
> 
> https://github.com/fxliang/weasel/actions

![image](https://user-images.githubusercontent.com/11702676/230712498-a4a71a4b-a2fe-40c9-a94d-ea61ab8127cc.png)
这个下载的地方点不了，下载不到
