### ISSUE TITLE
如何设置两次空格才上字（智能ABC模式）

### ISSUE THREAD

**Issue by crackxia** [rime/weasel#853]
如图
![GIF 2023-4-12 10-50-15](https://user-images.githubusercontent.com/516438/231335711-fc19bd58-9925-4ce6-b491-49495e0763ad.gif)
一直找不到这个设置

**Comment by wxyzh** [comment]
第一次空格：查字典？
第二次空格：最前面的候选上屏？

**Comment by crackxia** [comment]
> 第一次空格：查字典？ 第二次空格：最前面的候选上屏？

对，整个完整过程需要按两次空格，这是当年用智能ABC养成的习惯，20多年了，一直改不掉

**Comment by mokapsing** [comment]
也许用lua可以实现通过按键触发translator，但我觉得这种打字方式太奇葩了，没有动力去写这种脚本

**Comment by mokapsing** [comment]
拆中一下，用fluid_editor替换express_editor

**Comment by crackxia** [comment]
> 拆中一下，用fluid_editor替换express_editor

有没有详细点的介绍，感谢

**Comment by sgcell** [comment]
speller:
  use_space: true

**Comment by SSazanami** [comment]
智能ABC因为数字键同时用做选字和笔形键，所以必须要先按一次空格在输拼音和选候选之间切换吧
