### ISSUE TITLE
fxliang 的构建版本，切换中英文键盘后皮肤会变成默认

### ISSUE THREAD

**Issue by quantumfallout** [rime/weasel#854]
系统Windows 11 22H2 内部版本22621.1555
Weasel 使用的是 Commit [3248752](https://github.com/fxliang/weasel/commit/3248752198c4d9f29804b93720c8b78de3e53519)的自动构建版本。

在使用Win+空格切换键盘之后，皮肤会回到程序文件夹里 weasel.yaml 的默认值（我这里深色模式默认是lost temple)，而非appdata里面weasel.custom.yaml中的设定值。

**Comment by fxliang** [comment]
浅色和深色下都试了一下，暂未复现问题

**Comment by quantumfallout** [comment]
在Windows Sandbox(22621.1555)中测试了一下，浅色模式没有问题，只有深色模式会回到lost temple

**Comment by Lloydqiu** [comment]
同此问题，不管设置什么皮肤都会变成lost temple

**Comment by fxliang** [comment]
贴配置吧

**Comment by quantumfallout** [comment]
配置是默认生成的配置。

**Comment by Lloydqiu** [comment]
我是默认配置，只是在设置里选择了其他皮肤。当时可以用，然后切换窗口后就变成了lost temple

**Comment by Lloydqiu** [comment]
> 配置是默认生成的配置。
> 
> default.custom.yaml
> 
> ```
> patch:
>   schema_list:
>     - {schema: luna_pinyin_simp}
>     - {schema: luna_pinyin}
> ```
> 
> weasel.custom.yaml
> 
> ```
> patch:
>   "style/color_scheme": ps4
> ```
> 
> edit2: 临时解决方案 weasel.custom.yaml的`patch`部分添加`"style/color_scheme_dark": ps4`

我试试你这个，另外如果要横向该怎么写？

**Comment by quantumfallout** [comment]
> > 配置是默认生成的配置。
> > default.custom.yaml
> > ```
> > patch:
> >   schema_list:
> >     - {schema: luna_pinyin_simp}
> >     - {schema: luna_pinyin}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > weasel.custom.yaml
> > ```
> > patch:
> >   "style/color_scheme": ps4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > edit2: 临时解决方案 weasel.custom.yaml的`patch`部分添加`"style/color_scheme_dark": ps4`
> 
> 我试试你这个，另外如果要横向该怎么写？

`patch`部分添加`"style/horizontal": true`

**Comment by fxliang** [comment]
删除程序目录里面的weasel.yaml中的color_scheme_dark行，解决。
