### ISSUE TITLE
只有在光标存在时才能按shift切换中英文,能否实现光标不存在也可切换

### ISSUE THREAD

**Issue by zhifuchen** [rime/weasel#858]
weasel的所有快捷键都需要把光标放到输入框里"激活"输入法后才起作用,能不能让快捷键全局有效,这样会更方便

**Comment by ghsgz** [comment]
并不会更方便。中英文状态方便与否，主要看两个场景：使用单字母快捷键；输入另一种语言。前者如果扰人，应该考虑添加yaml配置，指定目标应用的初始输入法状态；后者，本来就应该在输入时根据情况切换，没有理由提前切换。

**Comment by ls148478** [comment]
> 并不会更方便。中英文状态方便与否，主要看两个场景：使用单字母快捷键；输入另一种语言。前者如果扰人，应该考虑添加yaml配置，指定目标应用的初始输入法状态；后者，本来就应该在输入时根据情况切换，没有理由提前切换。

请问一下 Windows也有这个功能吗 在yaml中配置指定应用初始输入法状态 可否提供一下 我只找到mac版本的支持此功能

**Comment by determ1ne** [comment]
> > 并不会更方便。中英文状态方便与否，主要看两个场景：使用单字母快捷键；输入另一种语言。前者如果扰人，应该考虑添加yaml配置，指定目标应用的初始输入法状态；后者，本来就应该在输入时根据情况切换，没有理由提前切换。
> 
> 请问一下 Windows也有这个功能吗 在yaml中配置指定应用初始输入法状态 可否提供一下 我只找到mac版本的支持此功能

是不是说的 #856 这种？

**Comment by ls148478** [comment]
> > > 并不会更方便。中英文状态方便与否，主要看两个场景：使用单字母快捷键；输入另一种语言。前者如果扰人，应该考虑添加yaml配置，指定目标应用的初始输入法状态；后者，本来就应该在输入时根据情况切换，没有理由提前切换。
> > 
> > 
> > 请问一下 Windows也有这个功能吗 在yaml中配置指定应用初始输入法状态 可否提供一下 我只找到mac版本的支持此功能
> 
> 是不是说的 #856 这种？

感谢解答

**Comment by determ1ne** [comment]
> > > > 并不会更方便。中英文状态方便与否，主要看两个场景：使用单字母快捷键；输入另一种语言。前者如果扰人，应该考虑添加yaml配置，指定目标应用的初始输入法状态；后者，本来就应该在输入时根据情况切换，没有理由提前切换。
> > > 
> > > 
> > > 请问一下 Windows也有这个功能吗 在yaml中配置指定应用初始输入法状态 可否提供一下 我只找到mac版本的支持此功能
> > 
> > 
> > 是不是说的 #856 这种？
> 
> 感谢解答

之后会把这个 PR merge 掉

**Comment by fxliang** [comment]
global_ascii已实现
