### ISSUE TITLE
鼠标悬停2s左右无点击会自动选中鼠标停留的词语

### ISSUE THREAD

**Issue by daomiren** [rime/weasel#861]
fxliang发布的最新的小狼毫出现了如题所述的问题，之前都没有，4月19号的版本开始出现的。
系统：Win11 22621.1555 64位

**Comment by QianmuZ** [comment]
还是希望能够提供关闭鼠标选择的能力，由于输入框跟鼠标离的很近，经常出现自动选择的情况

**Comment by augor** [comment]
同样问题，希望为鼠标停留自动选中功能提供一个开关。
鼠标点击自动截图功能没有必要，希望同样设置一个开关

**Comment by fxliang** [comment]
这个有预编译指令 USE_MOUSE_EVENTS 可以控制使用鼠标事件或者禁用鼠标事件，增加参数似乎有点把事情做复杂了，所以之前将这个参数删除了。
[这里](https://github.com/fxliang/weasel/blob/master/include/WeaselCommon.h#L15)

**Comment by fxliang** [comment]
最新提交已默认关闭鼠标悬停响应，只保留了点击和滚轮响应。
