### ISSUE TITLE
在wezterm下不能工作

### ISSUE THREAD

**Issue by BarryArch** [rime/weasel#863]
在其他应用正常使用，但切换到wezterm应用后，中英切换无响应，只能输入英文，输入法不工作。

**Comment by Techince** [comment]
https://github.com/Techince/weasel/releases/download/weasel-0.15.0.0_x64/weasel-0.15.0.0-installer_x64.exe
试下这个版本看能否正常输入，代码里补了几个注册类别。

**Comment by elxy** [comment]
> https://github.com/Techince/weasel/releases/download/weasel-0.15.0.0_x64/weasel-0.15.0.0-installer_x64.exe 试下这个版本看能否正常输入，代码里补了几个注册类别。

依然不行

**Comment by Techince** [comment]
> 在 VisualStudio 2022 也是一样, 用了 0.14 0.15,均無法输入中文
> 
> 切换到别的输入法,再切换回来,方可输入中文, 但每次要这样才能输入, 也是非常麻烦

目前已知问题是有些应用启动时会同时加载两个输入法模块，可以把「System32」和「Windows\SysWOW64」两目录下的「weasel.ime」加个扩展名屏蔽一下试试。

**Comment by Techince** [comment]
> > https://github.com/Techince/weasel/releases/download/weasel-0.15.0.0_x64/weasel-0.15.0.0-installer_x64.exe 试下这个版本看能否正常输入，代码里补了几个注册类别。
> 
> 依然不行，而且Firefox地址栏无法输入了

我测试了0.14.3增加注册类别后可以输入，但0.15.0却没反应。听determ1ne说是需要关闭图形加速才能输入。

**Comment by elxy** [comment]
> > 在 VisualStudio 2022 也是一样, 用了 0.14 0.15,均無法输入中文
> > 切换到别的输入法,再切换回来,方可输入中文, 但每次要这样才能输入, 也是非常麻烦
> 
> 目前已知问题是有些应用启动时会同时加载两个输入法模块，可以把「System32」和「Windows\SysWOW64」两目录下的「weasel.ime」加个扩展名屏蔽一下试试。

唔，wezterm试了下还是无法输入，需要我们做什么，能帮忙定位问题呢？

**Comment by elxy** [comment]
> > > https://github.com/Techince/weasel/releases/download/weasel-0.15.0.0_x64/weasel-0.15.0.0-installer_x64.exe 试下这个版本看能否正常输入，代码里补了几个注册类别。
> > 
> > 
> > 依然不行，而且Firefox地址栏无法输入了
> 
> 我测试了0.14.3增加注册类别后可以输入，但0.15.0却没反应。听determ1ne说是需要关闭图形加速才能输入。

受这里的启发，修改wezterm的front_end = 'Software'，改用CPU渲染后，可以用weasel输入了。

**Comment by elxy** [comment]
> > > > https://github.com/Techince/weasel/releases/download/weasel-0.15.0.0_x64/weasel-0.15.0.0-installer_x64.exe 试下这个版本看能否正常输入，代码里补了几个注册类别。
> > > 
> > > 
> > > 依然不行，而且Firefox地址栏无法输入了
> > 
> > 
> > 我测试了0.14.3增加注册类别后可以输入，但0.15.0却没反应。听determ1ne说是需要关闭图形加速才能输入。
> 
> 受这里的启发，修改wezterm的front_end = 'Software'，改用CPU渲染后，可以用weasel输入了。

不过渲染速度下降好多，界面能察觉到延迟。看起来weasel尚不能很好地支持GPU加速的GUI？

**Comment by Techince** [comment]
> > > > > https://github.com/Techince/weasel/releases/download/weasel-0.15.0.0_x64/weasel-0.15.0.0-installer_x64.exe 试下这个版本看能否正常输入，代码里补了几个注册类别。
> > > > 
> > > > 
> > > > 依然不行，而且Firefox地址栏无法输入了
> > > 
> > > 
> > > 我测试了0.14.3增加注册类别后可以输入，但0.15.0却没反应。听determ1ne说是需要关闭图形加速才能输入。
> > 
> > 
> > 受这里的启发，修改wezterm的front_end = 'Software'，改用CPU渲染后，可以用weasel输入了。
> 
> 不过渲染速度下降好多，界面能察觉到延迟。看起来weasel尚不能很好地支持GPU加速的GUI？

新的候选输出采用了direct2d绘制的。

**Comment by Techince** [comment]
https://github.com/Techince/weasel/releases/tag/weasel-0.15.0.0_x64

查到原因了，试下这个版本。TSF模块初始化失败引起的。

**Comment by elxy** [comment]
> https://github.com/Techince/weasel/releases/tag/weasel-0.15.0.0_x64
> 
> 查到原因了，试下这个版本。TSF模块初始化失败引起的。

可以了，感谢！

**Comment by elxy** [comment]
But I can't input in Firefox...

**Comment by elxy** [comment]
> > https://github.com/Techince/weasel/releases/tag/weasel-0.15.0.0_x64
> > 查到原因了，试下这个版本。TSF模块初始化失败引起的。
> 
> 刚装上是可以的，但重启后又无法输入了。重启后Weasel也无法在Firefox和企业微信中输入。。。

重启下小狼毫服务就好了

**Comment by elxy** [comment]
> > > https://github.com/Techince/weasel/releases/tag/weasel-0.15.0.0_x64
> > > 查到原因了，试下这个版本。TSF模块初始化失败引起的。
> > 
> > 
> > 刚装上是可以的，但重启后又无法输入了。重启后Weasel也无法在Firefox和企业微信中输入。。。
> 
> 重启下小狼毫服务就好了

这个版本有个问题，就是系统重启后无法输入，需要手动重启小狼毫服务。

**Comment by Techince** [comment]
> > > > https://github.com/Techince/weasel/releases/tag/weasel-0.15.0.0_x64
> > > > 查到原因了，试下这个版本。TSF模块初始化失败引起的。
> > > 
> > > 
> > > 刚装上是可以的，但重启后又无法输入了。重启后Weasel也无法在Firefox和企业微信中输入。。。
> > 
> > 
> > 重启下小狼毫服务就好了
> 
> 这个版本有个问题，就是系统重启后无法输入，需要手动重启小狼毫服务。

查下注册表，是不是32位的启动信息和64位的启动信息都存在。
「计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run」64位
「计算机\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run」32位
任务管理器里也要看下「小狼毫算法服务」启动项有没有被禁用。

**Comment by determ1ne** [comment]
fixed by #937

**Comment by Parsifa1** [comment]
无法使用中文输入法
![image](https://github.com/rime/weasel/assets/31800073/80ad87c9-f601-466c-91ca-8d8129001e08)
![image](https://github.com/rime/weasel/assets/31800073/ea466d79-9f92-4558-a756-a4c85f5b77b0)
当处于wezterm时，无法正常中英文切换，且右下角一直为中文， 但是只能输出英文

**Comment by Techince** [comment]
@Parsifa1 
试试这个吧。
https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.0-installer_x64.exe
以前修复过这个问题。后来发现小狼毫的按键处理逻辑在暴雪公司的游戏里会丢字符，改了下逻辑，适合绝大多数应用，只有这一个Wezterm例外，今天把它又修复了一下。安装包里加入了这个虎码方案，文件体积大了一点。

**Comment by elxy** [comment]
> @Parsifa1 试试这个吧。 https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.0-installer_x64.exe 以前修复过这个问题。后来发现小狼毫的按键处理逻辑在暴雪公司的游戏里会丢字符，改了下逻辑，适合绝大多数应用，只有这一个Wezterm例外，今天把它又修复了一下。安装包里加入了这个虎码方案，文件体积大了一点。

试了下这个版本，用中文输入会导致Wezterm崩溃：

```
16:51:51.575  ERROR  env_bootstrap > panic at window\src\os\windows\window.rs:1514:31 - !?
   0: git_tag_tagger
   1: git_tag_tagger
   2: <unknown>
   3: git_tree_entry_filemode_raw
   4: git_tree_entry_filemode_raw
   5: git_tree_entry_filemode_raw
   6: git_tree_entry_filemode_raw
   7: git_midx_writer_new
   8: git_midx_writer_new
   9: git_tag_tagger
  10: git_tag_tagger
  11: git_tag_tagger
  12: git_tag_tagger
  13: DispatchMessageW
  14: CallWindowProcW
  15: wglSwapBuffers
  16: DispatchMessageW
  17: DispatchMessageW
  18: TranslateAcceleratorW
  19: KiUserCallbackDispatcher
  20: NtUserSetWindowPos
  21: boost::archive::detail::iserializer<boost::archive::text_wiarchive,weasel::UIStyle>::load_object_data
  22: boost::archive::detail::iserializer<boost::archive::text_wiarchive,weasel::UIStyle>::load_object_data
  23: boost::archive::detail::iserializer<boost::archive::text_wiarchive,weasel::UIStyle>::load_object_data
  24: boost::archive::detail::iserializer<boost::archive::text_wiarchive,weasel::UIStyle>::load_object_data
  25: AtlThunk_AllocateData
  26: DispatchMessageW
  27: DispatchMessageW
  28: CallNextHookEx
  29: KiUserCallbackDispatcher
  30: NtUserCreateWindowEx
  31: CreateWindowExW
  32: CreateWindowExW
  33: CreateWindowExW
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: TextInputServerCreate
  38: TextInputServerCreate
  39: TsfOneCreate
  40: <unknown>
  41: CtfImeSelectEx
  42: tsfGetKeyState
  43: tsfGetKeyState
  44: tsfGetKeyState
  45: <unknown>
  46: TF_UninitSystem
  47: TF_CreateThreadMgr
  48: CtfImeProcessCicHotkey
  49: CtfImeSelectEx
  50: TF_SetShowFloatingStatus
  51: TF_SetShowFloatingStatus
  52: ImmTranslateMessage
  53: GetWindowTextLengthA
  54: git_tag_tagger
  55: git_tag_tagger
  56: git_tag_tagger
  57: DispatchMessageW
  58: CallWindowProcW
  59: wglSwapBuffers
  60: DispatchMessageW
  61: DispatchMessageW
  62: git_tag_tagger
  63: <unknown>
  64: <unknown>
  65: <unknown>
  66: <unknown>
  67: git_tree_entry_filemode_raw
  68: <unknown>
  69: git_midx_writer_new
  70: BaseThreadInitThunk
  71: RtlUserThreadStart

16:51:51.576  ERROR  window::os::windows::window > caught Any { .. }
```

**Comment by Techince** [comment]
@elxy 我昨天上传的版本可以正常使用呀。之前的版本确实会崩溃

**Comment by Techince** [comment]
@elxy 之前的版本，有个逻辑没考虑周全，致使切换焦点时，偶尔会让新焦点的程序崩溃。这个版本已修复。
[Weasel_x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.001-installer_x64.exe)

**Comment by Parsifa1** [comment]
> @elxy 之前的版本，有个逻辑没考虑周全，致使切换焦点时，偶尔会让新焦点的程序崩溃。这个版本已修复。 [Weasel_x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.001-installer_x64.exe)

谢谢，已经能正常使用了，不过识别的逻辑有点奇怪，切换中英的框会在右下角
![image](https://github.com/rime/weasel/assets/31800073/bc101b99-f49f-493a-a54e-a9b20fe8957d)

**Comment by Techince** [comment]
> > @elxy 之前的版本，有个逻辑没考虑周全，致使切换焦点时，偶尔会让新焦点的程序崩溃。这个版本已修复。 [Weasel_x64](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.001-installer_x64.exe)
> 
> 谢谢，已经能正常使用了，不过识别的逻辑有点奇怪，切换中英的框会在右下角 ![image](https://user-images.githubusercontent.com/31800073/282713439-bc101b99-f49f-493a-a54e-a9b20fe8957d.png)

切换中英文的图标绘制是由WeaselServer中的UI模块绘制的，坐标是从WeaselTSF这边获取的。WezTerm这个应用，空内容请求不到正确的坐标。

**Comment by youguanxinqing** [comment]
请教一下，这里的修复是哪个版本，是 [Nightly](https://github.com/rime/weasel/releases/tag/latest) 吗？我windows10安装这个版本以后不能使用中文输入法，安装回[0.15.0](https://github.com/rime/weasel/releases/tag/0.15.0)可在其他软件中正常使用，在wezterm中不能输入中文

**Comment by lifei** [comment]
什么能发布release版本？

**Comment by rocex** [comment]
今天在 Windows 10 IoT 企业版 LTSC 试了 WezTerm-20240203、每夜版，Alacritty-0.17.0，发现 weasel-0.16.3正式版、weasel-0.17.4正式版、weasel-0.17.4.49、weasel-0.17.4.50都能正常输入，但是光标不跟随，候选框都显示在屏幕右下角，只有 https://github.com/Techince/weasel/releases 下的可以正常跟随，我只试了weasel-0.15.1.008。但是不管是哪个版本的 weasel，在 WindowsTerminal 和 cmder 下都是正常的输入和跟随。希望大佬们检查下是什么问题，最好能合并到正式版里。

-----------------------------------------
这个参数虽然解决了光标跟随的问题，但是在中文状态下输入英文带来了不好的体验，并没有彻底解决问题，最终还是用了 Techince 的 weasel-0.15.1.008 先顶着用吧。
WezTerm 通过配置 ime_preedit_rendering = 'System' 解决了光标跟随的问题，见 https://github.com/wezterm/wezterm/pull/8157 和 https://wezterm.org/config/lua/config/ime_preedit_rendering.html 。
