### ISSUE TITLE
 fxliang的新版本被windows发现木马自动删除

### ISSUE THREAD

**Issue by jiezi506** [rime/weasel#864]
是什么地方出问题了么

**Comment by liuwentao** [comment]
遇到了同样的问题。

诺顿报的如下

> 试图访问 D:\soft\Rime\weasel-0.14.3\WeaselServer.exe。 已检测到并删除了名为 GenericRXVV-DL!FE03CB633FF9 的 特洛伊木马程序。

**Comment by wxyzh** [comment]
McAfee 也有同样的信息。看样子是被通用特征匹配了

**Comment by DuDuF-1019** [comment]
遇到同样的问题，SEP（诺顿企业版）报毒，只能手动设置例外。

**Comment by wxyzh** [comment]
看样子很难搞，我把检查更新的代码注释掉了，只对部分杀毒软件有效。注入dll这个是必须的行为。

**Comment by daomiren** [comment]
昨天还正常，今天几个核心文件全被windows defender 给干掉了，导致无法正常使用了。

**Comment by fxliang** [comment]
目前确认的是我水平不够还不会怎么写木马😂

**Comment by fxliang** [comment]
参见 https://rime.im/download/
```
敬告 Rime 用家
請您知曉：

※ 本品是按照 GPL 授權條款發佈的自由軟件，您可嘗試按照本站提供的指南自行編譯安裝。
※ 輸入法是一種有較高權限的系統軟件，所以一些 Windows 安全防護軟件會在輸入法安裝過程中彈出提示，需要選擇「允許繼續操作」方可正確安裝。
※ 〔小狼毫〕的開發與發佈均在受保護的環境中完成。如果使用過程中，您系統中某種“安全”軟件稱「發現木馬」，那麼此種情形將考驗您的判斷力。
```
