### ISSUE TITLE
小狼毫不支持Windows 11 touch keyboard

### ISSUE THREAD

**Issue by lester1027** [rime/weasel#865]
現在如果希望用touch keyboard操作小狼毫的話，虛擬數字鍵無法顯示。謝謝。

**Comment by wxyzh** [comment]
![Snipaste_2023-04-27_10-27-29](https://user-images.githubusercontent.com/19548073/234744210-ea236df1-d62a-42a4-9e9a-5acb3444e1fa.png)
我这里似乎没问题，梁大的版本

**Comment by lester1027** [comment]
我只有這個鍵盤版本
![image](https://user-images.githubusercontent.com/20129253/235054467-558aec7c-d755-4ab1-a09d-a8d461197649.png)

**Comment by wxyzh** [comment]
键盘右上角`齿轮` -`键盘布局`中有三种布局可选

**Comment by lester1027** [comment]
可能只有粤语输入有问题

**Comment by determ1ne** [comment]
> 可能只有粤语输入有问题

输入方案不会影响功能

无法复现

**Comment by lester1027** [comment]
https://github.com/rime/rime-cantonese/issues/172

這邊的説法似乎不同

**Comment by lester1027** [comment]
請問可以説説詳細做法嗎？另外，你確定沒有問題的是哪一個版本？

**Comment by determ1ne** [comment]
https://github.com/rime/weasel/commit/9c7ea6cdde68e2ffdf7e0c2fe4adf1f62f0f66bb CI 构建：https://github.com/rime/weasel/suites/13137621189/artifacts/714094640

安装到简体中文输入选项：
![image](https://github.com/rime/weasel/assets/16241583/35b8987a-3ce9-4474-8771-0ec18a35f1a8)

**Comment by lester1027** [comment]
噢！成功了，謝謝你。
