### ISSUE TITLE
有表情和没表情的高度不一致

### ISSUE THREAD

**Issue by daomiren** [rime/weasel#866]
有表情的时候显示的高度比没有的时候高，而且表情的位置感觉跟文字显示的不一致，表情更靠下一些，文字则显示居中点，是因为表情基于opencc转换的缘故吗？
![Snipaste_2023-04-27_20-01-28](https://user-images.githubusercontent.com/128763194/234856117-8428a6b4-43cb-4413-9774-1610f9feedd4.png)
![Snipaste_2023-04-27_19-59-16](https://user-images.githubusercontent.com/128763194/234856177-095e7b2b-2e41-4961-9bf7-88c8121453c4.png)
![Snipaste_2023-04-27_19-59-45](https://user-images.githubusercontent.com/128763194/234856234-fff0c9b3-d854-4ca6-9720-88ba683a171b.png)

**Comment by fxliang** [comment]
这个是不同字体的基线位置不一样引起的，解决思路可以是更换字体组合，或者魔改字体调整基线位置

**Comment by letianpai-lpt** [comment]
是的，例如我之前用的霞鹭文楷等宽也出现了这个问题，改成霞鹭文楷后就正常了

**Comment by byzod** [comment]
+1

难受, 打几个字候, 选框就跟楼上在开拖拉机似的抖动

我看好像有解决方案a, 是小狼毫这边实现不一样吗

https://github.com/rime/squirrel/commit/54d872bd5c1d846e33ffca02a1d14f96cb5831e1

**Comment by byzod** [comment]
通过hack一个输入法暂时解决勒（一部分

发现不管怎么弄配置，还是没法完全一致，明明master属性已经一模一样了

猜测rime根据字体轮廓判断了尺寸，但并没有关注base line/ascender之类的设置，所以最后还是看字体的实际大小

不过目前跳得没那么厉害了，先将就着吧，希望早日修复

默认的Segeo print + 微软雅黑，迷人的原始舞蹈.jpg
![An1](https://github.com/rime/weasel/assets/848607/154fb605-604b-4789-b960-d8686132d5fa)

修改过的segeo print ft msyh，羞涩的交际舞.gif
![An2](https://github.com/rime/weasel/assets/848607/aa9aa95d-aac3-49dd-b4af-d8b55bca11dd)


基线设置：
![3](https://github.com/rime/weasel/assets/848607/c8678801-27d4-409b-af50-cedbc3a239f7)
