### ISSUE TITLE
fxliang的新版本在Microsoft Excel中用鼠标点击候选项上屏的是候选项序号而不是候选项内容

### ISSUE THREAD

**Issue by SkatingCN** [rime/weasel#867]
fxliang的新版本，在Microsoft Excel中用鼠标点击候选项，上屏的是序号而不是候选项内容。在其他软件中，暂未发现此现象。

**Comment by fxliang** [comment]
点击操作是模拟发送数字键的keydown和keyup，没有Excel无法测试，可能还和方案相关，或许这个特性应该要删减掉

**Comment by SkatingCN** [comment]
多年前多多输入法生成器4.0版在测试阶段，也存在Microsoft Excel中用鼠标点击候选项上屏的Bug（候选项内容和输入编码一起上屏），我反馈后才修复。

**Comment by Techince** [comment]
> 点击操作是模拟发送数字键的keydown和keyup，没有Excel无法测试，可能还和方案相关，或许这个特性应该要删减掉

我最近在用你的源码编译输入法使用。以前的librime不支持opencc中文路径，我底层代码里加了两个转换函数修复过了，官方版可以正常使用中文路径。但发现您的源码里，误将宽字符集转换成UTF8了，官方源码里有注释，说是Windows内部使用多字节编码，不应将其转换成UTF8. 用上多字节后，程序已能正常进行了。

**Comment by SkatingCN** [comment]
我的输入法方案中，并没有中文路径。经测试，输入法方案的yaml文件、lua文件和opencc 目录里的txt文件都是使用UTF8编码（宽字符）才能正常使用的。不清楚哪些文件需改成多字节(ANSI)编码，烦请明示。

**Comment by Techince** [comment]
> 我的输入法方案中，并没有中文路径。 经测试，输入法方案的yaml文件、lua文件和opencc 目录里的txt文件都是使用UTF8编码（宽字符）才能正常使用的。 不清楚哪些文件需改成多字节（ANSI）编码，烦请明示。

外部文件还需要使用UTF8. 程序内部涉及到Windows路径的需要用多字节字符集，与方案没有关系的。我是借楼联系下作者。

**Comment by determ1ne** [comment]
> > 我的输入法方案中，并没有中文路径。 经测试，输入法方案的yaml文件、lua文件和opencc 目录里的txt文件都是使用UTF8编码（宽字符）才能正常使用的。 不清楚哪些文件需改成多字节（ANSI）编码，烦请明示。
> 
> 外部文件还需要使用UTF8. 程序内部涉及到Windows路径的需要用多字节字符集，与方案没有关系的。我是借楼联系下作者。

新开 issue 讨论吧

**Comment by Techince** [comment]
> > > 我的输入法方案中，并没有中文路径。 经测试，输入法方案的yaml文件、lua文件和opencc 目录里的txt文件都是使用UTF8编码（宽字符）才能正常使用的。 不清楚哪些文件需改成多字节（ANSI）编码，烦请明示。
> > 
> > 
> > 外部文件还需要使用UTF8. 程序内部涉及到Windows路径的需要用多字节字符集，与方案没有关系的。我是借楼联系下作者。
> 
> 新开 issue 讨论吧

移除ime模块后，候选框就支持鼠标点击了。

**Comment by fxliang** [comment]
https://github.com/fxliang/weasel/actions/runs/5495228871
没有Excel，等你们测试
![msl](https://github.com/rime/weasel/assets/4023160/c6069a34-3a65-467f-96bf-1890eae82250)

**Comment by Techince** [comment]
> https://github.com/fxliang/weasel/actions/runs/5495228871 没有Excel，等你们测试 ![msl](https://user-images.githubusercontent.com/4023160/252015351-c6069a34-3a65-467f-96bf-1890eae82250.gif)

Excel下测试成功。

**Comment by SkatingCN** [comment]
在Win 10 64位操作系统中，Exel 2021 下测试成功。
希望更快合并到主仓的master新构建里。
