### ISSUE TITLE
fxliang 版本 深色与浅色模式出问题

### ISSUE THREAD

**Issue by ls148478** [rime/weasel#868]
当开关深色模式与浅色模式后会发现出现某些界面为 深色皮肤 某些界面呈现 浅色皮肤
猜测情况为：已打开的应用切换失败

https://user-images.githubusercontent.com/38435967/235288171-29677f99-87a2-4a2e-b265-cb8d7e64fa3c.mp4

**Comment by fxliang** [comment]
这个状态是已知的，切换暗色主题之前的应用，只要重新切换进入小狼毫就可以对应切换。
尝试过在FocusIn函数里进行更新，但是似乎没有效果，所以这个后面没有细化展开处理的。

**Comment by ls148478** [comment]
> 这个状态是已知的，切换暗色主题之前的应用，只要重新切换进入小狼毫就可以对应切换。 尝试过在FocusIn函数里进行更新，但是似乎没有效果，所以这个后面没有细化展开处理的。

了解了
