### ISSUE TITLE
很好奇为什么小狼毫会出现候选项闪烁或者不显示的问题

### ISSUE THREAD

**Issue by seszu** [rime/weasel#870]
不懂就问，试过好多输入法，小众大众的都用过，唯独小狼毫会出现候选项在word一些软件中候选项不显示的问题，小狼毫是使用了什么特殊的技术了吗

**Comment by wxyzh** [comment]
关闭 inline_preedit 看看呢

**Comment by YQ-YSY** [comment]
诱发Rime在Word中闪烁的条件（故障可重现）以及临时解决方法

很多朋友都遇到了Rime输入法在word中闪烁，难以使用的问题。
我的电脑是：Win10系统，Office 2019，小狼毫weasel-0.14.3.0
经过多尝试和试验，终于发现诱发闪烁的条件（故障可重现）：关键是在Word的“标尺”上，

当我用鼠标拖动“标尺”下方的“小四方形（左缩进）”或者“向上小三角形（悬挂缩进）”几次后，用Rime打字就会闪烁。
临时的解决方法是：把鼠标放在标尺上，就能正常打字，不闪烁了。但是，如果鼠标从标尺上移开，打字又会闪烁。

所以记住，如果要在Word标尺上操作，就先切换为其他输入法，不用Rime。
如果不小心操作了Word标尺，已经造成Rime闪烁了，那么把鼠标放在标尺上，就能继续打字了。
应急打完字后，保存文件，关闭Word，再重新打开，Rime才恢复正常。目前就只能这样了。

——以上信息提供给Rime的开发者，希望能对修改调试程序有帮助。

**Comment by seszu** [comment]
> 

关闭了之后，情况并没有改善

**Comment by seszu** [comment]
> 关闭inline_preedit 看看呢

关闭inline_preedit 后，在我的电脑上，情况并没明显改善

**Comment by Aiden2014** [comment]
置顶issue已经给出解决方法了https://github.com/rime/weasel/issues/228

**Comment by seszu** [comment]
> 置顶issue已经给出解决方法了#228

按照这个设置了，第一天还有效果的，过两天不知道什么原因，再拖动标尺后，候选又闪烁了，去设置里看，输入法控制那里没有被勾上

**Comment by seszu** [comment]
> > 置顶issue已经给出解决方法了#228
> 
> 按照这个设置了，第一天还有效果的，过两天不知道什么原因，再拖动标尺后，候选又闪烁了，去设置里看，输入法控制那里没有被勾上

最后发现很大的可能和OneNote（桌面版，非商店win10版）有关，使用过OneNote后，会导致小狼毫候选窗口在其他软件上出现奇怪的问题，切换到其他输入法再切换回来才会正常。

**Comment by determ1ne** [comment]
最新版 CI 产物中应该已经不存在该问题： https://github.com/rime/weasel/commit/9c7ea6cdde68e2ffdf7e0c2fe4adf1f62f0f66bb CI 构建：https://github.com/rime/weasel/suites/13137621189/artifacts/714094640

**Comment by fxliang** [comment]
留意到在Word中开启inline_preedit的时候，输入编码后，工具栏上的复制剪贴按钮是有响应的，同样微软自带的write.exe也有类似的响应情况，而WPS似乎并没有类似的响应；
应该是Word响应了TSF的select range对应的消息频繁的变化工具栏状态、同时还激活了刷新选择区域导致？可以在旧版的代码上尝试注释这行对比看看
[WeaselTSF/Composition.cpp#L246](https://github.com/rime/weasel/blob/master/WeaselTSF/Composition.cpp#L246)
```cpp
_pContext->SetSelection(ec, 1, &tfSelection);
```

> 最新版 CI 产物中应该已经不存在该问题： [9c7ea6c](https://github.com/rime/weasel/commit/9c7ea6cdde68e2ffdf7e0c2fe4adf1f62f0f66bb) CI 构建：https://github.com/rime/weasel/suites/13137621189/artifacts/714094640

**Comment by determ1ne** [comment]
> 

新版本绘制改了后，在屏上显示不影响了。

参照现在微软拼音的行为，输入法没上屏时，输入的字母是不应该选中的，这部分代码确实也需要去掉

**Comment by seszu** [comment]
> > 
> 
> 新版本绘制改了后，在屏上显示不影响了。
> 
> 参照现在微软拼音的行为，输入法没上屏时，输入的字母是不应该选中的，这部分代码需要修改，让光标指向最后方

确实在word中没有问题了，后来发现在有问题的软件中，切换到别的输入法再切换回来，可以解决大部分的软件兼容性，比如桌面版的OneNote

**Comment by determ1ne** [comment]
> 

会

**Comment by YQ-YSY** [comment]
很高兴看到问题得到解决，谢谢！

**Comment by uliuyt** [comment]
0.15版本还是有问题，在桌面版OneNote2021使用时，候选框会闪烁。切换到windows自带输入法再切回小狼毫可暂时解决。
