### ISSUE TITLE
win7 不能自定义 复杂字符串

### ISSUE THREAD

**Issue by fanrongqitiancai** [rime/weasel#873]
我想实现的功能是这样的。但我按下 dm后，第一个候选项输出
![image](https://github.com/rime/weasel/assets/9015263/742ad3fd-ef3a-4709-97eb-1d1f4d03d538)

这里输入法需要输出回车符。
qq输入法是能实现这个效果的
![image](https://github.com/rime/weasel/assets/9015263/c7444bc9-a22d-4299-bc00-9daf8d813893)

上屏后是
![image](https://github.com/rime/weasel/assets/9015263/906e4e4b-39ab-4872-bce6-818fa65400f3)

**Comment by fanrongqitiancai** [comment]
我这样写代码测试，会卡死，也不能实现这样的效果
![image](https://github.com/rime/weasel/assets/9015263/5c475a21-4ac1-439b-9180-24394692a940)

**Comment by fxliang** [comment]
用\r

**Comment by fanrongqitiancai** [comment]
用\r 解决了问题，可以实现换行了
