### ISSUE TITLE
How to provide translations for the installer

### ISSUE THREAD

**Issue by null-von-sushi** [rime/weasel#874]
In order to make RIME more usable by non-natives, it would be helpful if the Windows installer could be translated. I would like to help you do this, however I am not sure where the strings are stored (or are they hardcoded?)
If there's an external file for translation, I would like to translate the strings into English

**Comment by mirtlecn** [comment]
大部分界面语言写在 rc 文件中，还有一部分在源码里，目前只有繁体中文。现在应该不太方便提供翻译。

#900 只给 nsis 安装包文件提供了一些繁中、简中和英文的翻译，但只影响注册表和快捷方式的名称。

不过如果真的要提供非中文的翻译，大篇的中文文档可能也要一并处理。

**Comment by fxliang** [comment]
#900 done
