### ISSUE TITLE
win10 vs2019 不能打开工程

### ISSUE THREAD

**Issue by fanrongqitiancai** [rime/weasel#875]
我下载了weasel-master.zip。win10 上安装了vs2019，双击weasel.sln文件，提示不能加载，错误信息如下：
C:\Users\shhys\Desktop\weasel-master\WeaselSetup\WeaselSetup.vcxproj : error  : 未找到导入的项目“C:\Users\shhys\Desktop\weasel-master\weasel.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。  C:\Users\shhys\Desktop\weasel-master\WeaselSetup\WeaselSetup.vcxproj

我运行目录里的，管理员方式 install_boost.bat。一闪就消失了。我的win10没有安装rime输入法。

**Comment by determ1ne** [comment]
`install_boost.bat` 需要电脑中安装有 aria2 ，可以参考下文件内容手动下载相关文件。
