### ISSUE TITLE
最新构建在Chrome和Firefox内不工作

### ISSUE THREAD

**Issue by Shouyupedia** [rime/weasel#877]
Windows10和11下用最后一个release的new feature版本以及最新action构建的new feature版本都会出现在这两个浏览器内不工作的情况，基于chrouim的浏览器如Brave内工作正常，清除全部文件，重启，重新安装，重启后仍然存在同样的问题。旧版0.14.3正常。

**Comment by determ1ne** [comment]
该 commit https://github.com/rime/weasel/commit/9c7ea6cdde68e2ffdf7e0c2fe4adf1f62f0f66bb 的 CI 构建版本是否仍能在你的环境复现该问题？

**Comment by Shouyupedia** [comment]
您好，感谢您关注我的问题，完整删除并重新安装最新构建后已正常工作。
