### ISSUE TITLE
可否加入台灣繁體介面？

### ISSUE THREAD

**Issue by ghost** [rime/weasel#89]
雖然程式有繁體介面，但均為大陸詞彙，感覺蠻彆扭的。

**Comment by david50407** [comment]
RIME 應該有加入新酷音的詞庫才對，如果你是使用朙月拼音的話可以在方案選單（Ctrl+`）裡面選擇《朙月拼音・臺灣正體》

**Comment by zhtw2013** [comment]
他說的是UI用語在地化的部分。

舉幾個例子。

簡體：用戶 繁體：使用者
簡體：導出 繁體：匯出
簡體：導入 繁體：匯入
簡體：設定字體... 繁體：設定字型

說的是這類的用語習慣。

**Comment by lotem** [comment]
介面本地化固然是好的，方便講不同語言的人理解和使用軟件，但也不能走極端。
同爲一種語言，各個地區遣詞造句的習慣多少有些不同，甚至每個人都有獨特的語言風格。「用家」「用戶」「使用者」，差異總大不到形成閱讀障礙的程度。魯迅那樣濃濃紹興味的文風，尚且容於後世的讀者，沒人請求將佢的文章本地化。
吾輩可不是全篇中州白話，更不懂什麼標準用語。語言傳播中相互包容借鑑，並不容易找到截然的分界。自信拿到漢語方言分歧極大的地方，都不需要翻譯；到了現代標準漢語通行度極高的臺灣，反要強調劃出一個「體統」，這也太講究了。吾輩斷然不會做這等無聊之事。

當然，你開心就好。
開源的好處就是大家都可以按照自己的想法做改進。不妨試試看能否爲程序的介面加入本地化的支持。

**Comment by zhtw2013** [comment]
@lotem 
公子，用語在地化的部分，這比較偏向配合系統用語
像我做軟體中文化，能夠跟隨規範的部分幾乎都會跟隨規範的
(Window上有微軟語言入口網站能參考)
這是為了讓使用者更方便，而不是為了「劃出一個體統」
也談不上講究啥的，就是照規矩走而已。

他會覺得彆扭也是這個原因，習慣做中文化的譯者通常都會照著規範走。
舉例：i18n  Mac 上的User 就是翻成使用者，一堆「使用者」中看到一個「用戶」
會覺得不和諧、彆扭也是肯定的。

當然不會形成閱讀障礙，但就是不符合規範了，看來彆扭，會有這種感覺是很正常的。

於中文化譯者的立場來看，已經有既定翻譯的詞彙，還是用既定翻譯比較好，
像是Folder，在Windows上叫做資料夾，在MAC上叫做檔案夾，簡體用語叫做文件夾，
翻譯時就要針對它做適應、配合。

反正公子的立場就是不會改的，所以這裡只是做個解釋而已。

**Comment by lotem** [comment]
汉字字形的简繁和地域用语的差异是两个不相关的的问题。不要混为一谈。

**Comment by zhtw2013** [comment]
公子，我說的完全就是地域用語差異，並不是漢字字型簡繁差異。
![image](https://user-images.githubusercontent.com/9501406/37356981-3267a72c-2722-11e8-9958-2a3093f19d5d.png)

**Comment by xingezhang** [comment]
浏览器不是流览器

**Comment by zhtw2013** [comment]
@xingezhang 這是故意加入的，
因為有些人會打錯字，打成流覽器，
所以轉換也要考慮這種情況。
