### ISSUE TITLE
输入法兼容OR其他问题，输入框不展示

### ISSUE THREAD

**Issue by QianmuZ** [rime/weasel#891]
0531的action版本安装，在Obsidian的Notion tables 中不展示输入框，不知道是否软件兼容个例

![不展示输入框](https://github.com/rime/weasel/assets/28744797/ef41c583-1ea8-47e4-a08c-d6adc04b0d5f)
@fxliang @determ1ne

**Comment by mirtlecn** [comment]
#882下的构建也无法在这个插件下输入

另外，同样的配置文件，在不开启 inline_preedit 的情况下，Windows 11 正式版打开设置面板（⊞Win+I）。我将所有配置文件和插件删除，只用自带的全拼，仍然可以复现。

- 最新构建，Weasel 会 100% 导致设置面板闪退。
- #882 构建无此问题

首先切换 ASCII mod，然后再切回去不会导致闪退。开启 inline_preedit 不会导致闪退。

**Comment by fxliang** [comment]
这个Issue和我之前听到的OneNote下输入异常的问题是类似的，和TSF组件的一些功能没有做全有关系

**Comment by Techince** [comment]
> 0531的action版本安装，在Obsidian的Notion tables 中不展示输入框，不知道是否软件兼容个例
> 
> ![不展示输入框](https://user-images.githubusercontent.com/28744797/242467235-ef41c583-1ea8-47e4-a08c-d6adc04b0d5f.gif) @fxliang @determ1ne

似乎是ime模块引起的，把「System32」和「Windows\SysWOW64」两目录下的「weasel.ime」加个扩展名屏蔽一下试试。

**Comment by QianmuZ** [comment]
> > 0531的action版本安装，在Obsidian的Notion tables 中不展示输入框，不知道是否软件兼容个例
> > ![不展示输入框](https://user-images.githubusercontent.com/28744797/242467235-ef41c583-1ea8-47e4-a08c-d6adc04b0d5f.gif)
> >       
> >         [
> >           
> >         
> >             ![不展示输入框](https://user-images.githubusercontent.com/28744797/242467235-ef41c583-1ea8-47e4-a08c-d6adc04b0d5f.gif)
> >           ](https://user-images.githubusercontent.com/28744797/242467235-ef41c583-1ea8-47e4-a08c-d6adc04b0d5f.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/28744797/242467235-ef41c583-1ea8-47e4-a08c-d6adc04b0d5f.gif)
> >         
> >        @fxliang @determ1ne
> 
> 似乎是ime模块引起的，把「System32」和「Windows\SysWOW64」两目录下的「weasel.ime」加个扩展名屏蔽一下试试。

确实可行

**Comment by determ1ne** [comment]
似乎还有别的问题，虚拟机中无图形加速一切正常，虚拟机外候选框一闪而过，类似 wezterm

**Comment by determ1ne** [comment]
> > 似乎还有别的问题，虚拟机中无图形加速一切正常，虚拟机外候选框一闪而过，类似 wezterm
> 
> 
> 
> 我测试的，在wezterm下输入法没反应

wezterm里是无法激活输入法。你可以按官方说明把图形加速关了，就能正常输入了

**Comment by determ1ne** [comment]
新版 Notion 插件中无问题
