### ISSUE TITLE
inline_preedit黑暗模式字体颜色问题

### ISSUE THREAD

**Issue by xjkdev** [rime/weasel#893]
出现版本：master分支a980ebb
系统版本：win 11 22H2
出现问题：
win11黑暗模式下字体仍然是黑色，不与文本框字体一致导致看不清楚。
![屏幕截图 2023-06-01 151802](https://github.com/rime/weasel/assets/4402707/8e3f262f-d211-45a6-8f25-59382cfabdb7)
![屏幕截图 2023-06-01 151830](https://github.com/rime/weasel/assets/4402707/6ef53502-c7dc-48d8-a6b0-ab87b6fe0cbd)

之前使用的应该是fxliang的ea12128的版本，之前并没有这个问题。

**Comment by determ1ne** [comment]
无法复现。这个文本框里文字的颜色不是 weasel 管的。

**Comment by xjkdev** [comment]
但是其他输入法，比如微软拼音没有这个问题，黑暗模式候选字会显示白色。

**Comment by determ1ne** [comment]
> 但是其他输入法，比如微软拼音没有这个问题，黑暗模式候选字会显示白色。

等一下这个 build（ https://github.com/rime/weasel/actions/runs/5152921666 ），安装后重启下系统试试。

我这里是正常工作的

![image](https://github.com/rime/weasel/assets/16241583/7387f23d-11aa-4a82-897c-5cf22cf53e08)

顺便可以附上操作系统的详细 Build Number 。在运行中输入 winver 可以看到

**Comment by xjkdev** [comment]
这个build依然有这个问题。
系统版本是22621.1702

要不我用二分法找一下是什么时候开始有的bug吧。

**Comment by xjkdev** [comment]
这个版本没有问题：https://github.com/rime/weasel/actions/runs/5119988650 
这个版本开始出现了问题：https://github.com/rime/weasel/actions/runs/5119993256

**Comment by determ1ne** [comment]
@fxliang

**Comment by xjkdev** [comment]
这个版本没有问题：https://github.com/rime/weasel/actions/runs/5104933578
这个版本开始有问题：https://github.com/rime/weasel/actions/runs/5119988650

之前应该是因为有选中的状态所以反色了，但是去除后导致不能看清楚。
![屏幕截图 2023-06-02 153506](https://github.com/rime/weasel/assets/4402707/f6aca223-dbbc-4e50-9a41-e561638f19f2)

**Comment by fxliang** [comment]
@xjkdev  可以试一下，fork主仓到一个分支上，然后修改这个位置的RGB数值
[https://github.com/rime/weasel/blob/master/WeaselTSF/DisplayAttributeInfo.cpp#L11](https://github.com/rime/weasel/blob/master/WeaselTSF/DisplayAttributeInfo.cpp#L11)

提交看看CI产出的数据安装包是不是就正常了。您提的这个问题我在Windows10下没有复现

**Comment by xjkdev** [comment]
我还没装编译的环境，而且对windows开发不是很熟悉，所以如果自己调试的话可能需要一段时间，我慢慢试试吧。
但我个人觉得此处用固定的颜色可能不太准确，这里可能是应该使用文本框提供的颜色。

**Comment by fxliang** [comment]
> 

我等下试改一个分支你到时看看。另外留意如果没有开输入法的情况下，直接英文输入的时候那个位置的文字显示的情况如何的

**Comment by xjkdev** [comment]
英文输入都是没有问题，ascii mode也没有问题。

**Comment by fxliang** [comment]
> 英文输入都是没有问题，ascii mode也没有问题。

https://github.com/fxliang/weasel/actions/runs/5153416119 试试这个测试的产出，看看字体是不是变成了红色

**Comment by xjkdev** [comment]
没错，现在是红色了。

**Comment by fxliang** [comment]
> 

说明不同版本系统上对这个设置的参数响应不一样，在Windows10上似乎是无视了这个参数的。
几分钟后留意这个的产出
[https://github.com/fxliang/weasel/actions/runs/5153734886](https://github.com/fxliang/weasel/actions/runs/5153734886)

**Comment by xjkdev** [comment]
OK了，现在问题解决了

**Comment by fxliang** [comment]
@determ1ne 这个看看其他的应用上是不是有出现异常了，如果没有异常的话，要不然就考虑将我这个修改合入

**Comment by determ1ne** [comment]
> @determ1ne 这个看看其他的应用上是不是有出现异常了，如果没有异常的话，要不然就考虑将我这个修改合入

应该是这个Windows版本的bug，我的win11上没有这个问题。我明天再检查下ci build，没问题的话我合掉
