### ISSUE TITLE
输入法候选框和输入法设定不显示

### ISSUE THREAD

**Issue by Fitzgerald-Porthmouth-Koenigsegg** [rime/weasel#894]
这个问题是我在重装新系统再进行安装小狼毫时候所产生的（系统是Windows 10的，严格来说是重置了系统）。
安装后，我使用小狼毫打字不会出现欲输入字的候选框，换而言之就是这个东西（借用了官网的图片），但是打了字母再按空格字还是能打出来的：
![Image text](https://rime.im/images/home-feature-4.svg)
同时，输入法菜单里的`输入法设定`选项，点击后也不会出现任何东西，点击`重新部署`会没有任何反应（就连“部署中”的通知提示框都没有）。
这个问题我询问了多方都无人解答，也无人清楚是怎么回事，如果提案里有人知晓解决方法请劳烦尽快提出，因为目前来说我已经不能正常使用小狼毫了。
诚谢。

**Comment by fxliang** [comment]
更加细节信息提供一下，或者，试装CI下最新的构建产出？

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
我所安装的版本即为当前release中的最新版本（即为0.14.3.0），不清楚是不是您所提到的CI下最新的构建产出。
另外您想要提供哪些方面的更加细节信息（因我本人对这方面完全没有任何了解，恕本人思维驽钝）？

**Comment by fxliang** [comment]
如果使用的是1.7.3以上的librime，检查一下在用户目录下面有没有default.custom.yaml和weasel.custom.yaml，如果没有的话创建空文件在下面再部署看看情况。旧版的文件配合1.7.3的librime没有那两个文件的话是打不开设定窗口的

至于最新的ci是看看[这里](https://github.com/fxliang/weasel/suites/13299825341/artifacts/726148628)，下方的artifact链接处的压缩包里有个安装包，新的构建修复了上面提到的文件问题，做好必要的数据备份，试试看情况如何。

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
问题已解决，感谢您的帮助。
