### ISSUE TITLE
新版本在word中输入时会造成字体错乱

### ISSUE THREAD

**Issue by s92671** [rime/weasel#896]
最新构建（8aa26ff）在word中输入时，如果按ESC关闭选词框，再次输出时word中字体会错乱，似乎是变成了默认字体。

系统：Win10 LTSC 21H2
word版本：Office LTSC 2021

**Comment by determ1ne** [comment]
附一下截图 /GIF ？

**Comment by s92671** [comment]
![23](https://github.com/rime/weasel/assets/40166/406cad6d-fd8f-48e0-a740-ce623e9588f0)

**Comment by determ1ne** [comment]
知道是什么问题了，我之后在 #890 里修掉。
