### ISSUE TITLE
Feature request: 当 inline_preedit 为 false 时，同样在行内显示输入码

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#897]
![image](https://github.com/rime/weasel/assets/76689045/0b482e39-3831-4215-8507-4da51ecf2089)

搜狗输入法会在原文本处显示输入码，也会在候选窗口显示输入码。

Weasel 将 inline_preedit 设置为 false 时，为 GetTextExt()，会插入字符，此时影响部分软件功能
- 行首「输入空格开启 AI 预测模式」会因为此空格意外触发；
- #895 
- #896 
- #946

或许可以参考搜狗输入法解决方法，做个假的非 inline_preedit 模式，即使 inline_preedit 关闭，也显示输入码，这样就不需要 workaround。inline_preedit 调整为只影响是否在候选项上方展示额外的输入码。

**Comment by mirtlecn** [comment]
你说的有道理，我原贴说的不太合适。

Weasel 最初似乎是参考了微软原先的做法插入空格的。但现在当前，微软，搜狗，百度等主流输入法部分摒弃了这个方法，不再提供完全关闭 inline_preedit 的选项，想必是插入字符的 walkgroud 确实不优雅，潜在问题不少。https://github.com/rime/weasel/pull/890#issuecomment-1573093143 这里的你的评论也是因为这个插入字符导致的。

我试用了搜狗和百度，他们在设置面板中并没有插入可见的字符，并没有闪退。
![image](https://github.com/rime/weasel/assets/76689045/3e9692ea-fe28-4abd-b1c1-e66ec8dca944)

且插入零宽空格并不会在一些系统版本上导致应用闪退。

或许仅在有某些未知冲突的应用上可以如此实现。

**Comment by determ1ne** [comment]
这个 feature 之后可以提供成一个选项，做在 inline_preedit 的位置

**Comment by mirtlecn** [comment]
#985 PR 里分应用设置 inline_preedit 的做法解决问题了
