### ISSUE TITLE
Win8下自定义输入方案部署失败

### ISSUE THREAD

**Issue by pihao** [rime/weasel#9]
**系统:** Windows 8.1 x64
**输入法:** 小狼毫 0.9.29.1
**输入方案:** 自定义
**问题:** 自定义输入方案部署失败

按Wiki上的**[综合演练](https://code.google.com/p/rimeime/wiki/RimeWithSchemata#綜合演練)**新建一个`hello`的输入方案, 但词典无法生效.
多次尝试干无果后, 打算卸载重装. 结果成功了.

然后又新建了一个ID为`wubi98`的方案, 但词典又无法生效.
尝试卸载秤也还是不行.

观察发现, 
`wubi98`方案在部署后还是只有`dict.yaml, schema.yaml`这两个文件,
而`hello`方案还生成了这些文件:`prism.bin, reverse.bin, table.bin, userdb.kct, userdb.kct.wal`.
在`用户扁词典管理`有`hello`这个词典, 但没有`wubi98`.

Google多次也没找到解决办法.
这是哪里操作错误了吗?

**Comment by HernandoR** [comment]
我想问一下，日志在哪里看啊

**Comment by ryysoft** [comment]
对，我也问日志怎么看？
