### ISSUE TITLE
横排布局下最小宽度参数失效竖排下正常

### ISSUE THREAD

**Issue by LT-1234** [rime/weasel#908]
菜鸡一问😅，style/horizontal: true的时候，style/layout/min_width就失效了，只对竖排生效，横排宽度参数是否改了呢~

**Comment by fxliang** [comment]
> 菜鸡一问😅，style/horizontal: true的时候，style/layout/min_width就失效了，只对竖排生效，横排宽度参数是否改了呢~

留意 #909 的产出确认是不是已解决问题
