### ISSUE TITLE
想学习一下，请问有相关的文档吗？

### ISSUE THREAD

**Issue by zeleven** [rime/weasel#91]
没有找到有文档

**Comment by lotem** [comment]
文檔： https://github.com/rime/home/wiki/UserGuide

**Comment by zeleven** [comment]
呃，这个只是用户使用手册吧，我是想学习下源码，想找开发者文档之类的东西

**Comment by lotem** [comment]
開發者文檔： https://github.com/rime/home/wiki/RimeWithSchemata

**Comment by zeleven** [comment]
可以再問一下嗎，圖形介面部分是用什么实现的呢？

**Comment by lotem** [comment]
https://github.com/rime/weasel/blob/master/WeaselUI/WeaselPanel.h
