### ISSUE TITLE
次像素反鋸齒失效

### ISSUE THREAD

**Issue by a0193143** [rime/weasel#910]
在100%縮放沒有了次像素反鋸齒(subpixel anti-aliasing)會讓字顯得粗細不均、發虛
在Changelog似乎沒有提到這個

0.14.3
![1](https://github.com/rime/weasel/assets/32773311/e4e89fd6-f709-4178-80cd-d316cf4cf2b4)

0.15.0
![2](https://github.com/rime/weasel/assets/32773311/656b61e3-01ce-4df8-a929-b61bba8405c6)

**Comment by fxliang** [comment]
实现没有失效，只是形式不是您预期的状态吧。目前这个是ANTIALIAS_MODE_GRAYSCALE，大多数人的反馈是更清了。
当然如果你不满意，没有问题，我小改了下推了个小修改，增加一个自由配置模式的选项可以你试试，你可能喜欢的是default或者cleartype模式的渲染。

https://github.com/fxliang/weasel/actions/runs/5198444875

`style/antialias_mode: "default" | "cleartype" | "grayscale" | "aliased" | "force_dword" `

**Comment by fxliang** [comment]
> > 新版是从原来的GDI绘制文字改为了directwrite，最正常的directwrite文字绘制.至于为什么Mactype有那样的情况就应该问那边的软件大神了。
> 
> 大概这正是问题所在，mactype核心功能只作用于GDI，对于directwrite，mactype只能更改其内置参数（需要DirectWrite=1），也就是说，这次更新对大部分用户是福音，但对mactype用户而言可能是体验降级，就我而言好消息是彩色emoji可以正常显示了😂️

这个不一定的，抗锯齿方式这个东西有点看人的，有人喜欢这样有人喜欢那样，我也有用mactype但是未有发现什么明显不适感

**Comment by huaxianyan** [comment]
@Hermaros 请教下你最后是怎么解决的？

我现在的输入框在 MacType 没干涉的软件上效果很好，但是在 MacType 干涉的软件上候选效果一言难尽，首选项还对不齐

**Comment by Hermaros** [comment]
@huaxianyan DirectWrite=0，因为我实在没法测试相关参数的具体效果，mactype的directwrite调教是直接引入的另一位作者的作品，以至于mactype的文档里对相关参数的说明一共四条，两条包含“我也不知道效果如何”，还有一条结语是“常识如此，但这里有不同的设定”。而且似乎不是所有软件都接受这些自定义参数。至于对不齐，建议如果之前修改过字号，则直接删除相关修改。
