### ISSUE TITLE
0.15.0版本安裝程序被Symantec Endpoint Protection識別爲木馬

### ISSUE THREAD

**Issue by yatounoneko** [rime/weasel#914]
小狼毫更新/安裝程序被識別為木馬，由於是公司電腦因此無權限排除...

版本：0.15.0
OS: Windows 11
受影響殺毒軟件：Symantec Endpoint Protection

FYI
![Snipaste_2023-06-08_11-54-37](https://github.com/rime/weasel/assets/22129910/d36dd99c-c7f3-4101-9cff-420672e15a94)
![Snipaste_2023-06-08_11-54-22](https://github.com/rime/weasel/assets/22129910/c297567f-cac5-4bf2-8fdd-435b1f742586)

**Comment by determ1ne** [comment]
误报是个很麻烦的问题，只能走杀毒软件的上报通道了
看起来 virustotal 上都报告安全了，但上面并没有 symantec
只能尝试给 symantec 提交 false positive 说明，看看那边怎么反馈

**Comment by Eason0210** [comment]
Windows 自带的杀毒软件也报了。目前只能自己解除隔离。不知道哪可以上报？

**Comment by determ1ne** [comment]
> Windows 自带的杀毒软件也报了。目前只能自己解除隔离。不知道哪可以上报？

你下载的是 release 版本吗？ commit ci 版本很容易被误报。

Windows Defender 的上报链接： https://www.microsoft.com/en-us/wdsi/filesubmission/

**Comment by Eason0210** [comment]
> 你下载的是 release 版本吗？ commit ci 版本很容易被误报。

是的，我下的 commit ci  版本。正式版本只是安装后才会报毒。

**Comment by owenyang-ai** [comment]
Virustotal 检测连结档案 和 下载后再上传，结果不太一样，好像是使用的vendor不同。

![image](https://github.com/rime/weasel/assets/62329706/ddb22528-bf9b-4bbf-8447-87d7376f9681)

**Comment by TsFreddie** [comment]
公司的 McAfee 也报了

**Comment by determ1ne** [comment]
刚刚编译 0.14.3 版本 WeaselServer 的结果：

![image](https://github.com/rime/weasel/assets/16241583/3fd697b5-6087-4311-a160-e18dc115b854)

看来是中间改的什么东西触发到特征码了。 WeaselServer 依赖上还是比较复杂的，需要看到底是 IPC、 IPCServer 还是 RimeWithWeasel 谁出了问题，需要研究一段时间

看起来这些杀毒软件都是收费的，我在本地测试会比较麻烦，有条件帮忙的朋友，可以看下这些二进制会不会被报毒（只扫描就行了）：

0.14.3 代码编译的 WeaselServer ，使用了新工具链：

[WeaselServer_Old_Antivirus.zip](https://github.com/rime/weasel/files/11686482/WeaselServer_Old_Antivirus.zip)

fxliang 的第一个 PR 版本：

https://github.com/rime/weasel/suites/12819542859/artifacts/690295460

#876 的版本：

https://github.com/rime/weasel/suites/13137621189/artifacts/714094640

**Comment by determ1ne** [comment]
只用 Windows Defender 的话会比较玄学，本地特征库不会报毒，但开了基于云的防护会报毒

**Comment by determ1ne** [comment]
symantec 单独为 0.15.0 的安装包开了白名单（但不确定 weasel server 是否还会被报毒）

```text
Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:

    File name: weasel_0.15.0.0_installer.exe
    MD5: 51C97A47948E06586142D5A1E8DDCA07
    SHA256: 21B2B3BA19F11B308DB3C50CE343A14A42CE10331E3C0B7021850EC6726DCD10
    Note: Whitelisting is available by downloading a RAPID RELEASE indicated in the Further Information section below or via the next Live Update Further Information:
Required RAPID RELEASE sequence >= 228309
```

**Comment by determ1ne** [comment]
windows defender 的报毒已移除

更新病毒库的方法：

```
1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"
```

**Comment by kur0** [comment]
https://www.virustotal.com/gui/file/21b2b3ba19f11b308db3c50ce343a14a42ce10331e3c0b7021850ec6726dcd10
1.5.0 在virustotal還是報告有毒

**Comment by kur0** [comment]
fxliang 的第一个 PR 版本：23/67
https://www.virustotal.com/gui/file/21b2b3ba19f11b308db3c50ce343a14a42ce10331e3c0b7021850ec6726dcd10
https://github.com/rime/weasel/pull/876 的版本：14/69
https://www.virustotal.com/gui/file-analysis/ODQ2MTEzOGVkZDkxM2Q3ZTNmNTY1MWUwZGJjZjA3ZGE6MTY4NjIzNzcxMw==

**Comment by juneszh** [comment]
> windows defender 的报毒已移除
> 
> ![image](https://user-images.githubusercontent.com/16241583/244560987-68dc3171-8016-46d8-9d04-d6667c0545ac.png) ![image](https://user-images.githubusercontent.com/16241583/244561023-60a2a765-ec00-4814-9490-80ccdbccb007.png)
> 
> 更新病毒库的方法：
> 
> ```
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> ```

更新病毒库后，安装文件仍然报毒

![图片](https://github.com/rime/weasel/assets/2436252/02505131-c510-4e4c-b575-840ca9906ee9)


```
PS C:\Program Files\Windows Defender> .\MpCmdRun.exe -removedefinitions -dynamicsignature

Service Version: 4.18.23050.3
Engine Version: 1.1.23050.3
AntiSpyware Signature Version: 1.391.905.0
AntiVirus Signature Version: 1.391.905.0

Starting engine and signature rollback to last known good signature...
Done!

Service Version: 4.18.23050.3
Engine Version: 1.1.23050.3
AntiSpyware Signature Version: 1.391.836.0
AntiVirus Signature Version: 1.391.836.0
PS C:\Program Files\Windows Defender> .\MpCmdRun.exe -SignatureUpdate
Signature update started . . .
Service Version: 4.18.23050.3
Engine Version: 1.1.23050.3
AntiSpyware Signature Version: 1.391.836.0
AntiVirus Signature Version: 1.391.836.0
Signature update finished.
```

**Comment by J4gQBqqR** [comment]
我的电脑被公司重置了！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
![Imagepipe_4](https://github.com/rime/weasel/assets/77554817/e5d20bbb-2d53-4dab-82d5-cf8158da652e)
![Imagepipe_3](https://github.com/rime/weasel/assets/77554817/2f1e65b3-e824-4b7d-bedb-6db166fb36e6)

我不知道怎么形容我现在的心情…………………………

**Comment by fxliang** [comment]
https://www.virustotal.com/gui/file/a52ca42cdc1aa57ba3515f0bf4632c00bac639a8c911a1a4f479ccdc30db3549?nocache=1

我的第一个PR是新特性那个吗？上面是我本机构建的安装包上传上去测的，似乎差的多呀

**Comment by Shea11012** [comment]
我的遇到的就很奇怪，没有报病毒，但是我把搜狗输入法删除后，Weaselserver.exe 就不会被删除了

**Comment by determ1ne** [comment]
> https://www.virustotal.com/gui/file/a52ca42cdc1aa57ba3515f0bf4632c00bac639a8c911a1a4f479ccdc30db3549?nocache=1
> 
> 我的第一个PR是新特性那个吗？上面是我本机构建的安装包上传上去测的，似乎差的多呀

以散列值为准吧，单独测 WeaselServer.exe 更好些，安装包的检测也比较迷

**Comment by marcushsu** [comment]
连Chrome都拦截了。
![image](https://github.com/rime/weasel/assets/11764515/a7884f60-f15e-4203-9fd8-e017ead67014)

**Comment by s5unty** [comment]
McAfee Endpoint Security 也发来贺电

**Comment by determ1ne** [comment]
> McAfee Endpoint Security 也发来贺电

mcafee 今天白名单了

**Comment by yatounoneko** [comment]
目前不再誤報了。
