### ISSUE TITLE
weaselserver.exe 被自动删除

### ISSUE THREAD

**Issue by Shea11012** [rime/weasel#916]
操作系统：win11专业版
版本：22621.1702
weasel：0.15.0
在安装时没有报病毒，但是关机第二天打开后，weaselserver.exe 就不在安装目录了。
查看了火绒和window defender没有找到删除或隔离记录。

**Comment by Shea11012** [comment]
> 估计被 Windows Defender 干掉的

并没有在defender看到删除记录

**Comment by danvim** [comment]
VirusTotal: https://www.virustotal.com/gui/file/21b2b3ba19f11b308db3c50ce343a14a42ce10331e3c0b7021850ec6726dcd10/detection

![image](https://github.com/rime/weasel/assets/5255292/d13ef249-4ca7-47ad-ad17-11c0b74f5a47)

**Comment by zhifuchen** [comment]
windows defender报特洛伊木马后删除了安装程序,排除安装程序安装后还报特洛伊木马(Trojan:Win32/Wacatac.H!ml)

**Comment by yehh** [comment]
我的也被删除了，即使之前通过内置的升级到0.15后（使用原来的配置）也无法使用

**Comment by determ1ne** [comment]
合并进 #914 讨论

有条件先手动白名单，或等下版本可能的排查修复
