### ISSUE TITLE
剛剛更新是發現病毒

### ISSUE THREAD

**Issue by lpg694** [rime/weasel#918]
**上报前请检查**
- [X] 我遇到的问题没有其他人在 issue 里提到过
- [X] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 10 22H2 (OS Build 19045.2965]
 - 小狼豪版本: [ 0.14.3]

**描述遇到的问题**
自動更新時遇到防毒軟體通告説明安裝程式含了木馬病毒 - Wacatac B!ml.

**复现步骤**
重现问题的步骤，如：
1. 按了 "Install Update"
![image](https://github.com/rime/weasel/assets/28111446/816767d7-ee16-42c6-aed9-fc99fffb2756)
2. 再按 “Install Update"
![image](https://github.com/rime/weasel/assets/28111446/5fa88efb-db51-4627-a237-e72ccf31c4bc)
3. 进行 "Launching the installer" 操作
4. 遇到了 "Failed to launch the installer" 问题 
![image](https://github.com/rime/weasel/assets/28111446/a88ed273-1074-464d-b26f-95a2ebee7b68)

**预期行为**
沒法更新
**截图**
![image](https://github.com/rime/weasel/assets/28111446/1a870531-0918-4760-9de5-59840b31d1e0)

**其他补充说明**

**Comment by determ1ne** [comment]
duplicate of #914 

手动更新病毒库 / 添加白名单 / 等下版本可能的修复
