### ISSUE TITLE
max_width max_height 在设置之后无法恢复，只能重新启动小狼毫算法服务程序

### ISSUE THREAD

**Issue by KyleBing** [rime/weasel#919]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows10 21H1(19043.1055)
 - 小狼豪版本:  0.15.0.0

**描述遇到的问题**
在 `weasel.custom.yaml` 文件中配置了 `max_width` 与 `max_height` 属性部属之后，撤消它，再部属，无法正常显示。
需要重新启动小狼毫算法服务程序才能恢复。

**复现步骤**
重现问题的步骤，如：
1. 在 `weasel.custom.yaml` 文件中配置了 `max_width` 与 `max_height` 属性
2. 部属，此时界面生效。
3. 将刚才两个属性删除
4. 部属
5. 候选界面无法恢复
6. 需要重新启动小狼毫算法服务程序才能恢复

**预期行为**
正常显示并恢复候选界面

**截图**
原始显示：
![2023-06-09 09 36 01](https://github.com/rime/weasel/assets/12215982/b6e461ce-3368-4b24-9c8b-15116f5feafb)

问题截图：
![2023-06-09 09 52 49](https://github.com/rime/weasel/assets/12215982/02da5851-6b8f-4ea8-a7fb-d85aceb762b7)
![2023-06-09 09 51 45](https://github.com/rime/weasel/assets/12215982/4a29bece-99f7-499a-b2d4-454192a57694)

**其他补充说明**
无

**Comment by fxliang** [comment]
尝试你描述的操作未复现问题，一切正常。

出现你所示图二的状态，说明yaml文件存在明显的语法问题，请尝试核对文件复查确认；

或者

weasel.custom.yaml 文件只留以下内容做注释和解注释测试
```yaml
patch:
  style/layout/max_width: 100
  style/layout/max_height: 100
```

**Comment by KyleBing** [comment]
收到
