### ISSUE TITLE
Win 10, Version 1709 报错,无法输入中文

### ISSUE THREAD

**Issue by SJTUboy** [rime/weasel#92]
OS: Win 10, 64 bit
Version: 1709
表现：安装 Win 10 秋季更新后（2017.10.19）小狼毫输入法频繁弹出服务进程启动不起来，截图在下一条补上
从 Win 7 一直到上一个大版本 Win 10, 没有出错过，这次报错了，被小狼毫宠坏已经找不到替代的输入法，不知道有没有和我一样出问题的朋友？希望开发者能关注

**Comment by SJTUboy** [comment]
![image](https://user-images.githubusercontent.com/13373715/31734699-293bc548-b472-11e7-9a02-2248ced25a58.png)

**Comment by SJTUboy** [comment]
![image](https://user-images.githubusercontent.com/13373715/31734824-7ea37314-b472-11e7-96b2-694a53a518a5.png)

**Comment by SJTUboy** [comment]
上面中文是我在 MacBook 里面打的

**Comment by SJTUboy** [comment]
https://github.com/rime/home/issues/25
这个 issue 我有看，感觉不是很理解实操上怎么解决

**Comment by Prcuvu** [comment]
> rime/home#25
> 这个 issue 我有看，感觉不是很理解实操上怎么解决

建议改用[osfans/PRIME](https://github.com/osfans/PRIME)。

**Comment by SJTUboy** [comment]
谢谢！我先去试试

**Comment by SJTUboy** [comment]
感謝！問題已經解決，正在把 rimr 設置轉移過去，關於配置轉移，大家可以參考這兩個鏈接
https://mind.momok.xyz/archives/replace-rime-ime-with-prime.html
http://blog.royink.li/post/prime
希望對其他朋友有幫助
