### ISSUE TITLE
帶陰影窗口的位置

### ISSUE THREAD

**Issue by ywxt** [rime/weasel#920]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本:Windows 11 22H2 19045.2965
 - 小狼豪版本: 0.15.0.0

**描述遇到的问题**
當使用`shadow_offset_x/y`把陰影向左和上移時，候選窗口位置的計算包含了陰影，實際的效果看起來就是 border 之內的部分向右下移動了。

**复现步骤**

```yaml
style/layout/shadow_offset_x: -1
style/layout/shadow_offset_y: -1
```

**预期行为**
候選窗口起始座標不應該包括陰影大小。

**Comment by fxliang** [comment]
因为阴影偏移可调，您期待的状态，会有其他用户会说阴影不应该盖住输入的位置，那如何是好？

**Comment by ywxt** [comment]
我調整x是陰影默認偏右的。不理解爲什麼會這樣設計。



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2023年6月9日(週五) 下午3:48
收件人： ***@***.***&gt;;
抄送： "Cui ***@***.******@***.***&gt;;
主旨： Re: [rime/weasel] 帶陰影窗口的位置 (Issue #920)




 
因为阴影偏移可调，您期待的状态，会有其他用户会说阴影不应该盖住输入的位置，那如何是好？

**Comment by ywxt** [comment]
鼠須管的陰影是上面無陰影，左右陰影是對稱的，爲什麼不這麼設計呢。



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2023年6月9日(週五) 下午3:48
收件人： ***@***.***&gt;;
抄送： "Cui ***@***.******@***.***&gt;;
主旨： Re: [rime/weasel] 帶陰影窗口的位置 (Issue #920)




 
因为阴影偏移可调，您期待的状态，会有其他用户会说阴影不应该盖住输入的位置，那如何是好？

**Comment by ywxt** [comment]
> > 我調整x是陰影默認偏右的。不理解爲什麼會這樣設計。
> 
> 保证阴影可见，让候选窗口尽量接近输入位置，同时避免阴影遮盖输入行的内容而影响输入周边的内容显示。
> 
> > 鼠須管的陰影是上面無陰影，左右陰影是對稱的，爲什麼不這麼設計呢。
> 
> 你要左右对称的时候，只要将shadow_offset_x和shadow_offset_y都设置为0即可，当然这个时候上下也是有阴影的，这时阴影的宽度取决于shadow_radius的大小。

明白了，多謝。
