### ISSUE TITLE
小狼毫 0.15.0 误报病毒声明 

### ISSUE THREAD

**Issue by determ1ne** [rime/weasel#922]
镜像 https://github.com/rime/home/issues/1319

## 所述文件信息

若非官方渠道下载，请务必验证文件的散列值信息。

```
File name: weasel_0.15.0.0_installer.exe
MD5: 51C97A47948E06586142D5A1E8DDCA07
SHA256: 21B2B3BA19F11B308DB3C50CE343A14A42CE10331E3C0B7021850EC6726DCD10
```

## 为什么会误报病毒？

可能是在代码编写的过程中，某些特殊的行为触发了部分较为敏感杀毒软件的特征码检测，导致报毒。

## 是否存在编译过程中的污染问题/是否真的有可能被病毒污染？

1. 代码使用 GitHub Actions 进行编译和发布版本，过程可供人工审计： https://github.com/rime/weasel/actions/runs/5189059536
2. virustotal 检测结果为 `24/71` ，大部分杀毒软件没有报毒。（病毒对应的是大部分杀毒软件报毒）
3. 部分杀毒软件已将安装程序与 WeaselServer 列入白名单：
  - Symantec: 提交编号 334527 ，需 RAPID RELEASE sequence >= 228309
  - Windows Defender: 经检查无毒，已列入排除名单。但微软给出的升级定义方法貌似无法完全解决报毒问题（可能是 WD 的 Bug ）

## 目前的情况：

安装程序、 WeaselServer 与 WeaselSetup 均会被报毒。其中 WeaselSetup 报毒较少。

部分杀毒软件（如 MAX ）在删掉 WeaselSetup 里的某些功能后，报不报毒取决于程序中的字符串常量删没删。。

## 目前采取的措施？

如果您是个人用户，请将软件列入白名单，或继续使用 0.14.3 版本程序；
如果您是企业用户，请继续使用 0.14.3 版本程序。

## 之后会采取的措施？

下一个版本发布前，会先尽力查找是哪一部分代码引入的问题并进行修改。

话虽如此，但 Weasel 0.14.3 版本的程序再次编译出的产物，仍会被部分杀毒软件报毒。历史上小狼毫的新版本也曾经被各种报毒。

0.14.3 版本时间较长（2019年的版本），各种杀毒软件可能含有其散列值的白名单；而小狼毫没有付费购买才能使用的程序数字签名，在部分杀毒软件中被评为病毒的机率更大。

如果查找不出代码上的问题，那就只能在每次发布后先人工送入几个较为流行杀毒软件的误报通道，再延迟发布了

**Comment by Techince** [comment]
我在本机编译的时候，WinSparkle.dll会引起算法服务自动启动。不过我编译的64位，32位那个dll加载不到算法服务的地址空间中。换上自己编译的64位dll后就正常了。

**Comment by Techince** [comment]
![image](https://github.com/rime/weasel/assets/12376669/15b21fa2-a3ea-416d-9d73-588eab2685ee)

**Comment by manyfew** [comment]
我也是，火狐直接不让我下载，说有病毒。

**Comment by bcegkmqs23** [comment]
我WeaselServer直接被干掉了，我还郁闷了半天怎么突然输入法坏了

**Comment by 1wingedangel** [comment]
最近发现小狼毫 0.15.0 在32位程序上使用的时候，位于 `c:\Windows\SysWOW64\weasel.dll` 的文件被 Windows Defender 误杀，需要重新把 `weasel.dll` 复制回去、在安装选项里删除输入法再安装输入法，重启32位程序后才会正常。

然后重启系统之后 dll 又被隔离删除了……如此循环。

系统是 Windows 11 23H2 专业工作站版。

**Comment by fxliang** [comment]
> 最近发现小狼毫 0.15.0 在32位程序上使用的时候，位于 `c:\Windows\SysWOW64\weasel.dll` 的文件被 Windows Defender 误杀，需要重新把 `weasel.dll` 复制回去、在安装选项里删除输入法再安装输入法，重启32位程序后才会正常。
> 
> 然后重启系统之后 dll 又被以另一个木马的名称隔离删除了……如此循环。
> 
> 系统是 Windows 11 23H2 专业工作站版。

代码是公开的，无添加木马（不会:）,添加信任即可

**Comment by 1wingedangel** [comment]
> > 最近发现小狼毫 0.15.0 在32位程序上使用的时候，位于 `c:\Windows\SysWOW64\weasel.dll` 的文件被 Windows Defender 误杀，需要重新把 `weasel.dll` 复制回去、在安装选项里删除输入法再安装输入法，重启32位程序后才会正常。
> > 然后重启系统之后 dll 又被以另一个木马的名称隔离删除了……如此循环。
> > 系统是 Windows 11 23H2 专业工作站版。
> 
> 代码是公开的，无添加木马（不会:）,添加信任即可

我没有这方面的担心，只是每次启动系统后打开32位程序，Windows Defender就把这个dll删除掉，就很麻烦……

如下图，每次允许威胁之后把dll重新贴回去，重启系统之后又一另一个名称又被隔离，然后我又得再次允许威胁再重新贴回去……

![image](https://github.com/rime/weasel/assets/396190/92177134-1c19-472b-88ca-a05b569ac278)

**Comment by 1wingedangel** [comment]
补充一下信息：打开64位程序时没有这个问题，小狼毫可以正常使用，Windows Defender 也没有误报。这点貌似和 #1079 完全相反。

**Comment by fxliang** [comment]
#1121 可以试试这个PR的产物（产出32/64兼容包安装时自动根据系统安装），或者有变化？

**Comment by 1wingedangel** [comment]
> #1121 可以试试这个PR的产物（产出32/64兼容包安装时自动根据系统安装），或者有变化？

好，有时间的话我试一试。

**Comment by fxliang** [comment]
https://support.microsoft.com/zh-cn/windows/%E5%B0%86%E6%8E%92%E9%99%A4%E9%A1%B9%E6%B7%BB%E5%8A%A0%E5%88%B0-windows-%E5%AE%89%E5%85%A8%E4%B8%AD%E5%BF%83-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by fxliang** [comment]
可以试试最新nightly 构建，tsf dll已经显著减少误报了（通过用vs2019构建）
https://www.virustotal.com/gui/file/c863c5e6fc0e4c897aaeabfa7334bd3419e85724be0d074dca75b0830bc74353?nocache=1
![image](https://github.com/rime/weasel/assets/4023160/f9f7a83f-98cf-4a18-8b36-b049c41c244d)

**Comment by JMichaelKane** [comment]
我的也是报毒

**Comment by jk9112605** [comment]
我最近申請小狼毫在公司使用，但是IT把weasel-0.16.3.0-installer.exe放到virustotal跑出以下結果
https://www.virustotal.com/gui/file/efa114b20a8cda39c34316cd1a9b5ed25ac0581891aa3e485c830ff7cc2dbdd9/behavior
因為有兩個issues，所以被否決了…
![Image](https://github.com/user-attachments/assets/ece3066b-1a19-4d9e-aaea-364fa80beaa3)

我也用0.14.3跑過，還是有issue
好可惜，不知道是否有什麼解法? 
請成功在公司使用的朋友分享一下經驗，謝謝。

我是個小鶴雙拼+繁體輸出 的使用者，若有其它替代方案(付費的也行，只要可在公司使用即可)也歡迎提供，謝謝。

**Comment by lotem** [comment]
> 是否有什麼解法?

從本機編譯
