### ISSUE TITLE
输入框出现多余空白宽度

### ISSUE THREAD

**Issue by Qeynos** [rime/weasel#923]
**操作系统信息**
 - OS 详细版本:Windows 10 22H2 19045.2965
 - 小狼豪版本: 0.15.0.0

**描述遇到的问题**
候选框右侧出现不必要的多余空白，在0.14.3版本没有出现
尝试过调整layout中的参数没有解决

**复现步骤**
任意超过最小宽度输入时均可实现

**预期行为**
这是虚拟机中0.14.3纯净安装后的状态
![截图_20230610105850](https://github.com/rime/weasel/assets/28810097/454664a8-f942-4910-be36-968e66dd1a10)

这是实机安装并配置好的0.15.0.0的状态（实际在虚拟机中也纯净安装试验过，是一样的现象）
![截图_20230610105208](https://github.com/rime/weasel/assets/28810097/759cd53d-ad99-4e1c-8b8a-cd8507519059)

**Comment by fxliang** [comment]
这个是留给翻页符的位置，不显示的时候是应该减掉的。迟些改了。

**Comment by fxliang** [comment]
@Qeynos 留意这个构建的产出，应该已经解决了您提到的这个bug了，找时间再提PR。
https://github.com/fxliang/weasel/actions/runs/5235685888
![image](https://github.com/rime/weasel/assets/4023160/775b47e5-76fc-426e-b3ce-b55f604bd58b)

**Comment by Qeynos** [comment]
确实已解决，感谢
