### ISSUE TITLE
显示托盘图标功能好像具备缺陷

### ISSUE THREAD

**Issue by ls148478** [rime/weasel#925]
如标题所说 如果设置 display_tray_icon = false
那么在托盘图标里的设置 例如重新部署，退出等功能 诸如此类 应该如何触发

例如把 display_tray_icon 设置为false 的情况下
想改变设置的时候 应该如何找到重新部署这个功能来修改所运行的配置呢

我尝试关闭 **WeaselServer.exe** 进程结束 但是这没有起作用

**Comment by fxliang** [comment]
如果设置display_tray_icon: false，则相应的菜单在语言栏的按钮上实现右键弹出对应的菜单。

如果您将语言栏关闭了的话，是有可能看不见这个按钮的。留意确认。

![langbarbutton](https://github.com/rime/weasel/assets/4023160/cbecdccb-29b5-44e4-879a-531e67541958)

**Comment by ls148478** [comment]
> 如果设置display_tray_icon: false，则相应的菜单在语言栏的按钮上实现右键弹出对应的菜单。
> 
> 如果您将语言栏关闭了的话，是有可能看不见这个按钮的。留意确认。
> 
> ![langbarbutton](https://user-images.githubusercontent.com/4023160/245013348-cbecdccb-29b5-44e4-879a-531e67541958.gif)

了解了 想不到还可以这样
