### ISSUE TITLE
win10 1709安装一直卡在运行: "C:\Program Files\Rime\weasel-0.9.30\WeaselSetup.exe" /i

### ISSUE THREAD

**Issue by pongfcnkl** [rime/weasel#93]
![qq 20171020131654](https://user-images.githubusercontent.com/24273319/31806255-25e4f6da-b599-11e7-8fc8-489dba326491.png)
如图所示

**Comment by lotem** [comment]
現在已經過了 10 個小時，還沒有完成進度嘛？
