### ISSUE TITLE
在Blender软件中使用异常

### ISSUE THREAD

**Issue by lingchuanbo** [rime/weasel#931]
**操作系统信息**
 - OS 详细版本: Windows 10 LTSC 2021
 - 小狼豪版本:  0.15.0.0 

**描述遇到的问题**
在Blender软件中使用异常，异常表现为英文输入使该软件快捷键失效，输入状态无法正常输出。

**复现步骤**
重现问题的步骤，如：
1. 打开Blender软件
2. 切换输入状态为英文操作

**Comment by Techince** [comment]
https://github.com/Techince/weasel/releases/tag/weasel-0.15.0.0_x64
试下新修的这个版本正不正常。

**Comment by lingchuanbo** [comment]
还是异常状态，卸载重装后还是异常,  英文不能输入，新测试发现 在输入状态下 切换至英文输入 会导致与shift相关快捷键失效，比如常用快捷键shift+a

**Comment by fxliang** [comment]
目前的英文状态下确实存在无法输入英文字母的问题，可以这样处理：禁用小狼毫输入法，如需输入中文时使用CTRL+SPACE切换，使用完之后建议切换到禁用状态即可正常。
```yaml
  app_options:
    blender.exe:
      ascii_mode: true
```

关于快捷键，如shift+a，请使焦点离开输入框，即可
![image](https://github.com/rime/weasel/assets/4023160/2e6ae356-6f18-467e-9e5c-28e01f9391fd)
