### ISSUE TITLE
小狼毫在特定三拼方案下，会导致光标所在程序崩溃

### ISSUE THREAD

**Issue by shitlime** [rime/weasel#935]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 8.1 Windows10 Windows11 都能复现
 - 小狼豪版本:  0.15.0

**描述遇到的问题**
使用小狼毫输入某些音节（例：输入uru（对应方案中的拼音xu4））导致当前输入光标所在的程序崩溃

**复现步骤**
重现问题的步骤，如：
1. 打开 '记事本' 软件
2. 输入 'uru'
3. 光标所在程序崩溃

**预期行为**
预期能正常输入，光标所在程序不会崩溃

**视频**
触发bug的视屏如下，环境是win8.1（在win10、win11中也能复现）
![video 视频](https://github.com/rime/weasel/assets/31384673/5bc20a0a-55f2-4ba8-96f3-e592e9aab478)

**方案文件打包**
[rime.zip](https://github.com/rime/weasel/files/11741063/rime.zip)

**其他补充说明**
+ 这个方案还有一些其他的音节也能复现该bug，如拼音dong1，ji4（分别对应输入码：dpg，jri）但这两个复现概率比较低
+ 在%TEMP%下，没有任何ERROR log

**Comment by shitlime** [comment]
附：
Log文件
[rime.weasel.WIN-QNP09UV8S7H.test.log.INFO.20230614-111205.3256.log](https://github.com/rime/weasel/files/11741295/rime.weasel.WIN-QNP09UV8S7H.test.log.INFO.20230614-111205.3256.log)
[rime.weasel.WIN-QNP09UV8S7H.test.log.WARNING.20230614-111205.3256.log](https://github.com/rime/weasel/files/11741296/rime.weasel.WIN-QNP09UV8S7H.test.log.WARNING.20230614-111205.3256.log)

**Comment by mirtlecn** [comment]
关联 #897 

设置 "style/inline_preedit": true 可解

**Comment by Techince** [comment]
> 

这个方法确实有效。

**Comment by Techince** [comment]
> 关联 #897
> 
> 应该也是方案用到的某个特殊字符 + Weasel 插入空格的问题。在 weasel.yaml 设置 "style/inline_preedit": true 可以解决

这个方法确实有效。

**Comment by shitlime** [comment]
> 关联 #897
> 
> 应该也是方案用到的某个特殊字符 + Weasel 插入空格的问题。在 weasel.yaml 设置 "style/inline_preedit": true 可以解决

有效，感谢

**Comment by fxliang** [comment]
![image](https://github.com/rime/weasel/assets/4023160/366bb563-6814-453f-ab59-366d2349013b)
你们都是错的，是方案文件243行有鬼
