### ISSUE TITLE
候选字前面的数字序号偏大，而且有点模糊

### ISSUE THREAD

**Issue by FanXiangTM** [rime/weasel#941]
序号与候选字字体大小不一样,像是DPI缩放比例不一致。候选字前面的数字序号偏大，而且有点模糊。这个问题是升级到0.15以后出现的

![image.png](https://pic7.58cdn.com.cn/nowater/webim/big/n_v255a0d9182b724126ad25cfb334cc7c51.png)

--------------------------------------

已经搞明白，是因为配置里面没有配置前面数字序号的字体大小，默认大小好像是 14，而我指定了候选字的字体大小是11

**Comment by mirtlecn** [comment]
无法复现，看下生成的 default.yaml 和 weasel.yaml 配置

**Comment by fxliang** [comment]
如无眼拙，您用的应该是Emoji字体中的数字glyph，如下图我设定style/label_font_face: Noto Color Emoji SVG，就会有类似您的状态，如果背景色是浅色的话，就会有一点看不清的感觉maybe. 解决方案是调整style/label_font_face的设定

![image](https://github.com/rime/weasel/assets/4023160/4932dab6-6e01-4571-b437-175ef99d186e)

**Comment by FanXiangTM** [comment]
> 如无眼拙，您用的应该是Emoji字体中的数字glyph，如下图我设定style/label_font_face: Noto Color Emoji SVG，就会有类似您的状态，如果背景色是浅色的话，就会有一点看不清的感觉maybe. 解决方案是调整style/label_font_face的设定
> 
> ![image](https://user-images.githubusercontent.com/4023160/246062683-4932dab6-6e01-4571-b437-175ef99d186e.png)

我的情况跟您这个截图上的情况应该有所区别。仔细观察我大的截图会发现，数字和候选字的底部没有对齐。您这个情况是数字发粗，但是跟候选字一样大

**Comment by FanXiangTM** [comment]
> 无法复现，看下生成的 default.yaml 和 weasel.yaml 配置

default.yaml ：
__build_info:
  rime_version: 1.8.5
  timestamps:
    default: 1686057630
    default.custom: 1655012409
    key_bindings: 1686057630
    key_bindings.custom: 0
    punctuation: 1686057630
    punctuation.custom: 0
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Shift_L: commit_code
    Shift_R: commit_code
config_version: 0.40
key_binder:
  bindings:
    - {accept: "Control+p", send: Up, when: composing}
    - {accept: "Control+n", send: Down, when: composing}
    - {accept: "Control+b", send: Left, when: composing}
    - {accept: "Control+f", send: Right, when: composing}
    - {accept: "Control+a", send: Home, when: composing}
    - {accept: "Control+e", send: End, when: composing}
    - {accept: "Control+d", send: Delete, when: composing}
    - {accept: "Control+k", send: "Shift+Delete", when: composing}
    - {accept: "Control+h", send: BackSpace, when: composing}
    - {accept: "Control+g", send: Escape, when: composing}
    - {accept: "Control+bracketleft", send: Escape, when: composing}
    - {accept: "Control+y", send: Page_Up, when: composing}
    - {accept: "Alt+v", send: Page_Up, when: composing}
    - {accept: "Control+v", send: Page_Down, when: composing}
    - {accept: ISO_Left_Tab, send: "Shift+Left", when: composing}
    - {accept: "Shift+Tab", send: "Shift+Left", when: composing}
    - {accept: Tab, send: "Shift+Right", when: composing}
    - {accept: minus, send: Page_Up, when: has_menu}
    - {accept: equal, send: Page_Down, when: has_menu}
    - {accept: comma, send: Page_Up, when: paging}
    - {accept: period, send: Page_Down, when: has_menu}
    - {accept: "Control+Shift+1", select: .next, when: always}
    - {accept: "Control+Shift+2", toggle: ascii_mode, when: always}
    - {accept: "Control+Shift+3", toggle: full_shape, when: always}
    - {accept: "Control+Shift+4", toggle: simplification, when: always}
    - {accept: "Control+Shift+5", toggle: extended_charset, when: always}
    - {accept: "Control+Shift+exclam", select: .next, when: always}
    - {accept: "Control+Shift+at", toggle: ascii_mode, when: always}
    - {accept: "Control+Shift+numbersign", toggle: full_shape, when: always}
    - {accept: "Control+Shift+dollar", toggle: simplification, when: always}
    - {accept: "Control+Shift+percent", toggle: extended_charset, when: always}
menu:
  page_size: 8
punctuator:
  full_shape:
    " ": {commit: "　"}
    "!": {commit: "！"}
    "\"": {pair: ["“", "”"]}
    "#": ["＃", "⌘"]
    "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]
    "%": ["％", "°", "℃"]
    "&": "＆"
    "'": {pair: ["‘", "’"]}
    "(": "（"
    ")": "）"
    "*": ["＊", "·", "・", "×", "※", "❂"]
    "+": "＋"
    ",": {commit: "，"}
    "-": "－"
    .: {commit: "。"}
    "/": ["／", "÷"]
    ":": {commit: "："}
    ";": {commit: "；"}
    "<": ["《", "〈", "«", "‹"]
    "=": "＝"
    ">": ["》", "〉", "»", "›"]
    "?": {commit: "？"}
    "@": ["＠", "☯"]
    "[": ["「", "【", "〔", "［"]
    "\\": ["、", "＼"]
    "]": ["」", "】", "〕", "］"]
    "^": {commit: "……"}
    _: "——"
    "`": "｀"
    "{": ["『", "〖", "｛"]
    "|": ["·", "｜", "§", "¦"]
    "}": ["』", "〗", "｝"]
    "~": "～"
  half_shape:
    "!": {commit: "！"}
    "\"": {pair: ["“", "”"]}
    "#": "#"
    "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]
    "%": ["%", "％", "°", "℃"]
    "&": "&"
    "'": {pair: ["‘", "’"]}
    "(": "（"
    ")": "）"
    "*": ["*", "＊", "·", "・", "×", "※", "❂"]
    "+": "+"
    ",": {commit: "，"}
    "-": "-"
    .: {commit: "。"}
    "/": ["、", "/", "／", "÷"]
    ":": {commit: "："}
    ";": {commit: "；"}
    "<": ["《", "〈", "«", "‹"]
    "=": "="
    ">": ["》", "〉", "»", "›"]
    "?": {commit: "？"}
    "@": "@"
    "[": ["「", "【", "〔", "［"]
    "\\": ["、", "\\", "＼"]
    "]": ["」", "】", "〕", "］"]
    "^": {commit: "……"}
    _: "——"
    "`": "`"
    "{": ["『", "〖", "｛"]
    "|": ["·", "|", "｜", "§", "¦"]
    "}": ["』", "〗", "｝"]
    "~": ["~", "～"]
recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
schema_list:
  - schema: luna_pinyin_simp
  - schema: easy_en
switcher:
  abbreviate_options: true
  caption: "〔方案選單〕"
  fold_options: true
  hotkeys:
    - "Control+grave"
    - "Control+Shift+grave"
    - F4
  option_list_separator: "／"
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
    - zh_hant
    - zh_hans
    - zh_hant_tw


weasel.yaml：
__build_info:
  rime_version: 1.8.5
  timestamps:
    weasel: 1686057548
    weasel.custom: 1686832875
app_options:
  cmd.exe:
    ascii_mode: true
  conhost.exe:
    ascii_mode: true
  i_view64.exe:
    ascii_mode: true
  onenote.exe:
    ascii_mode: true
  studio64.exe:
    ascii_mode: true
config_version: 0.22
preset_color_schemes:
  FanXiang:
    author: FanXiang
    back_color: 0xEFEFEF
    border_color: 0xD4D4D4
    candidate_text_color: 0x1C1C1D
    comment_text_color: 0x1C1C1D
    hilited_back_color: 0xEFEFEF
    hilited_candidate_back_color: 0xCE7539
    hilited_candidate_text_color: 0xFFFFFF
    hilited_text_color: 0x1C1C1D
    name: JiJian
    text_color: 0x1C1C1D
  android:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x99731c
    border_color: 0x99731c
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0x99731c
    hilited_candidate_back_color: 0x50c4a8
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0x50c4a8
    label_color: 0xc18835
    name: "安卓／Android"
    text_color: 0xffffff
  aqua:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xeceeee
    border_color: 0xe0e0e0
    candidate_back_color: 0xeceeee
    candidate_shadow_color: 0x00000000
    candidate_text_color: 0x000000
    hilited_back_color: 0xd4d4d4
    hilited_candidate_back_color: 0xfa3a0a
    hilited_candidate_shadow_color: 0x00000000
    hilited_candidate_text_color: 0xffffff
    hilited_shadow_color: 0x00000000
    hilited_text_color: 0x000000
    name: "碧水／Aqua"
    shadow_color: 0x00000000
    text_color: 0x000000
  azure:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0x8b4e01
    border_color: 0x8b4e01
    candidate_text_color: 0xfff8ee
    comment_text_color: 0xc69664
    hilited_back_color: 0x8b4e01
    hilited_candidate_back_color: 0xa95e01
    hilited_candidate_text_color: 0x7ffeff
    hilited_text_color: 0xfff8ee
    name: "青天／Azure"
    text_color: 0xffe8ca
  brasil:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x559311
    border_color: 0x559311
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0x7d3617
    hilited_candidate_back_color: 0x16c7f7
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0xffffff
    label_color: 0xffffff
    name: "笆悉／Brasil"
    text_color: 0xffffff
  brisk:
    author: "skoj <skoj@qq.com>"
    back_color: 0xffffff
    border_color: 0x333333
    candidate_text_color: 0x575757
    hilited_back_color: 0xffffff
    hilited_candidate_back_color: 0xffffff
    hilited_candidate_text_color: 0x2238dc
    hilited_text_color: 0x2238dc
    name: "輕盈／Brisk"
    text_color: 0x2238dc
  cool_breeze:
    author: "skoj <skoj@qq.com>"
    back_color: 0xFFFBFB
    border_color: 0xFFAAAA
    candidate_text_color: 0x009100
    hilited_back_color: 0xFFFBFB
    hilited_candidate_back_color: 0xFFD6AC
    hilited_candidate_text_color: 0x6F003A
    hilited_text_color: 0x0000CE
    name: "清風／Cool Breeze"
    text_color: 0x0000FF
  dark_temple:
    author: "佛振 <chen.sst@gmail.com>, based on ir_black"
    back_color: 0x222222
    border_color: 0x222222
    candidate_text_color: 0xd8e3e6
    comment_text_color: 0x606cff
    hilited_back_color: 0x222222
    hilited_candidate_back_color: 0x333333
    hilited_candidate_text_color: 0x92f6da
    hilited_text_color: 0xffcf9a
    name: "暗堂／Dark Temple"
    text_color: 0x92f6da
  doraemon:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0xffffff
    border_color: 0xe89f00
    candidate_text_color: 0xe89f00
    comment_text_color: 0xe89f00
    hilited_back_color: 0x1200e5
    hilited_candidate_back_color: 0xe89f00
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0xffffff
    label_color: 0xe89f00
    name: "銅鑼衛門／Doraemon"
    text_color: 0x1200e5
  dota_2:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x120f10
    border_color: 0x120f10
    candidate_text_color: 0x5c758f
    comment_text_color: 0x5c758f
    hilited_back_color: 0x120f10
    hilited_candidate_back_color: 0x1841dd
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0x1841dd
    label_color: 0x5c758f
    name: "DOTA 2"
    text_color: 0xffffff
  espagna:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x230dc3
    border_color: 0x230dc3
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0x2cb5f7
    hilited_candidate_back_color: 0x2cb5f7
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0xffffff
    label_color: 0xffffff
    name: "埃斯巴尼亞／España"
    text_color: 0xffffff
  flypy:
    author: "Pal.lxk <Pal.lxk@gmail.com>"
    back_color: 0xffffff
    border_color: 0xc6c6c6
    candidate_text_color: 0xff8000
    comment_text_color: 0xff8000
    hilited_back_color: 0xffffff
    hilited_candidate_back_color: 0xffffff
    hilited_candidate_text_color: 0x0000b0
    hilited_comment_text_color: 0x0000b0
    hilited_text_color: 0xff8000
    label_color: 0xff8000
    name: "小鹤飞扬／flypy"
    text_color: 0x000000
  gholabok:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x2939e8
    border_color: 0x2939e8
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0x437b00
    hilited_candidate_back_color: 0x3d6ded
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0xffffff
    label_color: 0xffffff
    name: "胡蘿菔／Gholabok"
    text_color: 0xffffff
  google:
    author: "skoj <skoj@qq.com>"
    back_color: 0xFFFFFF
    border_color: 0xE2E2E2
    candidate_text_color: 0x000000
    hilited_back_color: 0xFFFFFF
    hilited_candidate_back_color: 0xCE7539
    hilited_candidate_text_color: 0xFFFFFF
    hilited_text_color: 0x000000
    name: "谷歌／Google"
    text_color: 0x666666
  google_plus:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0xffffff
    border_color: 0x394bdd
    candidate_text_color: 0x394bdd
    comment_text_color: 0xcac9c8
    hilited_back_color: 0xffffff
    hilited_candidate_back_color: 0x394bdd
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0x394bdd
    label_color: 0xcac9c8
    name: "Google+"
    text_color: 0xcac9c8
  ink:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xffffff
    border_color: 0x000000
    hilited_back_color: 0xdddddd
    hilited_candidate_back_color: 0x000000
    hilited_candidate_text_color: 0xffffff
    hilited_text_color: 0x000000
    name: "墨池／Ink"
    text_color: 0x000000
  kuma_shuzboz:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x2db6f8
    border_color: 0x2db6f8
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0xffffff
    hilited_candidate_back_color: 0x000000
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0x2db6f8
    label_color: 0xffffff
    name: "熊出沒／Kuma Shuzboz"
    text_color: 0x000000
  kuon:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x70b33e
    border_color: 0x70b33e
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0xffffff
    hilited_candidate_back_color: 0xffffff
    hilited_candidate_text_color: 0x70b33e
    hilited_comment_text_color: 0x70b33e
    hilited_text_color: 0x70b33e
    label_color: 0xffffff
    name: "琨／Kuon"
    text_color: 0xffffff
  lost_temple:
    author: "佛振 <chen.sst@gmail.com>, based on ir_black"
    back_color: 0x444444
    border_color: 0x444444
    hilited_back_color: 0x222222
    hilited_candidate_back_color: 0x82e6ca
    hilited_candidate_text_color: 0x000000
    hilited_text_color: 0x82e6ca
    name: "孤寺／Lost Temple"
    text_color: 0xe8f3f6
  lost_temple_with_shadow:
    author: "佛振 <chen.sst@gmail.com>, based on ir_black"
    back_color: 0x444444
    border_color: 0x444444
    hilited_back_color: 0x222222
    hilited_candidate_back_color: 0x82e6ca
    hilited_candidate_text_color: 0x000000
    hilited_text_color: 0x82e6ca
    name: "孤寺／Lost Temple"
    text_color: 0xe8f3f6
  luna:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xffffff
    border_color: 0xcccccc
    hilited_back_color: 0x7fffff
    hilited_candidate_back_color: 0x000000
    hilited_candidate_text_color: 0xffffff
    hilited_text_color: 0x000000
    name: "明月／Luna"
    text_color: 0x000000
  macau:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x81a300
    border_color: 0x81a300
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0x00d9ff
    hilited_candidate_back_color: 0xffffff
    hilited_candidate_text_color: 0x00d9ff
    hilited_comment_text_color: 0x00d9ff
    hilited_text_color: 0xffffff
    label_color: 0xffffff
    name: "澳門／Macau"
    text_color: 0x00d9ff
  metroblue:
    author: "Prcuvu <prcuvu@gmail.com>"
    back_color: 0xffffff
    border_color: 0xd77800
    candidate_text_color: 0x000000
    comment_text_color: 0x000000
    hilited_back_color: 0xffffff
    hilited_candidate_back_color: 0xd77800
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_label_color: 0xffffff
    hilited_text_color: 0x000000
    label_color: 0x838383
    name: "现代蓝／Metro Blue"
    text_color: 0x000000
  modern_warfare:
    author: P1461
    back_color: 0x0a1b0d
    border_color: 0x4bad83
    candidate_text_color: 0xabfedc
    comment_text_color: 0xfcfdfb
    hilited_back_color: 0x030e06
    hilited_candidate_back_color: 0x676f63
    hilited_candidate_text_color: 0xabfedc
    hilited_text_color: 0xfbfdfc
    name: "現代戰爭／Modern Warfare"
    text_color: 0x14bc70
  nba:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0xb76a00
    border_color: 0xb76a00
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0xffffff
    hilited_candidate_back_color: 0x541ed7
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0x541ed7
    label_color: 0xffffff
    name: NBA
    text_color: 0xffffff
  ps4:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x000000
    border_color: 0x000000
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0x575759
    hilited_candidate_back_color: 0xe89f00
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0xffffff
    label_color: 0xffffff
    name: "遊驛四／PS4"
    text_color: 0xffffff
  psionics:
    author: "雨過之後、佛振"
    back_color: 0x444444
    border_color: 0x444444
    candidate_text_color: 0xeeeeee
    comment_text_color: 0x808080
    hilited_back_color: 0x444444
    hilited_candidate_back_color: 0xd8bf00
    hilited_candidate_label_color: 0xfafafa
    hilited_candidate_text_color: 0xfafafa
    hilited_comment_text_color: 0x444444
    hilited_text_color: 0xeeeeee
    name: "幽能／Psionics"
    text_color: 0xc2c2c2
  skype:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0xefad00
    border_color: 0xefad00
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0xffffff
    hilited_candidate_back_color: 0xffffff
    hilited_candidate_text_color: 0xefad00
    hilited_comment_text_color: 0xefad00
    hilited_text_color: 0xefad00
    label_color: 0xffffff
    name: "斯蓋普／Skype"
    text_color: 0xffffff
  smurfs:
    author: "skoj <skoj@qq.com>"
    back_color: 0xbf7817
    border_color: 0xf5ede0
    candidate_text_color: 0xf6f6f6
    comment_text_color: 0xf6f6f6
    hilited_back_color: 0xbf7817
    hilited_candidate_back_color: 0xdbbc6d
    hilited_candidate_text_color: 0xf6f6f6
    hilited_comment_text_color: 0xf6f6f6
    hilited_text_color: 0xdbbc6d
    label_color: 0xbf7817
    name: "藍精靈／Smurfs"
    text_color: 0xffffff
  so_young:
    author: "五磅兔 <zcunlin@foxmail.com>"
    back_color: 0xe3f6fd
    border_color: 0xd5e8ee
    candidate_text_color: 0x837b65
    comment_text_color: 0xd28b26
    hilited_back_color: 0xd5e8ee
    hilited_candidate_back_color: 0x98a12a
    hilited_candidate_text_color: 0xd5e8ee
    hilited_comment_text_color: 0xd5e8ee
    hilited_text_color: 0x969483
    label_color: 0xa1a193
    name: "致青春／So Young"
    text_color: 0x8236d3
  solarized_rock:
    author: "Aben <tntaben@gmail.com>, based on Ethan Schoonover's Solarized color scheme"
    back_color: 0x362b00
    border_color: 0x362b00
    candidate_text_color: 0x969483
    hilited_candidate_back_color: 0x8236d3
    hilited_candidate_text_color: 0xffffff
    hilited_text_color: 0x98a12a
    name: "曬經石／Solarized Rock"
    text_color: 0x009985
  starcraft:
    author: "Contralisk <contralisk@gmail.com>, original artwork by Blizzard Entertainment"
    back_color: 0x000000
    border_color: 0x1010a0
    candidate_text_color: 0x30bb55
    hilited_back_color: 0x000000
    hilited_candidate_back_color: 0x000000
    hilited_candidate_text_color: 0x60ffa8
    hilited_text_color: 0xfecb96
    name: "星際我爭霸／StarCraft"
    text_color: 0xccaa88
  starcraft_ii:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x29190a
    border_color: 0x534b46
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0x17100a
    hilited_candidate_back_color: 0xefad1e
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0xffffff
    label_color: 0xffffff
    name: "星際爭霸Ⅱ／StarCraft Ⅱ"
    text_color: 0xffffff
  steam:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0x141617
    border_color: 0x353638
    candidate_text_color: 0xffffff
    comment_text_color: 0xa7a7a9
    hilited_back_color: 0x141617
    hilited_candidate_back_color: 0x594231
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xa7a7a9
    hilited_text_color: 0xc9cfd1
    label_color: 0xffffff
    name: Steam
    text_color: 0xcd8c52
  tintin:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0xd99500
    border_color: 0xd99500
    candidate_text_color: 0xffffff
    comment_text_color: 0xffffff
    hilited_back_color: 0xd99500
    hilited_candidate_back_color: 0x2164f1
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0xf7d891
    label_color: 0xffffff
    name: "丁丁／ Tintin"
    text_color: 0xffffff
  wii:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0xefefef
    border_color: 0xefefef
    candidate_text_color: 0x575759
    comment_text_color: 0xcac9c8
    hilited_back_color: 0xefefef
    hilited_candidate_back_color: 0xffcc33
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0xffcc33
    label_color: 0xcac9c8
    name: Wii
    text_color: 0x575759
  xbox_silver:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0xefeeee
    border_color: 0xefeeee
    candidate_text_color: 0x1fc28d
    comment_text_color: 0x1fc28d
    hilited_back_color: 0x5bf0b5
    hilited_candidate_back_color: 0x448c28
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0xffffff
    label_color: 0x5bf0b5
    name: "銀色叉盒／Xbox Silver"
    text_color: 0x1fc28d
  youtube:
    author: "Patricivs <ipatrickmac@me.com>"
    back_color: 0xdedede
    border_color: 0xdedede
    candidate_text_color: 0x000000
    comment_text_color: 0x000000
    hilited_back_color: 0xffffff
    hilited_candidate_back_color: 0x230dc3
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xffffff
    hilited_text_color: 0x230dc3
    label_color: 0x000000
    name: YouTube
    text_color: 0x000000
style:
  color_scheme: FanXiang
  comment_font_face: "Microsoft YaHei"
  comment_font_point: 14
  display_tray_icon: false
  font_face: "Microsoft YaHei"
  font_point: 11
  fullscreen: false
  horizontal: false
  inline_preedit: false
  label_font_face: "Microsoft YaHei"
  label_font_point: 14
  label_format: "%s."
  layout:
    border_width: 1
    candidate_spacing: 5
    hilite_padding: 2
    hilite_spacing: 4
    margin_x: 16
    margin_y: 16
    min_height: 0
    min_width: 160
    round_corner: 2
    spacing: 8
  mark_text: ""
  preedit_type: composition
  vertical_auto_reverse: false
  vertical_text: false
  vertical_text_left_to_right: false
  vertical_text_with_wrap: false

**Comment by fxliang** [comment]
@FanXiangTM 
凌乱的配置文件里面看到几个点，
1、候选字体大小比label的要小，前者11，后者14，所以标签字体比候选字大是你设置出来的结果
2、自行编制的配色方案，定义了候选颜色却没有定义label颜色,那标签字体颜色就会是对应候选颜色和（高亮）候选背景色的混合计算值，当然会淡

![image](https://github.com/rime/weasel/assets/4023160/85e1639f-dfb3-4cd2-84b1-4159c43905a0)

**Comment by FanXiangTM** [comment]
> 无法复现，看下生成的 default.yaml 和 weasel.yaml 配置

已经搞明白了，原来是因为数字序号的字体大小跟候选字的字体大小不一致，才导致出现这种现象。
