### ISSUE TITLE
是否能调整：通过「输入法设定」调整设置不再格式化 *.custom.yaml 文件

### ISSUE THREAD

**Issue by mirtlecn** [rime/weasel#942]
小狼毫在通过「输入方案设定」操作的时候，会把 weasel.custom.yaml 和 default.custom.yaml 里的注释、空行删除掉，是否能调整为不更改这些文件，不然不方便写配置。

另外意外发现我能改 wiki，如果是不小心的得关下。

趁机写了点🤣: https://github.com/rime/weasel/wiki/Weasel-%E5%AE%9A%E8%A3%BD%E5%8C%96

**Comment by mirtlecn** [comment]
另外，小狼毫在通过「输入方案设定」操作的时候，会把 weasel.custom.yaml 和 default.custom.yaml 里的注释、空行删除掉，是否能调整为不更改这些文件，不然不方便写配置。

**Comment by fxliang** [comment]
> 另外，小狼毫在通过「输入方案设定」操作的时候，会把 weasel.custom.yaml 和 default.custom.yaml 里的注释、空行删除掉，是否能调整为不更改这些文件，不然不方便写配置。

学我啊，在那两个文件里面__include一个外部的文件

**Comment by mirtlecn** [comment]
> > 另外，小狼毫在通过「输入方案设定」操作的时候，会把 weasel.custom.yaml 和 default.custom.yaml 里的注释、空行删除掉，是否能调整为不更改这些文件，不然不方便写配置。
> 
> 学我啊，在那两个文件里面__include一个外部的文件

我确实之前看了你的配置也这样干了👀

![image](https://github.com/rime/weasel/assets/76689045/b8bcdd75-acfe-44f5-a915-0b2b6909cb96)

但要是能直接比做这样的格式化操作更好一点，写 weasel.custom.yaml 的文档也好写一些

**Comment by yanhuacuo** [comment]
librime 需要写入文件头和版本信息，以及后面的格式这里的处理，是 `cpp-yaml` 的机制吧，建议还是 `__include` 来规避， 不往这下面写配色信息以外的东西。
