### ISSUE TITLE
在OneNote 上不显示候选框

### ISSUE THREAD

**Issue by FanXiangTM** [rime/weasel#943]
在OneNote 这款软件上打字的时候不显示候选框，但是可以输入汉字。有时候多次用Shift键、Ctrl+Space 键切换输入状态，可以恢复正常显示候选框，但是下次重新打开OneNote的时候还是不显示输入框。

**Comment by determ1ne** [comment]
尝试 ci 构建版 https://github.com/rime/weasel/suites/13629827033/artifacts/752002534

**Comment by FanXiangTM** [comment]
> 尝试 ci 构建版 [https://github.com/rime/weasel/suites/13629827033/artifacts/752002534 ](https://github.com/rime/weasel/suites/13629827033/artifacts/752002534)

这个版本已经解决了OneNote上不显示候选框的问题
