### ISSUE TITLE
firefox和相关浏览器设置页面无法输入。

### ISSUE THREAD

**Issue by lisansas** [rime/weasel#946]
无论是原版Firefox，还是各种Firefox改版，使用最新版15.0无论是release里的，actions里的，issue里那个x64版本，皆无法输入。

已经删除了Weasel.ime。

但之前使用fxliang的各种alpha版本均无此问题，上个版本也无此问题。

**Comment by fxliang** [comment]
实际上，最新的firefox里面的设置菜单中，我退回我好久以前还上传本地构建的版本，也是不行的……要再看了

**Comment by beoxgame** [comment]
win11 friefox114.0.1 复现成功。表现为选词框转瞬即逝。

**Comment by Techince** [comment]
> 

系统目录里的weasel.ime文件删除即可

**Comment by Techince** [comment]
![image](https://github.com/rime/weasel/assets/12376669/eaedbf27-955e-4425-8fcd-22f6a5736dc5)
为什么我测不出来此问题呢？

**Comment by beoxgame** [comment]
> > 
> 
> 系统目录里的weasel.ime文件删除即可
问题没有解决（四个.ime都删了也不行）。
另外：意外触发了一次火狐的[崩溃](https://crash-stats.mozilla.org/report/index/57a5782c-366f-46df-a337-250eb0230618)，已通过火狐的崩溃报告系统提交，或许可以将其中的调用栈等信息用于分析。
触发崩溃的操作为快速键入任意字母并按空格。但后面尝试复现时没有成功。

**Comment by fxliang** [comment]
新版Firefox才有这个问题，而且是设定菜单中才有这个问题，后续再看缘份解了。

**Comment by mirtlecn** [comment]
我發現 Chromium 系中 github doc 搜索欄裏也有一模一樣的情況：

![20230602112023](https://github.com/rime/weasel/assets/76689045/ccec45c6-4561-40ee-b9ec-cf198bcd677f)

**Comment by mirtlecn** [comment]
@lisansas 发现把 inline_preedit 设置成 true 就能正常输入了。不晓得是不是和那个插入空格有关系。

但还是没法在 GitHub doc 的搜索栏中正常输入。

**Comment by fxliang** [comment]
因为这个位置，firefox就不给你插入空格！自动吃掉的……

**Comment by mirtlecn** [comment]
firefox 114 的设置界面；以及 GitHub 文档界面，这个链接右上的搜索 https://docs.github.com/en @Techince

**Comment by lisansas** [comment]
> firefox 114 的设置界面；以及 GitHub 文档界面，这个链接右上的搜索 https://docs.github.com/en @Techince

这个GitHub的我倒是没问题……

**Comment by zhifuchen** [comment]
> firefox 114 的设置界面；以及 GitHub 文档界面，这个链接右上的搜索 https://docs.github.com/en @Techince

我在github docs复现了

**Comment by zhifuchen** [comment]
> > firefox 114 的设置界面；以及 GitHub 文档界面，这个链接右上的搜索 https://docs.github.com/en @Techince
> 
> ![image](https://user-images.githubusercontent.com/12376669/246854054-580b4c2d-1f0f-4193-abdd-8ba6265c9450.png) 很奇怪，还是没有触发。

我在github docs复现了,如果先输入一个空格,就可以正常输入了

**Comment by mirtlecn** [comment]
> https://github.com/fxliang/weasel/actions/runs/5310773526 只要改成一个非空格的预上屏字符就问题不大了，具体还有没有其他方法要再讨论了

空格时没有含义的，并且不会触发 Word 中对字体的自动调整。

但预上屏其他字符，在「边输入，边执行某项操作」的情况下，比如边输入，Google 自动建议，就会因为这个预输入的 `|` 搜出现 `|` 有关的建议。（实际上空格在某些应用里也是有含义的）。另外，始终会有某些输入框限定只能输入某些字符，和预上屏冲突的情况。只能说实现的不是很完美。

我看其他的输入法不需要预上屏可能是因为它用的不是 tsf 吧，用这个框架的微软输入法似乎之前去掉了这个 inline_preedit 特性了（未求证）🤣

GitHub doc 搜索无法输入可以在 chrome 系浏览器中搜索稳定复现，Firefox 中我却没法复现。

**Comment by fxliang** [comment]
微软输入法目前的方式似乎默认了inline_preedit

**Comment by lisansas** [comment]
> > https://github.com/fxliang/weasel/actions/runs/5310773526 只要改成一个非空格的预上屏字符就问题不大了，具体还有没有其他方法要再讨论了
> 
> 空格时没有含义的，并且不会触发 Word 中对字体的自动调整。
> 
> 但预上屏其他字符，在「边输入，边执行某项操作」的情况下，比如边输入，Google 自动建议，就会因为这个预输入的 `|` 搜出现 `|` 有关的建议。（实际上空格在某些应用里也是有含义的）。另外，始终会有某些输入框限定只能输入某些字符，和预上屏冲突的情况。只能说实现的不是很完美。
> 
> 我看其他的输入法不需要预上屏可能是因为它用的不是 tsf 吧，用这个框架的微软输入法似乎之前去掉了这个 inline_preedit 特性了（未求证）🤣
> 
> GitHub doc 搜索无法输入可以在 chrome 系浏览器中搜索稳定复现，Firefox 中我却没法复现。

我还在用一款名叫“影子输入法”的也是tsf框架，也挺正常的。顺便我把inline_preedit为true后问题消失了，但在而且仅在QQ频道会随机保留输入的1-2个字母。

**Comment by determ1ne** [comment]
> 小狼毫0.15.0 win11 friefox114.0.1 复现成功。表现为选词框转瞬即逝。

是否类似 #891 ？

**Comment by determ1ne** [comment]
> 我發現 Chromium 系中 github doc 搜索欄裏也有一模一樣的情況：
> 
> ![20230602112023](https://user-images.githubusercontent.com/76689045/246744003-ccec45c6-4561-40ee-b9ec-cf198bcd677f.gif)

这个问题很多输入法都有，搜狗也这样

**Comment by beoxgame** [comment]
> > 小狼毫0.15.0 win11 friefox114.0.1 复现成功。表现为选词框转瞬即逝。
> 
> 是否类似 #891 ？

不是，效果和这图里的一样：

> 我發現 Chromium 系中 github doc 搜索欄裏也有一模一樣的情況：
> 
> ![20230602112023](https://user-images.githubusercontent.com/76689045/246744003-ccec45c6-4561-40ee-b9ec-cf198bcd677f.gif)

**Comment by beoxgame** [comment]
> > firefox 114 的设置界面；以及 GitHub 文档界面，这个链接右上的搜索 https://docs.github.com/en @Techince
> 
> ![image](https://user-images.githubusercontent.com/12376669/246854054-580b4c2d-1f0f-4193-abdd-8ba6265c9450.png) 很奇怪，还是没有触发。

不确定谋智版火狐是否修改了这部分交互的代码，但我无法输入使用的是[原版火狐](https://www.mozilla.org/zh-CN/firefox/new/)

**Comment by lanyuue** [comment]
遇到类似的问题，打开google搜索框输入第一个词，rime框会固定在左上角
`"style/inline_preedit": ture` inline_preedit设置为true可以修复此问题（偶尔还会复现）
在我刚才打的这段话里，偶尔在输入了英文字符后，又会出现跳到左上角的问题

**Comment by Techince** [comment]
> 遇到类似的问题，打开google搜索框输入第一个词，rime框会固定在左上角 `"style/inline_preedit": ture` inline_preedit设置为true可以修复此问题（偶尔还会复现） 在我刚才打的这段话里，偶尔在输入了英文字符后，又会出现跳到左上角的问题
> 
> ![rime_firefox_bug](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> 
> *在edge中一切正常

Action一个新版本试试。新版本已修复此问题。

**Comment by lanyuue** [comment]
> > 遇到类似的问题，打开google搜索框输入第一个词，rime框会固定在左上角 `"style/inline_preedit": ture` inline_preedit设置为true可以修复此问题（偶尔还会复现） 在我刚才打的这段话里，偶尔在输入了英文字符后，又会出现跳到左上角的问题
> > ![rime_firefox_bug](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> >       
> >         [
> >           
> >         
> >             ![rime_firefox_bug](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> >           ](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> >         
> >       
> > *在edge中一切正常
> 
> Action一个新版本试试。新版本已修复此问题。

确实修复了 感谢

**Comment by lisansas** [comment]
> > 遇到类似的问题，打开google搜索框输入第一个词，rime框会固定在左上角 `"style/inline_preedit": ture` inline_preedit设置为true可以修复此问题（偶尔还会复现） 在我刚才打的这段话里，偶尔在输入了英文字符后，又会出现跳到左上角的问题
> > ![rime_firefox_bug](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> >       
> >         [
> >           
> >         
> >             ![rime_firefox_bug](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> >           ](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> >         
> >       
> > *在edge中一切正常
> 
> Action一个新版本试试。新版本已修复此问题。

那需要close掉吗？

**Comment by Techince** [comment]
> > > 遇到类似的问题，打开google搜索框输入第一个词，rime框会固定在左上角 `"style/inline_preedit": ture` inline_preedit设置为true可以修复此问题（偶尔还会复现） 在我刚才打的这段话里，偶尔在输入了英文字符后，又会出现跳到左上角的问题
> > > ![rime_firefox_bug](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> > >       
> > >         [
> > >           
> > >         
> > >             ![rime_firefox_bug](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> > >           ](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> > >         
> > >       
> > > ```
> > >     [
> > >       
> > >     
> > >         ![rime_firefox_bug](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> > >       ](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/33956921/251093364-c76ba698-7404-48dc-84ce-15d44cee2491.gif)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > *在edge中一切正常
> > 
> > 
> > Action一个新版本试试。新版本已修复此问题。
> 
> 那需要close掉吗？

可以关闭此问题了。
