### ISSUE TITLE
游戏【无畏契约】中被锁定为英文键盘

### ISSUE THREAD

**Issue by beoxgame** [rime/weasel#947]
**上报前请检查**
- [X] 我遇到的问题没有其他人在 issue 里提到过
- [X] 我的小狼毫版本于 rime/weasel 下载
- [X] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: 版本 22H2 (OS 内部版本 22621.1848)
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**
[无畏契约](https://val.qq.com/main.html)中所有窗口模式都无法使用输入法（表现为锁定为英文键盘并无法切换，见下图）。
![Snipaste_2023-06-18_14-39-43](https://github.com/rime/weasel/assets/136954107/6187ef1e-11e6-4f53-9585-7ae7df8d8e6c)

**复现步骤**
重现问题的步骤，如：
0. 使用中文键盘布局
1. 打开 '无畏契约' 软件并调整为窗口模式
2. 点击游戏界面的右侧边栏，点击完全展示后的右侧边栏底部的图标 打开文本输入框
3. 尝试输入中文、切换语言
5. 无法输入、键盘布局被锁定为ENG（一旦在任务栏点击其他窗口如火狐就能恢复中文键盘，再次点击【无畏契约】又被切回ENG）

**预期行为**
可正常切换键盘布局并输入

**用户文件**
刚安装，无任何自定义设置

**其他补充说明**
微软拼音可正常使用

**Comment by Techince** [comment]
点Action自动构建一个，新版本应该解决了此问题，Release那里没有更新。

**Comment by beoxgame** [comment]
> 点Action自动构建一个，新版本应该解决了此问题，Release那里没有更新。

安装[此版本](https://github.com/rime/weasel/actions/runs/5297768790)后问题解决

**Comment by beoxgame** [comment]
> 安装[此版本](https://github.com/rime/weasel/actions/runs/5297768790)后问题解决

不知道为什么时好时坏

**Comment by Techince** [comment]
> 

时好时坏具体有什么症状？

**Comment by beoxgame** [comment]
> 时好时坏具体有什么症状？

原因不明，有时候能切出中文输入，有时候切不出来。
`能否使用中文输入`这个状态，应该是随游戏进程保持的。
另外：游戏已弃坑卸载，没法进行测试了。

**Comment by Techince** [comment]
> > 时好时坏具体有什么症状？
> 
> 原因不明，有时候能切出中文输入，有时候切不出来。 `能否使用中文输入`这个状态，应该是随游戏进程保持的。 另外：游戏已弃坑卸载，没法进行测试了。

看看安装的版本，「System32」和「Windows\SysWOW64」两目录下是否存「weasel.ime」，存在的话，删除或加个扩展名，兼容性会变好。

**Comment by wx40217** [comment]
这个问题似乎又出现了 0.16.3的release版本 在游戏内切输入法始终是英文输入法
