### ISSUE TITLE
升级 0.15 后无法在 OneNote 中正常打字

### ISSUE THREAD

**Issue by b11p** [rime/weasel#948]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 11 22H2 22621.1848
 - 小狼毫版本: 0.15.0.0
 - 使用的方案是： https://github.com/KyleBing/rime-wubi86-jidian

**描述遇到的问题**
OneNote 无法显示候选框，且输入后字词会出现两遍。

**复现步骤**
在 OneNote 桌面版中进行输入就会出现。

**预期行为**
正确显示候选框，输入文字不会重复出现。

**用户文件**
https://github.com/KyleBing/rime-wubi86-jidian

**截图**

https://github.com/rime/weasel/assets/35132976/69b39073-71c6-4084-9d51-92087f4888ad

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by Techince** [comment]
「System32\weasel.ime」和「Windows\SysWow64\weasel.ime」两个文件删除即可

**Comment by b11p** [comment]
楼上的方法有用，感谢

**Comment by determ1ne** [comment]
下个版本中会修复
