### ISSUE TITLE
安装程序无法正常进行静默安装

### ISSUE THREAD

**Issue by SpecterShell** [rime/weasel#949]
**上报前请检查**
- [X] 我遇到的问题没有其他人在 issue 里提到过
- [X] 我的小狼毫版本于 rime/weasel 下载
- [X] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: 19045.3086
 - 小狼毫版本: 0.15.0.0

**描述遇到的问题**

下载最新版本的安装包后，在PowerShell内使用`.\weasel-0.15.0.0-installer.exe /S`执行静默安装时，安装程序会弹出本不应弹出的“方案選單設定”窗口，导致静默安装在这里卡住，无法正常完成安装并退出。

![image](https://github.com/rime/weasel/assets/56779163/7fdf1c3b-344c-4da9-8114-0300c82dbc9e)

安装程序的NSIS脚本在这一步试图使用`${GetParameters}`宏获取命令行参数以判断目前是否为静默安装，但是NSIS的静默安装参数`/S`会被NSIS系统本身所使用，不会出现在该宏返回的命令行参数中。

https://github.com/rime/weasel/blob/5824f8b8f3217d08a08e4b8348624e3901a5cac1/output/install.nsi#L210-L214

可以通过`IfSilent`函数检测当前是否为静默安装，例如：

https://github.com/rime/weasel/blob/5824f8b8f3217d08a08e4b8348624e3901a5cac1/output/install.nsi#L117-L120

**Comment by determ1ne** [comment]
不是这个问题，上面列的那个是设置 weaselsetup 的参数，也确实起作用了。

第一次安装的时候用户文件夹中还没有方案，所以 weaseldeployer 会弹窗选择

**Comment by SpecterShell** [comment]
嗯……好像确实。

那能否设置 weaseldeployer 在初次安装且为静默安装的情况下使用默认选项而无需用户选择？

**Comment by determ1ne** [comment]
PR Welcome
