### ISSUE TITLE
大词库无法完成部署

### ISSUE THREAD

**Issue by SogaSuga** [rime/weasel#953]
**上报前请检查**
- [☑ ] 我遇到的问题有其他人在 issue 里提到过，但一直没有有效的解决方法
- [☑ ] 我的小狼毫版本于 rime/weasel 下载
- [☑ ] 我在使用小狼毫的最新发布版本

**操作系统信息**
 - OS 详细版本: Windows10 22H2，19045.3086
 - 小狼毫版本: 0.15.0

**描述遇到的问题**
词库总词条数大约超过150万后，无法完成部署，deployer一直在运行但cpu使用为0。
（例如雾凇拼音 https://github.com/iDvel/rime-ice 的词库都加上就会这样）

**Comment by zweie** [comment]
你试一下看看把 'vocabulary: ' 这个加入到你输入法的词库文件的开头里。
用法就是 vocabulary: + 词库文件名，比如雾凇拼音的8105词库，就是 vocabulary: 8105 。
而且你词库的文件要放在用户文件夹的根目录下。

我之前也有碰到过，后来怎样弄来弄去就可以了，记得的主要的改动是这个。可以试一下看看。
用的位置是这样子
```
name: double_pinyin_flypy
vocabulary: 8105

import_tables:
  - 8105
  - 41448
  - base
```

**Comment by SogaSuga** [comment]
> 你试一下看看把 'vocabulary: ' 这个加入到你输入法的词库文件的开头里。 用法就是 vocabulary: + 词库文件名，比如雾凇拼音的8105词库，就是 vocabulary: 8105 。 而且你词库的文件要放在用户文件夹的根目录下。
试过还是不行。我现在是用同文部署出bin，再复制到windows里替换

**Comment by SogaSuga** [comment]
> 

纯用雾凇确实没问题唉。
试了一番发现我自己的词库里有use_preset_vocabulary: true，关掉这个部署就没问题了，但是我确实需要它。。

**Comment by zweie** [comment]
> > 
> 
> 纯用雾凇确实没问题唉。 试了一番发现我自己的词库里有use_preset_vocabulary: true，关掉这个部署就没问题了，但是我确实需要它。。

哦，这个啊，这一条可以用我前面跟你说的 `vocabulary: 8105` 这个来代替。

这个好像是字的码表来着。

**Comment by BigOldTree** [comment]
试试这个
https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64

**Comment by SogaSuga** [comment]
> 试试这个 https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64

这个可以，感谢！

**Comment by ASC8384** [comment]
> 你试一下看看把 'vocabulary: ' 这个加入到你输入法的词库文件的开头里。 用法就是 vocabulary: + 词库文件名，比如雾凇拼音的8105词库，就是 vocabulary: 8105 。 而且你词库的文件要放在用户文件夹的根目录下。
> 
> 我之前也有碰到过，后来怎样弄来弄去就可以了，记得的主要的改动是这个。可以试一下看看。 用的位置是这样子
> 
> ```
> name: double_pinyin_flypy
> vocabulary: 8105
> 
> import_tables:
>   - 8105
>   - 41448
>   - base
> ```

请问，`vocabulary: 8105` 这种用法在哪个文档里有具体说明呀

**Comment by ASC8384** [comment]
> > 你试一下看看把 'vocabulary: ' 这个加入到你输入法的词库文件的开头里。 用法就是 vocabulary: + 词库文件名，比如雾凇拼音的8105词库，就是 vocabulary: 8105 。 而且你词库的文件要放在用户文件夹的根目录下。
> > 我之前也有碰到过，后来怎样弄来弄去就可以了，记得的主要的改动是这个。可以试一下看看。 用的位置是这样子
> > ```
> > name: double_pinyin_flypy
> > vocabulary: 8105
> > 
> > import_tables:
> >   - 8105
> >   - 41448
> >   - base
> > ```
> 
> 请问，`vocabulary: 8105` 这种用法在哪个文档里有具体说明呀

看到这里提到过 https://github.com/rime/librime/issues/509

**Comment by markwu** [comment]
> 试试这个 https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64

我也遇到相同的問題，但是是用在自己轉的維基詞庫上。請問這個打包可以信任呢？還是要等官方的 0.15.1 的打包呢？

**Comment by zigeweiwu** [comment]
> > 试试这个 https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64
> 
> 我也遇到相同的問題，但是是用在自己轉的維基詞庫上。請問這個打包可以信任呢？還是要等官方的 0.15.1 的打包呢？


这包我用了一个多月没有出现问题，但是如果说信任的话，要等官方x64 的包。但是官方现在没有这个计划出x64的包

**Comment by zigeweiwu** [comment]
> > 试试这个 https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64
> 
> 我也遇到相同的問題，但是是用在自己轉的維基詞庫上，約 130 萬條詞目。請問這個打包可以信任呢？還是要等官方的 0.15.1 的打包呢？
> 
> `註：沒有不敬的意思，只是非官方打包我都會小心的多問一下。`

这里有其他的解决方案 但是我的cup不支持  https://github.com/rime/home/discussions/1074

**Comment by fxliang** [comment]
https://github.com/rime/weasel/issues/841里面我做了个小玩具，应该是可以解决的，最后的那个回复的压缩包。

最终的解决等Librime同时放出64位的构建的话，可以同时生成WeaselDeployer_x64就可以解决了。等吧

**Comment by markwu** [comment]
謝謝 @zigeweiwu 和 @fxliang ，我來試試看。

**Comment by markwu** [comment]
@fxliang 來回報一下，114萬條維基百科詞庫，部署沒有任何問題。

**Comment by plutotree** [comment]
我是用雾凇拼音词库的时候也出现了这个问题，一直处于词库部署中无法完成，看日志似乎是触发了内容变更重新加载。

手动尝试雾凇拼音词库一个个加载，发现问题也在最大的那个Tencent词库加载的时候才有问题。

根据前面的回帖指定`use_preset_vocabulary:false`后发现就正常了，不过同时也删除了原来维护的另外的词表，现在主要就是用雾凇拼音的词库以及自己维护的几份词库。

**Comment by suibianzai** [comment]
> [rimedeployerx64.zip](https://github.com/rime/weasel/files/12496136/rimedeployerx64.zip) 这个里面的文件丢到算法服务目录里面，运行rimedeployerx64.exe就可以部署大词库了，不用另外复制粘贴文件了

谢谢分享，请问算法服务目录是哪个文件夹？

**Comment by fxliang** [comment]
> > [rimedeployerx64.zip](https://github.com/rime/weasel/files/12496136/rimedeployerx64.zip) 这个里面的文件丢到算法服务目录里面，运行rimedeployerx64.exe就可以部署大词库了，不用另外复制粘贴文件了
> 
> 谢谢分享，请问算法服务目录是哪个文件夹？

最新nightly 已有64位应用，在64位系统上自动安装64位应用，不用这个了
