### ISSUE TITLE
最新构建在Word“查找与替换”弹窗中输入时，按下首个按键后候选框无法弹出

### ISSUE THREAD

**Issue by s92671** [rime/weasel#954]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Win10 LTSC 21H2 19044.3086
 - 小狼毫版本: [81afe6c](https://github.com/rime/weasel/commit/81afe6c1042bcfa3ea59199846d75d779a2ddce7)
 - Word版本: Office LTSC 2021

**描述遇到的问题**
在Word的“查找与替换”弹窗中输入时，按下首个按键后，候选框无法弹出，按下第二个按键后才弹出。
如图示，弹窗中输入“侧”时，按下C键后候选框无法弹出，再按下E键后才会弹出。
输入时均采用全拼输入。

![123](https://github.com/rime/weasel/assets/40166/665b59f6-d027-4281-bb27-71dff243cf9c)

**Comment by fxliang** [comment]
如果你按的再慢一点感受一下，新的显示框是在c的按键抬起后更新的；
如果再细致观察一下，输入位置那个预插入的定位空格也是在c的抬起后显示出来的。
如果你试一下记事本软件，你会发现这个问题忽然就不存在了；
如果你试一下inline_preedit: true，大概率这个“问题”消失了。

**Comment by mirtlecn** [comment]
复现成功，特地在按第一个键后停顿了一两秒，无法弹出候选框

```yaml
inline_preedit: true
preedit_type: preview
```

![1687570109](https://github.com/rime/weasel/assets/76689045/3854221a-9ac3-4ba8-b78c-576f38ff4365)

**Comment by fxliang** [comment]
确认在最新版的Office的这个位置是有问题，关联composition

**Comment by Techince** [comment]
尝试修复这个问题，可以试试这个版本。
https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64

**Comment by Techince** [comment]
没想到在定位框里还是第一编码无候选框。

**Comment by Techince** [comment]
@mirtlecn @s92671 已查到原因，修复了此问题。可下载此版本试用。
https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64

**Comment by fxliang** [comment]
closed by #1026
