### ISSUE TITLE
请问一下 schema/icon 的使用方法

### ISSUE THREAD

**Issue by ls148478** [rime/weasel#957]
使用的最新版本的程序
根据 https://github.com/rime/weasel/pull/882 所说 还是无法很好的理解

尝试过在 `xx.schema.yaml`、`default.custom.yaml`、`weasel.custom.yaml` 中修改，都没有成功

> xx..schema.yaml
![image](https://github.com/rime/weasel/assets/38435967/9b93f479-0666-4ade-ba2d-8a37745e9acc)
-----
> default.custom.yaml
![image](https://github.com/rime/weasel/assets/38435967/2f001b42-94b1-48c4-8d25-afdddfea69ce)
----
> weasel.custom.yaml
![image](https://github.com/rime/weasel/assets/38435967/f1104469-dc70-498a-abec-e7872130ad89)
----
应该如何使用呢...

**Comment by fxliang** [comment]
看看就懂
https://github.com/fxliang/weasel_config/blob/main/wubi091.custom.yaml

**Comment by ls148478** [comment]
> 看看就懂 https://github.com/fxliang/weasel_config/blob/main/wubi091.custom.yaml
@fxliang 
感谢您的解答 原来需要新建文件使用
我想再咨询您一个问题 这个我使用感觉很模糊 有什么方案改善吗
![image](https://github.com/rime/weasel/assets/38435967/0146cde8-8769-4ca2-9ecf-a4ff710121b7)

**Comment by ls148478** [comment]
> 在原来的方案下同样的节点位置设定也是可以的。 不清晰是因为你的icon对比度不够，这个是素材问题

感谢 我明白了

**Comment by fxliang** [comment]
> > 在原来的方案下同样的节点位置设定也是可以的。 不清晰是因为你的icon对比度不够，这个是素材问题
> 
> 感谢 我明白了

文件可以在用户目录下，也可以是在共享数据目录下，检索顺序优先前者
