### ISSUE TITLE
建议添加类似imtip输入状态提示 或兼容imtip

### ISSUE THREAD

**Issue by Qeynos** [rime/weasel#958]
imtip是github上一个项目，在点击输入框时跳出图标提示输入法的中英状态，支持但小狼毫因为某些机制，输入状态无法被imtip捕获，无论小狼毫处在什么状态都提示中文状态

> 理论上支持所有输入法，系统自带的微软拼音，微软五笔，搜狗输入法，小小输入法，百度输入法，QQ输入法，谷歌输入法，小鹤输入法，手心输入法 …… 包括我测试的日文、韩文、西班牙语输入法都可以支持 ImTip 。

现在显示器越来越大，频繁多窗口输入的时候去状态栏看状态时视线需要挪动的距离越来越大，盲目输入往往发现输入法状态不对，删掉重新输入，小狼毫是否有可能提供这样的功能，或兼容imtip

**Comment by retina007** [comment]
也为这个问题困扰很久（windows系统）。
1.如何在鼠标点击输入框时（鼠标箭头变成输入光标状态），直接马上显示中英状态，然后持续3秒就自动消失就行
2.目前需要按shift才能知道，多余的操作

**Comment by retina007** [comment]
@Qeynos 
话说有imtip这个工具，我主要输入法本来就是微软输入法。谢谢你，imtip很好用
Rime就体验了一个小时，发现这个功能还需要按shift，放弃了

**Comment by fxliang** [comment]
#956 中提及这个事项，然后我确实试了下，目前是没有试通

大致的情况就是，不管在tsf内和服务里，方案的识别都是正确的，但是ui那边的status就是没有成功更新继而显示不正确，一直维持在最后一次使用的方案上

接口在`STDAPI WeaselTSF::OnSetFocus(ITfDocumentMgr *pDocMgrFocus, ITfDocumentMgr *pDocMgrPrevFocus)`上, 这个东西看缘份，说不定就哪天忽然有思路解了

![tip_schema](https://github.com/rime/weasel/assets/4023160/4397c2dc-65f9-40c7-aca4-95441cc36a65)


notepad.exe上的方案是五笔86， notepad3.exe上的方案是五笔拼音
```
---------------------------------------------------------------
schema name: 五笔86 OnSetFocus called, pDocMgrFocus && pDocMgrPrevFocus == NULL
FocusIn notepad.exe, session_id = 83878232, current schema_name = 五笔86
---------------------------------------------------------------
schema name: 五笔·拼音 OnSetFocus called, pDocMgrFocus && pDocMgrPrevFocus == NULL
FocusIn notepad3.exe, session_id = 84917488, current schema_name = 五笔·拼音
---------------------------------------------------------------
schema name: 五笔86 OnSetFocus called, pDocMgrFocus && pDocMgrPrevFocus == NULL
FocusIn notepad.exe, session_id = 83878232, current schema_name = 五笔86
---------------------------------------------------------------
schema name: 五笔·拼音 OnSetFocus called, pDocMgrFocus && pDocMgrPrevFocus == NULL
FocusIn notepad3.exe, session_id = 84917488, current schema_name = 五笔·拼音
---------------------------------------------------------------
schema name: 五笔·拼音 OnSetFocus called, pDocMgrFocus && pDocMgrPrevFocus == NULL
FocusIn notepad3.exe, session_id = 84917488, current schema_name = 五笔·拼音
---------------------------------------------------------------
schema name: 五笔86 OnSetFocus called, pDocMgrFocus && pDocMgrPrevFocus == NULL
FocusIn notepad.exe, session_id = 83878232, current schema_name = 五笔86
---------------------------------------------------------------
schema name: 五笔·拼音 OnSetFocus called, pDocMgrFocus && pDocMgrPrevFocus == NULL
FocusIn notepad3.exe, session_id = 84917488, current schema_name = 五笔·拼音
```

**Comment by fxliang** [comment]
不太聪明但是能实现的方法，但是可能会逼死另外一些强迫症
![imtips0](https://github.com/rime/weasel/assets/4023160/0e3f3b91-e128-4ebf-9cfb-9fe9f3a71137)
![imtips1](https://github.com/rime/weasel/assets/4023160/3e466c86-0b76-40f4-b61e-57d6e9bd8ae0)

**Comment by fxliang** [comment]
![imtips1](https://github.com/rime/weasel/assets/4023160/2aebdea6-c3ee-40d1-80a0-aec162af7e13)
![imtips2](https://github.com/rime/weasel/assets/4023160/8add8e31-a9f4-4b41-951c-2537ac8511fc)

**Comment by Qeynos** [comment]
> ![imtips1](https://user-images.githubusercontent.com/4023160/251374733-2aebdea6-c3ee-40d1-80a0-aec162af7e13.gif) ![imtips2](https://user-images.githubusercontent.com/4023160/251374741-8add8e31-a9f4-4b41-951c-2537ac8511fc.gif)

看起来很直观，有CI可以试用吗

**Comment by fxliang** [comment]
另外吐嘈一下imtip这个软件，真的处理好内存了吗？一个提示软件占用几百M的内存？
![image](https://github.com/rime/weasel/assets/4023160/c17eb2de-2040-4d22-b496-d65895bd47f8)

**Comment by Qeynos** [comment]
> 另外吐嘈一下imtip这个软件，真的处理好内存了吗？一个提示软件占用几百M的内存？ ![image](https://user-images.githubusercontent.com/4023160/251608587-c17eb2de-2040-4d22-b496-d65895bd47f8.png)

我这里4.4版20多M，最新的CI部分窗口正常，但微信里还是无法正确识别输入状态

**Comment by fxliang** [comment]
> > 另外吐嘈一下imtip这个软件，真的处理好内存了吗？一个提示软件占用几百M的内存？ ![image](https://user-images.githubusercontent.com/4023160/251608587-c17eb2de-2040-4d22-b496-d65895bd47f8.png)
> 
> 我这里4.4版20多M，最新的CI部分窗口正常，但微信里还是无法正确识别输入状态

反正官网下载的最新版，没有看是什么版本。我后面重开之后似乎现在是40多。目测是资源没有释放，处理多了就泄漏了。

另外微信和谷歌浏览器我这边是没有问题的
![wechattest](https://github.com/rime/weasel/assets/4023160/1b44f838-127e-4d5a-aed1-68f6b4fc66ba)
![chrometest](https://github.com/rime/weasel/assets/4023160/9af92a92-a245-43d6-a95b-393a01434cda)

**Comment by Qeynos** [comment]
> > > 另外吐嘈一下imtip这个软件，真的处理好内存了吗？一个提示软件占用几百M的内存？
> > 
> > 
> > 我这里4.4版20多M，最新的CI部分窗口正常，但微信里还是无法正确识别输入状态
> 
> 反正官网下载的最新版，没有看是什么版本。我后面重开之后似乎现在是40多。目测是资源没有释放，处理多了就泄漏了。
> 
> 另外微信和谷歌浏览器我这边是没有问题的 

这东西只能将就用，肯定没有输入法自带原生的好用

**Comment by fxliang** [comment]
closed by #956

**Comment by aardio** [comment]
> > > 另外吐嘈一下imtip这个软件，真的处理好内存了吗？一个提示软件占用几百M的内存？ ![image](https://user-images.githubusercontent.com/4023160/251608587-c17eb2de-2040-4d22-b496-d65895bd47f8.png)
> > 
> > 
> > 我这里4.4版20多M，最新的CI部分窗口正常，但微信里还是无法正确识别输入状态
> 
> 反正官网下载的最新版，没有看是什么版本。我后面重开之后似乎现在是40多。目测是资源没有释放，处理多了就泄漏了。
> 
> 另外微信和谷歌浏览器我这边是没有问题的 ![wechattest](https://private-user-images.githubusercontent.com/4023160/251629058-1b44f838-127e-4d5a-aed1-68f6b4fc66ba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTczMDAsIm5iZiI6MTcyMzg1NzAwMCwicGF0aCI6Ii80MDIzMTYwLzI1MTYyOTA1OC0xYjQ0ZjgzOC0xMjdlLTRkNWEtYWVkMS02OGY2YjRmYzY2YmEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMDExMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDExYjk4NmIwOTRkYTU3YmI4ODg2NDllM2ZjMmMyZWZiODljNDE1OWU1MzNjZjNjOTI5MDgyYTMwMGY0YjVmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-55jZF9RxvZEoItCTAZM197oHvF1X-T6rHsp_MJ9IPc) [ ![wechattest](https://private-user-images.githubusercontent.com/4023160/251629058-1b44f838-127e-4d5a-aed1-68f6b4fc66ba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTczMDAsIm5iZiI6MTcyMzg1NzAwMCwicGF0aCI6Ii80MDIzMTYwLzI1MTYyOTA1OC0xYjQ0ZjgzOC0xMjdlLTRkNWEtYWVkMS02OGY2YjRmYzY2YmEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMDExMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDExYjk4NmIwOTRkYTU3YmI4ODg2NDllM2ZjMmMyZWZiODljNDE1OWU1MzNjZjNjOTI5MDgyYTMwMGY0YjVmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-55jZF9RxvZEoItCTAZM197oHvF1X-T6rHsp_MJ9IPc) ](https://private-user-images.githubusercontent.com/4023160/251629058-1b44f838-127e-4d5a-aed1-68f6b4fc66ba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTczMDAsIm5iZiI6MTcyMzg1NzAwMCwicGF0aCI6Ii80MDIzMTYwLzI1MTYyOTA1OC0xYjQ0ZjgzOC0xMjdlLTRkNWEtYWVkMS02OGY2YjRmYzY2YmEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMDExMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDExYjk4NmIwOTRkYTU3YmI4ODg2NDllM2ZjMmMyZWZiODljNDE1OWU1MzNjZjNjOTI5MDgyYTMwMGY0YjVmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-55jZF9RxvZEoItCTAZM197oHvF1X-T6rHsp_MJ9IPc) [ ](https://private-user-images.githubusercontent.com/4023160/251629058-1b44f838-127e-4d5a-aed1-68f6b4fc66ba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTczMDAsIm5iZiI6MTcyMzg1NzAwMCwicGF0aCI6Ii80MDIzMTYwLzI1MTYyOTA1OC0xYjQ0ZjgzOC0xMjdlLTRkNWEtYWVkMS02OGY2YjRmYzY2YmEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMDExMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDExYjk4NmIwOTRkYTU3YmI4ODg2NDllM2ZjMmMyZWZiODljNDE1OWU1MzNjZjNjOTI5MDgyYTMwMGY0YjVmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-55jZF9RxvZEoItCTAZM197oHvF1X-T6rHsp_MJ9IPc) ![chrometest](https://private-user-images.githubusercontent.com/4023160/251629063-9af92a92-a245-43d6-a95b-393a01434cda.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTczMDAsIm5iZiI6MTcyMzg1NzAwMCwicGF0aCI6Ii80MDIzMTYwLzI1MTYyOTA2My05YWY5MmE5Mi1hMjQ1LTQzZDYtYTk1Yi0zOTNhMDE0MzRjZGEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMDExMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWMxMGQ1MTU0MDk1NmFlYTRjOTljZDE4YWY2MjNkNTU4ZDM2NDE1NDY2NjkxMzYwODJjNTI4NjQ0NjJjZjA2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QtqZsrdU81mYGaTr-TXlTZ1Uzhd7PdxC7iUUxf0d5xk) [ ![chrometest](https://private-user-images.githubusercontent.com/4023160/251629063-9af92a92-a245-43d6-a95b-393a01434cda.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTczMDAsIm5iZiI6MTcyMzg1NzAwMCwicGF0aCI6Ii80MDIzMTYwLzI1MTYyOTA2My05YWY5MmE5Mi1hMjQ1LTQzZDYtYTk1Yi0zOTNhMDE0MzRjZGEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMDExMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWMxMGQ1MTU0MDk1NmFlYTRjOTljZDE4YWY2MjNkNTU4ZDM2NDE1NDY2NjkxMzYwODJjNTI4NjQ0NjJjZjA2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QtqZsrdU81mYGaTr-TXlTZ1Uzhd7PdxC7iUUxf0d5xk) ](https://private-user-images.githubusercontent.com/4023160/251629063-9af92a92-a245-43d6-a95b-393a01434cda.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTczMDAsIm5iZiI6MTcyMzg1NzAwMCwicGF0aCI6Ii80MDIzMTYwLzI1MTYyOTA2My05YWY5MmE5Mi1hMjQ1LTQzZDYtYTk1Yi0zOTNhMDE0MzRjZGEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMDExMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWMxMGQ1MTU0MDk1NmFlYTRjOTljZDE4YWY2MjNkNTU4ZDM2NDE1NDY2NjkxMzYwODJjNTI4NjQ0NjJjZjA2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QtqZsrdU81mYGaTr-TXlTZ1Uzhd7PdxC7iUUxf0d5xk) [ ](https://private-user-images.githubusercontent.com/4023160/251629063-9af92a92-a245-43d6-a95b-393a01434cda.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTczMDAsIm5iZiI6MTcyMzg1NzAwMCwicGF0aCI6Ii80MDIzMTYwLzI1MTYyOTA2My05YWY5MmE5Mi1hMjQ1LTQzZDYtYTk1Yi0zOTNhMDE0MzRjZGEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMDExMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWMxMGQ1MTU0MDk1NmFlYTRjOTljZDE4YWY2MjNkNTU4ZDM2NDE1NDY2NjkxMzYwODJjNTI4NjQ0NjJjZjA2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QtqZsrdU81mYGaTr-TXlTZ1Uzhd7PdxC7iUUxf0d5xk)

ImTip 如果只是使用提示功能，正常不需要开任何窗口，资源占用是很少的。

如果使用了外观设计器、字体浏览器，例如字体图标要用到 Web 浏览器控件这不是实时适放内存的，可能会有一个短暂的内存峰值。 不用重启，只要关掉窗口内存就会释放。

刚才我把 ImTip 有功能都打开运行了一遍，占用内存也就 40 MB，CPU 占用为 0 ，ImTip 已经连续运行了一周。如果您遇到超出正常占用的情况，如果能提供重现问题的步骤我排查一下是不是有『内存没处理好』的问题。

**Comment by fxliang** [comment]
太久远了，我从来不用Imtip，现在硬盘上也没有Imtip了。
这个当时只是有人说要，就加了对应的隔离仓相关的消息，应该也不是百百复现；
另外当时只是调试图标有没有对不对，所以没有开任何设置窗口什么的，就是默认的配置，回复那个消息的时候就真实的出现了这个内存占用，这个我是觉得异常的，绘制几个图标不应该会出现这么大的内存占用，感觉像是漏了，就随口提了一句

**Comment by fxliang** [comment]
这个不应该是看看imtip是怎么实现这样才是嘛？

小狼毫这个对应的pr只是在状态变化的时候更新了隔离仓数据，imtip应该是通过类似的tsf接口获取的吧

**Comment by abgox** [comment]
好吧，我以为是专门提供了接口
