### ISSUE TITLE
请问如何在default.custom.yaml禁用默认的Shift+space(全角/半角切换)

### ISSUE THREAD

**Issue by 2anyone** [rime/weasel#96]
我从不使用全角, 但是输入的时候总是不小心会碰到这个组合键, 所以我想屏蔽这个组合键.

我不愿意直接在default.yaml用#注释掉`- {accept: "Shift+space", toggle: full_shape, when: always}`, 而是想在default.custom.yaml中用patch的方式解决.

尝试了:

```
patch:
  "ascii_composer/switch_key":
    Shift+space: noop
```

重新部署后这个组合键仍然可以切换全角/半角, 似乎并没有达到我的预期, 请问该如何设置呢?

**Comment by dupontjoy** [comment]
在cangjie5(输入法).custom.yaml中写入:
`  key_binder/bindings:
    - { accept: "Shift+space", toggle: noop, when: always} #取消全半角切换`

**Comment by 2anyone** [comment]
非常感谢, 我在default.custom.yaml中加入这行似乎也可以进行全局设定.

**Comment by lotem** [comment]
我做了一個對快捷鍵的較大改動，尚未合併到默認配置
https://github.com/rime/rime-prelude/pull/2
徵求用家意見

**Comment by edhub** [comment]
> 在cangjie5(输入法).custom.yaml中写入:
> 
> ```
> Patch:
>   key_binder/bindings:
>     - { accept: "Shift+space", toggle: noop, when: always} #取消全半角切换```
> ```

我在鼠须管中，试用这个配置无效，依然可以切换半、全角。请问还有其他方式可以搞吗？

**Comment by lasting-yang** [comment]
> > 在cangjie5(输入法).custom.yaml中写入:
> > ```
> > Patch:
> >   key_binder/bindings:
> >     - { accept: "Shift+space", toggle: noop, when: always} #取消全半角切换```
> > ```
> 
> 我在鼠须管中，试用这个配置无效，依然可以切换半、全角。请问还有其他方式可以搞吗？

我把所有.yaml文件中的 `- {accept: "Shift+space", toggle: full_shape, when: always}` 删掉了，就没有全角符号了

**Comment by arfaWong** [comment]
在 default.custom.yaml 里面这么写可以生效
```
patch:
  "key_binder/bindings/+":
    - { when: always, accept: "Shift+space", toggle: noop }
```

**Comment by Eyre-S** [comment]
找到了一个可以真正解绑快捷键的办法，不仅可以解绑 Shift+space，而且也能让 Shift+space 时正常输出空格

```
patch:
  "key_binder/bindings/+":
    - { accept: "Shift+space", send: "Shift+space", when: always }
```
