### ISSUE TITLE
这是不是bug，求解。

### ISSUE THREAD

**Issue by Sickid** [rime/weasel#960]
![Snipaste_2023-07-04_07-23-51](https://github.com/rime/weasel/assets/5845381/ec9e2788-fe9e-4d78-a64d-bcace06da083)
在安装选项里换了几次用户资料夹，结果就这样了。ctrl+shift会出来一堆小狼毫（没截到图），系统的输入法设置中也能看到。重启系统后依然存在，目前未卸载输入法尝试（还要重启系统太麻烦）。

**Comment by Sickid** [comment]
输入法都卸载了，这些选项依旧存在。

**Comment by yanhuacuo** [comment]
估计安装过古早的版本，最新版已经会回收这些注册项了。

https://github.com/rime/weasel/issues/373

**Comment by Techince** [comment]
![image](https://github.com/rime/weasel/assets/12376669/ce05df92-ed14-4d42-95f5-54c668f30bc3)
你需要的是这样的一个逻辑。更换用户目录时但不卸载，「安装」按钮变成「更换」。目前小狼毫更换用户目录时，不先删除的话，点安装，系统托盘里就会有多个小狼毫的键盘，因为它会不断向注册表里添加信息。

**Comment by Sickid** [comment]
> ![image](https://user-images.githubusercontent.com/12376669/252181775-ce05df92-ed14-4d42-95f5-54c668f30bc3.png) 你需要的是这样的一个逻辑。更换用户目录时但不卸载，「安装」按钮变成「更换」。目前小狼毫更换用户目录时，不先删除的话，点安装，中文键盘里就会有多个小狼毫的键盘，因为它会不断向注册表里添加信息。

我在网上找了半天，最后是删除注册表解决的。你这个界面是哪里来的，请指教。

**Comment by Techince** [comment]
> > ![image](https://user-images.githubusercontent.com/12376669/252181775-ce05df92-ed14-4d42-95f5-54c668f30bc3.png) 你需要的是这样的一个逻辑。更换用户目录时但不卸载，「安装」按钮变成「更换」。目前小狼毫更换用户目录时，不先删除的话，点安装，中文键盘里就会有多个小狼毫的键盘，因为它会不断向注册表里添加信息。
> 
> 我在网上找了半天，最后是删除注册表解决的。你这个界面是哪里来的，请指教。

https://github.com/Techince/weasel/releases
此处可以下载。

**Comment by fxliang** [comment]
看看#985 是不是你期待的方案
