### ISSUE TITLE
请求添加隐藏语言栏里的中英指示图标的功能

### ISSUE THREAD

**Issue by PuppetVaysa** [rime/weasel#961]
就是下图红框中的图标
![1](https://github.com/rime/weasel/assets/8633108/6bcba446-afec-455c-ac29-c1cdd8e474e9)

这个图标会导致在切换语言时托盘的长度改变
![1](https://github.com/rime/weasel/assets/8633108/78a0511f-9c43-4012-8302-9b32aceb9e4c)

**Comment by yanhuacuo** [comment]
并没有「导致在切换语言时托盘的长度改变」，因为输入法你要跟微软内置的「微软拼音」或「微软五笔」作对比，而不是跟这个「ENG」的无盘键状态作对比。

如果实在「不能忍受」，可以在「windows系统设置」~「语言选项」中，把小狼毫之外的键盘都删了，包括额外添加的「ENG」，使用 shift 切换中英文状态的基本设定，不过，这可能不是你想要的。

**Comment by PuppetVaysa** [comment]
> 你好感谢回复，具体什么原因我也不是很清楚，只是很不喜欢这种动来动去的感觉(我有些强迫症)

我因为某些原因(比如启动某些游戏时如果开了中文输入法容易导致崩溃)不得不使用这个ENG语言，而且也不习惯单Shift切换中英，容易误按，目前已经在配置文件里关闭了这个快捷键

**Comment by liuliping0315** [comment]
微软长时间的问题了。经典案例：点击任务栏托盘图标，突然输入法指示器长度变化，然后点到旁边的图标了。
一个比较妥协的办法是，使用全局输入法，即“设置--时间和语言--输入--高级键盘设置”中，**不要勾选**“允许我为每个应用窗口使用不通的输入法”。

**Comment by byzod** [comment]
可是对于想要保留分窗口输入模式的来说，就很难受了

![An1](https://github.com/rime/weasel/assets/848607/50e35c82-b5f1-4869-aed3-3416bb9c7368)

从这个例子可以看到即使窝以非常快的速度双击，还是被搞到把图标换了个位置，则个微卵可以说是非常脑瘫了

有在考虑给美式键盘安装一个套壳输入法，其实啥作用没有，就是会多一个图标占位，不知道有没有这种实现？

**Comment by liuliping0315** [comment]
> 可是对于想要保留分窗口输入模式的来说，就很难受了
> 
> ![An1](https://private-user-images.githubusercontent.com/848607/314143763-50e35c82-b5f1-4869-aed3-3416bb9c7368.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTcyOTMsIm5iZiI6MTcxMDg5Njk5MywicGF0aCI6Ii84NDg2MDcvMzE0MTQzNzYzLTUwZTM1YzgyLWI1ZjEtNDg2OS1hZWQzLTM0MTZiYjljNzM2OC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwMTA5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2RiZThlYmVhMTI2NGFjNDc1OGM3YWY4YTliZTkxZDgzZmEzNzg1MzY1YTc3ZDhhYzUwN2I1M2JkY2EwZTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gwaZQB4TB1YJFoeg79KFAqZ04KR4ATLV32iUwtejQRI) [ ![An1](https://private-user-images.githubusercontent.com/848607/314143763-50e35c82-b5f1-4869-aed3-3416bb9c7368.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTcyOTMsIm5iZiI6MTcxMDg5Njk5MywicGF0aCI6Ii84NDg2MDcvMzE0MTQzNzYzLTUwZTM1YzgyLWI1ZjEtNDg2OS1hZWQzLTM0MTZiYjljNzM2OC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwMTA5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2RiZThlYmVhMTI2NGFjNDc1OGM3YWY4YTliZTkxZDgzZmEzNzg1MzY1YTc3ZDhhYzUwN2I1M2JkY2EwZTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gwaZQB4TB1YJFoeg79KFAqZ04KR4ATLV32iUwtejQRI) ](https://private-user-images.githubusercontent.com/848607/314143763-50e35c82-b5f1-4869-aed3-3416bb9c7368.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTcyOTMsIm5iZiI6MTcxMDg5Njk5MywicGF0aCI6Ii84NDg2MDcvMzE0MTQzNzYzLTUwZTM1YzgyLWI1ZjEtNDg2OS1hZWQzLTM0MTZiYjljNzM2OC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwMTA5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2RiZThlYmVhMTI2NGFjNDc1OGM3YWY4YTliZTkxZDgzZmEzNzg1MzY1YTc3ZDhhYzUwN2I1M2JkY2EwZTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gwaZQB4TB1YJFoeg79KFAqZ04KR4ATLV32iUwtejQRI) [ ](https://private-user-images.githubusercontent.com/848607/314143763-50e35c82-b5f1-4869-aed3-3416bb9c7368.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTcyOTMsIm5iZiI6MTcxMDg5Njk5MywicGF0aCI6Ii84NDg2MDcvMzE0MTQzNzYzLTUwZTM1YzgyLWI1ZjEtNDg2OS1hZWQzLTM0MTZiYjljNzM2OC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwMTA5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2RiZThlYmVhMTI2NGFjNDc1OGM3YWY4YTliZTkxZDgzZmEzNzg1MzY1YTc3ZDhhYzUwN2I1M2JkY2EwZTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gwaZQB4TB1YJFoeg79KFAqZ04KR4ATLV32iUwtejQRI)
> 
> 从这个例子可以看到即使窝以非常快的速度双击，还是被搞到把图标换了个位置，则个微卵可以说是非常脑瘫了
> 
> 有在考虑给美式键盘安装一个套壳输入法，其实啥作用没有，就是会多一个图标占位，不知道有没有这种实现？

哈哈哈哈哈哈哈哈，笑死，win10~11就是草台班子，输入法明明可以在所有托盘图标左侧，任务栏那么宽可以供你微软自由发挥，甚至像搜狗/早期微软拼音也可以自由发挥，把五六个图标都放任务栏。

**Comment by byzod** [comment]
禁止为每个窗口使用不同输入法选项可以完全关闭这个图标，能解决问题

如果希望每个窗口用不同的输入法，窝找到了一个相对来说好一点的hack

那就是使用旧式（大概）的语言栏

会始终处于托盘区左边，就不影响图标位置了

![An1](https://github.com/rime/weasel/assets/848607/850a202a-dc7c-46ea-8593-764a2e6dc2cf)

方法是把使用桌面语言栏打开，然后选悬浮或者固定到任务栏

![Snipaste_2024-03-26_19-50-39](https://github.com/rime/weasel/assets/848607/88114b70-8966-4d11-a1b8-42a3c098e94b)

设置界面都是旧式窗口的，之后的win版本可能会取消。。。能用且用吧🤡

**Comment by liuliping0315** [comment]
> 禁止为每个窗口使用不同输入法选项可以完全关闭这个图标，能解决问题
> 
> 如果希望每个窗口用不同的输入法，窝找到了一个相对来说好一点的hack
> 
> 那就是使用旧式（大概）的语言栏
> 
> 会始终处于托盘区左边，就不影响图标位置了
> 
> 缺点是比较丑，而且rime右键菜单会失效
>       
> 
> 方法是把使用桌面语言栏打开，然后选悬浮或者固定到任务栏
> 
> 
> 设置界面都是旧式窗口的，之后的win版本可能会取消。。。能用且用吧🤡

我以前也按照你这个方式设置，但是现在
我这里停靠于任务栏已经是灰色了，灰色很久了

**Comment by byzod** [comment]
> > 禁止为每个窗口使用不同输入法选项可以完全关闭这个图标，能解决问题
> > 如果希望每个窗口用不同的输入法，窝找到了一个相对来说好一点的hack
> > 那就是使用旧式（大概）的语言栏
> > 会始终处于托盘区左边，就不影响图标位置了
> > 缺点是比较丑，而且rime右键菜单会失效
> > 方法是把使用桌面语言栏打开，然后选悬浮或者固定到任务栏
> > 设置界面都是旧式窗口的，之后的win版本可能会取消。。。能用且用吧🤡
> 
> 我以前也按照你这个方式设置，但是现在 我这里停靠于任务栏已经是灰色了，灰色很久了

你是win11吗还是win10？看来果然被砍了……可能是窝蛮久没更新（还是10 21H2）所以还能用orz

**Comment by mruru** [comment]
主要我感觉rime的这个中英文指示图标太丑了，还不如微软默认的【中/英】

**Comment by fxliang** [comment]
新版里面可以每个方案定义中英文图标，可以自行设定，使用ico文件

方案patch里面
```yaml
patch:
  schema/icon: your_schema_icon # 用户目录的相对路径
  schema/ascii_icon:  your_ascii_icon # 用户目录的相对路径
```

**Comment by wzv5** [comment]
@fxliang 为什么不考虑加这个功能，可以解释一下么？
我一开始用 weasel 时也被这个问题困扰，当时还没有研究 weasel 的代码，只是随手反汇编暴力修改掉了。
现在想增加这个选项，搜到之前被你否决了。

顺便把我当时搞的修改补丁分享出来，dUP2 制作的，包含源码。
补丁解压到 weasel 安装目录中，如 `C:\Program Files\Rime\weasel-0.16.3`，然后运行补丁，会自动修改 `weasel.dll` 和 `weaselx64.dll`。
然后手动把修改后的 `weasel.dll` 复制到 `C:\Windows\SysWOW64` 并替换同名文件。
把 `weaselx64.dll` 先复制到桌面等临时位置，改名为 `weasel.dll`，再复制到 `C:\Windows\System32` 并替换同名文件。
如果无法替换，可以先把系统默认输入法改为微软拼音，重启后再替换，替换完再把默认输入法改回来。

[小狼毫去输入法状态图标补丁.zip](https://github.com/user-attachments/files/18906628/default.zip)

![Image](https://github.com/user-attachments/assets/683305c9-a7e7-4039-9eb5-2df8492f7012)

**Comment by fxliang** [comment]
> [@fxliang](https://github.com/fxliang) 为什么不考虑加这个功能，可以解释一下么？ 我一开始用 weasel 时也被这个问题困扰，当时还没有研究 weasel 的代码，只是随手反汇编暴力修改掉了。 现在想增加这个选项，搜到之前被你否决了。
> 
> 顺便把我当时搞的修改补丁分享出来，dUP2 制作的，包含源码。 补丁解压到 weasel 安装目录中，如 `C:\Program Files\Rime\weasel-0.16.3`，然后运行补丁，会自动修改 `weasel.dll` 和 `weaselx64.dll`。 然后手动把修改后的 `weasel.dll` 复制到 `C:\Windows\SysWOW64` 并替换同名文件。 把 `weaselx64.dll` 先复制到桌面等临时位置，改名为 `weasel.dll`，再复制到 `C:\Windows\System32` 并替换同名文件。 如果无法替换，可以先把系统默认输入法改为微软拼音，重启后再替换，替换完再把默认输入法改回来。
> 
> [小狼毫去输入法状态图标补丁.zip](https://github.com/user-attachments/files/18906628/default.zip)
> 
> ![Image](https://github.com/user-attachments/assets/683305c9-a7e7-4039-9eb5-2df8492f7012)

因为大多数用户并不存在这个困扰吧，这个图标在正常使用的时候99以上的时间里目光的焦点都不在这个右下角的位置。

如果将这个隐藏了那相关的菜单就无从使用，这个更多时候反而会产生新的困扰。

如果一定要实现这个，可以考虑在style里加一个bool类型的key，然后创建session的时候将这个style传递过去，然后在处理更新language bar的操作中判断这个值是什么对应判断是不是要创建这个icon，更新这个icon，修改的地方还是相当多的。

**Comment by fxliang** [comment]
> > 因为大多数用户并不存在这个困扰吧，这个图标在正常使用的时候99以上的时间里目光的焦点都不在这个右下角的位置。
> 
> 倒不是因为图标碍眼，主要是默认英文输入、分窗口中文输入时，这个图标会导致托盘位置乱跳，点击托盘图标时容易点错。
> 
> > 如果一定要实现这个，可以考虑在style里加一个bool类型的key，然后创建session的时候将这个style传递过去，然后在处理更新language bar的操作中判断这个值是什么对应判断是不是要创建这个icon，更新这个icon，修改的地方还是相当多的。
> 
> 小众需求的话，是不是可以做成注册表选项，就不做进算法服务里了，实现起来也更加容易。
> 
> 隐藏图标只是让这个图标不在托盘区右侧显示，实现方式是改这里：
> 
> [weasel/WeaselTSF/LanguageBar.cpp](https://github.com/rime/weasel/blob/ea49aa13e936cf2309854ee353f18c2442153643/WeaselTSF/LanguageBar.cpp#L110)
> 
> Line 110 in [ea49aa1](/rime/weasel/commit/ea49aa13e936cf2309854ee353f18c2442153643)
> 
>  pInfo->guidItem = _guid; 
> guid 传 null 就隐藏了。这只影响托盘区右侧显示的图标，不影响独立语言栏里的图标。

原来不是语言栏那个是右边的那个？那你可以pr一个，然后在WeaselSetup里加一条命令在user区写一条数据

**Comment by nyuga** [comment]
这个问题就是我至今不用搜狗以外的输入法的最主要原因，今天搜了一下还真有人提，而且还被拒绝了。看来短期内是换不了了。

**Comment by CoderChang65535** [comment]
> 新版里面可以每个方案定义中英文图标，可以自行设定，使用ico文件
> 
> 方案patch里面
> 
> patch:
>   schema/icon: your_schema_icon # 用户目录的相对路径
>   schema/ascii_icon:  your_ascii_icon # 用户目录的相对路径

请教下这个会影响我在输入光标处的提示图标么？

**Comment by ws2bhhh** [comment]
> 这个问题就是我至今不用搜狗以外的输入法的最主要原因，今天搜了一下还真有人提，而且还被拒绝了。看来短期内是换不了了。

Windows 11，已解决。这个问题疑似微软的锅。
我的解决办法：
1. **安装**英语，去掉所有勾选框只保留基础输入法
2. **删除**英语，此时ENG标志应该消失，英语键盘也应该消失
3. **删除**rime外其他所有键盘

问题解决：
<img width="172" height="36" alt="Image" src="https://github.com/user-attachments/assets/b2d960e5-3524-4f6c-a53e-1cfb2afcc643" />

**Comment by hlc1209** [comment]
遇到同样的问题。并且在windows remote desktop的用例下特别明显的产生困扰。

上面有人说删除其他所有输入法，包括英文输入法，只保留rime。不太可行，因为在很多场景下，如游戏，shift按键会切换到中文。

目前win11下的workaround是打开“使用桌面语言栏”

<img width="1164" height="929" alt="Image" src="https://github.com/user-attachments/assets/85221170-dd22-41c8-be75-f90350e5b3e8" />

然后点击“语言栏选项”

选择“隐藏”

<img width="607" height="661" alt="Image" src="https://github.com/user-attachments/assets/8fe99c26-ed34-4cbb-b3a6-676479677043" />

**Comment by icaca** [comment]
可以是可以了，就是什么图标都没了~ 凑合这用吧 

<img width="336" height="159" alt="Image" src="https://github.com/user-attachments/assets/8726242c-c7c4-4fae-88c9-7d61459d0abb" />


<br />

<img width="112" height="40" alt="Image" src="https://github.com/user-attachments/assets/5028f574-46e5-4054-a505-34a4771d1113" />
