### ISSUE TITLE
在Wegame中输入卡顿

### ISSUE THREAD

**Issue by MOldtime** [rime/weasel#962]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本:  WInodws 11 Canary通道 23H2 25905.1000
 - 小狼毫版本: 0.15.0 [b00ee09](https://github.com/rime/weasel/pull/969/commits/b00ee0968297508e2449bd6eb8a07af955db8636)

**描述遇到的问题**
在Wegame中输入（搜索框）非常卡顿，不跟手

**复现步骤**
重现问题的步骤，如：
1. 打开 'Wegame' 软件
2. 输入 '找到搜索框 任意输入'

**截图**
视频演示：

https://github.com/rime/weasel/assets/38435967/7959f27f-7497-4b03-acd9-053185130b37

**Comment by Techince** [comment]
有时间再测试下[64位](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.exe)看看卡不卡。
去年我测试了几个版本，包括0.14.3版本，非常卡顿。今天又测试了，卡的不太严重。「Ctrl+Shift+G」关闭候选框就感觉不到卡顿了。

**Comment by MOldtime** [comment]
这个版本404了，不过发现了个 [for.Win8.1](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.for.Win8.1.exe)版本的，不知道适不适合

**Comment by Techince** [comment]
> 这个版本404了，不过发现了个 [for.Win8.1](https://github.com/Techince/weasel/releases/download/weasel-0.15.1.0_x64/weasel-0.15.1.007-installer_x64.for.Win8.1.exe)版本的，不知道适不适合

不好意思，上传错版本了。
你再重新下载，还是那个链接。

**Comment by MOldtime** [comment]
测试了一下，结果和您的一致，关闭悬浮后不卡，开启还是卡顿.
