### ISSUE TITLE
無法設置二三四五選項

### ISSUE THREAD

**Issue by mgrtfok** [rime/weasel#963]
使用weasel 0.15.0.0
沒有見誰有這樣的問題

本人使用的是大易輸入法，和注音一樣有四十鍵。
我將候選序號設置為了0‘[]\（12345)
我的問題如下：
如何用’[]\作為選擇鍵，可選2345候選項。

參考過：
patch:
  "key_binder/bindings/@next 1": {accept: apostrophe, send: ‘, when: has_menu}  #撇號次选
  "key_binder/bindings/@next 2": {accept: bracketleft, send: [, when: has_menu}  #[三选
  "key_binder/bindings/@next 3": {accept: bracketright, send: ], when: has_menu}  #]四选

但沒有任何作用。
![image](https://github.com/rime/weasel/assets/47293549/a34ac832-14d0-46cc-a12c-13fb44ddd691)

![image](https://github.com/rime/weasel/assets/47293549/579f8e7e-d17c-40ef-beda-0fd7debaf89d)

改成：
patch:
  "key_binder/bindings/@next 1": {accept: apostrophe, send: 2, when: has_menu}  #撇號次选
  "key_binder/bindings/@next 2": {accept: bracketleft, send: 3, when: has_menu}  #[三选
  "key_binder/bindings/@next 3": {accept: bracketright, send: 4, when: has_menu}  #]四选

效果如下：
![image](https://github.com/rime/weasel/assets/47293549/759c17d7-20c7-4053-9cda-28dfe80e831d)
要選擇「車」字：
![image](https://github.com/rime/weasel/assets/47293549/085f7146-646f-4131-957b-4377d20ebb53)

還是失敗。

請問有什麼辦法能夠實現用'[]\作為二三四五選項。

十分感謝。

**Comment by yanhuacuo** [comment]
小众方案都有个内部社群吧，应该跟群内的朋友讨论一下 schema 的功能实现。
你这个问题，大概率是因为其它功能项，用正则表达式绑走了你想要的键。
如果没有绑定，就不会有上述问题。

**Comment by mgrtfok** [comment]
謝謝  
那好的 
我撤走問題再思考一下原因

**Comment by mgrtfok** [comment]
謝謝
那好的
我撤走問題再思考一下原因

**Comment by fxliang** [comment]
```yaml
key_binder/bindings:
    - { accept: semicolon, send: 2, when: has_menu}  #打字时，冒号选中第2个候选字发送
    - { accept: apostrophe, send: 3, when: has_menu} #打字时，引号选中第3个候选字发送
    - { accept: slash, send: 4, when: has_menu} #打字时，引号选中第3个候选字发送
    - { accept: Shift+parenleft, send: 5, when: has_menu} #打字时，左括号选中第5个候选字发送
    - { accept: Shift+parenright, send: 6, when: has_menu} #打字时，右括号选中第6个候选字发送
```

**Comment by mgrtfok** [comment]
感謝回覆.

經過幾天的摸索我終於找到了正確的方法.
改變候選序號,在dayi.schema.yaml中寫入:
menu:
  alternative_select_keys: 0'[]\-

然後在key_bindings.yaml中將:
#paging_with_brackets:
#__append:
#- { when: paging, accept: bracketleft, send: Page_Up }
#- { when: has_menu, accept: bracketright, send: Page_Down }
全部註釋掉.
重新佈署生效.

最後,我總算可以愉快地打字了.
