### ISSUE TITLE
label_font_face 参数失效

### ISSUE THREAD

**Issue by Huandeep** [rime/weasel#964]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 fxliang/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ Windows 11 22H2 23475.1000 ]
 - 小狼毫版本: [ [2e3afb1](https://github.com/fxliang/weasel/actions/runs/5500784314) ]

**描述遇到的问题**
`label_font_face`参数失效，貌似整合进`font_face`里面了

**截图**
![image](https://github.com/rime/weasel/assets/30691481/1fe1d671-2e3f-4ba9-bff2-25f221c64a52)

**Comment by fxliang** [comment]
https://github.com/fxliang/weasel/actions/runs/5505800956
fixed.
