### ISSUE TITLE
用「独立文件夹」管理方案

### ISSUE THREAD

**Issue by isPoto** [rime/weasel#967]
现在的一锅炖，所有方案都放到同一文件夹太不合理。

有些方案用到公有文件夹，像 script/opencc 等。如果已有方案，就只能把这些文件夹的文件单独移到 RIme 已有文件夹中。

同样，有些方案是尝试性的。事后清理也不方便。要区分方案之间的文件，谨慎删除。

请做成独立文件夹放置方案。这样每个方案的指定文件寻找、方案的删除就可以很方便。

**Comment by ChihSee-Hsie** [comment]
大概是说，在用户文件夹中有公用的 `weasal.costom.yaml`、`default.custom.yaml` 等等，也有各个输入方案自有的配置文件如 `english.xxxx.yaml` （以下记作 `(schema.xxxx.yaml)`）等等。当加载的方案数量不多时，这些文件放在一个文件夹里不至于造成混淆，但如果加载的方案数量较多，或者一个方案加挂了大量词典文件时，都放在用户文件夹就会使得文件夹臃肿不堪，操作时容易出错。今请求将方案自用的 `(schema).xxxx.yaml` 集中起来放到特定的 `(schema)` 文件夹中，方便归类查找。

以上构想可能有要求如下，即设定程序添加输入方案时，需要在用户文件夹中自动创建方案专用的子文件夹，并将从 GitHub 上获取的文件下载其中，而不是像现有方式一样直接归入用户文件夹。

**Comment by fxliang** [comment]
大量词典？参考rime-ice的处理，就有独立的文件夹放那些词库
https://github.com/iDvel/rime-ice/blob/main/rime_ice.dict.yaml

ps，这个更多是后端的策略问题，前端不处理的。
