### ISSUE TITLE
weasel.ico 256x256 图标应该用PNG而不是BMP格式

### ISSUE THREAD

**Issue by CharlesMengCA** [rime/weasel#970]
你好，

weasel.ico 里的 256x256 图标应该用PNG而不是BMP格式。这样能小很多， 也是标准格式。

**Comment by fxliang** [comment]
取自https://github.com/rime/artworks/blob/master/weasel-icons/weasel-black.png，
大小选了16，32，48， 64，128，256，网页工具生成
有更优版本可以修订PR的亲
