### ISSUE TITLE
知乎網頁版回覆評論模塊不能呼出鍵盤

### ISSUE THREAD

**Issue by LucioOng** [rime/weasel#971]
**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [ ] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ 运行 winver.exe 获取，如 Windows 11 22H2 22621.1555]
 - 小狼毫版本: [ 如 0.15.0.0 ， CI 构建版请附短 commit hash ，如 372c9c ]

**描述遇到的问题**
简短地描述你所遇到的问题

**复现步骤**
重现问题的步骤，如：
1. 打开 '...' 软件
2. 输入 '...'
3. 进行 '...' 操作
4. 遇到了 '...' 问题

**预期行为**
简短地描述你预期小狼毫怎么反馈

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by Techince** [comment]
只要登陆知乎账号是可以呼出键盘的，不登陆账号，任何一个输入法都呼不出键盘。

**Comment by fxliang** [comment]
![zhihu](https://github.com/rime/weasel/assets/4023160/72328529-1615-4bb3-8414-f19c440d3b0c)
未复现问题，未登陆，链接是https://zhuanlan.zhihu.com/p/609505137

**Comment by Techince** [comment]
> ![zhihu](https://user-images.githubusercontent.com/4023160/255103597-72328529-1615-4bb3-8414-f19c440d3b0c.gif) 未复现问题，未登陆，链接是https://zhuanlan.zhihu.com/p/609505137

估计和浏览器也有关系。114版本的Edge浏览器，退出账号号，这个框就不再有焦点了，纯英文也输不上去。

**Comment by fxliang** [comment]
知乎网页就拦截了未登陆的输入，我之前能输入是因为有油猴脚本，所以破案了。
