### ISSUE TITLE
候选字只有1个的时候，候选框长度异常

### ISSUE THREAD

**Issue by liangzhi52** [rime/weasel#972]
**上报前请检查**
1.我遇到的问题没有其他人在 issue 里提到过
2.我用的版本：[https://github.com/rime/weasel/actions/runs/5330965780]

**操作系统信息**
 - OS 详细版本: Windows 10 版本 21H2 19044.3208
 - 小狼毫版本: 0.15.1 ，下载地址 https://github.com/rime/weasel/actions/runs/5330965780

**描述遇到的问题**
内嵌输入时，当候选字只有一个的时候，显示异常：候选框长度远大于显示一个字所需的长度

**复现步骤**
重现问题的步骤，如：
1. 打开 记事本
2. 输入 dei

**预期行为**
只有一个候选字的时候，候选框的长度不应太长（空白的区域太大），影响美观

**用户文件**
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.6
  generator: "Weasel::UIStyleSettings"
  modified_time: "Sun Apr 23 19:33:36 2023"
  rime_version: 1.8.5
patch:
  "preset_color_schemes/Micosoft":
    author: XNOM
    back_color: 0xffffff
    border_color: 0xA05800
    candidate_text_color: 0x000000
    hilited_back_color: 0xffffff
    hilited_candidate_back_color: 0xA05800
    hilited_candidate_text_color: 0xffffff
    hilited_text_color: 0x000000
    name: Micosoft
    text_color: 0x000000
  "style/color_scheme": Micosoft
  "style/font_point": 13
  "style/horizontal": true
  "style/inline_preedit": true
  "style/layout/border": 1
  "style/layout/border_width": 1
  "style/layout/candidate_spacing": 20
  "style/layout/hilite_padding": 12
  "style/layout/hilite_spacing": 3
  "style/layout/margin_x": 12
  "style/layout/margin_y": 12
  "style/layout/round_corner": 0
  "style/layout/spacing": 10
  "style/layout/corner_radius": 0

**截图**
![截屏](https://github.com/rime/weasel/assets/97319907/7c50cd0a-af37-4338-bfdd-2a67a3a4b981)

**其他补充说明**
Action最新版也有这个问题 https://github.com/rime/weasel/actions/runs/5613402328

**Comment by fxliang** [comment]
看下build目录下weasel.yaml中的style/layout/min_width看看是多少？
