### ISSUE TITLE
word输入遇到换行时候选框位置反复横跳

### ISSUE THREAD

**Issue by yiguanxianyu** [rime/weasel#974]
**上报前请检查**
- [✅] 我遇到的问题没有其他人在 issue 里提到过
- [✅ ] 我的小狼毫版本于 rime/weasel 下载
- [✅] 我在使用小狼毫的最新版

**操作系统信息**
 - OS 详细版本:  Windows 11 22H2 22621.1992
 - 小狼毫版本:  0.15.0.0

**描述遇到的问题**
在word里输入时，如果遇到换行，候选框位置可能会出现闪动，图中除了第一下是正常的以外，每次按下都会快速在右侧闪一下。如果第一个拼音够长直接换行（比如打「创」字），也不会出现这个问题。

在其他软件（Typora和记事本）里没有发现这个现象。输入法设置是雾凇拼音+小鹤双拼

**截图**
![weasel](https://github.com/rime/weasel/assets/11457822/f399607c-cda8-46b1-bca5-b0a077f5dcbf)

**Comment by QianmuZ** [comment]
> 调整下更新候选框的语句位置可解决此问题。 将 _UpdateUI(*context, _status); _UpdateCompositionWindow(_pEditSessionContext); 语句移到 if (_IsComposing() && config.inline_preedit) 条件分支之后执行就可以了。

提交个PR？

**Comment by Techince** [comment]
@yiguanxianyu @QianmuZ 试试这个吧。
https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64

**Comment by yiguanxianyu** [comment]
> @yiguanxianyu @QianmuZ 试试这个吧。 https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64

确实修复了，谢谢！

**Comment by Techince** [comment]
> > 调整下更新候选框的语句位置可解决此问题。 将 _UpdateUI(*context, _status); _UpdateCompositionWindow(_pEditSessionContext); 语句移到 if (_IsComposing() && config.inline_preedit) 条件分支之后执行就可以了。
> 
> 提交个PR？

我编译的是64位版本，提不了pr。冲突严重。

**Comment by zllx666** [comment]
你好  我使用最新版本时候选框仍然存在着个问题，会跳到其他地方，在sublime和记事本测试没这个问题，不知是否可以修复，谢谢。
操作系统信息
    OS 详细版本: Windows 10 21H2 19044.3086
    小狼毫版本: 0.16.1
截图如下：
![Animation](https://github.com/rime/weasel/assets/60544614/9da92983-ac69-459a-b6d4-9cc2ff2b7119)
