### ISSUE TITLE
 0.15.0.0版本算法服务经常崩溃，导致无法输入中文

### ISSUE THREAD

**Issue by primejava** [rime/weasel#982]
**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [ ] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ 运行 winver.exe 获取，如 Windows 11 22H2 22621.1555]
 - 小狼毫版本: [ 如 0.15.0.0 ， CI 构建版请附短 commit hash ，如 372c9c ]

**描述遇到的问题**
简短地描述你所遇到的问题

**复现步骤**
重现问题的步骤，如：
1. 打开 '...' 软件
2. 输入 '...'
3. 进行 '...' 操作
4. 遇到了 '...' 问题

**预期行为**
简短地描述你预期小狼毫怎么反馈

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
如果问题需要，可附上 GIF 图片

**其他补充说明**
如果有其他补充说明，可以写在这里

**Comment by Techince** [comment]
看看「%temp%\rime*」开头的日志文件有没有错误信息。

**Comment by a823002162** [comment]
我也有遇到这个问题,经常输入中文没反应,需要手动的启动WeaselServer才可以
日志中只有info和warning级别的日志,没有error级别的日志
![image](https://github.com/rime/weasel/assets/39456045/280b8bcb-210f-4b43-bff5-f81176550268)

系统信息:
![image](https://github.com/rime/weasel/assets/39456045/2b415d05-46aa-4957-926e-fa87801e501b)

软件版本:
![image](https://github.com/rime/weasel/assets/39456045/85dc0f84-39f3-43ae-a2b9-b88e5a259ad9)

**Comment by Techince** [comment]
算法服务崩溃通常是所用方案引用的「lua」脚本引起的。

**Comment by a823002162** [comment]
> 

好嘞,我去爬一爬雾凇的issue,看看有没有解决方案

**Comment by abcdefg233** [comment]
你是否启用了`语法插件`：`grammar`和`contextual_suggestion`？
部分 Lua脚本 与之合用会产生崩溃，并且不会拉起 Error，这也曾困扰过我。
```
I20230824 14:53:16.607959 23328 engine.cc:72] starting engine.
I20230824 14:53:16.608973 23328 engine.cc:124] updated option: ascii_punct
I20230824 14:53:16.608973 23328 engine.cc:124] updated option: _auto_commit
I20230824 14:53:16.608973 23328 dictionary.cc:318] loading dictionary 'rime_ice'.
I20230824 14:53:16.608973 23328 octagram.cc:29] use grammar: zh-hans-t-essay-bgw
I20230824 14:53:16.608973 23328 table_db.cc:78] stabledb 'custom_phrase_double' does not exist.
I20230824 14:53:16.608973 23328 dictionary.cc:318] loading dictionary 'melt_eng'.
I20230824 14:53:16.608973 23328 engine.cc:124] updated option: ascii_mode
I20230824 14:53:16.609988 23328 engine.cc:137] updated property: client_app
I20230824 14:53:16.609988 23328 engine.cc:137] updated property: client_type
I20230824 14:53:16.609988 23328 engine.cc:124] updated option: inline_preedit
I20230824 14:53:16.609988 23328 engine.cc:124] updated option: soft_cursor
I20230824 14:53:16.609988 23328 engine.cc:124] updated option: inline_preedit
I20230824 14:53:16.609988 23328 engine.cc:124] updated option: soft_cursor
I20230824 14:53:16.609988 23328 engine.cc:124] updated option: __synced
I20230824 14:53:57.260182  6068 engine.cc:93] engine disposed.
```
你的 Info 文件中结尾是这样的信息，而在使用上文提到的`语法插件`时在`starting engine`的过程中调用某些 Lua 就会导致 rime 毫无征兆地崩溃。

你可以尝试在桌面复制文件，然后再将其删除，几轮操作后可以促使 rime 进入`engine disposed.`状态，此时你再尝试输入，rime 就会进入`starting engine`状态，如果 weasel 成功触发崩溃，说明你遇到的问题与我一致。你需要关闭所有 Lua 或者禁用`语法插件`才能修复这个问题。

**Comment by abcdefg233** [comment]
另外，你似乎删除了雾凇的`custom_phrase_double`文件，把他找回来看看。

**Comment by a823002162** [comment]
> 

非常感谢您的建议,我逐一去确认了下我的配置,结果如下:
## 1. 你是否启用了语法插件：grammar和contextual_suggestion？
### reply: 
下面是我的方案的补丁文件,已启用的lua脚本有这些,并没有grammar和contextual_suggestion
[double_pinyin_flypy.schema.txt](https://github.com/rime/weasel/files/12494051/double_pinyin_flypy.schema.txt)
```
# 输入引擎
engine:
  processors:
    - lua_processor@select_character      # 以词定字
  translators:
    - lua_translator@date_translator      # 时间、日期、星期
    - lua_translator@unicode              # Unicode
    - lua_translator@number_translator    # 数字、金额大写
  filters:
    - lua_filter@autocap_filter           # 英文自动大写
    - lua_filter@reduce_english_filter    # 降低部分英语单词在候选项的位置
```

## 2.你可以尝试在桌面复制文件，然后再将其删除，几轮操作后可以促使 rime 进入engine disposed.状态，此时你再尝试输入，rime 就会进入starting engine状态，如果 weasel 成功触发崩溃，说明你遇到的问题与我一致。你需要关闭所有 Lua 或者禁用语法插件才能修复这个问题。
### reply:  
您指的是这样的复制删除的操作吗,没有出现weasel崩溃的问题,可能是因为前两天我因为weasel不能全局统一输入状态的问题而切换了这个构建版本的weasel基于0.14.3.0 https://github.com/rime/weasel/pull/856
![capture20230901112655](https://github.com/rime/weasel/assets/39456045/a8952c4e-1893-4cef-810f-11615ec200e0)

## 3.另外，你似乎删除了雾凇的custom_phrase_double文件，把他找回来看看。
### reply: 
我特意去翻了下雾凇方案的仓库里面的文件,似乎也没有找到您所说的这个custom_phrase_double,但是我有看到有一个这样的文件custom_phrase.txt,所以我是不是应该将custom_phrase.txt这个文件重命名为custom_phrase_double.txt
而且我发现在我现在使用的方案的补丁里面有一个这样的注释,似乎也印证了我上面的想法
![image](https://github.com/rime/weasel/assets/39456045/015eac68-a5e7-4b48-b57e-c2d071e737d6)
![image](https://github.com/rime/weasel/assets/39456045/9bb79fef-dcfd-4f4b-bd57-3196555a6fff)

以上就是我这边目前能提供的所有的信息,感谢

**Comment by C-Hermit** [comment]
我也是这样，这个问题怎么解决？

**Comment by a823002162** [comment]
> 我也是这样，这个问题怎么解决？

可以先尝试现将补丁文件里面启用的lua脚本全部禁用掉,或者可以降级到0.14.3.0版本
我暂时没有禁用lua脚本,但是我降级了之后最近没有再出现类似的问题

**Comment by C-Hermit** [comment]
> > 我也是这样，这个问题怎么解决？
> 
> 可以先尝试现将补丁文件里面启用的lua脚本全部禁用掉,或者可以降级到0.14.3.0版本 我暂时没有禁用lua脚本,但是我降级了之后最近没有再出现类似的问题
怎么禁用补丁文件里面启用的lua脚本?

**Comment by C-Hermit** [comment]
> > 我也是这样，这个问题怎么解决？
> 
> 可以先尝试现将补丁文件里面启用的lua脚本全部禁用掉,或者可以降级到0.14.3.0版本 我暂时没有禁用lua脚本,但是我降级了之后最近没有再出现类似的问题

怎么禁用掉补丁文件里面启用的lua脚本

**Comment by vectorstone** [comment]
> > > 我也是这样，这个问题怎么解决？
> > 
> > 
> > 可以先尝试现将补丁文件里面启用的lua脚本全部禁用掉,或者可以降级到0.14.3.0版本 我暂时没有禁用lua脚本,但是我降级了之后最近没有再出现类似的问题
> 
> 怎么禁用掉补丁文件里面启用的lua脚本

直接注释掉就好了,像下面这样
在你使用的方案*.schema.yaml文件下的engine下,把所有的lua_开它的都注释掉
(translator下的spelling_hints)也需要注释掉
![image](https://github.com/rime/weasel/assets/39456045/7ffa048b-2f37-4bcb-9f18-f7bfe046bbd2)
