### ISSUE TITLE
在魔兽世界中, 使用小狼毫会导致按键输入部分丢失.

### ISSUE THREAD

**Issue by yuiwong** [rime/weasel#983]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: Windows 10 22H2 19045.3208
 - 小狼毫版本:   [7b371c0]

**描述遇到的问题**
在魔兽世界中, 会出现吞输入的情况.  如果缓慢输入, 小狼毫可以捕获全部输入内容.
候选框弹出位置也会出现错误.

使用 release中的0.15版本会锁定为只有英文输入, 
最新的action CI build可以输入中文, 但出现了上述问题.
PS: 测试时, inline_preedit皆为true

**复现步骤**
重现问题的步骤，如：
1. 打开乌龟服客户端wow.exe, 这是一个魔兽世界私服, 用的是较早版本的WOW.exe
2. 在聊天窗口任意输入一些文字.

测试如下:
输入内容:  '这是一个测试'

[video.mov](https://github.com/rime/weasel/assets/10131032/55db3218-cfd8-48b8-adef-9969359db136)

**Comment by 107295472** [comment]
游戏就别想了，都不到用

**Comment by Techince** [comment]
https://github.com/Techince/weasel_x64/releases/tag/weasel-0.15.1.0_x64
安装这个版本。然后进「System32」目录下将「weasel.dll」备份一下。用下面这个文件替换。
进入游戏，打几个字，能触发丢编码就行，别打太多。
退出游戏，进「%temp%」目录下找到生成的「TextServiceFramework.log.*」日志，将此日志发到此贴中，我看下是哪里出了问题。
[weasel.dll.zip](https://github.com/rime/weasel/files/12494284/weasel.dll.zip)

**Comment by Techince** [comment]
经别人测试，这个版本在魔兽世界中不会丢失编码。

**Comment by yuiwong** [comment]
抱歉, 回复晚了, 使用了一段时间后, 有了新的发现.
如果设置inline_preedit=true,  那么每次都会有输入丢失的情况, 且会导致游戏严重掉帧.
如果设置inline_preedit=false, 那么吞输入的情况只会出现在候选窗没出现的时候. 候选框出现后, 即便快速输入也没问题.

对MS IME不太熟悉, 目前猜测原因可能出现在 wow.exe调用IME <------> Rime响应IME事件 之间? 这样能解释掉帧问题.

晚些时候我会替换debug dll测试(这服排队严重, 等能登录就测试下).

**Comment by yuiwong** [comment]
测试了下, 0.15.1可以使用. 在开始输入时会有些许掉帧, 但不会吞字符, 使用体验大幅好转. 

感谢修复.

**Comment by Techince** [comment]
> 测试了下, 0.15.1可以使用. 在开始输入时会有些许掉帧, 但不会吞字符, 使用体验大幅好转.
> 
> 感谢修复.

想问一下，《魔兽世界》中的候选框不是游戏本身绘制的吗？如果是的话，这种绘制方式称为无UI模式，候选框绘制由游戏本手接手，以提高游戏的性能。

**Comment by yuiwong** [comment]
我猜测并不是, 因为候选框的配色和样式都是在小狼毫自定义的.

**Comment by Techince** [comment]
> 我猜测并不是, 因为候选框的配色和样式都是在小狼毫自定义的. 有些应用的候选框样式很简单, 那种应该是应用本身接手绘制的.
候选框的坐标正确吗？不会是在右下角位置吧？

**Comment by Techince** [comment]
> 我猜测并不是, 因为候选框的配色和样式都是在小狼毫自定义的. 有些应用的候选框样式很简单, 那种应该是应用本身接手绘制的.

候选框的坐标正确吗？有一位网友说是正常，另一位网友说是在屏幕右下角处。

**Comment by yuiwong** [comment]
坐标仍在右下角. °‿‿°

**Comment by Techince** [comment]
> 坐标仍在右下角. °‿‿° 需不需要我测试个log?

稍等一下，我再编译一个新的文件。这几天代码又变动了。

**Comment by Techince** [comment]
> 坐标仍在右下角. °‿‿° 需不需要我测试个log?

https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64
好了，你可以下载测试了。weasel.dll.test是带日志的输入法模块，将「System32\weasel.dll」备份一下，用带日志的模块替换。
安装包也更新了，两个文件可一并下载。
打开游戏前，输入法要先设置成别的输入法，进游戏中再切换到小狼毫，打两个字，将输入法切换成其它，然后退出游戏。
「%temp%\TextService*」可找到日志文件，发到这个链接下就可以了。
谢谢测试。

**Comment by yuiwong** [comment]
好的, 目前服务器排队3000+, 只能半夜登录再测试了. 一旦能测了, 我会以视频+log的形式发到这里.

**Comment by yuiwong** [comment]
刚刚测试了下, 但出了点问题. 并没有wow.exe的log文件输出.
首先排除dll问题, 以下图片是替换dll后, 其他应用正常输出的log文件.

![Capture](https://github.com/rime/weasel/assets/10131032/a29cd138-de6d-4a88-9d41-39634efef1f6)

但我反复测试了几次, 没有wow.exe的log文件, 具体原因不详.
以下是测试:

https://github.com/rime/weasel/assets/10131032/71dcd847-a61b-47a0-8342-25a3c8cb836c

**Comment by Techince** [comment]
> 刚刚测试了下, 但出了点问题. 并没有wow.exe的log文件输出. 首先排除dll问题, 以下图片是替换dll后, 其他应用正常输出的log文件.
> 
> ![Capture](https://user-images.githubusercontent.com/10131032/268353398-a29cd138-de6d-4a88-9d41-39634efef1f6.PNG)
> 
> 但我反复测试了几次, 没有wow.exe的log文件, 具体原因不详. 以下是测试:
> 
>  1.mp4

没有日志文件，一个可能性——《魔兽世界》不是64位程序，是32位程序。

**Comment by yuiwong** [comment]
刚刚用x32dbg.exe和x64dbg.exe分别测试了下. x32dbg可以正常导入, 可以确定为32位.
没log也不好排查, 还是就这样用吧, 不吞输入在体验上已经很好了.

**Comment by Techince** [comment]
> 刚刚用x32dbg.exe和x64dbg.exe分别测试了下. x32dbg可以正常导入, 可以确定为32位. 没log也不好排查, 还是就这样用吧, 不吞输入在体验上已经很好了.

估计换成64位版本，体验效果会更好一些。

**Comment by Techince** [comment]
> 刚刚用x32dbg.exe和x64dbg.exe分别测试了下. x32dbg可以正常导入, 可以确定为32位. 没log也不好排查, 还是就这样用吧, 不吞输入在体验上已经很好了.

试一下新版本，还是原来的链接，增加了关闭「光标跟随」可自由拖动候选框位置。

**Comment by Techince** [comment]
@yuiwong 目前已修复Win10下Wow的无UI模式，请下载试用。

**Comment by yuiwong** [comment]
> @yuiwong 目前已修复Win10下Wow的无UI模式，请下载试用。

抱歉抱歉又来晚了, 试了下新版本.

在配置没变的情况下, 以下为输入状态
![321321321](https://github.com/rime/weasel/assets/10131032/9f00d604-83c9-403a-a1ea-8925c2b22a94)

我又试了下别的输入框(插件里), 都可以正确识别位置. 
可以说很完美. 非常感谢.

**Comment by diablosin** [comment]
> > @yuiwong 目前已修复Win10下Wow的无UI模式，请下载试用。
> 
> 抱歉抱歉又来晚了, 试了下新版本(weasel-0.15.1.004-installer_x64.exe).
> 
> 在配置没变的情况下, 以下为输入状态 ![321321321](https://private-user-images.githubusercontent.com/10131032/289384832-9f00d604-83c9-403a-a1ea-8925c2b22a94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5OTc5NjksIm5iZiI6MTcwMzk5NzY2OSwicGF0aCI6Ii8xMDEzMTAzMi8yODkzODQ4MzItOWYwMGQ2MDQtODNjOS00MDNhLWExZWEtODkyNWMyYjIyYTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA0NDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMjAzMTc4Yjg5YzIyNzgxOTJhMWI3YzlhZGU5YWY0YWEzYjgzMWE0OGQ1ZDYwZWU1ZmM0MzVkY2ZiNGM5ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xK1t0RGqvZlhvFjjzIfSadNz4smiOZyFSYVFgEe8MRw)
> 
> 我又试了下别的输入框(插件里), 都可以正确识别位置. 可以说很完美. 非常感谢.

请问你是完全卸载先前安装的版本后，再安装新的包（weasel-0.15.1.004-installer_x64.exe）吗

**Comment by yuiwong** [comment]
@diablosin 
一开始不是的, 安装目录里同时有0.15.0和0.15.1. 
后来的某天系统启动后, 切换到小狼毫无法输入文字, 候选框也没有. 把两个都删掉, 再安装0.15.1就正常了.

**Comment by liang881011** [comment]
@Techince 你好，升级了0.17.4后这个问题又出现了，请问有办法解决吗？

@yuiwong 你好，请问你现在还是在用weasel-0.15.04-installer_x64.exe版本还是已经升级到0.17.4？

**Comment by Techince** [comment]
> [@Techince](https://github.com/Techince) 你好，升级了0.17.4后这个问题又出现了，请问有办法解决吗？
> 
> [@yuiwong](https://github.com/yuiwong) 你好，请问你现在还是在用weasel-0.15.04-installer_x64.exe版本还是已经升级到0.17.4？

具体原因是将官方版本中「WeaselTSF::OnTestKeyDown」里的「_UpdateComposition(pContext);」语句注释掉即可。在测试击键Down事件中执行合成更新，个别应用会丢弃那个合成会话的。

**Comment by liang881011** [comment]
> > [@Techince](https://github.com/Techince) 你好，升级了0.17.4后这个问题又出现了，请问有办法解决吗？
> > [@yuiwong](https://github.com/yuiwong) 你好，请问你现在还是在用weasel-0.15.04-installer_x64.exe版本还是已经升级到0.17.4？
> 
> 具体原因是将官方版本中「WeaselTSF::OnTestKeyDown」里的「_UpdateComposition(pContext);」语句注释掉即可。在测试击键Down事件中执行合成更新，个别应用会丢弃那个合成会话的。



感谢回复，因为是新手，有具体的操作流程吗？

**Comment by Techince** [comment]
> > > [@Techince](https://github.com/Techince) 你好，升级了0.17.4后这个问题又出现了，请问有办法解决吗？
> > > [@yuiwong](https://github.com/yuiwong) 你好，请问你现在还是在用weasel-0.15.04-installer_x64.exe版本还是已经升级到0.17.4？
> > 
> > 
> > 具体原因是将官方版本中「WeaselTSF::OnTestKeyDown」里的「_UpdateComposition(pContext);」语句注释掉即可。在测试击键Down事件中执行合成更新，个别应用会丢弃那个合成会话的。
> 
> 感谢回复，因为是新手，有具体的操作流程吗？

需要编译源代码。具体步骤需要上网查，对新手来说，环境搭建比较复杂。

**Comment by fxliang** [comment]
可以考虑将部分应用的特例做成app_options， 在config 里传递给前端做特例处理，当然这些特例我几乎 没有遇到所以我就动不了了

**Comment by liang881011** [comment]
@Techince 尝试使用VS2022编译，但直接提示C1083错误，查找很久也没有发现那里出错。

最终还是放弃了，还是用回你这个0.15.1版本吧

**Comment by vincentchangcaoliu2018** [comment]
电脑开机 输入法首次启动 很慢 只能打英文
