### ISSUE TITLE
不支持 88f5a0c 及以后的 librime

### ISSUE THREAD

**Issue by mrhso** [rime/weasel#99]
虽然前端已经停止维护了，但是不能使用 librime 的话，我想总是一个严重问题。

**Comment by Prcuvu** [comment]
已确认。原来在我更改Windows DLL导出函数之前就已经不兼容了。
[rime/librime@88f5a0c](88f5a0cd9224cebf29bc5d5838f01a8106eb757a)使得custom.yaml打补丁的机制被废弃，造成了小狼毫的兼容性问题。

**Comment by mrhso** [comment]
等等，現有的補丁機制是怎麼様的？

**Comment by mrhso** [comment]
也就是説従合成文件変成直接読取 custom？

**Comment by Prcuvu** [comment]
> 也就是説従合成文件変成直接読取 custom？

对。原文件将不会被修改。

`rime_api`中的`deploy_config_file`函数因此死掉了。小狼毫应该就是这么出问题的。

**Comment by mrhso** [comment]
那麼得修改小狼毫関於那塊的地方了。

**Comment by mrhso** [comment]
其它前端也有波及，但是没有到無法使用這種厳重地歩。

**Comment by lotem** [comment]
@Prcuvu 
> rime_api中的deploy_config_file()函数因此死掉
怎麼理解？是返回 false 導致流程中斷嘛？

Tracking issue in librime: https://github.com/rime/librime/issues/164
