### ISSUE TITLE
版本0.15在win10 LTSC下office2021版打字还是会有后移的问题

### ISSUE THREAD

**Issue by Judefy** [rime/weasel#993]
ppt、word都正常，唯独office会出现后移情况。

**Comment by Techince** [comment]
https://github.com/Techince/weasel_x64/releases/tag/weasel-0.15.1.0_x64
来试用下我这个版本。已修复此问题。

**Comment by Judefy** [comment]
> https://github.com/Techince/weasel_x64/releases/tag/weasel-0.15.1.0_x64 来试用下我这个版本。已修复此问题。
 
你这个问题更多，候选框到处乱飘等

**Comment by Techince** [comment]
> > https://github.com/Techince/weasel_x64/releases/tag/weasel-0.15.1.0_x64 来试用下我这个版本。已修复此问题。
> 
> 你这个问题更多，候选框到处乱飘等

什么软件下会飘？我用的Office 2021测试，没问题呀

**Comment by Techince** [comment]
安装完成后，系统需要注销一下，输入法才会生效

**Comment by liangzhi52** [comment]
> 安装完成后，系统需要注销一下，输入法才会生效

确实修复了这个困扰多年的问题，厉害！
WPS中也正常了，候选框不再跟着光标后移了。

**Comment by liangzhi52** [comment]
> 安装完成后，系统需要注销一下，输入法才会生效

### **一、成功的地方**
确实解决了候选框跟随光标的问题

### **二、小bug**
（一）中文状态下，不支持 **shift** 将已经打出的英文字符上屏 （我使用其他版本正常）
（二）英文切换为中文的后，立即输入中文。此时的中文候选框跟光标附近的输入法中文状态提示（就是那个【中】字）重合，且【中】字覆盖在候选框上面。（其他版本的，只要开始输入中文，【中】字立即看不到了，不会产生覆盖的情况）

**Comment by flyAlfanso** [comment]
![图片](https://github.com/rime/weasel/assets/98010886/7e50bd8d-0678-455f-a2a3-22d850a2ff29)

**Comment by flyAlfanso** [comment]
> https://github.com/Techince/weasel_x64/releases/tag/weasel-0.15.1.0_x64 来试用下我这个版本。已修复此问题。

![图片](https://github.com/rime/weasel/assets/98010886/27bdbe5e-d515-4606-a1e3-c3f73edee971)
在word中输入时，出现这种情况的回车符号后移能够解决嘛？

**Comment by Techince** [comment]
> > https://github.com/Techince/weasel_x64/releases/tag/weasel-0.15.1.0_x64 来试用下我这个版本。已修复此问题。
> 
> ![图片](https://private-user-images.githubusercontent.com/98010886/292127068-27bdbe5e-d515-4606-a1e3-c3f73edee971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTg0MzksIm5iZiI6MTcwMzE1ODEzOSwicGF0aCI6Ii85ODAxMDg4Ni8yOTIxMjcwNjgtMjdiZGJlNWUtZDUxNS00NjA2LWExZTMtYzNmNzNlZGVlOTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDExMjg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YzI2NWEzYzA2NmY0ZTg3ZjcyZTliOWE5ZDM0YWZkYjQxZTg4ZjA3ZWNmMWRkYWI1NzhhNjllMDBhODQ0YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2zNKsA-3o3DBCKsKGfztNximO7UdWia9DPx4nVlTI_Q) 在word中输入时，出现这种情况的回车符号后移能够解决嘛？

那个插入的是哑字符空格，没有它的话，非嵌入式候选框获取不到焦点坐标。
可以使用inline_preedit: true风格的候选框。

**Comment by flyAlfanso** [comment]
多谢大佬
