### ISSUE TITLE
更新显卡驱动后输入框无任何文字，需重启当前应用才能显示。

### ISSUE THREAD

**Issue by haphap** [rime/weasel#994]
**上报前请检查**
- [ ] 我遇到的问题没有其他人在 issue 里提到过
- [ ] 我的小狼毫版本于 rime/weasel 下载
- [ ] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: [ 运行 winver.exe 获取，如 Windows 11 22H2 22621.2215]
 - 小狼毫版本: [ 如 0.15.0.0 ， CI 构建版请附短 commit hash ，如 372c9c ]

**描述遇到的问题**
更新显卡驱动后输入框无任何文字，需重启当前应用才能显示。

**复现步骤**
重现问题的步骤，如：
1. 更新显卡驱动；
2. 在已经启动的应用中输入任意汉字
3. 无任何文字

**预期行为**
简短地描述你预期小狼毫怎么反馈

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**
<img width="332" alt="屏幕截图 2023-09-01 135731" src="https://github.com/rime/weasel/assets/884398/f2ba2b1f-53dd-49b0-bbc2-6b72a121061f">

**其他补充说明**

如果有其他补充说明，可以写在这里

**Comment by Techince** [comment]
这个需要重启下系统才会生效吧

**Comment by haphap** [comment]
不需要。你看我的问题，需要重启应用才能有字。发自我的 iPhone在 2023年9月1日，下午6:59，Techince ***@***.***> 写道：﻿
这个需要重启下系统才会生效吧

**Comment by fxliang** [comment]
其实重新切换进入小狼毫应该也是可以的。因为使用的是direct2d相关的一些接口，显卡驱动更新有可能会引入影响的。

**Comment by fxliang** [comment]
https://github.com/fxliang/weasel/actions/runs/6092119298
可以看看这个，目前我在观望中，看用久一点看是不是之前那个偶发的文字绘制无效的问题修复了。

**Comment by kabylake2** [comment]
same problem
![Screenshot (1)](https://github.com/rime/weasel/assets/34359020/42aa3988-5bc1-4129-b1b7-3dd43c69cb91)

**Comment by fxliang** [comment]
> same problem ![Screenshot (1)](https://user-images.githubusercontent.com/34359020/268169740-42aa3988-5bc1-4129-b1b7-3dd43c69cb91.png)

是使用了我那个试验分支的产出之后还有吗？

**Comment by haphap** [comment]
使用试验分支后，情况已经大为好转，不会影响正常使用：更新显卡驱动后第一时间仍会出现无文字现象，但切换其他应用再回到当前应用输入窗口能够恢复正常。

**Comment by fxliang** [comment]
> 使用试验分支后，情况已经大为好转，不会影响正常使用：更新显卡驱动后第一时间仍会出现无文字现象，但切换其他应用再回到当前应用输入窗口能够恢复正常。

哪个commit的？

**Comment by haphap** [comment]
这个版本：https://github.com/fxliang/weasel/actions/runs/6092119298发自我的 iPhone在 2023年9月23日，下午12:27，fxliang ***@***.***> 写道：﻿

使用试验分支后，情况已经大为好转，不会影响正常使用：更新显卡驱动后第一时间仍会出现无文字现象，但切换其他应用再回到当前应用输入窗口能够恢复正常。

哪个commit的？

**Comment by fxliang** [comment]
试下更新一点的ci，后面有增加一点东西https://github.com/fxliang/weasel/actions/runs/6272290925

**Comment by haphap** [comment]
已经使用了最新CI（https://github.com/fxliang/weasel/actions/runs/6447165871），更新显卡驱动后，Chrome、notepad等输入字符仍会出现输入框无文字现象，wechat似乎不受影响，将无文字应用切换到wechat再切回能够恢复正常。

**Comment by fxliang** [comment]
要tf2分支的最新ci，这个也是我自己在用的

其他分支有些是我将tf2上的东西拆开用来pr的。你用这个是只在master上只修了那个hilite_space的事项

**Comment by haphap** [comment]
使用tf2分支进行了测试，问题已经完全解决，感谢大佬！
